### ISSUE TITLE
Make sure PVC is working in dev environment

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#10017]
If we create the PVC with `spec.storageClassName=""`, the Kubernetes will search the storage class name "" rather than using the default storage class (which is local-path) in the cluster, ref to https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume.

We should update the code then to not set storageClassName in that case. As that would be what users in self hosted would probably do as well, do not set (keep empty) storage class to use default one.

**Comment by sagor999** [comment]
Depends on this being merged first: https://github.com/gitpod-io/gitpod/pull/9475

**Comment by jenting** [comment]
I'd like to handle this one @sagor999 
May I assign it to me?

**Comment by sagor999** [comment]
@jenting assigned you. Thank you! :heart:

**Comment by jenting** [comment]
The current code, creating the PVC uses the "default" storageClass (which is empty) in ws-manager config.

According to https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume, if we create the PVC with spec.storageClassName="", the Kubernetes will search the storage class name "" rather than using the default storage class in the cluster.

```go
        PVCConfig := m.Config.WorkspaceClasses[config.DefaultWorkspaceClass].PVC
	if startContext.Class != nil {
		PVCConfig = startContext.Class.PVC
	}
	storageClassName := PVCConfig.StorageClass

	PVC := &corev1.PersistentVolumeClaim{
		ObjectMeta: metav1.ObjectMeta{
			Name:      fmt.Sprintf("%s-%s", prefix, req.Id),
			Namespace: m.Config.Namespace,
		},
		Spec: corev1.PersistentVolumeClaimSpec{
			AccessModes:      []corev1.PersistentVolumeAccessMode{corev1.ReadWriteOnce},
			StorageClassName: &storageClassName,
			Resources: corev1.ResourceRequirements{
				Requests: corev1.ResourceList{
					corev1.ResourceName(corev1.ResourceStorage): PVCConfig.Size,
				},
			},
		},
	}
```

Therefore, we could either update the ws-manager config, "default" storageClass to `local-path` _or_ we could check if the "default" storageClass is empty, do not set the PVC spec.storageClassName.

**Comment by jenting** [comment]
> I will create a separate issue for this and submit a fix once VolumeSnapshot support PR will get merged.

I think we could use this issue to track.
