### ISSUE TITLE
TOML Support

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#102]
We could possibly leverage configuration and LS from
https://github.com/bungcip/better-toml

**Comment by jankeromnes** [comment]
Great idea! @akosyakov do you think we could install it as a VSCode extension in Gitpod's Theia, or would it be more practical to steal/import its configuration and language server directly?

**Comment by akosyakov** [comment]
Right now there is no way to install VS Code extensions in Gitpod. We could start by trying out support of better-toml with pure Theia and raise issues for missing APIs and metadata support.

In order to try with local Theia:
- download vsix file for an extension to some folder
- point THEIA_DEFAULT_PLUGINS env variable to this folder, like export `THEIA_DEFAULT_PLUGINS=local-dir:///myplugins_folder`
- start Theia app with plugin-ext and plugin-ext-vscode extensions installed

You can try it with Gitpod using the browser app from Theia repo.

**Comment by jankeromnes** [comment]
Thanks @akosyakov. I'll soon try using the TOML VSCode extension in Theia directly, and file any bugs I encounter.

@svenefftinge In the short term, TOML is very close to INI, which Theia already supports. Do you think it's possible to somehow coerce Gitpod into syntax-highlighting TOML as INI? It would look like this:

<img width="1138" alt="screenshot 2019-01-10 at 16 09 20" src="https://user-images.githubusercontent.com/599268/50977281-3ed07200-14f2-11e9-85a1-09f12702e2f4.png">

**Comment by jankeromnes** [comment]
I extended Theia's INI grammar to include `.properties` and `.toml` files in https://github.com/theia-ide/theia/pull/4015.

This should make TOML support good enough until we can use the VSCode extension with its language server.

**Comment by svenefftinge** [comment]
Great, than lets close this issue.

**Comment by jankeromnes** [comment]
Having the language server you mentioned would be great as well, but I agree that it can wait that VSCode extensions are well supported.
