### ISSUE TITLE
Epic: Github CodeSpace + Copilot

### ISSUE THREAD

**Issue by ionutale** [gitpod-io/gitpod#10242]
### Summary

this summer GitHub will release copilot GA and maybe code spaces. I firmly believe that those who will use code-spaces, will have copilot auto installed. This will give GitHub a massive advantage over you GitPod.

since as a platform, I like GitPod more, I was worried.
And my questions are: 

- how will GidPod compete with codespaces? 
- do you have a plan to build your own code assistant?

### Context

this summer GitHub will release copilot GA and maybe code spaces. I firmly believe that those who will use code-spaces, will have copilot auto-installed. This will give GitHub a massive advantage over you GitPod.

since as a platform, I like GitPod more, I was worried.

### Value

better product overall

### Acceptance Criteria

have a auto installed code assistant

### Measurement

not sure about this one

**Comment by davemecha** [comment]
I really love working with Gitpod. But it's getting more and more annoying that there is no access to GitHub Copilot. I'm using paid Tabnine for a year now as an alternative. But it doesn't improve well and suggestions are ok but I would like to have better support.

To work with local vscode is no option. I want to have multiple workspaces open at the same time. Sometimes on the same project sometimes on different projects. I run into port conflicts if I work locally.

I tried to reach out to Github to allow Gitpod, but I didn't even get an answer. But maybe you as a company are more powerful, if you get into a conversation. They already know you because you sent them a cake. 😉

I'm already finding myself looking around for alternatives to get first class AI support. But I really want to stay with Gitpod. You are a German company and you have a great product. Please help us. 🙏
