### ISSUE TITLE
Clean up User Page within Admin Dashboard

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10247]
**Context:**
The information shown about a user within the admin dashboard > user page is outdated and not relevant for a self-hosted user:
<img width="1113" alt="Screenshot 2022-05-25 at 18 53 03" src="https://user-images.githubusercontent.com/22516873/170318315-c21f90fe-4fa4-4caa-814a-805d4591263c.png">

**Desired Behaviour:**
- Let's make the admin dashboard work for both SaaS and Self-Hosted. The needs and use cases are likely different, so we need a way to selectively show information
- We only show information that is relevant to the self-hosted admin on this page. 
 - Things like User ID, name, when they joined Gitpod, how many workspaces (instances) they have and actions like blocking and deleting are relevant. 
 - Things like Remaining hours, the plan, feature flags, student are not relevant. 
- If we need this information for SaaS, we should find a way to keep it separate from our Self-Hosted users.

**Comment by geropl** [comment]
I agree with the goal (make admin pages useful for Self-Hosted users) but I feel SaaS has a legitimate need as well. 🙃 

I'd be even happier if we:
 - could shift the perspective from "not relevant" and "separate" to "how to selectively display data and options based on context (Self-Hosted + SaaS)"
 - frame this request (and others with a similar direction) in the wider context of "Make Admin Dashboard production ready" - because today, it frankly isn't: it's a tool to SaaS operations

If we did the later, we could also think about how we want split up responsibilities, so that each team can contribute, without interfering with others work/requirements. 🧘

**Comment by geropl** [comment]
FYI: There has been a [recent change](https://github.com/gitpod-io/gitpod/pull/12770) that effectively hides Chargebee/Stripe info + actions for Self-Hosted.
It's based on BillingMode, which is `none` for Self-Hosted (bad naming is my bad: should be called: `license` 🙈 ).

Does that help for now @lucasvaltl (cmp. [PR](https://github.com/gitpod-io/gitpod/pull/12770) for screeshots)

**Comment by geropl** [comment]
As Lucas is out: What you'll see in Self-Hosted now is this reduced set of properties+actions (only BillingMode will be "none" instead of "usage-based"):

![Image](https://user-images.githubusercontent.com/32448529/189851090-a30a84e6-1a1f-4489-b8e6-f22a2872d402.png)

I'm closing for now; we can always re-open later.

Fixed with: https://github.com/gitpod-io/gitpod/pull/12770
