### ISSUE TITLE
Improve documentation around workspace lifecycle and persistence guarantees

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#1031]
Form the documentation it is not immediately clear what the possible lifecycle states of a workspace are and what persistence guarantees are given between those. We never describe what is persisted during prebuilds, for instance.

**Comment by svdarren** [comment]
Related to [this question](https://community.gitpod.io/t/how-to-save-loadtime-with-npm-installs-overlap-between-gitpod-yml-and-dockerfile/198)...

- What should go in the dockerfile vs the yml?
- What portions are executed for prebuild vs interactive?
- What portions are restored?

**Comment by davidar** [comment]
This bit me, everything was working fine until prebuilds were automatically enabled by installing the github app, and initialisation suddenly stopped working properly. It's rather confusing given that prebuilds are described as if they're just caching what usually happens when you start a workspace, whereas in reality the behaviour is quite different when they're enabled.

**Comment by jankeromnes** [comment]
@davidar That's an excellent point, sorry for the bad surprise there.

On the upside, the Full Workspace Backup feature will be made stable next quarter (beginning in two weeks), which means that _every file_ in your workspaces will be backed up (in both prebuilt and non-prebuilt workpaces), not just what's in `/workspace`.

I think this will solve a lot of headaches!

**Comment by geropl** [comment]
Re-opened because IMO this is one of the most-important bugs with Gitpod.io :upside_down_face:

**Comment by astrojuanlu** [comment]
Naughty bot marking "one of the most-important bugs with Gitpod.io 🙃" as stale, grumpy subscriber leaving an annoying comment to revert ;)
