### ISSUE TITLE
Setup usage datastore and store usage

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#10323]
Depends on https://github.com/gitpod-io/gitpod/issues/10320

We want to start persisting our usage report such that it can be viewed and queried quickly (from the Public API, and dashboard). In this task, we're defining the datastore and persisting the report into it.

* [x] Create table to store usage data (https://github.com/gitpod-io/gitpod/pull/11311)
* [x] Persist data on every reconcilation run (https://github.com/gitpod-io/gitpod/pull/11343)
  * [x] Populate `creditsUsed` columns (https://github.com/gitpod-io/gitpod/pull/11406)

**Comment by andrew-farries** [comment]
We decided:

1. Store usage data in a new table in the existing db, called `workspace_instance_usage` or similar. This will have fields: `instanceId`, `attributionId`, `startTime`, `stopTime`, `creditsUsed` and some kind of `generationId` to show the last report in which the instance appeared.

2. Separately, we would also like to persist the raw usage report (as json), possibly using `content-service` so that we have an audit trail. The `generationId` field in the usage table could then be a link to this report.

**Comment by geropl** [comment]
That sounds good to me. I'm not sure we need 2. (the document store), though, but happy to learn about the motivation once we ticked 1.

Regarding the schema: I did not check all fields, but even given a `generationId`, a `generationTimestamp` or so would greatly help with debugging, at the very least.
