### ISSUE TITLE
Show usage details in usage view

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#10328]
> The usage view needs to show the details about who did run what workspace when, so that when in doubt users understand where and why the cost has been created.

> Also such a view provides teams a great insight of how Gitpod is used and adopted within their team.

Note: The usage view should also be available when there is no billing configured, e.g. to see personal usage against your free credit, or to see self-hosted team usage.

- [x] #11257
- [x] Update components with real API
- [x] #11285

**Comment by jankeromnes** [comment]
Thought: We can show raw usage per Project, per User or per Team. Which one do we want here?

I guess we'll want per User first (for the skateboard). Later, we can also show per Team (once we have delegated billing). Per Project could also be interesting, but I'd leave it out of scope for now.

**Comment by easyCZ** [comment]
Excellent observation. I'd say go for the simplest one initially and we cut additional tickets for the subsequent ones.

**Comment by jankeromnes** [comment]
FYI, sharing an exciting early draft concept from @gtsiolis of what the Usage UI could eventually look like:

<img width="821" alt="Screenshot 2022-06-24 at 16 21 51" src="https://user-images.githubusercontent.com/599268/175555635-683f3556-87a6-4ea5-8429-74bd1cbb9151.png">

(I guess it's sort of off-topic here, since this issue calls for just showing "raw" usage data, but I think it's still helpful to give an idea of approximately what we'll want to show eventually. 💭)

**Comment by svenefftinge** [comment]
The draft is more like an invoice with aggregated usage. The usage view needs to show the details about who did run what workspace when, so that when in doubt users understand where and why the cost has been created.
Also such a view provides teams a great insight of how Gitpod is used and adopted within their team.

I see this as a first skateboard towards full blown Usage analytics, where teams can also get metrics that help understand how the team is spending it's time on top of this data.

In that light, let's remove the billing bits from the usage (besides the number of used credits) and show the list of sessions where for each session we show:
 - workspace id
 - user (shows `prebuild` when it's a prebuild, as 'user' is not relevant here)
 - project/repo
 - Start (absolute time stamp to the minute)
 - Duration
 - Credits
 - (optional) session id (workspace instance id) - to easily reference a session

FWIW I don't believe we need to make a decision if we start with user's usage or team's usage as both views would be more or less the same. In case I missed something it is clearly team usage that would have the priority IMO.

**Comment by jldec** [comment]
If we have the usage data and APIs available to show a paginated list with details for all workspace instances (including prebuilds) sorted most recent first, that would be 🥇.

@gtsiolis could we see a design for a detailed list view including the session details listed above?

**Comment by laushinka** [comment]
We can close this as all tasks have been completed.
There will still be more iterations on the UI - this will be tackled in follow-up issues.
