### ISSUE TITLE
configure Installer to set multiple pull secrets in image-builder-mk3

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#10397]
Amend the `image-builder-mk3` configmap to reflect the new config for `pullSecrets`. This will require two values - the existing pull secret for the container registry and the `imagePullSecret`

**Comment by MrSimonEmms** [comment]
Removing staleness

**Comment by kylos101** [comment]
:wave: @MrSimonEmms can you check the description? The # referenced (10397) indicates this depends on itself. 

Also, do we have a workaround for this now in KOTS? I assume [this](https://github.com/gitpod-io/gitpod/pull/10685) is a workaround. In other words, do we have any users who cannot install Gitpod because of this issue, or are they okay because of the above PR?

I agree the product should be fixed long term so a workaround isn't needed. :+1:

**Comment by MrSimonEmms** [comment]
@kylos101 good spot. I think that's an old comment, so I've removed it.
