### ISSUE TITLE
Use stable value for rabbitmq-erlang-cookie

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/gitpod#10459]
The Installer is currently generating a random string for the rabbitmq-erlang-cookie secret ([source](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/rabbitmq/secret.go#L25)) for every invocation of the Installer which is the source of drift in ArgoCD for us. We've worked around it by telling ArgoCD to ignore the secret when producing diffs, but is there any way we could make it stable between invocations so our customers don't have to do the same workaround?

Internal discussion [here](https://gitpod.slack.com/archives/C01KLC56NP7/p1654248658232499)

**Comment by MrSimonEmms** [comment]
There are two approaches I can see to this (additional options welcome). Neither is a clear-cut winner, so a discussion on the ramifications is good.

## Option 1 - hard-code the cookie value

As done for the [in-cluster database password](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/database/incluster/secret.go#L26), we could hard-code this value. This resource is not exposed to the internet so should be low-risk.

### Pros

- Quick
- Low-risk

### Cons

 - Very hacky
 - Doesn't look great on us

## Option 2 - add post-processing to KOTS

Could add some post-processing to the KOTS Installer. Something akin to:
1. Does `rabbitmq-erlang-cookie` secret exist?
2. If yes, get the value from secret and change the value in the generated `gitpod.yaml` before applying (including the annotation)

### Pros

 - Neater
 - Nearly as quick as option 1

### Cons

 - Not supported by Installer (@mads-hartmann's ArgoCD post-processing would need to remain)
 - Ideally, we don't want to be putting in KOTS-specific post-processing. It sets a bit of a precedent and these might then be missed for Installer-only deployments

## Honourable mention - do it in the Installer

We've tried to keep the Installer as disconnected from existing deployments. The thinking behind this was to remove the dependency on a real cluster so that rendering of the YAML can be isolated from a concrete instance. We did originally talk of using the Installer to be able to retain secret values natively between runs, but that's never been investigated. Conceivably, this could be done but it's a wider-ranging change than covered in this ticket. It would also probably be bigger than we'd want to commit to yet.

cc @gitpod-io/engineering-self-hosted @gitpod-io/engineering-webapp

**Comment by corneliusludmann** [comment]
What about this:

## Option 3 - allow configuring an existing secret

Currently, the installer creates a secret. In other places, we let users specify an existing secret in the config that is used by Gitpod. What about when we give users the option to configure an existing secret with the password and when this configuration is given, no new secret is created but the existing is used. When the config is missing, we keep the current behavior.

With this, we don't have to work with credentials in the config, don't need post-processing, and also have way to prevent randomly generated passwords for each run.

This also means we need a verification action when this config is given that checks if the secret is there.

**Comment by csweichel** [comment]
It's unlikely users actually care about this value. The Erlang Cookie is only relevant for setting up a cluster of rabitmq nodes, something we don't support today. Because RabitMQ is not exposed outside the cluster anywhere, one would need access to the cluster to make use of this value. 

I'd vote for Option 1, with a path towards Option 3 once there's customer need for it.

**Comment by MrSimonEmms** [comment]
@mads-hartmann can you link through to the ArgoCD post-processing that you do please? I had a play with it this morning and it keeps restarting my `messagebus-0` pods

**Comment by mads-hartmann** [comment]
@MrSimonEmms We're relying on an ArgoCD feature that allows ArgoCD to ignore a specific diff. See example [here](https://github.com/gitpod-io/ops/blob/2edcae09d9370a5e7422ecc4b5bc40b892ff4c70/deploy/production/meta-eu02/argocd/gitpod-webapp.yaml#L36-L41) and the [docs here](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/). I'm not 100% sure, but I was assuming this is only a "don't consider it out of sync" feature and that it does actually apply the new secret.
