### ISSUE TITLE
GitPod not pushing and cannot be accessed

### ISSUE THREAD

**Issue by RossComputerGuy** [gitpod-io/gitpod#1061]
**Describe the bug**
I was trying to push a commit and got an error saying that the device or address for GitHub does not exist. I refreshed and then got a 500 error, I tried taking screenshots for both but the Chromebook reported that it failed to take a screenshot.

**To Reproduce**
I dunno how to reproduce this, I guess use a Chromebook and try pushing while the battery is low.

**Expected behavior**
The commits to be pushed and for the website to load

**Comment by JesterOrNot** [comment]
@RossComputerGuy were you pushing to a closed fork?

**Comment by RossComputerGuy** [comment]
No, it was a repo I own. It said I didn't have permission to push to the repo but I already granted access to it then I tried again and got the device or address does not exist error. Then I refreshed and got a 500 error.

**Comment by jankeromnes** [comment]
Hi @RossComputerGuy, thank you for reporting this issue. I don't think this can be related to your Chromebook's battery state, because "device or address for GitHub does not exist" sounds like a DNS problem (e.g. maybe Gitpod temporarily couldn't reach GitHub?), and Error 500 sounds like an internal server problem (either in Gitpod or in GitHub -- these happen occasionally, but should be extremely rare).

If this happens again, please update this issue. Also, if you can't take screenshots with your Chromebook, please try to take a picture of your Chromebook screen with your phone. Seeing your screen would help a lot, because it can provide many subtle clues as to what went wrong.

**Comment by RossComputerGuy** [comment]
![image](https://user-images.githubusercontent.com/19699320/72638138-a1cfc280-3917-11ea-905c-78694a1807d3.png)
I was able to get the issue to occur again
