### ISSUE TITLE
Add a way to open git project page from IDE

### ISSUE THREAD

**Issue by ashwin-vbs** [gitpod-io/gitpod#10615]
In the web IDE, there should be a command palette entry or some UI element (like an entry in menu or button in status bar) to navigate to the github or gitlab project that is being currently edited.

For example, there is a "Gitpod" button in [https://github.com/gitpod-io/gitpod](https://github.com/gitpod-io/gitpod) project page. Clicking this creates a workspace in Gitpod server and opens an IDE for this workspace.
There should be a command or button in this IDE, which when activated, opens [https://github.com/gitpod-io/gitpod](https://github.com/gitpod-io/gitpod) in a new browser tab.

**Comment by loujaybee** [comment]
Hey Ashwin, since you mentioned the "web IDE" I guess we're talking about VS Code in the browser. 

In Gitpod, this is called a context (https://www.gitpod.io/docs/context-urls). 

You can access via the command palette, or via the menu bar on the right hand side. 

|In the side bar|In the command palette|
|-|-|
|![image](https://user-images.githubusercontent.com/5528307/173327319-86ade55c-11e6-45b7-9f19-613cb767094a.png)|![image](https://user-images.githubusercontent.com/5528307/173327356-90f1f228-62bd-4486-9380-5bf42872c0e0.png)|

Does that give you what you need? If not, feel free to re-open the issue!
