### ISSUE TITLE
[ws-manager] "last backup failed: no running ws-daemon pod found."

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#10682]
### Bug description

A user lost his changes of a session and the status of the instance in the DB shows the error:
```
"last backup failed: no running ws-daemon pod found.
```

This seems to be a single case as I couldn't find other instances in that time with a similar error message.

### Workspace affected

instanceid: e3c9d5ff-4492-464e-96fc-2cba13e31d45

[Logs for the last seven days](https://cloudlogging.app.goo.gl/KVDSJu1L5MRBRfZz5) (internal link)

**Comment by jenting** [comment]
This is because the ws-daemon temporarily unreachable (probably due to restart), and the ws-manager doesn't not handling this with retry.
- https://github.com/gitpod-io/gitpod/blob/6afe081713ae99453d4cfac843ddf85d4afbd327/components/ws-manager/pkg/manager/monitor.go#L615-L618
- https://github.com/gitpod-io/gitpod/blob/6afe081713ae99453d4cfac843ddf85d4afbd327/components/ws-manager/pkg/manager/monitor.go#L798-L802 and https://github.com/gitpod-io/gitpod/blob/6afe081713ae99453d4cfac843ddf85d4afbd327/components/ws-manager/pkg/manager/monitor.go#L809-L810
- https://github.com/gitpod-io/gitpod/blob/6afe081713ae99453d4cfac843ddf85d4afbd327/components/ws-manager/pkg/manager/monitor.go#L1001-L1004 and https://github.com/gitpod-io/gitpod/blob/6afe081713ae99453d4cfac843ddf85d4afbd327/components/ws-manager/pkg/manager/monitor.go#L1209-L1211

**Comment by kylos101** [comment]
Removing from scheduled groundwork, PVC will resolve this for the saas, there are no reports that this is happening for self-hosted.
