### ISSUE TITLE
cannot initialize workspace: no space left on device

### ISSUE THREAD

**Issue by lesichkovm** [gitpod-io/gitpod#1071]
**Describe the bug**
 cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/f4de3c6e-57c4-410b-b77d-0787d0fb8c2a: no space left on device
Please file an issue if you think this is a bug.

**To Reproduce**
Not sure how. The repo is very small. Few HTML files only

**Expected behavior**
Open the environment

**Additional Information**
This is all seen:  cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/f4de3c6e-57c4-410b-b77d-0787d0fb8c2a: no space left on device
Please file an issue if you think this is a bug.

**Comment by thomas-worm-fernuni** [comment]
It is now working again.

**Comment by jankeromnes** [comment]
@lesichkovm Thank you for reporting this issue! And we're very sorry for the bad experience.

We indeed received a monitor alert 3 hours ago: one server in our Europe West 1 cluster suddenly started filling up 100% of its disk. We're not sure why, but we were able to jump into this server and recover most of the disk space about 1 hour later.

We're now trying to understand what happened, in order to prevent it from happening again in the future.

**Comment by Hanksha** [comment]
This is happening to me right now.
<img width="652" alt="Screen Shot 2020-02-06 at 8 11 22 PM" src="https://user-images.githubusercontent.com/6960133/73936152-24e3a780-491d-11ea-9b30-e2095ecc303a.png">

**Comment by JesterOrNot** [comment]
Seems this has happened again :(

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.
