### ISSUE TITLE
[self-hosted] Add officially support service type `ClusterIP` for proxy

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#10725]
With #10537, we support setting the service type of the proxy via an experimental config option in the installer. We see, that we need to support this officially ([internal discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1655462991148249)).

For official support, we need:
- [x] #10983
- [x] #11025
- [x] #11008
- [x] #11009
- [x] #11011
- [x] #11033

**Comment by szab100** [comment]
@corneliusludmann @lucasvaltl When implementing this, please move adding these two hard-coded annotations to inside the IF(type == LB) {..} stmt above. These should only be used when 'proxy' is a load-balancer. When it's NodePort or ClusterIP, the 'external-dns' annotation on 'proxy' interferes with the ingress load-balancer that can also be using this annotation with same host values, creating a conflict in the external dns system, causing the LB to be unreachable.

**Comment by mrzarquon** [comment]
@MrSimonEmms if this setting moves from experimental to main, we should still honor the setting if it's in experimental and flag it with a deprecation warning. otherwise people who had clusterip working in 2022.6 will have it stop working in 2022.7 if they don't update the config (and since it's not easy to download / update the config in the replicated UI, there's no way for them to know)

**Comment by MrSimonEmms** [comment]
Yes, we still honour the `experimental` setting and will do until December release https://github.com/gitpod-io/gitpod/issues/11124

**Comment by mrzarquon** [comment]
gitpod-installer parses config, outputs to a assessment.log, troubleshoot.sh analyzer checks for "has_deprecated_experimental_feature" and reports it?
