### ISSUE TITLE
IDE selection modal window not fiting in screen

### ISSUE THREAD

**Issue by FabienTregan** [gitpod-io/gitpod#10747]
### Bug description

After first login, you are shown a modal windows to select you IDE.
On low resolution screen (mine is 1366x768), the window does not fit in screen, there is no scrollbar and you don't even know there is a button that must be clicked (which is outside the screen)

![image](https://user-images.githubusercontent.com/2663407/174451667-a6b7ca71-49a4-4063-be25-502a22f2998e.png)

### Steps to reproduce

have a low resolution screen
register account
log in

### Expected behavior

the windows fits in screen or there is a scrollbar

**Comment by geropl** [comment]
@gtsiolis pinging you for awareness. I feel it would be nice to have a general solution for all our pages - even if it's suboptimal, e.g. like adding a scrollbar.

**Comment by gtsiolis** [comment]
Thanks for noticing, @FabienTregan! 👀 

:a: Using a scrollbar area in the modal would be great and has been needed in the past, see https://github.com/gitpod-io/gitpod/issues/3829. Sounds also like a good [skateboard](https://www.notion.so/gitpod/f7f54cb1c69643e9ac42c9f2ddd9e46f) and boring (simple) solution, towards improving the overall responsive design of the dashboard (https://github.com/gitpod-io/gitpod/issues/4050). 🛹  

:b: [FYI](https://en.wikipedia.org/wiki/FYI), In the future, I'd expect the editor selection card component to be replaced with a more flexible dropdown component, which would resolve the issue here, see screenshot below.

Thanks for the ping, @geropl! 🏓 

| Early design for editor selection through a dropdown | 
|-|
| <img width="963" alt="Editors" src="https://user-images.githubusercontent.com/120486/180228953-f1115055-0bf6-4fbf-afe0-f305f4d91240.png"> |

**Comment by gtsiolis** [comment]
Closing this as it has been resolved in https://github.com/gitpod-io/gitpod/pull/15084. Thanks, @selfcontained!
