### ISSUE TITLE
Java Language Server crashes

### ISSUE THREAD

**Issue by dhavalmshah** [gitpod-io/gitpod#1079]
**Describe the bug**
I am unable to do Java development, because my workspace keeps reporting that Java Language Server has crashed 5 times in last 3 minutes

**To Reproduce**
Open workspace with any Java code from github

**Expected behavior**
Workspace should open and assist in Java development

**Additional Information**

**Comment by dhavalmshah** [comment]
![image](https://user-images.githubusercontent.com/9105352/72342978-cd726300-36f3-11ea-952b-0315ba1a14d5.png)

**Comment by JesterOrNot** [comment]
Hey @akosyakov can you take a look at this?

**Comment by akosyakov** [comment]
Yes, please share repo with which it happens. A workspace id can help to investigate as well.

**Comment by dhavalmshah** [comment]
workspace id is: da7ddddd-5b77-4211-a046-9b95cccc51f1

**Comment by dhavalmshah** [comment]
I think this is same issue as https://github.com/gitpod-io/gitpod/issues/1073

**Comment by akosyakov** [comment]
@dhavalmshah Sorry for the delay, it is hard to investigate, the issue seems to be in the extension itself. It does not produce any error logs on crash, so only a user can investigate it by enabling java tracing: https://github.com/gitpod-io/gitpod/issues/1073#issuecomment-575048749

You can install lombok extension for your repo for now as I've mentioned here: https://github.com/gitpod-io/gitpod/issues/1073#issuecomment-575503989
Please see docs on how to install one: https://www.gitpod.io/docs/vscode-extensions
If you let me know which repo you work on I can make a PR for you.

I've filed an issue for the java vscode extension to clarify why does it require lombok extension to be installed.

**Comment by jankeromnes** [comment]
@dhavalmshah To clarify, you can make Gitpod automatically install the Lombok VS Code extension, for every workspace started on your repository.

To achieve this, please simply create a `.gitpod.yml` file containing:

```yml
vscode:
  extensions:
    - GabrielBB.vscode-lombok@0.9.9:crmJ0s9mO0sdhxHl4cZaMw==
```

and then commit and push this file to your repository. This should resolve the problem for good.

**Comment by akosyakov** [comment]
Another workaround, in your user settings remove `java.jdt.ls.vmargs`. I contains `-javaagent:\"/tmp/vscode-extensions/GabrielBB.vscode-lombok@0.9.9/extension//server/lombok.jar\"`. Looking who is responsible for inserting it.

**Comment by dhavalmshah** [comment]
Ok, I have it working using the .gitpod.yml workaround. I am good for now.
