### ISSUE TITLE
Evicted: Pod The node had condition: [DiskPressure]

### ISSUE THREAD

**Issue by c-wegner** [gitpod-io/gitpod#1080]
**Describe the bug**

Try to load workspace that was operating fine an hour ago and get evicted for "Disk Presure"
**To Reproduce**

See above
**Expected behavior**

The work space to open
**Additional Information**

**Comment by JesterOrNot** [comment]
Sounds like a Kubernetes issue @jankeromnes can you take a look?

**Comment by jankeromnes** [comment]
Hi @c-wegner, thanks for reporting this, and so sorry about the disruption.

FYI this is the same bug as #916, #923, #935, #954, #955, #989 and #1059.

### Why is this happening

This problems happens when a server in one of our clusters has the condition "DiskPressure", i.e. one of its disks is getting close to full, so Kubernetes "randomly" decides to "evict pods" (i.e. most likely it will force-stop a user workspace) in order to reclaim some disk space.

We believe that Kubernetes will evict the pod that's consuming the most disk space (e.g. maybe the `/workspace` volume, or the workspace's Docker image, are very large). This is bad, because it disrupts developers while they're using Gitpod.

Also, we're not sure yet which disk Kubernetes thinks is under "pressure", because in our monitoring, the server SSDs quite often still have plenty of available disk space.

In any case, we should find out where Kubernetes sees "Disk Pressure", and stop it from shutting down user workspaces (that's not the correct way to handle a disk getting full -- instead we should do something behind the scenes that doesn't disrupt users, e.g. start allocating new workspaces to a new server with fresh disks).

### How can I stop or restart my workspace?

I currently believe that the workspace can be restarted almost instantly. However, if the workspace starts on the same server, and re-triggers a "Disk Pressure" event (e.g. by having a large Docker image), then it may likely get evicted again.

In practice I'd suggest trying again 5 to 10 minutes later.

### My workspace won't start but I really need the data

Please send an email to support@gitpod.io with your workspace ID. If you haven't manually deleted your workspace, an admin will be able to recover a backup archive of your workspace, and email it to you.
