### ISSUE TITLE
Epic: In product collection of workspace logs

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10802]
We commonly get issues from customers / users and have to subsequently ask users for logs, the time of the issue, the workspace etc. We have in product mechanisms for gaining ad-hoc feedback and collecting logs, as detailed in troubleshooting. However, the process is: 

* Still to hard / requires users to do manual work to extract logs
* Must consider self-hosted where we don't have access to logs
* Must still provide timeframes

It would be good if there were some way (in product) to mark a troubled workspace, and to automatically run the required steps to grab logs and performance data from the client (appropriately sanitised). 

https://www.gitpod.io/docs/troubleshooting

![image](https://user-images.githubusercontent.com/5528307/174844645-a2282e41-52c7-4a97-8e83-a98c67caac4d.png)

Related [internal discussion](https://gitpod.slack.com/archives/C02JV0QE45S/p1646153232710499) regarding using WireShark for debugging networking issues. 

And related internal discussion on [perf improvements](https://gitpod.slack.com/archives/C01KPEPNBD0/p1656586552674479). 

Relates to: 
- https://github.com/gitpod-io/website/issues/2246
- https://github.com/gitpod-io/gitpod/issues/6740
- https://github.com/gitpod-io/gitpod/issues/8704

**Comment by lucasvaltl** [comment]
👋 Hey @lou
Speaking of Self-Hosted: replicated has a feature called [support bundles](https://docs.replicated.com/reference/custom-resource-support-bundle) which allows us to get data from a running installation/cluster. We are already using this. We have some control over what data gets included in there, and can actively expanding the data that is included doing (e.g. https://github.com/gitpod-io/gitpod/issues/10399).

Where do expect the logs to come from? If they are coming from a users machine (i.e. they are using a desktop IDE, or downloading the logs from VS code web to their machine), replicated support bundles won't help. If we expect the logs to come from the workspace, it might be possible to include workspace logs in these bundles. In order to actually get validation here, it is worth having a design discussion with someone from the self-hosted team. Happy to find someone that has 30 minutes if you like.
