### ISSUE TITLE
Extremely poor connection for SEA region and CORs error

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#10920]
### Bug description

Gitpod's connection has been bad on decent Internet speed (30mbps) for users in SEA region. There are also CORS error and websockets to Gitpod servers take an extremely long time to send response back or will time out.

### Steps to reproduce

Open a workspace

### Anything else?

![gitpod-error-01](https://user-images.githubusercontent.com/14900791/175855053-3f9dd31f-c5c5-461f-9509-ce4fd4c966d0.PNG)
![gitpod-error-02-cors](https://user-images.githubusercontent.com/14900791/175855064-cfb11b47-974d-4b9a-9cb5-1ef17f22997a.PNG)

**Comment by atduarte** [comment]
We are aware of the latency issues and have plans for improving that https://github.com/gitpod-io/gitpod/issues/7489.

Nonetheless, you shouldn't be experiencing errors. Are those errors only visible in the Chrome Dev Tools console or do you experience any issues?

**Comment by kunxin-chor** [comment]
It takes a long time for the file explorer to load its file too.

**Comment by mustard-mh** [comment]
Hey @kunxin-chor, this CORs error is known and you can track it here https://github.com/gitpod-io/gitpod/issues/8579

Your problem maybe due to latency that @atduarte mentioned above https://github.com/gitpod-io/gitpod/issues/10920#issuecomment-1167202358, but we need to investigate what happened in your workspace, could you provide more information? i.e.

- Workspace id that this problem happend
- Logs in vscode maybe helpful somehow https://www.gitpod.io/docs/troubleshooting#gitpod-logs-in-vs-code-web-and-desktop

**Comment by kunxin-chor** [comment]
Another issues also include the file explorer taking a long time to load, saving files is non-responsive and port 3000 taking a long time to connect. For the logs I will follow up via email.

**Comment by mustard-mh** [comment]
Hey @kunxin-chor, thanks for your logs provide 🙏 , I thought the problem you faced might be because of the network problem that atduarte mentioned above https://github.com/gitpod-io/gitpod/issues/10920#issuecomment-1167202358.

You can try with VPN to see if it works for you, and we have an issue to add Singapore (sg) region to Gitpod https://github.com/gitpod-io/gitpod/issues/5534, please upvote 👍  and track it here.

Feel free to reopen it if VPN not works for you.
