### ISSUE TITLE
Allow User Profile Updates

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#10999]
Currently, the user information (name and email) is taken from whatever oauth provider you started out with. User can't update them later on. For product-led-sales reasons we want to encourage users to put in their work email and company name.

# Solution

- In addition to `Name` and `Work E-Mail`add a third field `Company` and allow users editing all three.
- [SaaS only] Nudge users once a year that have at least started two workspaces in the past, with a modal in the dashboard to update their profile information (in-modal).

**Comment by svenefftinge** [comment]
@gtsiolis could you draft a design for the modal? I was thinking of embedding the form the profile settings with a heading such as "Is your profile information up to date?".

**Comment by gtsiolis** [comment]
@svenefftinge What do you think of using the new alert component in-page for nudging users for updating their account information instead of the more aggressive and intrusive modal?

| Account | Account (Edit) | Account (Nudge} |
|-|-|-|
| <img width="1440" alt="Account-1" src="https://user-images.githubusercontent.com/120486/176536180-c80270c6-ed35-497d-a509-62c4346cd190.png"> | <img width="1440" alt="Account" src="https://user-images.githubusercontent.com/120486/176536170-1e36153e-d709-42a8-af69-b8718cf72dac.png"> | <img width="1440" alt="Account-2" src="https://user-images.githubusercontent.com/120486/176536184-7f74ed24-bd0c-43b0-b622-524c033f9574.png"> |

Notes:
1. Use a modal to update the account information instead of making the information editable inline
2. Remove relevant information to override author name and email for commits as this will be no longer relevant
3. Use an alert component to nudge users about their account information with an action link that triggers the same modal and an option to dismiss the alert

| Account edit (modal) | Account edit (inline) |
|-|-|
|  <img width="1440" alt="Account" src="https://user-images.githubusercontent.com/120486/176537050-4a097844-15c4-4b68-9d94-78687547f65f.png"> | <img width="1440" alt="Account-1" src="https://user-images.githubusercontent.com/120486/176537062-c49420fa-4fa5-4ec2-8b0d-52fb5bc2a983.png"> |
