### ISSUE TITLE
Not able to use Gitpod

### ISSUE THREAD

**Issue by dhavalmshah** [gitpod-io/gitpod#1105]
Hi,

I am a paid subscriber, and have not been able to use Gitpod for past several days. This is despite having raised an issue for the same. I wonder if you have a refund or compensation policy because this kind of delays are not acceptable by any professional organization

**Comment by jankeromnes** [comment]
Hi @dhavalmshah, we're sorry that Gitpod didn't live up to your expectations. We'll try to fix any problems that prevent you from using Gitpod, and we're happy to discuss a commercial gesture to make this right.

To ensure that we're not overseeing any problems, what do you mean by "not been able to use Gitpod for past several days"? We're aware that:
-  #1043 You were unable to start a workspace on January 2, because a server in our Asia region had a full disk. We've resolved the situation, and improved our disk-monitoring systems.
- #1079 The Java Language Server didn't work for you on January 14, because of a missing Lombok extension. We're investigating why this extension is sometimes required.

Is there anything else that doesn't work for you in Gitpod? Please let me know if we missed anything, or if we didn't understand the full extent of one of these problems.

**Comment by Kreyren** [comment]
FWIW No problem with uptime on my end in Europe and GitPod staff seems to be fast on resolving these issues alike yesterday's US02 cluster downtime.

**Comment by dhavalmshah** [comment]
> Hi @dhavalmshah, we're sorry that Gitpod didn't live up to your expectations. We'll try to fix any problems that prevent you from using Gitpod, and we're happy to discuss a commercial gesture to make this right.
> 
> To ensure that we're not overseeing any problems, what do you mean by "not been able to use Gitpod for past several days"? We're aware that:
> 
> * #1043 You were unable to start a workspace on January 2, because a server in our Asia region had a full disk. We've resolved the situation, and improved our disk-monitoring systems.
> * #1079 The Java Language Server didn't work for you on January 14, because of a missing Lombok extension. We're investigating why this extension is sometimes required in order to fix the Java LS crashes.
> 
> Is there anything else that doesn't work for you in Gitpod? Please let me know if we missed anything, or if we didn't understand the full extent of one of these problems.

Hi @jankeromnes, I was frustrated with #1079. #1043 I was ok with, happens....
#1079 seems like someone on gitpod side inserted a configuration which causes this issue. But I was not able to Gitpod to work for past 3 days due to this issue, and that cause me a lot of pain.

Anyway, it is working for now, with a workaround so I am fine.

**Comment by jankeromnes** [comment]
> Hi @jankeromnes, I was frustrated with #1079.

Ok, I understand. Thank you for clarifying.

> seems like someone on gitpod side inserted a configuration which causes this issue.

This configuration is indeed what caused the crashes. However, it wasn't introduced by someone from Gitpod, it's actually set on a user-wide basis by an extension (we believe it's the lombok extension itself).

We're now looking into how to deal with extensions that install settings on a user-wide basis, even though the user may have other workspaces where the extension is not actually installed.

> But I was not able to Gitpod to work for past 3 days due to this issue, and that cause me a lot of pain.

We're very sorry about that. Unforeseen bugs like these can happen at any time, but we're striving to detect & fix them as fast as possible to limit any disruption to users. Also, we were already busy with another incident (the US region instability), which is why we took a bit longer to address the Java LS crashes.

But in order to make this right for you, we've decided to offer you a one-time credit of 50 Gitpod hours. They won't expire, so please use them whenever you like, e.g. if you run out of hours during any given month. We hope that this small gesture will make you happy. Please let us know if there is anything else we can do to help.
