### ISSUE TITLE
Alert if user tries to link accounts of another user

### ISSUE THREAD

**Issue by aggsol** [gitpod-io/gitpod#1106]
**Describe the bug**
Authorizing GitLab access ends with an error message "Sorry, something went wrong 😓
GitLab authorization failed."

Gitpod.io is listed as successfully authorized app in the GitLab profile.

**To Reproduce**
1. Open Access control
2. Check all 3 checkboxes for GitLab
3. Authorize
4. Get redirected to GitLab
5. Confirm authorization on GitLab
6. Get redirected back to Gitpod.io error message

**Expected behaviour**
Allow access to GitLap repos after successful authorization

**Additional Information**
Firefox 72.0.1, Windows 10

**Comment by AlexTugarev** [comment]
Hi @aggsol!

> GitLab authorization failed

This is a sign for a GitLab API issue. Let me check, if there's an issue...

**Comment by AlexTugarev** [comment]
@aggsol, I checked the logs. It's indeed a gap in Gitpod's strategy for linking identities from GitHub and GitLab to your account, if they are already in use. 

So, here is what happened: you've logged into Gitpod using GitLab. Because you were not logged in to Gitpod at that point in time, and you accepted the Terms of Services, this means you've created a second account. In order to link you first account with GitLab as well, you should stay logged in with the first account and use the Access Control to grant the permissions for GitLab.

Assuming that you want to keep your initial account, and that you can push all your changes done in the workspaces of the second one, it would be best to use `Delete Account` link on the [Usage](https://gitpod.io/usage/) page. Afterwards, you can [log in to Gitpod](https://gitpod.io/login) with GitHub, and then update the permissions for GitLab on the [Access Control](https://gitpod.io/access-control/) page.

**Comment by aggsol** [comment]
@AlexTugarev I followed the steps, but that did not work. 

I noticed that the permissions on GitLab for Gitpod.io are: `read_user api read_repository` I expected more permissions.

Also my profile on GitLab is set to private (Don't display activity-related personal information on your profiles) but should not prevent authorization.

**Comment by aggsol** [comment]
Ha! I tried it again but this time instead of using Github to log in I used Gitlab (and logged out from Github before). Now it works. So there is something fishy about login and authorization.

**Comment by AlexTugarev** [comment]
Reopening, as the fix isn't yet deployed.

**Comment by AlexTugarev** [comment]
The underlying issue has been resolved. @aggsol you will be able to login with your most recently used Gitpod account using either login with GitHub or with GitLab.
