### ISSUE TITLE
Add slack notifications for failed deployments

### ISSUE THREAD

**Issue by andrew-farries** [gitpod-io/gitpod#11123]
During a recent incident ([retrospective here](https://www.notion.so/gitpod/internal-Webapp-deployment-failed-to-run-database-migration-c02d681f19534a15ae0dcaf0fd8356a2?v=2df2f472ffa44823afc70af13cad26d5) (internal)), a Webapp deployment failed (during database migration) but it was not obvious that it had done so.

We see *deployment job started* and *deployment job succeeded* slack notifications, but we do not receive notifications when a deployment fails

**Comment by meysholdt** [comment]
hi @andrew-farries, since all product teams own their deployment pipelines and there is nothing super special about this fix, this is something the WebApp team could do by themselfes, correct? Let me know if pointers would be helpful. 

From the incident notes, the failed job:
https://werft.gitpod-io-dev.com/job/ops-custom-main.2234/raw
