### ISSUE TITLE
Stopping workspace sharing does not work

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#1125]
**Describe the bug**
Together with a colleague I tried the workspace sharing. He uses Firefox and I am using Chrome.
He shared his workspace with me sent me the link to it and I was able to access it. 
After he stopped sharing the workspace I was still able to modify files in the tab I accessed the workspace with.
When I close this tab and reopen a new one with the same link as before I first see a red GitPod icon but then am forwarded to the workspace again and still can modify files.
Also after he restarted sharing there is no difference. I'm still able to access and modify files with the link he sent me the very first time.

**To Reproduce**
A shares workspace and sends link l to B.
B accesses workspace in tab 1 with link l.
A stops workspace sharing.
B ist still able to modify files in tab 1.
B closes tab one and opens a tab 2 and enters link l.
B first gets a red GitPod icon and then is forwarded to the not shared workspace.
A starts sharing workspace again. 
Process can still be replayed with link l -> no difference

**Expected behavior**
I would have expected B to be actively kicked from the workspace as soon as A stops sharing it.
I also would have expected B not to be able to access the workspace again with the link from the first sharing session after A stopped sharing it and started a second sharing session.

**Additional Information**
workspace id of A: baaa9374-5925-4c69-a872-ba4c24450903

**Comment by jankeromnes** [comment]
Hi @Sandared, many thanks for sharing all these helpful details.

Most of what you describe is Gitpod's currently expected behavior:
- If a workspace is shared, then anyone who has the link can open it (the link contains an unguessable workspace ID)
- If a workspace is unshared, it will not "kick out" everyone except the owner (i.e. people who entered while the workspace was shared can continue to collaborate until they close the tab)
- The sharing link is actually just the workspace URL, so there is no "single link per sharing instance" (i.e. if you share the workspace again later, you will still get the same sharing link as before)

However, this does sound like a bug:

> I first see a red GitPod icon but then am forwarded to the workspace again and still can modify files.

> B first gets a red GitPod icon and then is forwarded to the not shared workspace.

The "you don't have access to this workspace" error should definitely _not_ forward you to an interactive workspace where you can edit files. Let's focus on this problem only in this issue.

Side note: "kicking non-owners out when unshared" and "different links every time you share" would be two feature requests. Please open separate issues for these if you'd like them to be implemented.

**Comment by gtsiolis** [comment]
Probably a duplicate of https://github.com/gitpod-io/gitpod/issues/164.

**Comment by dan-kez** [comment]
@jankeromnes I would argue that not kicking out active users is a bug. If I rescind permissions to see that code it should not allow people with active sessions to continue to browse, copy paste, etc.

I gave more details on reproduction steps in the community forum here https://community.gitpod.io/t/gitpod-still-allows-access-to-workspace-after-sharing-workspace-stopped/2645 

We use gitpod to run interviews. Right now there is no way to rescind their ability to have access to the code except asking them to close the tab.
