### ISSUE TITLE
Gitpod self-hosted does not allow access to SharedArrayBuffer

### ISSUE THREAD

**Issue by blueberrymuffin3** [gitpod-io/gitpod#11328]
### Bug description

Gitpod self-hosted adds the "cross-origin-opener-policy: same-origin-allow-popups" header to workspaces, which breaks apps that use SharedArrayBuffer.
The header is added here: https://github.com/gitpod-io/gitpod/blob/aa2c51c80405c1d2da0d58840c27fa7fd0bb746b/components/proxy/conf/Caddyfile#L49-L56

For some reason, this doesn't seem to affect gitpod.io

### Steps to reproduce

1. Open https://github.com/blueberrymuffin3/gitpod-secure-context-test in gitpod.io and a self-hosted instance of gitpod
2. Tests pass for gitpod.io, but fail on self-hosted gitpod

### Expected behavior

The test should pass on self-hosted Gitpod (i.e. window.SharedArrayBuffer should be defined).

### Example repository

https://github.com/blueberrymuffin3/gitpod-secure-context-test

**Comment by MrSimonEmms** [comment]
Hi @blueberrymuffin3, I can't recreate this. I've got this running on gitpod.io and on my own self-hosted instance (set up using [my k3s guide](https://github.com/MrSimonEmms/gitpod-k3s-guide)) 

# gitpod.io
![image](https://user-images.githubusercontent.com/275848/178736993-7eb8e6b4-76e7-4fbd-be31-e7831e6f63e0.png)

# My self-hosted instance

![image](https://user-images.githubusercontent.com/275848/178737042-cb30200b-1aa8-414a-bb2f-12dfb2f36119.png)

In both cases, I'm using [your repo](https://github.com/blueberrymuffin3/gitpod-secure-context-test) and then just going to port 3000 (due to a port conflict, the one on my self-hosted instance is running on port 3001, but that's the only difference)

**Comment by blueberrymuffin3** [comment]
I believe this only happens when accessing the app through the browser VS Code instance, as the header is added by the caddy proxy. Forwarding the port to localhost seems to avoid the issue.

**Comment by blueberrymuffin3** [comment]
I'm running version 2022.6.0, deployed with KOTS.

**Comment by blueberrymuffin3** [comment]
@MrSimonEmms are you able to test accessing the app through VSCode browser instead of through localhost (i.e. 3000-workspace-name.ws.example.com)?

**Comment by MrSimonEmms** [comment]
I normally use VSCode Desktop, but I've tried it in-browser as well - the results are the same between the two. I'm using the [live preview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) for the test.

On Gitpod.io, I get:

```
window.parent (not an iframe): Not OK!
window.isSecureContext (headers): OK
window.SharedArrayBuffer: Not OK!
```

On my self-hosted instance, I get:

```
window.parent (not an iframe): Not OK!
window.isSecureContext (headers): OK
window.SharedArrayBuffer: Not OK!
```

These are different to what you get through a [full browser](https://github.com/gitpod-io/gitpod/issues/11328#issuecomment-1183183058) (in my case, I use Firefox). I can't see any difference between the Gitpod.io and self-hosted outputs - if you get different, can you reopen this issue and add a short video demonstrating the different ([Loom](https://www.loom.com/home) is pretty good for that)
