### ISSUE TITLE
java: "No X11 DISPLAY variable was set"

### ISSUE THREAD

**Issue by antrobot1234** [gitpod-io/gitpod#1137]
**Describe the bug**

i am trying to run a github project on java that uses jframe and graphics, but i get a No X11 DISPLAY variable was set exception whenever i try to run the main class. this does not happen on a dedicated IDE.
**To Reproduce**

run a java program using jframe (i can provide the specific repo if need be)
**Expected behavior**

i expected the jframe to open up on the side or in a separate window
**Additional Information**

gitpod /workspace/pacman $ /home/gitpod/.sdkman/candidates/java/current/bin/java -Dfile.encoding=UTF-8 -cp /workspace/pacman/bin pacman.Main
Picked up JAVA_TOOL_OPTIONS: -Xmx2254m
Exception in thread "Thread-0" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
        at pacman.objects.Display.createDisplay(Display.java:19)
        at pacman.objects.Display.<init>(Display.java:16)
        at pacman.Game.init(Game.java:38)
        at pacman.Game.run(Game.java:57)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jankeromnes** [comment]
Hi @antrobot1234, thanks for reaching out!

> but i get a No X11 DISPLAY variable was set exception whenever i try to run the main class

You likely want to use Gitpod's VNC image, which provides an X11 display with a Virtual Desktop.

To achieve this, simply create a `.gitpod.yml` file containing:

```yml
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
```

Then just commit and push this file, close your workspace, and create a new Gitpod workspace for your repository. This will give you a X11 server.

> i can provide the specific repo if need be

Please do. 🙂 When you do that, we can generally find the problem faster, and send you a Pull Request to fix it.

**Comment by antrobot1234** [comment]
[this](https://github.com/antrobot1234/pacman) is the github link. if you're willing to do a pull request to it to fix it, then be my guest. i'm having a bit of trouble adding the code you suggested to that gitpod.yml file (errors and such)

**Comment by antrobot1234** [comment]
update: i have added the yml file and now it seems that i can't even run my main file anymore

**Comment by antrobot1234** [comment]
@jankeromnes update 2: i have gotten it to run with the yml file, but the issue is persisting. the github project is still linked above

**Comment by jankeromnes** [comment]
Thank you for trying! 💯 I'll take a look, and send you a PR if I find what's wrong. 🙂

**Comment by jankeromnes** [comment]
Seems like your `.gitpod.yml` file contains just `{}`, which is not the expected content (and it's not even YAML syntax -- but it's likely the fault of our automated setup tool).

**Comment by jankeromnes** [comment]
@antrobot1234 please see https://github.com/antrobot1234/pacman/pull/1 🙂

**Comment by antrobot1234** [comment]
@jankeromnes i have merged the pull request and merged it, then brought gitpod up to speed, and now it's bringing up a window with what seems to be the correct window, but it isn't actually running the program like it should be. it opens up a window within a tab, but the window isn't displaying anything besides a blank page. by the way, the main method is in src>pacman>Main.java

**Comment by jankeromnes** [comment]
@antrobot1234 Sorry for the late reply. The window you're seeing is the virtual desktop. But you'll also need to compile and run your Java program from the Terminal.

When you do that, the "No X11 DISPLAY" error should be gone, and the Java GUI should open in the virtual desktop (note: it may open in the center of the virtual screen, i.e. not be visible in the narrow preview pane. To be sure, open the virtual desktop preview in a new tab, e.g. by clicking on the preview URL. Or go to "Ports" > "8080" > "Open Browser".)

**Comment by kevindmadden** [comment]
@antrobot1234 @jankeromnes 
Did you ever get this to work? I'm seeing the same thing as @antrobot1234 stated in his most recent post here. A window does open up, but the window doesn't display anything other than a blank page.

**Comment by mat-su** [comment]
I cant run javaAWT programs in my gitpod.. the error is same as @antrobot1234 ..

**Comment by carsonsaldanha** [comment]
For anyone else that comes across this issue, I fixed it with the following in `.gitpod.yml`:

```
image:
  file: .gitpod.dockerfile

ports:
  - port: 6080
    onOpen: open-preview
```

And this in `.gitpod.dockerfile`:

```
FROM gitpod/workspace-full
FROM gitpod/workspace-full-vnc

RUN bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh              && sdk install java 8.0.292-open"
```

**Comment by aniketkr01** [comment]
Is there any way to deploy java project ? I tried to run GUI in java using above procedure but didn't worked.

**Comment by jankeromnes** [comment]
Hi @mat-su @aniketkr01 -- in order to run graphical apps in Gitpod, like JavaAWT, please try these steps:

1. In Gitpod, create a new file called `.gitpod.yml`, with the following contents:

```
image: gitpod/workspace-full-vnc
```

2. Next, commit this file to Git (for example, in the terminal run `git add .gitpod.yml && git commit -m "Add .gitpod.yml"`)
3. Next, push this file to your GitHub repository (for example, in the terminal run `git push`)
4. Next, stop your current Gitpod workspace (for example by pressing `F1` and searching for `Stop Workspace` -- or you can simply close your Gitpod workspace browser tab)
5. Next, go to your repository in https://github.com, and open it in Gitpod again (this should create a brand new Gitpod workspace, based on the new configuration -- restarting the old workspace will not work)
6. Finally, when the new workspace is running, find the port `6080` and open it in a preview -- this will show you the virtual desktop

Also, your Java app should find the X11 environment variable, and start graphically in the virtual desktop mentioned above.

**Comment by jankeromnes** [comment]
@carsonsaldanha your configuration does look good! (Although, you don't need the first `FROM gitpod/workspace-full` in your Dockerfile, since you already use `FROM gitpod/workspace-full-vnc` below -- using just the latter should work fine).

If this doesn't work for you, could you please provide a link to your repository so that I can try opening it myself in Gitpod to reproduce the error you see? (Or, if it's a private repository, could you please create a small public repository with a minimal Java app & Gitpod config that reproduces the error?)

This would help me troubleshoot and get this working for you.

**Comment by klettercraft** [comment]
hello i have the same problem but your anserws arent working for me can you help me?
