### ISSUE TITLE
port does not respond?

### ISSUE THREAD

**Issue by fudge88** [gitpod-io/gitpod#1140]
hi why am i having problems with Gitpod- its keeps saying my port does not respond when i try to see it in a browser. 
i have exposed it and i have submitted the following command 'python -m http.server', however nothing has changed?

**Comment by Kreyren** [comment]
NOTICE: I though that i had same/simmilar issue, but it was caused by syntax error in `.gitpod.yml` (pebcak) submiting this as PSA

---

I seem to have same(?) issue on https://github.com/Kreyren/LearnRust/tree/redrectangle where previously exposed port 6080 with VNC doesn't seem to be recognized:
![image](https://user-images.githubusercontent.com/11302521/73137110-34c5d680-4055-11ea-811a-bb01e894641e.png)

EDIT: invalid - It was caused by a syntax error in `.gitpod.yml`

---

Maybe you have same issue as i did?

**Comment by svenefftinge** [comment]
@fudge88 could you please provide steps to reproduce?
Just running `python3 -m http.server` in a terminal in an arbitrary workspace works for me.

**Comment by fudge88** [comment]
Hi thank you for your response, however I managed to get hold of someone with experience- she advised em to close the terminal and populate a new one- I did this and when I commanded history my work was still there. Thank you

Sent from my iPhone

On 27 Jan 2020, at 09:39, Sven Efftinge <notifications@github.com> wrote:

﻿

@fudge88<https://github.com/fudge88> could you please provide steps to reproduce?
Just running python3 -m http.server in a terminal in an arbitrary workspace works for me.

**Comment by svenefftinge** [comment]
Please let me know if there is still anything for us to do here.

**Comment by fudge88** [comment]
Thanks you very much- but it’s all sorted now :)

Sent from my iPhone

On 3 Feb 2020, at 08:48, Sven Efftinge <notifications@github.com> wrote:

﻿

Please let me know if there is still anything for us to do here.
