### ISSUE TITLE
Unable to log into Gitpod workspaces;  am getting "Sorry, something went wrong 😓 Error 504"  in both Chrome and IE.

### ISSUE THREAD

**Issue by BobHerold** [gitpod-io/gitpod#1151]
### Describe the bug

Unable to log into Gitpod workspaces; am getting "Sorry, something went wrong 😓 Error 504" in both Chrome and IE.

### Steps to reproduce

1. Try to use Gitpod in the US

### Expected behavior

Should be able to log in.

**Comment by BobHerold** [comment]
I'm in the US...

**Comment by jankeromnes** [comment]
Hi @BobHerold, thank you for reporting this bug, and sorry about the broken experience. We're aware of a new incident affecting the US region, and we're trying to mitigate it and restore service as fast as possible.

**Comment by jankeromnes** [comment]
US service should be restored now. Please report back if something seems broken again.

**Comment by jelaniwoods** [comment]
I'm unable to create/launch into new workspaces. 

After a few attempts of creating a workspace and getting this error
![image](https://user-images.githubusercontent.com/17581658/73208228-aeb89700-410b-11ea-8efe-7820efbdc5f1.png)

I'm able to see the new workspace on my dashboard,

![image](https://user-images.githubusercontent.com/17581658/73208148-8df04180-410b-11ea-97df-8a61991a3e09.png)

But I'm unable to open it
![image](https://user-images.githubusercontent.com/17581658/73208274-c98b0b80-410b-11ea-8b50-62d096efd74f.png)

**Comment by svenefftinge** [comment]
We are pretty sure we have identified and fixed the root cause, now. There has been a bad DB query that caused the DB's CPU to hit its ceiling and subsequently creating backpressure. Adding an index completely relaxed this situation. We will further investigate and improve our monitoring so it doesn't take us so long to identify such issues in the future. We are super sorry and apologize for the downtime.
Also, many thanks to everyone who has and keeps reporting any issues. Please keep this up it's really helping us a lot.

**Comment by jelaniwoods** [comment]
@jankeromnes Yes! About 20-30 minutes later I was able to start workspaces.
