### ISSUE TITLE
I lost my code

### ISSUE THREAD

**Issue by manizha01** [gitpod-io/gitpod#1153]

**Comment by jankeromnes** [comment]
Hi @manizha01. There are many way to retrieve your code. I'm happy to help.

Please provide more information so I can help:

- Why are you saying that your code is lost? (E.g. does your Gitpod workspace refuse to start? Or is it no longer shown in your list? Etc)

- Do you have a workspace ID, or a workspace URL, so that we can check if there is any backup of your code?

In general, please provide as many details as you can. Screenshots, full error messages, URLs, etc. That way we can help you faster.

**Comment by manizha01** [comment]
HI,

I have a  repository called resume but when I open my gitpot my codes are
not here and even i save it and run git push command

[image: image.png]


[image: image.png]

**Comment by jankeromnes** [comment]
Hi @manizha01, thank you for your reply.

Unfortunately, images don't work when sent by email -- could you please re-upload your screenshots directly on https://github.com/gitpod-io/gitpod/issues/1153 ?

Also, please take a look at your list of workspaces: https://gitpod.io/workspaces/

Maybe there is one workspace there in the list that has the changes you're looking for? (Gitpod will indicate if a workspace contains changes that were accidentally not committed or pushed.)

**Comment by jankeromnes** [comment]
Issue is not actionable because it doesn't have enough information, so I'm closing it now.

If you're still seeing issues, please share more information and/or open a new issue. Thanks!
