### ISSUE TITLE
Can't open new workspace

### ISSUE THREAD

**Issue by JayneyNix** [gitpod-io/gitpod#1154]
### Describe the bug
Trying to initiate a new workspace from github using this url in browser - https://gitpod.io/#https://github.com/github username/ github project name

### Steps to reproduce
insert above URL into browser

### Expected behavior
To start a new workspace

### Additional Information
I was getting this error message - 
"Sorry, something went wrong :sweat:
Error: Connection got disposed.
Please file an issue if you think this is a bug." (edited)"

But now gitpod icon spins in the browser window for a few minutes before leaving a blank white screen.

### Example Repository
As per URL above

**Comment by RDIL** [comment]
Known issue, duplicate

**Comment by jankeromnes** [comment]
Hi @JayneyNix, many thanks for reporting this problem. It's likely related to this ongoing incident: #1151 -- we're currently trying to restore US service as fast as possible.

**Comment by Kreyren** [comment]
> Known issue, duplicate

Link the duplicate next time O.o this is not really helping

**Comment by jankeromnes** [comment]
I agree that adding a link to the issue that's most likely to receive an update soon is helpful for users who report a problem.

Also I try to always warmly thank users who take the time to report a bug, because even when it's a duplicate report, it's helpful for us to get as many details about a current issue as possible (e.g. screenshots, complete error messages, URLs, etc.)

Sometimes, even an issue filed without any extra info is useful, because just knowing that this particular problem happened again around a certain time can be helpful (e.g. when we're validating a potential fix or mitigation, or trying to correlate bug occurrences with other metrics).
