### ISSUE TITLE
Gitpod seems to have instability issues in Europe

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1156]
I keep getting following (this happend 2801200737 CET):
![image](https://user-images.githubusercontent.com/11302521/73241065-2be21b80-41a1-11ea-8b86-8250ea8bf0a3.png)

where workspace becomes unresponsive for up to 2 minutes.

**Comment by Kreyren** [comment]
again in 2001200745

**Comment by jankeromnes** [comment]
Hi @Kreyren, thanks a lot for reporting this.

Orange bottom bar generally means:

1. Unstable network (probably not in your case since you have stable ping)
2. Overloaded browser event loop (i.e. big JS computation in frontend, could be IDE or extension)
3. Overloaded backend (i.e. Gitpod temporarily doesn't respond, but should be very rare, e.g. DoS)

Is there a specific action that you always do prior to the unresponsive events? Do you see similar problems when working on a completely different project?

**Comment by svenefftinge** [comment]
The current production version has an issue with workspace search which results in a yellow bar for longer. We are going to deploy a fixed and much faster version tomorrow.

**Comment by Kreyren** [comment]
> Is there a specific action that you always do prior to the unresponsive events?

Seems to happend on random I dont see any pattern

> Do you see similar problems when working on a completely different project?

yes I saw same issue on different projects as well, but It wasn't that frequent.

**Comment by Kreyren** [comment]
> The current production version has an issue with workspace search

I am not aware of performing any kind of search during these events

**Comment by Kreyren** [comment]
This issues doesn't seem to be present anymore -> Closing

Will reopen if the issue appears again
