### ISSUE TITLE
If onOpen: open-browser is set for port, GitPod still asks what to do for this port

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#1157]
### Describe the bug
If I set a port X to be opened in browser via `onOpen: open-browser` in my gitpod.yml then the browser window pops up correctly, but GitPod still shows a small pop-up asking for what to do for port X. If I do the same with open-preview, then now additional pop-up is shown.

### Steps to reproduce
* Write a web application
* expose port 8080 via
```
ports:
   - port: 8080
     onOpen: open-browser
```
* let application be opened, e.g., by a task
* In Gitpod there is a small pop-up in the lower right corner, asking if the exposed port 8080 should be shown in preview or in browser

### Expected behavior
The pop-up should not be shown, as I already defined what GitPod should do, as is the case for `open-preview`

**Comment by jankeromnes** [comment]
Hi @Sandared! What's likely happening here is that the `open-browser` action fails, and thus Gitpod falls back to asking you.

This happens a lot with `open-browser`, because any tabs opened not in the same JS event loop cycle as a user click are blocked by the browser's pop-up blocker.

Clicking on "Open Browser" doesn't have this problem, thanks to the user click event (that's the other reason Gitpod shows the notification, to give the user the opportunity to "Open Browser" manually).

A longer-term solution is to allow the workspace tab to open pop-ups (we promise we'll never open ads or anything like that).

This is a bit unfortunate for `onOpen: open-browser`, but I'm not sure Gitpod can do more here.

**Comment by Sandared** [comment]
Hi @jankeromnes ,

I turned off all adblockers and allowed to open pop-ups but still get this message. However, it's just a really small invconvenience so it's not that important :)

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.
