### ISSUE TITLE
Arduino Support

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#116]
It should be not too hard to add support for Arduino.
This library (https://github.com/arduino/arduino-create-agent-js-client) seems to be an easy means to communicate with locally installed Arduino agent.

cc/ @32leaves

**Comment by sr229** [comment]
I'm interested how this would work - this might as well replace Arduino IDE.

**Comment by JesterOrNot** [comment]
so what would this entail a dockerfile? or more

**Comment by jankeromnes** [comment]
It would probably require a local agent to create a link between Gitpod's cloud workspace and any hardware connected to your local device.

**Comment by JesterOrNot** [comment]
If we could do this then adb would work for the android support thing

**Comment by michael-bartmann** [comment]
There is not very much information about using gitpod for Arduino projects. I found out about gitpod when compiling tasmota with it.
Now with my own projects I can compile fine, doing a 
```
tasks:
  - before: pip3 install -U platformio
    command: platformio run -e myenv
```
in my .gitpod.yml.
But I cannot get the editor to resolve even the simplest
`#include <Arduino.h>`
So with this issue #116 I am not totally clear what should work, and what will not work as long as this issue is still "OPEN".
Or is it just about the ability to have a local tool communicating with the build system to handle flashing of devices?

**Comment by sr229** [comment]
Honestly we don't really have a clear indication which should work - Artik Cloud IDE requires that the device must be plugged in, which I assume they have a background agent to listen for a specific USB ID.

**Comment by sr229** [comment]
@svenefftinge I decided to give this a little more analysis, I found out that WebUSB might be our best bet if you want some sort of interconnect from the Web IDE Web client, passing context from server to browser is a little bit I didn't investigate.

**Comment by sr229** [comment]
Alright I think this can be closed considering we have VSIX support, we can just use PlatformIO for this purpose.
