### ISSUE TITLE
How to enable syslog?

### ISSUE THREAD

**Issue by aggsol** [gitpod-io/gitpod#1166]
I am logging into syslog but cannot find any logs in `/var/log`. I tried to install rsyslog but as no systemd there I am not sure how to do it.

What is the best/easiest way to get syslogd during development in gitpod?

**Comment by jankeromnes** [comment]
Hi @aggsol, thanks for your question. I've never used syslog / syslogd before, but I suspected that your issue could be related to the fact workspaces are actually Docker containers.

When I searched for "syslogd in containers", I found this article: https://www.projectatomic.io/blog/2014/09/running-syslog-within-a-docker-container/ which suggests modifying `/etc/rsyslogd.conf`.

I guess you'd need to create a [`.gitpod.yml` file](https://www.gitpod.io/docs/config-gitpod-file/) that references a [`.gitpod.Dockerfile`](https://www.gitpod.io/docs/config-docker/).

In that Dockerfile, you could apply the proposed changes to `/etc/rsyslogd.conf`, e.g. by using `sed` commands a bit [this one](https://github.com/gitpod-io/definitely-gp/blob/c67b3713ab41ab226969ab1ba90913142d5a21b7/servo/.gitpod.dockerfile#L55).

Please let me know if that solves your problem, of if you're still seeing this error after making these changes. Also, if you add a link to your repository, I'm happy to send you a Pull Request.

**Comment by jankeromnes** [comment]
Also, please take a look at https://github.com/rsyslog/rsyslog-docker which may be relevant/useful here.

Note that Gitpod supports Docker images based on Ubuntu and Alpine.

**Comment by corneliusludmann** [comment]
As I see it, the problem is that for security reasons it is not allowed to run the rsyslog daemon as root in Gitpod. Thus, rsyslog could not create the socket `/dev/log` that accepts the log messages.

However, you can run rsyslog as unprivileged user. I created an example for you there: [gitpod-syslog-example](https://github.com/corneliusludmann/gitpod-syslog-example)
The limitation is that you must specify in your application that the log socket `/home/gitpod/rsyslog/dev/log` instead of `/dev/log` should be used as I do this in the example with the `logger` command like this:
```shell
$ logger --socket /home/gitpod/rsyslog/dev/log "Hello world"
```

Maybe somebody else has an idea how to improve this …

**Comment by aggsol** [comment]
I was not able to use syslog. I am using now a differen logging.
