### ISSUE TITLE
[ws-daemon] Unexpected cannot find workspace during DisposeWorkspace

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11710]
### Bug description

![Jaeger-UI](https://user-images.githubusercontent.com/161571/181394879-28cafc4d-ef42-4dbb-b7d6-00b683d2c0f1.png)

### Steps to reproduce

-

### Expected behavior

If it's not really an error condition, then change this to be a warning. The warning would essentially be an indicator that we're calling dispose 2 or more times, and the 1st time would have done disposal.

### Anything else?

When does this error happen? Is it really an error? Is there anything else we can log with it, to determine the state of the workspace on the node (`/workspace` still exist?)

**Comment by kylos101** [comment]
👋 @jenting , may I ask you to focus on https://github.com/gitpod-io/gitpod/issues/11713, move this back to scheduled, and unassign yourself for now? This way you can focus on #11713. If you think there's a need to do both at the same time, can you share why? I'm not seeing the relationship, and am trying to limit work in progress.

**Comment by kylos101** [comment]
👋 @jenting alternatively, if you already started #11710, please move #11713 back to scheduled, etc.

**Comment by jenting** [comment]
From the Jaeger tracing, the observation is that we call the `finalizeWorkspaceContent` almost within the same time.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/49380831/182526044-a5a4625c-79e6-4110-a10f-d9ac302d14a7.png">
<img width="673" alt="image" src="https://user-images.githubusercontent.com/49380831/182526239-bcb2de7c-dbc4-44a6-82dc-20e300d2c4fb.png">

**Comment by kylos101** [comment]
I am still seeing in `us60`:

![Image](https://user-images.githubusercontent.com/1272076/183795529-3082b3c8-a004-4471-94f9-431151f9ca47.png)

**Comment by utam0k** [comment]
In this case, it has already been erased from ws-daemon's store. In other words, it was terminated normally, but the disposal was canceled due to a timeout in the context. In other words, it was terminated normally but failed due to a timing issue.
![image](https://user-images.githubusercontent.com/13010913/183860503-b564f6f7-ac7f-44eb-91d3-db680f72a20c.png)



> I am still seeing in `us60`, search workspace logs for instanceId `eb3d43eb-18bc-47fe-83b0-0adf388dcfb8` for detail from August 9.
> 
> ![Image](https://user-images.githubusercontent.com/1272076/183795529-3082b3c8-a004-4471-94f9-431151f9ca47.png)

**Comment by jenting** [comment]
We need to check the jaeger tracing on the gen63 cluster to see if it still happens or not.

**Comment by utam0k** [comment]
Unfortunately, this problem still happened on the gen63 😭

**Comment by sagor999** [comment]
Looking at `cc69aed8-7cd1-4055-8f90-777f2281cc3b`
`INITIALIZING` phase started at say 0 seconds. It lasted 6.5s.
While it was running, pod went from INITIALIZING to STOPPING phase at +3 seconds. 
At this point, we are now starting to Dispose workspace, at the same time as `initializeWorkspace` is still running and finishing its work. In this specific example, it actually failed, because by the time it got to talking to ws-daemon, we already disposed workspace. 
Hence a bunch of errors with `cannot find workspace`.

Seems like we have an architectural problem due to ability to run phases in parallel. :thinking:
