### ISSUE TITLE
Errors in limits units should be reported in the validation phase of the installer

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11756]
### Bug description

This issue impacts the node density.

```
{"level":"info","logger":"KubeAPIWarningLogger","message":"spec.containers[0].resources.requests[memory]: fractional byte value \"13743895347200m\" is invalid, must be an integer","serviceContext":{"service":"ws-manager","version":"commit-66042649f552ed30b4a2ef1a129c53f25afb72a3"},"severity":"INFO","time":"2022-08-01T03:18:45Z"}
``` 

### Steps to reproduce

- Set memory request limits to `12.8Gi` in the installer yaml file.

### Expected behavior

Setting limit in the installer should not allow setting `Gi` values that produce fractional `Mi` values.

### Anything else?

As bonus, if we can compare the values to ensure they are the same, even when the unit is different, that would be helpful (6GB = 6000MB).

**Comment by kylos101** [comment]
@jenting this may also be good to squash while working #11759

**Comment by lucasvaltl** [comment]
@MrSimonEmms is this fixed with the new preflight check that validates the installer config?

**Comment by MrSimonEmms** [comment]
@lucasvaltl once this feature is wired into the `validation config` command in the Installer, this will get run as part of the preflight.

**Comment by mrsimonemms** [comment]
I've looked into this and I don't think there's an awful lot we can do on this with the current setup. We're using the Kubernetes `ResourceRequirements` struct for this rather than a custom one which makes using the validator package a little bit tricky. Also, there are no [built-in memory checks](https://pkg.go.dev/github.com/go-playground/validator/v10#section-readme) in that package which means we'd have to write something. I can see this being a bit problematic ensuring that it works with every possible permutation we may need.

Also, this is in the `experimental` config so this is not something that we're (currently) making part of our public, supported config structure.

For that reason, I'm closing this ticket as not necessary. Happy to discuss further if anyone has any strong feelings to the contrary

For reference, the config I used is below

```yaml
experimental:
  common:
    podConfig:
      ws-manager:
        resources:
          ws-manager:
            requests:
              cpu: "1"
              memory: 12.8Gi
```
