### ISSUE TITLE
fatal: 'origin/branch-name' is not a commit and a branch 'branch-name' cannot be created from it

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#11854]
### Bug description

In `gen59`, we see errors like:
![image](https://user-images.githubusercontent.com/1272076/182715613-e09d1c82-9066-4af4-ae04-e62d4687fff1.png)

We must be hitting [this error](https://github.com/gitpod-io/gitpod/blob/e4842b96a389c5a4ccd0d1d44f74fb6990e4fb7e/components/content-service/pkg/initializer/git.go#L147), which gets [traced here](https://github.com/gitpod-io/gitpod/blob/e4842b96a389c5a4ccd0d1d44f74fb6990e4fb7e/components/content-service/pkg/initializer/git.go#L141-L142).

### Steps to reproduce

Not sure. 

Maybe try starting a workspace, and delete the remote branch before the workspace starts, ideally after context parsing, before loading the content.

### Workspace affected

n/a

### Expected behavior

1. We should log this as an error, not debug, so we can see in the logs w/o enabling debug
2. We should return a clear message to the user when this happens.
3. We shouldn't retry so many times for so long

![image](https://user-images.githubusercontent.com/1272076/182716689-22397e95-2276-48f7-b47f-53435610300e.png)

**Comment by jenting** [comment]
I check the spans and corresponding logs, a case happens in prebuild, and the remote branch does not exist anymore.

**Comment by kylos101** [comment]
Still seeing this issue with prebuilds [[1](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-08-10T00:23:00Z;query=severity%3DERROR%0AjsonPayload.serviceContext.service%3D%2528%22ws-manager%22%2529%0Aresource.labels.cluster_name%20:%20%2528%22us60%22%2529%0Atimestamp%3D%222022-08-10T00:23:00Z%22%0AinsertId%3D%223h5dii30dob9njbx%22;summaryFields=:false:32:beginning:false;timeRange=PT30S?project=workspace-clusters)][[2](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-08-10T00:23:00Z;query=severity%3DERROR%0AjsonPayload.serviceContext.service%3D%2528%22ws-manager%22%2529%0Aresource.labels.cluster_name%20:%20%2528%22us60%22%2529%0Atimestamp%3D%222022-08-10T00:22:59Z%22%0AinsertId%3D%22wktpy6mbq5mmidex%22;summaryFields=:false:32:beginning:false;timeRange=PT30S?project=workspace-clusters)]

**Comment by kylos101** [comment]
@atduarte adding back to scheduled

**Comment by jenting** [comment]
> Still seeing this issue with prebuilds [[1](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-08-10T00:23:00Z;query=severity%3DERROR%0AjsonPayload.serviceContext.service%3D%2528%22ws-manager%22%2529%0Aresource.labels.cluster_name%20:%20%2528%22us60%22%2529%0Atimestamp%3D%222022-08-10T00:23:00Z%22%0AinsertId%3D%223h5dii30dob9njbx%22;summaryFields=:false:32:beginning:false;timeRange=PT30S?project=workspace-clusters)][[2](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-08-10T00:23:00Z;query=severity%3DERROR%0AjsonPayload.serviceContext.service%3D%2528%22ws-manager%22%2529%0Aresource.labels.cluster_name%20:%20%2528%22us60%22%2529%0Atimestamp%3D%222022-08-10T00:22:59Z%22%0AinsertId%3D%22wktpy6mbq5mmidex%22;summaryFields=:false:32:beginning:false;timeRange=PT30S?project=workspace-clusters)] in `us60`

The way to reproduce it is when running prebuild, the remote branch is deleted at that moment.

**Comment by kylos101** [comment]
When this happens:
![Image](https://user-images.githubusercontent.com/1272076/183789335-3f7edc30-5578-4002-94b3-e96ac20e6f06.png)

A chain of events occur:
![Image](https://user-images.githubusercontent.com/1272076/183789452-1c882bf9-d39c-4646-8b19-9df345793ff6.png)



![Image](https://user-images.githubusercontent.com/1272076/183789501-dcde76e0-e984-40fe-8ed4-6e85969cad20.png)

**Comment by jenting** [comment]
I checked the `InitWorkspace` span, and I found an interested thing, all the checkout branch error comes with the users use the [additionalRepositories](https://github.com/gitpod-io/website/blob/main/gitpod/docs/references/gitpod-yml.md#additionalrepositories) configuration within the .gitpod.yml.

Also, I create a test [repo](https://github.com/jenting/lh/tree/test-branch-1), and I'm able to reproduce it. Just open the repo with the branch `test-branch-1`, and filter the Jaeger tracing with
- service=content-initializer
- error=true

The problem is that all the additional repositories do not have branch `test-branch-1`. However, the content-initializer still trying to pull the `test-branch-1`. If the branch `test-branch-1` does not exist, we fall back to pull the default branch.

**Comment by fitztrev** [comment]
This has started happening for me today.

Repo: https://github.com/rosen-score/lila-gitpod

**Comment by kylos101** [comment]
:wave @fitztrev , thanks for the heads up! This fix will ship next week.

**Comment by fitztrev** [comment]
@kylos101 thanks for the quick update!

Seems to have started happening today because this change deployed yesterday: https://github.com/gitpod-io/gitpod/pull/11895 And now it does a hard stop if it encounters a git checkout error.

Yes, it probably was due to the fact that the default branch name is different between the main repo and any of the `additionalRepositories`.

For now, until this gets deployed, I removed the `additionalRepositories` section and just `git clone` them individually in the startup script.

**Comment by jimmybrancaccio** [comment]
[Conversations in Front](https://app.frontapp.com/open/top_3plze).

**Comment by david-bakin** [comment]
Is it gitpod's flow to close bugs before deployment (and before confirmation)?  I got this today - see #12118.

**Comment by atduarte** [comment]
@david-bakin Github issues are closed automatically and moved to "Awaiting Deployment" whenever the code that fixes the issue is merged. 

<img width="260" alt="image" src="https://user-images.githubusercontent.com/666176/185088717-33dfe8de-c0f8-470d-8a3b-b6d40a077f7a.png">

Then when we deploy, it is moved to "In Validation".

**Comment by mikenikles** [comment]
Hey André, based on your comment this PR is deployed, can you confirm that?

[According to Kyle in Discord](https://discord.com/channels/816244985187008514/1007280790960349235/1007369234948563064), PRs are only deployed once they have the `deployed: workspace` label.

**Comment by mikenikles** [comment]
Hey @atduarte, based on your comment this issue has been deployed, can you confirm?

[According to Kyle on Discord](https://discord.com/channels/816244985187008514/1007280790960349235/1007369234948563064), issues are only deployed once they have the `deployed: workspace` label, which isn't the case for this issue here.

**Comment by atduarte** [comment]
@mikenikles yap! As part of gen61.

The `deployed: workspace` label is applied to the PRs, not the issues unfortunately.
