### ISSUE TITLE
Gitpod not saving files

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1195]
### Describe the bug

Gitpod files are not saving, checked for local cache and was not the issue. Was also experiencing issues trying to edit- the page would become unresponsive, but only after experiencing the issue of the files not updating.

https://c49ce212-9670-4d32-87ac-6aadb685009c.ws-us02.gitpod.io/#/workspace/collab-cohort-vii-the-best-cohort-everrrrrr

**Comment by JesterOrNot** [comment]
Where is the broken config? I'm not seeing it can you paste them?

**Comment by ColbyWTaylor** [comment]
I didn't see anything regarding the config- it was just not saving the files. It is now working, but we experienced this with a few students today at the same time...

**Comment by JesterOrNot** [comment]
Can we close this issue?

**Comment by ColbyWTaylor** [comment]
While the issue isn't currently happening, any idea why it happened would be nice. It isn't the first time we've had this, and the past week we've experienced an increase in connection issues- just trying to get an idea of what is going on to better prepare for the next time this comes up.

**Comment by JesterOrNot** [comment]
I'm assuming you are pushing your changes to a git repo

**Comment by ColbyWTaylor** [comment]
While working on a project, the files within the session were not saving- nothing to do with pushing!

**Comment by alesanchezr** [comment]
This has happened to me before, its I have to develop a "sixth sense" because every now and then gitpod has this issue, sometimes I am working and refresh the workspace just to double check that everything is being really really saved.

It does not happen often, maybe twice a month, but I still commit all the time because I'm afraid that it could happen again.

I remember talking about this with @meysholdt like a year ago, something related to storage services being unstable at the time. idk if it's the same issue.

**Comment by alesanchezr** [comment]
I think #1209 its the same issue.

**Comment by svenefftinge** [comment]
Thanks for coming back and reporting. There was a node that ran out of disk in the US cluster yesterday around 4pm ET. That issue was solved an hour after it happened. Anyway we are will improve the monitoring for that case so cannot happen again. 
Let's use the more specific #1209 for tracking this and close this one as a duplicate.
