### ISSUE TITLE
File Icon Themes do not persist

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1196]
### Describe the bug
On opening of a new workspace previously configured Icon themes do not persist
### Steps to reproduce
Get a file icons extension
Install it to the repo
Put it in your user settings/workspace settings
Open new workspace
See that changes don't persist
### Expected behavior
File Icons Persist

**Comment by RDIL** [comment]
Icons aren't showing at all for me when I try

**Comment by akosyakov** [comment]
@RDIL Could you provide more info please? Which theme, maybe you can install it in the workspace instead of for user and share a snapshot to reproduce.

**Comment by felipecassiors** [comment]
I can confirm it's not working indeed. 

Try to install [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme). Then select it as the icon theme. It works for that session, but if you open another workspace of reopening that one, you have to re-set the icon theme. 

Details:
- It does not persist even if I put the setting key in the workspace settings.
- Themes (not Icon Themes) persist as expected, for both the workspace or the user settings.
- The setting key about the icon theme remains on the user setting (Ctrl + ,) despite it does not apply.

**Comment by diegoulloao** [comment]
Any solution for this?

**Comment by htbrown** [comment]
Also having this problem but with product and file icon themes - seems to be something up with the syncing because it reverts back to none/default with a reload.
Plugins I'm using are [Material Theme Icons](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme-icons) and [Fluent Product Icons](https://marketplace.visualstudio.com/items?itemName=miguelsolorio.fluent-icons).

**Comment by akosyakov** [comment]
@htbrown Could you try again? And if still does not work please file a new issue. This issue is about Theia editor which we don't use by now.
