### ISSUE TITLE
[installer] Support PVC size config for docker-registry

### ISSUE THREAD

**Issue by nandajavarma** [gitpod-io/gitpod#11984]
## Is your feature request related to a problem? Please describe

Currently, we do not support the configuration of PVC storage size for `docker-registry` component in the [helm config](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/docker-registry/helm.go). We seem to be setting the default value `10Gi` in the generated config. Considering workspace images can be large in size, it might be useful if we can support configuration of this value(`docker-registry.persistence.size`) from the installer config.

## Describe the behaviour you'd like

We should be able to set the size request of the `PVC` if the user has chosen `incluster` container registry option.

## Describe alternatives you've considered

Alternatively we could suggest a periodic cleanup job of old images as suggested by a [user on discord](https://discord.com/channels/816244985187008514/1006300442235515062/1006300446333337703).

**Comment by MrSimonEmms** [comment]
I had a look at this a few weeks ago as part of #9698 and it actually looks quite difficult to change a PVC now and support everything that's currently out there.

The in-cluster dependencies are not designed to be a one-size fits all solution for every use case. In reality, they're a limited solution to get people up and running quickly. There are so many configuration options out there that we could never expect to capture every nuance without placing a massive support burden on our team.

What we decided as part of the original issue was to document how to deploy their own DB/Registry/Storage to their cluster to their own requirements - see #11178.

What I would suggest is for the OP to check out the [Bitnami MySQL Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/mysql) and configure their own MySQL instance and use that instead of the Gitpod in-cluster configuration. From the KOTS config, this will be and `external` DB and the URL will be something like `mysql.db.svc.cluster.local:3306`
