### ISSUE TITLE
[ws-manager] - Operation cannot be fulfilled on pods "prebuild-<guid>": the object has been modified; please apply your changes to the latest version and try again

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12017]
### Bug description

It looks like a finalizer is being modified, failing and we trace as an error, and then successfully try again (refer to below picture).

[Logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-08-10T00:23:00Z;query=resource.labels.cluster_name%20:%20%2528%22us60%22%2529%0A-resource.labels.container_name%3D%22calico-node%22%0A%2269cd1a21-2d04-4f27-8528-f605fc580986%22;summaryFields=:false:32:beginning:false;timeRange=2022-08-09T23:48:26.037Z%2F2022-08-10T00:48:26.037Z?project=workspace-clusters)

Message: _Operation cannot be fulfilled on pods "prebuild-69cd1a21-2d04-4f27-8528-f605fc580986": the object has been modified; please apply your changes to the latest version and try again_

![image](https://user-images.githubusercontent.com/1272076/183785036-4eec0138-d244-4481-9ac9-053c0e56fd02.png)

### Steps to reproduce

Unknown

### Expected behavior

According to the trace, the operation is tried again, and was successful. Consider doing the trace, but, not as an error, if it successfully retries later.

**Comment by jenting** [comment]
> Message: Operation cannot be fulfilled on pods "prebuild-69cd1a21-2d04-4f27-8528-f605fc580986": the object has been modified; please apply your changes to the latest version and try again

It's because multiple workers are updating the same object resource at the same time.
- Worker A gets pod resource
- Worker B gets pod resource
- Worker A updates the pod resource first, and the `resourveVersion` updated
- Worker B updates the pod resource _without_ re-get the pod resource, and the error message occurs

So, that's the reason why we retry on conflict when conflict https://github.com/gitpod-io/gitpod/blob/d0627ab85e5b10fa867fe82b17f2f0b7ac37e569/components/ws-manager/pkg/manager/annotations.go#L184
