### ISSUE TITLE
Fonts or Images make file changed and makes wrong counts while committing

### ISSUE THREAD

**Issue by Swastyy** [gitpod-io/gitpod#12050]
### Bug description

When I open my fork of a repository as mentioned [here](https://github.com/apache/shardingsphere/issues/19536#issuecomment-1207251158) the files that contain static fonts or images gets counted in changed file and when I commit after the development of one file, these files also comes to committing stage making the changed files count to more than 400 which becomes hard to review the real changed file. I am attaching the screenshot of the bug here:
 
![image](https://user-images.githubusercontent.com/64654203/183990190-c2e8a559-a936-47a9-90fb-f6b991a4f8e8.png)

![image](https://user-images.githubusercontent.com/64654203/183989979-684f53b5-ad15-452b-8738-729b654ec5c9.png)

### Steps to reproduce

You can try opening the fork of [ShardingSphere](https://github.com/apache/shardingsphere) in gitpod.

### Expected behavior

Only the files changed should come to the committed stage and only be able to be pushed.

### Example repository

You can try opening the fork of [ShardingSphere](https://github.com/apache/shardingsphere) in gitpod.

**Comment by axonasif** [comment]
Hi @Swastyy, it's not a bug with Gitpod. It's just how `git` works, or was configured to work on your repo.

I assume that most maintainers of https://github.com/apache/shardingsphere use windows to develop and maybe that's why the committed files EOLs are `CRLF`. However, if you run `git diff` inside your Gitpod workspace, you will see what's happening actually. It's due the the [`.gitattributes`](https://github.com/apache/shardingsphere/blob/master/.gitattributes) rules of your repo.

**Comment by Swastyy** [comment]
Hey @axonasif , I get your point now. Thanks for explaining.
