### ISSUE TITLE
Negative credits in usage list view

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12064]
Something is wrong with the minutes -> credits computation.

<img width="1114" alt="Screenshot 2022-08-11 at 12 42 04" src="https://user-images.githubusercontent.com/849592/184126252-6fa941d2-f5b4-40b6-8902-c739b408d438.png">

**Comment by laushinka** [comment]
I investigated a particular workspaceId which was showing `-0.4`. The frontend received the negative amount from the server, while the credits entry persisted in `d_b_workspace_instance_usage` was not negative. 
After a few minutes of further investigation, I returned to the usage list, which now shows the correct number! The payload received by the frontend is also correct.
Apparently these negative values get corrected eventually, but how they came to be negative values in the first place still requires further investigation in the API.

I will unassign myself for now to allow others to pick it up, since I'll be focusing on other tickets.

**Comment by geropl** [comment]
@laushinka and I synced on this one:
 - we figure out that the DB stores negative values indeed, so we assume it's not the retrieval path that introduces these values
 - instead, we assume that `GenerateUsageReport` is wrong due false assumptions about timezones of it's parameters
 
I will try to produce a test and fix it.

**Comment by jankeromnes** [comment]
## Case study to verify the credits calculation

<img width="844" alt="Screenshot 2022-08-30 at 09 28 38" src="https://user-images.githubusercontent.com/599268/187376557-53198054-cd19-4331-b8d8-b2715c418b66.png">

This looks wrong, because 19.1 minutes of `g1-large` workspace should result in 19.1 / 3 = 6.37 credits. Instead, we have 0.1 credits. 🤔

Here is the usage record:

```json
{
  "attributionId": "team:c5895528-23ac-4ebd-9d8b-464228d5755f",
  "userId": "643ac637-74ae-4f82-9a86-c8527eb1e496",
  "projectId": "ef9d3f23-e5ab-4086-82f4-91813524bc3e",
  "workspaceId": "gitpodio-gitpod-8wvgb8p8tlv",
  "instanceId": "124b3f4e-3020-4529-8678-138d7c7c96c4",
  "workspaceType": "regular",
  "workspaceClass": "g1-large",
  "startTime": "2022-08-30T07:08:32.919Z",
  "credits": 0.11111111113333333,
  "contextURL": "https://github.com/gitpod-io/gitpod/pull/12376",
  "user": {
    "name": "Jan Keromnes",
    "avatarURL": "https://avatars2.githubusercontent.com/u/599268?v=4"
  }
}
```

- No `stopTime`?
- I guess usage accounting ran shortly after workspace start, so the usage record is ~19min outdated
- However, we show the duration based on the current dashboard time, which is wrong

**Comment by jankeromnes** [comment]
## Case study 2

<img width="822" alt="Screenshot 2022-08-30 at 09 59 36" src="https://user-images.githubusercontent.com/599268/187383061-59e3070b-1495-4457-bf5f-68f651932159.png">

- Negative credit
- (Same duration inaccuracy as above)

```json
{
  "attributionId": "team:c5895528-23ac-4ebd-9d8b-464228d5755f",
  "userId": "a5bfab1e-406f-4e6b-b1c6-8213be105eb5",
  "projectId": "ef9d3f23-e5ab-4086-82f4-91813524bc3e",
  "workspaceId": "gitpodio-gitpod-6i1tolj9jpg",
  "instanceId": "47d672cd-6370-4784-b52e-f7ccc13c79a3",
  "workspaceType": "prebuild",
  "workspaceClass": "g1-large",
  "startTime": "2022-08-30T07:39:34.099Z",
  "credits": -0.058333333344999995,
  "contextURL": "https://github.com/gitpod-io/gitpod/tree/main"
}
```

**Comment by geropl** [comment]
@andrew-farries I'm unsure in what state this issue is in. Can we close it? :thinking:

**Comment by andrew-farries** [comment]
Yes, let's close it. It's obsolete now given the move to the ledger-based reconciler.
