### ISSUE TITLE
Stuck on acquiring node

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1216]
### Describe the bug
title
its been stuck like this for 5 minutes
I tried deleting and remaking workspace, but nope

cc @jankeromnes

**Comment by jankeromnes** [comment]
Thanks @RDIL for reporting this. There seems to be an issue with the US cluster, so we're re-routing traffic to the EU while we investigate.

**Comment by alesanchezr** [comment]
Hey @jankeromnes my worskpace is stuck and I can't access the files I had there. is it posible to stop it to start it again?

**Comment by JesterOrNot** [comment]
I'm looking into it could be the .gitpod.yml

**Comment by jankeromnes** [comment]
There seems to be a new bug in our workspace manager, likely due to this morning's regular deployment. The bug only appears under pressure, e.g. usage ramp leading to cluster scale-up.

This causes workspaces to get stuck in "Acquiring Nodes" and/or "Pending".

We are rolling back production to the previous version, where the workspace manager didn't have this bug.

@alesanchezr I agree that a "force stop" would be cool. However, the problem here is with the workspace manager itself, i.e. it would likely fail to even do the "force stop" action.

**Comment by JesterOrNot** [comment]
@alesanchezr I think I got it working 
![image](https://user-images.githubusercontent.com/50386709/74361739-110ccb00-4d8d-11ea-9af8-e65fe5d7f15e.png)
I've prepared a small PR
https://github.com/breatheco-de/content/pull/123

**Comment by alesanchezr** [comment]
OMG I love you @JesterOrNot 😄 
Thank you for the so responsive and amazing help!

**Comment by jankeromnes** [comment]
Update: Gitpod.io rollback is live, we're no longer seeing the root cause error, so the service is now recovering.
