### ISSUE TITLE
Can not start workspace by old link

### ISSUE THREAD

**Issue by artalar** [gitpod-io/gitpod#1219]
### Describe the bug
Can not start workspace by old link

### Steps to reproduce
I have the **pinned** workspace (for work with [reatom](https://github.com/artalar/reatom)) and some time ago (yesterday or early) I was open it and save it in bookmarks by a link from url. Today I tray to open the link and application startup is failed:
Go to https://e98ddccc-1966-4280-9c26-a782b812427f.ws-eu01.gitpod.io
![image](https://user-images.githubusercontent.com/27290320/74402739-31449480-4e36-11ea-8eda-5a0e7465d058.png)

### Expected behavior
URL to same workspace instance is never changing

### Additional Information
After that, I go to https://gitpod.io/workspaces/, find needed workspace and open it by a new link: https://e98ddccc-1966-4280-9c26-a782b812427f.ws-us02.gitpod.io/#/workspace/reatom. But it is not not obvious.

### Example Repository
https://github.com/artalar/reatom

**Comment by jankeromnes** [comment]
The error code `302` on the WebSocket is an HTTP redirection.

Maybe you were logged out of Gitpod, and it was trying to redirect you to the login page? In that case, I think a "hard refresh" (i.e. <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd>, or <kbd>Shift</kbd> + click `Refresh` button) would solve it, because it wouldn't take the page from cache but properly redirect you to login.

Also, may I ask why you bookmark an old workspace? We believe it's better to always create new workspaces for your work (i.e. commit and push everything to a remote branch when you're done). That way you make sure that you always get a fresh, up-to-date environment to work in.

**Comment by artalar** [comment]
`why you bookmark an old workspace?`
I work on pretty hard task and 1 commit with few lines of code may took of me from one to few days of work.

**Comment by svenefftinge** [comment]
We had to remove the EU cluster yesterday, due to a problem we faced. In those cases workspaces will be started on other clusters (US in your case). The URLs do reflect that, indeed, so you'd better start from gitpod.io/workspaces if you want to restart old workspaces. sorry for the confusion.

**Comment by artalar** [comment]
Ok, thx
