### ISSUE TITLE
Fix the workspace integration tests

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#12248]
### Bug description

The workspace integration tests continue to fail
Now it failed:

- [x] Pass all tests in a row from local
- [x] Pass all tests in a row from werft
- [x] Ensure branch deleting to avoid remaining many preview env

### Steps to reproduce

Run the integration test

### Expected behavior

The workspace integration tests pass every day 👍 

### Anything else?

[Last failed run](https://gitpod.slack.com/archives/C03E52788SU/p1661162310890499)

**Comment by kylos101** [comment]
Thanks @utam0k ! 

I updated the description to account for some additional recent failures, and added this to Scheduled.

**Comment by kylos101** [comment]
👋 hey @utam0k , may I ask, is there a draft PR for which you can link to this issue? Let us know if you need any help? 🤗

**Comment by utam0k** [comment]
@kylos101 It took me a while to realize I was falling short of preview env's resources, but so far I don't need any help. Thank you.

**Comment by kylos101** [comment]
@utam0k may I ask a favor? Can you alter the script which triggers test runs, so that it deletes prior branches, prior to starting? In this way, we can be sure we do not start too many preview VMs. [Internal reference.](https://gitpod.slack.com/archives/C01KGM9EBD4/p1662793389381669?thread_ts=1662621986.692229&cid=C01KGM9EBD4)

**Comment by kylos101** [comment]
Related: https://github.com/gitpod-io/gitpod/issues/12021#issuecomment-1243069224

**Comment by utam0k** [comment]
> @utam0k may I ask a favor? Can you alter the script which triggers test runs, so that it deletes prior branches, prior to starting? In this way, we can be sure we do not start too many preview VMs. [Internal reference.](https://gitpod.slack.com/archives/C01KGM9EBD4/p1662793389381669?thread_ts=1662621986.692229&cid=C01KGM9EBD4)

[At the end of the integration script](https://github.com/gitpod-io/gitpod/blob/d4fe26f45f7c8ba281bc93e0f9e2d08e2a0d7a0a/.werft/workspace-run-integration-tests.sh#L63) runs delete a branch that the script creates. I wonder why deleting branch code sometimes isn't run. I guess it relates to this issue.
https://github.com/gitpod-io/gitpod/issues/12795

And I have added a workaround for this issue yet. Your suggestions are excellent. However, can we just take a look at the situation a bit?
https://github.com/gitpod-io/gitpod/pull/12793

**Comment by kylos101** [comment]
> I guess it relates to this issue. https://github.com/gitpod-io/gitpod/issues/12795

I am not sure @utam0k. Let's ask Mads.

@mads-hartmann , what do you think Re: #12795 causing too many preview VMs to be created?

> [At the end of the integration script](https://github.com/gitpod-io/gitpod/blob/d4fe26f45f7c8ba281bc93e0f9e2d08e2a0d7a0a/.werft/workspace-run-integration-tests.sh#L63) runs delete a branch that the script creates.

@utam0k , what if we exit the script early, before branch delete? :thinking: Would that avoid garbage collection of branch and preview?

> And I have added a workaround for this issue yet. 

Ok :cool: 

> However, can we just take a look at the situation a bit?

Has the issue happened (where too many VMs are created) occurred since you did #12793? 

@mads-hartmann what do you think? Should we delete prior branches at the beginning? It seems like a small yet good proactive change, to avoid overwhelming Harvester VMs.

**Comment by kylos101** [comment]
@utam0k can you update the description, so that we can tell current status, and remaining plans?

**Comment by mads-hartmann** [comment]
> what do you think Re: https://github.com/gitpod-io/gitpod/issues/12795 causing too many preview VMs to be created?

I'm really mystified by that issue to be honest. It could be that it is causing more branches/VMs to be created. I would expect https://github.com/gitpod-io/gitpod/pull/12793 to have resolved that though ☺️

> what do you think? Should we delete prior branches at the beginning? It seems like a small yet good proactive change, to avoid overwhelming Harvester VMs.

Yeah I think that would be the most robust solution for now ☺️

**Comment by utam0k** [comment]
@mads-hartmann @kylos101 I omitted to take into account the case where a job was forcibly deleted due to a timeout in the middle of the process. Presumably the job will be forced to terminate in about 2 hours, right? The branch is not erased at that time, right?
By the way, do you have a good idea to create a preview environment for testing without creating a branch?

**Comment by utam0k** [comment]
> @utam0k can you update the description, so that we can tell current status, and remaining plans?

I updated it

**Comment by mads-hartmann** [comment]
> I omitted to take into account the case where a job was forcibly deleted due to a timeout in the middle of the process. Presumably the job will be forced to terminate in about 2 hours, right? The branch is not erased at that time, right?

Yeah, this is why I think it will make things more robust if you delete stale branches at the beginning of the job ☺️ In the best case there won't be anything to clean up, but if there is some edge case we weren't aware of that is causing the cleanup logic to not run, then at least we know the next job would clean it up ☺️

> By the way, do you have a good idea to create a preview environment for testing without creating a branch?

It's possible now, but's its not quite intentional that it works I'd say. If you create a brach off main and use the Werft CLI then it will actually work even if you never pushed the branch (see example [here](https://github.com/gitpod-io/gitpod/blob/08650a7b7553d7796cbf1b452483ebc5e886df5d/.werft/platform-trigger-artificial-job.sh#L18-L20)).

However, a preview environment without a branch will get garbage collected quite quickly so I wouldn't recommend doing so. Properly supporting preview environments that are not coupled to specific branches is something we'd like to support int he future ☺️
