### ISSUE TITLE
You've been blocked. Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by wolfy01** [gitpod-io/gitpod#1227]
Is it possible that I could get the reason for this? I would like to know what I did wrong, and if possible, have another chance

**Comment by jankeromnes** [comment]
Hi @wolfy01! Thank you for reaching out.

The block happened because our system detected what seemed like Denial-Of-Service attacks launched from one of your workspaces this morning between 05:00 and 06:00 UTC. Please note that this is against our [Terms of Service](https://www.gitpod.io/terms/), and that Gitpod is meant for development.

I've just removed the block, and apologize if this was a mistake. If you have any question, concern, or feedback, please feel free to reach out to contact@gitpod.io

Happy coding! I hope that you'll continue to enjoy Gitpod. 🙂

**Comment by wolfy01** [comment]
Hi @jankeromnes, sorry if this seemed like a Denial-Of-Service attack, I made a proxy bot for a site, may have been a bit overkill. I will take this into account in future projects.... Sorry D:
