### ISSUE TITLE
[UBP ] Allow users to apply promotion codes for coupons in the UBP payment form

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#12341]
### Problem to solve

Some Gitpod programs will use Stripe coupons with predefined discounts and expirations. 

Entering these coupons manually (by Gitpod admins) is doable through the Stripe dashboard, but it would be better if this were self-serve, and users could perform this actions on their own while setting up their billing account in Gitpod.

Unfortunately, Stripe promotion codes cannot be used in the Stripe self-service Portal in our case. Customers can only use the portal to cancel (not modify) their subscriptions. See https://stripe.com/docs/customer-management/get-started#limitations

This suggests that we need to extend our payment configuration form to accept promo codes on initial configuration.

See investigation in comments below, and [discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1661344777291019?thread_ts=1661344576.731279&cid=C027AUU7BC3) (internal).

An ideal solution would be one where a promo-code could be applied not just during the initial signup, but also later once the subscription is active.

**Comment by jankeromnes** [comment]
Hmm -- according to the [Stripe docs](https://stripe.com/docs/billing/subscriptions/coupons#promotion-codes), it seems that promotion codes can only be added in a "checkout" flow, which we don't use (we only use a "setup" flow, where you add your credit card details, and your subscription is then created automatically by Gitpod behind the scenes).

I think that's why, even though we do allow Stripe users to use promotion codes:

<img width="755" alt="Screenshot 2022-08-24 at 14 53 48" src="https://user-images.githubusercontent.com/599268/186424339-3b0a4468-2af1-4515-b4af-4e75005f92a3.png">

there doesn't seem to be any way in the Stripe customer portal to add a promotion code to your existing subscription:

<img width="1440" alt="Screenshot 2022-08-24 at 14 58 35" src="https://user-images.githubusercontent.com/599268/186424553-7aaba7e9-c566-411f-b314-6748d17cf86a.png">

I think we may need to have some custom UI to apply coupon codes, maybe. 🤔

**Comment by jldec** [comment]
According to https://stripe.com/docs/billing/subscriptions/coupons#promotion-codes

> If you’ve implemented the [customer portal](https://stripe.com/docs/billing/subscriptions/customer-portal) and turned on promotion codes, customers can apply a discount to their existing subscriptions in the portal.

**Comment by jldec** [comment]
More research reveals that promotion codes cannot be used in the Stripe Portal in our case customers can only cancel their subscriptions. See https://stripe.com/docs/customer-management/get-started#limitations

This means that the promo code would have to be entered earlier, when first setting up the subscription.

**Comment by gtsiolis** [comment]
@jldec Could it help if we added a functionality to _Add funds_ to the billing balance and use a promo code there? 

To clarify, the initial idea of the proposal of this issue was to allow users to add funds but with a discounted price or no price at all, not apply a discounted rate or something.

**Comment by jldec** [comment]
Thanks for the suggestion @gtsiolis 

This issue is specifically to enable self-service use of Stripe promo codes by extending our payment form. We need all the nice coupon features built into Stripe e.g. expirations, and single-use 

There's a separate issue to extend our credits model with our own coupon-like behavior, which would allow Gitpod or 3rd parties to grant credits, and maybe your suggested approach would make sense for that.

**Comment by jldec** [comment]
@gtsiolis I updated the issue title and description to reflect this new information.

**Comment by gtsiolis** [comment]
Thanks, @jldec !
