### ISSUE TITLE
Make use of `final_backup_complete ` workspace condition

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#12387]
As a follow-up to https://github.com/gitpod-io/gitpod/issues/11453 this is about introducing a clear signal from ws-manager that a workspace hasn't gotten any backup. This is important information to signal to users, because such workspaces are broken and we should also forbid starting them (resulting in):
<img width="389" alt="Screenshot 2022-08-25 at 14 14 39" src="https://user-images.githubusercontent.com/372735/186668631-fada8282-7eb0-464c-95e1-a64e77eefafb.png">

**Comment by svenefftinge** [comment]
@sagor999 Is the `final_backup_complete` WorkspaceCondition always sent when a backup happened? I.e. can we rely on treating workspace instances for which we never received this condition to have no backup?

**Comment by sagor999** [comment]
Timely issue, thanks Sven!
I had a similar discussion with @geropl about this and we had a plan to introduce condition `hasBackup` to signal when backup was created. 
I was going to work on this today so this is a great reminder to implement this. 😀
More info to follow later today.

**Comment by sagor999** [comment]
@svenefftinge you are right, we can totally use `final_backup_complete` condition.
This PR #12408 improved reliability of that condition by making sure it is set to true correctly.
So once that is merged, server instead of this code:
https://github.com/gitpod-io/gitpod/blob/0699f84aba13019cbdb3c13dce79b2d33541a56f/components/server/src/workspace/workspace-starter.ts#L334-L336
Should use something like this:
```
const hasValidBackup = pastInstances.some( 
     (i) => !!i.status && !!i.status.conditions && i.status.conditions.final_backup_complete, 
 ); 
```
We should probably either use it only for workspaces created after X timestamp (once #12408 is deployed) or maybe fix DB to ensure `final_backup_complete` is set correctly for old workspaces? Not sure which approach would be better. Or if there is a better alternative.

**Comment by geropl** [comment]
Thank you @sagor999 for letting us now about https://github.com/gitpod-io/gitpod/pull/12408! From the data I saw I thought it has already been abandoned - good to have it back! :lotus_position:

**Comment by kylos101** [comment]
@sagor999 looks like webapp has related work Scheduled for this issue, let's leave this In-Validation until that is deployed. 👍 

@geropl 🙏 thank you for Scheduling related work! As an FYI, we're tracking this in our In-Validation column, so we'll bump into and check/review it weekly.

**Comment by jenting** [comment]
Assign to @sagor999 to validate it 🙇‍♂️

**Comment by sagor999** [comment]
I am marking workspace task as Done, since workspace part is complete at this point.
