### ISSUE TITLE
How to scale GUI apps depending on the preview size?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1239]
### Current

![image](https://user-images.githubusercontent.com/11302521/74844922-7da83c80-532e-11ea-9b24-b7c4a56b4a9a.png)

### Expected

![image](https://user-images.githubusercontent.com/11302521/74845057-b2b48f00-532e-11ea-8452-c6366941931c.png)

---

I need some solution to make diagrams willing to change the software if there is something better.

**Comment by jankeromnes** [comment]
Hi @Kreyren, excellent point. I've been meaning to do something here for a while now, because I think it's quite unfortunately that the noVNC virtual desktop doesn't automatically resize with the preview pane.

One flagrant example is https://github.com/techwithtim/Hangman/, a really cool Python demo that can be started automatically in Gitpod, however the Hangman game window opens in the center of the virtual desktop, so it's not visible by default in the preview pane (unless you know that you should expand it or maximize it).

See also #303, in which we identified a promising noVNC option called `resize`:

https://github.com/gitpod-io/gitpod/issues/303#issuecomment-463275662

However, it didn't work in our experiments, and we're not sure why. It would be great to resume these experiments, and see if this can be troubleshooted & fixed, because the current fixed-size virtual desktop in which you have to scroll around is just bad UX. (What's worse, scrolling in the virtual desktop also switches between 4 virtual desktops... which is super confusing and useless).

**Comment by jankeromnes** [comment]
More related to your question though, I think that once we have a virtual desktop with an auto-adaptive size, any GUI apps that's maximized should also follow the preview dimensions... hopefully.

**Comment by Kreyren** [comment]
## Self-Diagnostics

### Autoscale function?
noVNC apparently supports autoscale (https://github.com/novnc/noVNC/issues/763)

Research required.

**Comment by Kreyren** [comment]
ping @jankeromnes Running https://6080-....gitpod.io/vnc.html with following configuration fixes the issue. Is that usable for gitpod implementation?

![image](https://user-images.githubusercontent.com/11302521/74875404-77cc4e80-5362-11ea-965d-d0247b598e36.png)

**Comment by jankeromnes** [comment]
Amazing, thank you so much @Kreyren for researching this! 🎉 🙏 💯 

I don't have time to test it now, but if this works well we should probably make that the default behavior in Gitpod, e.g. via a noVNC `launch.sh` option in:

https://github.com/gitpod-io/workspace-images/blob/8a146a2cf092181723e63979e58605a413f84115/full-vnc/start-vnc-session.sh#L15

(assuming the desired configuration can be passed via CLI options there -- if not we'll have to find another way)

I can take a look at this tomorrow. Huge thanks again for driving this toward a fix, I've been waiting for an auto-resizing noVNC for so long now... 😲

**Comment by JesterOrNot** [comment]
@Kreyren Awesome 💯

**Comment by JesterOrNot** [comment]
I'll look into preparing a PR

**Comment by jankeromnes** [comment]
Thanks a ton for the fix @JesterOrNot! 🙏 🎉

I just merged the fix, so this should land in production as soon as the `master` build is through (E.T.A ~30min I think).

**Comment by Kreyren** [comment]
@jankeromnes note https://github.com/novnc/noVNC/issues/1370#issuecomment-588687241
