### ISSUE TITLE
file can't save

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/gitpod#1254]
### Describe the bug

file can't save

### Steps to reproduce

Save file (ctrl + s)

### Expected behavior

File is saved

### Additional information

Does not occur every time
Once that happens, the file can't save.
![image](https://user-images.githubusercontent.com/38714187/75089364-49858380-559b-11ea-8709-19b6b09c45b6.png)

**Comment by jankeromnes** [comment]
Hi @mouse484, thank you for reporting this problem, and especially for providing a screenshot of the full error message. 👍 Also, we're very sorry for the disruption to your work.

I think that this problem was due to a full disk in the `ap01` cluster, see #1255. This should now be fixed. Please try again. Also, if saving still doesn't work, please comment here or re-open this issue.
