### ISSUE TITLE
Error when starting workspace

### ISSUE THREAD

**Issue by geoffpopple** [gitpod-io/gitpod#1255]
### Describe the bug
cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/f3c929b1-ce3f-4f58-b60a-2574397d0e4b: no space left on device
Please file an issue if you think this is a bug.

### Steps to reproduce
Start the workspace

### Expected behavior
Workspace to start

### Additional information
https://abf0a1d4-00e8-443e-ac13-76a8e8220c25.ws-ap01.gitpod.io/

### Example repository
abf0a1d4-00e8-443e-ac13-76a8e8220c25
Scoreboard - master

**Comment by jankeromnes** [comment]
Hi @geoffpopple, thank you for reporting this. We're investigating.

**Comment by jankeromnes** [comment]
This is now fixed, please try again. We apologize for the disruption, and we'll make sure that similar problems cannot reoccur in the future.

Details: One server in our `ap01` cluster had a 100% full disk. It contained a temporary copy of a 150GB workspace(!) Removing the temporary copy fixed the problem. Also, we're implementing proper disk quota enforcement so that workspaces cannot grow indefinitely large (by accident or otherwise). This should go to production next Wednesday.
