### ISSUE TITLE
Rate-limited by github bottlenecks gitpod?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1257]
Based on following i believe that i am being rate limited by github when i am working on complicated projects (this happens after every new commit)
![image](https://user-images.githubusercontent.com/11302521/75101732-8ecca400-55e1-11ea-897a-c7c46f2f3c01.png)

This seems to transfer on gitpod which results in same issue:

![image](https://user-images.githubusercontent.com/11302521/75101720-6cd32180-55e1-11ea-8a0e-b613ccc257d3.png)

Which results in freezes every few mins while the new commit is being processed for up to 2 minutes.

I assume this is caused by gitpod waiting for GitHub API to process the request or something? If so is there a way to prevent gitpod from freezing?

Affected merge request https://github.com/RXT0112/RXT0112-3/pull/2

### Steps to reproduce
1. Push a new commit
2. Notice the instability (seems to happend when bots are processing the commit)

**Comment by Kreyren** [comment]
Further evidence on this theory 
![image](https://user-images.githubusercontent.com/11302521/75102048-25e72b00-55e5-11ea-97c4-b4cdddd990e2.png)

**Comment by jankeromnes** [comment]
But the yellow warning seems to indicate that some tab in your browser is going crazy on CPU, thus slowing down the entire browser.

Have you checked `about:performance` if you're using Firefox?

**Comment by jankeromnes** [comment]
The Gitpod errors seem weird though. Does the browser devtools console show any interesting errors?

**Comment by Kreyren** [comment]
> Have you checked about:performance if you're using Firefox?

I was checking htop where the utilized system resources were around 43% on CPU where i had X amount of tabs open where only gitpod and github were showing this after issue specifically after a commit for up to 5 mins (seems to get worse depending on the amount of bots and code changes).

I've reproduced the issue to check `about:performance`:
![image](https://user-images.githubusercontent.com/11302521/75105267-eaaf2100-5611-11ea-9f7c-e6907cc6adf9.png)

> The Gitpod errors seem weird though. Does the browser devtools console show any interesting errors?

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2:1:1
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!
```

This error is present only after new commit is made or there is an interaction with git i.e `git pull`, it is not present otherwise

---

Once gitpod recovers from this freeze it outputs following in the console https://gist.githubusercontent.com/Kreyren/068962222bfa0972a47a43f0f39c6209/raw/89cfa5c48a375906b6136cbcffb7e5c30d301790/asgasgaas

I assume that it just goes full panic mode after waiting for response from git/Github API ?

I believe that i have same issue on https://github.com/RXT0112/Zernit where this is happening for few seconds after new commit. This is a significantly smaller repository at this time so i assume there is a relationship between the amount of files and this issue.

**Comment by Kreyren** [comment]
Sidenote: I am using debian dockerimage where this issue is present on gitpod's image as well.

**Comment by Kreyren** [comment]
I also believe that the issue is not present if workflows are disabled, but this needs more investigation to confirm.

**Comment by jankeromnes** [comment]
Thanks for these additional details!

> I've reproduced the issue to check `about:performance`:

Hmm. It looks like the YouTube tab is using a lot of CPU. Does this issue also reproduce when you don't have any YouTube tabs open? (Also, note: I think `about:performance` actively collects perf data from tabs, so results may become clearer / more relevant after running for several seconds.)

> This error is present only after new commit is made or there is an interaction with git i.e `git pull`, it is not present otherwise

Then it seems to me that, contrary to what `about:performance` shows, it may be the Gitpod tab that's going crazy on CPU (or maybe a browser extension).

- Do you have any particular VS Code extensions installed for this project? (E.g. maybe one extension is badly written, and does a ton of JavaScript processing whenever there are Git updates.)
- Do you have any browser extension that could interfere in Gitpod? (E.g. something like Grammarly or other content-processing extension.)

> I assume that it just goes full panic mode after waiting for response from git/Github API ?

I believe that any communication with GitHub (except the brief initial OAuth login flow) happens in the back-end, i.e. such a bug would mean it's Gitpod's server panicking about GitHub API problems, while your browser front-end would be 100% ok.

Instead, your problem seems to be that something does a lot of JS processing in the front-end. Maybe you could use the Firefox Profiler, e.g. by starting a profile, then reproducing the issue, then stopping the profile? You can then analyze your profile, or upload it to https://profiler.firefox.com/, or send it to us for analysis (we're happy to take a look). The goal would be to identify what JS code / function / symbol is responsible to essentially DOS'ing your browser.

**Comment by Kreyren** [comment]
I was busy so i couldn't check it, but it seems that the issue fixed itself.

Will reopen if it happens again and provide the required info.
