### ISSUE TITLE
Feedback Issue: Usage-based billing

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12636]
Invite comments and questions from early access users of usage-based billing. 
See #9036 for more details.

**Comment by david-bakin** [comment]
Feature improvement request: _Per-project_ setting of workspace class.  Because different projects have different needs.

Bonus points: Allows more than one _project_ for same _repo_: Because different _uses_ of the same _project_ have different needs. (I.e., large workspaces may only be needed for certain regression runs, or certain debugging situations, or whatever.)

**Comment by david-bakin** [comment]
Feature improvement request: _Per-launch_ setting of workspace class.  Because different projects have different needs and also different _uses_ of the _same_ project have different needs.  (See above comment, except this is an alternate/additional way to go about it.  I wouldn't my specifying for _each_ launch (e.g., from a dropdown part of the button) but it could be combined nicely with defaults too.)

**Comment by david-bakin** [comment]
(Giving each suggestion as a separate comment so they can be "voted" on separately by people giving feedback here ...)

**Comment by david-bakin** [comment]
Feature improvement request: Being able to keep a _Professional_ plan (unlimited hours on "standard" workspaces) but being able to boost to a "large" workspace on demand (e.g., at workspace launch) - billing for the credits used.
