### ISSUE TITLE
VM Support

### ISSUE THREAD

**Issue by BSFishy** [gitpod-io/gitpod#1265]
Support for running virtual machines inside of Gitpod would be awesome. For example, using something like VirtualBox to create and run a virtual machine inside of the Gitpod workspace.

This is related to #1251 and is the issue blocking that functionality. In that issue, virtual machines have been discussed and decided to be put into another issue.

There are [security concerns with VirtualBox](https://www.cybersecurity-help.cz/vdb/SB2018110701?affChecked=1), although more recent versions do not appear to be listed under the vulnerable versions. Maybe there should be some more investigation.

@Kreyren supposedly did some testing with QEMU/KVM, although I'm not sure how far he got.

**Comment by Kreyren** [comment]
> @Kreyren supposedly did some testing with QEMU/KVM, although I'm not sure how far he got.

I've got it working to a reasonable degree, waiting for upstream to process the info

> There are security concerns with VirtualBox, although more recent versions do not appear to be listed under the vulnerable versions. Maybe there should be some more investigation.

VirtualBox is for security reasons mensioned in https://github.com/gitpod-io/gitpod/issues/1251#issuecomment-589881514 not an option untill this is resolved which is doubtful assuming current oracle maintainance and concerns mensioned in https://wiki.debian.org/VirtualBox thus there should be a tracking for this and we should consider implementation after this issue has been fixed and after the software has been peer-reviewed by trustworthy whitehats.

**Comment by BSFishy** [comment]
@Kreyren So would the KVM/QEMU combination be viable for running VM's in Gitpod? What sort of features are missing, if any? Is there anything stopping it from being fully usable inside of Gitpod?

**Comment by Kreyren** [comment]
> So would the KVM/QEMU combination be viable for running VM's in Gitpod? What sort of features are missing, if any?

As mentioned in https://github.com/gitpod-io/gitpod/issues/1251#issuecomment-589881514 it's possible assuming the usage of libvirt provider in vagrant that requires providing `/dev/kvm` (meaning loaded kvm kernel module) for udev to be able to create `/var/run/libvirt/libvirt-sock` to fix this issue on environment https://github.com/Kreyren/gitpod-tests1/tree/809456e4bf16825911b1e5f4e1695d9c210f8466.

> What sort of features are missing, if any? 

None that i am aware of on current docker setup, but rootless docker setup has been proposed (to enforce a security of containers) which has known limitations mentioned in https://docs.docker.com/engine/security/rootless/#known-limitations with which we may be able to workaround depending on the usecase.

---

Generally i would recommend running gitpod nodes on KVM assuming hardened system with livepatching functionality by default where vagrant can be used instead of docker which would in theory provide a better security, performance and avoided the issue with docker limitations since vagrant supports docker which would even allow gitpod users to use Linux/GNU, Darwin/XNU, (possibly windows and windows with cygwin), FreeBSD/GNU, Redox/GNU systems as a node for gitpod.

See [sourcehut](https://meta.sr.ht/) for example of this in practice on a production system.

As a sidenode current docker configuration is compatible with proposed setup assuming default gitpod vagrantfile provided with a backend to handle docker.

**Comment by Kreyren** [comment]
@geropl Can you provide more info on gitpod support for virtualization? Some timeline tracking would be nice for this so that i can adapt my projects for this limitation..

**Comment by geropl** [comment]
@Kreyren Sorry for the misunderstanding. We're not working on allowing virtualization inside Gitpod but looking into virtualization techniques for hosting Gitpod workspaces themselve. Virtualization _inside_ workspaces _might_ be a by-product, but is certainly not a primary goal. Thus I cannot give you a timeline.

**Comment by chiyanglin-AStar** [comment]
I have another type issue:   I try to do some code in gitpod , like web ui ,  but I need qemu machine as host ,    is there any comment about what kind of setting about gitpod ?   some other constraints , qemu 2443 is for web ui restful api request !

**Comment by faermanj** [comment]
This would allow us to run entire clusters inside gitpod, sad it's closed :/

**Comment by GitXpresso** [comment]
It weird they have an empty directory called hypervisor in the root directory in /
