### ISSUE TITLE
Avoid double-charges when chargebee plans are cancelled and replaced with UBP

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#12675]
For the migration case Chargebee -> UBP it makes sense to pro-rate paid plans on cancellation, to avoid people having to pay twice for a given period of time.

**Comment by svenefftinge** [comment]
Could we maybe not store an attributionID if the billingMode is not UBP? That way they would not end up in the ledger table.

**Comment by jldec** [comment]
We are trying to avoid the following situation 

- A team or individual cancels their prepaid Chargebee plan in order to upgrade to postpaid usage-based billing.
- No UBP usage shows up until the end of the Chargebee billing period because those subscriptions currently continue running after cancellation, until the prepaid period has ended.

See internal disucussions [here](https://www.notion.so/gitpod/Usage-Based-Pricing-Early-Access-e10c701ecc4247e28bd86c42c9bfb238#40a7a5e72cdc4f7aa29fc74f1b91ff9b) and [here](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#320aea5fe3d34aecb008d3cca0d311db).

**Comment by geropl** [comment]
I setup a preview environment [here](https://gpl-12675-proration.preview.gitpod-dev.com/plans) and tested with the following settings modified:
![image](https://user-images.githubusercontent.com/32448529/192481114-caccd488-9222-4289-9824-29bf97d2ed41.png)

For context: We didn't do this initially when implementing Chargebee integration to prevent abuse scenarios, and instead did "proration" in-product.

I tested with individual plans, and that works great so far.
Example: https://gitpod-test.chargebee.com/customers/55383133/details#invoices

Open questions:
 - [ ] How well does this work with seat-based team subscriptions/memberships?
 - [ ] Are there any in-product proration mechanisms that we need to disable?

**Comment by geropl** [comment]
Tested a bit with Team Subscriptions:
 - old, seat-based subscriptions work :heavy_check_mark: 
 - new, membership based subscriptions work :heavy_check_mark: 
   - Charges for during-the-month upgrades are not refunded on downgrade, because Chargebee doesn't do proration on unbilled charges ([source](https://www.chargebee.com/docs/2.0/unbilled-charges.html#faq_how-is-proration-applied-on-unbilled-charges)). But that's the same as before. :+1:

**Comment by geropl** [comment]
Enabled proration in prod:

![image](https://user-images.githubusercontent.com/32448529/192948670-4632bce0-f369-4b94-9b30-31c95011dd71.png)
