### ISSUE TITLE
Cannot create sandbox

### ISSUE THREAD

**Issue by martin0607** [gitpod-io/gitpod#1267]
Describe the bug:
Workspace won't start due to this problem.
Steps to reproduce:
Login and start gitpod
https://bba1e5f3-8c34-47d6-8d06-7b5384c6b946.ws-ap01.gitpod.io/
Result:
![1](https://user-images.githubusercontent.com/32560181/75320428-9faf3b00-58a9-11ea-933d-a307a9b73db7.png)

Cannot create sandbox.

**Comment by Kreyren** [comment]
Disclaimer: I am not gitpod staff, trying to help based on my own experience

> Login and start gitpod
> https://bba1e5f3-8c34-47d6-8d06-7b5384c6b946.ws-ap01.gitpod.io/

This is not helping since this instance has been created for you, which is not shared
![image](https://user-images.githubusercontent.com/11302521/75399002-6b646a80-58fb-11ea-97ea-dce59038f25e.png)

Which would require following on your end:
![image](https://user-images.githubusercontent.com/11302521/75399130-c302d600-58fb-11ea-8483-10435c4e95e3.png)

Red to share a snapshot of your current workplace (anyone can open this snapshot assuming that you provide the url to them and gitpod will open the exact same state of the editor to them)

Green being an alterantive which allows sharing the same workspace while it's running with a third party to which you shared the URL.

> Workspace won't start due to this problem.

To me it seems as possible pebcak on user-end due to the insufficient error message from an upstream -> **Can you share your gitpod configuration?**
