### ISSUE TITLE
Performance test PVC with a cluster saturated with workspaces

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12747]
## Is your feature request related to a problem? Please describe

We should test how a node behaves when it is full of workspaces using PVCs, where there is disk activity in the workspaces, and many workspaces are starting, running, and stopping. 

The # of regular workspaces we decide to run as part of this test should be 125% of the peek volume we saw in our EU cluster over the last month. 

## Describe the behaviour you'd like

1. Start a regular workspace in the cluster using PVC on a single node.
2. Run loadgen, once to fill half of the cluster to capacity
3. Run loadgen 
Begin to stop the first loadgen run & start the second one with ~20 workspaces

## Additional context

We haven't run with PVC snapshot or restore at scale, yet.

**Comment by sagor999** [comment]
It worked without issues.
Tested with loadgen with 20 workspaces, then with 30, then  with 100. (20 and 30 with stop and start at the same time).

**Comment by kylos101** [comment]
@sagor999 why 100 workspaces, instead of 125% of our peek volume in the last month? :thinking: I would feel comfortable, even though it will cost to run the test, that we can handle that related volume. This way we're not doing for the first time in production. :sweat_smile: 

Can you show the start and stop graphs from the overview dashboard, so we can peek at what those shapes look like? For example, I don't assume they'll be much different than now...but am curious to confirm/compare.

Also, can you share how we're supposed to do related clean-up after testing in our loadgen readme.md? This will be good for the future.

Lastly, if you could add this to our project and set status, that would be :ok_hand: , too! :bow:

**Comment by sagor999** [comment]
@kylos101 was concerned about the cost. But if you are ok with it, I can do loadgen with 700 workspaces. ok?
![image](https://user-images.githubusercontent.com/18602811/192063758-25ba48ae-24d1-4519-ad74-e1cd6ea5dbcd.png)
Here is the graph of workspace start up. It does look the same as regular workspaces to me.

**Comment by kylos101** [comment]
:wave: @sagor999 thanks for sharing bud, I am okay with the cost :+1: :+1: , especially it finds issues or mitigates risk. Could you do 900? We recently hit 830. :rocket: So long as you can delete snapshots after, we should be :ok: .

**Comment by kylos101** [comment]
Hi @sagor999 , it looks like we have [an issue](https://github.com/gitpod-io/gitpod/issues/13353), sometimes, and, we're unsure if it's related to load. 

For now, I recommend the following:
1. Close this issue, 12747
2. In https://github.com/gitpod-io/gitpod/issues/13353, run a load test [with a large number of workspaces](https://github.com/gitpod-io/gitpod/issues/12747#issuecomment-1256729588), to see whether that stress causes trouble.

**Comment by kylos101** [comment]
As #13353 was resolved, I recommend proceeding with a load test of large scale. :dancers:

**Comment by jenting** [comment]
> 

Pavel asked me to load test with 1000 regular workspace.

**Comment by jenting** [comment]
> As #13353 was resolved, I recommend proceeding with a load test of large scale. 👯

Pavel asked me to load the test with 1000 regular workspaces.

**Comment by kylos101** [comment]
👍 makes sense, you might need to increase the quota beforehand. Please submit a request a few days prior to increase the quota. @vulkoingim shared some advice on how to do, if you have any trouble or questions, let me know?

**Comment by vulkoingim** [comment]
> 👍 makes sense, you might need to increase the quota beforehand. Please submit a request a few days prior to increase the quota. @vulkoingim shared some advice on how to do, if you have any trouble or questions, let us know?

I have requested an increase last Thursday, and have contacted our account manager to help push the case - I'll keep you posted with any news.

**Comment by jenting** [comment]
Leaving a note here.

Running 1k workspaces test took over 1 hour, so we had to increase the workspace timeout from 1 hour to 3 hours before running the loadgen test. Otherwise, after the loadgen reaches 1k workspaces, the number of running workspaces would be less than 1k.

**Comment by jenting** [comment]
We need to increase the workspace timeout from 1 hour to 3 hours before running the loadgen test.
![image](https://user-images.githubusercontent.com/49380831/195308372-dc3b3ad5-1db8-4c90-986a-7097903db44f.png)

The workspace startup time is under 8.53 mins.
![image](https://user-images.githubusercontent.com/49380831/195308423-223ab817-8f43-40ca-a1aa-59312a031aaf.png)
![image](https://user-images.githubusercontent.com/49380831/195308510-04826934-4d40-46ee-bb45-1a1df2b2a3d4.png)
![image](https://user-images.githubusercontent.com/49380831/195308557-29c8e8cb-886c-4612-8f72-6173a2fb6751.png)

**Comment by jenting** [comment]
Change the loadgen custom timeout value to 180m (3 hours) when the start workspace does not work. The workspaces still time out after 60 minutes 🤔. 

As an alternative, I create multiple loadgen to stress testing until we reach 1k workspaces.

Below is the overall result, and in general, it looks good to me.
Except there are still some workspace failures per second happened, and I think it's because the [workspace disposal process](https://github.com/gitpod-io/gitpod/blob/36beceb536e9c5f9e5204020ec64b685b2658c67/components/ws-manager/pkg/manager/monitor.go#L1072-L1112) still depends on the ws-daemon even though we use PVC. cc @sagor999 

[Grafana dashboard](https://grafana.gitpod.io/?orgId=1&var-datasource=VictoriaMetrics&from=1665628200000&to=1665639000000&var-cluster=ephemeral12747)

![image](https://user-images.githubusercontent.com/49380831/195511173-485d83f9-db71-4b0d-8242-aa4641bc1567.png)
![image](https://user-images.githubusercontent.com/49380831/195511202-42bfe309-651f-432c-91f4-32192a3bdb56.png)

**Comment by sagor999** [comment]
Yeah, it does depend on ws-daemon, since ws-daemon tracks workspace state in json file. So during dispose we still have to tell daemon to clean up that state file on its end. (something that we can get rid of in wsman mk2).

Have you looked at the reason for failures?

**Comment by sagor999** [comment]
Then it is most probably related to ws-daemon bookkeeping or something similar. At the very least it does not seem related to PVC code, which is good. :) 

Re: Commit
that does look good I think. I think you are right, and there is no need to wait for daemon if using PVC. I guess only edge case I can think of right now if workspace never got ready (WaitForInit waits for ready state), then we will still create volume snapshot and potentially can mess up backup of that workspace. :thinking:

**Comment by jenting** [comment]
> I guess only edge case I can think of right now if workspace never got ready (WaitForInit waits for ready state), then we will still create volume snapshot and potentially can mess up backup of that workspace. 🤔

I think we could simplify the flow to check the `workspaceNeverReadyAnnotation` during the workspace disposal process, because the annotation `workspaceNeverReadyAnnotation` be removed once the [workspace initialization is ready](https://github.com/gitpod-io/gitpod/blob/63e49da4afa839446dec74c9b7ce35045ee260aa/components/ws-manager/pkg/manager/monitor.go#L624-L700).

Then, call the [finalizeWorkspaceContent](https://github.com/gitpod-io/gitpod/blob/63e49da4afa839446dec74c9b7ce35045ee260aa/components/ws-manager/pkg/manager/monitor.go#L475) when the `workspaceNeverReadyAnnotation` annotation not exist. So, we could get ride of [code](https://github.com/gitpod-io/gitpod/blob/63e49da4afa839446dec74c9b7ce35045ee260aa/components/ws-manager/pkg/manager/monitor.go#L1072-L1097).

**Comment by kylos101** [comment]
:wave: @jenting what is left for this issue, or, can we consider the stress testing for a saturated cluster done? I ask because I see you created https://github.com/gitpod-io/gitpod/issues/13856, but am not sure if there are other issues.

**Comment by jenting** [comment]
No other issues, let's close it.
