### ISSUE TITLE
BillingMode: If you're blocked to reach UBP by Team Seats/Team Subscriptions: Render Owner/Team Names in Billing(+ Admin) UI

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#12758]
In cases where users cannot gain UBP (Free Tier) because they still are on a Chargebee Team Seat/Team Subscription: Render the names of those in the UI under:
 - personal billing
 - admin: user details

Internal example: [Slack link](https://gitpod.slack.com/archives/C02EN94AEPL/p1662626011955119?thread_ts=1662625572.245669&cid=C02EN94AEPL)

**Comment by jankeromnes** [comment]
Thanks for filing this issue @geropl! I agree that showing "(legacy) Team Plan owner" or "(new) Team name" would be super helpful to remove any assigned team plan seat you no longer want.

## Additional note

In personal billing, we indicate any team plan memberships (from both legacy and new team plans) with a simple "Team seat assigned" label in https://gitpod.io/plans :

<img width="600" alt="Screenshot 2022-09-08 at 11 11 06" src="https://user-images.githubusercontent.com/599268/189083698-7181502c-b1f0-4ad5-901d-525a1adab7e9.png">

Unfortunately, this simple label can hide the fact that you're a member of multiple team plans (e.g. of the same type "Team Unleashed").

Instead of trying to show all the Owner/Team Names in that label, I propose that we just add a new list below all the Plan cards, to recap all assigned team plan seats if there are any, e.g. like so:

> ## Assigned Team Seats
> 
> - Team Professional (owned by John Doe)
> - Team Unleashed (owned by John Doe)
> - Team Unleashed (owned by team ACME)

**Comment by geropl** [comment]
@jankeromnes Thank you, that make sense.

I think that in addition, we should also show that list on the "Billing" page in [the "canUpgradeToUBB" case](https://github.com/gitpod-io/gitpod/blob/2814f385bc20036ef193b38bd717d0053c1b05ef/components/server/ee/src/billing/billing-mode.ts#L155-L159).

**Comment by AlexTugarev** [comment]
@geropl, did you already start working on this?

**Comment by geropl** [comment]
@AlexTugarev Yes, [here](https://github.com/gitpod-io/gitpod/pull/12805). Continuing today.
