### ISSUE TITLE
git pod error

### ISSUE THREAD

**Issue by zeethecoder** [gitpod-io/gitpod#1285]
### Describe the bug

Error: build failed: cannot build base image: The command '/bin/sh -c apt-get update && apt-get install -y pkg-config python3-dev' returned a non-zero code: 100
### Steps to reproduce

kept trying to restart my teacher tired to trick it and couldn't figure it out
### Example repository

https://a5d8d8aa-2199-4cab-b334-be37dcf5fa44.ws-us02.gitpod.io/#/workspace/html-hello
https://github.com/zeethecoder/gugs
![Screenshot (6)](https://user-images.githubusercontent.com/53783282/75787988-9143a200-5d35-11ea-851d-20b2871ac7bb.png)
![Screenshot (5)](https://user-images.githubusercontent.com/53783282/75788001-943e9280-5d35-11ea-9c72-6fe278a75655.png)

**Comment by jankeromnes** [comment]
Hi @zeethecoder,

Thank you for reporting this problem. I was able to reproduce it by visiting https://gitpod.io/#https://github.com/zeethecoder/gugs

Also, thank you for providing the repository URL. I'll take a look, and see if I can send you a PR that fixes this problem.

**Comment by Kreyren** [comment]
The IP works http://91.189.88.174/ 

So it seems like an issue on with gitpod's networking assuming following used?
```dockerfile

FROM gitpod/workspace-mysql:branch-mysql

# install python3-dev to make sure the pip package "mysqlclient" works fine.
USER root
RUN apt-get update && apt-get install -y pkg-config python3-dev
```

**Comment by jankeromnes** [comment]
> FROM gitpod/workspace-mysql:branch-mysql

FYI, `:branch-mysql` is a temporary development tag, which hasn't been updated in 9 months. The image should be `gitpod/workspace-mysql` (or `gitpod/workspace-mysql:latest`, which are the same thing).

> RUN apt-get update && apt-get install -y pkg-config python3-dev

I'm not sure that this is required, given that Python 3 is already installed in `gitpod/workspace-full`. But I may be wrong.

**Comment by jankeromnes** [comment]
@zeethecoder I've sent you a PR: https://github.com/zeethecoder/gugs/pull/1 please take a look when you have time 🙂

**Comment by alesanchezr** [comment]
Thank you @jankeromnes this project was created using the academy boilerplate:
https://github.com/4GeeksAcademy/flask-rest-hello

I implemented the same changes you made but upgrated to python 3.7, thank you!

The two errors you mention happen because the command `pipenv init` should only run one time during the entire project life, that I why I tried adding it into the "init" section of the gitpod.yml, where should I put it?

**Comment by jankeromnes** [comment]
> Thank you @jankeromnes this project was created using the academy boilerplate:
> https://github.com/4GeeksAcademy/flask-rest-hello

Aha, I was suspecting this, because I noticed you were the top committer 😄 (but I couldn't find an upstream repository for https://github.com/zeethecoder/gugs/ )

> I implemented the same changes you made but upgrated to python 3.7, thank you!

Awesome!

```Dockerfile
FROM gitpod/workspace-mysql:latest

# install python3-dev to make sure the pip package "mysqlclient" works fine.
USER root
#RUN apt-get update && apt-get install -y pkg-config python3-dev
```

I guess you no longer need a custom `.gitpod.Dockerfile`, and could simply reference `image: gitpod/workspace-mysql:latest` in your `.gitpod.yml` instead.

Also, for the `.gitpod.yml` tasks syntax, I was experimenting with:

```yml
tasks:
  - command: |
      set -x
      yarn install
      yarn build
      yarn start
      set +x
```

But I'm no longer sure I like this new syntax, because subsequent commands tend to continue running even if you had an error earlier. I've also tried `set -e` (or `set -ex` if you combine both), but then I think my Terminal just got closed whenever there was an error(!)


Maybe this syntax is still better:

```yml
tasks:
  - command: >
      set -x &&
      yarn install &&
      yarn build &&
      yarn start &&
      set +x
```

Or with `;` separators as you seem to prefer them (but I think maybe having a `;` at the very end can cause problems with prebuilds maybe?)

> The two errors you mention happen because the command `pipenv init` should only run one time during the entire project life, that I why I tried adding it into the "init" section of the gitpod.yml, where should I put it?

In theory, the `init` steps will only ever be run once throughout the entire workspace lifetime. From the looks of your `.gitpod.yml`, it seems that `pipenv run init` should only be run once.

Maybe other commands implicitly run `pipenv run init` as well? E.g. `pipenv install` or `pipenv run migrate` / `pipenv run upgrade`? (I'm not familiar with `pipenv`, sorry.)

> You can do a PR if you think there are important changes that have to be made

Sure! Will try to see if I see any potential improvements. 👍 But since I'm not yet sure what the ideal multi-line command syntax is, I'll give it some time to think about it more.

> I'm a developer with really bad devops or configuration skills 😢

Haha, same here. 😂 But I secretly think all configuration file syntaxes are optimized to facilitate shooting yourself in the foot in various ways.

**Comment by zeethecoder** [comment]
> @zeethecoder I've sent you a PR: [zeethecoder/gugs#1](https://github.com/zeethecoder/gugs/pull/1) please take a look when you have time 🙂

**Comment by alesanchezr** [comment]
Thank you for your detailed response @jankeromnes! Students are not experiencing errors anymore :) You guys can close this if you want.

I have not had any issues using `;` so far.

I'll be monitoring the boilerplate and share any improvements/knowledge we gain overtime! 😄
