### ISSUE TITLE
"new Git integration" page does not respect the proxy settings

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#12874]
When attempting to create a new Git integration on a proxied server, the test to see if a host is reachable does not get routed through the proxy.

There are a few possible reasons why this may be the case:
1. the `is-reachable` library [doesn't support it explicitly](https://github.com/sindresorhus/is-reachable/issues/7) (although it looks like `got` does)
2. does the call get made from the server or browser? If browser, this won't respect the routing
3. I may not have added the correct configuration for this package in #12726 

This ticket aims to see what can be done to support Gitpod installations that use a proxy server for their public internet access and ensure that we can support this with enterprise installations.

**Comment by geropl** [comment]
@MrSimonEmms Can you share any timeline on when we plan to over proxy support? Somehow that went past me, completely. I'd even go so far and question the decision to support it in the first place. Feels like we pushing an infrastructure concern into the product, really... 😕 

/cc @corneliusludmann

**Comment by MrSimonEmms** [comment]
@geropl timelines are not really set yet - in reality, I think the official answer is "shortly after the first paying customer requires this feature".

I agree that we don't want to be putting infrastructure concerns into the application. Largely, this is not the infrastructure side of things but it's making sure that the application respects the settings so that it can be installed in this environment and work as expected. In that respect, I view it similar to airgapped - we don't tell people how to build an airgapped environment, we just ensure that it works in that type of environment.

This morning, I wrote a [document of Self-Hosted definitions](https://www.notion.so/gitpod/Self-Hosted-Definitions-76409b905147450ba5307e9dacfc6e67) which may be relevant here in explaining our meaning.
