### ISSUE TITLE
Theia Plugins

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1287]
Allow for users to extend theia with plugins, possible config in `.gitpod.yml`

```yaml
theia:
  plugins:
    - foo
```

**Comment by Kreyren** [comment]
>  possible config in .gitpod.yml

elaborate? is this `extensions:` in gitpod.yml?

**Comment by JesterOrNot** [comment]
what do you mean?

**Comment by Kreyren** [comment]
> @JesterOrNot Allow for users to extend theia with plugins, possible config in .gitpod.yml

I am not familiar with theia, requesting more info to how is that relevant to gitpod.yml

**Comment by akosyakov** [comment]
@JesterOrNot I think VS Code extensions is already enough. Theia plugin is just another name for them.

**Comment by LimpingNinja** [comment]
@akosyakov Is it? They don’t install by drag and drop and there are some that I would consider very important to add before using GitPod, like this:

https://github.com/redhat-developer/netcoredbg-theia-plugin

This allows .NET core debugging via the Samsung debugger (which can’t happen with the stander net core debugger due to licensing). If “Theia plugin” is just another name then how would you install this .theia plugin? If not what VS code extension provides this?

**Comment by akosyakov** [comment]
@LimpingNinja Are you sure there is no VS Code extension already using this debug adapter?

**Comment by LimpingNinja** [comment]
@akosyakov I'm not sure why the Theia/Che team would make this a VSCode extension, as VSCode is allowed to use the .NET Core Debugger.  From what I understand, this was made specifically to resolve an issue with Theia lacking the capability to use that debugger and bolster Che's 1st class support of .NET: https://github.com/eclipse/che/issues/12790

I saw a comment from @svenefftinge about a year ago saying that you were looking at the debugging extension for .NET/C# debugging; is that something you are no longer doing? Having 1st class support for .NET is something my group was looking for - obviously self-hosted VSO is an option and hosting Coder and manually connecting the debugger, but those are pretty heavy-weight compared to Gitpod.
