### ISSUE TITLE
Usage in usage view is not updated within 15 min

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13060]
New usage takes much longer than 15min to appear in the usage view of a team with UBP billing configured.
This will be a problem for users, and also for us internally because it slows down our testing.

See [internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1663340288083649?thread_ts=1663339548.024379&cid=C02EN94AEPL) - this may be related to missing DB indexes.

**Comment by easyCZ** [comment]
This is a known issue at the moment. To fix this, we need the following changes:
* https://github.com/gitpod-io/gitpod/issues/11378
* https://github.com/gitpod-io/gitpod/pull/12706

This has been currently blocked due to new indices causing downtime.

For now, we could change the wording to say (refreshes every 1h) which is roughly how often we do it now. See [dashboard](https://grafana.gitpod.io/d/8W7P-jg4z/component-usage?orgId=1&viewPanel=20) for details.

**Comment by easyCZ** [comment]
US migrations now applied. We still need to apply the `stoppingTime` migration in EU

**Comment by easyCZ** [comment]
To apply the EU indices, execute the following:

```bash
# your kubecontext name may vary
kubectx webapp-eu2

kubectl port-forward svc/cloudsqlproxy 3306:3306

# Connect to the DB on port 3306
# ...
# Run the following query:
CREATE INDEX IDX_workspace_instance__stopping_time ON d_b_workspace_instance (stoppingTime);
```

Expected run time is ~25 minutes.

**Comment by geropl** [comment]
Done with the steps above :heavy_check_mark:
