### ISSUE TITLE
Nearly 50% calls to joinTeam return 500 status code

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#13125]
![Image](https://user-images.githubusercontent.com/1419286/191266737-6bb9b1e5-6cd5-4bff-935e-39132e87458b.png)

Query: `sum(increase(gitpod_server_api_calls_total{method="joinTeam"}[7d])) by (statusCode)`
[Dashboard](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28gitpod_server_api_calls_total%7Bmethod%3D%5C%22joinTeam%5C%22%7D%5B7d%5D%29%29%20by%20%28statusCode%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D)

**Comment by jankeromnes** [comment]
Good catch! 💯 

Looking at the code, I have a strong suspicion that this is about trying to join a team where you're already a member:

https://github.com/gitpod-io/gitpod/blob/3ac0c02e2d62b0755177baa0591db8399c4caebe/components/gitpod-db/src/typeorm/team-db-impl.ts#L182-L184

(Otherwise, if a valid invite really wasn't found, it would be a 404 response:

https://github.com/gitpod-io/gitpod/blob/3ac0c02e2d62b0755177baa0591db8399c4caebe/components/server/src/workspace/gitpod-server-impl.ts#L2124-L2127

)

**Comment by easyCZ** [comment]
It is, I looked at the logs for this. The API behaves weirdly here, it throws an error with "Already in a team" (or similar) which it then checks for with a regex on the client side. Here, we should probably use the 409 HTTP Status code to indicate that the membership already exists.

**Comment by easyCZ** [comment]
Fix for returning appropriate status codes: https://github.com/gitpod-io/gitpod/issues/13125

**Comment by easyCZ** [comment]
Since the rollout, the 500 errors have disappeared.


![Image](https://user-images.githubusercontent.com/1419286/194725737-d7505835-8ed9-4a6c-81f4-73e5958e6803.png)

Marking as complete.
