### ISSUE TITLE
Store Stripe Customer ID internally, and make StripeService.findCustomerByAttributionId use the stored ID when available

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#13177]
## Is your feature request related to a problem? Please describe

This is a follow-up to https://github.com/gitpod-io/gitpod/pull/13002, but the bug was actually pre-existing:

- Sometimes (maybe around 1 in 10 times?) when you subscribe a team to Stripe, creating the subscription randomly fails:

<img width="600" alt="Screenshot 2022-09-21 at 16 21 40" src="https://user-images.githubusercontent.com/599268/191530013-fba72f30-bfc4-4706-b8bb-57ec9146d3ee.png">

- And in the backend, you'll see this error:

```
Error: No Stripe customer profile for 'team:123ff8cd-422f-4865-87eb-2d3767b2b16f'
```

- But if you try adding the same credit card / country / currency again, it works

This is because searching Stripe customers by `attributionId` seems a bit inconsistent right after customer creation (we poll Stripe Search to confirm that a new customer is available in search results, but then when running the same query a few seconds later, it might come up empty again).

## Describe the behaviour you'd like

Instead of polling Stripe Search like we do here:

https://github.com/gitpod-io/gitpod/blob/759e588e450f37131dd20fe46855cf77e01815be/components/server/ee/src/user/stripe-service.ts#L94-L101

we should:

1. Store the created Customer ID in the team/user or their cost center (but it should not be widely accessible, because querying via `attributionId` is preferred)
2. When trying to find a customer by `attributionId`, StripeService.findCustomerByAttributionId should check for a stored ID first, and fall back to search of there is no ID, or the customer for that ID was deleted or its metadata were modified

## Describe alternatives you've considered

- Accept that subscribing sometimes fails and needs to be retried once? 😬
- Wait for a few more seconds after polling Stripe Search? 😬

**Comment by easyCZ** [comment]
Linking further context from [internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1664261553210779)

**Comment by easyCZ** [comment]
Occurrence of this raised internally during Workspace Start - [details](https://gitpod.slack.com/archives/C02EN94AEPL/p1664978399985299)

**Comment by easyCZ** [comment]
An initial draft of this is [here](https://github.com/gitpod-io/gitpod/pull/13622)

The draft chooses to store the (Stripe Customer ID, Attribution ID) tuple in a new table, independent of CostCenter but it can easily be changed to use it. The reason for storing it in a new table are the semantics of the CostCenter - new cost centers for an attribution get created but in the case of Stripe, the customer ID remains the same irrespective of the cost center.

Requests are proxied from server to usage, which handles the DB interaction.

**Comment by easyCZ** [comment]
After some exploration and a sync with @svenefftinge, we'll take the following staged approach:

1. Firstly, we'll move the lookup of a customer to usage. This change will not necessarily improve the situation in terms of the error, but it will co-locate it such that we can better monitor and apply fixes in a single place.
2. Next, (based on metrics) we'll introduce a table which stores the (Stripe Customer ID, Attribution ID, ...) away from the Cost Center. This is because the existence of a Stripe customer is independent of them having a Subscription (CostCenter). And customers continue to exist even when CostCenters (their billing strategy) do change. We'll use this table for a faster lookup of the mapping.
3. We'll extend the CostCenter table and store the `subscription id`. The (stripe) subscription id exactly matches the lifecycle of a CostCenter and will allow us to further remove a few lookups.

The first stage is implemented in stacked PRs:
1. https://github.com/gitpod-io/gitpod/pull/13659
2. https://github.com/gitpod-io/gitpod/pull/13667
3. https://github.com/gitpod-io/gitpod/pull/13669

**Comment by easyCZ** [comment]
Over time, we'll also be looking to move the bulk of CustomerCreation and Subscription creation over to `usage` to co-locate it there. This will allow for the domain of usage & billing to sit solely with the `usage` component.

**Comment by easyCZ** [comment]
We've been able to reduce the calls to Stripe by leveraging the Cost Center.
* https://github.com/gitpod-io/gitpod/pull/13690
* https://github.com/gitpod-io/gitpod/pull/13704

**Comment by easyCZ** [comment]
Moving to validation. We'll need to land the [remaining mitigation](https://github.com/gitpod-io/gitpod/pull/13704) and then monitor. Depending on resulting metrics we may be able to stop here.

**Comment by easyCZ** [comment]
So far, this has been working well. We've also got observability into the errors in [metrics ](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22gitpod_stripe_requests_completed_seconds_count%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)

Keeping in validation for now to get more data from prod before closing.
