### ISSUE TITLE
Epic: [Self-Hosted] Tag self-hosted related images with their corresponding release. 

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#13359]
### Summary

Tag self-hosted images on a per release basis to allow for customers to automatically mirror them in their airgapped registries.

### Context

To mirror images to their airgap environment cusotmers have to add them by tag, if we had a gitpod-release-version tag, they could have more easily found the images to add with a simple regex.

Having this feature going forward ensures they can configure automation around our release process and know they are consuming the right artifacts all the time.

### Value

Avoids customers having to write complex reg-exes, or doing this by hand. 

### Acceptance Criteria

When we ship a release to replicated, we should also tag all artifacts related.

By all artifacts, I mean all of them, including third party ones. Which means we will need to mirror third party artifacts to our gcr.io namespace (https://github.com/gitpod-io/gitpod/issues/12816) so we can add the tag.

### Measurement

- Customers confirm that they are able to mirror images easily using the newly provided tags.

### additional context
- Internal [thread](https://gitpod.slack.com/archives/C020VCB0U5A/p1663685288650349)

### Issues
- [ ] #12812 
- [ ] #12813 
- [ ] #12816

**Comment by mrzarquon** [comment]
Flattening the namespace *and* tags also comes with some consequences - we use three versions of minio at the moment, one for [shimming](https://github.com/gitpod-io/gitpod/issues/13135) to AKS, one for in cluster storage, and one brought in by kots.

We end up with two mysql containers because we don't use the exact same tags across the internal mysql container for accessing mysql, and the mysql helm chart for incluster use.

Another is re-using "[registry](https://github.com/gitpod-io/gitpod/tree/main/components/kots-config-check)" as the name of our registry check and the name of the registry container. I'd suggest we make one monolithic preflights tool image called "preflight"
