### ISSUE TITLE
Feature Request: Support Kubernetes

### ISSUE THREAD

**Issue by ngryman** [gitpod-io/gitpod#1337]
Hey there, first of all, great work with Gitpod 👏

I would be very interested in migrating our local environment to Gitpod. However, our product needs several containers to run in development mode.

So I would have 2 questions:

1. Do you plan to support k8s or any orchestration tool (ie. Docker Compose) in the future?
2. Meanwhile, what do you think about using DinD and Kubernetes IN Docker: https://github.com/kubernetes-sigs/kind? I didn't dive in it yet, but at first glance, it would be possible to run a cluster in a Docker image.

**Comment by JesterOrNot** [comment]
Hello, @ngryman, and welcome to the Gitpod community! :tada: @svenefftinge Correct me if I'm wrong, but I think we have plans to support it in the future. However, right now it would require root or root-like permissions, which as of now we don't allow, please, see the following issues for information: #52 #39

**Comment by svenefftinge** [comment]
Yes, we are working towards allowing DinD. For the time being here's how we develop kubernetes applications (i.e. Gitpod itself) using Gitpod.
https://www.freecodecamp.org/news/developing-kubernetes-applications-with-joy/

**Comment by jankeromnes** [comment]
FYI, we're doing a YouTube livestream about root/docker in Gitpod workspaces in about ~2.5 hours: https://www.youtube.com/watch?v=l4I2TVAnBuw

**Comment by davemecha** [comment]
Hi everybody,

I'm searching for a way for knative development & testing with GitPod in the new Docker preview but was not able to get a local kubernetes environment running. I checked out minikube, k3s and kind but I was not able to get any of them running.

> Yes, we are working towards allowing DinD. For the time being here's how we develop kubernetes applications (i.e. Gitpod itself) using Gitpod.
> https://www.freecodecamp.org/news/developing-kubernetes-applications-with-joy/

The https://www.telepresence.io/ option seems not to work with knative since the networking seems to conflict (there's an [open ticket](https://github.com/telepresenceio/telepresence/issues/1029) in the telepresence repo). Beside this, it's not always a good option because one has to run a Kubernetes cluster somewhere else, what may be cost intensive.

## demo

I created a demo repo so anybody could try the issues for themselves. https://github.com/davemecha/knative-minikube-test - Just fire up a GitPod from there and execute the stuff as mentioned in the readme.

I also watched the youtube session about Docker in GitPod but this was pretty heavy stuff for me. When I understood this correctly than there might be a similar solution for running Kubernetes inside cloud GitPod as was applied to run Docker alone. At least for the `cgroup` issues with minikube with Docker driver.

## logs

I posted my test-results (with some logs) in the [GitPod community](https://community.gitpod.io/t/knative-development-on-gitpod/2814) but maybe this github issue is a more appropriate place for discussing this case.


Thanks for help and comments. 🙏 

---

Best issue number. 💚 😍

**Comment by Baneeishaque** [comment]
Please don't stale.

**Comment by hferentschik** [comment]
Is there any progress on this?

**Comment by loujaybee** [comment]
Hey folks, just coming back to this for others who are googling, we recently published a new docs page: 

https://www.gitpod.io/docs/integrations/kubernetes

This page covers common use cases and ways to develop Kubernetes applications in Gitpod: 

* [Using Docker in Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#1-using-docker-in-gitpod)
* [Using Docker Compose in Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#2-using-docker-compose-in-gitpod)
* [Using a Kubernetes Network Proxy in Gitpod (e.g. Telepresence)](https://www.gitpod.io/docs/integrations/kubernetes#3-using-a-kubernetes-network-proxy-in-gitpod-eg-telepresence)
* [Running Kubernetes clusters in Gitpod (e.g. MiniKube)](https://www.gitpod.io/docs/integrations/kubernetes#4-running-kubernetes-clusters-in-gitpodeg-minikube)
* [Connecting to a remote Kubernetes cluster inside Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#5-connecting-to-a-remote-kubernetes-cluster-inside-gitpod)

Please do check it out, and let us know if you have any questions 🙏
