### ISSUE TITLE
Feedback Issue: Docs Navigation Restructure

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#13430]
Hey ! You might notice the Gitpod documentation looking different today! 

That's because we've overhauled how we showcase Gitpod in our documentation (see below).

Some notable changes (though, there are much more!): 

1. Separate sections to learn Gitpod, e.g. "introduction" as a new user vs "configure" as an existing user Gitpod 
3. Entities like workspaces, teams and projects all have a top-level spot now
4. Important pages like `.gitpod.yml` and the `gp` CLI are brought to the top-level

We hope you like the new layout, and it supports you in finding what you need better. But this is just the beginning. We'll be rolling out lots more upgrades over the coming weeks and months, to make working with Gitpod much easier. 

If you have any feedback, leave a comment below!

![image](https://user-images.githubusercontent.com/5528307/192948761-173d6269-1a47-493b-a08d-5d1325f32596.png)

**Comment by mittalyashu** [comment]
If this config schema for `mainConfiguration` is correct in [this repo](https://github.com/gitpod-io/demo-multi-repo-backend/blob/main/.gitpod.yml).

As `mainConfiguration` seems to be at the root.

Then the docs might needs to be updated:

| | |
| --- | --- |
| ![CleanShot 2022-10-01 at 18 08 01@2x](https://user-images.githubusercontent.com/29014463/193410063-1ea5ad5f-6c93-4c51-bcf3-f915b865e0ce.png) | ![CleanShot 2022-10-01 at 18 08 09@2x](https://user-images.githubusercontent.com/29014463/193410071-03787fe5-ba5f-42e3-a19d-0ff2f61296b8.png) |

**Comment by stemount** [comment]
You forgot the URL, I opened up the screenshot and wondered why half the page was missing!

I'm just gonna leave this here ;-)

## Gitpod New Documentation
https://www.gitpod.io/docs/introduction

**Comment by stemount** [comment]
Overall, fabulous job on building documentation, I really like the code samples and how the tables show arguments. That is very elegant and helpful.

The mobile version is very good, looks like a lot of work went into that!

Hopefully this feedback is relevant and welcome here, I've worked for the GOV.UK a number of times so I've had web accessibility drilled into my head. I suspect there may be Gitpod users might have a computer that doesn't have a fantastic brightness (Think somebody with a 5 year non-HiDPI laptop screen or a TN panel with 300 nits brightness, who use Gitpod because it provides them CPU/RAM as a saviour)

I have some feedback about the dark theme version, I had to turn up my (600 nits) screen to really see the navigation. I think this will make it hard for people to read. I see why it is done, so that "categories" stand out, but maybe another way is possible.

#### I can see here why you have the grey so the headers stand out.

##### Before
![CleanShot 2022-10-04 at 09 19 26](https://user-images.githubusercontent.com/150512/193772449-a40a6c35-6be4-4135-afa6-b06d729c5548.png)

#### With the font as #FFF, the site is instantly becomes a lot more readable, the search box also shows up a lot better.

##### After
![CleanShot 2022-10-04 at 09 20 59](https://user-images.githubusercontent.com/150512/193772616-c6a025b9-ae76-446a-ac86-79a66269c8d2.png)

#### The light varient of the site is great though. Whacking up the font size a tiny bit helps show that you have 9.2K supporters. I (personally) believe the font size being larger would help people navigate the documentation.

Just a suggestion from messing around in dev tools.

##### Before
![CleanShot 2022-10-04 at 09 24 51](https://user-images.githubusercontent.com/150512/193773775-eff044f0-2e25-4605-b934-fc4007850466.png)

##### After
![CleanShot 2022-10-04 at 09 24 42](https://user-images.githubusercontent.com/150512/193773799-9da8ff35-a9b2-458c-bf14-e4dd8c7b64ee.png)
