### ISSUE TITLE
Improve the latest IDE image experience for Self-Hosted customers

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#13480]
**Context**
* We have a "latest" feature in Gitpod SaaS for IDE images, however for Self-Hosted customers have to wait until the next release of Gitpod Self-Hosted to benefit from the latest IDE images
* This release process also complicates matters as we have to ensure things like Gitpod extensions release cycles are backwards compatible with Self-Hosted versions. 

**Overview**
This issue is to think about how we can more closely align Self-Hosted customers and our IDE clients, including the "latest" option. By allowing Self-Hosted customers to run latest they can see anticipate upcoming breaking changes and report them before a Self-Hosted release. It also means these customers get a faster feedback cycle than having to wait for the next Self-Hosted release. 

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/13359
- https://github.com/gitpod-io/gitpod/issues/13209

**Comment by mrzarquon** [comment]
@loujaybee `latest` works for self hosted (since they can pull from our registries live), however in the case of an airgapped install, the `latest` image is a snapshot from when the airgap bundle was created. For airgapped the customer would have to manually update the mirrored / internal tag of latest for those users.

Publishing `latest` builds with also a date tag would allow for airgapped customers to setup mirroring jobs to stage those images internally for consumption by Gitpod SH.

Allowing `latest` functionality to be smarter than just pulling `ide-image:latest` would be better (ie, also latest means 'use the image with a date timestamp closest to $now', let the self-hosted admin define what `latest` means for their install).
