### ISSUE TITLE
Stale bot should tag issues it closes with a unique tag!

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#13514]
Currently issues closed by the stale bot just get closed (and it isn't even the stale bot which is shown as the closer!)  The stale bot should tag issues that it closes with a unique tag so they can be searched for (and triaged!) (or have the never stale tag applied if appropriate!)

Unless the query `is:closed label:"meta: stale"` is supposed to be sufficient ...

**Comment by gtsiolis** [comment]
Thanks for the proposal, @david-bakin!

I agree, there's benefit is marking issues closed from the stale bot with a unique label but the **~meta: stale** label would suffice for now as stale bot automatically adds this before closing an issue, see [relevant query](https://github.com/gitpod-io/gitpod/issues?q=is%3Aissue+is%3Aclosed+stale+label%3A%22meta%3A+stale%22) and example comments[[1](https://github.com/gitpod-io/gitpod/issues/10587#event-7351937137)][[2](https://github.com/gitpod-io/gitpod/issues/10587#event-7453232071)].

**thought**: We've only scratched the surface of automatic triage operations like this so far, in the future using a more specific label, following the proposal here, like **~meta: auto-closed** could be ideal but this would require us first to get better and more intentional about issue triaging.

**issue**: From what I've seen, the stale app does not support this, see [relevant pull request](https://github.com/probot/stale/pull/317). Let me know if you know a workaround to do this with the stale app.

**suggestion**: [FWIW](https://en.wiktionary.org/wiki/FWIW), I don't think the **stale app**[[3](https://github.com/probot/stale)] currently used is flexible or powerful enough to support more complex use cases, especially as an inactive project. Moving to something like the **stale action**[[4](https://github.com/actions/stale)], which already supports [`close-issue-label`](https://github.com/actions/stale#close-issue-label), or a custom solution build to match our needs sounds like the best way forward.
