### ISSUE TITLE
Gitpod app: re-enable adding the gitpod button + description on every issue as a preference.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#1352]
I suspect that not every contributor goes through the Readme or Contributing.md maybe those contributing for the first time or those who are beginners do. 

One thing for sure is that issues are always looked and read quite carefully. I think It would be nice if we were to have the Gitpod app add comments with the Gitpod button + some description (i.e what Gitpod does).

@svenefftinge told that we use to have such functionality I would be in favour of having it back as a preference turned on by default.

**Comment by jankeromnes** [comment]
Great idea! Many thanks for suggesting it.

Some additional thoughts:
- A Gitpod button/link could also be added to PR templates / issue templates (although maybe that's not something the Gitpod App should do?)
- Alternatively, the Gitpod App could also add a Gitpod button/link only to issues labelled with `good-first-issue` or `help-wanted` (or custom set of labels), instead of all issues. This may be more complicated to implement, but maybe worth doing if many people request this feature.

**Comment by nisarhassan12** [comment]
> Alternatively, the Gitpod App could also add a Gitpod button/link only to issues labelled with good-first-issue or help-wanted (or custom set of labels), instead of all issues. This may be more complicated to implement, but maybe worth doing if many people request this feature.

@jankeromnes  Thanks! I would be in favour of having it on all issues unless it's highly requested. I have seen some popular OSS projects which don't bother to add labels like `help-wanted ` or `good-first-issue`  and so on, on almost the entirety of issues.

Maybe we could make this configurable as a preference which is disabled by default.

I have also seen projects which do have these labels added so I think it would make sense to implement it. I'm sorry If I misunderstood something related to what you meant.
