### ISSUE TITLE
[preview] Unable to build preview environment, not all pods ready in kube-system namespace

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#13556]
### Bug description

Hi there :wave: , @sagor999 just bumped into this issue, albeit probably not for workspace pods. 

For example, this time it was pods in the `kube-system` namespace.

```
Error Error: Not all pods in namespace kube-system transitioned to 'Running' or 'Succeeded/Completed' during the expected time.
    at /workspace/.werft/util/kubectl.ts:317:11
    at step (/workspace/.werft/util/kubectl.ts:44:23)
    at Object.next (/workspace/.werft/util/kubectl.ts:25:53)
    at fulfilled (/workspace/.werft/util/kubectl.ts:16:58)
```

Upon examination, it looks like `core-dns` and `local-path-provisioner` could not schedule:
```
[Waiting for k3s] Unready pods: coredns-d76bd69b-thfcc:Pending, local-path-provisioner-6c79684f77-rmrdz:Pending
```

### Steps to reproduce

Here is the related werft job where we bumped into the problem: 
https://werft.gitpod-dev.com/job/gitpod-build-pavel-13531.8/raw

### Anything else?

This happened previously for workspace pods in another issue: https://github.com/gitpod-io/gitpod/issues/12622

**Comment by meysholdt** [comment]
I see in the failed job that the pods did not come up because the k3s node was not ready:
[Waiting for k3s]   Warning  FailedScheduling  33m                  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
[Waiting for k3s]   Warning  FailedScheduling  4m1s (x27 over 32m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
Not sure why it was not ready. If this happens again, it would make sense to look at kubectl describe node and the syslog.

**Comment by kylos101** [comment]
> Not sure why it was not ready. If this happens again, it would make sense to look at kubectl describe node and the syslog.

@meysholdt would a skateboard be to update the job, so that that level of detail is output to Werft raw logs (at least the kubectl describe node)? This way it's available for continued troubleshooting and eventual closing of this issue - especially if other issues warrant similar input to do troubleshooting.
