### ISSUE TITLE
Environment Variables and org/rep

### ISSUE THREAD

**Issue by ttopholm** [gitpod-io/gitpod#1358]
### Describe the bug
If you have folders in gitlab.com, like <Organization>/<folder>/<repository> the environment variable created after a gp env foo=bar will be <Organization>/<folder>, but if you do a gp env -e you are not getting the variables back, because your repo is in <Organization>/<folder>/<repository>, the only workaround so far is to use */* in Org/rep in settings.

### Steps to reproduce
Add a folder structure in gitlab and you reproduce the bug

**Comment by corneliusludmann** [comment]
It's not entirely clear to me what you mean by “folder structure”. I guess you mean nested groups / subgroups like `gitlab.com/mygroup/mysubgroup/myproject` (probably your examples in your description are broken since they are recognized as markup).

Indeed I can confirm that setting env vars in a nested group does not work with `gp env`. Thanks for reporting!

**Comment by ttopholm** [comment]
Thx @corneliusludmann that was exactly what I meant ;-)

**Comment by DanielChalk** [comment]
Any chance this can get through to the SaaS offering of GitPod soon? This issue stops me from using it.

**Comment by svenefftinge** [comment]
It is deployed now.

**Comment by ceefour** [comment]
This doesn't seem to be fixed, see -> https://github.com/gitpod-io/gitpod/issues/8618#issuecomment-1153727634
