### ISSUE TITLE
Keyboard shortcuts don't work in GitPod Code when using alternative keyboard layout (Dvorak)

### ISSUE THREAD

**Issue by aaronrodriguez-qz** [gitpod-io/gitpod#13662]
### Bug description

OS: Ubuntu 20.04

Keyboard shortcuts involving any character that is mapped differently in the current keyboard layout (e.g. Dvorak) vs QWERTY do not work as expected. These shortcuts are only available using the physical locations of the letters/symbols on a QWERTY layout. The IDE doesn't respect the current keyboard layout when responding to keyboard shortcuts.

Examples:
`Ctrl+Z` doesn't perform "undo"; it toggles a line comment as if `Ctrl+/` were pressed. (Note `Z` on Dvorak is the same physical location as `/` on QWERTY)
`Ctrl+;` should do nothing, but performs "undo". (Note `;` on Dvorak is the same physical location as `Z` on QWERTY)

[Dvorak layout for reference](https://dvorak-keyboard.com/wp-content/uploads/dvorakkb.png)

### Steps to reproduce

Using Ubuntu 20.04:
- Set OS keyboard layout to Dvorak.
- Open/create a JS/TS file in GitPod Code.
- Enter some text.
- Press `Ctrl+(second row from bottom of keyboard, farthest to the right (immediately to the left of the right Shift key))`.

This key is `/` on QWERTY and `Z` on Dvorak.

Expectation: undo the last bit of typing

Result: line comment (as if `Ctrl+/` were pressed)

This expectation is consistent with every text editor, IDE, browser, etc that I've used with Dvorak, including Desktop VsCode.

### Expected behavior

The IDE should respond to keyboard shortcuts using the logical key pressed regardless of keyboard layout, rather than the QWERTY equivalent of the physical key pressed.

**Comment by jeanp413** [comment]
@aaronrodriguez-qz that's expected, because limitation in browser there's only a few keyboard layouts harcoded in vscode itself, so to make it work you need to explicitly tell vscode your key mappings
1. Open vscode desktop and run `Developer: Inspect Key Mappings (JSON)` command, this will open a file with the key mappings
2. Open gitpod code in browser and run `Change Keyboard Layout` command, select `Configure keyboard layout`
3. A `keyboardLayout.json` file will open, paste the content from the file in step 1 and save
4. Run `Change Keyboard Layout` command again and select the new keyboard layout

![image](https://user-images.githubusercontent.com/25115070/195425886-3825e0ba-9a3f-492b-b7ce-c4de439b6dde.png)

**Comment by aaronrodriguez-qz** [comment]
The above solution worked for me, but didn't sync across GitPod instances with Settings Sync. I found another workaround that fixes the problem and does get synced in the settings. I added `"keyboard.dispatch": "keyCode"` to my `settings.json`. Found here: https://github.com/microsoft/vscode/issues/103339

**Comment by akosyakov** [comment]
@axonasif @loujaybee maybe it is worth to document
