### ISSUE TITLE
Prorate final payment when individual users cancel their $€ 9.00 paid subscriptions.

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13804]
When users cancel a paid subscription which includes a credit allowance, like the personal paid plan, they should not be penalized for cancellations right after subscribing, or at the start of a billing period.

#### Effect of cancellation:
- Issue final invoice for that month.
- Usage limit drops back down to the free plan limit (500 credits).
- The charge for the $€ 9.00 flat-rate amount is pro-rated, proportional to usage or time (investigate Stripe support)

More details in [discussion](https://www.notion.so/gitpod/Usage-Based-Pricing-Cancellations-9c1da4d437de4314a4982ee7f7798f58#694eb1126faa4008a1c310aac662d06e) (internal)

**Comment by geropl** [comment]
> The unused credits will remain active until the end of the billing period.

But when you cancel your subscription, your billing period ends immediately: that's why you receive an invoice. 🤔 

Did we think about enabling proration in Stripe? The credit model rather well for that (because we know the exact number we want to refund).

 /cc @jankeromnes bc you maybe know whether enabling proration is as easy as I hope it is.

**Comment by jankeromnes** [comment]
Ah, I was finally able to track down the relevant information. Turns out it's pretty clearly indicated in the "cancel subscription" docs [[1](https://stripe.com/docs/billing/subscriptions/cancel?dashboard-or-api=api#canceling), [2](https://stripe.com/docs/api/subscriptions/cancel)]:

<table><tr><td>
<img width="831" alt="Screenshot 2022-10-25 at 09 43 30" src="https://user-images.githubusercontent.com/599268/197714375-3a169811-768c-4033-a81f-6d1402151bf7.png">
</td><td>
<img width="1175" alt="Screenshot 2022-10-25 at 09 43 55" src="https://user-images.githubusercontent.com/599268/197714387-7ab3f6b5-9669-4411-8d76-6516e52f1fec.png">
</td></tr></table>

Should be pretty easy to add -- let's try this out.

**Comment by geropl** [comment]
> Turns out it's pretty clearly indicated in the "cancel subscription" docs [[1](https://stripe.com/docs/billing/subscriptions/cancel?dashboard-or-api=api#canceling), [2](https://stripe.com/docs/api/subscriptions/cancel)]

Jep! Thought I shared that last time, but maybe on a different issue.. :see_no_evil: 
:100: agree with doing first what is easiest.

**Comment by jankeromnes** [comment]
> Jep! Thought I shared that last time, but maybe on a different issue.. 🙈

Ah, that's possible 🎯 but I still got distracted by many unrelated docs about proration before I found this again 😅

Side note: I'm also changing the [default proration behavior on subscriptions](https://stripe.com/docs/api/subscriptions/create#create_subscription-proration_behavior), because the normal cancellation flow is to cancel via the Stripe Customer Portal (where users cannot explicitly ask for proration):

<img width="802" alt="Screenshot 2022-10-25 at 11 29 53" src="https://user-images.githubusercontent.com/599268/197737938-89a93462-3108-4a63-babd-962d0d58a400.png">

We'll be able to test the effects of these combined options on all the different cancellation flows (portal, delete team, delete user) pretty soon once Werft accepts to build https://github.com/gitpod-io/gitpod/pull/14148

**Comment by geropl** [comment]
@jankeromnes In light of recent discussions I will close this for now. D'accord?

**Comment by jankeromnes** [comment]
Sounds good to me, thanks!
