### ISSUE TITLE
Julia REPL doesn't open on particular repository

### ISSUE THREAD

**Issue by grahamas** [gitpod-io/gitpod#1387]
### Describe the bug
When I try to open a Julia REPL with Julia language support installed, it opens a shell.

### Steps to reproduce
1. Open the Gitpod on https://github.com/FluxML/model-zoo/
2. Use the command palette to open a Julia REPL

### Expected behavior
After step 1, I would expect a REPL to be open. Instead, a command prompt is open.
After step 2, I would expect a REPL to open. Instead, another command prompt opens.

### Additional information
I tested the on Julia repository, and that gitpod worked fine.

### Example repository
https://github.com/FluxML/model-zoo/

**Comment by JesterOrNot** [comment]
Hello @grahamas, and welcome to the Gitpod community! 🎉 I looked at the project and it appears that Julia is not installed, this is odd (to say the least) since the image used is an official Docker image. To see an example of how to properly configure Julia for Gitpod please see our [example repository](https://github.com/gitpod-io/Gitpod-Julia). in the meantime, I will create a PR for the specified repository and fix their Gitpod configuration. If you have any questions please, let me know!
