### ISSUE TITLE
Clicking 'Create a Team' Link on Projects Page Takes Me to a Page to Create a Project

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#13917]
### Bug description

While on the Projects page (https://gitpod.io/projects) there is a blue alert banner with a link 'Create a Team':

<img width="928" alt="create-a-team-link" src="https://user-images.githubusercontent.com/405585/196220006-2d4bca7d-dba9-4b25-88bd-32d37299c7ec.png">

If I click on this link I am brought to a page to create a project (https://gitpod.io/new):

<img width="1450" alt="Screen Shot 2022-10-17 at 10 30 58" src="https://user-images.githubusercontent.com/405585/196220108-70ac05a1-e43c-4e0d-9fdb-93418acb64b7.png">

### Steps to reproduce

1. Go to https://gitpod.io/projects
2. Click on the 'Create a Team' link located in the blue alert banner at the top of the page.
3. Observe you go to the page which seems to be for creating projects - https://gitpod.io/new

### Expected behavior

I would expect clicking the 'Create a Team' link would take me to a page to create a team and not a project.

**Comment by gtsiolis** [comment]
Thanks, @jimmybrancaccio! I think this was intentional to drive users through the project onboarding flow. But I agree it seems more accurate and specific if we actually link to [`/teams/new`](https://gitpod.io/teams/new).

This alert is something we could work on improving to be clearer to users, see https://github.com/gitpod-io/gitpod/issues/13892. Cc @jldec 

In the meantime, I've opened https://github.com/gitpod-io/gitpod/pull/13920 to tackle this MVC.
