### ISSUE TITLE
ws-manager: DisposeWorkspace context deadline

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#13932]
### Bug description

Context deadline when executing the [DisposeWorkspace](https://github.com/gitpod-io/gitpod/blob/7ea0256d97221b3daa9672a7a58b8069e01ad8c6/components/ws-manager/pkg/manager/monitor.go#L1299-L1308), and we keep using the deadline context to update the [annotation](https://github.com/gitpod-io/gitpod/blob/7ea0256d97221b3daa9672a7a58b8069e01ad8c6/components/ws-manager/pkg/manager/monitor.go#L1015-L1019), which makes the ws-manager unable to add update annotation mark. The workspace pod keeps terminating.

The ws-manager relies on the workspace pod annotation (as the workspace pod state) to decide the code logic. Therefore, we must try our best to make sure the annotation is added to the workspace pod.

But the good news is the workspace content is in the GCS.

### Steps to reproduce

- [was unable to update pod's retrying disposal status - this might cause an incorrect disposal status](https://cloudlogging.app.goo.gl/rtmVbRS6MYb8zSo46)
- [DisposeWorkspace failed](https://cloudlogging.app.goo.gl/5yhfPTd5VXoJCjRj8)

### Expected behavior

The annotation `gitpod.io/disposalStatus` should be updated within the context deadline to reflect the actual disposal status of this workspace.

I think all the Kubernetes client-go operations Get/Update/List/Delete should use the context with a [timeout](https://github.com/gitpod-io/gitpod/blob/7ea0256d97221b3daa9672a7a58b8069e01ad8c6/components/ws-manager/pkg/manager/manager.go#L129) rather than use the parent content.

**Comment by kylos101** [comment]
@aledbf @sagor999 what do you think about `I think all the Kubernetes client-go operations Get/Update/List/Delete should use the context with a [timeout](https://github.com/gitpod-io/gitpod/blob/7ea0256d97221b3daa9672a7a58b8069e01ad8c6/components/ws-manager/pkg/manager/manager.go#L129) rather than use the parent content.`? 

This seems like it is a problem that would be partially solved by ws-manager-mk2, because we would not (for example) have to rely on the annotation on the pod. Instead, we'd track state in the CRD instance.

Questions:
1. Would we still rely on the `client-go` library to interact with the CRD instance?
2. What sort of timeout would we use when interacting with the CRD instance? It seems like we'd have the same problem/decision to make Re: using a context with a timeout versus the parent context.

**Comment by jenting** [comment]
We still need to pass context even if we use ws-manager-mk2 to interact with CRs.

**Comment by jenting** [comment]
We did not see an error message `was unable to update pod's retrying disposal status - this might cause an incorrect disposal status` in these two clusters over 1 week.
- us73 https://cloudlogging.app.goo.gl/5yPJpmrsxF8G1GxY9
- eu73 https://cloudlogging.app.goo.gl/cuKku5pMY8x1yZ4z9
