### ISSUE TITLE
[pvc] `/workspace` directory is owned by `nobody`

### ISSUE THREAD

**Issue by WVerlaek** [gitpod-io/gitpod#14003]
### Bug description

/workspace directory is owned by nobody

### Steps to reproduce

On a workspace with PVC enabled, the `/workspace` directory is owned by `nobody`:
```
$ ls -al /
...
drwxrwsr-x  13 nobody gitpod  4096 Oct 19 13:13 workspace
```

This prevents e.g. the root user from making a new directory inside `/workspace` (but it's fine when done from the `gitpod` user):
```shell
$ sudo mkdir -p /workspace/directory
mkdir: cannot create directory ‘/workspace/directory’: Permission denied

```

With pvc disabled, it's owned by `gitpod`:

```
$ ls -al /
...
drwxr-xr-x   7 gitpod gitpod   98 Oct 19 13:41 workspace
```

### Expected behavior

The prebuild workspace should be up and running.

### Anything else?

#7901

**Comment by sagor999** [comment]
This is due to the way k8s mounts PVC. It mounts folder as root:root.
We specify `FSGroup` [here](https://github.com/gitpod-io/gitpod/blob/95631caa58aa038cd48e33b75b9f794136e0ac67/components/ws-manager/pkg/manager/create.go#L591) when mounting that pvc, so that at least it is owned by gitpod group, but there is no k8s way of specifying user that should be used to mount that folder AFAIK.
One workaround that I know of is to use init container that would do `chown` on that folder to change ownership to gitpod user. It only needs to do chown on that folder only, not recursive, so it should be very fast.

@jenting @WVerlaek do you guys know a better way?

**Comment by WVerlaek** [comment]
Not aware of a better solution, I think the init container + chown approach makes sense

**Comment by jenting** [comment]
> Not aware of a better solution, I think the init container + chown approach makes sense

+1

Question: I thought we need to recursive all the files and folders to change the UID, doesn't it?

**Comment by sagor999** [comment]
Current progress is blocked until we resolve this: https://github.com/gitpod-io/gitpod/issues/14103

**Comment by kylos101** [comment]
@sagor999 are you still blocked on this issue? I assume no, because @utam0k shipped https://github.com/gitpod-io/gitpod/issues/14103.

**Comment by sagor999** [comment]
nope. PR with fix is pending review.
