### ISSUE TITLE
Define new SLO for StartWorkspace which measures only WebApp side of the call

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#14074]

**Comment by jankeromnes** [comment]
Many thanks for filing and scheduling this issue!

**Question**: What would be the benefit of a WebApp-only StartWorkspace SLO that is not already given by the already-existing cross-team StartWorkspace SLO?

**Comment by easyCZ** [comment]
@jankeromnes The main benefit is identifying how much of the time from the SLO is taken up by the StartWorkspace call to ws-manager, vs the part on the WebApp side. The intent is that we need to understand if the WebApp side is getting worse, such that we can fix it, if needed. Otherwise, know that we're not regressing on our side.
