### ISSUE TITLE
workspaces stuck in INITIALIZING 

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#14108]
incident: https://app.incident.io/incidents/260
affected cluster: `us72`

We noticed that new workspace got stuck in INITIALIZING (their content readiness probe failed), piods had status RUNNING.
The only thing we identified was that ws-manager consumed a lot of RAM and CPU. Restarting it mitigated the symptoms.

![image](https://user-images.githubusercontent.com/32448529/197344454-48c4318e-edc3-4a7c-b8ec-c8d3e70bf2a2.png)

These are the logs from around the time when CPU & allocation rates started rocketing: [logs](https://cloudlogging.app.goo.gl/vvYgFVFbwuGu3e5dA)
I see only two errors:
 - `The container could not be located when the pod was deleted.  The container used to be Running` (instanceId: f5345fbd-2625-45ec-b58f-a719df59e477, [log](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-22T12:53:45Z;query=resource.labels.container_name%3D%22ws-manager%22%0Aresource.labels.cluster_name%3D%22ws-us72%22%0Atimestamp%3D%222022-10-22T12:51:27Z%22%0AinsertId%3D%22b5ausi64ihv2lkju%22;timeRange=2022-10-22T12:50:00.000Z%2F2022-10-22T13:00:00.000Z?project=workspace-clusters))
 - `doFinalize failed` (instanceId: d309b3b3-61fe-428d-b46c-8e6c5558fc1d, [log](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-22T12:59:53Z;query=resource.labels.container_name%3D%22ws-manager%22%0Aresource.labels.cluster_name%3D%22ws-us72%22%0Atimestamp%3D%222022-10-22T12:57:49Z%22%0AinsertId%3D%222j2ixcwpae0x84zv%22;timeRange=2022-10-22T12:50:00.000Z%2F2022-10-22T13:00:00.000Z?project=workspace-clusters))

Other resources:
- [Related slack thread](https://gitpod.slack.com/archives/C0201TXMV54/p1666816767103749)
- [ws-manager pprof](https://gitpod.slack.com/archives/C0201TXMV54/p1666687097358139?thread_ts=1666686719.533279&cid=C0201TXMV54)

**Comment by geropl** [comment]
Potentially related changes:
- https://github.com/gitpod-io/gitpod/pull/13828
- https://github.com/gitpod-io/gitpod/pull/13957

**Comment by MrSimonEmms** [comment]
This appears to have triggered again just now - https://gitpod.pagerduty.com/incidents/Q1HZ3KVKZ31OZ8

**Comment by jenting** [comment]
[ws-manager pprof](https://gitpod.slack.com/archives/C0201TXMV54/p1666687097358139?thread_ts=1666686719.533279&cid=C0201TXMV54)

**Comment by atduarte** [comment]
Potentially resolved by https://github.com/gitpod-io/gitpod/pull/14214 (cc @aledbf)

**Comment by atduarte** [comment]
Potentially resolved by https://github.com/gitpod-io/gitpod/pull/14214.

@aledbf were you able to reproduce the issue and verify that what is described in this issue is not happening anymore?

**Comment by utam0k** [comment]
> The container could not be located when the pod was deleted. The container used to be Running (instanceId: f5345fbd-2625-45ec-b58f-a719df59e477, [log](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-22T12:53:45Z;query=resource.labels.container_name%3D%22ws-manager%22%0Aresource.labels.cluster_name%3D%22ws-us72%22%0Atimestamp%3D%222022-10-22T12:51:27Z%22%0AinsertId%3D%22b5ausi64ihv2lkju%22;timeRange=2022-10-22T12:50:00.000Z%2F2022-10-22T13:00:00.000Z?project=workspace-clusters))

I have created the issue about it
https://github.com/gitpod-io/gitpod/issues/12021

**Comment by kylos101** [comment]
> @aledbf were you able to reproduce the issue and verify that what is described in this issue is not happening anymore?

For gen72, we did a pprof as @jenting shared above, also observed goroutine count were very high 10k and 20k, and fixed with gen73 via https://github.com/gitpod-io/gitpod/pull/14214. 

We cannot necessarily recreate the original issue (being unable to start workspaces, accruing regular not active workspaces), though. However, the goroutine count is now stable in gen73 (below 1k for both clusters while active). We asserted the goroutine behavior prior to shipping gen73 when load testing, and [updated our baseline accordingly](https://www.notion.so/gitpod/Expected-workspace-cluster-performance-fcef20e0b4b243e2ab4b4d1e678cdda0). 

If ws-manager is unable to start workspaces again, and they get stuck in Regular Not Active, we should carefully observe it's [dashboard](https://grafana.gitpod.io/d/ws-manager/gitpod-component-ws-manager?orgId=1&refresh=30s), and create a new issue.

I am going to move this issue to Done, we've validated the goroutine leak is fixed.
