### ISSUE TITLE
Deploy usage in self-hosted

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14129]
We need to deploy the usage component in self-hosted installations. This is needed to ensure that a GetBalance call is reachable in the latest self-hosted release.

**Comment by easyCZ** [comment]
Open questions:
* What values do we set for `creditsPerMinuteByWorkspaceClass` in self-hosted?
* How often do we run the Usage Controller schedule in self-hosted? - 15 minutes like SaaS seems appropriate.

This change will first need to move the `usage` component configuration out of the `experimental` config and into standard config. In this, we'll need to pick sensible values to avoid the need to configure it explicitly by self-hosted.

**Comment by easyCZ** [comment]
Pausing this work. For now, we'll only focus on not using the `usage` component in self-hosted. See [more details](https://gitpod.slack.com/archives/C02EN94AEPL/p1666620805280229).

**Comment by geropl** [comment]
It turns out we really need to deploy the `usage` service, soon. https://github.com/gitpod-io/gitpod/pull/14173 introduced a work around to unblock the release, but we should look into deploying `usage` next week, to make sure it's in for the next release.
Once that's in, we should revert https://github.com/gitpod-io/gitpod/pull/14173/commits/6da8a9f6d536b17187f8e998213e92205e997531.

**Comment by easyCZ** [comment]
The change was reverted in https://github.com/gitpod-io/gitpod/pull/14751, will need to be re-added.
