### ISSUE TITLE
Allow force-killing workspaces

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1419]
### Describe the bug

I keep breaking my environment by running something that unintentionally causes the workspace build to run until timeout:

![image](https://user-images.githubusercontent.com/11302521/79809597-314e9c80-8371-11ea-9115-0aa334369e8e.png)

Where today it prevented me from working due the requirement on gitpod docker build that has been blocked by this (i can't open gitpod anywhere due workspace limit for the period of which gitpod is trying to build something unbuildable)

### Steps to reproduce

1. Run `while true; do true; done` in dockerfile
2. Check https://gitpod.io/workspaces/ and notice that there are is a workplace that you don't have permission to remove/stop/kill:
![image](https://user-images.githubusercontent.com/11302521/79809715-82f72700-8371-11ea-9d5a-295ad775fd00.png)

### Expected behavior

Close environment that is in infinite loop on demand

**Comment by csweichel** [comment]
When stopping a workspace/force-stopping a workspace we'd need to do the following things:
- if the workspace is currently in `prepare`, i.e. building the workspace image, we'd need to take it out of that state and abort the operation for that workspace start only. We cannot do this on image-builder, as others might be waiting for the same image build. Unfortunately this stage is not persistent and we don't know which server holds this state. Canceling this operation will be the most difficult part of implementing the change.
- otherwise we have to perform all those operations, no matter if a previous one failed
  - call `StopWorkspace` for the workspace on its ws-manager
  - trigger a state reconciliation within ws-manager-bridge for this workspace. ws-manager-bridge currently does not have an API that would allow this.
  - poll the database until the workspace is stopped. If this doesn't happen within some amount of time, repeat this process.
