### ISSUE TITLE
[registry-facade] Error on workspace start: `cannot pull image - failed to pull and unpack image` aka unexpected EOF

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14264]
## Bug description

We have observed the following error up to 132 times in 24 hours:

> cannot pull image: rpc error: code = Unknown desc = failed to pull and unpack image “reg.ws-eu73.gitpod.io:20000/remote/7d932e9e-914c-4c14-8341-6d04f079b254:latest”: failed to read expected number of bytes: unexpected EOF

The error did not recur on user retry.

context `https://gitpod.io/#https://github.com/gitpod-io/website/pull/2960`

## Steps to reproduce

N/A

## Workspace affected

https://gitpodio-website-u2l4lu0fymu.ws-eu73.gitpod.io/

## Plan

- [x] Add additional logs to more easily identify the source of the problem
- [ ] Fix failure of IPFS blobsource, as described by @csweichel [[1](https://github.com/gitpod-io/gitpod/issues/14264#issuecomment-1326133073)]

## Anything else

We now have new logs and recent occurrences in gen75 to facilitate the investigation [[1](https://cloudlogging.app.goo.gl/JB82pNWbk5s5saHt9)].

This also was happening in gen72 and gen73 according to [logs](https://cloudlogging.app.goo.gl/T8ozTgZJDxDrMwUU9).

![image](https://user-images.githubusercontent.com/1272076/198696937-4a519d56-2df2-408c-a72d-00a6529dd159.png)

**Comment by kylos101** [comment]
[Another example in eu73](https://gitpod.slack.com/archives/C0201TXMV54/p1667316225493069) (internal).

**Comment by aledbf** [comment]
From the traces, the error occurs downloading from the upstream registry (in `blob.go:175`)

Not sure there is something we can do here because we already returned content to the client.

**Comment by jenting** [comment]
- us73 https://cloudlogging.app.goo.gl/isEt97VWZJa5EhHn7
- us74 https://cloudlogging.app.goo.gl/E7Kuq9EJJkQ7ehgw8

**Comment by kylos101** [comment]
Looks like when this happens, [we log 6 errors at the same time](https://cloudlogging.app.goo.gl/riUkZ7G4HvoSwmcB9)? Almost like we're not backing off. 🤔 


![Image](https://user-images.githubusercontent.com/1272076/199810646-23f08fca-ebd9-4148-85ca-8c0112538eb6.png)

**Comment by kylos101** [comment]
It looks like they're all from the same node, `headless-ws-us74-pool-lm22`.

**Comment by kylos101** [comment]
Leaving this issue in breakdown for now, @aledbf is going to alter logging for registry-facade to collect more details, so we can understand when and what this is happening for. I am going to look in the logs, to see (1) when this started and (2) if there's a pattern.

**Comment by kylos101** [comment]
Log observations:
1. happens in both regions
2. the oldest log entry is from October 5 ([logs](https://cloudlogging.app.goo.gl/pWrcMkbkJTcbgHEt7)) for gen67. 
   * [Our retention holds logs for 30 days, though](https://console.cloud.google.com/logs/storage?project=workspace-clusters)
   * Our earliest logs go back to October 4 20:55 GMT
4. Oct 5 is when we deployed gen70, but, it's possible this started earlier and we just lack logs
5. [Count of error by cluster](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-03T20:24:14Z;lfeCustomFields=resource%252Flabels%252Fcluster_name;query=severity%3DERROR%0A%22unexpected%20EOF%22%0Aresource.labels.container_name%3D%22ws-manager%22;resultsSearch=cannot%20pull%20image;summaryFields=labels%252F%2522compute.googleapis.com%252Fresource_name%2522:false:32:beginning;timeRange=2022-09-04T20:37:42.830Z%2F2022-11-03T20:37:42.830Z?project=workspace-clusters)

Cluster | All Workspaces (count) | Regular Workspaces (count)
-- | -- | --
eu67 | 90 | 80
eu70 | 296 | 296
eu71 | 879 | 405
eu72 | 1229 | 1159
eu73 | 876 | 825
us70 | 316 | 123
us71 | 1063 | 405
us72 | 2006 | 916
us73 | 1613 | 756
us74 | 50 | 10

6. Frequency for the error increased on Oct 12 (gen71) and again on Oct 16 (before gen72)

![Image](https://user-images.githubusercontent.com/1272076/199833246-680b76f7-6abb-4b85-8369-fc5020a64d13.png)

**Comment by atduarte** [comment]
Identified as `blocked` as we are waiting for the deployment of the new logs and respective insights.

**Comment by aledbf** [comment]
new metric deployed, waiting for errors....
![Screenshot from 2022-11-08 20-53-02](https://user-images.githubusercontent.com/161571/200701657-47a6ae75-91b1-4f14-95a6-fc0e9a38adc1.png)

**Comment by kylos101** [comment]
[Still happening in us75](https://cloudlogging.app.goo.gl/JB82pNWbk5s5saHt9), doh! 132 in the last 24h.

**Comment by kylos101** [comment]
[Observation](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%20by%28blobSource,ok%29%20%28gitpod_registry_facade_registry_blob_req_dl_total%7Bcluster%3D%5C%22us77%5C%22%7D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) of recent failures indicates we have failures from the `ipfs` blobSource (1% of the IPFS blob sources were not OK for `us77`). 

Check related logs and logging for IPFS. For example, are there log entries in IPFS that coincide with `unexpected EOF`, like context or connections being forcibly terminated, due to some unexpected limit, in the same zone? Do logging levels or features to be logged need to be adjusted or enabled? What do the logs look like in GCP for our nodes when these errors occur? Are we losing services nodes altogether, thus causing this issue?

@aledbf you mentioned that we might be able to retry on `unexpected EOF`. Can you share an example for what you were thinking? As an alternative, when we get `unexpected EOF`, instead of failing, could we fallback and try to pull the blob from the Internet instead? The intent being to try and start the workspace still.

![Image](https://user-images.githubusercontent.com/1272076/202935702-a5684340-563e-4583-b543-bf764290862d.png)

**Comment by aledbf** [comment]
> you mentioned that we might be able to retry on unexpected EOF

To be able to do that, we need to change registry-facade methods that return io.ReadCloser to io.SectionReader like in [nerdctl](https://github.com/containerd/nerdctl/blob/main/pkg/ipfs/registry.go#L197)

**Comment by kylos101** [comment]
Moving back to our inbox for now, [this](https://github.com/gitpod-io/gitpod/issues/14264#issuecomment-1321813599) is not trivial, and we need the bandwidth to focus on other groundwork.

cc: @atduarte

**Comment by csweichel** [comment]
Implementing this a special case on top of IPFS should be reasonable straight forward. The IPFS source already returns a `ReaderAt` [[1](https://github.com/gitpod-io/gitpod/blob/8d8cdbfcabca4f584c9dfc536e6f0f68b02b86f8/components/registry-facade/pkg/registry/blob.go#L407-L415)]. We use that ReadCloser with `io.CopyBuffer` [[2](https://github.com/gitpod-io/gitpod/commit/88f310a172fd6a6c2826e047261c2252f3229156)] to which the retry would be transparent if we returned `SectionReader`.

**Comment by kylos101** [comment]
Hey @sagor999 , can you see if we can install and run IPFS in a harvester preview environment, using [these instructions](https://github.com/gitpod-io/gitpod/issues/12023#issuecomment-1213515387)? And then, to trigger the EOF, perhaps we can try restarting the CNI pod?

**Comment by kylos101** [comment]
Still [happening with gen85](https://cloudlogging.app.goo.gl/Gnh3yNCc5m96axWS6) according to the logs.


![Image](https://user-images.githubusercontent.com/1272076/217345023-46abd740-abed-4d42-aaa1-e5b3eab6e2c0.png)


The `gitpod_registry_facade_registry_blob_req_dl_total` appears to be getting dropped, so that makes these errors hard to observe from a metric standpoint.

**Comment by kylos101** [comment]
As a next step, for Breakdown, for these workspace starts that failed, we should analyze how long we tried pulling. For each blob, we would have tried for [up to one minute](https://github.com/gitpod-io/gitpod/blob/42c91536755c32757e99d2cd8e3b958a3b654a89/components/registry-facade/pkg/registry/blob.go#L179).

**Comment by kylos101** [comment]
We just had an alert, where a high rate of workspace starts were failing:


![Image](https://user-images.githubusercontent.com/1272076/221237116-2680e87f-ca89-49c6-b05d-61caf7692431.png)


![Image](https://user-images.githubusercontent.com/1272076/221230024-8a8f3ed9-205c-4832-a8e9-5bd46d411096.png)

We saw in this order:
1. `2023/02/24 15:10:27 http: superfluous response.WriteHeader call from github.com/docker/distribution/registry/api/errcode.ServeJSON (handler.go:37)` in `registry-facade` [here](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-02-24T15:10:27.009782355Z;query=--%20error_group%2528%22CLTZ2Jik-piwNg%22%2529%0AlogName:%22stderr%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22workspace-clusters%22%0A--%20resource.labels.pod_name%3D%22registry-facade-r5zr5%22%0Aresource.labels.cluster_name%3D%22ws-us88%22%0A--%20resource.labels.location%3D%22europe-west1%22%0Aresource.labels.container_name%3D%22registry-facade%22%0Aresource.labels.namespace_name%3D%22default%22%0A--%20%22cannot%20push%20to%20IPFS%22%0Aseverity%3DERROR%0A%22superfluous%22%0Atimestamp%3D%222023-02-24T15:10:27.009782355Z%22%0AinsertId%3D%223eqoden07ev1dyzl%22;timeRange=2023-02-24T12:27:44.855Z%2F2023-02-24T15:27:44.855Z?project=workspace-clusters)
2. [This warning](https://github.com/gitpod-io/gitpod/blob/ad26ca1a572b77dbe08563874c6a99a1a3939d4d/components/registry-facade/pkg/registry/blob.go#L185) presented often, `retry get blob because of error`
3. Confirmed in [error groups](https://console.cloud.google.com/errors;time=PT6H?project=workspace-clusters)

![Image](https://user-images.githubusercontent.com/1272076/221236121-a9efdec1-b86b-4998-8dc8-44905b2f0b7c.png)

4. This was because `unable to return blob` for `ipfs` ([code](https://github.com/gitpod-io/gitpod/blob/ad26ca1a572b77dbe08563874c6a99a1a3939d4d/components/registry-facade/pkg/registry/blob.go#L194)) was [happening often](https://cloudlogging.app.goo.gl/gx8KuJAN5gD5v6GSA) (59 of 60 occurrences).
   * `unable to return blob: read tcp 192.168.15.2:56228->10.30.93.86:9095: read: connection reset by peer` and
   * `timed out waiting for the condition`

![Image](https://user-images.githubusercontent.com/1272076/221238957-8b32e0a4-85a0-4b0f-a31a-4915a5ca8583.png)

It would be interesting, as part of this work to do a load test, which pulls many different images (right now we use a handful of different images), so that we can stress test the write (caching) of new images to IPFS, and then start workspaces that depend on those cached images.

From an implementation perspective, our thought is to make a composite reader, and it would fail forwards (local would degrade to IPFS, IPFS would degrade to upsteam registry, a failure at the upstream registry would be terminal).

**Comment by gounthar** [comment]
I have the same problem today with https://gitpod.io/?autostart=true#https://github.com/jenkins-docs/quickstart-tutorials .

**Comment by kylos101** [comment]
> I have the same problem today with https://gitpod.io/?autostart=true#https://github.com/jenkins-docs/quickstart-tutorials .

hey @gounthar , could I ask you to try again when you get a moment? We disabled a potential source of problematic cache, and expect your experience to be better now.

**Comment by gounthar** [comment]
It works now, thanks a lot for the fix! 🙏
