### ISSUE TITLE
No error shown when workspace fails to start due to supervisor error

### ISSUE THREAD

**Issue by WVerlaek** [gitpod-io/gitpod#14293]
### Bug description

When a workspace fails to start due to `supervisor` exiting with an error (e.g. [failing to setup the `gitpod` user in a custom image](https://github.com/gitpod-io/gitpod/blob/2b82c4be43a23b6b890d40ea3f0bd5483b415a1c/components/supervisor/pkg/supervisor/supervisor.go#L179)), the workspace immediately transitions to stopping and stopped, but doesn't show any error to the user:

![image](https://user-images.githubusercontent.com/9721064/199032516-0f8366a8-5196-47ac-8ca4-c355e1e0e224.png)

Related: https://github.com/gitpod-io/gitpod/issues/12978#issuecomment-1295210324 (has some more context as well)

### Steps to reproduce

- Start workspace with a custom base image that doesn't have the `gitpod` user (e.g. `hashicorp/terraform:1.2.9`)
- `supervisor` fails to add the `gitpod` user and exits
- Workspace transitions to stopping -> stopped states without showing an error

### Expected behavior

An error is shown to users if a workspace fails to start due to `supervisor` exiting with an error. If the error is for a missing `gitpod` user, the error message sent to the user should include a [link to our docs on custom base images](https://www.gitpod.io/docs/configure/workspaces/workspace-image#custom-base-image).

**Comment by kylos101** [comment]
@akosyakov would you like Team IDE to own this one,or, is it one of those scenarios where maybe you'd prefer Team Workspace contribute to Supervisor? cc: @Furisto @utam0k @WVerlaek

**Comment by akosyakov** [comment]
@kylos101 if it is urgent for the workspace team because of PVC go ahead and create a PR 🙏

**Comment by kylos101** [comment]
:wave: @akosyakov not urgent because of PVC (even when using object storage, the user gets an error message that is not helpful, so both failure modes are roughly the same). If I were to ask IDE team to do, could you estimate when you may be able to ingest as part of groundwork? That will help us know if we should do or not.

**Comment by kylos101** [comment]
Updated expected behavior to include a link if the `gitpod` user is missing.

**Comment by akosyakov** [comment]
We will consider it next Monday.

**Comment by kylos101** [comment]
For posterity, @WVerlaek is going to raise a PR, [reference](https://github.com/gitpod-io/gitpod/issues/12978#issuecomment-1300652319).

**Comment by kylos101** [comment]
Doh! Thank you, @WVerlaek .

Does this mean we still need help from IDE team? I ask because it's still in their inbox, and @akosyakov shared they were going to pick it up next week.

**Comment by WVerlaek** [comment]
@kylos101 yes if possible 🙏 

Just raised the `adduser` fix here: https://github.com/gitpod-io/gitpod/pull/14438

**Comment by kylos101** [comment]
Perfect, thanks for clarifying @WVerlaek ! :muscle: @akosyakov please let @WVerlaek know if you bump into any trouble or need help testing.

**Comment by kylos101** [comment]
Hi @mustard-mh , I tested https://github.com/gitpod-io/gitpod/pull/14650 with https://gitlab.com/kylos101/prebuild-experiment/-/blob/kylos101/customer-image/.gitpod.yml#L1, which should cause an error due to the `gitpod` user missing, but, the error message only mentions the exit status is 1. I was expecting a better error message to the user, for example, a message sharing that the `gitpod` user is missing. In other words, an exit status of 1 does not tell me what to fix so that my workspace can start.

Is that possible to change? Here is what I see now when trying to start a workspace from this [branch](https://gitlab.com/kylos101/prebuild-experiment/-/tree/kylos101/customer-image):

![image](https://user-images.githubusercontent.com/1272076/201775987-7915c204-e313-49d9-961e-38fd3cd2b41d.png)

@WVerlaek what sort of error message were you expecting to see? The workspace I tested with is https://kylos101-prebuildexperi-3ui0u5wx2ib.ws-us75.gitpod.io/.

**Comment by kylos101** [comment]
cc: @akosyakov

**Comment by WVerlaek** [comment]
Maybe on workspace startup failure, if it's an alpine-based image we can somehow show that it's not something we support currently?

**Comment by kylos101** [comment]
> Maybe on workspace startup failure, if it's an alpine-based image we can somehow show that it's not something we support currently?

@WVerlaek Can you create that as a separate issue for supervisor and inbox to IDE team?

**Comment by kylos101** [comment]
> @kylos101 in that specific example (a `terraform` workspace image) the bug in #14438 gets triggered which fails to add the `gitpod` user, if that issue gets fixed it shouldn't error on a missing `gitpod` user anymore. `supervisor` will still fail to start the `terraform`-based workspace though once fixed, as it's missing some other required tools as well (it's an alpine image, which was mentioned in the issue that we don't really support)

@WVerlaek whoops, thank you! For this issue, could you update the description? For example, `Steps to recreate` should avoid using an alpine image as the base image.

@mustard-mh what happens if you try using a custom image that is not alpine based? For example, is the error `exit status 1`, or does the error message indicate something else - like the `gitpod user is missing`?

**Comment by mustard-mh** [comment]
> @mustard-mh what happens if you try using a custom image that is not alpine based? For example, is the error exit status 1, or does the error message indicate something else - like the gitpod user is missing?

If you use custom image that is not alpine based, it will success, because even you don't have gitpod user, supervisor will create it, but it still can failed by some reason, e.g `missing useradd or adduser`

We will continue improve this error message in following PR
