### ISSUE TITLE
[UBP] Free tier Balance Used and Usage page do not show correct credits used 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14363]
The personal and team billing pages both show a progress indicator for "Balance Used" with actual usage against the usage limit. 

The usage detail page (for individuals and teams) both show a similar total credits used for the current period.

These indicators should derive their **"credits used"** value from credits used **since the last invoice/reset**, instead of assuming a calendar billing cycle.

The calculation should mirror the logic used to compute "credits used" to show the usage limit 80% or limit exceeded notifications and prevent workspace starts.

**Comment by jldec** [comment]
Related to #14367

**Comment by geropl** [comment]
I think the idea here was instead of retrieving the limit value, make sure that the selected time range matches what we expect from the Billing page. :thinking:

**Comment by geropl** [comment]
Steps to tackle this:
- [ ] fix "usage bar"
  - [ ] extend the [GetStripeSubscriptionResponse](https://github.com/gitpod-io/gitpod/blob/f52f5817a6bce420b62bc1dcdec0a977e077da53/components/usage-api/usage/v1/billing.proto#L98-L100) to also contain billingPeriod information
  - [ ] make that available via JSON RPC
  - [ ] use those values in the BillingConfig view to set/calculate period start&end [here](https://github.com/gitpod-io/gitpod/blob/c2f4fe34f8ffc953cc8b8e2003010e9687a9137b/components/dashboard/src/components/UsageBasedBillingConfig.tsx#L47-L49) (which will fix the display in the usage bar because we now select correctly)
 - [ ] make "Usage view" select arbitrary dates
  - [ ] add parameters for date selection, e.g.: `https://gitpod.io/t/gitpod/usage?start=...&end=...`
  - [ ] if set, use those [here](https://github.com/gitpod-io/gitpod/blob/5e09a4daafcfca50a955492833d559ff76a802c5/components/dashboard/src/components/UsageView.tsx#L52-L54)
 - [ ] make the "Usage View" link on the BillingConfig page set the start/end parameters based on the actual BillingCycle

**Comment by jldec** [comment]
Reported again today by early-access user [here](https://app.frontapp.com/open/cnv_jyhp2tm) (interna) and by Gitpodder [here](https://gitpod.slack.com/archives/C02EN94AEPL/p1667597629322679?thread_ts=1667333153.719269&cid=C02EN94AEPL) (internal).

**Comment by easyCZ** [comment]
> fix "usage bar"
 extend the [GetStripeSubscriptionResponse](https://github.com/gitpod-io/gitpod/blob/f52f5817a6bce420b62bc1dcdec0a977e077da53/components/usage-api/usage/v1/billing.proto#L98-L100) to also contain billingPeriod information

The StripeSubscription will only contain details if there's a Stripe subscription. It seems like we need the CostCenter for this. However, currently Stripe doens't set the NextBillingTime for that. We could have it set the NextBillingTime
