### ISSUE TITLE
VSCode extension keeps showing October update notes

### ISSUE THREAD

**Issue by fitztrev** [gitpod-io/gitpod#14376]
### Bug description

I am getting the Gitpod extension's October update notes opening in VSCode every time a new window is open. Can't seem to dismiss.

Happening on Mac VSCode, Linux VSCode, and within Gitpod web instances.

### Steps to reproduce

Open new VSCode window while having Gitpod extension installed.

**Comment by jimmybrancaccio** [comment]
[Related Discord Thread](https://discord.com/channels/816244985187008514/1037507071597367346/1037507071597367346).

**Comment by mustard-mh** [comment]
It should be fixed after gitpod version `v0.0.63`. Could you check @fitztrev ? 🙏 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/20944364/199664370-b9ba50d4-d3e4-431d-bff6-fd3ed8ebcaa6.png">

For gitpod browser vscode, I can't reproduce it. I assume that it's because you open workspace with VSCode Desktop. 

Reopen it if you still face this problem
