### ISSUE TITLE
Create an admin page feature to restore latest snapshot to a new workspace

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#14380]
admin clicks a button, as a user, this would create a new workspace, where the target snapshot is the latest (in the DB), and as a user, I'd see an existing workspace with my data restored.

**Comment by sagor999** [comment]
When we create new workspace, we can pass into it any snapshot ID that we want it to restore from (in theory).
So this would piggy back on this. Essentially it would allow admin to open any existing workspace, by restoring its snapshot (PVC) , and thus allow us to provide any files to the customer if they cannot access their workspace for some reason anymore.
(Since we are deprecating download workspace feature)
