### ISSUE TITLE
Hide useless debug output from werft job

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#14439]
### Bug description

Here is an example, I have a failed job and have to scroll through hundreds of lines of debug output (`get go package output`) to get to the bottom of it and actually see an error message:
![image](https://user-images.githubusercontent.com/18602811/200014948-2506aa63-651e-4d99-a648-a42f38755362.png)

Werft: https://werft.gitpod-dev.com/job/gitpod-build-jenting-13980.11

Can we hide that debug output? 

### Steps to reproduce

n\a

**Comment by meysholdt** [comment]
Is this issue about completely removing the logs, or is it about hiding them in CI by default while still having a way to access them?
I assume the latter because I assume the logs are useful to see if the build is doing something (downloading stuff) and to see the exact versions that got pulled into the build. 

If it's about hiding the logs, we should fix https://github.com/gitpod-io/ops/issues/5749 first and then look into it. 

If this is urgent and about removing the logs completely, I think we'll need to adopt https://github.com/gitpod-io/leeway to make this happen. In this case, can you file an issue in the leeway repository? 

Let me know if I'm missing something.

**Comment by sagor999** [comment]
Removing them from CI by default would be a great start.
But I would imagine either way it would require some sort of leeway modification to enable that, so created issue https://github.com/gitpod-io/leeway/issues/107

**Comment by mads-hartmann** [comment]
The Leeway issue has been fixed, keeping this open version [0.6.0](https://github.com/gitpod-io/leeway/releases/tag/v0.6.0) is in use in our dev image.

**Comment by sagor999** [comment]
This has been fixed already. Closing.
