### ISSUE TITLE
End of line / EOL

### ISSUE THREAD

**Issue by vivek-verma202** [gitpod-io/gitpod#1447]
### The bug
I am not sure if this issue traces back to Theia. The IDE adds extra line breaks.
### The behavior
*when I copy (cntrl + c) and paste in my Ubuntu terminal, the output looks:*
> for i in {1..22}; do
> 
> cat -> test_${i} << EOF
> 
> #!/bin/bash
> 
> echo ${i}
> 
> EOF
> 
> done

### Expected behavior
> for i in {1..22}; do
> cat -> test_${i} << EOF
> #!/bin/bash
> echo ${i}
> EOF
> done

### Additional information
*tried fixing it manually (with no luck):*
"files.eol": "\n"

**Comment by jankeromnes** [comment]
Hi @vivek-verma202, are you copying text from a Theia editor and pasting them in an Ubuntu Terminal, or the other way around? (Or did I misunderstand?)

Maybe it could be helpful if you provide a screenshot or screencast demonstrating the problem.

**Comment by Kreyren** [comment]
***kreyren** is infuriated by the bash used and can't resist not commenting on it*

fwiw double-quote the variables to avoid word-splitting, don't use echo since it's non-standard on XNU, useless use of cat and surrounding variables in curly brackets is bloat, use shellcheck https://github.com/koalaman/shellcheck so the correct version would look like:

```bash
for int in {1..22}; do
<<-EOF > "test_$int"
    #!/usr/bin/env bash
    printf '%s\n' "$int"
EOF
done
```

***kreyren** runs away, because it's off-topic*

**Comment by vivek-verma202** [comment]
the script:
> for i in {1..5}; do
> echo ${i}
> done
Look on the gitpod editor (no extra spaces):
![code_edit](https://user-images.githubusercontent.com/33168572/80409094-46a65800-8896-11ea-8b91-67c0de9269d9.png)

Look on the gitpod editor's terminal (again, no extra spaces):
![t1](https://user-images.githubusercontent.com/33168572/80409284-9553f200-8896-11ea-8684-5f3c7dfff07c.png)

And, when I copy - paste to Ubuntu terminal:
![Screenshot from 2020-04-27 14-52-30](https://user-images.githubusercontent.com/33168572/80409414-d0eebc00-8896-11ea-8d6a-bf786b794d43.png)
 (These extra EOLs is not an issue, unless in case of scripts which expect first line to be shebang.)

**Comment by Kreyren** [comment]
FWIW i don't have this issue on my end:
![image](https://user-images.githubusercontent.com/11302521/80410859-88052a80-88cb-11ea-935a-08fc2ce53fe0.png)

Caused by an extension?

Something relevant to ubuntu terminal?

**Comment by Kreyren** [comment]
Is this gitpod on windows parsed to WSL ubuntu terminal? (Windows is placing garbage on new-line that usually cause this behaviour)

**Comment by vivek-verma202** [comment]
I am using Google chrome on Ubuntu machine. 
Copying and pasting on gedit shows no anomalous line break behavior.

Copying lines from Gitpod -> text editor (Gedit) -> Ubuntu 20 / CentOS 7 terminal: again, no anomalous line line breaks.

I have asked Gitpod explicitly to use \n as EOL. But I do notice a small "!" on my settings.json file. Is something wrong with it? 

![Screenshot](https://user-images.githubusercontent.com/33168572/80426525-e32b2300-88b3-11ea-9d7c-71f344e071a7.png)

**Comment by Kreyren** [comment]
> Copying and pasting on gedit shows no anomalous line break behavior.

Afaik gedit won't show these since it's formatting the text, can you copy paste these in http://dpaste.com/ ? (or any other way to get raw to us)

> I have asked Gitpod explicitly to use \n as EOL. But I do notice a small "!" on my settings.json file. Is something wrong with it?

1. `editor.cursorWidth` is invalid, because you are parsing string to property that expects integer, see
![image](https://user-images.githubusercontent.com/11302521/80452108-0a660c80-8915-11ea-9cf9-1659dc081008.png)

recommends removing double-quotes `"` from value

2. There also seems to be other issues that i can't reproduce on my system, try hovering over theses underscored properties to see what is wrong:
![image](https://user-images.githubusercontent.com/11302521/80451896-814ed580-8914-11ea-8ffc-5fff9e340783.png)

Note that gitpod is linting `settings.json` so you can see all the problems in:
![image](https://user-images.githubusercontent.com/11302521/80452228-50bb6b80-8915-11ea-9b1b-e3df4e362170.png)

3. If that did not help then try to make a backup of your current `settings.json` and see if the issue persist, if not try to figure out which property is causing this behavior and report it to us. :)

4. If changing the `settings.json` did not help, then provide me list of extensions used. You can find these in `.gitpod.yml`:
![image](https://user-images.githubusercontent.com/11302521/80452409-c32c4b80-8915-11ea-88c3-b19e8f8145d1.png)

**Comment by svenefftinge** [comment]
FWIW I also cannot reproduce this on my mac using chrome. I tried with auto and \n settings for files.eol.
The warnings (!) you see in your settings are indicating that you have specified the same value twice. You should remove one. But really this is unrelated.

**Comment by vivek-verma202** [comment]
Thank-you so much guys! I was able to fix silly issues in my settings.json and get rid of the annoying "!". 

Copy paste from Gitpod to http://dpaste.com/ did not show extra line breaks.
Its not terminal settings, bash_profile or .bashrc issue as copy-paste from gedit or http://dpaste.com/  works absolutely fine. 

My "version"of Gitpod / Theia is doing something non-fatal but non-trivial with eols. This is not a generic Gitpod / Theia issue as I was not able to reproduce it when I copy-pasted from: https://ec77d690-8322-4dd1-8052-e70cfe28fd72.ws-us02.gitpod.io/#/workspace/spring-petclinic

Hence, there seems to be something specific with the docker image that I am using. How can I fix it? I need no special functionality (just vanilla sh).

Thanks again.

**Comment by Kreyren** [comment]
> Copy paste from Gitpod to http://dpaste.com/ did not show extra line breaks.

If it's in the raw it won't show up on browser's view of dpaste (browsers do not render these by default) where i was expecting the dpaste link alike http://dpaste.com/0QGE4X4 which looks like this on dpaste: 
![image](https://user-images.githubusercontent.com/11302521/80492752-fdb4d900-8953-11ea-804b-70513ec28bf3.png)

So that i could pipe it in `vim` with `:set lists` shows the special characters:
![image](https://user-images.githubusercontent.com/11302521/80493725-49b44d80-8955-11ea-9ca7-d3df6da34ce8.png)

or in editor capable of rendering invisibles like gitpod (see https://stackoverflow.com/a/61355603 if you want to know how): 
![image](https://user-images.githubusercontent.com/11302521/80494350-1cb46a80-8956-11ea-874f-7a33bbd6ce26.png)

> My "version"of Gitpod / Theia is doing something non-fatal but non-trivial with eols. This is not a generic Gitpod / Theia issue as I was not able to reproduce it when I copy-pasted from:

Can you share your:
1. your used browser? (Ideally user-agent from http://whatsmyuseragent.org/)
2. used kernel? (i.e Windows, MacOS, Linux, Redox!, FreeBSD, etc..)
3. ~~your repository or is it private?~~ assuming private since i can't find it on your profile

>  https://ec77d690-8322-4dd1-8052-e70cfe28fd72.ws-us02.gitpod.io/#/workspace/spring-petclinic

![image](https://user-images.githubusercontent.com/11302521/80494544-4a011880-8956-11ea-82c3-f16595271eca.png)

**Comment by vivek-verma202** [comment]
### The dpaste link: http://dpaste.com/3V6Z4SB

### Gitpod is not allowing me to use:
    "code-eol.newlineCharacter": "¬",
    "code-eol.returnCharacter" : "¤",
    "code-eol.crlfCharacter"   : "¤¬"

### I have made the following workspaces public:
1. gitpod-io/spring-petclinic - master (which adds no extra eols i.e. copy-paste works as expected, got it from "try in Gitpod" on https://theia-ide.org/)

2. vivek-verma202/GWAS_FM - master (which adds extra eols)

### I am using Google chrome, Version 81.0.4044.129 (Official Build) (64-bit).
### User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36


### Linux Kernel:
tried it on two (same problem):

1. Linux version 3.10.0-1062.12.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Feb 4 23:02:59 UTC 2020

2. Linux version 5.4.0-26-generic (buildd@lcy01-amd64-029) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020

**Comment by Kreyren** [comment]
> The dpaste link: http://dpaste.com/3V6Z4SB

Interesting! i see what i assume is unexpected `¤¬` which is on my gitpod character for CRLF (carriage-return) which is what i believe is causing this issue

![image](https://user-images.githubusercontent.com/11302521/80528793-06260780-8986-11ea-8dfa-dd33abe50bef.png)

But this is usually specific to Windows/DOS (never seen this on linux in 14 years) so i find it unexpected that this behavior has been observed on linux which is using `0x0D` character instead of standard new-line `0x0A`

‘\n’ == 10 == 0x0A == line feed

‘\r’ == 13 == 0x0D == carriage return

Based on available informations my best guess would be that  this is caused by some extension that is not optimized for usage on Linux.
Can you try to disable all extensions and if that fixed the issue and if so try to figure out which extension is causing this.

If this solves the issue i recommend filing a new issue to extension developer (that is likely the responsible for this behavior  assuming that we can't reproduce it and available info above) informing them about this behavior.

---

Looking at the provided repository (https://github.com/vivek-verma202/GWAS_FM):
- Repository is not using any repository-wide extension that i can see
- The whole code is using unexpected carriage-return characters instead of new-line:
![image](https://user-images.githubusercontent.com/11302521/80529940-cb24d380-8987-11ea-9716-1ae2980cc79c.png)
- I can reproduce the carriage-return on provided repository in `master.bash`
  - I can't reproduce the behavior in new file -> Assuming that this is copy-pasted bash file that has been originally written on Windows/DOS and gitpod is using the already present carriage return instead of expected new-line
- Created MR https://github.com/vivek-verma202/GWAS_FM/pull/2, please verify if you still have this issue

**Comment by Kreyren** [comment]
> Gitpod is not allowing me to use:

Also as referenced on https://stackoverflow.com/a/61355603 you need this extension https://marketplace.visualstudio.com/items?itemName=medo64.render-crlf for gitpod to recognize these properties

**Comment by Kreyren** [comment]
Also note https://www.gitpod.io/docs/languages/bash/ for shell-relevant development on gitpod

**Comment by vivek-verma202** [comment]
Got it!!
Fixed the option "CRLF" to "LF" on the lower right panel:
![Screenshot](https://user-images.githubusercontent.com/33168572/80542114-74fd6380-897a-11ea-952d-786c7c9d4f28.png)

Thank you so much for your help!
Gitpod's a pretty awesome concept. Keep up the hard work..

**Comment by Kreyren** [comment]
***kreyren** forgot that option is there x.x* 

@vivek-verma202 also a solution! :p but you should consider using shellcheck anyway it prevents lots of problems ^-^
