### ISSUE TITLE
Scaling Up/Down Service Nodes in EKS Causes Problems With Pods That Use Persistent Volumes

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#14529]
### Bug description

When scaling down a services node and then scaling it back up you may see that services/pods on that node fail to come back online due to volume mounting issues because of availability zones. This was originally reported with the OpenVSX Proxy but I was also able to replicate the issue with the MinIO pod.

### Steps to reproduce

1. Create an EKS cluster using the single-cluster reference architecture guide. You should have 2 service nodes and 2 workspace nodes as a result.
2. Deploy Gitpod to your new cluster.
3. Confirm things are u and running - for example setup the default SCM, and start up a new workspace. You can keep the workspace running or stop it.
4. Within AWS go to your cluster, and underneath the 'Cluster Info' block you should see several tabs. Click on the 'Compute' tab. Then within the 'Node groups' section click on the 'services' group.
5. Next click on the 'Edit' button in the upper right.
6. On the edit page scale nodes down to 1 and then save.
7. Keep an eye on your pods (something like `kubectl get po -n gitpod`).
8. At this point you may observe that a service pod is unable to start up or stuck in 'pending'.
    ```
    minio-9c5f788fd-4t2gh                  0/1     Pending     0              4m25s
    ```
    If you describe the pod you should see something like:
    ```
    Events:
    Type     Reason            Age                    From               Message
     ----     ------            ----                   ----               -------
    Warning  FailedScheduling  3m29s (x4 over 6m29s)  default-scheduler  0/4 nodes are available: 1 node(s) had volume node affinity conflict, 1 node(s) were unschedulable, 2 node(s) didn't match Pod's node affinity/selector.
    Warning  FailedScheduling  29s (x3 over 2m29s)    default-scheduler  0/3 nodes are available: 1 node(s) had volume node affinity conflict, 2 node(s) didn't match Pod's node affinity/selector.
    ```
9. I then went back to the AWS page and edited the services node group and scaled it back up to 2 nodes. I waited a little however I still saw my MinIO pod was in a 'pending' state.
    ```
    minio-9c5f788fd-4t2gh                  0/1     Pending     0              13m     <none>          <none>                                          <none>           <none>
    ```
    and a describe on the pod showed a similar error:
    ```
    Events:
    Type     Reason            Age                    From               Message
    ----     ------            ----                   ----               -------
    Warning  FailedScheduling  10m (x4 over 13m)      default-scheduler  0/4 nodes are available: 1 node(s) had volume node affinity conflict, 1 node(s) were unschedulable, 2 node(s) didn't match Pod's node affinity/selector.
    Warning  FailedScheduling  4m46s (x6 over 9m46s)  default-scheduler  0/3 nodes are available: 1 node(s) had volume node affinity conflict, 2 node(s) didn't match Pod's node affinity/selector.
    Warning  FailedScheduling  4m17s                  default-scheduler  0/4 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 1 node(s) had volume node affinity conflict, 2 node(s) didn't match Pod's node affinity/selector.
    Warning  FailedScheduling  16s (x5 over 3m47s)    default-scheduler  0/4 nodes are available: 2 node(s) didn't match Pod's node affinity/selector, 2 node(s) had volume node affinity conflict.
    ```
10. I again went back to the AWS page and edited my node group and scaled it up again to 3 nodes. That seems to have done the trick and the MinIO pod was able to start up properly.
    ```
    minio-9c5f788fd-4t2gh                  1/1     Running     0              20m     172.16.47.2     ip-192-168-103-32.us-east-2.compute.internal    <none>           <none>
    ```
    and we can see the volume was able to attach:
    ```
    Events:
    Type     Reason                  Age                 From                     Message
    ----     ------                  ----                ----                     -------
    Warning  FailedScheduling        52m (x4 over 55m)   default-scheduler        0/4 nodes are available: 1 node(s) had volume node affinity conflict, 1 node(s) were unschedulable, 2 node(s) didn't match Pod's node affinity/selector.
    Warning  FailedScheduling        46m (x6 over 51m)   default-scheduler        0/3 nodes are available: 1 node(s) had volume node affinity conflict, 2 node(s) didn't match Pod's node affinity/selector.
    Warning  FailedScheduling        46m                 default-scheduler        0/4 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 1 node(s) had volume node affinity conflict, 2 node(s) didn't match Pod's node affinity/selector.
    Warning  FailedScheduling        36m (x10 over 45m)  default-scheduler        0/4 nodes are available: 2 node(s) didn't match Pod's node affinity/selector, 2 node(s) had volume node affinity conflict.
    Warning  FailedScheduling        36m                 default-scheduler        0/5 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 2 node(s) didn't match Pod's node affinity/selector, 2 node(s) had volume node affinity conflict.
    Normal   Scheduled               36m                 default-scheduler        Successfully assigned gitpod/minio-9c5f788fd-4t2gh to ip-192-168-103-32.us-east-2.compute.internal
    Normal   SuccessfulAttachVolume  36m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-704f95fc-d022-43b7-b9d1-ab878943827f"
    Normal   Pulling                 35m                 kubelet                  Pulling image "docker.io/bitnami/minio:2022.5.26-debian-10-r0"
    Normal   Pulled                  35m                 kubelet                  Successfully pulled image "docker.io/bitnami/minio:2022.5.26-debian-10-r0" in 10.086771192s
    Normal   Created                 35m                 kubelet                  Created container minio
    Normal   Started                 35m                 kubelet                  Started container minio
    ```

### Expected behavior

I would expect that having used our single cluster reference architecture to create an AWS EKS cluster that when scaling up or down my service nodes it wouldn't cause issues with pods being able up to start up.

### Anything else?

It seems when scaling nodes back up it requires that I have the same amount of nodes that I do availability zones. This is just a theory though.

I'd like to get a better understanding how we can prevent this from happening. Does the reference architecture document need to be updated? Or does the product need to be updated?

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3t00a)

**Comment by adrienthebo** [comment]
Copying discussion from slack:

A cursory glance indicates that EBS volumes are scoped to a single availability zone; to support a multi-AZ cluster we'll need to switch to using EFS (which is 3x the cost of EBS). We're seeing a lot of development and support overhead to cover all possible self-hosted deployment scenarios and the reference architectures should nominally minimize the amount of area we need to support. We should either support EBS and single AZ EKS clusters, EFS and multi-AZ clusters, but not both to further the goal of more consistent support.

The AWS documentation on the [Amazon EFS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) would be a good starting point to explore replacing EBS with EFS.

**Comment by MrSimonEmms** [comment]
This might not necessarily be relevant to the issue at hand, but why does an AWS user have a Minio pod in their Gitpod cluster? As I recall, Minio should only be there if they're using in-cluster object storage or Azure for storage (in this case, it's just a gateway to provide an S3 interface - nothing gets stored on the cluster).

Could the problem be solved by switching over from in-cluster storage to external S3? If they do this, there will need to be some work to transfer the blob storage objects from the in-cluster Minio to the external S3, else the current workspaces won't have access to their data. This is not something we've ever tested, but it _SHOULD_ be possible (someone's probably written a tool).

All the in-cluster resources (DB, registry, storage) are designed for convenience rather than performance. The Minio instance only has an 8GB PVC for example.

**Comment by Pothulapati** [comment]
First, This happens because `openVSXProxy` statefulset has a redis container attached that has a PVC volume called `redis-data`. Because of the use `PVC` in the reference architecture (which has a requirement of being reliable and thus zone independent), A new instance could be on different zone causing this problem.

I and @lucasvaltl had a discussion about this, and have the following points:
- Reducing the availability of the whole cluster or just servers node group, doesn't seem like a great fix as it would reduce reliability guarantees of control-plane components in the reference guides, and also causes further customer problems.
- Considering that `openVSXProxy` is the only component that uses PVC for state in the reference architecture. We could either:
   - Change the usage of PVC to `optional`, and disabled by default. Considering OpenVSXProxy's `redis-data` is just a cache, This should not be a problem as it would be refilled after restart. This would add a new installer config.
    - Update the storage of openVSX to use a redis instance that is managed by AWS in the reference architecture. This requires slight application code change (to pass the auth tokens, etc)

**Comment by Pothulapati** [comment]
Created https://github.com/gitpod-io/gitpod/pull/14603 which does 2 i.e making PVC optional through the `disablePVC` option.

**Comment by dnegrisolli** [comment]
I'm facing a similar problem but in a K8s instance baremetal.
The validate-config Pod can't go further, and shows the problem:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-14T02:11:08Z"
    message: '0/2 nodes are available: 2 node(s) didn''t match Pod''s node affinity/selector.
      preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.'
```
Any ideas?

**Comment by Pothulapati** [comment]
@dnegrisolli Interesting, But I don't think its a PVC issue that is happening here i.e pods not being able to spun up in a zone as PVC was created in a different zone.

But I'm guessing your issue is around the node labels. Currently, [Gitpod separates all the components based on node labels](https://www.gitpod.io/docs/configure/self-hosted/latest/reference-architecture/single-cluster-ref-arch#kubernetes-cluster), and expect relevant labels to be present. Can you make sure they are all present? If this is not the issue, Can you please raise a separate issue for the same so that we can track it separately from this AWS zone X EBS issue? :)

Thanks,
Tarun
