### ISSUE TITLE
[Azure] Deployment not starting up

### ISSUE THREAD

**Issue by tuxflo** [gitpod-io/gitpod#14549]
### Bug description

I'm trying to setup gitpod (community license) on Azure to evaluate the tool for our onboarding and dev experience.
I followed the [Azure Installation Guide](https://github.com/gitpod-io/gitpod-microsoft-aks-guide) for the requirements and then did the kots install.
Even though with the preflight checks all green gitpod reports the status "Missing" in the dashboard and the troubleshooting page lists some unavailable resources:
![image](https://user-images.githubusercontent.com/2816893/200804478-ab1b4805-5c21-4348-81c8-b7debc2435c8.png)

The Troubleshooting site also lists some errors:
![image](https://user-images.githubusercontent.com/2816893/200807235-2c4feb47-df0e-42a9-a9b5-52c8b84af995.png)

Since I'm pretty new to k8s I don't know where to start debugging this.

### Steps to reproduce

* prepare Azure cloud usind the aks guide
* install gitpod

### Expected behavior

gitpod is up and running

### Anything else?

I uploaded the tar.gz support bundle to this repo: https://github.com/tuxflo/gitpod-issue/blob/main/supportbundle-2022-11-09T10_18_17.tar.gz

**Comment by Pothulapati** [comment]
Hey @tuxflo 

Thanks for raising the issue. Looking at the analysis.json in the uploaded bundle, I can see a bunch of cert-manager issues. Did you configure cert-manager correctly so that it can get the relevant domain TLS be issued through let's encrypt? 🤔 

There are relevant steps in the [azure guide on them](https://github.com/gitpod-io/gitpod-microsoft-aks-guide#dns-records). Also, If you can find any failure logs in the `installer-*` pod that would be great. (It has the label `component=gitpod-installer` which you can use to get the logs as the installer could fastly complete)

Thanks
