### ISSUE TITLE
Gitpod layer adding fails

### ISSUE THREAD

**Issue by brasilikum** [gitpod-io/gitpod#1475]
### Describe the bug
```
 build failed: cannot build workspace image: The command '/bin/sh -c /var/gitpod/layer.sh     && rm -f /var/gitpod/layer.sh' returned a non-zero code: 1.
Error: build failed: cannot build workspace image: The command '/bin/sh -c /var/gitpod/layer.sh     && rm -f /var/gitpod/layer.sh' returned a non-zero code: 1
```
### Steps to reproduce
Add the following to your .gitpod.Dockerfile
```
FROM bitriseio/docker-android
RUN useradd -ms /bin/bash gitpod
RUN sudo apt-get -q update && sudo apt-get install -yq nodejs python3-pip
RUN pip3 install gmsaas
```

### Expected behavior
The build should work or print a more informative error

### Example repository

https://gitlab.com/brasilikum/bare

**Comment by Kreyren** [comment]
> The build should work or print a more informative error

@brasilikum You are tripping security layer where I nor the script itself can't provide you more informations for this reason, because the security layer is currently kept confidential (i've made contribution that should allow it to be released, but gitpod is slow on review assuming it being huge contribution)

If you elaborate on what you expect to get on gitpod i can submit hotfix changes to gitpod-layer in the meantime or contribute a solution.

**Comment by brasilikum** [comment]
Ok.

I am trying to get the container to work in Gitpod so I can use the adb-tools to connect to an external emulator. Basically I want to be able to do native android development. I am aware that’s not supported directly but I figured if I use an external emulator it should work.

I suspect the error is around the user handling. I got an error related to the Gitpod user so I figured I would add it. That seems to not play nice with their account management is what I understand from you

**Comment by Kreyren** [comment]
@brasilikum Elaborate on the process of using the external emulator.

**Comment by brasilikum** [comment]
That’s the last command. I am installing the cli of genymotion, which I think only does the auth and then uses and to connect to their remote emulators

**Comment by Kreyren** [comment]
@brasilikum Currently i am stuck at:
![image](https://user-images.githubusercontent.com/11302521/81025881-79dd7e00-8e78-11ea-933f-046af9cf2271.png)

Were you able to built the image without any changes?

**Comment by brasilikum** [comment]
Yes, but I got an error wit the gitpod user

**Comment by Kreyren** [comment]
@brasilikum Seems to build for me now if you do not manipulate the gitpod user, can you confirm?

**Comment by Kreyren** [comment]
Also note the chosen dockerfile provider seems to be deprecated assuming that it's using ubuntu-14 which was released in 2013 and based on available informations is end of life since 25 April 2019 (https://en.wikipedia.org/wiki/Ubuntu_version_history#1404)

Assuming that upstream released the dockerfiles you might want to copy+paste them to recent assuming that it seems to need very minor changes.

From what i've seen it seems to take a long time to build, because the dockerimage itself is doing lots of things.

**Comment by Kreyren** [comment]
Clarification: After the first built gitpod will cache the tasks so it won't take as long as initial build.

**Comment by brasilikum** [comment]
@Kreyren thank you very much helping me debug! I will try your suggestions.

As for this pull request: I think there should be more Actionable insight given.

**Comment by Kreyren** [comment]
> As for this pull request: I think there should be more Actionable insight given.

elaborate?

**Comment by brasilikum** [comment]
I think there should be more actionable feedback than: "Gitpod layer adding failed, status 1".
It could be a link explaining that you did something wrong around auth. Just something helping users debug the problem.
This is what I as a user would find useful. Feel free to close this if It's not something you see value in

**Comment by Kreyren** [comment]
> I think there should be more actionable feedback than: "Gitpod layer adding failed, status 1".
It could be a link explaining that you did something wrong around auth. Just something helping users debug the problem.

Agree that's why i made the contribution for it's very verbose and has option for debug flag that will be even more verbose, but again the contribution is huge (basically rewrites whole workspace-images and is around three times bigger atm even with strict code quality to reduce the dead code) and i was told that gitpod staff is currently unable to review all that where i understand that they seems to be working on gitpod's backend that should have a priority.

See https://github.com/gitpod-io/workspace-images/pull/204 that i had to move to private repository due to the usage of confidential info (all checks are completed + i've added more things like the ability to customize the output, gitpod package support depending on the repository used, etc..)

I've split the changes in waves where the first wave is waiting to be processed on https://github.com/jankeromnes/gitpod-layers/pull/3

**Comment by Kreyren** [comment]
@brasilikum just informing: my merge request has been submitted for production waiting for a review now.
