### ISSUE TITLE
Feature-Request: `Disable Student Plan` button in admin panel

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/gitpod#14777]
## Is your feature request related to a problem? Please describe
How Can an admin disable the Student plan for a user?

## Describe the behaviour you'd like

Having a `Disable Student Plan` button similar to `Disable Professional Open Source Plan`

![image](https://user-images.githubusercontent.com/55068936/202631975-213d1d91-d9fa-4cdd-9db2-d4b822244f40.png)

## Describe alternatives you've considered
N/A

## Additional context
[Internal Discussion](https://gitpod.slack.com/archives/C020VCB0U5A/p1667562061871039)

**Comment by gtsiolis** [comment]
Not sure if it's worth the effort since we're planning to end support GitHub Student Pack in favor of better alternatives for the team and wider community, see **[relevant RFC](https://www.notion.so/gitpod/693cba37767e4c3c895d1420eaedb91c)** (internal).

See also [relevant RFC](https://www.notion.so/gitpod/d7af057f0b6042b3af92c12e7cb00179) (internal) for potential improvements for the professional open source plan.

I'd only spent time on this if it takes less than an hour to add. Otherwise, let's put our focus and energy on changes that will improve the user's outcome.

**Comment by Siddhant-K-code** [comment]
This is resolved now ✅
