### ISSUE TITLE
[UBP] Don’t immediately block free-tier users with heavy prebuild usage when UBP is enabled

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14814]
Users with a lot of prebuild usage should not be blocked immediately when we turn on UBP.

#### Taking the following steps to address this:
  - [x] #9898
  - [x] #4353
  - [x] #15144

#### Earlier suggestions
- Enabling UBP should reset the free tier cost center to 500 fresh credits even if past usage was higher
- Users with high prebuild usage should see a warning notification when they have used 400/500 credits 

Related to #9898

See [RFC](https://www.notion.so/gitpod/RFC-Don-t-immediately-block-free-tier-users-with-heavy-prebuild-usage-when-UBP-is-enabled-428b2ed9990a48d68ffca2f0909037ac) (internal) for more details

**Comment by jldec** [comment]
Clarification required - Let look at usage data to see how many cases like this are expected.

**Comment by svenefftinge** [comment]
> Users with high prebuild usage should see a warning notification when they have used 400/500 credits

I'd prefer to generalize this warning to all kinds of low credits. We could email people on low credits.

**Comment by jankeromnes** [comment]
> Users with a lot of prebuild usage should not be blocked immediately when we turn on UBP.

To clarify, why shouldn't they get blocked immediately? (I.e. why is that problematic?)

My thinking is:
- Some users may have an extraordinarily heavy prebuild usage, but this isn't intentional
- When we switch to usage-based GA, they notice this heavy usage (i.e. they get blocked, see a notification, checkout their usage, see what is causing the excessive usage)
- Armed with this knowledge, these users can then fix their excessive prebuilds (e.g. by deleting their unused projects, or restricting prebuilds to only the main branch, something like that)
- Problem solved ✅ ?

> - Users with high prebuild usage should see a warning notification when they have used 400/500 credits

We already have this, right?

https://github.com/gitpod-io/gitpod/blob/304851d0a7d737b33afbf2b63a40baab003685f8/components/server/ee/src/workspace/gitpod-server-impl.ts#L2353-L2355

> We could email people on low credits.

This sounds like an excellent additional feature request. 👍

**Comment by jldec** [comment]
Clarified OP - thanks @jankeromnes, I think your fixes are going to do a lot to help here.
