### ISSUE TITLE
[projects] Introduce "no setting", i.e. default to user's setting for workspace classes

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#14810]
The workspace classes on the projects setting don't make a visual distinction between "no setting" and the set to the default class. But internally the difference is that an explicit project-level setting overrules any user settings.

We need a way in the project settings that communicates/allows setting to "default/ no setting".

**Comment by jldec** [comment]
@svenefftinge @gtsiolis 

How about showing the "use default" (no setting) state in both personal and project settings?
This would allow for users to receive a different default when it is modified say at the org level 😉 .

**Comment by jldec** [comment]
@gtsiolis 
This configuration on projects is optional and the selection UI needs an unselected state.

New and existing projects have no workspace class config and the UI should show that, because it means that the user's preference, or the installation default will be used. Simply showing that default as selected is confusing/wrong because it depends on who is looking at the setting and what their personal preference is at the time.

Going into project settings in order to change the setting is how project owners override the user or installation default.
In gitpod.io, they should see 3 choices and on first use, 1 will be highlighted.

1. Use default e.g. if configured in personal preferences
2. Standard
3. Large

**Comment by svenefftinge** [comment]
we don't need this for now. Maybe introduce it once we have policies for workspace classes on team and org level.

**Comment by gtsiolis** [comment]
Thanks @svenefftinge @jldec!
