### ISSUE TITLE
Highlight expired PATs in ListView

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14947]
When a PAT is expired, we s hould highlight it in some form to communicate the fact it is expired.

CC @gtsiolis if you've got design ideas how to do this.

**Comment by gtsiolis** [comment]
Let's use an orange color for the expiration date to indicate that attention is required. Additionally, we could append an exclamation icon to make it more prominent, see designs below. Cc @easyCZ 

| Expiring access token |
|-|
| <img width="1440" alt="Expires" src="https://user-images.githubusercontent.com/120486/203947263-f8ce4fd3-73cf-4dee-b9f2-6bab6bf84aef.png"> |

**Comment by laushinka** [comment]
> Let's 🅰️ use an orange color for the expiration date to indicate that attention is required. Additionally, we could 🅱️ append an exclamation icon to make it more prominent, see designs below. Cc @easyCZ

Nice. How about we also add text so it says "Expired on Nov 24, 2022"?

**Comment by gtsiolis** [comment]
@laushinka I'd keep the verb out of there to avoid the duplication since we already have the column title. If we decide to redesign the table list layout or remove the list header we could duplicate this prefix to all tokens like the following:

> Token A
> Expires on Dec 24, 2022

> Token B
> ⚠️ Expired on Nov 24, 2022

However, it could make sense to duplicate the expiration prefix to make this information even more prominent. You're welcome to try using the prefix to see how this feels.

**Comment by laushinka** [comment]
> avoid the duplication since we already have the column title

That is a good point. Let's keep it as you proposed.
