### ISSUE TITLE
Collaborate: mouseup event listener not triggered

### ISSUE THREAD

**Issue by ghost** [gitpod-io/gitpod#1499]
When my colleague clicks anywhere on the window the "mouseup" event listener does not trigger. The "click" event triggers though.

**Comment by thoughtsunificator** [comment]
wheel also does not work

**Comment by Kreyren** [comment]
reopening assuming that the issue is not solved

**Comment by Kreyren** [comment]
@thoughtsunificator I don't understand what is the issue, care to elaborate?

***kreyren** likes screenshots and short videos*

**Comment by thoughtsunificator** [comment]
You will probably tell me that this is ongoing work but I might as well explain:

When collaborating on a project, there's this great feature for the preview that shares events across multiple client so that when you click a button it is also clicked on all the other clients.

The thing is that mouseup (problably mousedown too) and wheel (probably more too) they only trigger for the source of the event. mouseup triggers for me but not for the other clients.

I hope that was clear enough.

**Comment by Kreyren** [comment]
> You will probably tell me that this is ongoing work but I might as well explain

Personally i like investigate and potentially fix anything relevant so if you find something that doesn't work as expected on gitpod or can be improved then i want to know about it! ^-^

> The thing is that mouseup (problably mousedown too) and wheel (probably more too) they only trigger for the source of the event. mouseup triggers for me but not for the other clients.

I am not familiar with this feature, but it looks like bug to me.

cc @jankeromnes

**Comment by thoughtsunificator** [comment]
The sync events across client behavior actually comes from browser-sync, who would have thought... I recently updated all my projects to use browser-sync because gitpod would not simply load my index.html (also Chrome is a pain in the ass too).

So this has nothing to do with gitpod it's just browser-sync sending events across all client that loaded the preview.

Sorry.

**Comment by Kreyren** [comment]
I like to believe that i understand around 35% of what you are saying, but if something confused you on gitpod maybe we can do something to avoid similar confusion in the future?

Reopening in case there is something that can be done by upstream.

**Comment by Kreyren** [comment]
Assuming possible UX issue
