### ISSUE TITLE
Epic: Automate blue/green deployments of workspace clusters

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#15068]
Currently workspace cluster blue/green deployments, including preparation, validation and traffic-shifting, are manual which results in a lot of person-hours wasted. As we are growing the number of Gitpod installations we manage, we need to reduce that burden. 

We are aiming to have in-place workspace application roll-outs (#15065). Although we know we will still have the need for blue/green deployments at least for infrastructure related changes. Therefore, we still need to invest in their automation.

## Value

1. Enable Gitpod Dedicated growth
2. Reduce engineering effort wasted on manual deployment and traffic shift

## Success Criteria

1. Full workspace roll-outs of multiple Gitpod installations, where entirely new workspace clusters are deployed, are achievable with a click of button
3. Roll-out success is automatically monitored, and in case of issues roll-back is automatically initiated
4. Manual rollback should be similarly possible
3. Roll-outs and roll-backs result in no service disruption
4. What we build is applicable to both Gitpod Dedicated (AWS) and gitpod.io (GCP). We need to be mindful of how we roll out dedicated and ensure it is compatible with what is built here. 

## Dependencies

N/A

## Plan

TBD

## Resources

[Upgrading Gitpod in a Dedicated world - Gap analysis (internal)](https://www.notion.so/gitpod/Upgrading-Gitpod-in-a-Dedicated-world-Gap-analysis-dbb143176e3c4484b5c617e73be4206c)

## Open questions

1. What are the most time consuming parts of the deployment?
3. Given (1), how can we decompose this epic into smaller projects?

**Comment by kylos101** [comment]
@Pothulapati hey there, are you working from [this branch](https://github.com/gitpod-io/gitpod/tree/tar/work-rollout)?

**Comment by kylos101** [comment]
@Pothulapati the status for this is still breakdown? 🤔 Should it be moved to in-progress? 

Also, are there any issues that you'd like to have Team Workspace help with? If yes, could I ask you to inbox them for team workspace?

**Comment by Pothulapati** [comment]
@kylos101 Correct. Moved this into `in-progress`.

Update:

- Started building this new component in https://github.com/gitpod-io/gitpod/tree/tar/work-rollout, which performs the rollout while monitoring traffic. I'm not there yet. All the interactions with `ws-manager-bridge` work now, and I'm starting to write out the core logic, planning to get a working prototype demo by the end of the week.
- > but, wasn't sure if there are changes in other repos, too. 👋
There is also https://github.com/gitpod-io/workspace-preview/pull/76 but this is just for the developer environment.

**Comment by kylos101** [comment]
@Pothulapati I was talking with @aledbf today, and he mentioned that this should ultimately run within a lambda for Gitpod Dedicated, rather than as a job in the application cluster. He shared that lambdas can get a kubecontext, so it seems like maybe you'd be okay? 

@corneliusludmann for awareness. It's possible the new CLI @Pothulapati is working would short term run as a kubernetes job in application clusters for gitpod.io. But long term, in Gitpod Dedicated, run as a lambda.

**Comment by Pothulapati** [comment]
> and he mentioned that this should ultimately run within a lambda for Gitpod Dedicated, rather than as a job in the application cluster. He shared that lambdas can get a kubecontext, so it seems like maybe you'd be okay?

Hmm. Currently, Because the job runs in Kubernetes, I'm accessing the services directly (i.e `ws-manager-bridge` and `prometheus`). The same should be possible through `kubeconfig` too (like how `gpctl` does) with some amendments.

**Comment by kylos101** [comment]
:wave: @Pothulapati  would it be possible to add metrics to the workspace rollout job, so that we can derive rollout success? We would later, in the ops repo, setup a related SLO. 

You might be able to differentiate between failures using a reason label, so that we can have a [SLO like this one](https://github.com/gitpod-io/ops/blob/ab188bee15343819fe26c79b9891a74c351af637/slos/workspace/workspace-stop-workspace-success-ratio.yml#L21-L23), but instead of calculating stop success, it'd be rollout success. For example, a rollout failure would be going back to the old cluster, not being able to shift to the new cluster, etc. wdyt?

**Comment by Pothulapati** [comment]
> would it be possible to add metrics to the workspace rollout job, so that we can derive rollout success? We would later, in the ops repo, setup a related SLO.

Totally makes sense. I just added gauges to track the progress of the label

> You might be able to differentiate between failures using a reason label, so that we can have a [SLO like this one](https://github.com/gitpod-io/ops/blob/ab188bee15343819fe26c79b9891a74c351af637/slos/workspace/workspace-stop-workspace-success-ratio.yml#L21-L23), but instead of calculating stop success, it'd be rollout success. For example, a rollout failure would be going back to the old cluster, not being able to shift to the new cluster, etc. wdyt?

Definitely sounds interesting. I can start with adding the rollout outcome (i.e `success` or `failure`) along with the reason, and we can then build an SLO on top by aggregating metrics across jobs and tracking failures.

**Comment by kylos101** [comment]
Reopening, as this needs to be measured/validated
