### ISSUE TITLE
[PAYG] rename paid personal billing =  "Pro"

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15102]

**Comment by gtsiolis** [comment]
YES! 🎊

**Comment by svenefftinge** [comment]
Is this request about changing the header on /billing to "Pro" instead of "Personal Billing"?
How does that improve anything? The header should describe what this section is about.

Or is it to replace the "9$/Month" part with Pro? Where would the user learn what it costs to move over to a paid plan?

**Comment by jldec** [comment]
[New pricing page](https://www.gitpod.io/pricing) no longer has a column or name for this plan - closing.
