### ISSUE TITLE
port forwarding in vscode desktop opens a port but does not load

### ISSUE THREAD

**Issue by samuelstroschein** [gitpod-io/gitpod#15123]
### Bug description

A port from a Vite instance is forwarding in the web IDE but not working locally. Another port from a regular express server works as expected. 

### Steps to reproduce

1. Open the snapshot (see below) locally 
<img width="369" alt="Screenshot 2022-12-02 at 12 45 06" src="https://user-images.githubusercontent.com/35429197/205286453-80d17f35-12cb-49d4-9cf9-79200e4dc8b6.png">

2. Open port 3000 in the browser 
<img width="1443" alt="Screenshot 2022-12-02 at 12 46 18" src="https://user-images.githubusercontent.com/35429197/205286533-f1892170-50cd-48d5-9ac6-0c4c0af5c80b.png">

The port will not load. Interestingly, port 3001, the express server, is loading as expected. 

### Expected behavior

opening http://localhost:3000 opens the web app similar to the web ide (see screenshot below) 

<img width="932" alt="Screenshot 2022-12-02 at 12 44 37" src="https://user-images.githubusercontent.com/35429197/205286723-20754deb-3439-4dde-96e7-46558fb46363.png">

### Example repository

https://gitpod.io#snapshot/53bd3763-121e-4627-b7e2-f97686c9899f

### Anything else?

I tried to run the web app on port 3001 that works with the express server, no luck though.

**Comment by mustard-mh** [comment]
It's because `vite` using `localhost` as default listen host, in Gitpod we support ipv4 and ipv6, if localhost point to ipv6 address, vscode desktop maybe not able to port forward

in your example, it using ipv6

<img width="605" alt="image" src="https://user-images.githubusercontent.com/20944364/210308172-aa1a544d-a106-42fd-9990-91ab53e4c3e2.png">

<img width="782" alt="image" src="https://user-images.githubusercontent.com/20944364/210308214-56c0a6a8-e433-421d-b4af-bf48065617f6.png">

You can configure vite using `127.0.0.1` as host

```git
diff --git a/source-code/website/vite.config.ts b/source-code/website/vite.config.ts
index 2d51496..54d8e16 100644
--- a/source-code/website/vite.config.ts
+++ b/source-code/website/vite.config.ts
@@ -29,6 +29,9 @@ export default await withFsPolyfills({
                        "@env": fileURLToPath(new URL("./env.ts", import.meta.url)),
                },
        },
+    server: {
+        host: "127.0.0.1"
+    },
 });
 
 /**
```


after that change, it will using ipv4, and `vscode desktop` can port-forwared it
<img width="581" alt="image" src="https://user-images.githubusercontent.com/20944364/210308465-e961200e-9d46-4778-9649-138fe1fdac50.png">

<img width="719" alt="image" src="https://user-images.githubusercontent.com/20944364/210308492-a5c4165c-92e4-4d86-8f66-91abf152566a.png">

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/20944364/210308584-a0ba3988-a640-4761-832f-cf77b2da7f87.png">

**Comment by samuelstroschein** [comment]
@mustard-mh Thank you! I avoided the problem by removing the second server and thereby only listen to port 3000.
