### ISSUE TITLE
[installer|docs] Write a guide about the Installer config contract and how to handle breaking changes and new config version

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#15121]
In the Installer, the config acts as a contract between the installer and the user. We considered the option to introduce a new config version in case of breaking changes.

We should write an (internal) guide on what is considered as breaking change and how/when a new config version should be introduced.

The guide should at least answer the following questions:
- Who is the user of the installer (internal/external)? What expectations/requirements do they have for the stability the config?
- What is considered as breaking change? [A new mandatory config value](https://github.com/gitpod-io/gitpod/issues/15028)? A changed config value structure?
- What alternative strategies do we have to avoid breaking changes?
- When do we want to introduce a new config version?
- How do we introduce a new config version?
- How does the migration between config versions look like?

**Comment by Pothulapati** [comment]
A very valid conversation @corneliusludmann, and falls in line well with https://github.com/gitpod-io/gitpod/issues/15076



Not trying to give all the answers but focusing on `experimental` first. I see it as the following (but others can feel free to add their thoughts):

- Anything in the `v*/Config` should be considered important and has to go through a breaking change/version upgrade procedure for it to be removed/changed. (We should define this process more on how to make sure we do changes, and upgrades between config versions).
- Stuff under `experimental` shouldn't be considered in the same way. `Experimental` gives new feature authors space to play with config before they come to a conclusion, and then move into the main config interface once they are satisfied. This is why #15076 is important for us so that users are not depending on the `experimental` section for new features. (We could build some tooling here for making the move seamless for users)

**Comment by Pothulapati** [comment]
While Removing it out of `Experimental` isn't a breaking change, Mandating it in `v1` could be one. Especially when we have the deployment fail when the secret is not present for https://github.com/gitpod-io/gitpod/pull/15059. 🤔
