### ISSUE TITLE
Login SLO should identify user/system errors

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#15175]
### Bug description
When we fail to authenticate with a provider, we increment a login counter. In this case, we do not differentiate between user and system errors which results in us being paged when invalid arguments are supplied.

### Steps to reproduce
https://gitpod.slack.com/archives/C04DGADN3GX

CC @geropl for more details

**Comment by geropl** [comment]
Code reference [here](https://github.com/gitpod-io/gitpod/blob/8e40aa2243b9174c72c34f5c45c8d7ccaa29a131/components/server/src/auth/generic-auth-provider.ts#L337-L344)

**Comment by AlexTugarev** [comment]
To complete this: we need to treat the case where no `state` session/cookie is present on `*/callback` calls as user errors. Still, as @easyCZ mentioned on the call, we'd need to aggregate those kind of errors separately, in order to identify broader outages, etc..

I guess it was the lack of confidence into the login process to not exclude it in the first place. Given the noise this kind of false alarms do produce over time we need to change this.
