### ISSUE TITLE
Feedback Issue: Use Last Successful Prebuild (Incremental Workspaces)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#15310]
### Objective

Looking for comments and questions from early users of incremental workspaces.
See https://github.com/gitpod-io/gitpod/issues/12582 for more details.

**Comment by geropl** [comment]
Multiple customers thought their prebuilds are broken, because we re-execute the `init` task, and they relied on the :banana: signal from the terminal to understand whether "this workspace is based on a prebuild".
This is especially hard to explain because we did not update our docs, yet. :upside_down_face:

**Comment by gtsiolis** [comment]
Cross-posting a [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1668596264825679) (internal) in case this is relevant:

> @gtsiolis: Is it known or expected that prebuild logs[[1](https://gitpod.io/t/gitpod/website/5469260f-e6cf-4c58-9d45-d825b7fadcce)][[2](https://gitpod.io/t/gitpod/ops/df75726d-8aca-4b25-ba0a-158520a410a2)][[3](https://gitpod.io/t/gitpod/leeway/3fdbf3a4-707c-4144-aa47-1617eabba73d)][…] no longer mention how many minutes a prebuild has saved?

> <img width="436" alt="Screenshot 2022-11-16 at 12 56 06 PM" src="https://user-images.githubusercontent.com/120486/207295126-9a4ab175-80d7-49c1-9b62-41284cdeaa5c.png">
