### ISSUE TITLE
[db-sync] Consider alternatives to the `auth/workspace-cookie` redirect

### ISSUE THREAD

**Issue by andrew-farries** [gitpod-io/gitpod#15328]
See [internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1670922098012619).

**Comment by geropl** [comment]
Some prior information why we use a `fetch` to get that cookie: We want it to be `httpOnly`, so the browser (JS runtime) never has access to it.

There are two parts of code that are relevant:
- the server handler: [`/auth/workspace-cookie`](https://github.com/gitpod-io/gitpod/blob/478a75e744a642d9b764de37cfae655bc8b29dd5/components/server/src/user/user-controller.ts#L197-L293)
- the client code calling it: [ensureWorkspaceAuth](https://github.com/gitpod-io/gitpod/blob/f8fd16eea98c888687af62a2ff4578d05e4754fd/components/dashboard/src/start/StartWorkspace.tsx#L380-L394)

I personally observed that during regular workspace runtime, I got redirected to that endpoint, and it would return plain codes of `404` (and maybe `200`?) and got stuck there.
Looking at the handler code, there seem to be a couple of potential exits we might be triggering:
 - "attempted to fetch workspace cookie without instance ID" (code `400`, [0 log entries last 31 days](https://cloudlogging.app.goo.gl/SWruyeWSyPxpWfB97)) 
 - "attempted to fetch workspace cookie for non-existent workspace instance" (code `400`, [**~1550 log entries**](https://cloudlogging.app.goo.gl/bTc7u7CePb5d5nTy5))
 - "unauthorized attempted to fetch workspace cookie" (code `403`, [0 log entries](https://cloudlogging.app.goo.gl/FyLun8kTq5eXqng1A))
 - "attempted to fetch workspace cookie, but instance has no owner token" (`200` (:exclamation: :question: ), logs not visible yet because it's debug log) 

Observations:
 - the "non-existent workspace instance" seems to be a bigger issue, beyond the scope of the `slow-server` experiment. By manually looking at a couple of affected users it _feels_ as if a lot of those are coming from China/East Asia, so maybe we're this is a general problem indeed. Feels like we're looking at a race - question is where it's coming from. The affected workspaces I checked have all been started in the US cluster. But maybe their frontends regularly switch to EU due to changing latency (same DB setup we have with slow-server). This would go a way with a single DB. OR we have a different race, and it will persist
 - the client code seems to be very naive, and not matching the handler logic. On error, for instance, the client will simply redirect to the handler's URL, no matter the code. But the handler does not support, that, at all. :see_no_evil: E.g., never does redirect away... :x:

**Comment by geropl** [comment]
We don't have any insights into client metrics. But from team internal testing it seems this is solved now.
