### ISSUE TITLE
Gitpod.io workspace hangs after Restoring the layout state...

### ISSUE THREAD

**Issue by studentIvan** [gitpod-io/gitpod#1535]
### Describe the bug
When I open my workspace with the running state. I see only blue jumping cube, for a long time, and nothing more. No any status or the message.

<img src="https://habrastorage.org/webt/bw/m7/tb/bwm7tbfqyofak1pytmqfjvbkxom.png" />

### Additional information
First time seems it hangs after this log line:
```
root INFO >>> Restoring the layout state...
```

And after that I see 5 or more messages: (and seems they coming infinity)

```
root INFO Window became visible, fetching
```

### Example repository
Repository is private

Full log from devtools:
https://gist.github.com/studentIvan/db97a4a98a4f8d0b990a03bfe605b15c

**Comment by Kreyren** [comment]
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://dodmmooeoklaejobgleioelladacbeki/dist/gitpodify.bundle.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

Could you try disabling the gitpod extension to see if it has any effect on the issue?

```
/#/workspace/ridestore-pwa:1 A cookie associated with a cross-site resource at http://github.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

cc @jankeromnes this seems like gitpod extension bug waiting to hapend to me

```
fetch-wrapper.js:13 GET https://api.github.com/repos/Ridestore/ridestore-pwa/community/profile 404 (Not Found)
```

Possible GitHub shortage? (those are pretty common these days)

@studentIvan Can you check if the issue still present to exclude this being caused by GitHub?

Alternatively i guess that this could also be caused by the permission assigned to gitpod assuming this being a private repository -> Can you verify that relevant repository has gitpod permissions? See https://gitpod.io/access-control/

**Comment by studentIvan** [comment]
@Kreyren access control is ok. Disabling the gitpod chrome extension didn't solve the problem. But now I see the open terminal message. Other things the same - the workspace loading hangs.

<img src="https://habrastorage.org/webt/xg/bd/u7/xgbdu7pfk0lkx35maim0ydmvkgg.png" />

**Comment by Kreyren** [comment]
cc @jankeromnes, out of ideas
