### ISSUE TITLE
Research: NoVNC

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1537]
This issue is created as an investigation in possible solutions to these issues and exploring alternatives if needed

DISCLAIMER: I am doing this research on my own where TypeFox wants to focus on more important issues atm, i am providing this for later brainstorm or if depending on the solution to implement the fix myself.

Any relevant info is welcomed.

---

As discussed in REDACTED current NoVNC has issues with:
1. scaling - The preview images are too small in the browser
![image](https://user-images.githubusercontent.com/11302521/82670320-35562e80-9c3d-11ea-9613-b0090f423566.png)

2. The latency is not acceptable - Takes around 3 seconds to move the window on it (this could also be related to my usage of tor and gitpod's cluster location)

**Comment by jankeromnes** [comment]
Thanks @Kreyren for filing this issue!

> 1. scaling - The preview images are too small in the browser

This is a compromise. Previously, the VNC preview was at "normal scale", but overflowed outside the preview pane. This caused a lot of confusion, because sometimes graphical windows open in the "center" of the virtual screen, i.e. they're outside the visible portion of the VNC preview, so users would wrongly conclude that either their app or Gitpod didn't work.

Now you can see the entire virtual screen, but it's scaled down. To make it bigger, you can still open the preview in a new fullscreen tab.

> 2. The latency is not acceptable - Takes around 3 seconds to move the window on it (this could also be related to my usage of tor and gitpod's cluster location)

The latency feels quite fast on my end.

Since the input/reaction feedback loop contains a full network round-trip, it's important for the user to be "as close as possible" to the workspace server (this means geographically, as a trip across an ocean already degrades the experience, but also means the lowest possible amount of intermediate buffers adding latency).

I'd say the slowness you experience is most likely due to Tor (where you trade latency for privacy). By default, Gitpod already selects the best region for you based on latency, so if you're in Europe, it should give you a direct connection to the Brussels datacenter, which would give you a very short latency.

**Comment by jankeromnes** [comment]
Also, note: you can disable noVNC's scaling by clicking on the left VNC toolbar, then the Gear/Settings icon.

**Comment by Kreyren** [comment]
@jankeromnes Seems that my gitpod's input lag is affected by the usage of tor that has in general 50~200ms latency, but without tor it also seems slower then acceptable.. 

In theory deploying a gitpod on darkweb should lower the latency assuming that i could connect directly on gitpod with optimized routing that doesn't sacrifice too much of a privacy.

For the non-tor seems that TigerVNC is more efficient on latency.

Still investigating..
