### ISSUE TITLE
Track client IP in for analytics

### ISSUE THREAD

**Issue by jakobhero** [gitpod-io/gitpod#15600]
### Bug description

We are depending on the (masked) client IP for the creation of a daily changing fingerprint in order to identify users without cookies and map website activity to web app activity, see [this PR](https://github.com/gitpod-io/gitpod/pull/14978#issuecomment-1362748733). The obtained IPs tracked here belong to some Google data center, not the client and a first attempt to fix did not address this issue, see [this PR](https://github.com/gitpod-io/gitpod/pull/15356).

### Steps to reproduce

Cannot be reproduced in developer environment as the bug arises from the architecture in production. There are (at least) two ways to get some context on this issue

- check the IPs in production is [these logs](https://github.com/gitpod-io/gitpod/pull/15356#pullrequestreview-1219305190)
- Query identify calls (they use the client's masked IP), e.g. of yourself, in BigQuery with the query below

Also, you can find more analysis on the issue in this [data task](https://www.notion.so/gitpod/Complete-Cookieless-Tracking-69c9ca21f7444b528a8f96479b66e09a#58faf5c4175c419a8d674d1729cacef9).

Query for identify calls:
```
select
    user_id,
    timestamp,
    context_ip
from production_trusted.identifies
where user_id = '<your Gitpod user ID>' --insert your own user_id here
and context_ip is not null
order by timestamp desc
limit 10
```

### Expected behavior

Instead of IPs that seem to belong to some proxy, we are expecting to obtain the true client IP in `express-util.ts`'s `clientIp` function.

**Comment by andrew-farries** [comment]
Some thoughts on this:

* Does the GCP loadbalancer set the `Forwarded` header rather than/in addition to `X-Forwarded-By` header? GCP docs [suggest not](https://cloud.google.com/load-balancing/docs/https), but might be worth seeing if `Forwarded` is present in the request.
* Are the IP addresses in the `X-Forwarded-By` header out-of-order? The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) suggest the client IP should be the first value in the comma separated list of IPs, but maybe they arrive out of order for some reason.
* Does `proxy` mutate the header in some way before `server` sees it?

**Comment by jakobhero** [comment]
hi @gitpod-io/engineering-webapp!👋 i got around to assessing the effectiveness of the fix and unfortunately, the absence of IP addresses in the tracking calls since `2023-01-01` suggest that he fix led to IPs no longer being available at all - for more context, see [here](https://www.notion.so/gitpod/Complete-Cookieless-Tracking-69c9ca21f7444b528a8f96479b66e09a#e38b8b876473457db704f0d864c77081). could you please have another look?🙏🏼

**Comment by geropl** [comment]
Fixed by setting `X-Real-IP` in the LB
