### ISSUE TITLE
Remove all licence restrictions

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#15640]
Remove all restrictions on numbers of users in both Gitpod and Replicated licences, the default licence and the fallback licence

**Comment by DJIronic** [comment]
Hello,
Me being an idiot, I run the selfhosted edition until ve find a new solution, but I fight with the licence issue, I have the latest version gitpod is able to update to. Should I somehow update it manually using this repo, or is this something the Gitpod console will update to automatically?

The issue is I cannot exceed the number of ten even with community license, but this should be an issue at all as the licensing system should be disabled.

Thank you very much for your help.

**Comment by mrsimonemms** [comment]
@DJIronic Gitpod self-hosted hasn't been [officially supported since January](https://www.gitpod.io/blog/introducing-gitpod-dedicated), the last release being [2022.11.3](https://github.com/gitpod-io/gitpod/releases/tag/2022.11.3). I don't expect you'll get an official response from anyone inside Gitpod - sorry about that.

From memory, the licence server should be disabled but I can't remember if it made it into the 2022.11.3 release. The best thing to do would be to read the release notes from the last few releases (assuming they're accurate that is).

**Comment by AToska21** [comment]
> [@DJIronic](https://github.com/DJIronic?rgh-link-date=2023-11-16T20%3A47%3A27.000Z) Gitpod self-hosted hasn't been [officially supported since January](https://www.gitpod.io/blog/introducing-gitpod-dedicated), the last release being [2022.11.3](https://github.com/gitpod-io/gitpod/releases/tag/2022.11.3). I don't expect you'll get an official response from anyone inside Gitpod - sorry about that.
> 
> From memory, the licence server should be disabled but I can't remember if it made it into the 2022.11.3 release. The best thing to do would be to read the release notes from the last few releases (assuming they're accurate that is).

They haven't added PR #15583 to the latest release. I can't figure out how to do it myself either.
