### ISSUE TITLE
Stop prebuilds from running when a project is added on a new team with no paid plans or available credits

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15798]
### Bug description

Prebuilds for some projects on teams with no active billing or available credits continue to run against the user who added the project. One case involves a GitLab repository where the individual user added the repository as a project, using a webhook, the default method for enabling prebuilds for GitLab repositories.

See [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1673956943214129) (internal). Cc @jldec @svenefftinge 

### Steps to reproduce

Haven't tested this, but this could be probably reproduced by adding a GitLab repository as a project on a new team with no active paid plan, which enables prebuilds for that project.

**Comment by jldec** [comment]
The current behavior was by design, making prebuilds usable by members of the community, even when those prebuilds are managed through a project in a team with no payment configured.

Once attribution is limited to teams only (see #15665) and we have a mechanism to keep supporting OSS projects, this behavior will be revisited.

**Comment by geropl** [comment]
Should be covered by: https://github.com/gitpod-io/gitpod/pull/16347

**Comment by gtsiolis** [comment]
Thanks for coming back to this, @geropl! 🏀
