### ISSUE TITLE
Investigate `workspace pod did not transition to running state`

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#15859]
### Bug description

Investigate the warning error `workspace pod did not transition to running state` coming from https://github.com/gitpod-io/gitpod/blob/1559220778cad07ff987761e3bc4acc816fdf8f5/components/ws-manager/pkg/manager/manager.go#L383
https://cloudlogging.app.goo.gl/tPH864sGqYi56ZD47

 In other words, there is a workspace that has not reached RUNNING even after 7 minutes have elapsed.

### Steps to reproduce

I'm not sure 🤦

**Comment by kylos101** [comment]
Looks like it started on/around Dec 20th:
![image](https://user-images.githubusercontent.com/1272076/213456474-acb24d93-9b91-4d9e-a07b-edb8f2b6be6c.png)

**Comment by utam0k** [comment]
> Looks like it started on/around Dec 20th: ![image](https://user-images.githubusercontent.com/1272076/213456474-acb24d93-9b91-4d9e-a07b-edb8f2b6be6c.png)

It may be past the log stored period.

**Comment by utam0k** [comment]
I added the trace to verify whether or not a pod wasn't schedulable. I think there isn't enough information to tackle this issue at this stage. So let's check it after `gen84` deploy
https://github.com/gitpod-io/gitpod/pull/15861

**Comment by kylos101** [comment]
Blocked till we confirm results of https://github.com/gitpod-io/gitpod/pull/15861

**Comment by kylos101** [comment]
This issue is [present with gen85](https://cloudlogging.app.goo.gl/Dmtfh4Ev3ALLXU9d8) (logs). 

Here is the timeline for startWorkspace calls that I see for this one workspaceId given the below traces:
1. 12:59:36am, a606af54-9d90-4f7e-be8f-99caf3e1d995, failed due to a 7m timeout
2. 1:06:37am, a606af54-9d90-4f7e-be8f-99caf3e1d995, failed because the workspace already exists from the first request
3. 1:06:39am, a606af54-9d90-4f7e-be8f-99caf3e1d995, achieves running till 1:30:28am, when it is stopped

There are [34 traces](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/search?end=1675794594588000&limit=1500&lookback=24h&maxDuration&minDuration&service=ws-manager&start=1675708194588000&tags=%7B%22instanceId%22%3A%22a606af54-9d90-4f7e-be8f-99caf3e1d995%22%7D), spanning for about 31 minutes (12:59am - 1:30am).

Next steps to socialize in refinement:
1. To recreate the 7m timeout, we may be able to do in a preview environment by simply cordoning the node.
2. It seems like the 2nd startWorkspace error should not have happened, assuming the state could have been reset before trying after the 7m timeout
3. Assuming we can make a change, to avoid the 2nd failure for this scenario, when we recreate this, the total start counter should increment twice, success once, and failure once.

**Comment by kylos101** [comment]
Move back to the inbox for now, reconsider once we're live with mk2
