### ISSUE TITLE
Support kubernetes in development environment

### ISSUE THREAD

**Issue by mehdihadeli** [gitpod-io/gitpod#1585]
Hi,
Does gitpod support Kubernetes in its development environment for hosting apps on Kubernetes nodes?

**Comment by Kreyren** [comment]
Like developing kubernetes environment and apps on gitpod?

I don't know afaik if it doesn't need `/dev/kvm` and root account then i don't see anything that would prevent that?

**Comment by jankeromnes** [comment]
Hi @mehdihadeli, Gitpod itself runs on Kubernetes, and can be deployed in a Kubernetes cluster alongside your Kubernetes apps in order to make your development flow truly cloud-native -- i.e. you can then launch a dev environment on any branch or Pull Request in seconds, and your workspace is directly connected to a dedicated Kubernetes staging deployment, so that you can start coding / debugging / testing / tweaking a live deployment almost immediately from any context (as opposed to tediously re-configuring a local clone all the time).

For example, we use Gitpod to develop Gitpod itself (a Kubernetes app), and our internal on-demand dev environments have direct Kubernetes access when launched. See it in action here: 
https://www.youtube.com/watch?v=dFMpXUsJcGM

**Comment by jankeromnes** [comment]
For deploying Gitpod in your own Kubernetes cluster, see also: https://github.com/gitpod-io/self-hosted/

**Comment by mehdihadeli** [comment]
@jankeromnes Hi, I don't want deploy Kubernetes on my own machine. so can I use Kubernetes commands (kubectl) on gitpod environment to deploy my repo app on gitpod Kubernetes cluster on the cloud?

**Comment by sr229** [comment]
From what I understood, looks like he wants to try out developing for Kubernetes using `kubectl` (please @mehdihadeli  correct me if I'm wrong).

We could add the following but I think this is more of the job of our friends from [OpenShift.io](https://openshift.io).

**Comment by mehdihadeli** [comment]
ok thanks

**Comment by jankeromnes** [comment]
Hi @mehdihadeli! We use `kubectl` in Gitpod every day while developing Gitpod in Gitpod. 🙂 (Because Gitpod runs on Kubernetes.)

Every internal Pull Request gets its own dedicated Kubernetes staging deployment, so that you can see your modified Gitpod running live, and every PR also gets a prebuilt Gitpod dev environment that is pre-connected to the staging deployment, so that in one click, you can review a PR, see & test the deployment running live, use `kubectl` to inspect the different microservices (and maybe tweak their config live or try shutting one pod to see what happens).

This is a workflow that I think would be super valuable for many Gitpod users, so we're working on a demo where hopefully you'll also be able to use a pre-connected `kubectl` in a Gitpod workspace. More news on that soon. 🙂

**Comment by mehdihadeli** [comment]
@jankeromnes thanks for your explanation, yes it's better creating a sample or a document for using this feature for easy to use

**Comment by jankeromnes** [comment]
Agreed. We're on it. :)

**Comment by DanielHabenicht** [comment]
@jankeromnes is there a guide or article already published?

**Comment by carlskii** [comment]
+1 for this

**Comment by shepherd1530** [comment]
Is something like Okteto possible with GitPod?

**Comment by axonasif** [comment]
@shepherd1530 see:
- https://www.youtube.com/watch?v=dgtuEgmsLoQ
- https://www.okteto.com/blog/modern-development-environments-for-cloud-native-applications-using-gitpod-and-okteto/

**Comment by loujaybee** [comment]
Hey folks, just coming back to this for others who are googling, we recently published a new docs page: 

https://www.gitpod.io/docs/integrations/kubernetes

This page covers common use cases and ways to develop Kubernetes applications in Gitpod: 

* [Using Docker in Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#1-using-docker-in-gitpod)
* [Using Docker Compose in Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#2-using-docker-compose-in-gitpod)
* [Using a Kubernetes Network Proxy in Gitpod (e.g. Telepresence)](https://www.gitpod.io/docs/integrations/kubernetes#3-using-a-kubernetes-network-proxy-in-gitpod-eg-telepresence)
* [Running Kubernetes clusters in Gitpod (e.g. MiniKube)](https://www.gitpod.io/docs/integrations/kubernetes#4-running-kubernetes-clusters-in-gitpodeg-minikube)
* [Connecting to a remote Kubernetes cluster inside Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#5-connecting-to-a-remote-kubernetes-cluster-inside-gitpod)

Please do check it out, and let us know if you have any questions 🙏
