### ISSUE TITLE
How to open browser when local server is running on https?

### ISSUE THREAD

**Issue by subhendukundu** [gitpod-io/gitpod#1594]
I am running a project which has self-signed certified with localhost and running on 8080.
On starting the server it has an open port as 8080. But when I open preview or open browser it says port 8080 didn't respond.

How do we fix it?

**Comment by th3c0d3br34ker** [comment]
Hey @subhendukundu , I am not a official representative of gitpod, but would surely like to help. 😄 
Since, exposing a port should allow you to see your content. There might be a small configuration problem in your repository. Kindly share a link to your repository so that I might be able to help.

**Comment by subhendukundu** [comment]
Thank you so much for replying back, I was losing hope on this one.
https://github.com/gunschu/jitsi_meet

**Comment by svenefftinge** [comment]
Is this still an issue? Could you please provide an example project or snapshot so we can reproduce the problem?

**Comment by subhendukundu** [comment]
Yes, it's still an issue.
For example try,
https://gitpod.io/#https://github.com/jitsi/jitsi-meet
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web for running the server.

**Comment by naramore** [comment]
I am having a similar problem on my project:  https://github.com/naramore/ex_pathom

I'm exposing 2 ports, 4000 (http) & 4001 (https), and when attempting to use the preview or browser option for 4001, nothing is displayed and the error my server is displaying is:

`[info] TLS :server: In state :hello at tls_record.erl:477 generated SERVER ALERT: Fatal - Unexpected Message`

Which is the same error I've gotten when attempting to access the server via HTTP (instead of HTTPS) on my local machine.

Here is a snapshot of my gitpod if that helps:  https://gitpod.io/#snapshot/452a26dc-bfce-461f-aaa3-56efe460ca06

All you should have to do is: `mix setup && iex -S mix phx.server`, and open port 4001 (refresh it if necessary) and you'll see the TLS :server error I posted above.

**Comment by subhendukundu** [comment]
This is still an issue.

**Comment by GiooRomanadze** [comment]
This is still an issue.

**Comment by krise86** [comment]
same here, reverse proxy terminates on tls and fwd to backend with http always. Is there any way to tell gitpod to use tls on backend

**Comment by twbluenaxela** [comment]
This is still an issue.

**Comment by axonasif** [comment]
Here are two workarounds for now:
You can:
- Open your workspace on Desktop VSCODE, so all ports are forwarded to your PC `localhost:port`
    See https://www.gitpod.io/docs/ides-and-editors/vscode
- Or you can use `image: gitpod/workspace-full-vnc` on your `.gitpod.yml` to use a chrome browser from inside Gitpod through noVNC, so that you can access your app via localhost.
