### ISSUE TITLE
push failure

### ISSUE THREAD

**Issue by KittiKovacs** [gitpod-io/gitpod#1601]
Hi!

I am getting this error message when I am using the git push command. It is a repository I created and I am the only contributor. I don't understand why I am not able to use this repository. Can you help?  Kitti

remote: Permission to KittiKovacs/Milestone-Project-1-User-Centric-Front-End-Development.git denied to KittiKovacs.
fatal: unable to access 'https://github.com/KittiKovacs/Milestone-Project-1-User-Centric-Front-End-Development.git/': The requested URL returned error: 403

**Comment by jankeromnes** [comment]
Hi @KittiKovacs!

This sounds like Gitpod isn't allowed to push to your repository. Normally, this error should show a pop-up in the IDE that suggests how to fix the problem, but in case you don't get this pop-up:

The fix is to head over to https://gitpod.io/access-control/ and to make sure that the GitHub checkbox `write public repos` is checked (if not, please check it and click on Update). This should allow you to push from Gitpod.

Notes:
- To push to a private repository, you'll also need to grant `read/write private repos`
- Sometimes if you have a `.github/workflows/` directory in your repository, GitHub will refuse pushes unless you also grant `update workflows`

**Comment by KittiKovacs** [comment]
Thank you I'll try this!
It's strange bacuse this is not my first repository and I've never met this problem before.

**Comment by jankeromnes** [comment]
> Thank you I'll try this!

Hope it works! And you're very welcome.

> It's strange bacuse this is not my first repository and I've never met this problem before.

Ah, that is strange indeed. Now I'm thinking that this may be a temporary problem with GitHub (it seems that lately GitHub has been occasionally/randomly responding `403 Forbidden` to some requests, but trying the same request again later worked fine).

So maybe it's just a matter of trying again a few times? (If this becomes a widespread/frequent problem, we may have to implement some sort of automatic retry mechanism in Gitpod.)

**Comment by Kreyren** [comment]
FWIW i usually have this when gitpod is not allowed in the target organization aldo it should output a notification about this O.o
