### ISSUE TITLE
Use System V init scripts for workspace-image specific services

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#16092]
## Is your feature request related to a problem? Please describe

Currently we rely on the execution of `bash` shell's run commands (i.e. `bashrc`) to manage the execution of services such as:
- VNC
- Databases

However, it usually makes the process more complicated, with additional reliance on `bash`.

## Describe the behaviour you'd like

Use System V init scripts instead. Have them executed on a Gitpod workspace startup.

## Additional context

- https://gitpod.slack.com/archives/C01RC164G48/p1675073281696329 (internal)
- https://github.com/gitpod-io/gitpod/issues/3966#issuecomment-1408417856

**Comment by akosyakov** [comment]
To be clear it is not about initd, but ability to contribute startup scripts on workspace start collected form image itself, ie via labors, which can call out to initd particularly in our images for vnc and postgres.

**Comment by akosyakov** [comment]
> However, it usually makes the process more complicated, with additional reliance on bash

To be clear it is bad because it triggers on each bash sourcing and leads to unexpected behaviour as well as race conditions. Using init.d service allows to have clean startup and shutdown hooks bound to the workspace lifecycle. As well as give a user explicit commands like `server postgres start|stop|restart` to control the start of a service.
