### ISSUE TITLE
https://f66a7ce2-7a2d-467a-a76a-930196bee544.ws-eu01.gitpod.io

### ISSUE THREAD

**Issue by schmatthy** [gitpod-io/gitpod#1644]

**Comment by jankeromnes** [comment]
Hi @schmatthy 

This is not an actionable error report, so we can't do anything here. Please provide more information, like for example:
- Did an error happen?
- What was the error message?
- What did you expect to happen instead?
- Screenshots of the problem(s)
- Any steps we can take to reproduce the problem ourselves (e.g. "open this project in Gitpod, then click on X, notice that Y happens instead of Z")

Thanks!
