### ISSUE TITLE
GCP DB Alert at ~3am CET

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#16460]
GCP has fired an alert at around 3am CET in the past 2 das:
* https://gitpod.slack.com/archives/C01TNS8EVQT/p1676599719818159
* https://gitpod.slack.com/archives/C01TNS8EVQT/p1676513318699029

Investigate the cause and/or adjust the threshold.

**Comment by geropl** [comment]
It's unclear where the regularity comes from. We're lagging traces atm to find out, which is tackled in https://github.com/gitpod-io/ops/issues/8409.

The new DB insights suggests it's likely caused by old accounting code. https://github.com/gitpod-io/gitpod/pull/16508 is an attempt to fix that.
If that does not help, we should limit the upper bound for calculating those AccountStatements ([draft PR](https://github.com/gitpod-io/gitpod/pull/16509)).

**Comment by geropl** [comment]
We ruled out other causes, next step is to do a minimal query optimization.

**Comment by geropl** [comment]
https://github.com/gitpod-io/gitpod/pull/16564 and https://github.com/gitpod-io/gitpod/pull/16562 did the trick it seems. :heavy_check_mark:
