### ISSUE TITLE
Question: master vs. main default branch name in .gitpod.yml config

### ISSUE THREAD

**Issue by jywarren** [gitpod-io/gitpod#1646]
I wasn't sure if the docs in https://www.gitpod.io/docs/prebuilds/#configure-prebuilds meant that the setting `master` should remain even if our default branch is `main` or if we should change it. Maybe either a slight tweak to the docs and/or an alias of the config name to `default` would help? 

I wonder if this was the wrong thing to do:

https://github.com/publiclab/image-sequencer/pull/1680

Thank you, love GitPod!!! ❤️

**Comment by nisarhassan12** [comment]
cc @jankeromnes

**Comment by jankeromnes** [comment]
Hi @jywarren!

Good point, thanks for catching this. Gitpod should definitely work with default branches that are not called `master`, but it seems that our prebuild configuration option for enabling the default branch is itself still called `master` (regardless of the actual name of the repository's default branch). This is incorrect and we should fix it.

## Current situation

It seems that your `.gitpod.yml` configuration is broken, because there is no such prebuild option called `github.prebuilds.main` in Gitpod -- the feature for enabling the default branch is still called `github.prebuilds.master` (even if your default branch is called `main`).

I would suggest fixing your `.gitpod.yml` prebuild configuration, either by:
- renaming the `main` option back to `master`, or
- removing this option entirely (prebuilds are already enabled by default for the default branch, so there is no need to specify a value)

I'll send your a PR for convenience.

## Near term

We should rename Gitpod's `github.prebuilds.master` option to something better like `github.prebuilds.default` or `github.prebuilds.defaultBranch` (and maybe `github.prebuilds.branches` to `github.prebuilds.allBranches` to lift any ambiguity).

I'll keep this issue open as an enhancement request. Thanks again!

**Comment by jywarren** [comment]
Oh awesome, thanks so much, esp. for the quick response!

**Comment by mikenikles** [comment]
Re-opening to see if we can make the change suggested by Jan.
