### ISSUE TITLE
Gitpod Image Build Logs

### ISSUE THREAD

**Issue by ShaunSHamilton** [gitpod-io/gitpod#16485]
## Is your feature request related to a problem? Please describe

After opening a Gitpod workspace, it would be useful to be able to view the Docker/build logs for the container.

## Describe the behaviour you'd like

Currently, Gitpod comes with a `Gitpod: Export all logs` command. However, this only exports the logs from the various VSCode outputs (I do not know anything about the other editor options).

I would like the container logs to be added to the folder of logs generated. Similar to what you can do when building an image/container locally on VSCode.

## Describe alternatives you've considered

On the Discord, someone mentioned the `gp rebuild` command as a workaround to see the logs as the image builds. However, this is just a workaround.

**Comment by loujaybee** [comment]
Hey @ShaunSHamilton — could you explain a little more about what it is that you're looking for with the logs? Could you explain a little about what the issue is that you're trying to resolve that you need the logs for? 

`gp rebuild` is in beta and we're actively improving it day-by-day right now ([docs](https://www.gitpod.io/docs/references/gitpod-cli#rebuild)), I am also [giving a demo on it tomorrow](https://twitter.com/gitpod/status/1627703902765187078?s=20) in the community, so I wouldn't really call it a "workaround". The command emulates almost entirely a workspace build (we are working towards as close to 100% parity as reasonable), so I see no good reason not to trust the logs from that command. 

Maybe we can incorporate your use case.

**Comment by ShaunSHamilton** [comment]
> Could you explain a little more about what it is that you're looking for with the logs? Could you explain a little about what the issue is that you're trying to resolve that you need the logs for?

Honestly, I have forgotten why I needed (wanted) the logs. It was most likely to do with debugging the `init` during build.

> Is there something insufficient about the output from that command currently for your use case?

No. The reason I said "workaround" is that I have to rebuild to get the logs. I just thought that odd, because I assume there are already build logs somewhere out there from when the container was first created?

---

Are the logs that are shown sometimes during the pre-build phase stored anywhere on the file system?

**Comment by loujaybee** [comment]
> Honestly, I have forgotten why I needed (wanted) the logs. It was most likely to do with debugging the init during build.

Gotcha. `gp rebuild` has some flags such as `--prebuild` and `--as="prebuild"` which allow you to emulate different prebuild scenarios, which should make `init` task debugging simpler. 

> No. The reason I said "workaround" is that I have to rebuild to get the logs. I just thought that odd, because I assume there are already build logs somewhere out there from when the container was first created?

We don't put those build logs into the built workspace to my understanding. I can see the appeal, but also do think that `gp rebuild` may well become the default way that we encourage Gitpod users to configure, validate and test their configurations. However, if there are situations that doesn't make sense, exposing the build logs could also be useful. I'm going to refer this one to @gitpod-io/engineering-workspace as I think they'll be best placed on the feasibility on accessing and putting those logs in the workspace. 

Thanks for the additional info, @ShaunSHamilton !

**Comment by axonasif** [comment]
For context, original discussion on Discord:
- https://discord.com/channels/816244985187008514/1075032474574409790
