### ISSUE TITLE
request for extension compatibility

### ISSUE THREAD

**Issue by rholland** [gitpod-io/gitpod#1649]
In order of priority it would be great to get the following functionality:

1. Interactive python window that respects the cell #%% token and lens's, and loads the jupyter kernel
2. "Inline Bookmarks" extension
3. "Toggle Panel" extension

I loaded the .vsix for 2 and 3 but they generally fail silently (occasional error message).

Thanks for the great work.

**Comment by jankeromnes** [comment]
Hi @rholland, thanks for the feedback!

> 1. Interactive python window that respects the cell #%% token and lens's, and loads the jupyter kernel

Sorry, I'm not very familiar with Jupyter notebooks. But is this something that could be run as a web service using an existing tool? If so, please feel free to install the tool in Gitpod, and to use the automatic web preview.

Otherwise, I'll defer to people who know more about Jupyter notebooks.

> 2. "Inline Bookmarks" extension
> 3. "Toggle Panel" extension
> 
> I loaded the .vsix for 2 and 3 but they generally fail silently (occasional error message).

Ah, this sounds like extension compatibility bugs in Theia, Gitpod's IDE. For each of them, could you please:

- File an issue under https://github.com/eclipse-theia/theia/issues
- Provide the .vsix file you've used, or the extension's version
- Add full error messages that you're seeing, either in IDE notifications, or more likely in your browser's devtools console

Thanks again!

**Comment by akosyakov** [comment]
An issue with Jupyter notebook and worked on. There is a PR in Theia which brings its support: https://github.com/eclipse-theia/theia/pull/7908

**Comment by rholland** [comment]
ok - thanks.  I will file issues there.
