### ISSUE TITLE
Problem with automatic tasks on .gitpod.yml

### ISSUE THREAD

**Issue by rodrorivero** [gitpod-io/gitpod#16572]
### Bug description

Tasks are only executed the first time the workspace is rendered by the first time. no log or error message is shown

### Steps to reproduce

1 - launch wotkspace and close it. Berify the tasks execute correctly.
2 - launchthe workspace again, tasks are not executed anymore and no log is shown.

### Workspace affected

rodrorivero-awsbootcamp-8tcok2iab13

### Expected behavior

tasks should run when workspace is opened.

### Example repository

https://github.com/rodrorivero/aws-bootcamp-cruddur-2023

### Anything else?

Tried to troubleshoot changing .gitpod.yml code with several combinations but the issue persists.

**Comment by axonasif** [comment]
Hi @rodrorivero 👋 

That is the expected behavior.

As it goes by its name, `init` will only run once on the initialization of a workspace.

I can also see that you're using `init` tasks for installing system packages/tools[^1], but `init` is not well-suited for that. You can check the following page to learn more about how tasks work:
- https://www.gitpod.io/docs/configure/workspaces/tasks

My recommendation would be to use a custom dockerfile for this purpose.

In an attempt to help you out: https://github.com/rodrorivero/aws-bootcamp-cruddur-2023/pull/1

[^1]: https://github.com/rodrorivero/aws-bootcamp-cruddur-2023/blob/f0e7481615684c24dca9b455010d011f1d8a59ba/.gitpod.yml#L7
