### ISSUE TITLE
Wrong highlighting of shell/bash variables using string manipulation

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1660]
Is it not expected for theia to highlight the 'id' part of '${ID:-id}' as variable

![image](https://user-images.githubusercontent.com/11302521/87299210-e4abd500-c50b-11ea-930a-1c8a803774f1.png)

```console
kreyren@leonid:~$ echo $ID

kreyren@leonid:~$ ID=id
kreyren@leonid:~$ echo ${ID:-id}
id
kreyren@leonid:~$ unset ID
kreyren@leonid:~$ echo ${ID:-id}
id
```

**Comment by corneliusludmann** [comment]
Thanks for reporting.

However, syntax highlighting for shell scripts is provided by the built-in VSCode extension. You'll find the source code in the [VSCode repo](https://github.com/microsoft/vscode/tree/master/extensions/shellscript). Please create an issue there.

The extension is available in the [Open VSX Registry](https://open-vsx.org/extension/vscode/shellscript).

I'll close this issue since we cannot fix this in Gitpod. Feel free to re-open this issue if necessary.
