### ISSUE TITLE
Two different errors with very similar PRs containing simple static sites

### ISSUE THREAD

**Issue by Cervator** [gitpod-io/gitpod#1672]
### Describe the bug

We set up with some GitPod config a little while ago. We had it working for both https://github.com/MovingBlocks/movingblocks.github.com and https://github.com/MovingBlocks/Terasology although in the latter case 1 FPS might be a generous description of "working" although that's from running a video game in a cloud workspace, not a problem with what GitPod wraps around our stuff 😅 

However, now https://github.com/MovingBlocks/movingblocks.github.com/pull/150 got one error immediately:

```
We are having trouble parsing your context
Error: Cannot read property 'repository' of null
```

I realize that PR is closed and the associated branch has been deleted, which I would guess is probably the cause for the error. The same button on https://github.com/MovingBlocks/movingblocks.github.com seemingly works fine. But in that case shouldn't the UI produce a graceful error message to the user / prevent starting a workspace at all? The content is still there, although it looks like it was a squash merge.

Additionally https://github.com/DestinationSol/DestinationSol.github.io/pull/28 _does_ get past that error, but then fails while doing some Docker stuff. Similar simple static site, but the PR itself notes it did not actually work back when we tried it. Unsure if that was the same error as we're facing now:

```
You don't have write permissions for the /var/lib/gems/2.7.0 directory
```

(Manually typed, can't seem to copy paste from the error page)

The config files in that repo look identical to the ones in the movingblocks.github.com repo, that seemingly works (outside of that listed PR)

### Steps to reproduce

1. Go to either URL - https://github.com/MovingBlocks/movingblocks.github.com/pull/150 or https://github.com/DestinationSol/DestinationSol.github.io/pull/28
1. Use the GitPod button added via browser addon (or just plug the URL into the GitPod site - you end up in the same place as far as i know)
1. Wait a bit and see either error appear

### Expected behavior

Expected the GitPod build would execute, work, and serve a workspace with the static site working, as it has in the past. Or at least serve more user-actionable errors :-)

### Additional information

Inlined logs above

### Example repository

Noted above

**Comment by AlexTugarev** [comment]
Hi @Cervator! 

> I realize that PR is closed and the associated branch has been deleted, which I would guess is probably the cause for the error.

You are absolutely right. Gitpod couldn't provide you with a ready-to-use workspace, because the remote branch from the PR ☝️ was already deleted. 

To continue working on the changes from that PR, please start from the target branch.

> But in that case shouldn't the UI produce a graceful error message to the user / prevent starting a workspace at all?

There is no doubt about it, no one can tell that from the error message. We definitely need to improve the handling in cases like this.

Creating a workspace for the target branch could be another option.

**Comment by AlexTugarev** [comment]
@Cervator, I left a comment on the Docker image PR:  https://github.com/DestinationSol/DestinationSol.github.io/pull/28#discussion_r460906703

**Comment by jankeromnes** [comment]
Thanks again for this report!

> Error: Cannot read property 'repository' of null

This happens when the underlying branch or fork has been deleted. Now tracked here: https://github.com/gitpod-io/gitpod/issues/3659

> You don't have write permissions for the /var/lib/gems/2.7.0 directory

This seems unrelated, and is probably a Dockerfile error. Seems to be addressed by https://github.com/DestinationSol/DestinationSol.github.io/pull/28#discussion_r460906703
