### ISSUE TITLE
Gitpod we are having trouble parsing your context, Error: unauthorized

### ISSUE THREAD

**Issue by Ridley-nelson17** [gitpod-io/gitpod#1675]
### Describe the bug
Everytime I opened gitpod.io/#https://github.com/Ridley-nelson17/Python-Application-Creator it would return ”we are having trouble parsing your context error: unauthorized”

### Expected behavior
normally, what should happen is it would open the repository in a gitpod editor

### Additional information
my github repository is https://github.com/Ridley-nelson17/Python-Application-Creator

### Example repository
https://github.com/Ridley-nelson17/Python-Application-Creator

**Comment by AlexTugarev** [comment]
Hi @Ridley-nelson17, thanks for reporting. I'm happy to look into this. 

`Ridley-nelson17/Python-Application-Creator` is a public repo, I wonder why authorization should be a thing. Are you sure you experienced it with this repo, maybe you've tried with a private repo.

BTW, there is an issue with the Dockerfile, please use `DEBIAN_FRONTEND=noninteractive apt-get install ...` in https://github.com/Ridley-nelson17/Python-Application-Creator/blob/master/.theia/.gitpod.Dockerfile#L3. I just tried, but the image build hangs due to readline invocation.

**Comment by AlexTugarev** [comment]
In case of a private repo, please make sure you have granted `read/write private repos` access for GitHub on https://gitpod.io/access-control/

<img width="356" alt="Screen Shot 2020-07-27 at 16 30 46" src="https://user-images.githubusercontent.com/914497/88554282-9ed03000-d026-11ea-9c0b-2ba087e46873.png">

**Comment by AlexTugarev** [comment]
@Ridley-nelson17, one more question: is it possible that you changed anything on the [Connection with Gitpod ](https://github.com/settings/connections/applications/484069277e293e6d2a2a) page on github.com? Just trying to understand what happened there.
