### ISSUE TITLE
MYSQL error after importing the database

### ISSUE THREAD

**Issue by flamecopper** [gitpod-io/gitpod#1706]
mysql> CREATE USER 'xxxxx'@'localhost' IDENTIFIED BY 'xxxx';
ERROR 1805 (HY000): Column count of mysql.user is wrong. Expected 51, found 50. The table is probably corrupted
mysql> mysql_upgrade --force -uroot -p
    -> ;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysql_upgrade --force -uroot -p' at line 1
mysql> exit
Bye
gitpod /workspace/PHPLabwork $ mysql_upgrade --force -uroot -p
Enter password: 
The mysql_upgrade client is now deprecated. The actions executed by the upgrade client are now done by the server.
To upgrade, please start the new MySQL binary with the older data directory. Repairing user tables is done automatically. Restart is not required after upgrade.
The upgrade process automatically starts on running a new MySQL binary with an older data directory. To avoid accidental upgrades, please use the --upgrade=NONE option with the MySQL binary. The option --upgrade=FORCE is also provided to run the server upgrade sequence on demand.
It may be possible that the server upgrade fails due to a number of reasons. In that case, the upgrade sequence will run again during the next MySQL server start. If the server upgrade fails repeatedly, the server can be started with the --upgrade=MINIMAL option to start the server without executing the upgrade sequence, thus allowing users to manually rectify the problem.
gitpod /workspace/PHPLabwork $ mysql
ERROR 3118 (HY000): Access denied for user 'root'@'localhost'. Account is locked.

**Comment by flamecopper** [comment]
In summary,
import a database
unable to add user 
refer to a solution in stack overflow
account locked

**Comment by flamecopper** [comment]
I have tried all the fixed avaliable in the command , but still have issues;
gitpod /workspace/PHPLabwork $ mysql -u root
ERROR 3118 (HY000): Access denied for user 'root'@'localhost'. Account is locked.
gitpod /workspace/PHPLabwork $ service mysql st
start  stop   
gitpod /workspace/PHPLabwork $ service mysql st
start  stop   
gitpod /workspace/PHPLabwork $ service mysql stop
 * Stopping MySQL database server mysqld
   ...fail!
gitpod /workspace/PHPLabwork $ service mysql start
 * Starting MySQL database server mysqld
   ...done.
gitpod /workspace/PHPLabwork $ service mysql stop
 * Stopping MySQL database server mysqld
   ...fail!
gitpod /workspace/PHPLabwork $ service mysql restart
 * Stopping MySQL database server mysqld
   ...fail!
 * Starting MySQL database server mysqld
   ...done.
gitpod /workspace/PHPLabwork $ mysql -u root
ERROR 3118 (HY000): Access denied for user 'root'@'localhost'. Account is locked.
gitpod /workspace/PHPLabwork $ mysqld_safe --skip-grant-tables --skip-networking &
[1] 6344
gitpod /workspace/PHPLabwork $ 2020-08-15T23:53:38.262167Z mysqld_safe Logging to '/var/log/mysql/error.log'.
2020-08-15T23:53:38.287257Z mysqld_safe A mysqld process already exists

[1]+  Exit 1                  mysqld_safe --skip-grant-tables --skip-networking
gitpod /workspace/PHPLabwork $ mysqld_safe --skip-grant-tables --skip-networking &
[1] 6789
gitpod /workspace/PHPLabwork $ 2020-08-15T23:53:45.401861Z mysqld_safe Logging to '/var/log/mysql/error.log'.
2020-08-15T23:53:45.422304Z mysqld_safe A mysqld process already exists
^C
[1]+  Exit 1                  mysqld_safe --skip-grant-tables --skip-networking
gitpod /workspace/PHPLabwork $ mysql -u root
ERROR 3118 (HY000): Access denied for user 'root'@'localhost'. Account is locked.
gitpod /workspace/PHPLabwork $

**Comment by corneliusludmann** [comment]
Hi @flamecopper,

As I understand it, you have problems with the import of a MySQL DB. This seems to be due to an incorrect usage of MySQL. I like to try to help but this is pretty hard with a replicable example. Could you provide one?

A general comment: In Gitpod, MySQL is started with the script `/etc/mysql/mysql-bashrc-launch.sh` not via a service unit. That's why `service mysql ...` does not work.

Cornelius

**Comment by flamecopper** [comment]
Hi there

I have reach the point where root@localhost account is lock. how can I
unlock the account?

**Comment by corneliusludmann** [comment]
I don't know how you locked the root account of your MySQL database. However, Gitpod is designed to have ephemeral workspaces. That means that you can start a new workspace anytime you want with an empty MySQL database. In fact, we recommend to configure an automatic workspace setup in your `.gitpod.yml` so that you can start a new, fresh workspace for each new task instead of re-using old ones. Thus, there is no need to figure out how to unlock the root user of your database. Just go to your repo and prefix the URL with `gitpod.io#`, hit enter and you have a fresh new workspace where you could try again to configure your workspace setup.
