### ISSUE TITLE
issue whit wokspace last backup failed 

### ISSUE THREAD

**Issue by borisbrunop** [gitpod-io/gitpod#1718]
### Describe the bug

I stopped a project while opening another and both crash, it says: 

"cannot wait for workspace to initialize: workspace initialization is currently unavailable - please try again; last backup failed: workspace does not exist. Please contact support if you need the workspace data.
Please file an issue if you think this is a bug."

**Comment by corneliusludmann** [comment]
Hi @borisbrunop,

Sorry for the bad experience. I would like to help you and try to recover what we have. It would be helpful to have workspace IDs and information about the time you used your workspace the last time before the error.

What I can see so far is that there is a workspace with timestamp `2020-08-22T18:46:50.719Z` that has some changes backuped:
```
	modified:   bc.json
	modified:   exercises/02-Hello-World/app.py
	modified:   exercises/03-What-is-a-function/app.py
	modified:   exercises/04-Call-a-function/app.py
	modified:   exercises/05-Defining-vs-Calling-a-function/app.py
	modified:   exercises/06-lambda-functions/app.py
	modified:   exercises/07-lambda-function-two/app.py
	modified:   exercises/08-Function-that-returns/app.py
	modified:   exercises/09-Function-parameters/app.py
	modified:   exercises/10-Array-Methods/app.py
```

And then, there are older workspaces. The latest with the timestamp `2020-07-30T04:14:19.512Z`. This workspace has been removed by the garbage collector. Workspaces older than 14 days are removed unless you pin them (as stated in the message box on the top of the workspaces list gitpod.io/workspaces). I cannot restore these workspaces since the content has been removed already.

Please let me know if should restore something (like the changes I posted above).

Cornelius
