### ISSUE TITLE
SSH keys generated via `ssh-keygen` and the file `authorized_keys` are periodically deleted

### ISSUE THREAD

**Issue by barafael** [gitpod-io/gitpod#17435]
Disclaimer: not sure if bug report or user error.

## Problem: I want to upload build artifacts from my gitpod instance to a remote server
I want to collaboratively work on some project. To test it, I need to upload its build artifacts to a testing server. So:

* I generate public/private key via `ssh-keygen` on the gitpod instance.
* I add the public key of the instance to the authorized keys of my server
* I use `scp` to move the files over

This works nicely, however, after some time, the contents of the `.ssh` directory seem to be purged. I am not sure if this is a security feature, or a trial period, or what.

## Intended Behaviour
Ideally, I'd like it if this were either explicitly supported and the ssh config files would persist, or this would be explicitly unsupported.

**Comment by barafael** [comment]
Never mind, it's just the normal timeout.

**Comment by axonasif** [comment]
Hi @barafael, this is the expected behavior.

Quoting from https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#workspace-statuses:
> **Important:** Only files in the /workspace directory are kept between state transitions.

If you want to persist them across new workspaces and workspace reboots, you can do the following:

- Add a task on `.gitpod.yml` to decode:
```yaml
tasks:
  - name: Install id_rsa
    before: |
      cd "${HOME}"
      base64 -d <<<"${SSH_DIR_ENCODED}" | tar -xpf -
      # exit
```

- [once] Save the archived+encoded `.ssh` dir as an env var to your account, scoped to the repo:
```bash
cd ~

gp env SSH_DIR_ENCODED="$(tar -cpf - .ssh | base64 -w0)"

# Check if it works
gp validate
```
