### ISSUE TITLE
Image builder alternatives

### ISSUE THREAD

**Issue by cristian-radu** [gitpod-io/gitpod#1755]
GitPod UX is awesome!

The image builder uses the Docker in Docker model which relies on running privileged containers in your Kubernetes cluster. 
https://github.com/gitpod-io/gitpod/blob/master/chart/templates/image-builder-deployment.yaml#L69-L75

There are of course some pretty serious security concerns around this and in fact, I think this makes it a no-go for a lot of people.

What about using an alternative image builder like https://github.com/GoogleContainerTools/kaniko for example?

**Comment by meysholdt** [comment]
> GitPod UX is awesome!

thx! :)

> The image builder uses the Docker in Docker model which relies on running privileged containers in your Kubernetes cluster.
> There are of course some pretty serious security concerns around this and in fact, I think this makes it a no-go for a lot of people.

Well, the more relevant security boundary is between docker-builds and docker-engine. As you can see in the code snipped that you liked to, `--userns-remap` is enabled, so that processes that are root inside a docker-build are NOT root outside the docker build. 

> What about using an alternative image builder like https://github.com/GoogleContainerTools/kaniko for example?

We didn't go with Kaniko because it doesn't support the feature I'm describing above: Last time I checked, it did not support userns-remap, making it easy for root-processes that tun inside a docker-build to break free from container isolation and attack your Kubernetes cluster. Also, Kaniko doesn't support local caching of build results. On the plus side, Kaniko would have allowed for easier scaling due to its stateless natures.

**Comment by cristian-radu** [comment]
Thanks for the background on your choice to go with dind. 

I agree that using `--userns-remap` does create somewhat of a security boundary. 

Unfortunately, working in a high-security environment, we have pod security policies that prevent us from running privileged containers.
