### ISSUE TITLE
In docker container, second process cannot write to /proc/1/fd/1

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#17551]
### Bug description

Writing to /proc/1/fd/1 (or /proc/1/fd/2) is a standard idiom for processes inside a docker container to add to the docker logs. 

On most platforms, it's possible for processes in addition to process 1 to write to these, but on gitpod it doesn't seem to be possible. 

### Steps to reproduce

```
# In first terminal
docker run -it --rm -u 33 --name=junk ubuntu bash
```

```
# In second terminal 
docker run -it junk bash
ls >/proc/1/fd/1
bash: /proc/1/fd/1: Permission denied
```

### Workspace affected

All

### Expected behavior

* Permission should not be denied.
* Output should go to the first terminal

**Comment by loujaybee** [comment]
This does look related to the docker implementation in Gitpod.

**Comment by achille-roussel** [comment]
I think I am running into a similar issue, accessing stdio files in `/dev` is also causing permission errors.

Here is a simple step to reproduce:

```
$ cat /dev/stdout
cat: /dev/stdout: Permission denied
```

On a _classic_ linux system, the behavior of this command is to hang because `cat` attempts to read from its own output, but here we get a permission error.

A possible reason for the issue is the owner of stdio files in `/dev` is `root`, but the shell is running as the `gitpod` user:

```
$ ls -l /dev/
...
lrwxrwxrwx 1 nobody nogroup      15 Jun 26 17:27 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 nobody nogroup      15 Jun 26 17:27 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 nobody nogroup      15 Jun 26 17:27 stdout -> /proc/self/fd/1
...
$ ls -l /proc/self/fd/
total 0
lrwx------ 1 gitpod gitpod 64 Jun 26 18:15 0 -> /dev/pts/0
lrwx------ 1 gitpod gitpod 64 Jun 26 18:15 1 -> /dev/pts/0
lrwx------ 1 gitpod gitpod 64 Jun 26 18:15 2 -> /dev/pts/0
...
$ ls -l /dev/pts/
total 0
crw--w---- 1 root   nogroup 136, 0 Jun 26 18:16 0
...
$ whoami
gitpod
```

This limitation seems excessive since those are virtual files that are unique to each process, opening them in read/write mode should be allowed.
