### ISSUE TITLE
use sudo command for install some packages

### ISSUE THREAD

**Issue by mehdihadeli** [gitpod-io/gitpod#1763]
Hi,
I need `sudo` to install some packages in my environment.
Do you have any solution for this?

**Comment by Kreyren** [comment]
DISCLAIMER: I wasn't using gitpod in 1~2 months, but i believe this to be still the case.

Duplicate of https://github.com/gitpod-io/gitpod/issues/39

@mehdihadeli Workspaces doesn't have root access by default unless you set `privileged: true` in the `.gitpod.yml` file in the root of the repository **and** you are privileged user which is only granted to typefox staff, because gitpod's docker environment is not sanitized enough to allow root access (with root you could in theory escape docker sandbox and interfiere with workspaces of other users).

But you have root access during the docker-build phase so to install packages you can do:

```dockerfile
FROM gitpod/workspace-full:latest

# To avoid bricked workspaces (https://github.com/gitpod-io/gitpod/issues/1171)
ENV DEBIAN_FRONTEND=noninteractive

USER gitpod

RUN true \
	&& sudo apt-get update -q \
	&& sudo apt-get install -qy \
		emacs \
	&& sudo apt-get autoremove -qy \
	&& sudo rm -rf /var/lib/apt/lists/*
```

placed in (for example) `gitpod.dockerfile` in the root of your repository and then set `.gitpod.yml` as:

```yml
image:
  file: gitpod/debian.Dockerfile
```

See https://www.gitpod.io/docs/config-gitpod-file/ for more info about `.gitpod.yml` configuration

I also recommend using `hadolint` https://github.com/hadolint/hadolint for dockerfile linting.

**Comment by Kreyren** [comment]
Note:

```
	&& sudo apt-get autoremove -qy \
	&& sudo rm -rf /var/lib/apt/lists/*
```

These are set so that docker only caches the changes made by the task to allow for theoretically faster deployment as gitpod doesn't have to process X amount of Megabytes~Gigabytes of unneeded files (apt downstream files)

**Comment by Kreyren** [comment]
Note: Docker caches each `RUN` so if you have a task that takes X amount of minutes~hours you can let that to be processed and cached for the next deployment to be next to instant. This can be automatized using `tasks` in `.gitpod.yml`

**Comment by Kreyren** [comment]
Also if it helps and iirc development for dockerfiles in gitpod is pita so this might be helpful to you:

```Makefile
test-gitpod:
	@ cat development.Dockerfile | sed -E "s#(RUN\s{1}true\s{1}\")(replace)(\"\s{1})#\1$$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)\3#gm" > .gitpod.Dockerfile
	@ git add -u
	@ git commit -m "$$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)"
	@ git remote add fork https://github.com/Kreyren/Breaking-gitpod.git || true
	@ git push fork
	@ gp preview about:blank >/dev/null; gp preview https://gitpod.io/#https://github.com/<OWNER>/<REPOSITORY>/tree/<BRANCH>
```

This is made to also replace things alike:

```Dockerfile
RUN true "replace" \
	&& blah blah
```

with

```Dockerfile
RUN true "random-string" \
	&& blah blah
```

To test the changes of the `RUN` tasks, because if these are unchanged then gitpod is going to source the previous cache.

**Comment by Kreyren** [comment]
And if it's still the case you can request gitpod staff to make a merge request in your repository to set up the environment for you.

**Comment by Kreyren** [comment]
Also if you prefer gitpod has an IRC room on https://webchat.freenode.net/#gitpod (requires freenode.net account)

**Comment by corneliusludmann** [comment]
You can use `sudo` in your own Dockerfile: https://www.gitpod.io/docs/config-docker/

**Comment by mehdihadeli** [comment]
ok thanks
