### ISSUE TITLE
Feedback Issue: Browser-based terminal IDE

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#17724]
### Objective

Issue for feedback related to our browser-based terminal IDE. 

**Related roadmap items:** 

- https://github.com/gitpod-io/gitpod/issues/11180
- [Linear project](https://linear.app/gitpod/project/xtermjs-browser-based-terminal-bfae38e3ac06)

**Related links**

- ~[Form for signing up for the private beta [Gitpod labs]](https://gitpod.io/labs)~ **It is available Generally now.** See [**changelog**](https://www.gitpod.io/changelog/code-in-the-terminal-without-leaving-your-browser!)

**Comment by erikmd** [comment]
Dear Gitpod maintainers,
Thanks to @loujaybee's advice (https://github.com/gitpod-io/gitpod/issues/2419#issuecomment-1569754649) I was able to test your brand new browser-based Terminal (version 1.0.0 "latest"); here is some feedback/issues reports.

in this first session (using firefox-esr on Debian stable) I was especially interested in testing basic interaction with emacs (which is preinstalled in this ubuntu LTS image 👍)

## emacs (2 keybindings issues)

* upside: the interaction is smooth and impressive; I was able to install and run a few packages using MELPA, the emacs menu works well with `F10`.
* blocking drawbacks: the keybindings `C-w` (<kbd>Ctrl+W</kbd>) and `C-q` does not work (they are intercepted by firefox to close the tab, and close the browser, which is a bit… unfortunate)

**additional remarks:**
* the `C-w` issue is reproducible with chromium, and close the tab
* fortunately, the `C-q` shortcut which does not seem to be bound in chromium, so it works as expected in chrome/chromium
* note: `C-q` is important:
  * both for emacs (it is the standard quoting command to insert control characters (e.g. `C-q C-m` inserts `^M`, that is the 13rd control character, that is the CarriageReturn char))
  * and for the terminal, because it allows to resume a stopped command, e.g. try:
    ```
    $ while :; do echo .; sleep 1s; done
    C-s    #(stop)
    C-q    #(resume)
    ```
* `C-w` is a bit less important in emacs, but is still used by default for the cut-to-clipboard shortcut and for saving file to another filename (`C-x C-w`)

**conclusion:**
* do you think it's feasible to prevent the browser for "seeing these two shortcuts"?
  * if yes, great ✨✨✨
  * otherwise, you could add in the doc a comment suggesting to (1) use Chromium/Chrome to be able to use `C-q` in emacs, and (2) reopen the tab with <kbd>Ctrl+Shift+T</kbd> if closed inadvertently

## clipboard handling

Finally, a comment regarding copying/pasting code or logs from/to the browser-based terminal:
it seems it's possible to use the browser contextual menu, but due to the default colors, the copied text may contains "noise characters" ; that's obviously a minor pain ; but maybe this could be solved by adding a dedicated clipboard menu in the webpage? or just keep it as is: indeed I believe overriding shortcuts further with <kbd>Ctrl+C</kbd> or <kbd>Ctrl+Shift+C</kbd> would be a more invasive strategy IMHO.

Last but not least, thanks a lot for developing this, and congrats for the impressive work!

**Comment by jeanphibaconnais** [comment]
Hello :wave: 
thank's for giving me the terminal option in my Gitpod account. I just quickly tested it, this looks great. I tried a `exit` command and is it not possible to stop the workspace with this command ? I will test more in detail next weeks

**Comment by axonasif** [comment]
Hi @jeanphibaconnais, you can use `gp stop` command instead.

But if you really want to have exit act like `gp stop`, you could add the following to your dotfiles repo `install.sh`:
```bash
#!/usr/bin/env bash

printf 'alias %s="%s"\n' exit "gp stop" >> "$HOME/.bashrc"
```

**Comment by jeanphibaconnais** [comment]
Hi @axonasif , thanks for your response. Yes of course I know the `gp stop` command. As it was my first reflex to quit the terminal with the `exit` command, maybe it would be a behavior by default (or not 😅 )

**Comment by erikmd** [comment]
Hi all, good news:
I performed new tests to follow-up my [experience report](https://github.com/gitpod-io/gitpod/issues/17724#issuecomment-1597862258),
and got a pretty good workaround (that might be mentioned in Gitpod documentation, maybe :)

## For Firefox

* The `C-q` shortcut can be disabled in the user preferences, and it is then fully seen by the **Gitpod** terminal
* The `C-w` shortcut can't be disabled but the drawback of its outcome can be mitigated by:
  * changing the user preferences to never close the browser if there is only one tab opened with Gitpod,
  * and subsequently type `C-S-t` (Ctrl+Shift+T) to reopen the Gitpod tab if we mis-closed it.
 
To this aim, I used this configuration:

![2023-07-12_22-41-03_Screenshot_Firefox_workaround](https://github.com/gitpod-io/gitpod/assets/10367254/e040f574-4f18-482c-a7df-a77dd2a8b8e4)

Credits: inspired by https://askubuntu.com/a/1401149/851217

## For Chromium/Chrome

* The `C-w` shortcut can be disabled:
  * by installing an extension (e.g. [ctrlw](https://chrome.google.com/webstore/detail/ctrlw/goejokenmdamcapadhgghgpeeaeaaedc/), but there are other ones)
  * and configuring its shortcuts so that `C-w` is a no-op, and `C-S-w` closes the current tab.
  * *remaining drawback w.r.t. Gitpod:* the `C-w` shortcut is not seen by Gitpod (obviously, given it's a no-op :)

To this aim, I used this configuration:

![2023-07-12_23-14-15_Screenshot_Chromium_workaround](https://github.com/gitpod-io/gitpod/assets/10367254/c357d864-ce60-4ca0-837c-04feb4044bd5)

Credits: inspired by https://unix.stackexchange.com/a/621800/297058

Hoping that this helps

**Comment by erikmd** [comment]
> The `C-w` shortcut can't be disabled

On second thought, I just realize that it's easy to fully fix this aspect, by adding an [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) handler in Gitpod's js code.

### Additional info

I had done [several tests](https://github.com/ocaml-sf/learn-ocaml/issues/467#issuecomment-1059802295) in a webapp project I co-maintain, and it appears not all ways to add an onbeforeunload are portable across (Firefox, Chrome, Safari); so FWIW, I had ended up with:

```js
window.onbeforeunload = function(e) {e.preventDefault(); return false;}
```
(that could be "cancelled" with `window.onbeforeunload = null;`)

**Comment by erikmd** [comment]
Another issue/wishlist with the Browser Terminal:

The shortcut `C-t` (useful in Emacs as well as in a shell) currently is not caught by Gitpod.
Currently, it always opens a new tab…
Reproduced in Firefox-ESR and Chromium.

Fortunately, the shortcut works if we connect from SSH (not using a browser).

**Comment by axonasif** [comment]
@daniloraisi 👋 if you're on firefox, you can configure a custom monospace font from the preferences, this worked for me.
<img width="1072" alt="Screenshot 2023-10-30 at 11 19 52 PM" src="https://github.com/gitpod-io/gitpod/assets/39482679/d27376a9-e66f-46e3-ab6e-4c2249c26730">

**Comment by daniloraisi** [comment]
@axonasif I'm using Edge, but it worked the same way. Thanks!

**Comment by axonasif** [comment]
@daniloraisi awesome!

**Comment by jfadams1963** [comment]
Thank you for providing a browser-based terminal option.

I'm brand-new to using Gitpod's IDE as an alternative to GitHub Codespaces, and so far I like it and will continue using it.

I'm puzzled by two things I'm seeing:
+ When using the browser terminal, the command in .gitpod.yml is not executed. If I run `gp validate` within a terminal sesion, the debugging image _does_ run my script and set up my database. Also, if I run a browser VS Code session, the script does run and set up the database.
+ The browser terminal session takes much longer to start than the browser VS Code session does and it takes even _longer_ to shut down.

Please let me know if I should formally open a separate issue. Thanks!
