### ISSUE TITLE
[VS Code] copy paste is not working

### ISSUE THREAD

**Issue by Palistha14** [gitpod-io/gitpod#18013]
### Bug description

ctrl+v is not working. We could only use ctrl+shift+v.
It's pasting the file path instead of the content.

### Steps to reproduce

It appears automatically

**Comment by loujaybee** [comment]
@Palistha14 which IDE or editor was this?

**Comment by Palistha14** [comment]
VS code

**Comment by davidwindell** [comment]
This is affecting all our team too, please could you escalate this?

**Comment by Palistha14** [comment]
This problem is now resolved. I apologize for not letting you know sooner.

**Comment by mustard-mh** [comment]
Hey @davidwindell , do you still have problem with copy paste? Could you provide more info to help us debug with 🙏 ? like

- Editor you're using (browser VS Code or desktop VS Code)
- If it's browser, then which browser you're using now?
- A screen record will be good for us to check how you use copy-paste

**Comment by akosyakov** [comment]
@davidwindell We are relying on VS Code itself for this and will need to escalate it to MS, but we need reproducible steps. Unfortunately none in our team can reproduce it :( 

I wonder maybe it is related with special VS Code/Chrome extension which messing up key shortcuts for you. Could you disable all extension in your browser and VS Code and try again?

**Comment by bryanmonterrosa** [comment]
This is the issue that I'm facing related to ctrl + v and ctrl + shift + v:

1. Copy a file in the explorer.
2. This allows you to use ctrl + v on a folder and the file is pasted.
3.  Using ctrl + v on the editor will paste the path to the file.

4. ```The issue```: copy text from the editor and try to paste it.
5.  This will continue to paste the previous file's path instead of the text from step 4.
6.  Only right-click -> paste will work with the text copied from step 4.

![Screen recording 2023-06-30 11 23 03 AM](https://github.com/gitpod-io/gitpod/assets/123660290/633e2c75-4ad9-4a8c-9fa6-731b61bd1c86)

I sent troubleshooting info to troubleshooting@gitpod.io

**Comment by akosyakov** [comment]
@bryanmonterrosa thank you ❤️ I was able to reproduce it now too

**Comment by akosyakov** [comment]
It was fixed in insider and going to be available in next release (1.80): https://github.com/microsoft/vscode/issues/185466

You can switch to latest version on gitpod.io/preferences to work it around for now.
<img width="593" alt="Screenshot 2023-07-03 at 09 13 26" src="https://github.com/gitpod-io/gitpod/assets/3082655/81aa4b41-5ccd-4b0b-940f-7cc126c14b01">

**Comment by treeder** [comment]
This still isn't fixed for me, is it for anyone else?
