### ISSUE TITLE
Error: cannot create initializer for unkown context type

### ISSUE THREAD

**Issue by vigneras** [gitpod-io/gitpod#1860]
### Describe the bug
Can't access my workspace

### Steps to reproduce
Create a workspace from gitlab

### Expected behavior
Access to workspace granted

### Example repository
c1aaf38c-4a26-4322-92b2-054b9a198ab3

**Comment by corneliusludmann** [comment]
Would you mind providing the Gitpod URL you have used to open your workspace?

**Comment by vigneras** [comment]
I had to move fast, I deleted it. 
Regards.

**Comment by alycda** [comment]
I have this issue trying to open one of my workspaces, but I was able to resolve by using the GitPod: Ready to Code button on my gitlab repo's README.

**Comment by strausmann** [comment]
I just had the same problem. GitPod self-managed with a GitLab self-managed behind it.

I created a new repository in GitLab. Then loaded the empty repository with the gitpod. Then I created the .gitpod.yml, the README.md and a .env.example. Created a commit in the GitPod and then tried in vain to push it into the master branch. The only way I could create the push was via the terminal.
Now the session ended after 30 minutes. I made some more changes, but I haven't committed or pushed them yet.

Now I cannot start this workspace anymore. I get this message:

Error: cannot create initializer for unkown context type

Clicking on the Gitpod button in README.md now loads the last push into the workspace. So all changes since the last push are gone.

**Comment by svenefftinge** [comment]
Do you get the mentioned error (Error: cannot create initializer for unkown context type) when you try to start the workspace from the workspaces list in your dashboard?

**Comment by strausmann** [comment]
Yes

**Comment by strausmann** [comment]
Please, reopen this issue, thanks

**Comment by strausmann** [comment]
Can you reproduce the problem?
I think the problem is the empty repository... 
Can I still send you any logs?
I'm using the GitPod Docker container variant

**Comment by csweichel** [comment]
> Can I still send you any logs?

The logs from `ws-sync`, `ws-manager` and `server` would be very helpful indeed.

**Comment by strausmann** [comment]
Can you send me the right command to extraxt the right logs for you? Thanks

**Comment by akosyakov** [comment]
`kubectl get pods` to see pods then `kubectl logs` to get logs
