### ISSUE TITLE
deleted work

### ISSUE THREAD

**Issue by JoeLouisDsantos** [gitpod-io/gitpod#1910]
Hello,

So I was doing work on my Resume repository in Gitpod and was saving everything and made about 5 commits. I then decided to update and restart my laptop (mainly because it said it needed one, also because an image wasn't loading properly from Gitpod to the open port, all the code was correct so I thought maybe restarting my laptop could help) so I closed my browsers and other open applications then restarted my laptop. I have then gone back on to Github to find that my Resume repository was empty and none of my code was inside. I just want to know if I can get my work back?

Regards
Joe-Louis D'Santos

**Comment by jankeromnes** [comment]
Hi @JoeLouisDsantos!

I assume that you've found your work-in-progress again by visiting https://gitpod.io/workspaces/ and restarting your old workspace.

Going forward, we recommend to always commit and push your changes to your repository at the end of each coding session -- that way you're certain never to forget any valuable changes in an old workspace (especially since old/unused workspaces get garbage collected after a while).

Also, please feel free to create as many new workspaces as you'd like. We typically create a new workspace for every task we tackle (so some progress on a feature + a code review = 2 separate workspaces) and then push any valuable changes at the end (thus we never reuse old workspaces).

Hope this helps. Please let me know if you have any questions.
