### ISSUE TITLE
[Theia] No more heartbeats

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1939]
On staging I started a workspace and then closed the tab. 
Just noticed that the workspace is still running.

**Comment by svenefftinge** [comment]
Checking the database there are no entries in d_b_workspace_instance_user anymore (since last deploy on friday)

**Comment by svenefftinge** [comment]
Checking the WS connection there are no `heartBeat` messages sent anymore.

Also I noticed that on staging the websocket connection to the gitpod server seems to be reconnecting a lot.
<img width="256" alt="Screenshot 2020-10-04 at 09 34 26" src="https://user-images.githubusercontent.com/372735/95009773-db229c80-0624-11eb-9e5f-e8bd879341a4.png">

**Comment by akosyakov** [comment]
ws-proxy bogusly with empty message and 200 code then a supervisor is not ready yet to provide a workspace info, as follow-up breaking heart beat

**Comment by akosyakov** [comment]
There were also issues in the supervisor frontend code. I've fixed them in https://github.com/gitpod-io/gitpod/pull/1941/files#diff-a9065f9684620c2a5474ad01384dad97R17-R18

I as well got rid of the call to the supervisor workspace info endpoint, since at the moment of the scheduling the heart beat I already have instance if from the server: https://github.com/gitpod-io/gitpod/pull/1941/files#diff-e03f459162565e7c3de33519ca8d7e70R79-R84

But we should an issue with ws-proxy otherwise ide and content checks are returning too early. Also in Gitpod Code I still need to call the workpace info endpoint and if it breaks there then it breaks completely.

**Comment by csweichel** [comment]
I've raised a PR for fixing the ws-proxy behaviour: https://github.com/gitpod-io/gitpod/pull/1943

**Comment by akosyakov** [comment]
should be resolved by https://github.com/gitpod-io/gitpod/pull/1941 and https://github.com/gitpod-io/gitpod/pull/1943
