### ISSUE TITLE
Directly starting a workspace from a branch

### ISSUE THREAD

**Issue by nhorton** [gitpod-io/gitpod#19490]
## Is your feature request related to a problem? Please describe
Prebuild pages no longer have a "new workspace from prebuild button" and the "New Workspace" screen lets you choose a repo but not a branch. The comments in PR's are the only easy way to start a workspace on a branch now.

## Describe the behaviour you'd like
Priority 1 would be adding a branch selector to the Start Workspace screen.
Priority 2 would be restoring a "Start Workspace from Prebuild" button to the Prebuild screen, or just have that on the latest prebuild and have a link from each old prebuild to the latest.

**Comment by filiptronicek** [comment]
Hi @nhorton 👋,
we removed the "run workspace from prebuild" buttons from the prebuild UIs because the feature was causing a lot of confusion and was technically challenging, where most users would land on older git states defeating most of prebuilds' benefits.

For starting workspaces from a specific branch, I would recommend you to try out our browser extension, which adds a Gitpod button to GitHub, GitLab and Bitbucket to open PRs or branch URLs directly in Gitpod. Alternatively, you can prefix a branch / PR URL with `gitpod.io/#` and it will create a workspace tied to the correct one.
