### ISSUE TITLE
Cannot start workspaces with JetBrains Rider

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#20132]
### Bug description

When starting a workspace with the Rider IDE, it'll timeout, and begin to stop with the message `backend timed out to start after 5 minutes`. Once stopping has finished, the error will read `container workspace completed; containers of a workspace pod are not supposed to do that`

### Steps to reproduce

Try starting a workspace with the JetBrains Rider IDE from any repo

### Anything else?

No workaround at this time

**Comment by mustard-mh** [comment]
**Updates**

https://github.com/gitpod-io/gitpod/pull/20141 can bring Rider x Gitpod integration back, but only for `2024.1`, because we’re blocked by an [upstream issue](https://youtrack.jetbrains.com/issue/RIDER-116278/Incorrect-format-of-plugin.xml-for-Riders-bundled-plugin-intellij.rider.plugins.cwm) to build plugin for `2024.2`.

**Comment by mustard-mh** [comment]
Changes will be deployed to gitpod.io next Monday
