### ISSUE TITLE
Result of gp url in .gitpod.yml different from gp url inside terminal

### ISSUE THREAD

**Issue by maksimr** [gitpod-io/gitpod#2021]
STR:

- Add.gitpod.yml
- Add `command: gp env SANDBOX_URL="$(gp url 8080 2>/dev/null)" && echo $SANDBOX_URL`
- Open terminal and run `gp url 8080` it would be different from `$SANDBOX_URL` value

### Expected behavior

Add possibility setup container environment variable with public url

### Example repository

https://github.com/maksimr/playground/blob/master/.gitpod.yml#L3

**Comment by svenefftinge** [comment]
The command `gp env` doesn't set an environment variable in the current container or even shell, but only stores it in the Database, such that it gets injected on next start. But since you'll get a new workspace id for each new workspace you start on a project, it doesn't make sense to store the output of `gp url` in a gitpod env var. 
So what you probably want to do is something like:
`export SANDBOX_URL="$(gp url 8080 2>/dev/null)" && ...`

**Comment by svenefftinge** [comment]
I hope this helps, please tell us if not. Also please open more tickets if you have other questions, or simply ask in https://community.gitpod.io

**Comment by maksimr** [comment]
@svenefftinge unfortunately `export` isn't what I want exactly. My goal is set env variable globally for the container. For example I want to open new terminal and expect that `SANDBOX_URL` would refer on `gp url 8080` for the current container.

But thanks for the explanation how `gp env` works. My bad I have missed this moment in documentation.
