### ISSUE TITLE
[Bitbucket] Tokens expiring soon results in "unauthorized"

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2024]
When a token is expired (for bitbucket tokens are expiring after 2h) we see 'user unauthorzed!' when starting a workspace.
Only after logging in and out the token seems to get refreshed.
CC @AlexTugarev Does that make sense, or did I miss something?

**Comment by AlexTugarev** [comment]
Without more info this is hard to tell, but my best guess is, this has nothing to do with the git hoster at all. Otherwise we would see something like "couldn't parse context"

It sounds like we're not handling unauthenticated errors for `/start` URLs, which we definitely should and already do for creation of new workspaces. In that cases we're redirecting to the login handler with the request to get back to where we started.

**Comment by AlexTugarev** [comment]
We've the means of getting tokens refreshed in background by now.
