### ISSUE TITLE
Bug: Copy & Paste files does not work

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#2026]
### Describe the bug
When copy & pasting files from one folder to another it does not work.

### Steps to reproduce
1. Right click on any file that is inside any folder.
2. Select (click) on the "copy" menu option.
3. Right click on another folder (but not the same as the file parent folder)
4. Select the "paste" menu option.

### Expected behavior
A new file should be created on the destination folder, the file content should be the same as the original copied file.

Here is an animation:
![iTDhqs8WiX](https://user-images.githubusercontent.com/426452/96518526-1afa9e00-1239-11eb-922c-dddf447329ed.gif)

**Comment by svenefftinge** [comment]
The context menu commands don't work in browsers because they don't allow JS to access the user's clipboard. 
Please use the system shortcuts instead. You should get a notification on the bottom right about that.
<img width="528" alt="Screenshot 2020-10-20 at 09 56 12" src="https://user-images.githubusercontent.com/372735/96557542-b122d880-12ba-11eb-8d08-0992dfb869db.png">

**Comment by alesanchezr** [comment]
Oh you are right, I didn't see the notification but you are right its showing up.
I guess you can close this 😄
