### ISSUE TITLE
Server specifications

### ISSUE THREAD

**Issue by hm2075** [gitpod-io/gitpod#2081]
Hi

what would you recommend for a small team of developers,    about 8 developers and at most 4-5 developers working on an angular/dotnet core app,        

server : centos8

ram and disk space

also

![image](https://user-images.githubusercontent.com/53794682/97466353-ea9eb800-193a-11eb-80ed-45ea4ec368f8.png)

what does 1m mean?       and how does requests and limits come into play?

thanks

**Comment by wulfthimm** [comment]
In general you need for a small team about 3 nodes with each one having 8 CPUs and 8 GB RAM. The storage depends on the size of workspaces you are running. `workspace-full` needs about 8 GB storage so I guess about 200GB space to store workspace data. You can use bigger machines to increase the workspace density on one node or you can make the nodes smaller so that unneeded servers will be shutdown when you use auto-scaling.

**Comment by hm2075** [comment]
Thanks for the detail
Much appreciated
