### ISSUE TITLE
Cannot "open preferences" inside developed Theia application

### ISSUE THREAD

**Issue by marechal-p** [gitpod-io/gitpod#21]
**Describe the bug**
When running a Theia application from within gitpod, it seems like I cannot open the preferences (the button click does nothing).

**To Reproduce**
https://gitpod.io/#https://github.com/theia-ide/theia/pull/2602
Start the browser example application, go to `File > Open Preferences`.
It should do nothing.

**Expected behavior**
We could expect the preferences to be opened.

**Comment by akosyakov** [comment]
It's Theia bug, the preference widget should use the editor manager to open an editor, instead of trying  try to reimplement an editor opening himself: https://github.com/theia-ide/theia/blob/842196b5b18ce340f6b1beaea9e9a7ddbe2fd96f/packages/preferences/src/browser/preferences-tree-widget.ts#L193-L196

**Comment by akosyakov** [comment]
Yes, I'm pretty sure, the internal contract was changed, the editor factory excepts an object, no a URI. But it is all implementation details, clients should just always use `EditorManager`.

**Comment by akosyakov** [comment]
it was resolved already
