### ISSUE TITLE
can't open port in browser

### ISSUE THREAD

**Issue by VKirijanova** [gitpod-io/gitpod#2102]
When I am pressing in open ports open in browser it showing me error:

The web page at https://33060-ab2bfcf2-02e4-420f-b649-1dafaaf4c5ff.ws-eu01.gitpod.io/ might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR

**Comment by corneliusludmann** [comment]
Hi @VKirijanova,

Could you please provide more information that helps to debug the situation? E.g.:
- What services runs on port 33060? How did you start it?
- Is the service accessible from inside the workspace, e.g. by `curl`?

Could you provide a link to the repository or [share your workspace](https://www.gitpod.io/docs/sharing-and-collaboration/)?

**Comment by VKirijanova** [comment]
Hello,

This will be my repository: https://github.com/VKirijanova/USD-resume1

when i'm opening preview in Gitpod, I can see my work, however when I am trying to do any actions with open ports, it showing me error. 

I am starting my new repository with adding template, however yesterday when I tried to open my previous repository, ports was not working as well.

Thnk you for your help

**Comment by corneliusludmann** [comment]
Sorry, it seems that this isn't a problem with Gitpod. I'm able to open your repository in Gitpod, start the python webserver as written in your README.md and show the index.html file that is served on port 8000.

If you think that there is a Gitpod bug, please write precisely what is not working and what you expect to work. Otherwise, I'll gonna close this issue soon.

Thanks for your understanding.

**Comment by VKirijanova** [comment]
I am soooo sorry. I feel super dumb now :( 

Thank you for help
