### ISSUE TITLE
[staging]: Ruby hovers, auto-complete, go to defination, rename symbol all don't work

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2132]
### Describe the bug

Hovers, auto-complete, go to definition, rename symbol all don't seem to work.

### Steps to reproduce

Try:  https://gitpod-staging.com#https://github.com/gitpod-io/rails_sample_app

**Comment by svenefftinge** [comment]
Didn't we remove the language services extension because there are different alternatives and we decided to not forcing everyone to one opinionated solution?

**Comment by jankeromnes** [comment]
We did remove `castwide.solargraph`, because it was broken.

I think now we should install `rebornix.Ruby` by default, because it's the preferred extension ([1,448,003](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) downloads on VSCode marketplace, as opposed to [414,291](https://marketplace.visualstudio.com/items?itemName=castwide.solargraph) for Solargraph).
