### ISSUE TITLE
MongoDB and Node (Express)

### ISSUE THREAD

**Issue by Yael95** [gitpod-io/gitpod#2175]
Hi Everyone,
I would like to ask about how can I install mongodb and set it up in gitpod as I am trying to run npm install mongod but I get an issue with node-gyp not being able to get installed, I just want to install mongodb to follow along an online course on my repo. Can I get some pointers as to how to get mongodb to work in gitpod?

**Comment by wulfthimm** [comment]
Do you want to install the `mongodb` database server or only the nodejs driver?

**Comment by akosyakov** [comment]
Please also consult our ultimate guide: https://www.gitpod.io/blog/gitpodify/#mongodb (composed by @jankeromnes 🙏)

**Comment by Yael95** [comment]
I know how to install it but the problem is how to set it up with mongo compass on my local machine. It just does not connect at all

**Comment by akosyakov** [comment]
@csweichel wrote a blog post about how to use local services from Gitpod workspaces: https://www.gitpod.io/blog/local-services-in-gitpod/

**Comment by meysholdt** [comment]
I assume your're running MongoDB in your Gitpod Workspace and Mongo Compass on your desktop (because it's a GUI app). 

You'll need to make sure that 
* You have Mongo's port exposed in Gitpod (Marked as "public")
* obtain the URL via `gp url <portno>` in Gitpod's Terminal.
* wrap the URL into [Mongo Compass's connection string](https://docs.mongodb.com/compass/master/connect).

This assumes Compass talks a HTTP-based protocol and this assumes Compass is fine with the fact that Gitpod does the HTTPS-termination. 

I haven't tried it myself.

**Comment by wisammechano** [comment]
> I assume your're running MongoDB in your Gitpod Workspace and Mongo Compass on your desktop (because it's a GUI app).
> 
> You'll need to make sure that
> 
> * You have Mongo's port exposed in Gitpod (Marked as "public")
> * obtain the URL via `gp url <portno>` in Gitpod's Terminal.
> * wrap the URL into [Mongo Compass's connection string](https://docs.mongodb.com/compass/master/connect).
> 
> This assumes Compass talks a HTTP-based protocol and this assumes Compass is fine with the fact that Gitpod does the HTTPS-termination.
> 
> I haven't tried it myself.

Unfortunately, I've tried this and it doesn't work. The problem seems to be the internal port mapping for gitpod. Trying to connect through `gp url <portno>` output, but it hangs on no response for all ports: 27017, 80, 443 because gitpod URLs are actually proxied through https.

Though I wonder why URLs are as such, wouldn't it be close to usual behavior if a workspace had a unique url and then ports can actually be appended to it instead of pretending it to the domain?

so instead of `https://27017-red-lynx-4rm8h0jx.ws-eu18.gitpod.io/` it becomes `https://wp-red-lynx-4rm8h0jx.ws-eu18.gitpod.io:27017`
