### ISSUE TITLE
Native S3 support

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#2197]
Gitpod Self-Hosted can currently access S3 storage only indirectly through Minio.
It would be great if Minio would not be needed when working with S3 buckets.

**Comment by csweichel** [comment]
I'd expect that we can already do this, because MinIO is S3 compatible.

To test this, you'd need to configure e.g. an AWS S3 endpoint [where you'd otherwise configure minio at](https://github.com/gitpod-io/gitpod/blob/master/chart/values.yaml#L412-L414).

**Comment by supra08** [comment]
So currently in order to use S3, we have a Minio instance with an S3 storage backend. Won't we be requiring native S3 support like the one we have for GCS (https://github.com/gitpod-io/gitpod/blob/master/components/content-service/pkg/storage/gcloud.go)?
I am thinking of implementing the same using the https://github.com/aws/aws-sdk-go quite much on similar lines. The corresponding functions can be replicated for this. Possibly this might be a better solution for self-hosted on AWS?

**Comment by csweichel** [comment]
The MinIO client already have in the code base should be able to directly talk to an S3 service - without a MinIO backend inbetween.
