### ISSUE TITLE
Hi 2 Questions.

### ISSUE THREAD

**Issue by ret394** [gitpod-io/gitpod#2252]
Hi 2 Questions.

1. Why should I care about this email?

>Welcome to Private Trial

It's sitting in my junk mail. 30 days? Trial? Spam.

Meta comment -

**Comment by gtsiolis** [comment]
Hey @ret394! I've moved the issue since this is not related to [`gitpod-io/gitpod-status`](https://github.com/gitpod-io/gitpod-status).

By default when opening a private repository for the first time, you automatically join the Free Trial for 30 days. If you think you've received this email more than once let us know.

Feel free to ask such questions in the [forum](http://community.gitpod.io/) and not in the issue trackers. This way other community members can benefit from seeing or searching similar cases. Thanks! 💯

**Comment by ret394** [comment]
Sorry I asked. My bad!
