### ISSUE TITLE
Configure maven so the repository sits in worksapce folder

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#232]
We need to make sure that downloaded libraries are sitting in the `workspace` folder so they are kept between sessions.

**Comment by svenefftinge** [comment]
Instead of reconfiguring everything we should investigate in snapshoting the docker container.

**Comment by meysholdt** [comment]
since the container snapshotting is not a low-hanging-fruit and we really need to archive the libraries in pre-built workspaces, I think we should go with the configuration approach for now.

a) have `/home/gitpod/.m2/settings.xml` with contents 
```
<settings>
  <localRepository>/workspace/m2-repository/</localRepository>
</settings>
```

b) have `ENV M2_HOME=/workspace/.m2`

It's important for us this also works for Gradle. [It should](https://discuss.gradle.org/t/mavenlocal-how-does-gradle-resolve-the-directory-of-the-local-maven-repository/4407).

While I like the simplicity of (b) I think it is not good to encourage people to share their `settings.xml` because it can contain passwords. Additionally, there may be `.m2/settings-security.xml` with a master password.

**Comment by meysholdt** [comment]
c) `settings.xml` [can also be in `${maven.home}/conf/settings.xml`](https://maven.apache.org/settings.html)

d) [`ENV MAVEN_OPTS="-Dmaven.repo.local=/workspace/.m2"`](https://stackoverflow.com/a/7071791)

e) `ln -s /workspace/.m2/repository ${maven.home}/.m2/repository`

**Comment by meysholdt** [comment]
option (b) is technically invalid, since it refers to the installation-dir and not the user's config-dir. Proper solutions:
https://stackoverflow.com/a/1528913
https://gerardnico.com/maven/user.home
