### ISSUE TITLE
json bad syntax hightlighting for long strings with escape char

### ISSUE THREAD

**Issue by eyak** [gitpod-io/gitpod#242]
**Describe the bug**
Valid json is highlighted as bad:
![image](https://user-images.githubusercontent.com/5586769/51209073-024cae00-1918-11e9-8ed7-0142dff6cfc5.png)

**To Reproduce**
Extract [test.zip](https://github.com/gitpod-io/gitpod/files/2761411/test.zip), and open test.json in editor

**Expected behavior**
All valid json should appear blue

**Comment by svenefftinge** [comment]
This is due textmate stopping highlighting for too long lines (over 400 characters). 
So the tokenizer looses its state and subsequent tokens are odd.

We do that to not do overly expensive computation and thereby blocking users when opening e.g. minified code.

**Comment by codemzy** [comment]
Any chance this could be extended above 400 characters? I can understand the reasons for it, but I run into this highlighting issue fairly regularly for example, when putting an inline svg into some html...

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M17.16 6.42a8.03 8.03 0 0 0-3.58-3.58l-1.34 2.69a5.02 5.02 0 0 1 2.23 2.23l2.69-1.34zm0 7.16l-2.69-1.34a5.02 5.02 0 0 1-2.23 2.23l1.34 2.69a8.03 8.03 0 0 0 3.58-3.58zM6.42 2.84a8.03 8.03 0 0 0-3.58 3.58l2.69 1.34a5.02 5.02 0 0 1 2.23-2.23L6.42 2.84zM2.84 13.58a8.03 8.03 0 0 0 3.58 3.58l1.34-2.69a5.02 5.02 0 0 1-2.23-2.23l-2.69 1.34zM10 20a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm0-7a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/></svg>
```

I have to split the path up onto multiple lines so that the rest of the html formatting / highlighting looks right in the editor. I can continue with this workaround, but maybe if it could be extended without any major issues for you guys it would be super handy 👍
