### ISSUE TITLE
Is there a roadmap for GitPod?

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#244]
Hi I just wanted to ask if there is an official roadmap for Gitpod, i.e., which features will be implemented next and so on.

Or is the roadmap of Gitpod similar to the one of theia? And will all features of Theia eventually land in Gitpod?

Kind regards,
Thomas

**Comment by svenefftinge** [comment]
Hi Thomas,

all features of Theia will land in Gitpod, too. Most importantly we are working on making VS Code extensions work and with that have access to over 9000 existing extensions. 🎉 

But Gitpod is more than Theia. We will keep working on removing friction for developer flows. For instance, a huge new feature we are going to release soon is what we call 'prebuilt workspaces', i.e. Gitpod workspaces being built and executing init commands on each commit, similarly to a CI, so that when users want to start working on a certain branch and there is a prebuilt WS already, they really can start coding immediately.

There is no 'official roadmap' at this point other than the blog posts. We are talking about the things that exists. But since you ask, we plan to leave the beta phase within the next couple of weeks.
hth, 
Sven

**Comment by Sandared** [comment]
Hi Sven,

thanks for the quick reply. 
Prebuilt workspaces sound great! Maybe that will reduce my time waiting for `mvn clean install` to download the internet the first time it is used in a new workspace ;)

I'll start my next (larger) project at the beginning of february and would love to use Gitpod for it, but until now I'm still missing Java debug support :/ (Therefore the question about a roadmap) So if you have something like beta access to new features or plan to publish Java debugging within the next weeks anyway then that would be awesome :)

That said, I'm still hyped about Gitpod and the smooth workflow it allows.
Great work! Keep it up!

Thomas

**Comment by svenefftinge** [comment]
Java debug support has quietly landed already. But there are some other things we want to fix with Java, before announcing it. You can see, when opening a main method in an editor there are code lenses to start and debug the application.

**Comment by Sandared** [comment]
Wow!!! That's awsome 👍 

Is there also a way to connect to an arbitrary running java process? I'm developing with the osgi framework and would like to avoid to start it by hand via a main method.
And is there a debug view?
Or documentation? So I don't have to annoy with even more questions about this awesome feature? xD

**Comment by Sandared** [comment]
Forget the question about views... that one was simply stupid ;) Should have just checked the "View" menu entry

**Comment by svenefftinge** [comment]
Yes, you can attach. Open the launch settings and try content assist. 
Documentation to be written (once we announced).
And you questions are not annoying :-)

**Comment by svenefftinge** [comment]
Please post as many questions as you want over at https://github.com/theia-ide/theia/pull/3833

**Comment by Sandared** [comment]
I will do so. Thanks for all the information :)
