### ISSUE TITLE
Image Pulls take very long

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2451]
It seems like image pulls take longer since our last deployment.
For instance, for this context https://gitlab.com/garybell/gitlab/-/tree/242022-bscallout-to-glalert-applications I had to wait more than 5 minutes. To be investigated.

**Comment by markfirmware** [comment]
Is it possible to update a .gitpod.log file in the workspace with events such as workspace-start-initiated and workspace-start-completed? That could be valuable information.

**Comment by svenefftinge** [comment]
We could add this information to the details of the workspace history dashboard.

**Comment by meysholdt** [comment]
it would be awesome if `registry-facade` could log for every URL it downloads from an external source (e.g. hub.docker.com, eu.gcr.eu, us.gcr.io, etc):
* the URL
* the size of the download (e.g. in MB)
* the duration of the download
* the average speed of the download (e.g. in MB/sec).

This would help to
* understand if it's the `registry-facade` itself that's making things slow or if the cause is external
* if some of the external hosts are notoriously slow. For example, our US-workspaces still pull from `eu.gcr.io`.
* how often we pull old (and therefore not pre-fetched) versions of workspace-full.
