### ISSUE TITLE
Is Centos docker image not supported?

### ISSUE THREAD

**Issue by jssfy** [gitpod-io/gitpod#2456]
I changed default docker image to centos:centos7.8.2003, but it failed to start. 
e.g., https://github.com/jssfy/io500

when opening(https://gitpod.io/#https://github.com/jssfy/io500), error looks like below: 
build failed: cannot build workspace image: container exited with non-zero exit code: 1.
Error: build failed: cannot build workspace image: container exited with non-zero exit code: 1

Does any one know about the reason?

**Comment by corneliusludmann** [comment]
Currently, we support debian-like and alpine images only since [we need to add a layer to these images](https://github.com/gitpod-io/gitpod/tree/1cf441ab78ef5d9d23eb5ef31ffaaf5f330da1e5/components/image-builder/workspace-image-layer/gitpod-layer) to be able to run Gitpod. Since Gitpod is open-source, PRs are very welcome to support other distros as well.
