### ISSUE TITLE
My workspace is not starting

### ISSUE THREAD

**Issue by emilyjmaloney** [gitpod-io/gitpod#2525]
### Describe the bug
Error msg rcvd: "Last run 3 minutes ago: cannot initialize workspace: remote content error"
![Workspaces-Gitpod-error](https://user-images.githubusercontent.com/65418787/101991599-de1cb780-3c7b-11eb-88f9-0639a8583e71.png)

**Comment by geropl** [comment]
Just saw the same. `workspaceId`: f704bea2-20a8-4a6f-b40d-8bbd0350d6e1

**Comment by csweichel** [comment]
The underlying issue is that we've lost resilience towards broken snapshots and prebuilds.
[Here](https://github.com/gitpod-io/gitpod/blob/master/components/ws-daemon/pkg/content/initializer.go#L62-L64) and [here](https://github.com/gitpod-io/gitpod/blob/master/components/ws-daemon/pkg/content/initializer.go#L74-L76) we should check if the snapshot/prebuild was not found.
