### ISSUE TITLE
[Self-Hosted] Proxy crashloopbackoff (using hostname, GCP installer)

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#2569]
### Describe the bug
After installing gpsh with a custom domain, I can't access my gitpod installation.

Proxy component is stuck in crashLoopBackOff

Relevant error logs:

```
An unexpected error occurred: There were too many requests of a given type :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/ Please see the logfiles in /var/log/letsencrypt for more details. /nginx.sh: line 55: 117 Killed lama -d /var/www/lama -p 8003 cp: cannot stat '/etc/letsencrypt/archive/as-gitpod.gitpod-self-hosted.com/*.pem': No such file or directory

Starting nginx 2020/12/16 20:45:14 [emerg] 1#1: BIOnewfile("/etc/nginx/certificates/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certificates/fullchain.pem','r') error:2006D080:BIO routines:BIOnewfile:no such file) nginx: [emerg] BIOnewfile("/etc/nginx/certificates/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/certificates/fullchain.pem','r') error:2006D080:BIO routines:BIOnewfile:no such file)
```

/cc @ArthurSens 

### Expected behavior
Gitpod deploys and runs without proxy errors.

### Additional information
Installed Gitpof Self-Hosted following https://www.notion.so/gitpod/GCP-Playgrounds-5b49f9c92e5c42438af73343b98253b1 using `hostname`.

**Comment by meysholdt** [comment]
The error message says "too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/". 
We've seen this error before: 

When installing Gitpod via the installer+domain, our `nginx-proxy` uses a `certbot` to obtain a cert from LetsEncrypt via http-challenge. During a notmal install process, however, the challenge fails at the beginning because the user hasn’t configured the domain to resolve to the right IP because the user gets to know the right IP only at the end of the installation. Thus, the `nginx-proxy` crash-loops for a while, re-trying the challenge. This caused LetsEncrypt to blacklist @Arthur Sens’s IP yesterday due to exceeding their rate limit. Is there a way to postpone the challenge until the domain is configured? Ideas:
a) the proxy could test if a URL can be accessed
b) the proxy could test if the domain resolves to the right IP.
c) use `certmanager` or cloud-provider-managed-certs.
d) Configure Nginx to start even if there are no certs and obtain certs once (a) passes.
However, for (a) I don’t know if there are any URLs that respond *before* the nginx-proxy is running.
For (b) I don’t know if the nginx-proxy has an acceptable way to detect what the “correct” IP is, e.g. `kubectl get services`

**Comment by csweichel** [comment]
I reckon option 2 is the way to go. It's quite similar to what certbot does (checks if the DNS has updated during the DNS challenge), and it's straight forward to implement using dig.

**Comment by meysholdt** [comment]
true, it's easy to obtain the IP via `dig`, but how can the `proxy` know if the domain resolves to the "right" IP? I assume that the proxy does not have the permission to run `kubectl get services` and look up the external IP of the proxy-service.

Furthermore, the IP may also be the public IP of a LoadBalancer and I don't see any way how the proxy could ask the LB for it's public IP.

**Comment by bilalshahzad139** [comment]
Team, What workaround do you suggest to avoid this? I am getting this same error "too many registrations for this IP". POD starts with 

`Failed authorization procedure. test.mydomain.com (http-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for test.mydomain.com - check that a DNS record exists for this domain"`

and after some restarts, it shows "too many registrations for this IP". Should I skip proxy during self-hosted installation and let other installation completes, get IP, add DNS/IP mapping & then enable proxy so it doesn't get NXDOMAIN problem?
