### ISSUE TITLE
Moving identities results in dead acounts

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2629]
We had a case where a user

- initially logged into Gitpod using his GitLab account and purchased the personal subscription. 
- later logged into Gitpod using his GitHub account. Usually, this would add the new authorization to an existing account, but since you had no active session with Gitpod, a new user was created. 
- when using the GitLab authorization again with an active Gitpod session, Gitpod moved the GitLab auth from the old account to the new one. 

As a result, we had two accounts, where the old one had the personal subsritpion running, but was unreachable (no associated authorizations)

**Comment by AlexTugarev** [comment]
I'm still puzzled about the expectation in such a case ;-)

As a quick solution to this, we can (try to) move the subscription into the current user's account under the assumption this will be the correct procedure in the most cases. I will sync with @geropl about potential conflicts with subscriptions.

For completeness, there are more issues and options with moving provider identities between accounts. First of, potentially there are other (meaningful) resources to consider, like:
 - workspaces
 - env vars
 - settings (also in storage)
 - [...]
The left over subscription actually shows the surprising moment users might face when this happens under the hood without any notice. Perhaps it'd be of value to explain this sort of steps to user from UX perspective (/cc. @gtsiolis)

My personal view on this: the user should decide on the account. Rather moving identities automatically, we explain the situation if they want to connect with an already connected provider identity and leave them the choice. The extra work for the user to login with the other provider identity first, and unlink, which might even end up in account deletion, will be also a precaution to do it in the right direction.

**Comment by AlexTugarev** [comment]
@geropl provided very helpful insights into a crucial part of this issue, the association with subscriptions. The conclusion was that we should avoid detaching identities from Gitpod accounts for which subscriptions exists.

Also noteworthy, we cannot just replace the current Gitpod account of a user session.

Given that, I'd like to propose to implement a detection of cases where the consolidation of provider identities would lead to the mentioned problems, and then show a proper message to guide users through the resolution. That would message would include a link which would logout the user and forward them to login with the other provider to make sure the current account is the one that is linked in the subscription.

**Comment by gtsiolis** [comment]
Thanks for the ping @AlexTugarev! I see two areas for improvements here let me know if I'm missing something.

**planning**: I've tried to break these down into smaller iterative MVC (minimum viable change) fixes that can implemented independently across different milestones.

### Step 1 (Short-term) - Migrate unreachable accounts

**question**: Unreachable accounts probably have no workspaces at all as these are automatically deleted after 14 days because of the [garbage collection](https://www.gitpod.io/docs/life-of-workspace/#garbage-collection) process, right? At least between the time Fix A and Fix B land in production.

**thought**: This means there's no data to migrate or inform the user about related to workspaces. I also don't think there's need to migrate any data from Usage, Teams, Access Control, or Settings as the user is probably already using the reachable account for these data now. Let alone the possible duplicate emails they could be getting because of the Email Settings in both accounts.

To avoid a) going back and forth, b) individually implementing features within the product that will be used once, c) risk waiting for a response from all users etc, I'd suggest to follow a plan like the following:

1. **Fix A**: Stop moving provider authorizations from any accounts.
2. **Fix B**: When trying to login using the unreachable account, inform the user that this email is now associated with another account and prompt the user to try to login using another provider.
3. **Fix C**: Migrate the subscriptions to the reachable accounts.
4. **Fix D**: Send an email to the primary email of the reachable account with the following points:
    1. Inform about the successful subscription restoration. We could also provide a free month of the ultimate plan as a small compensation because of this issue.
    2. Inform them that we are going to securely delete the unreachable account that now contains no workspace data but only user data within the Settings like environment variables and allow them to reach out within a 30 day period if they need a raw export of these data (JSON, CSV).
5. **Fix E**: Delete all unreachable accounts.

### Step 2 (Long-term) - Mitigate such cases in the future

I think long term we should consider adding an improved sign-up flow to mitigate such cases. Providing as much awareness and feedback as possible in the UI when a user lands in gitpod.io manually or using a context URL can help guide, inform, and enable the user. This could include the following features that can be broken down into even smaller pieces for implementation:

1. **Allow users to manage providers connections.** Provide a way in the UI to allow users to a) see connected authorized providers, b) disconnect existing secondary provider authorizations, and c) connect new ones regardless the primary email they use fo each provider.
2. **Introduce dedicated sign-up and login pages**. This could include a) having a separate and distinctly different page for account creation (sign up) and account login or b) only a single dedicated login page for all cases.
    - Both of these pages could include a secondary action link to move between these two pages.
    - The login page could have an indicator for the last used provider. We could store this in browser's local storage so that it remains even after the expiration of our session (see screenshot below).

| Login page | Login page with last used provider indicator |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/104741607-1e2afa80-5752-11eb-9257-0428d4d11580.png) | ![image](https://user-images.githubusercontent.com/120486/104741673-313dca80-5752-11eb-8126-a26e3f6b4d2e.png) |
