### ISSUE TITLE
Live reload instead of opening a new browser tab

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2631]
I run my dev server on port 1234, which is set to open-browser in .gitpod.yml.

Every time I rebuild my server, it spawns a new tab. When I use tools like ibazel, this can spawn a LOT of new browser tabs. Can we get a live reload feature instead? I'd like it to open a new tab if one doesn't exist yet, and reload the tab if it's already been created.

**Comment by svenefftinge** [comment]
There are many ways to get live-reload support. Usually, this is built into the dev server's (e.g. webpack) which is why I'd prefer to avoid building a special one for Gitpod. There are also generic ones that you could try.
I like `browser-sync` a lot. https://browsersync.io/

Let us know (and share your project, please) if you need help with setting things up.
