### ISSUE TITLE
Allow adding a git provider for a GitLab instance using a relative URL

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2637]
### Describe the bug

GitLab allows configuring a relative URL for the GitLab instance, see [relevant docs](https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-a-relative-url-for-gitlab).

However, you can not add a git provider within Gitpod for a GitLab instance using a relative URL.

### Steps to reproduce

1. Go to [`/settings`](https://gitpod.io/settings/).
1. Try adding a git provider for a GitLab instance.
1. Use a relative URL for the provider's host name. For example, `example.com/gitlab`.

### Expected behavior

Successfully add a git provider for a GitLab instance.

**Comment by AlexTugarev** [comment]
@geropl this is interesting.

Is there a possibility/probability to have example.com/gitlab1 and example.com/gitlab2 to be present, and if so, which OAuth2 Application are used then? Is everything namespaced then?

As of now, it's enforced to be a valid host name, which disallows additional paths in the configuration. I don't see any problems in relaxing this. 

On the other hand, when we need to decide on the Auth Provider (or user's identity) to pick a token for access, which happens to be the process call of `git` and the invoked credential helper, it's not obvious which one to pick. The reason is simple: `git` will ask for credentials for the `example.com` host in both cases. We already have the means of reading the URL from process arguments, which could be used to check for the path as well.

It sounds possible, though it requires to revise all components dealing with Auth host names.

**Comment by AlexTugarev** [comment]
@gtsiolis, perhaps you know of any installation I could use for testing? 🤔

**Comment by gtsiolis** [comment]
@AlexTugarev I don't know any but we could try setting up a testing environment in our playground project.
