### ISSUE TITLE
Unable to push changes from an old re-opened issue

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#2656]
### Describe the bug

I started a Gitpod workspace from an old re-opened issue. When I tried to push the changes to GitHub, I got the following error message: `Request push failed with message: The repository has been updated since you last pulled. Try pulling before pushing.`
I tried to rebase but it didn't help.
When I started Gitpod from the project and created a branch manually, everything worked fine. I'm reporting this, as it might be a common bug for old re-opened issue.

Thanks a lot @nisarhassan12 for helping to investigate 

Screenshot:
<img width="1362" alt="Bildschirmfoto 2021-01-04 um 15 31 06" src="https://user-images.githubusercontent.com/46345125/103547493-c1535880-4ea4-11eb-9c26-38ab279a81c3.png">

**Comment by nisarhassan12** [comment]
I have re-opened this issue for testing https://github.com/gitpod-io/website/issues/889

**Comment by nisarhassan12** [comment]
I have tested this again just to confirm and I can still reproduce this.

I can also verify that pulling the latest changes via rebasing on top of the latest master does not help.

**Comment by svenefftinge** [comment]
I cannot reproduce this with a fresh workspace. Did you maybe restart and old workspace? In that case you'd need to do `git pull` or fetch and rebase. I might have missed something but it sounds like normal git behavior.

**Comment by nisarhassan12** [comment]
@svenefftinge Thanks for having a look. I can still reproduce this and the workspace is not old it was created tomorrow and rebasing does not help:

![image](https://user-images.githubusercontent.com/46004116/103608219-a502fa80-4f3c-11eb-84c4-c710ca5ee4ab.png)

The workspace id is: `a0a5c247-4d89-40a6-a08e-65e7be3ce6e4`

I re-tried once more via starting a new workspace from https://gitpod.io/#https://github.com/gitpod-io/website/issues/889 and did `git log` which showed me the latest commit but it did not work. 

![image](https://user-images.githubusercontent.com/46004116/103608363-00cd8380-4f3d-11eb-87e0-06eb90d340ce.png)

**Comment by svenefftinge** [comment]
What did you do in order to get the error message?

For me it worked as expected. 
 - clicked the link above to start a WS, 
 - made some changes
 - committed them and
 - pressed the cloud symbol in the status bar

**Comment by nisarhassan12** [comment]
> What did you do in order to get the error message?
 
- Made a commit.
- Tried pushing it via the publish button in the PR tab in the top right corner:
![image](https://user-images.githubusercontent.com/46004116/103626500-17d09d80-4f5e-11eb-9606-d7c14ba7b2ac.png)

- also tried the cloud icon but it does not seem to work and gave the exact same error. 
![Peek 2021-01-05 14-01](https://user-images.githubusercontent.com/46004116/103626890-a9400f80-4f5e-11eb-80fd-295e035d417c.gif)

**Comment by jankeromnes** [comment]
Thanks @nisarhassan12 for reproducing this issue live during our 1:1.

### Summary of the problem

When you open an issue in Gitpod, Gitpod creates a new branch for this issue (based on your username, the issue title and issue number).

However, if that same branch already exists in the upstream repo, Gitpod doesn't detect it, and will fail to push your work (because the upstream branch contains something different than what you have in your workspace).

### Expected behavior

You would like Gitpod to detect when the new branch name already exists upstream, and pick a different branch name to avoid conflicts (e.g. by adding a suffix like `-2` like so: `nisarhassan12/bug-twitter-share-889-2`).

### Workarounds

You can manually sync your workspace with what the upstream branch has by running `git pull --rebase origin nisarhassan12/bug-twitter-share-889`

Or, alternatively you can delete the existing branch `nisarhassan12/bug-twitter-share-889` in the origin repo, e.g. if you no longer need it (then Gitpod will be able to create it again from your new workspace).
