### ISSUE TITLE
impossible to start Gitpod on specified branch

### ISSUE THREAD

**Issue by uaru** [gitpod-io/gitpod#2670]
### Describe the bug

It is impossible to start Gitpod on specified branch in bitbucket.org

### Steps to reproduce

in the browser, according to the manual https://www.gitpod.io/docs/context-urls/#branch-context

https://gitpod.io/#https://bitbucket.org/[my account]/[my project]/-/tree/develop

I tried different things after -/:
develop
branch/develop

It always starts on master

### Expected behavior

start Gitpod on develop branch

**Comment by AlexTugarev** [comment]
Hi @uaru!

Sorry for the late reply to that. I first thought this was a gap in the context parser for BitBucket, but it turns out this is a misunderstanding of the docs.

The `-/tree` URLs are specific to _GitLab_ repositories, as shown in the example in the docs.

The branch URLs of BitBucket repositories do look a bit different, e.g.
https://bitbucket.org/AlexTugarev2/repo/branch/foobranch

@uaru, please confirm, that you can start workspaces on a specific branch 🙏🏻 

Also, we might need to improve the docs to include more examples of different context URLs, as such differences are confusing. Maybe some sort of tabbed code snippets for different Git Providers.

**Comment by uaru** [comment]
Hello, @AlexTugarev

Thank you very much for your reply. You are right, this was a confusion about how the URLs are built. 

I am not really aware of how gitlab constructs the URLs, so I interpreted -/ as a special code.
That means the reality is less complicated than I thought.

I fully agree the section of the manual should be expanded, and possibly include the examples of context URLs for different providers.


Again thank you for clarification.

**Comment by AlexTugarev** [comment]
@uaru, I'm glad how this turned out. Happy coding!
