### ISSUE TITLE
Self-Hosted Release Artifacts

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2682]
A self-hosted build/release consists of several different artefacts:
- docker images created during the build
- Helm charts
- Terraform scripts
- Database init scripts
- installer images that make the installation easier

Only the images are consumed by any kind of SH installation. Depending on the installation path and variant different artefacts are required. When installing a Gitpod SH release, we aim for the following:
- Helm should feel like helm, i.e. no faffing with Docker images when the rest of the world uses `helm install`
- the SQL scripts/terraform scripts should be consumable without having to wade through a Git repo and tags, or having to use Docker
- releases should be discoverable, i.e. we would want to use the GitHub release page

In addition to regular releases (e.g. 0.6.0) we also want to be able to install branch builds, albeit without the ease of consumption. Then we'd take the files from the installer image rather than a GitHub release. Branch builds never push to the Helm repository.

As part of this issue we'd change the GPSH release process to also produce a GitHub release that contains the following archives:
- gitpod-terraform-version.tar.gz
- gitpod-helm-version.tar.gz
- gitpod-database-init-version.tar.gz

as well as pointer to the docs and installer images.

**Comment by meysholdt** [comment]
about branch builds:

> Then we'd take the files from the installer image rather than a GitHub release

I know I advocated this yesterday because it's convenient to build in the release job and we already have it. 

On second thought, another option comes to mind: For a "brach" build, point people to the Werft Results page (e.g. https://werft.gitpod-dev.com/job/gitpod-build-master.336) and list gitpod-terraform-version.tar.gz gitpod-helm-version.tar.gz gitpod-database-init-version.tar.gz as additional results. We could do that by having the job upload these files to a public GCP bucket.

**Comment by csweichel** [comment]
The GCP bucket is indeed an option. I'd still vote for the installer image though. It's easier to do (we have it already) and it's even in the docs now.

**Comment by csweichel** [comment]
We could use https://github.com/c4milo/github-release for this

**Comment by geropl** [comment]
Fixed with #https://github.com/gitpod-io/gitpod/pull/3388
