### ISSUE TITLE
How to use project files in gitpod.Dockerfile?

### ISSUE THREAD

**Issue by Otoru** [gitpod-io/gitpod#2685]
I am trying to use gitpod to work with some configuration files that I have versioned, so I need these files to be in specific repositories. For example:

The file `/ workspace/Example/opensips/routing.cfg` needs to be in the path `/etc/opensips/opensips.cfg`.

To do this I am using a dockerfile with an instruction similar to this:

```
RUN sudo ln -s /workspace/Example/opensips/routing.cfg /etc/opensips/opensips.cfg
```

However an error occurs saying that the file `/workspace/Example/opensips/routing.cfg` does not exist.

What am I doing wrong?

**Comment by csweichel** [comment]
The Docker image build at the start of a workspace can use your repository as context, much like a regular Docker build would. Because of that the folder structure during a Docker build is different from what you'd find in a workspace:
| Workspace | Docker Build |
|---|---|
| `/workspace/your-repo` | `.` |
| `/workspace/your-repo/opensips/routing.cfg` | `opensips/routing.cfg` |

You could still create that symlink by creating a dummy file first, something along the lines of. **Note: I haven't tested this, and there's a good chance it might break.**
```
RUN mkdir -p /workspace/Example/opensips && \
    touch /workspace/Example/opensips/routing.cfg && \
    ln -s /workspace/Example/opensips/routing.cfg /etc/opensips/opensips.cfg && \
    rm -r /workspace/Example/opensips
```

Alternatively, you could use the [root access feature](https://www.gitpod.io/docs/feature-preview/#root-access) to create this symlink when the workspace starts, as part of an init task in your `.gitpod.yml`:
```YAML
tasks:
  - init: sudo ln -s /workspace/Example/opensips/routing.cfg /etc/opensips/opensips.cfg
```

**Comment by Otoru** [comment]
Hi @csweichel,

The first proposal didn't work (I don't know if due to OS or opensips).

The task-based approach served me well, thank you very much for your help. I will close this issue.
