### ISSUE TITLE
Update Kubernetes client library

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2689]
We're still sitting on dependency of kubernetes/client-go version 1.15. We should update to at least 1.17, better yet 1.19.

Use https://github.com/gitpod-io/gitpod/blob/master/components/common-go/go-get-kubernetes.sh to update followed by `leeway link`.

This is directly influenced by #2657

**Comment by geropl** [comment]
Note: The move the 1.19 seems to be not very hard, as Gitpod mainly runs when switching to that master version, except one new field: Pod.PodSpec.PodSecurityContext.SeccompProfile

**Comment by corneliusludmann** [comment]
@csweichel Have you done something on this issue yet? I had noticed the other day that Gitpod does not work with `k3s` version `v1.20.0+k3s2`. After [community members](https://community.gitpod.io/t/readiness-probe-failed/2451?u=corneliusludmann) stumbled upon this as well, I took a look. It turns out that Gitpod does not work with Kubernetes 1.20 because the Kubernetes go client library needs to be updated. To verify this, I updated the client library to version v0.20.1 (1.20) (see [`4f884be`](https://github.com/gitpod-io/gitpod/commit/4f884beccf5928423a8634cf67d8f2760330d2ee) / [`clu/gitpod-k3s-v1-20`](https://github.com/gitpod-io/gitpod/tree/clu/gitpod-k3s-v1-20)—quick and dirty change, some places need probably be improved). With this change, Gitpod runs on Kubernetes 1.20 / latest `k3s` and our GCP dev-preview runs as well (at least workspaces start).

**Comment by csweichel** [comment]
@corneliusludmann did you use [`go-get-kubernetes.sh`](https://github.com/gitpod-io/gitpod/blob/4710fa0b106b23e26d3d214a0b53a6bd9aa68174/components/common-go/go-get-kubernetes.sh#L1) and `leeway link` or manually replace stuff in the `go.mod`s?

**Comment by corneliusludmann** [comment]
I used `go-get-kubernetes.sh` and `leeway link`.
