### ISSUE TITLE
Failed to start frontend application: DomException: The quota has been exceeded.

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#2712]
### Describe the bug
Workspace start hangs in (3/3), console shows:
![image](https://user-images.githubusercontent.com/32448529/104017739-f3bcc880-51b8-11eb-8470-440fffe2d923.png)

I was able to resolve this by:
- Preferences -> Privacy & Security -> Cookies & Site data -> Manage Data...
 - filter by gitpod-dev.com -> "delete all shown"
 - restart Firefox

Interestingly, each "Manage Data..." showed between 48-300KB per sub-domain (preview env). In Firefox local storage is shared per base-domain: https://bugzilla.mozilla.org/show_bug.cgi?id=1064466

I got the same error for production (gitpod.io) a few days earlier. There we should not have that much variation, but still a lot of workspace cookies which add up in Firefox (despite being on a subdomain). I also noted that the layout we store there was quite large (368KB), but I delete the file.

### Steps to reproduce
Not sure, try to fill up the local storage 

### Expected behavior
Frontend should start fine.

**Comment by akosyakov** [comment]
I could not reproduce it. I tried following:
- create one workspace and run in the dev tools console:
```js
var n10b =    '0123456789';
var n100b =   repeat(n10b, 10);
var n1kib =   repeat(n100b, 10);
var n10kib =  repeat(n1kib, 10);
var n100kib = repeat(n10kib, 10);
var n1mib =   repeat(n100kib, 10);
function repeat(string, count) {
    var array = [];
    while (count--) {
        array.push(string);
    }
    return array.join('');
}
```
- then do localStorage.setItem("first-workspace-1", n1mib) with different keys unique for this workspace till you hit the exception, i hit around 10Mb
  - to compute size:
```js
var _lsTotal=0,_xLen,_x;for(_x in localStorage){ if(!localStorage.hasOwnProperty(_x)){continue;} _xLen= ((localStorage[_x].length + _x.length)* 2);_lsTotal+=_xLen; console.log(_x.substr(0,50)+" = "+ (_xLen/1024).toFixed(2)+" KB")};console.log("Total = " + (_lsTotal / 1024).toFixed(2) + " KB");
```
- after reload though the application started and i got a notification to clean up the local storage:
<img width="763" alt="Screenshot 2021-01-11 at 14 12 15" src="https://user-images.githubusercontent.com/3082655/104187292-e0f3ff00-5417-11eb-8802-4687a63dfc48.png">
- then i created another workspace and did over again with the same result

It would be good if someone can share the stack trace of both errors when they happen again.

We can also do preemptive measurements by making sure that the layout info is not stored in the local storage. For Gitpod Theia it does not make sense since we use the DB for it. In this case workspace will always use less than 10K in the local storage.

**Comment by akosyakov** [comment]
It could be also that `the quota has been exceeded` is a follow-up of `Failed to start the frontend application`. But it is hard to tell without logs.

**Comment by geropl** [comment]
@akosyakov Hm, can't reproduce either. I wonder if there whether I upgraded Firefox over the weekend... might be. Now it's 84.0.2. What is your version?

@CyberiumShadow Do you know a way to reproduce the issue?

**Comment by CyberiumShadow** [comment]
> 
> 
> @akosyakov Hm, can't reproduce either. I wonder if there whether I upgraded Firefox over the weekend... might be. Now it's 84.0.2. What is your version?
> 
> @CyberiumShadow Do you know a way to reproduce the issue?

Apologies for the late reply with this,

So far, apart from the initial reproduction on Firefox 84.0.1, I haven't had it come up on Firefox 84.0.2 either as of yet.
Changelog for FF 84.0.2 shows only a security fix.

I'll keep using Gitpod in everyday use and the next time the error pops up I'll try to grab console logs for this issue & check how many "cookies" have been stored for gitpod respectively

**Comment by akosyakov** [comment]
It looks like a FF bug and the fix should be a part of 85 release: https://bugzilla.mozilla.org/show_bug.cgi?id=1683299

**Comment by akosyakov** [comment]
Closing, please reopen if it still happens.
