### ISSUE TITLE
tablet (iPad) support

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#28]

**Comment by jankeromnes** [comment]
See also #311 and https://github.com/theia-ide/theia/issues/3557.

**Comment by jankeromnes** [comment]
Another iPad keyboard problem:

- [ ] `Ctrl` + `C` doesn't work (not a single `Ctrl` command actually)

**Comment by kenneth-reitz** [comment]
Looking forward to this working! You'll be (by far) the best iOS dev solution=D

**Comment by mrpher** [comment]
+1 vote for this, this would be a game-changer. 🤩

**Comment by 6ms** [comment]
I also agree. Gitpod on iPad Pro is almost usable, but for these reasons it is really painful to use currently.

**Comment by jankeromnes** [comment]
Hi @mrpher and @6ms! Many thanks for the feedback! 👍

I would vote for closing this issue, because Gitpod does work well on iPad now! 🎉

There are of course a few things to be improved still, like:
- Apple Pencil support
- Ability to resize panels on touch interfaces
- Ensuring that scrolling works everywhere (including in keybinding settings, markdown previews, and using magic keyboard touchpad)
- Ensuring that copy/paste works everywhere (e.g. in editors and terminals)

@6ms Are there additional problems that break your iPad experience with Gitpod? If so, please list all specific issues you see.

**Comment by gtsiolis** [comment]
> I would vote for closing this issue, ...

Agree. It makes sense to close this and open more specific follow-up issues we can tackle one-by-one. Having a broad and abstract issue like this isn't much helpful. 📕

**Comment by geropl** [comment]
Closing because too unspecific. Gitpod on IPad generalls works now (see above); though it makes sense to track the missing pieces in separate issues.
