### ISSUE TITLE
Workspace

### ISSUE THREAD

**Issue by MaitriManiya** [gitpod-io/gitpod#2829]
I am not able to create a new workshop because I cannot see any such option for a new workshop.

**Comment by jankeromnes** [comment]
Hi @MaitriManiya!

In order to create a new Gitpod workspace, please go to any repository on GitHub, GitLab or Bitbucket, and then edit the URL in your web browser to add this in front:

```
gitpod.io/#
```

For example, if you'd like to edit a project like https://github.com/gitpod-io/website, you'd open something like this in your web browser:

```
gitpod.io/#https://github.com/gitpod-io/website
```

Hope this helps!
