### ISSUE TITLE
Workspace Dockerfile zsh configuration

### ISSUE THREAD

**Issue by sabrehagen** [gitpod-io/gitpod#286]
We have a custom `.zshrc` in our `stemn/development-environment` Dockerfile. When the gitpod docker container is built, our `.zshrc` is overwritten. Appending rather than overwriting might be a viable solution.

Our gitpod dockerfile looks like this:

```Dockerfile
FROM stemn/development-environment:latest

# Give control to gitpod
USER root

# Gitpod configuration
ENV GITPOD_HOME /home/gitpod
ENV GITPOD_UID_GID 33333

# Keep the stemn user configuration
RUN mv $STEMN_HOME $GITPOD_HOME && \
  chown -R $GITPOD_UID_GID:$GITPOD_UID_GID $GITPOD_HOME
```

**Comment by 32leaves** [comment]
Hi,

we don't explicitly overwrite/modify `.zshrc`. We do however copy the content of `/root` to `/home/gitpod` in an attempt to carry over any configuration one might have done as root. In your `stemn/development-environment:latest` there are remnants of the _oh-my-zsh_ installation in `/root` and that's what's overwriting the `.zshrc` from `/stemn/home`.

As a workaround you could remove the `/root/.zshrc` file in your Dockerfile (`RUN rm /root/.zshrc`), or better yet in the Dockerfile for `stemn/development-environment:latest`. I've tried the former and that works well:
<img width="583" alt="screenshot 2019-02-07 at 10 00 36" src="https://user-images.githubusercontent.com/3210701/52400382-479b7000-2abf-11e9-9946-1045c7a28d41.png">


The real issue is though that we overwrite configuration that a user has explicitly put in place (by creating `/home/gitpod`). I'll open an issue for that.

**Comment by sabrehagen** [comment]
Thanks for the explanation - I'll make your change in my code.
