### ISSUE TITLE
Starting gitpod for private Bitbucket repo fails with Error: Forbidden

### ISSUE THREAD

**Issue by aced0** [gitpod-io/gitpod#3003]
### Describe the bug

Trying to start a new gitpod from one of my private Bitbucket  repositories fails:
![image](https://user-images.githubusercontent.com/17823141/105633150-4c49c200-5e57-11eb-8e41-8d8e93e71cb2.png)

No problems for my Github repos and public Bitbucket

### Steps to reproduce
Try to open Bitbucket repository with Gitpod browser extension and with manually adding repo url as context.

### Expected behavior
Open a new Gitpod workspace...

### Additional information
Gitpod access control
![image](https://user-images.githubusercontent.com/17823141/105633375-73ed5a00-5e58-11eb-8af4-15674072f701.png)

### Example repository
-

**Comment by gtsiolis** [comment]
Hey @aced0! I could successfully open a private repository from Bitbucket.org. Are you still seeing this?

**Comment by aced0** [comment]
Yes, here are some additional details and it is related to the fact that I have two Bitbucket accounts (_not_ workspaces, but real accounts with different logins etc.). One personal and one for work.
On my laptop I can open gitpods from private work repositories but not my personal private repositories. On my PC it is via versa, I can open personal private repositories but no private work repositories.

* I did clear the cache
* I did log in the respective bitbucket account first, navigated to the repo and then prefixed it with gitpod.io/#

**Comment by AlexTugarev** [comment]
Hey @aced0!

If you have two separate bitbucket.org accounts, then you likely have two gitpod.io accounts, right?

You need to log out from gitpod.io as well, before you re-login with the other bitbucket.org in order to get into the right gitpod.io account.

BTW, we have a change in the current milestone to make this kind of situation transparent. You should then be able to see, which account you are trying to login with if there is any conflict. 

Other than that, I think it is correct, that bitbucket.org doesn't allow access to private project, or do I miss something?

**Comment by aced0** [comment]
Yes you are right, I missed the fact that the second Gitpod account was automatically created for my second Bitbucket account because I didn't have the intention of doing so. It's kind of obvious thinking about it now. 

But it speaks for the setup and how easy it is. 👍 A better indication is surely a good addition.

Thanks for the support, the ticket can be closed.
