### ISSUE TITLE
CVE-2021-3156

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#3040]
### Describe the bug

Is Gitpod affected by [CVE-2021-3156](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3156)?
Since now `sudo` commands are possible in Gitpod, I didn't know if some code or docker images should be updated.

**Comment by csweichel** [comment]
Thank you for pointing this out.

Gitpod is not affected however, because:
- All services run without `sudo` in their images.
- In the image-builder, i.e. during workspace image builds, users are privileged already.
- In workspaces with feature preview all users can use `sudo` anyways because everyone can bring their own userland (including `/etc/sudoers`).

In the latter two cases, workloads are isolated towards the node using user namespaces.
