### ISSUE TITLE
Error: could not find : chart docker-registry not found in https://kubernetes-charts.storage.googleapis.com/

### ISSUE THREAD

**Issue by Tiller431** [gitpod-io/gitpod#3047]
### Describe the bug
When trying to use the docker image for the latest release. The install fails with the error:
`Save error occurred:  could not find : chart docker-registry not found in https://kubernetes-charts.storage.googleapis.com/
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart docker-registry not found in https://kubernetes-charts.storage.googleapis.com/`

### Steps to reproduce
`$ docker run \
    --privileged \
    --name gitpod \
    --publish 443:443 --publish 80:80 \
    --env DOMAIN=10-0-0-5.ip.mygitpod.com \
    eu.gcr.io/gitpod-core-dev/build/gitpod-k3s`

**Comment by csweichel** [comment]
@corneliusludmann could you have a look please?

**Comment by corneliusludmann** [comment]
@Tiller431 Thanks for reporting. It seems that the Kubernetes charts for installing the internal Docker registry are not reachable at the moment. We had this issue recently internally as well and it suddenly worked again without any change. However, now it seems to be lasting.

The update of the helm charts for the internal registry is already on our roadmap. As it seems to break the self-hosted installation now, I try to prioritize it higher. Sorry, for the inconvenience. :-(

**What you can do know:**
In order to get your installation running, you could install your own registry. Here is a pointer to the docs: https://www.gitpod.io/docs/self-hosted/latest/install/docker-registry/

**Comment by lstkz** [comment]
@corneliusludmann is this fixed? I tried to follow steps from https://www.gitpod.io/docs/self-hosted/latest/install/install-on-aws-script/ but I am getting the same error.

**Comment by geropl** [comment]
This should be fixed with https://github.com/gitpod-io/gitpod/releases/tag/v0.8.0.

@lstkz Those installers are sadly deprecated and not expected to work anymore. :confused: We're planning on updating the docs with https://github.com/gitpod-io/gitpod/issues/3893.
