### ISSUE TITLE
Channel Closed

### ISSUE THREAD

**Issue by TeMp3r126** [gitpod-io/gitpod#306]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Please help all my work is on there!

**Comment by meysholdt** [comment]
Hello! When do you get the error message "Channel Closed"?

**Comment by TeMp3r126** [comment]
Today around 9:15AM

**Comment by meysholdt** [comment]
ok... could you describe what you did before you saw the error message?

**Comment by TeMp3r126** [comment]
I started the IDE but then just kept on the screen starting!

**Comment by DiegoGca** [comment]
Same thing happened to me. I contacted via chat and my workspace files were sent to me by email. I also can create and run new workspaces.

**Comment by TeMp3r126** [comment]
same

**Comment by 32leaves** [comment]
this issue seems to be related to the Docker image builds. As a temporary workaround starting the workspace again seems to work (once the image build is running things are "fine").

**Comment by 32leaves** [comment]
I have restarted some of our servers which were affected by this issue and have been unable to reproduce the problem since. It would seem that there was a dangling connection in a newly introduced part of the system.

We'll put a fix in place to prevent this from happening in the future. I'll post here once this has happened.

**Comment by TeMp3r126** [comment]
Ok, Thanks! Much appreciated!
