### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by Mrfiziee** [gitpod-io/gitpod#3075]

**Comment by gtsiolis** [comment]
Hey @Mrfiziee! The issue tracker is used for tracking bug reports and feature requests, however, based on the information given, it's not clear what this issue is about.

Let's close this, but if you believe this was closed in error, please re-open and include more details in the issue using the issue template when editing the issue description. For example, including a) clear description, b) steps to reproduce, or even c) an example repository can be really helpful.

In the meantime, there are a few resources that you can use to find help and support from the community or even check if there's any ongoing service interruption for Gitpod.io, see:
1. [Community Forum](https://community.gitpod.io/)
1. [Documentation](https://www.gitpod.io/docs/)
1. [Status Page](https://status.gitpod.io/)
