### ISSUE TITLE
cannot read property `endsWith` on undefined

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3076]
I tried to start a workspace on gitlab org by the mistake and got the confusing error message:
<img width="1904" alt="Screenshot 2021-02-02 at 11 24 52" src="https://user-images.githubusercontent.com/3082655/106586971-53ed2300-6549-11eb-8deb-6748f65438a2.png">

**Comment by gtsiolis** [comment]
Thanks for bringing this up @akosyakov! For more clarification, this is about opening a GitLab [Group](https://docs.gitlab.com/ee/user/group/) instead of a GitLab [Project](https://docs.gitlab.com/ee/user/project/). Similarly, we get an error also for GitHub and Bitbucket.

##### Opening a GitLab Group

> We are having trouble parsing your context
> Error: Cannot read property 'endsWith' of undefined

##### Opening a GitHub Organization

> We are having trouble parsing your context
> Error: NotFoundError

##### Opening a Bitbucket Workspace

> We are having trouble parsing your context
> Error: parameter required: 'repo_slug'

---

### Proposal

We could probably handle this error gracefully and inform the user about it explaining they are trying to open a Group, Organization, or Workspace dpending on the case.

**Comment by svenefftinge** [comment]
Checking URLs and trying to figure out what they are pointing at seems pretty involved and doesn't scale. 
Instead, we could tell the user that "<context-url>" is not pointing to a repository, branch, or any other supported context. And point them to docs listing the supported contexts.
