### ISSUE TITLE
Cannot access Gitpod projects - Error: Connection got disposed.

### ISSUE THREAD

**Issue by charliekranz** [gitpod-io/gitpod#3128]

**Comment by jasonford** [comment]
+1

**Comment by gtsiolis** [comment]
Thanks everyone for sending this in, the team is on it. It seems this affects only the EU cluster at the moment. 👀 

Let's keep this issue open to track progress on this issue.

**Comment by cfconor** [comment]
I'm not sure if its possible to get a timeframe on how quickly this could be resolved, or at least temporarily resolved, is there?

I've got a project deadline in 48 hours and I cant even get access to my uncommitted work, I'm very worried about losing potentially days of work here... I know, commit often and all that, but would be awesome if this is a relatively quick fix, so that I can grab my data!

**Comment by JonathanTreffler** [comment]
I think a incident report on https://status.gitpod.io/ with a link to this issue might be a good idea.

**Comment by JonathanTreffler** [comment]
> I'm not sure if its possible to get a timeframe on how quickly this could be resolved, or at least temporarily resolved, is there?
> 
> I've got a project deadline in 48 hours and I cant even get access to my uncommitted work, I'm very worried about losing potentially days of work here... I know, commit often and all that, but would be awesome if this is a relatively quick fix, so that I can grab my data!

I connected to a VPN in America and now it works. So it seems to be possible to circumvent the problem by not using the EU cluster.

**Comment by gtsiolis** [comment]
Closing this as everything seems to be back to normal since yesterday. Thanks everyone! 🤝

**Comment by charliekranz** [comment]
Hi George - it's happening again.

**Comment by gtsiolis** [comment]
Hey @charliekranz! There's a new incident issue in https://github.com/gitpod-io/gitpod/issues/3146. 🏓
