### ISSUE TITLE
Docker gitpodk3s image is broken

### ISSUE THREAD

**Issue by Tiller431** [gitpod-io/gitpod#3139]
The docker image for gitpod is broken. When using the docker run command in the example, it only outputs this and stops:
`DOMAIN:                  127-0-0-1.ip.mygitpod.com
BASEDOMAIN:              127-0-0-1.ip.mygitpod.com
REMOVE_NETWORKPOLICIES: `

Heres the command I used to run it:

`docker run \
    --privileged \
    --name gitpod \
    --publish 443:443 --publish 80:80 \
    --env DOMAIN=127-0-0-1.ip.mygitpod.com \
    --volume $(pwd)/minio-secrets.yaml:/values/minio-secrets.yaml \
    eu.gcr.io/gitpod-core-dev/build/gitpod-k3s`

**Comment by corneliusludmann** [comment]
Thanks for reporting, @Tiller431. Indeed, there is a bug in the `entrypoint.sh` script when there is no Docker DNS on 127.0.0.11. That's usually the case when you use `docker run` instead of `docker-compose`. I fixed this bug in https://github.com/gitpod-io/gitpod/tree/corneliusludmann/docker-gitpodk-3139.

What you can do now:
- You could use `docker-compose` instead of `docker run`.
- You can use the image `eu.gcr.io/gitpod-core-dev/build/gitpod-k3s:corneliusludmann-docker-gitpodk-3139.1` instead of `latest`.

However, there seems to be another problem with the mygitpod.com domain. The mygitpod.com setting is currently not supported (see https://github.com/gitpod-io/gitpod/issues/2684 and https://github.com/gitpod-io/gitpod/issues/2683). Some pods will not come up because the HTTPS cert is missing. That's why you need to configure your own domain and HTTPS certs until we fixed the issues linked above.
