### ISSUE TITLE
Our CDN seems to be blocked in China

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#324]
We got the following feedback from a user:

> Well, currently the case is that, your site is unaccessible without a VPN from shanghai, not sure about other part of China. And the blocking point is just your CDN provider's IP 35.201.89.83 is totally blocked here. Other endpoints are accessible WITHOUT VPN.
> 
> Only static content server are blocked, other endpoints' speed is fine. So my suggestion is that you might consult your CDN provider about the network blocking issue, I think they must be quite experienced with such matter. Could be as simple as changing an IP.

**Comment by meysholdt** [comment]
I've sent a message to our CDN provider.

**Comment by meysholdt** [comment]
Our CDN provider (Google Cloud Platform) says that (1) confirms that the IP is blocked from China and that this is likely caused by networking conditions in China, not Google's services. They also point to their transparency report (2).

1: https://www.comparitech.com/privacy-security-tools/blockedinchina/
2: http://www.google.com/transparencyreport/traffic/

**Comment by MichaelYgZhang** [comment]
If this is the case, do you have any suggestions for Chinese users?I have the same problem.

**Comment by MichaelYgZhang** [comment]
https://cdn.gitpod.io/theia/bundle-06cd929bfae9bc4a6c5842c4c9fe962c.js
This file is not available

**Comment by AlexTugarev** [comment]
Theia is no longer used. Closing as obsolete.
