### ISSUE TITLE
[hints] Adjust hints and tips

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#325]
This keybinding only works on macOS, I am on macOS so I do not know whether Windows/Linux users see the same or not, but giving a non-working hint can be bad.
![screen shot 2019-02-20 at 09 09 49](https://user-images.githubusercontent.com/1405703/53078948-9ef50380-34f5-11e9-9ceb-f4fcb1dbec80.jpg)

Go back: `isOSX ? 'ctrl+-' : isWindows ? 'alt+left' : /*isLinux*/ 'ctrl+alt+-'`
Go forward: `isOSX ? 'ctrl+shift+-' : isWindows ? 'alt+right' : /*isLinux*/ 'ctrl+shift+-'`

https://github.com/theia-ide/theia/blob/234b88961be3b335dc6e567cef057f89a55aecb2/packages/editor/src/browser/editor-keybinding.ts#L26-L39

**Comment by kittaakos** [comment]
And this one is incorrect, we open a new terminal with <kbd>Ctrl</kbd>+<kbd>\`</kbd> on each platform. Long sotry short; `Cmd` should be `Ctrl`.
![screen shot 2019-02-20 at 10 06 01](https://user-images.githubusercontent.com/1405703/53079688-3eff5c80-34f7-11e9-8362-4e57230f3f1b.jpg)

**Comment by jankeromnes** [comment]
To piggy-back on this issue, I think the tips are awesome, but:

I find it really confusing that commands are blue, the color of links (I actually tried to click it):
<img width="558" alt="screenshot 2019-02-20 at 10 10 13" src="https://user-images.githubusercontent.com/599268/53079935-d4025580-34f7-11e9-9f99-faaf89b0f75a.png">

Also, actual links, are white instead (maybe they should be blue, instead of the commands?):
<img width="369" alt="screenshot 2019-02-20 at 10 10 06" src="https://user-images.githubusercontent.com/599268/53079978-eb414300-34f7-11e9-8093-8a316a2a2d2b.png">

And some tips are very long. As a lazy person, I'll never read this:
<img width="913" alt="screenshot 2019-02-20 at 10 09 54" src="https://user-images.githubusercontent.com/599268/53080032-0e6bf280-34f8-11e9-87ea-b6799175adce.png">

**Comment by jankeromnes** [comment]
Additionally, I suggest we add this tip:

> Hold `Option` + `Shift` to select code vertically.

because vertical selection is really cool and useful, and more people could benefit from it.

And maybe the wording of:

> Check [docs.gitpod.io](https://docs.gitpod.io/) to learn what's possible.

could be improved, e.g. with something like "to learn more about what Gitpod can do for you"? Or "to see all the ways to fine-tune your developer experience"?

**Comment by svenefftinge** [comment]
> Hold `Option` + `Shift` to select code vertically.

For me the shortcut moves lines. What operation do you want to highlight?

**Comment by svenefftinge** [comment]
I agree with the blue. But would like to keep the links white, too. To make the messages less noise.

**Comment by jankeromnes** [comment]
> > Hold `Option` + `Shift` to select code vertically.
> 
> For me the shortcut moves lines. What operation do you want to highlight?

Ah, sorry for the ambiguous wording. I meant holding `Option` + `Shift` and clicking to select text (this selects vertically, instead of line-by-line). On a side note, `Option` + `Shift` + `Arrow` is so weird, its goal is to duplicate lines above or below?

**Comment by jankeromnes** [comment]
One more small thing, the magnifying glass looks weird in the prefix-tip URL bar:

<img width="704" alt="screenshot 2019-02-20 at 14 07 12" src="https://user-images.githubusercontent.com/599268/53094790-6831e400-351b-11e9-984f-8edc32f716dd.png">

I initially thought it was placed there by hand (padding on right seems exaggerated, and vertical alignment looks off) but then I realized that it's this way in Chrome's URL bar too.

Still, can we remove it? I feel like the magnifying glass distracts from the prefix, and doesn't add any value.
