### ISSUE TITLE
[root access] mknod /dev/net/tun

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3258]
At the moment we're mounting `/dev/net/tun` from the node into the workspace. This fails on some Linux distributions. Instead we could mknod it as part of the "user ns prep" call to ws-daemon.

**Comment by DentonGentry** [comment]
This would be quite useful for Tailscale, a Mesh VPN: https://tailscale.com
https://github.com/DentonGentry/gitpod

**Comment by fntlnz** [comment]
Alll righty, just made it happen. Here's how I did it:

In a gitpod workspace, open three terminals.

Terminal #1:

```
sudo unshare --user --map-root-user --net
echo $$ > /tmp/pid
```

Terminal #2:

```
sudo slirp4netns --configure --mtu=65520 --disable-host-loopback $(cat /tmp/pid) tap0
```

Now, in terminal #1 you will end up in a situation like this:


```
root@ws-817e44a6-04c1-47d5-a0f2-4432a8c46ee6:/home/gitpod# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
```

From here you can start tailscale just fine, moving everything state to tmp to avoid permissions issues on the mount namespace.

```
tailscaled --socket /tmp/tailscale.sock --state /tmp/tailscaled.state
```

Now in Terminal #3

```
sudo nsenter -t $(cat /tmp/pid) -n tailscale --socket /tmp/tailscale.sock up
```

It will prompt login and everything.


At this point the workspace will be available in your tailscale dashboard

![image](https://user-images.githubusercontent.com/3083633/138577252-8de30d99-6526-4445-8995-4afdb4fc50c5.png)


And, in your namespace.


```
root@ws-817e44a6-04c1-47d5-a0f2-4432a8c46ee6:/workspace/gitpod# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tap0: <BROADCAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether a6:5f:ef:2a:9b:1b brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
       valid_lft forever preferred_lft forever
    inet6 fe80::a45f:efff:fe2a:9b1b/64 scope link 
       valid_lft forever preferred_lft forever
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 100.97.226.73/32 scope global tailscale0
       valid_lft forever preferred_lft forever
    inet6 fd7a:115c:a1e0:ab12:4843:cd96:6261:e249/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::23de:1250:f78:c720/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```


Problem is that now the two interfaces can't be bridged together because gitpod does not allow creating bridges on the root netns

```
sudo ip link add name tailbridge0 type bridge
```

Alternatively to the bridge, the gitpod workspace can also join the tailscale network using userspace networking

```
tailscaled --tun userspace-networking
```

I think that a mix of the two would be a good opportunity, in particular.

- In the Gitpod workspace's root netns, with userspace networking you can expose all the ports to the tailscale network
- In the slirp4netns namespace, with tun networking you can access all the devices in the network without having to use the socks5 proxy you would need to use if you only have the userspace networking solution.

That's all

**Comment by csweichel** [comment]
Fixexd by now using the `experimentalNetwork` flag
