### ISSUE TITLE
Gitpod environment slow to create (15 minutes!)

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#3285]
### Describe the bug
I started a new gitpod workspace, and it took 15 minutes to pull the docker container. It was stuck in that state (2/4) - Pulling docker container for the majority of the time.

And a related question: Do we get billed for creation time as well? What about workspaces getting stuck?

### Steps to reproduce
??

### Expected behavior
This should be fast

### Additional information

![image](https://user-images.githubusercontent.com/2382497/109325153-7271d180-780a-11eb-81e3-2f627ed45b4e.png)

**Comment by svenefftinge** [comment]
Yes, you run into an issue with our way too large `workspace-full` image and how we invalidate docker images for workspaces.

Background: Our workspace-full image is super big, but it doesn't matter if you use the latest one, because we pre-cache that one on all nodes. However, when a project (like yours) is using a custom `.gitpod.dockerfile` that points to `workspace-full` we build a docker image whenever the `.gitpod.Dockerfile` changes. If that hasn't happened in quite some time, the referenced layers from workspace-full are old and not cached on the node. So they need to be pulled.

**A workaround** is to add a change to your `.gitpod.Dockerfile` from time to time. E.g. bumping a variable or so. This will invalidate the cache and a new docker image is being built.

But, of course, this is something on our side to solve.

**Comment by Michaelhobo** [comment]
Thanks for the context. I guess I haven't changed it for a while, until last week.
