### ISSUE TITLE
[ws-manager] Remove PLIS and replace with finalizer

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3335]
ws-manager currently sports a "pod lifecycle independent state" (PLIS), which is basically a configMap used to maintain workspace state beyond the workspace pod's lifetime. We introduced this PLIS so that we can create the workspace content backup once the workspace pod is gone, so as to avoid concurrent modification issues during the backup. This PLIS has introduced significant complexity in ws-manager, and has introduced several state-related issues in the past. Hence, we'd be all too happy to see it go. 

What we built using the PLIS has a Kubernetes-native equivalent: the [finalizer](https://book.kubebuilder.io/reference/using-finalizers.html). Now that @aledbf introduced ws-manager to the controller framework, using a finalizer is much closer to home.

As part of this issue, we will:
- orchestrate the workspace disposal (including content backup) using a finalizer
- update the status machinery to properly extract that status
- remove all things PLIS from ws-manager

**Comment by geropl** [comment]
I'm really keen on anything that tackles `PLIS`. But I'm a bit worried about finalizers, but only because we only experience with them is when they are blocking Namespace-deletion in a very nasty way.
So my worry is twofold:
 - if using a finalizer really that much easier in terms of code complexity; especially compared to some sort of local (persisted) state
 - it creates more problems by further entangling with Kubernetes (with low benefit), which can be nastier when doing OPs stuff (like today: just delete those pods does not work because of broken finalizers blocking it)

**Comment by geropl** [comment]
Ok, yesterday I learned from Chris that finalizers are merely a marker that prolongs a pod's existence, and everyone adding a Finalizer is repsonsible for acting and updating indenpendently. So no central registration+API calls involved.

That means I'm in! :upside_down_face:
