### ISSUE TITLE
[Dashboard] Plans Page

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3358]
The Subscriptions page in the new dashboard needs to be implemented. We will only reimplment a UI for the current model. Remodeling payment is out of scope. 

We will need the same functionality that is currently available under https://gitpod.io/subscription/. I.e. the buttons changedepending on the state of the user. Please refer to the old code, because it doesn't get more detailed than that.

@gtsiolis we will need a possibility (button) to open the "billing", i.e. the chargebee pop-up where users can manage their credit card details, etc.

### Designs 

| Plans |
|-|
| ![image](https://user-images.githubusercontent.com/120486/112122796-4d823b80-8bc9-11eb-859c-e376ec4e06dc.png) |

| Hover | Professional OSS |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112123132-a651d400-8bc9-11eb-90e4-3fd14cf8a650.png) | ![image](https://user-images.githubusercontent.com/120486/112123158-ace04b80-8bc9-11eb-8a59-c849f257ab98.png) |

| Upgrade | Downgrade (Hover) | Downgrade (Modal) |
|-|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112126919-963bf380-8bcd-11eb-84a6-be2b0a5208ab.png) | ![image](https://user-images.githubusercontent.com/120486/112123282-cc777400-8bc9-11eb-843c-56e9acb301ac.png) | ![image](https://user-images.githubusercontent.com/120486/112126929-99cf7a80-8bcd-11eb-8fac-a217ab515b6a.png) |

See also [design specs](https://www.figma.com/file/9phVO5xziEca2VBiZuEbsf/Plans-3358?node-id=0%3A1).

**Comment by jankeromnes** [comment]
@gtsiolis Minor heads up: In the current https://gitpod.io/subscription/ page, we sometimes replace "plan cards" under special conditions:

- If the user has **Professional Open Source** status, the **Free** plan card is replaced with Pro OSS (unlimited hours), regardless if the user is on a paid subscription or not (e.g. if the user has a Personal plan but is also Pro OSS, the Free card will show Pro OSS plan, but the Personal plan card will be selected)
- If the user was created a long time ago, their **Free** plan still has 100 hours instead of 50
- If the user still has an old plan (called **Basic**) this replaces the **Personal** plan card
- If the user was added to a Team Plan, the Team Plan membership replaces the **Professional** or **Unlimited** plan card (but without a button because you cannot manage that Team Plan)

I'm planning to keep the same behavior for now. 🚀

**Comment by gtsiolis** [comment]
> I'm planning to keep the same behavior for now.

The perfect strategy! 🏀
