### ISSUE TITLE
Containerized Flask app with self signed certificated

### ISSUE THREAD

**Issue by lioramilbaum** [gitpod-io/gitpod#3364]
### Describe the bug
The workspace is spinning a containerized flask application. The certbot service is providing a self signed certificate for localhost on port 8443.
Browsing to - https://8443-xxx.gitpod.io is returning:
`400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx`
### Steps to reproduce
Spin a workspace from the repo listed bellow

### Example repository
https://github.com/larisafaingold/zapata

**Comment by jankeromnes** [comment]
Hi @lioramilbaum!

Unfortunately, exposing HTTPS servers from a Gitpod workspace to the outside world is not supported yet -- only HTTP servers can be exposed (and are then encapsulated behind a Gitpod-authenticated HTTPS proxy).

Potential solutions here:

- Disable HTTPS in your Flask app in order to serve HTTP (in order to let Gitpod expose your HTTP server via its HTTPS proxy)
- Use your HTTPS Flask app only locally (for example, only with `curl https://localhost:8443` in a workspace Terminal -- but unfortunately, Previews won't work)
- Open a feature request (i.e. a new issue, or we could also re-purpose this issue) for Gitpod's workspace port proxy to also support HTTPS servers in additional to HTTP servers

**Comment by lioramilbaum** [comment]
@jankeromnes Thank you for the elaborate answer. I am still using my host for spinning local dev environments. This is a good solution for now.
I will continue watching this issue in case this request is implemented.
