### ISSUE TITLE
Store Gradle Build/Dependency Cache in /workspace

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#337]
We need this because:
* only `/workspace` is currently persisted during workspace-restarts
* `/workspace` can be initialised by pre-builds. This could (and should!) warm up the Gradle caches.
* `/workspace` is mounted onto an SSD-drive and therefore has faster IO than other folders.

The maven-config introduced in https://github.com/gitpod-io/gitpod/issues/232 seems to have no impact on the [Gradle Build Cache](https://docs.gradle.org/current/userguide/build_cache.html) and the [Gradle Dependency Cache](https://docs.gradle.org/current/userguide/dependency_cache.html).

**Comment by meysholdt** [comment]
Possible solutions:
a) configure [Gradle Home](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home) to be `/workspace/.gradle`
b) `ln -s /workspace/gradle-caches /home/gitpod/.gradle/caches`

**Comment by dclong** [comment]
Is it better to persist the home directory as well?

**Comment by meysholdt** [comment]
yes, that would be better and hopefully we can have it soon. But until then, storing Gradle Home in `/workspace/.gradle` is I think the best option we have.

 I see you've filed #340 for this.

**Comment by jankeromnes** [comment]
> a) configure [Gradle Home](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home) to be `/workspace/.gradle`

That could indeed work. But we'll have to do similar fixes for all tools that store important things in `$HOME`.

> b) `ln -s /workspace/gradle-caches /home/gitpod/.gradle/caches`

While that might technically work, I don't like it because it relies what I consider a bug in our workspace backup: Instead of properly saving and restoring symbolic links as is, we blindly follow them and try to save everything we can find. This has previously lead to broken backups, because projects like Chromium sometimes [create circular symlinks](https://github.com/gitpod-io/definitely-gp/commit/8f54378f5c370e8bbb555f6b664eb36d910d9ae1#diff-cdc228f94ce4a45c13eec3dad76ae05d).

And if we fix that backup behavior, then we wouldn't actually save `$HOME/.gradle/caches` but simply restore a symlink to an empty (or worse, non-existent) directory.

> Is it better to persist the home directory as well?

I agree that this would be a more generic fix for any tool that saves important stuff under `$HOME`, but it could also create other problems (see my reply to #340 about `~/.bashrc` changes).

**Comment by meysholdt** [comment]
closing, since https://github.com/gitpod-io/workspace-images/pull/61 implements (a).

@jankeromnes regarding your comment to (b), I think there is a misunderstanding. My intention was to make Gradle store the contents of `/home/gitpod/.gradle/caches` under `/workspace/gradle-caches`. My intention was *not* to have our workspace backup follow symlinks to locations outside `/workspace`. 

I strongly assume our workspace backup doesn't follow symlinks but backs them up as symlinks and resorts them as symlinks. If you observe otherwise, that's a bug and we should fix it.
