### ISSUE TITLE
[self-hosted] Run proxy behind TLS terminating AWS Classic ELB (NLB)

### ISSUE THREAD

**Issue by kirooshu** [gitpod-io/gitpod#3417]
Hello folks. I wanted to start this "feature request" as a point of discussion on how to best implement support for NOT terminating TLS in nginx/openresty but allowing the upper proxy layer to do that for us. And the tricky part is when that upper layer is not layer 7 proxy and cannot send the `x-forwarded-proto: https` header. 

I have made 90% of the needed changes and will open some PR for various places in the app where there are assumptions made about how TLS is terminated but I think currently for the self-hosted install script, there is just one setting called `useHttps` which controls both terminating TLS *and* redirecting from http:// to https://. I think the first step will be to split those into different settings so this way we can have the redirect logic without the TLS termination. The way I implemented support right now for our installation is to hack in proxy protocol support in the Nginx proxy configs and turning that feature on at the NLB level (target group).

So, while I did that, there are still places where you do ` template "gitpod.scheme"` and I cannot (for the life of me) figure out how that is being set or is supposed to be modified.

I will link the work-in-progress PRs to this issue for reference.

Thanks

**Comment by JanKoehnlein** [comment]
Thanks for your contribution. We're looking into it.

**Comment by geropl** [comment]
Hi @kirooshu ,

this really is a coincidence as we just spoke about the difference between "TLS termination" and "self referencing scheme (http/https)" today. As it turned out - and you found out yourself already - this is rather crosscutting because
  - all directly-available services are affected
  - we currently have the assumption that the scheme we're _directly called_ with is the one we're _exposed_ with

Due to the effort to change this and as this is not super important for gitpod.io atm we came to the conclusion that we won't do this now.

Nevertheless, it might become interesting once we focus more on Gitpod Self-Hosted. In that vein: Could you share more details about your setup, especially why this is:
> And the tricky part is when that upper layer is not layer 7 proxy and cannot send the x-forwarded-proto: https header.

Thanks!

**Comment by aledbf** [comment]
> And the tricky part is when that upper layer is not layer 7 proxy and cannot send the x-forwarded-proto: https header.

This is not possible if you use NLBs. The only solution for this problem is to use a dedicated server block, listening in a dedicated port that only redirects to HTTPS.

Also, I agree with @geropl about the scope of the change and the priorities.

**Comment by kirooshu** [comment]
Thank you folks. I agree this is kind of specific to being fronted with an NLB. I think I might just set a self signed certificate inside gitpod and let NLB talk to it over TLS which should then workaround this problem for the time being. Thank you.
