### ISSUE TITLE
[tests] not all mocha tests are run

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#3451]
### Bug description

I observed this for mocha tests. When I run tests for a specific component from command line, not all tests in the component are actually run. 

### Steps to reproduce

In a dev environment 
```
yarn --cwd components/server run test
```
I get a few messages on skipped tests and in the end a summary of 0 tests that have passed, even though there are unguarded tests suites e.g. in `src/auth`.

### Expected behavior

All tests should be run

### Example repository

gitpod-io/gitpod

**Comment by geropl** [comment]
We partially fixed this by now: All unit tests are picked up by `yarn test` now.

The tests left(and skipped because of missing credentials) are the ContextParser tests. In the "Automated Test Crew" [we agreed that we should try to make the tests independent of their respective platform](https://www.notion.so/gitpod/Crew-Kick-Off-Automated-Tests-969e916e5add42018469deeea6036e76#5ec7c4e0a34248f69e08e632dfdd9c3b). This would a) make them real unit tests and b) allow us to execute them without the token problem.

**Comment by JanKoehnlein** [comment]
Awesome. Feel free to close this issue
