### ISSUE TITLE
Deprecation of Theia?

### ISSUE THREAD

**Issue by GitMensch** [gitpod-io/gitpod#3475]
> Please make sure to user VS Code integration in Gitpod: https://www.gitpod.io/docs/feature-preview/#default-ide We are planning to make it default since April and deprecate Theia.

_Originally posted by @akosyakov in https://github.com/gitpod-io/gitpod/issues/3470#issuecomment-800886010_

Why?
And did I miss that in the [April 2021 milestone](https://github.com/gitpod-io/gitpod/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22%5Bbacklog%5D+April+2021%22) somehow?

**Comment by svenefftinge** [comment]
We are not deprecating direct support of Theia in April already, because many users rely on that. Instead new users will go with Code by default and existing users will be asked to opt-in to use Code. That said longer term (two months in) we plan to indeed deprecate support of Theia.

> Why?

To provide a great UX we are building a deep integration between the IDE and the Gitpod product. Maintaining such integration for more than one IDE is just too much work on our side atm. Theia is similar to VS Code and the main reason we picked Theia in the first place was to provide a VS Code-like UX to our users. Since VS Code itself now runs well in browsers, we decided to go with the original in order to remove the "like" in vscode-like experience. 

Will such a switch cause issue on your end?

**Comment by GitMensch** [comment]
Thank you for the explanation. I suggest to make that visible by either an extra issue or using this here, likely renamed, pin that and add it to the relevant milestones. Please also adjust https://www.gitpod.io/docs/feature-preview/#default-ide to note this and link to whatever issue this is outlined.

I understand these reasons and (as long as users feel informed about that before it happens) see that to be reasonable, too.

> Will such a switch cause issues on your end?

Not that I know of. It will definitely remove a booster that Theia had, which I had appreciated because of different development and telemetry decisions. It will also lead to more extensions working out of the box and less extensions being tested against Theia.

The only thing that is directly related (I guess it is answered somewhere else already):

* Is there any difference in telemetry between the use of Theia and vscode backend?
* What telemetry is sent to gitpod.io?

**Comment by svenefftinge** [comment]
We haven't sent any telemetry from the IDEs yet. We plan to collect anonymous telemetry in order to better understand where the product needs to improve, but users will be able to opt-out or opt-in, of course.

**Comment by philipreimer** [comment]
Does that mean gitpod will build and integrate its own "distribution of the Code - OSS repository"?
Or will you integrate an existing one like Visual Studio Code or VSCodium?

**Comment by akosyakov** [comment]
> Does that mean gitpod will build and integrate its own "distribution of the Code - OSS repository"?
Or will you integrate an existing one like Visual Studio Code or VSCodium?

We are building based on OSS repository: https://github.com/gitpod-io/vscode/tree/gp-code

**Comment by akosyakov** [comment]
Theia was deprecated in last release and going to be removed in next: https://github.com/gitpod-io/gitpod/issues/4630 Please switch to VS Code.
