### ISSUE TITLE
[Incident] US cluster was unstable again throughout the weekend

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#3515]
### Bug description

Attempting to log into Gitpod via Github results in either 504 or the page stuck on loading. Tried clearing cache, different browsers etc. 

### Steps to reproduce

1. Clear cache, cookies and all site data
2. Go to https://www.gitpod.io
3. Click on Login
4. Click on Github
5. Log into Github
6. Redirect is stuck

### Expected behavior

Able to launch workspaces

**Comment by kevinadhiguna** [comment]
I am facing an exactly same situation. Here is the logs and network tabs : 

![1](https://user-images.githubusercontent.com/43397636/111857376-98027e80-8963-11eb-85f8-164f63bb3f5f.png)

Nevertheless, what I wonder is [status.gitpod.io]() says all services are operational : 

![2](https://user-images.githubusercontent.com/43397636/111857392-b9636a80-8963-11eb-90e4-81d8401b0f66.png)

Any help will be appreciated, thanks!

**Comment by amymaldonado** [comment]
also experiencing the same

**Comment by kevinadhiguna** [comment]
It is working now, thanks..

**Comment by kunxin-chor** [comment]
It's still not working for myself. I cannot retrieve any workspaces, and attempt to login again results in **no** login buttons showing up:
![image](https://user-images.githubusercontent.com/14900791/111858702-db65e880-8975-11eb-98ac-b4a2b86732a7.png)

**Comment by bigint** [comment]
Same, this is happening for me too!

**Comment by kunxin-chor** [comment]
And now it's back to yesterday's issues where returning to https://www.gitpod.io results in a blank page.

**Comment by kevinadhiguna** [comment]
Again, it's not working..

![image](https://user-images.githubusercontent.com/43397636/111864496-c8621100-8993-11eb-9080-0320efc229a0.png)

**Comment by amafjarkasi** [comment]
Still not working - none of the extensions or anything else are loading up

**Comment by jankeromnes** [comment]
Hi all. We are deeply sorry that, following https://github.com/gitpod-io/gitpod/issues/3499 and its mitigation, the US cluster relapsed over the weekend, offering on-and-off service until Monday morning western Europe time (where most of our small team is located). This is not acceptable, and we should do better.

The service is now fully operational again, and the team is focused on better understanding and permanently resolving several underlying issues that happened since Friday's deployment.

In parallel to that, we will step our our reliability and incident response processes, in particular by:

- reiterating the importance of communicating incidents & responses (in issues, the community forum, twitter, and [status.gitpod.io](https://status.gitpod.io))
- improving our monitoring and alerting in light of this weekend's issues
- accelerating our plans toward implementing a dedicated 24/7 on-call ops rotation, so as to more effectively catch incidents outside (western Europe) working hours

**Comment by kunxin-chor** [comment]
And it's down again.

**Comment by warriorBrian** [comment]
@jankeromnes 
I think the problem remains, report:
Sorry, something went wrong 😓
Error: Connection got disposed.
