### ISSUE TITLE
The number of queues in messagebus sometimes explodes and then plateaus 

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3558]
![image](https://user-images.githubusercontent.com/239422/112175633-b2548a80-8bf7-11eb-9186-40702e9327ad.png)

**Comment by ArthurSens** [comment]
Do not explain a sudden spike yet, but watching closely since the last deployment (2h from now), I can see a constant increase. Is it related to load increase on US, since they are starting their day now, or can we assume that we have a leak somewhere?


![image](https://user-images.githubusercontent.com/24193764/112194620-d4dea780-8be7-11eb-8edd-74e241d441c1.png)

**Comment by ArthurSens** [comment]
> Is it related to load increase on US, since they are starting their day now, or can we assume that we have a leak somewhere?

After 12h, the graph suggests that the number of queues increases with load. So far it does not look like a leak
![image](https://user-images.githubusercontent.com/24193764/112304434-3ea89100-8c7c-11eb-9999-478018ce60b1.png)
