### ISSUE TITLE
Consider switching to examples in the new workspace modal for new users

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3606]
### Problem to solve

The New Workspace modal now inludes two tab options, _Recent_ and _Examples_. While the _Recent_ can be quite useful for regular users, new users get an empty list there.

### Proposal

Although we do have an empty state with a primary action button to switch to _Examples_, we could default to Examples for new users or users that have. an empty _Recent_ list.

### Risk

However, this could slightly affect muscle memory for users as the list here could be empty in a different use case scenarios where the users is using a different account, different setup, and etc. ⚠️

**Comment by apolopena** [comment]
Since it is a tab system, defaulting to examples when there are no recents seems worth the muscle memory risk. One less click for a new user to get started is almost always a good thing. Just keep the position of the tabs the same. A nice thing about tabs is that all the choices are prominent and next to each other.
