### ISSUE TITLE
Telepresence VPN-TCP Method Fails

### ISSUE THREAD

**Issue by jrdzha** [gitpod-io/gitpod#3834]
### Bug description

Cannot use `telepresence --method vpn-tcp`

This results in the output:
```
iptables v1.8.4 (legacy): can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

T: The vpn-tcp method requires the use of iptables. If you're running Telepresence in a container, add network capabilities (docker run ... --cap-add=NET_ADMIN --cap-add=NET_BIND_SERVICE ...) or use a privileged container (docker run 
T: ... --privileged ...).

T: Unable to use iptables

T: Exit cleanup in progress
```

### Steps to reproduce

`sudo iptables -L -n` prints out the same bug. This can be tested in the gitpod-io/gitpod repo when launched in gitpod.

Cannot use `telepresence --method vpn-tcp`

This results in the output:
```
iptables v1.8.4 (legacy): can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

T: The vpn-tcp method requires the use of iptables. If you're running Telepresence in a container, add network capabilities (docker run ... --cap-add=NET_ADMIN --cap-add=NET_BIND_SERVICE ...) or use a privileged container (docker run 
T: ... --privileged ...).

T: Unable to use iptables

T: Exit cleanup in progress
```

`sudo iptables -L -n` prints out the same bug. This can be tested in the gitpod-io/gitpod repo when launched in gitpod.

**Comment by csweichel** [comment]
Thank you for brining this up.

There are several things that block telepresence right now:
1. network namespace: telepresence needs plenty of capabilities which it does not have in the workspace's network namespace (which is the network namespace of the actual Kubernetes container). That's one of the reasons one needs to start Docker using `docker-up`, so that we wrap things in a new network namespace.
3. Even within the network namespace there seem to be connection issues which I haven't been able to iron out yet. I suspect they have to do with the way slirp4netns works.
3. FUSE has been an issue until recently. With yesterdays update we also enabled FUSE support in workspaces.

**Comment by jrdzha** [comment]
I see, looks like there are still many challenges to working exclusively in a container. I wonder if using a full VM would have been better than containers in terms of compatibility?
