### ISSUE TITLE
Logs from workspace should have serviceContext

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3835]
in [GCP Error reporting](https://console.cloud.google.com/errors), errors are nicely sorted by component / version. That's unfortunately not true for error log messages from the workspace. Today it's just "gke_instance":
![image](https://user-images.githubusercontent.com/239422/113977121-63873180-9842-11eb-8d65-3684fd0ffe7c.png)

This is easy to achive by adding a [serviceContext](https://cloud.google.com/error-reporting/reference/rest/v1beta1/ServiceContext) to the JSON log message. Example: 
![image](https://user-images.githubusercontent.com/239422/113977990-aac1f200-9843-11eb-9547-5d8ac7d07af4.png)

I propose we introduce contexts that make it easy to distinguish between error froms our code vs. user-uploaded code. 
maybe:
* `supervisor:<gp-version>`
* `ide:<ide-version>` or `vscode:<vscode-version>`
* `vsix-<extname>:<extversion>` or just `user-provided`

**Comment by csweichel** [comment]
All our Go components (including supervisor and workspacekit) come with a `serviceContext` (GKE compatible log format). The same cannot be said for third-party bits, e.g. vs code or any extension. Their log output is pushed directly to stdout, because we don't want to introduce failure modes because of log manipulation.

The GKE specific logging is a problem to boot. Instead of trying to bend all our logging to GKE's will, we should settle on a good (vendor neutral format, e.g. OpenTelementry's format if it comes along/sees more adoption) and make our logging infrastructure work with it - not the other way around.
