### ISSUE TITLE
Deleting an active workspace should behave the same way as deleting a stopped one.

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3879]
### Bug description

**Background**:
When a user deletes a stopped workspace, the workspace is removed right away from the workspace dashboard and this is the desired and expected result especially since workspaces does not have a possible state/status of "Deleting".

**Result:**
This issue is when deleting an active workspace. When deleting an active workspace the status of the workspace changes to "Stopping" for a decent amount of time before disapearing from the dashboard.

This is a new behavior and was not present prior to the first live push of the March 2021 milestone. The workspace use to be removed from the dashboard instantly regardless of the state of the workspace.

### Steps to reproduce

Delete an active workspace.

The workspace is not removed right away and changes to a Status of "Stopping".

### Expected behavior

- The flow of deleting a workspace in the dashboard should be consistent regardless of workspace states/status.
- If a workspace does not have a possible state/status of Deleting then it should be removed from the dashboard right away.

### Example repository

Any

**Comment by gtsiolis** [comment]
Closing this because of the one-line change workaround in https://github.com/gitpod-io/gitpod/pull/4170.  📕 

Some relevant notes for consideration in follow-up issues:
1. The fix in https://github.com/gitpod-io/gitpod/pull/4170 is moving `STOPPING` workspaces to the _All_ list.
2. Pinned workspaces are still visible in the _Active_ list when during deletion time.

Thanks @apolopena for bringing this up and @jankeromnes for the fix! 🏀
