### ISSUE TITLE
[dashboard] New and w/o cxt? Redirect to www.gitpod.io

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3898]
If you go to gitpod.io without any additional context or path and you are not logged-in, you should be redirected to www.gitpod.io.

**Comment by FeixuRuins** [comment]
IMO `gitpod.io` should redirect to `app.gitpod.io` or some other subdomain to clear up possible confusion between the two.

**Comment by svenefftinge** [comment]
The app is the more important place, especially with gitpod and its `gitpod.io/#` prefix. FWIW github and gitlab do it exactly like this as well.

**Comment by AlexTugarev** [comment]
Just one thing to add: it should be `www.gitpod.io` in SaaS context, but `TBD` in self-hosted.

**Comment by AlexTugarev** [comment]
We just agreed on handling this for SaaS for now. 🖖🏻 
Later on we can discuss if and how to solve this for Gitpod Self-Hosted.

**Comment by svenefftinge** [comment]
For self-hosted it can stay as is, i.e. no redirect but the login screen.

**Comment by ghuntley** [comment]
Some data from our community after I made a boo-boo whilst in a tweet:
- https://twitter.com/AnthonyBriggs/status/1382966449795342336?s=19
- https://twitter.com/candeira/status/1382970929437765635

**Comment by ghuntley** [comment]
More data:

https://github.com/gitpod-io/website-kumquat/issues/377

### Bug description

The URL https://www.gitpod.io/docs (or any other direct link to documentation) cannot be accessed directly and results in a 500 error.
The workaround is going to any other page (like the homepage), and then click on 'Docs' on the menu.

### Steps to reproduce

Open https://www.gitpod.io/docs in your browser, you'll get a 500 error.
![image](https://user-images.githubusercontent.com/22901/114972137-e6fce000-9e4b-11eb-8821-bbb63b103929.png)


### Expected behavior

I expect to be able to open directly any page in documentation.

### Example repository

_No response_
