### ISSUE TITLE
[self-hosted] Workspace initialisation fails with error on PrepareForUserNS with moby

### ISSUE THREAD

**Issue by pavan-tri** [gitpod-io/gitpod#3909]
### Bug description

When the workspace starts, the ws-daemon/workspace-kit is trying to initialize ring0 and makes a GRPC call PrepareForUserNS. This call times out, leading it to stopping of intialization. WS go into "stopped" state.

nodeRoot was changed to "moby" as per troubleshooting guide for Self-hosted.  

First Observation: Containerd wrapper is having a hardcoded namespace ( k8s.io [Link](https://github.com/gitpod-io/gitpod/blob/1b5341f2c3b337b5f5370700d3e777ed2757d871/components/ws-daemon/pkg/container/containerd.go#L31)) . When I changed the nodeRoot to moby, the underlying containerd runtime is expecting a "moby" name space. This is leading to no Container ID found error messages

Second Observation: Containerd wrapper also expects c.Labels to have map entries like "io.kubernetes.pod.name".  With moby namespace the only map entry available is "com.docker/engine.bundle.path"

### Steps to reproduce

**_Env Details:_**

AWS - EKS 1.16
Ubuntu  18.04 AMI
Containerd: 1.3.3-0ubuntu1~18.04.4

 **_ws-daemon config:_** 

workspaceSizeLimit: "5g"
nodeRoots:
- /var/lib
- /run/containerd/io.containerd.runtime.v1.linux/**moby**

### Expected behavior

WorkSpace should start.

**Comment by ghuntley** [comment]
Howdy @pavan-tri can you please try v0.10.0 and report back? We have put together an EKS guide over at https://www.gitpod.io/docs/self-hosted/latest/installation

**Comment by pavan-tri** [comment]
Thanks for the update. I will keep you posted.

**Comment by stefanstoeckigt** [comment]
I get the same issue with v0.10.0

**Comment by jgallucci32** [comment]
I am currently seeing the same issue with v0.10.0 on RHEL 8 with Docker CE 20.10.7. I understand Docker is not officially supported, but it has been working for over a year with 0.6.0 on both RHEL7 and RHEL8 hosts.

**Comment by jgallucci32** [comment]
I found a workaround for the first issue (hard-coded "k8s.io" namespace). You can change the default with the docker daemon as follows
```
cat << EOF > /etc/docker/daemon.json
{
  "containerd-namespace": "k8s.io"
}
EOF
```
Reboot the host for changes to take effect. This will change the default namespace for all containers to be "k8s.io". This also allows you to use the default nodeRoot in the Helm chart.

**Comment by jgallucci32** [comment]
Regarding the second issue, I see labels for `io.kubernetes.container.name` and `io.kubernetes.pod.name` on the running container, but I do NOT seem them for `io.cri-containerd.kind` which is the third constant in that section of the code for labels.

This seems to be less a containerd issue and more a CRI plugin issue for containerd since `containerd-cri` is required for Gitpod per https://github.com/gitpod-io/gitpod/issues/2691

**Comment by jgallucci32** [comment]
I was able to get `containerd-cri` enabled using an installation of Docker CE. To enable it you must do the following:
1. Enable CRI plugin by modifying `/etc/containerd/config.toml` as follows
```
disabled_plugins = []
```
2. Run `systemctl restart containerd`
3. Verify `cri` plugin is enabled by running `ctr plugins ls | grep cri`
3. Modify `kubelet` to use containerd instead of dockershim (this example is for RKE cluster.yaml)
```yaml
    kubelet:
      extra_args:
        container-runtime: remote
        container-runtime-endpoint: 'unix:///run/containerd/containerd.sock'
      extra_binds:
        - '/var/gitpod:/var/gitpod'
        - '/var/lib/containerd:/var/lib/containerd'
```
NOTE: The `/var/gitpod` binding is required for RKE deployments because kubelet is containerized

I used these two sources as reference coming up with the configuration
https://gianarb.it/blog/kubernetes-1-20-dockershim-in-practice
https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/

**Comment by jgallucci32** [comment]
I think this can be closed out as Moby (i.e. Docker) is not supported because it lacks a CRI interface. There is work in progress in https://github.com/Mirantis/cri-dockerd but it looks like it's limited to only a few K8s 1.21 distributions and not something which could be considered GA at the moment.

The workarounds posted in the comments enable CRI for existing Docker installs as it bypasses the dockershim and uses containerd directly.
