### ISSUE TITLE
remote: Invalid username or password. fatal: Authentication failed for '<repo>.git/'

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3936]
### Bug description

Today, I was working as usual in a few Gitpod (prod) workspaces, when suddenly one of my workspaces gave me a surprising error:

```
$ git push -f origin jx/grant-20h 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gitpod-com/gitpod.git/'
```

- Workspace ID: `cyan-galliform-1f6bep3c`
- Time: I've tried multiple times in the minutes before `2021-04-14T11:14:00.000Z`

I then worked around this problem, by:
- Removing the `[credential]` section from my `~/.gitconfig`
- Manually generating a Personal Access Token (scope `repo`) from https://github.com/settings/tokens
- Renewing my force-push command (login: `jankeromnes`, password: the token)

### Steps to reproduce

1. (not sure)

**Comment by AlexTugarev** [comment]
Hi @jankeromnes! I tried to find anything fishy in the logs, but failed. 

> I was working as usual in a few Gitpod (prod) workspaces

Server logs do show some activity in the above mentioned 15min range. I could see that the websocket connection was established frequently, actually sometimes several times per minute. That could be explained by many workspace starts, or a flaky connection. 

In general, during this period of time, no relevant errors were logged, besides a broken websocket connection, but this cannot be linked to your session due to missing log instructions.

> Workspace ID: cyan-galliform-1f6bep3c

That workspace was running for a while and it's supervisor reconnected to the server every 10 mins (this is a sad thing.) 

The only error for this workspaces seems to be unrelated: `client request body is buffered to a temporary file` `request POST /code-sync/v1/resource/globalState`.

**Comment by jankeromnes** [comment]
Same problem in my workspace https://indigo-chinchilla-5l3ps0op.ws-eu07.gitpod.io/

```
$ git push origin jx/incremental-prebuild-logs 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gitpod-io/gitpod.git/'
```

Haven't "fixed" it and the workspace is still running (for now).

**Comment by AlexTugarev** [comment]
@jankeromnes, I've seen that, too. There was no way how to fix this for the running workspace.

The error logged on JS console might be related:

> GitHub sign in failed:  Error: 5 NOT_FOUND: no token available

**Comment by geropl** [comment]
Closing this issue as it's too old to be sure if it is related to todays problems.
