### ISSUE TITLE
Bring back 'rename workspace' feature

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3946]

**Comment by gtsiolis** [comment]
Thanks for opening this @jankeromnes! Since this feature request is probably be coming from the lack of information clarity and context awareness on previous workspaces list, let's hold this back a bit and keep this open for further discussion.

A good next step would be to first improve the _Workspaces_ list and more specifically the _Context_ column with more useful and clear information following the [initial specs](https://github.com/gitpod-io/gitpod/issues/3426), see https://github.com/gitpod-io/gitpod/issues/3594.

**Comment by tnir** [comment]
Thanks again, @gtsiolis. #3594 looks talking about the second column "Content" to me to date.

This issue seems talking about the first column "Name". I am not sure why a user should see `blue-hamster-7890abcd` **in bold**? (which cannot be changed as discussion here and https://github.com/gitpod-io/gitpod/issues/3727#issuecomment-817467285) To get supported easier???

**Comment by tnir** [comment]
Not sure how many users are using multiple workspaces for a single repo. Only those who use many workspaces for a single repo might need to rename workspace 😁

**Comment by pattacini** [comment]
Actually in the past the `rename workspace` was actually acting on the context @tnir, which is perfectly fine to me.

**Comment by SimpleSimpleAds** [comment]
Not allowing workspaces names can limit the value of Share Workspace Snapshot. Why should I be forced to use another developers naming structure if I am being sent a snapshot of a project?

For reference I am also speaking about the Name in the Context Column.

**Comment by jankeromnes** [comment]
Cross-posting here: 'Rename Workspace' feature revival is now in early design draft. ✏️

https://community.gitpod.io/t/please-let-me-change-workspace-names/3650/7?u=jan

**Comment by tnir** [comment]
Is this still pending? Or developing? This would look like an advantage over GitHub Codespaces to me.

**Comment by SimpleSimpleAds** [comment]
Nothing seems to get updated with these guys. Services go out a lot though. Looking I to new options because the support and stability are questionable.

It's a shame because I fundamentally like the product.

**Comment by Poonam11Dwivedi** [comment]
HI Team , I am not able to find the functionality to rename the workspace name . Also how to delete the wrongly added workspace?
Could anyone please guide me in this?

**Comment by laushinka** [comment]
> HI Team , I am not able to find the functionality to rename the workspace name . Also how to delete the wrongly added workspace? Could anyone please guide me in this?

@Poonam11Dwivedi Hi, you can click on the dropdown on the right-side of the /workspaces page and choose Rename. There is an option to delete there too.

<img width="582" alt="Screenshot 2021-10-05 at 10 57 40" src="https://user-images.githubusercontent.com/8015191/135992942-08dbac2a-3570-4237-8ac8-cb2d1c8c0572.png">
:

**Comment by Poonam11Dwivedi** [comment]
> > HI Team , I am not able to find the functionality to rename the workspace name . Also how to delete the wrongly added workspace? Could anyone please guide me in this?
> 
> @Poonam11Dwivedi Hi, you can click on the dropdown on the right-side of the /workspaces page and choose Rename. There is an option to delete there too.
> 
> <img alt="Screenshot 2021-10-05 at 10 57 40" width="382" src="https://user-images.githubusercontent.com/8015191/135992942-08dbac2a-3570-4237-8ac8-cb2d1c8c0572.png">
> 
> :

Hi

![image](https://user-images.githubusercontent.com/89123188/136011566-419e02e6-9933-4ae1-8c05-05f34c281245.png)
Please find the image for the reference .

Here I am not getting any dropdown to change the workspace name or delete it. Please guide me accordingly

**Comment by laushinka** [comment]
@Poonam11Dwivedi That's not Gitpod but Gitscrum :)

**Comment by Poonam11Dwivedi** [comment]
Could you please guide me the steps for GItscrum?

**Comment by Poonam11Dwivedi** [comment]
> @Poonam11Dwivedi That's not Gitpod but Gitscrum :)

Could you please guide me the steps for GItscrum?

**Comment by Poonam11Dwivedi** [comment]
> @Poonam11Dwivedi That's not Gitpod but Gitscrum :)

Could you please guide me the steps for GItscrum?

**Comment by laushinka** [comment]
@Poonam11Dwivedi We are not Gitscrum so I'm not sure how we can help you here.
