### ISSUE TITLE
Menu entry "About Gitpod" for Theia is missing an image

### ISSUE THREAD

**Issue by kuniss** [gitpod-io/gitpod#3989]
### Bug description

Title says it all.

### Steps to reproduce

Select menu entry Help -> About Gitpod.

### Expected behavior

Image is shown.

### Example repository

Any, I guess.
Else: https://github.com/kuniss/epsilon/

**Comment by kuniss** [comment]
![Bildschirmfoto vom 2021-04-18 11-54-21](https://user-images.githubusercontent.com/1107971/115141568-6a315800-a03d-11eb-973e-27e49f820229.png)

**Comment by AXIM0S** [comment]
> 
> 
> ![Bildschirmfoto vom 2021-04-18 11-54-21](https://user-images.githubusercontent.com/1107971/115141568-6a315800-a03d-11eb-973e-27e49f820229.png)

That image block is expecting `https://gitpod.io/images/gitpod-ddd.svg` but it seems to be missing.
The image path is defined [here](https://github.com/gitpod-io/gitpod/blob/968840da1e4ad8917526dcf0048a958ce786db24/chart/values.yaml#L96)

**Comment by gtsiolis** [comment]
Nice catch @kuniss @AXIM0S! ⚾ 

This has been removed in https://github.com/gitpod-io/gitpod/pull/3295 with the new dashboard changes.

Since we're now defaulting to VS Code for the default IDE (see [relevant product roadmap item](https://www.notion.so/Product-Roadmap-b9b5eac0a15147ac8d2dd25cf0519203#1ddc3df582b14349b9d0ebb194e7af94)) and we're going to phase out Theia and only allow Theia as a custom IDE image (see [relevant product roadmap item](https://www.notion.so/gitpod/Product-Roadmap-b9b5eac0a15147ac8d2dd25cf0519203#92ea462a5450471e8a5f8ef23198754c)), it could make sense to also remove this menu entry altogether. Alternatively, replacing the broken image should also work.

What do you think @akosyakov? /cc @svenefftinge

**Comment by akosyakov** [comment]
We are not going to make changes to Theia. We should either to reintroduce or redirect for images for time being. Or it is not fix and will be resolved when Theia goes aways.

**Comment by kuniss** [comment]
Not be bothered! Not that important...
Just want to mentioned in case it may be important for the Gitpod team.
Just let it go it disappear with Theia going away.
