### ISSUE TITLE
Make Docker-based workflows seamless

### ISSUE THREAD

**Issue by sr229** [gitpod-io/gitpod#4028]
At the moment, we still require our workflows to invoke `docker-up` to even use Docker. This removes some of the benefits of having "less" to set-up on the workflow, since you still need to manually invoke `docker-up` everytime you want to work on a Docker project.

`docker-up` as much as possible should be invoked in the background instead of requiring the user to do it manually, since it doesn't make sense to call it from CLI when you expect Gitpod to do it for you.

**Comment by akosyakov** [comment]
fixed by https://github.com/gitpod-io/gitpod/pull/4018 :) ?

**Comment by csweichel** [comment]
Thank you for bringing this up. Indeed, this is fixed by #4018 which basically makes docker available in every workspace without having to call `docker-up` first. You should see this feature land before the end of next week.

Closing this issue for now. If the aforementioned PR does not solve this issue for you, please reopen.

**Comment by sr229** [comment]
Ran it on a local K3s instance and I can confirm it works! Are you guys speedrunning or what @csweichel? 😄
