### ISSUE TITLE
Svelte Language Tools broken

### ISSUE THREAD

**Issue by jwrunner** [gitpod-io/gitpod#4034]
### Bug description

When starting an example workspace using the SvelteKit example from https://www.gitpod.io/#get-started, I receive two VSCode messages: `Couldn't start client Svelte` and `vscode.languages.registerDocumentSemanticTokensProvider is not a function` 

![image](https://user-images.githubusercontent.com/7559478/115641523-20ab6c00-a2ce-11eb-877c-68094692af9c.png)

The features of the Svelte for VS Code language tools extension don't work as a result.

### Steps to reproduce

Create a new SvelteKit example workspace and watch for the messages in the lower right corner.

### Expected behavior

Svelte for VS Code language tools should work (commands like Format Document inside of a .svelte file)

### Anything else?

If I uninstall Svelte for VS Code (listed currently as v104.9.1) for the project, close the tab (but not the workspace) then re-open the workspace from the dashboard, I notice that Svelte for VS Code is no longer in the "Installed for this project" but is now listed in "Installed for <username>" in the Extensions pane and it works fine. Note that it says v.101.1.1 when going this route.

Not sure if the changes to the extension to support ESM described in https://github.com/sveltejs/language-tools/pull/930 are relevant.

**Comment by mikenikles** [comment]
Hi, thanks for reporting that 🙏 ! I can't reproduce that unfortunately, I'm surprised v.101.1.1 works as it was released on Jul 8, 2020. Looking at the [changelog](https://github.com/sveltejs/language-tools/releases), I see v.104.9.0 added support for ESM configs so that should be ok.

I wonder if there may have been a temporary issue, although I see you reported that a few minutes ago and I tested not long after you opened the issue. Please let me know if you continue to see this issue, I will be back in the morning and re-test again with a few new workspaces on my end to see if I can reproduce it.

**Comment by jwrunner** [comment]
Sorry, I logged in to Gitpod a year ago and so my settings defaulted to Theia and evidently I also had an old version of that extension installed. Consider giving users who haven't logged in recently a notice that they can switch to VS Code if they are defaulted to Theia??
