### ISSUE TITLE
Improve Grant Access rendering on Start Workspace

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4083]
### Bug description

When authorizing GitLab, I used to be redirected automatically.

Now, I just see confusing error messages, and often the proposed action doesn't work.

### Flow 1: Works ✅ 

- Delete GitpodStaging entry from https://gitlab.com/profile/applications if present.
- open a new private browser
- open https://gitpod-staging.com/#https://gitlab.com/AlexTugarev/gp-test
- ensure the onboarding flow works nicely.

---

### Flow 2: Doesn't work well ❌

- Delete GitpodStaging entry from https://gitlab.com/profile/applications if present.
- open a new private browser
- login to https://gitpod-staging.com/login using GitHub Auth
- open https://gitpod-staging.com/#https://gitlab.com/AlexTugarev/gp-test
- ensure the onboarding flow works nicely.

It shows me this error message, which doesn't make sense, because the repository is not private (it's [public](https://gitlab.com/AlexTugarev/gp-test)). However, clicking the button makes it work:

<img width="1440" alt="Screenshot 2021-04-27 at 16 12 15" src="https://user-images.githubusercontent.com/599268/116257244-2b557d80-a774-11eb-9769-33e5d0dfc479.png">

---

### Flow 3: Doesn't work at all ❌ 

- Delete GitpodStaging entry from https://gitlab.com/profile/applications if present.
- Disconnect from GitLab in https://gitpod-staging.com/integrations
- open a new private browser
- login to https://gitpod-staging.com/login using GitHub Auth
- open https://gitpod-staging.com/#https://gitlab.com/AlexTugarev/gp-test
- ensure the onboarding flow works nicely.

It shows me this error screen. Clicking on Authorize opens a GitLab tab, where I can authorize, but then it takes me back to the very same error page (clicking again multiple times always returns to the same error / never opens a workspace):

<img width="1440" alt="Screenshot 2021-04-27 at 16 13 52" src="https://user-images.githubusercontent.com/599268/116257971-cf3f2900-a774-11eb-9368-9b2f2e459aa7.png">

### Expected behavior

All 3 flows should redirect me + do the right thing + open a workspace successfully.

**Comment by AlexTugarev** [comment]
@jankeromnes, thanks for reporting. 

Indeed `Flow 3` is broken. There seems to be no retry in that path, which lets me wonder why the path is different to `Flow 2`.

OTOH, `Flow 2` worked for me. Just double checked. 

Please be careful with private tabs. Depending on the settings of the browser they may just break GH/GL flows in general. It's better to use fresh profiles.

**Comment by jankeromnes** [comment]
Thanks for confirming @AlexTugarev!

Flow 2 doesn't tell you "repository may be private"?

**Comment by AlexTugarev** [comment]
> Flow 2 doesn't tell you "repository may be private"?

@jankeromnes, it does. This message is bogus, because we never handle the case of revoked access properly. If there is a token, but that token doesn't allow reading properties of a repo, we assume it's private 🙈

**Comment by AlexTugarev** [comment]
@jankeromnes the failing Create Workspace retry on `Authorize with gitlab.com` from `Flow 3` should be covered by https://github.com/gitpod-io/gitpod/pull/4105.

Other than that, this issue is mostly about the missing differentiation between "revoked token" and "unauthorized", which is well-known. While this is always visible during testing, as the test cases are written like that, this is not a regular case, right?

We need to solve this class of issues, and by that I mean: make the context parser aware of the differences between "repo not found", "token expired", "token revoked", "unauthorized", etc. to be able to render proper messages.

**Comment by AlexTugarev** [comment]
@jankeromnes, after merging https://github.com/gitpod-io/gitpod/pull/4105, this issue is about to improving of the rendered message in all cases where the authorization is missing. that might be the case due to revoke, or missing permissions for an organization, or you name it. 

I'd suggest to simplify the message for this class of errors for now. once we do detect those details on the backend, we can fine tune the message. 

WDYT?
