### ISSUE TITLE
Gitpod not saving brew packages

### ISSUE THREAD

**Issue by circutrider21** [gitpod-io/gitpod#4085]
### Bug description

Whenever I restart a gitpod container, it makes me reinstall all the brew packages that I have downloaded. Now, this dosen't seem like a big problem until I realized it takes upwards of 30 minutes to compile qemu, one of the packages that I have installed. Going though a 30-minute long process just to restart a container or to go back to my work seems ridiculous.

### Steps to reproduce

Install qemu with the following

````bash
$ brew update && brew install qemu
````

Then close the tab and leave the container for 15 or so minutes, or restart the container

Upon returning, Voila!

No more qemu!

### Expected behavior

Qemu should be there when I restart the container, but to my surprise, it isn't there!

**Comment by jankeromnes** [comment]
Hi @circutrider21, thanks for the useful feedback! 💯

I agree that this 30+ minutes installation process should definitely be properly persisted, and ideally even run ahead-of-time with [prebuilds](https://www.gitpod.io/docs/prebuilds/).

The reason that packages installed with `brew` are not persisted when you call `brew` from your `.gitpod.yml` tasks (or live from your workspace terminal) is that:

1. currently, Gitpod only backs up the contents of the `/workspace` directory for running workspaces (e.g. when you stop and restart, only `/workspace` will be as it was before, while other paths like `/tmp` or `$HOME` will not be kept)

2. `brew` in Gitpod is [currently configured](https://github.com/gitpod-io/workspace-images/blob/409e1707b3cbe6752a894893cd6354fc13d7b8f5/full/Dockerfile#L67-L71) to install packages under `/home/linuxbrew/.linuxbrew/` (I think this is not yet configurable for HomeBrew / LinuxBrew)

Fortunately, there are a few solutions here:

- You could move the `brew update && brew install qemu` into a [custom Dockerfile](https://www.gitpod.io/docs/config-docker/) for your repo. Everything that happens in a Docker build is persisted into an image and cached (the `/workspace` limitation is only for when the workspace is already started).

- We can enable the "Full Workspace Backup" Beta feature for your account. This makes Gitpod save & restore your entire workspace file system between restarts, not just `/workspace`. We're even planning to enable this feature by default soon, but you can have it earlier if you're interested.

**Comment by circutrider21** [comment]
How do you enable the "Full Workspace Backup" Feature?

**Comment by jankeromnes** [comment]
That's something a Gitpod admin can enable for your account upon request.

"Full Workspace Backup" will also become the default system for everyone in Gitpod in a few months.

**Comment by circutrider21** [comment]
Well could you enable it for me, I use my github account as my gitpod account.

**Comment by jankeromnes** [comment]
@circutrider21 Sure, done! ✅

The feature should be enabled for every new or existing workspace that you (re)start from now on (i.e. if you currently have a running workspace, you'll need to restart it -- after committing & pushing your work, just in case).

Please report anything that seems off, or if you'd like the feature disabled again. Thank for beta-testing Gitpod's "Full Workspace Backup"! 👍

**Comment by circutrider21** [comment]
No Problem. With that said, I think that there are no more problems!
Thanks for helping🥇

**Comment by DasSkelett** [comment]
I seem to have encountered basically the same issue, but with apt: I'm installing a few packages, like Redis, Postgres etc., and the installation does happen during the prebuild as I can see the output of apt, but when I start the workspace, the packages are completely gone.

Thanks to this issue I now know that this is "by design" and expected – however this is not documented anywhere. I've searched through the docs several times, I can't find any note anywhere that warns you about this.
Even worse, there is misleading information suggesting otherwise:
> The init task is where you want to do the heavy lifting, things like:
>  - Download & install dependencies

https://www.gitpod.io/docs/config-start-tasks#prebuild-and-new-workspaces

In retrospect I can see that his basically only refers to npm and other packaging tools that keep everything inside the application directory. I'm missing an explicit mention of that, though.

Until the full workspace backup feature is enabled, I think one or more warnings and clarifications should be added to the docs, so other people don't run into this and spend hours figuring out why things aren't installed besides apt clearly running.
