### ISSUE TITLE
Please use a useful workspace name instead of a nonsensical one

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#4129]
I never can figure out what is in a tab without looking at the code. Instead of a nonsensical name like `https://purple-scorpion-d98aj3rj.ws-us04.gitpod.io/` could we have one that hints at the contents?

So for example, if I open up github.com/drud/ddev with GitHub Codespaces I get a URL like this: `https://rfay-drud-ddev-479f.github.dev/` - it indicates that it's owned by rfay, and is drud/ddev at 479f. Nice.  Thanks! Solves several other name-related complaints here like https://github.com/gitpod-io/gitpod/issues/3908

Thanks for gitpod! It's amazing.

**Comment by csweichel** [comment]
This definitely needs feedback from @svenefftinge; wdyt?

(removing from groundwork until this becomes actionable)

**Comment by svenefftinge** [comment]
I think it's a good improvement. We currently have two name segments followed by 8 characters to make the workspace unique. Since seeing my name as the first segment wouldn't help me to distinguish workspaces, I propose to leave that out.

We can change the name function so that you can optionally pass in two segments that match the regexp `[0-9a-z]{2,16}`. We could include `_` which we use to replace any character that doesn't fit. 

For git-based workspaces we can then generate names using org followed by the repo-name.

**Comment by roboquat** [comment]
@ghuntley: We have more than 20 cards scheduled. Above 15 only scheduler can perform this action. Those are:
  - csweichel
  - JanKoehnlein


<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4129#issuecomment-905187128):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by atduarte** [comment]
Related with #898

**Comment by rfay** [comment]
To me this is still really important. I think you could add a little information to the URL and make gitpod hugely more valuable.

**Comment by svenefftinge** [comment]
Thanks for keeping this alive @rfay. You might be right that my hypothesis is not accurate.
I also think your argument regarding disposable dev environments is great. Why would we want to give our dev environments names (e.g. purple scorpion) if they are disposable.

So I'd vote for doing as described in https://github.com/gitpod-io/gitpod/issues/4129#issuecomment-886429830 

cc @jldec

**Comment by loujaybee** [comment]
Thanks for raising @rfay! I've seen some other issues on this topic that I think have the same underlying issue, but with different proposed solutions. So I wanted to throw in a couple alternative / additional solutions / thoughts:

1. When in a browser context, we could also **consider altering or modifying the page title**. https://github.com/gitpod-io/gitpod/issues/6360 this has been discussed before.
2. I've seen **custom and/or alternate favicons** used within CI build tooling for instance. (In the simplest case: red-failed, green-passed). We could consider letting the user pick custom or coloured favicons to assign to their different workspaces to better see (at a glance) their different contexts.
3. Another option is also to better show the context https://github.com/gitpod-io/gitpod/issues/6227 from within the workspace. There's no direct solution suggested there just yet but the problem seems the same. **Showing context from within the workspace** has the disadvantage of requiring you to actually _click_ the workspace before understanding the context but seems like it's similar/the same as having a custom URL. We could look at something similar to: https://github.com/gitpod-io/gitpod/issues/6392. I should also note that from usability we have also seen that users sometimes a hard time finding out how to return to the dashboard, so having some thin top banner/nav with some context and a link back to the dashboard might impact usability quite well here and solve #6227 at the same time. 

**Note:** From a usability session [[1](https://www.notion.so/gitpod/Viswaprasath-53bd0ec553964c0c85205d2028de78a1
)], a user did also raise that they'd like to customise their URL's but the context/problem was a little different, i.e the user wanted to have more static URL's to make sharing them / remembering them more easily.

**Comment by rfay** [comment]
Thanks for this! It's a great step forward.

https://rfay-ddev-ja8v4i6b4t0.ws-us27.gitpod.io/

**Comment by shaal** [comment]
Thank you for getting this fixed! It's great.

I found a bug with repos that contain capital letters (ie. DrupalPod), and found the fix for that was already committed today :)
https://github.com/gitpod-io/gitpod/commit/5550be1eb29c28e932a116d14c61bf96c56d290d

How can we tell when will this fix be deployed to live Gitpod workspaces?

**Comment by JanKoehnlein** [comment]
Next deployment is planned for Tuesday 9am CET

Sent via Superhuman iOS ***@***.***>
