### ISSUE TITLE
Update wording for marketing related notifications in settings

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#4142]
### Bug description

"Marketing" has a quite negative connotation, also it's a very general term and doesn't explain the value of the emails. Instead, we should have more descriptive wording.

Right now we are using "Marketing Notifications -Receive product marketing emails"

Suggestion: "Product notifications - receive emails about products updates and news"

### Steps to reproduce

https://gitpod.io/notifications

**Comment by gtsiolis** [comment]
Good point @ChristinFrohne! Thanks for bringing this up. 💯

**Comment by JohannesLandgraf** [comment]
Would be great if we can fix this in the current cycle 🙌 I couldn't reproduce on the spot, but if we reference 'Marketing Notifications' not only in Settings but also during Sign Up we should change that too

**Comment by gtsiolis** [comment]
Thanks everyone! I've added https://github.com/gitpod-io/gitpod/pull/4232 to resolve this. 🏀 

FYI we've removed that step we had to subscribe to these notifcations during sign up. These continue to be opt-in and a user has to go to [`/notifications`](https://gitpod.io/notifications) to enable them. /cc @JohannesLandgraf

**Comment by ChristinFrohne** [comment]
Thanks! 
Did I understand you correctly that the product/marketing emails are disabled by default and that the users needs to navigate manually to` /notifications` to enable them? I guess this change leads to most people having them disabled. 

Would it be possible to enable product/marketing emails by default or is that legally not possible?

**Comment by gtsiolis** [comment]
> Did I understand you correctly that ...

@ChristinFrohne Yes, that was always the case. Previously we hade an extra step (page) during sign up that offerred the option to subscribe to product (previously known as marketing) updates.

> Would it be possible to enable ...

We could consider this but I'd vote to do it as a next step out side of #4232 as the previous interaction was really close to being a [dark design](https://en.wikipedia.org/wiki/Dark_pattern) pattern because users had a single checkbox and a button below they had to click to continue using Gitpod where usually this pattern is used for accepting terms via a checkbox and clicking a button.

![image](https://user-images.githubusercontent.com/120486/118635737-9971eb00-b7dc-11eb-8337-15adf44f2d00.png)
