### ISSUE TITLE
Support Containerd 1.4.3

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#4171]
When upgrading from containerd 1.2, I notice:

The HostPathMount of ws-daemon fails because /run/containerd/io.containerd.runtime.v1.linux/k8s.io does not exist on the node (the last segment, k8s.io does not exist).
However, there is /run/containerd/io.containerd.runtime.v2.task/k8s.io/ which looks like (judging based on the content) like it’s what we’re looking for. Switch?

After ws-daemon came up, workspaces fail with error `MountVolume.SetUp failed for volume "dev-net-tun" : hostPath type check failed: /dev/net/tun is not a file`

**Comment by cyrilcros** [comment]
@meysholdt I am seeing this as documented in the chart values, maybe make it a default. 
https://github.com/gitpod-io/gitpod/blob/360759883778f3414e5c54fdfc8cae16068a19c9/chart/values.yaml#L407
/dev/net/tun was #3258 and may have been fixed since (?): https://github.com/gitpod-io/gitpod/commit/44a47ef48e5edd0d4b239138fb6ff9fb949c67bd

**Comment by JanKoehnlein** [comment]
@wulfthimm is working on it

**Comment by csweichel** [comment]
`/dev/net/tun` failure is fixed in https://github.com/gitpod-io/gitpod/pull/4596
