### ISSUE TITLE
[Admin] Cannot delete account if team subscription slot is assigned

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#4229]
### Bug description

Account deletion fails if there is a team subscription slot assigned. 

### Steps to reproduce

1. Assign a team subscription slot.
2. Try to delete the account of the assignee.
3. See deletion fails with no feedback.

### Expected behavior

Team subscription slot should be made available and deletion should succeed.

**Comment by jankeromnes** [comment]
FYI, I believe the bug is here: https://github.com/gitpod-com/gitpod/blob/a88ddab2ec06167186c6bce9c1fe44469a55bc50/components/server-io/src/user/user-deletion-service.ts#L24-L39 -- deletion code seems to call `this.chargebeeService.cancelSubscription(...)` with a `paymentReference` that is not a valid chargebee subscription ID.

The code doesn't seem to properly handle:
- assigned team plan seat (which creates a "synthetic" subscription with `paymentReference = ''`)
- subscription purchased via GitHub (has a `paymentReference` that starts with `github:`)

**Comment by JanKoehnlein** [comment]
There is not much we can do for subscriptions via GitHub, as their API doesn't allow that. But we should notify the user.

**Comment by JanKoehnlein** [comment]
See 
https://github.com/gitpod-com/gitpod/tree/jk/cancel-team-4229
https://github.com/gitpod-io/gitpod/pull/4501
