### ISSUE TITLE
Prebuilts not triggered from Gitlab on branches

### ISSUE THREAD

**Issue by j0nes2k** [gitpod-io/gitpod#4333]
### Bug description

Gitpod user since some months here. I am hosting my private repository on gitlab.com, and I am experiencing issues that prebuilts for my branches are not running. From what I can see in gitlab, the corresponding webhook is triggered and the input is looking fine.

My .gitpod.yml follows a basic setup:

```
tasks:
  - init: |
      some_prebuild_task.sh
    command: |
      some_frontend_task.sh
```

On my master branch a prebuild is available, however the latest changes to master are already several days old.

### Steps to reproduce

Log file from Gitlab Webhook here:

Request headers:
```
Content-Type: application/json
User-Agent: GitLab/14.0.0-pre
X-Gitlab-Event: Push Hook
X-Gitlab-Token: my-gitlab-token
```

Request Body:
```
{
  "object_kind": "push",
  "event_name": "push",
  "before": "myoldsha",
  "after": "mynewsha",
  "ref": "refs/heads/feature/fix_pip_dependencies",
  "checkout_sha": "dfea055400435d957f1a1bcdd77283cdce48b2ac",
  "message": null,
  "user_id": 98765,
  "user_name": "Jonas Kaufmann",
  "user_username": "j0nes2k",
  "user_email": "",
  "user_avatar": "https://gitlab.com/uploads/-/system/user/avatar/747341/avatar.png",
  "project_id": 12345,
  "project": {
    "id": 12345,
    "name": "awesomecompany",
    "description": "",
    "web_url": "https://gitlab.com/awesomecompany-dev/awesomecompany",
    "avatar_url": null,
    "git_ssh_url": "git@gitlab.com:awesomecompany-dev/awesomecompany.git",
    "git_http_url": "https://gitlab.com/awesomecompany-dev/awesomecompany.git",
    "namespace": "awesomecompany-Dev",
    "visibility_level": 0,
    "path_with_namespace": "awesomecompany-dev/awesomecompany",
    "default_branch": "master",
    "ci_config_path": "",
    "homepage": "https://gitlab.com/awesomecompany-dev/awesomecompany",
    "url": "git@gitlab.com:awesomecompany-dev/awesomecompany.git",
    "ssh_url": "git@gitlab.com:awesomecompany-dev/awesomecompany.git",
    "http_url": "https://gitlab.com/awesomecompany-dev/awesomecompany.git"
  },
  "commits": [
    {
      "id": "mysha",
      "message": "Mymessage\n",
      "title": "Mymessage",
      "timestamp": "2021-05-28T12:27:31+02:00",
      "url": "https://gitlab.com/awesomecompany-dev/awesomecompany/-/commit/my-sha",
      "author": {
        "name": "Jonas Kaufmann",
        "email": "jonas@awesomecompany.com"
      },
      "added": [

      ],
      "modified": [
        "api_app/requirements/dev.txt",
        "api_app/requirements/testing.txt",
        "frontend_app/frontend_app/config.py",
        "frontend_app/requirements/dev.txt",
        "frontend_app/requirements/testing.txt",
        "frontend_app/tests/basetest.py"
      ],
      "removed": [

      ]
    }
  ],
  "total_commits_count": 1,
  "push_options": {
  },
  "repository": {
    "name": "awesomecompany",
    "url": "git@gitlab.com:awesomecompany-dev/awesomecompany.git",
    "description": "",
    "homepage": "https://gitlab.com/awesomecompany-dev/awesomecompany",
    "git_http_url": "https://gitlab.com/awesomecompany-dev/awesomecompany.git",
    "git_ssh_url": "git@gitlab.com:awesomecompany-dev/awesomecompany.git",
    "visibility_level": 0
  }
}
```

Response Headers:
```
Content-Length: 2
Content-Security-Policy: frame-ancestors self https://*.gitpod.io https://gitpod.io
Content-Type: text/html; charset=utf-8
Date: Fri, 28 May 2021 10:27:39 GMT
Etag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
Referrer-Policy: no-referrer-when-downgrade
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Via: 1.1 google
Set-Cookie: GCLB=CLCh38Tc-dGeHA; path=/; HttpOnly
Alt-Svc: clear
Connection: close
```

Response Body:
```
OK
```

### Anything else?

When triggering a prebuild manually via `#prebuild` in the URL, I get the "Prebuild in progress" screen, but without any visible log or output.

**Comment by corneliusludmann** [comment]
Thanks, @j0nes2k, for the report.

What I can see in our logs is that the prebuild fails because it cannot find the tag/branch `feature/fix_pip_dependencies` here:

https://github.com/gitpod-io/gitpod/blob/862e3a27b647a7c9351d06600383dbda369aa763/components/server/src/gitlab/gitlab-context-parser.ts#L211-L213

_([internal log link](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-05-28T10:27:43.127Z;query=%22feature%2Ffix_pip_dependencies%22%0Atimestamp%3D%222021-05-28T10:27:43.127Z%22%0AinsertId%3D%221lfp43dg153lcy5%22;timeRange=2021-05-28T02:40:02.412Z%2F2021-05-28T14:40:02.412771Z?project=gitpod-191109) for future access)_

That means for some reason we cannot find the branch with the GitLab API here:

https://github.com/gitpod-io/gitpod/blob/862e3a27b647a7c9351d06600383dbda369aa763/components/server/src/gitlab/gitlab-context-parser.ts#L179-L193

We need to debug why this is the case.

Could you do me the favor and confirm that that the branch name `feature/fix_pip_dependencies` is correct (means it exists/existed) and that you are able to open branches like this in Gitpod? I wonder why this piece of code works for opening Gitpod workspaces for this branch but not for running prebuilds … :thinking:

**Comment by j0nes2k** [comment]
Hello @corneliusludmann, 

thank you for looking into this! I have just double-checked and the branch name is indeed correct and also still exists. 

As a sidenote, Gitlab v13.12 was released one week ago: https://about.gitlab.com/releases/2021/05/22/gitlab-13-12-released/
...and Gitlab sends a User-Agent "GitLab/14.0.0-pre". Maybe this could be related.

**Comment by svenefftinge** [comment]
Looking at the [code](https://github.com/gitpod-io/gitpod/blob/862e3a27b647a7c9351d06600383dbda369aa763/components/server/src/gitlab/gitlab-context-parser.ts#L179) it seems, we do only handle single segment branch names (i.e. without `/`) atm.

**Comment by corneliusludmann** [comment]
> Looking at the [code](https://github.com/gitpod-io/gitpod/blob/862e3a27b647a7c9351d06600383dbda369aa763/components/server/src/gitlab/gitlab-context-parser.ts#L179) it seems, we do only handle single segment branch names (i.e. without `/`) atm.

@svenefftinge That's a search term starting with a `^` that finds all branches starting with the first segment (see also [GitLab API docs](https://docs.gitlab.com/ee/api/branches.html)). It's because we don't know what segments of the context URL are part of the branch name and what is the file path.

The strange thing is that we use the same code for opening regular workspaces and it works there.

**Comment by svenefftinge** [comment]
I'll add a test and see if I can make it fail.

**Comment by j0nes2k** [comment]
Do you have any updates on this? As a sidenote, Gitlab v14.0 was recently released with some deprecations: https://about.gitlab.com/blog/2021/06/04/gitlab-moving-to-14-breaking-changes/

**Comment by corneliusludmann** [comment]
@j0nes2k: We figured out that sometimes the parsing of the branch name fails. We think that it's the case when you have a branch name called `prefix/foobar` and you have a lot of branches with the common prefix `prefix/` (e.g. for `feature/` branches).

We improved our branch name parser as well as the logging when the parsing fails. This is expected to be deployed today. After that, I'll have a look in the logs to check whether this fixed it. Until then, I would like to keep the issue open.

**Comment by corneliusludmann** [comment]
Hi @j0nes2k!

We have the changes in production. What I see in the logs is that from time to time a prebuild fails because the GitLab API tells us that the branch does not exist after we got a push hook. It is noticeable that in these cases the number of commits is 0 and the value of the field `after` in the webhook payload is `0000000000000000000000000000000000000000` but should have the commit hash of the latest commit. I try to figure out why GitLab pushes such messages. However, these push events seem to be rather rare.

After all, it looks like GitLab prebuilds work pretty well now. I would like to close this issue now. Please let me know if you observe failing prebuilds and I'll have a look in the logs. The date/time of the push would be helpful then.

**Comment by j0nes2k** [comment]
Hi @corneliusludmann , thank you for the update! I am not sure if the prebuilds are executed every time on my feature branches, however I am sure that on this one a prebuild was not working. Please let me know if you need more information!

Timestamp: Jul 20, 2021 9:21am GMT+0200
Commit SHA: a06f24d7ac1fac1505c4cff27ae7a352d4084ca4

**Comment by corneliusludmann** [comment]
Hi @j0nes2k! That was indeed very helpful. I had a look in the logs and found the problem:

```
workspace timed out after running the headless workspace (01h00m) took longer than 01h00m
```

I currently check what I can do for you. Do your (pre)builds always took that long? Or was it a failed one (for some reason)?

**Comment by j0nes2k** [comment]
Thanks @corneliusludmann for looking into this! This was due to errors during testing, normal prebuilds should not take any longer than 15 min max.

I will continue to monitor this and let you know if I encounter missing prebuilds again.
