### ISSUE TITLE
Failure to pull image for docker container inside workspace

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/gitpod#4336]
### Bug description

When starting a workspace off gitpod-io/gitpod I can no longer start a mysql:5.7 container inside of my workspace. I get the following error

```sh
$ docker run --rm -it -p 23306:3306 -e MYSQL_ROOT_PASSWORD=test -d mysql:5.7
Unable to find image 'mysql:5.7' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 8.8.8.8:53: dial udp 8.8.8.8:53: connect: network is unreachable.
See 'docker run --help'.
```

### Steps to reproduce

1. Start a fresh workspace https://gitpod.io/#https://github.com/gitpod-io/gitpod
2. Try to start a Docker container
    ```sh
    docker run --rm -it -p 23306:3306 -e MYSQL_ROOT_PASSWORD=test -d mysql:5.7
    ```

### Expected behavior

Previously this would start the Docker container and have it run happily in the background.

**Comment by csweichel** [comment]
We have found the reason for this issue and are deploying a fix as we speak. Expect this issue to be resolved before 19:00 CEST

**Comment by asthomasdk** [comment]
Any idea when it will be available for self-hosted?

**Comment by asthomasdk** [comment]
Did this get included in the 0.9.0 release? 
I am still seeing it in the setup I did from the release today.

**Comment by geropl** [comment]
@asthomasdk No, it is not.

That being said, we're working on a 0.10.0 release for next week based on the deployment to gitpod.io we plan for next week.

A short explainer for the long gap:
 - we got a special delay by 2 cycles because of a rebranding of gitpod.io which required some re-work for SH as well
 - Self-Hosted in general has not been our focus lately (but I feel the tides are turning here :upside_down_face: )
 
 /cc @solomonope

**Comment by asthomasdk** [comment]
@geropl Thanks for the update. 
I will wait for the 0.10.0 release and test again.

**Comment by asthomasdk** [comment]
@geropl When can we expect the 0.10.0 release that includes this fix?
