### ISSUE TITLE
Deprecate unsupported `openModes`

### ISSUE THREAD

**Issue by topher200** [gitpod-io/gitpod#4340]
### Bug description

`openMode: 'split-bottom'` is treated as `split-right`. 

### Steps to reproduce

Load https://github.com/csweichel/werft/tree/ee38f5c in Gitpod.

Observe that all three terminal windows are side-by-side:
![image](https://user-images.githubusercontent.com/206988/120043562-2c2f3880-bfda-11eb-8f2a-3bcdc3280508.png)

### Expected behavior

Observe that https://github.com/csweichel/werft/tree/ee38f5c includes these lines in its gitpod.yml:

```
  - init: yarn --cwd pkg/webui
    command: yarn --cwd pkg/webui start
    openMode: split-right
  - command: k3s server --disable-agent
    openMode: split-bottom
```

This means that one terminal pane should be split right and one shot be split bottom. However, both panes appear as if they were opened under the 'split-right'.

### Example repository

https://github.com/csweichel/werft/tree/ee38f5c

### Anything else?

Although this example includes a mix of `split-right` and `split-bottom`, I've observed the issue in a repo that just performs `split-bottom`.

---

Searching around, it doesn't appear that many people have attempted to use the `split-bottom` feature. Perhaps it's always been broken?

![image](https://user-images.githubusercontent.com/206988/120044175-503f4980-bfdb-11eb-9c09-796353a693c8.png)

**Comment by mikenikles** [comment]
Thanks for reporting this @topher200 🙏.

This likely doesn't work because VS Code doesn't support top/bottom terminal splits from what I can tell based on [their docs](https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-splitting). We are working on new documentation to clean things like that up as I imagine this used to work when the default editor was Theia.

I created a demo repo (https://github.com/mikenikles/gitpod-configure-project-test) to experiment with the different values. The result:

![image](https://user-images.githubusercontent.com/788827/120048991-abc30480-bfe6-11eb-8dc6-38789b2c1778.png)

* The first 4 terminals open as separate terminals
* `Tab 1, second` incorrectly shows up as the first terminal
