### ISSUE TITLE
Gitpod should save user's preferred UI layout and preferences across all instances

### ISSUE THREAD

**Issue by sr229** [gitpod-io/gitpod#438]
Gitpod still has a friction when it comes to user preferences. Let's say I want my IDE layout and user settings to be persistent accross every Theia IDE I encounter, and apparently I can't do that because all instances has their own preference store and its ephemeral. 

## Possible use cases

Use cases of this are people who are migrating from desktop editors and wants their settings to be persistent when they enter Gitpod.

**Comment by svenefftinge** [comment]
Please note, that user preferences are stored across all instances and workspace preferences are shared per git repo. So it is the same as with a using e.g. VS Code locally.

UI Layout is not shared or persisted per user, because that often depends on the project. I.e. in some projects I prefer to work with two or more terminals in split mode. In others one is enough. I think this is rather something I want to share with everyone working on that project (to some extend).

But we store the exact layout per workspace instance. So you can close your browser tab and in case you want to come back tomorrow restarting it you'll get the exact same UI layout. This is also the case for workspace snapshots.

**Comment by sr229** [comment]
My only concern is a use case when user might want his layout across all of his projects from his configuration in project X (which seems to be the case for most of my colleagues during our Hackfest, when they want to sport their own IDE layout that they're most comfortable). 

So I believe there is a use case for this kind of customizability @svenefftinge

**Comment by svenefftinge** [comment]
Would be helpful to know what parts specifically they were changing and why. Do you remember?
Such a feature would need to work well with the shared and restored UI layouts described above.

**Comment by sr229** [comment]
@svenefftinge most of them doesn't want Outline view for example, and some want all of those icons in the left pane for a more VSCode-like experience (that includes me), and most of us don't want to reiterate the same change per workspace.

**Comment by justinmoon** [comment]
I want to hide the "open ports" widget at the bottom when the IDE first starts up
![open-ports](https://user-images.githubusercontent.com/4335621/58752965-45e62580-847d-11e9-9ee4-86bd5ed895ce.png)

**Comment by svenefftinge** [comment]
Thanks. Do you want this for yourself or for all users of a certain repository?

**Comment by justinmoon** [comment]
All users of a repository

**Comment by svenefftinge** [comment]
> All users of a repository

Ok, then it is different to what was initially requested in this issue.
We'll need to think a bout a way to describe layouts and also rules on how layouts are enhanced/adjusted through user-specific settings.

**Comment by mahmoudajawad** [comment]
Any update on this?

**Comment by sr229** [comment]
> Any update on this?

CC @svenefftinge, IIRC they're still working on this at the moment.

**Comment by josephflorian365** [comment]
Why is the open ports widget not appearing in the gitpod IDE?
