### ISSUE TITLE
Username does not change on the IDE

### ISSUE THREAD

**Issue by Carlos-Schrodinger** [gitpod-io/gitpod#4390]
### Bug description

Usernames dont get updated if you change them in any of the services supported (Bitbucket, Gitlab and Github).

I recently changed my name from Sylack-Lab to Carlos-Schrodinger, but the IDE's (Only Theia atm since I have not tested on VSCode) still show up as Sylack-Lab.

### Steps to reproduce

Username problem:

1. Create gitpod account with a github account.
2. Change github account
3. Relog into gitpod with the new account username
4. Gitpod will call you your old username in some parts of the code such as extension installation
"Do you want to install for **old username here**"? Even though you have a new username.

### Expected behavior

To show the correct username based on my GitHub data.

### Example repository

Any repository works.

### Anything else?

running Chrome Dev branch

**Comment by gtsiolis** [comment]
Hey @Carlos-Schrodinger, I was able to reproduce this. Thanks for reporting this! 💯 

This happens because we pick up the name during sign up. We're considering of allowing users to change their name from the dashboard (see [`/account`](https://gitpod.io/account)) but I'm not sure if it'd make sense to constantly sync the name from the provider as you can connect multiple providers using different names. Looping in @AlexTugarev in case they have any thoughts on this.

In the meantime, you can use a different name or email per project or for all projects using [environment variables](https://www.gitpod.io/docs/environment-variables).

**Comment by Carlos-Schrodinger** [comment]
> Hey @Carlos-Schrodinger, I was able to reproduce this. Thanks for reporting this! 💯
> 
> This happens because we pick up the name during sign up. We're considering of allowing users to change their name from the dashboard (see [`/account`](https://gitpod.io/account)) but I'm not sure if it'd make sense to constantly sync the name from the provider as you can connect multiple providers using different names. Looping in @AlexTugarev in case they have any thoughts on this.
> 
> In the meantime, you can use a different name or email per project or for all projects using [environment variables](https://www.gitpod.io/docs/environment-variables).

Did not think about that! Thanks for helping :-)

**Comment by AlexTugarev** [comment]
Hi!
I don't think the `User.name` attribute is or shall be updated on login. While that's true for the provider connection and the `Identity` info, we do not touch the `User` representation. 

AFAIU, we're going to make the details on /account editable at some point. And all places needs to be reviewed, where we use `User.identity[0].name` by mistake.

**Comment by Carlos-Schrodinger** [comment]
> Hi!
> I don't think the `User.name` attribute is or shall be updated on login. While that's true for the provider connection and the `Identity` info, we do not touch the `User` representation.
> 
> AFAIU, we're going to make the details on /account editable at some point. And all places needs to be reviewed, where we use `User.identity[0].name` by mistake.

Good to know, thank you!
