### ISSUE TITLE
Inconsistent times for "Pulling container image" stage to finish (15 seconds vs 60 seconds)

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4400]
### Bug description

The stage of "Pulling container image" is usually, by far, the longest part in the process of opening a new workspace.

This repo always loads super-fast as a Gitpod workspace (2 seconds of "Pulling container image")
https://github.com/symfony/demo

This repo is sometimes fast (2 seconds) and sometimes slow (30 seconds or more)
https://github.com/shaal/vite-lit-element-ts-sass

This repo is sometimes fast (15 seconds) and sometimes slow (45 seconds)
https://github.com/shaal/ddev-gitpod

This repo is usually slow (over a minute)
https://github.com/gitpod-io/gitpod
 

Some of these repos do not define any docker image (so I'm assuming it's using Gitpod default docker image), some repos define a custom docker image, and some has additional steps in `.gitpod.dockerfile`

![image](https://user-images.githubusercontent.com/22901/120911381-2cbc7480-c655-11eb-9667-d6f1e4fd1031.png)

### Steps to reproduce

Try opening each of the repos above with a prefix of `gitpod.io/#` in the browser.

### Expected behavior

I wish all workspaces would open as fast as symfony demo opens!

**Comment by svenefftinge** [comment]
As you already suggested, the used docker images as well as the cache state on the workspace's node determine how much needs to be pulled on startup (pulling docker images phase).
 - `workspace-full` is cached on all nodes, so that doesn't need to be pulled
 - custom dockerfiles `FROM workspace-full` should ideally only pull their layers. But it the image wasn't rebuilt (change the dockerfile file) in a while the `workspace-full` layers might be outdated as well and hence need to be pulled.
 - custom images (e.g. the one used in gitpod-io/gitpod) need to be pulled on all nodes.

In any case, you can be lucky and end up on a node that has your image already. The less common the image is the less likely it is, of course.

**Comment by shaal** [comment]
I'm interested in custom dockerfiles `FROM workspace-full`.

After prebuild finished, opening a new workspace for the same repo, would sometimes take 15 seconds (which is nice!) and sometimes take almost a minute (which feels very slow).

No prebuilds or changes to the repo, just recreating new workspace of a repo, and seeing that huge inconsistency.

This is the repo I'm trying to improve the time it takes to open a new workspace. 
I only install a few packages, projector (jetbrain), and ddev (through brew). 
I thought this was just a small addition to workspace-full, and expected it to start a workspace much faster - 
https://gitpod.io/#https://www.github.com/shaal/ddev-gitpod

**Comment by svenefftinge** [comment]
> and seeing that huge inconsistency.

Yes, this difference happens when in one case the image was pulled already and in the other it was not. We (reso. containerd) also have a bug with parallel image pulls which could also cause such a behavior.

The best you can do is make sure you regularly rebuild the image (commit contents changes to `.gitpod.Dockerfile`) and make the added layers as small as possible.

**Comment by shaal** [comment]
Thank you @svenefftinge
Can you explain what you mean by regularly rebuild the image? Causing gitpod to rebuild image would make that process faster? So updating the image once a day? Once a week? 

AFAIK there are very few small packages installed in my `.gitpod.Dockerfile`
What makes the added layers smaller/bigger?

**Comment by geropl** [comment]
> Can you explain what you mean by regularly rebuild the image? Causing gitpod to rebuild image would make that process faster? So updating the image once a day? Once a week?

Once every 1-2 week would indeed work; but "not older than 2 months" is good enough.

Please note that this is a known issue and we're working on multiple fronts to improve things here: newer containerd version being the most important one, but also workspace startup in general.

I'll close the issue here, as this is a known issue we're already working. Please re-open if there's anything unclear.
