### ISSUE TITLE
Php 8.0 support by default

### ISSUE THREAD

**Issue by bigint** [gitpod-io/gitpod#4411]
It would be great if PHP 8.0 is supported by default in Gitpod

**Comment by geropl** [comment]
HI @bigint !

Just to make sure: In Gitpod, you can install [any linux tool](https://www.gitpod.io/docs/config-docker) and any [VSCode extension](https://www.gitpod.io/docs/vscode-extensions) via [configuration file](https://www.gitpod.io/docs/config-gitpod-file).

We already include a lot of tools with the default Docker image `gitpod-io/workspace-full` maintained [here](https://github.com/gitpod-io/workspace-image), but adding everything (and every version!) would be impractical to impossible (thus I will close this issue here).

You can try to raise an issue with https://github.com/gitpod-io/website to add a "[Quickstart PHP](https://www.gitpod.io/docs/quickstart)" section so others can read up about it.
