### ISSUE TITLE
Missing .gitpod.yml format specification

### ISSUE THREAD

**Issue by madoar** [gitpod-io/gitpod#447]
Currently your [website](https://www.gitpod.io/docs/41_Config_Gitpod_File/) is missing a format specification for the `.gitpod.yml` file format.

**Comment by jankeromnes** [comment]
Thanks for filing this issue! I totally agree that we should share the `.gitpod.yml` specification (or schema) somewhere.

We do have a JSON file for it, we just need to find a suitable place for it (ideally, we shouldn't just copy it into the website, because then we might to forget updating it, and risk missing out on valuable contributions).

The first line in it says:

```js
"$id": "https://gitpod.io/gitpod.schema.json",
```

But trying to load https://gitpod.io/gitpod.schema.json doesn't work. Maybe it should return the schema that's currently live?

Or, we create a dedicated repository just for the schema, and reference it both in our code and in our documentation.

**Comment by jankeromnes** [comment]
@madoar I've preliminarily published it under https://github.com/gitpod-io/gitpod-yml-schema.

It's not actually used anywhere yet, but I'd like to make our app use it, and also reference it from the [docs](https://www.gitpod.io/docs/) somehow.

**Comment by madoar** [comment]
Thank you for sharing your json schema! I believe this file may be too specific in some cases. Easier to understand are in my opinion short examples, which explain how different options in the `.gitpod.yml` file can be used. A good example for this is Travis CI, whose [documentation](https://docs.travis-ci.com/) is written like that.

**Comment by jankeromnes** [comment]
Many thanks for the great suggestion!

And I've always wanted to have a list of good `.gitpod.yml` examples (instead of having to regularly dig up specific examples from my memory), so I'll look into making one. :) Such a thing would have been so helpful for writing CircleCI configs!

**Comment by madoar** [comment]
No problem. It's nice to hear that I could give you some inspiration ;)
