### ISSUE TITLE
Workspaces list in dashboard: limit is applied before filtering for active workspaces

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#4488]
My “Active” list in production has running (and starting) workspaces only. No pinned workspaces. No stopped workspaces with changes.

Could it be that the limit of 50 is applied before filtering for active workspaces? When I change to a limit of 200 the pinned workspaces appear (they are pretty old). Even when I switch back to 50, the pinned workspaces are still there. After reload, they are gone again.

**Comment by gtsiolis** [comment]
Aha! Nice catch @corneliusludmann! I could reproduce this with the following steps:
1. Have more than 50 workspaces when filtering _All_ workspaces.
2. Change list size to 100 or 200.
3. Select a workspace below after the first 50 workspaces and pin it.
4. Force reload the workspaces list so that the list size resets to 50 and switched back to _Active_ workspaces.
5. Change list size top 100.
6. Notice a pinned stopped workspace showing up.

**suggestion**: We should probably resolve this with a proper pagination or infinite scrolling in such lists as well as remove the page size option. However, if this is an easy fix let's do that first. 💭
