### ISSUE TITLE
[cli] cred helper reports authentication error on GitLab SH

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4563]
### Bug description

See https://community.gitpod.io/t/gitlab-self-hosted-server-authentication/3947

### Steps to reproduce

Open a repo on a self hosted GitLab installation and perform a git operation.

**Comment by corneliusludmann** [comment]
I'm not able to reproduce this.

What I tried:

1. I started GitLab in a Gitpod repo. → https://gitpod.io/#https://gitlab.com/gitlab-org/gitlab
2. I patched GitLab because it uses `localhost` for the clone URL which obviously does not work when connecting to Gitpod (use `gp url 3000` as URL):
```diff
diff --git a/lib/gitlab/repository_url_builder.rb b/lib/gitlab/repository_url_builder.rb
index ed9a298ee8c..137c18a9cef 100644
--- a/lib/gitlab/repository_url_builder.rb
+++ b/lib/gitlab/repository_url_builder.rb
@@ -21,7 +21,7 @@ def ssh_url(path)
       end
 
       def http_url(path)
-        root = Gitlab::CurrentSettings.custom_http_clone_url_root.presence || Gitlab::Routing.url_helpers.root_url
+        root = "https://3000-aquamarine-lemur-88j2er52.ws-eu10.gitpod.io/"
 
         Gitlab::Utils.append_path(root, "#{path}.git")
       end
```
3. Make port 3000 public.
4. Connect this GitLab installation to Gitpod (Settings → Integration). I used a Gitpod self-hosted installation but production should also work.
5. I started a workspace with the `flightjs/Flight` repo shipped with the GitLab installation.
6. I created a commit and pushed it. The only message I got is that I need to change the permission scopes. After doing it push works as expected.

Since the original reporter in the community forum never provided some details, I'll close this issue. If someone experiences this as well, please feel free to open this issue or ping me.

**Comment by AlexTugarev** [comment]
https://github.com/gitpod-io/gitpod/issues/4563#issuecomment-884229493 impressive!
