### ISSUE TITLE
[dashboard] Horizontal scrollbar in “Changes” dropdown has no effect

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#4570]
When a workspace has changes (e.g. untracked or uncommitted files, unpushed commits), the files are truncated. Therefore, the horizontal scrollbar has no effect.

![image](https://user-images.githubusercontent.com/24960040/122885826-b8195380-d33f-11eb-81b3-4ed2dd7bc59e.png)

There are two options:
1. Hide the horizontal scrollbar.
2. Don't truncate the lines and allow to scroll.

I'm personally in favor of (2) because the truncated file paths make some information inaccessible. E.g. here you don't see which files exactly have been changed:

![image](https://user-images.githubusercontent.com/24960040/122886336-29590680-d340-11eb-8e0b-0f046c729841.png)

/cc @gtsiolis

**Comment by jankeromnes** [comment]
> I'm personally in favor of (2) because the truncated file paths make some information inaccessible. E.g. here you don't see which files exactly have been changed:

Side note: I'm occasionally bitten by the same thing (truncated text not helpful because the relevant part is hidden). So I've recently taken to adding a `title` attribute to all truncated texts I see.

For pending changes for example, you'll notice that hovering over each truncated entry reveals the full path. See also the new `title` attribute in:

https://github.com/gitpod-io/gitpod/blob/caa322c871da45343d997f1c73ad5f1ae86d7245/components/dashboard/src/components/ContextMenu.tsx#L87

**Comment by corneliusludmann** [comment]
Thanks for the addition, @jankeromnes! Generally speaking, I see it the same way. However, when you don't know if the value is truncated or not, the tooltip could be redundant. See discussion in this PR: https://github.com/gitpod-io/gitpod/pull/4416. But still tend to be more in favor of it.
