### ISSUE TITLE
[Self Hosted] PrepareForUserNS: cannot find workspace container

### ISSUE THREAD

**Issue by stefanstoeckigt** [gitpod-io/gitpod#4587]
### Bug description

Gitpod v0.9.0
kubernetes v1.19.9 (kubespray v2.15.1) 
External registry
Kubernetes Node OS: ubuntu 18.04, kernel 5.4
Container Runtime: docker v19.03

### ws-daemon
```json

{
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
    "error": "context deadline exceeded",
    "instanceId": "a3a6cd86-01fe-4e30-953a-e338da4b5d88",
    "level": "error",
    "message": "PrepareForUserNS: cannot find workspace container",
    "serviceContext": {
        "service": "ws-daemon",
        "version": ""
    },
    "severity": "ERROR",
    "time": "2021-06-23T09:02:12Z",
    "userId": "3d4b38f4-793e-4ecc-a489-43b23a366a54",
    "workspaceId": "coffee-clam-pkk2nkx8"
}

```

### Steps to reproduce

This error occurs when starting a workspace.

**Comment by corneliusludmann** [comment]
Hi @stefanstoeckigt!

Thanks for your bug report. Please note, that we currently support a very limited set of platforms only. See https://www.gitpod.io/docs/self-hosted/latest/install/install-on-kubernetes#prerequisites.

Sorry, that I don't have better news for you. Maybe you have luck and other users in our community forum could help you: https://community.gitpod.io/

**Comment by csweichel** [comment]
As already mentioned, unfortunately we do not support Docker as container runtime. Considering docker-shim is deprecated, it's very unlikely that we'll introduce Docker CRI support.

**Comment by jgallucci32** [comment]
@csweichel Can you point me in the right direction where in the code the breaking change was made for docker-shim? Gitpod v0.6.0 runs on Docker CE 20.10.07, but somewhere between that and v0.10.0 it stopped working.

**Comment by jgallucci32** [comment]
I was able to get `containerd-cri` enabled using an installation of Docker CE. To enable it you must do the following:
1. Enable CRI plugin by modifying `/etc/containerd/config.toml` as follows
```
disabled_plugins = []
```
2. Run `systemctl restart containerd`
3. Verify `cri` plugin is enabled by running `ctr plugins ls | grep cri`
3. Modify `kubelet` to use containerd instead of dockershim (this example is for RKE cluster.yaml)
```yaml
    kubelet:
      extra_args:
        container-runtime: remote
        container-runtime-endpoint: 'unix:///run/containerd/containerd.sock'
      extra_binds:
        - '/var/gitpod:/var/gitpod'
        - '/var/lib/containerd:/var/lib/containerd'
```
NOTE: The `/var/gitpod` binding is required for RKE deployments because kubelet is containerized

I used these two sources as reference coming up with the configuration
https://gianarb.it/blog/kubernetes-1-20-dockershim-in-practice
https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/
