### ISSUE TITLE
Expose workspace ports on external IP

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#459]
Currently the model we use for accessing workspace ports is different to 'real' machines our users are used to.

Problems with this approach:
 - limited to `https`
 - a lot of frontends try to connect to backends using the pattern `${window.location.hostname}:${port}`, which does not work with Gitpod (example: https://github.com/gitpod-io/gitpod/issues/435#issuecomment-480750205 f). Only solution: patch the respective code or put proxy in front

A solution would be to expose workspaces under a IP6 address. Then each workspace would be accessible under: <ipv6>:<port>
Optionally, we could add a (customizable) DNS entry for that as well (see #329)

This would allow other usecases:
 - `ssh` access into workspaces to integrate with local environment
 - none-https traffic

**Comment by axonasif** [comment]
See https://gitpod.slack.com/archives/C02EN94AEPL/p1645623283439319

**Comment by atduarte** [comment]
@kylos101 have no idea on how difficult this would be. Do you have any idea?

**Comment by shaal** [comment]
I wanted to propose an idea related to another issue I had opened previously (https://github.com/gitpod-io/gitpod/issues/9376).

When running the `gp validate` command, Gitpod generates a new debug workspace with a `debug-` prefix in the URL.

Would it be feasible for future Gitpod workspace URLs to have `ide-` as a prefix instead? Additionally, if there is a server running in the Gitpod workspace, could the current workspace URL display port 443 by default rather than the IDE?

I believe this would allow for cleaner URL segmentation between debug/IDE workspaces and make it simpler to access any web servers directly. Please let me know if this aligns with Gitpod's roadmap or if any clarification is needed on my proposal. I'm happy to discuss further.
