### ISSUE TITLE
Chrome Canary UI duplicates menu options multiple times

### ISSUE THREAD

**Issue by bvasilchik** [gitpod-io/gitpod#461]
**Describe the bug**
On Mac Osx Mojave using Chrome Canary Version 75.0.3759.0 (Official Build) canary (64-bit)
UI options are being duplicated whenever I hover over them

<img width="1439" alt="Screen Shot 2019-04-09 at 1 21 49 PM" src="https://user-images.githubusercontent.com/10767745/55821355-4db3ca00-5acb-11e9-9475-67fd0bd75c78.png">

**To Reproduce**
load up gitpod on chrome canary and right click on something or try to open and hover over menu options

**Expected behavior**
you shouldn't see the same menu duplicated multiple times

**Comment by akosyakov** [comment]
Which version of Canary? Just tried with `75.0.3760.0 (Official Build) canary (64-bit)` and everything is good.

Although i had generally bad exp with canary, since it is broken sometimes without anything relevant to an opened application. I would advise to use the stable Chrome version if you want to have the best exp.
