### ISSUE TITLE
Restore some of the bottom margin on dashboard pages

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4634]
### Problem to solve

In https://github.com/gitpod-io/gitpod/pull/4417 (cc @corneliusludmann), we've removed the bottom margin on dashboard pages, however, we need to always keep some of the bottom margin (e.g. `mb-16`) to allow long lists _Workspaces_ or sections like _Prefereces_ render without touching the bottom of the viewport on small viewports.

**Comment by corneliusludmann** [comment]
Makes sense.

**Suggestion:** Please document the reason for the bottom margin in the code so that we remember it for future changes.

**Comment by gtsiolis** [comment]
This is still relevant. Adding **meta: never-stale** label.

**Comment by jwpjrdev** [comment]
I might do this sometime. It's been driving me crazy for months.

**Comment by trumbitta** [comment]
Following the line of though of [this comment](https://github.com/gitpod-io/gitpod/pull/4417#issuecomment-860532577) from #4417 ("we should find a proper solution")

And having seen what happens at small resolutions / viewports:

![image](https://user-images.githubusercontent.com/462705/146656205-1a826f5a-7066-4b20-908e-fa7159674480.png)

I think reworking the whole dashboard app with a modern mobile first approach might be resolutive in regards of this and other issues that may and will arise.
The layout will be more robust, resilient, possibly more maintainable and easily extendable because mobile first has the main effect of giving you something that's good on mobile and tablets, and the side effect of giving you something that's good everywhere 😄 . It's not dissimilar from Accessibility in this: both of them make the experience better for everyone.

And hey 🖐️ I can help. I have experience in mobile first, have been advocating for it, building my web apps like this since [2011 when I read the seminal book about it](https://www.lukew.com/resources/mobile_first.asp), and I can work on it together with a Designer (if Gitpod has a Product Designer, this is of course the preferred way!), in a team, or alone.
I've been doing it at my daily jobs for the last 10yrs and it's just how think about web apps.

It's not something we can do overnight in a magic little `size/S` PR, but step by step we can manage to pull it off.

Come find me on discord if you like the idea!

**Comment by gtsiolis** [comment]
Added #7388 to resolve this.

🍊 🍊 🍊 🍊 

@corneliusludmann, following the comment in https://github.com/gitpod-io/gitpod/issues/4634, I've added a point about this in an internal draft I'm writing about design guidelines.

Re-posting from there:

> Every part of a user interface should be intentional including the empty space between elements. The amount of space between items creates relationships and hierarchy.

> Pages should be also intentional about empty space. For example, including some extra margin at the bottom of each page provides better UX when navigating long lists or large sections that reach the bottom of the viewport when scrolling to the end of the lists or sections.
