### ISSUE TITLE
[server] rewrite configuration to use a single config source

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#4650]
currently the server component's config consists of a number of env vars (which might be rendered from secrets) and mounts.

as suggested by @csweichel, it would be best to rewrite the configuration of the server component (perhaps payment as well, as they share some of the configuration,) to use a single source. advantages expected by this change are:
 * make telepresence easier
 * reduce turnarounds when working on changes related to payment or github

**Comment by geropl** [comment]
It turns out the helm chart and parsing interaction in `Env` is rather complicated. To make sure we do not miss any variance we take a 2 step approach:
 1. Introduce new `Config` shape which contains everything from `Env` (minus some basic refactoring and cleanup). This is **not used yet** to make sure we don't break anything, but instead just printed out on startup for reference.
 2. The next step is to ease the process of serializing->deserializing the config from

**Comment by geropl** [comment]
Re-opening as #4882 was only the 1st of 2 PRs.

**Comment by geropl** [comment]
While a biggest chunk has been merged, there are still some ToDos left:
 - [ ] deploy to prod
 - [ ] cleanup gitpod-com
 - [ ] cleanup gitpod-io
