### ISSUE TITLE
[staging] VS Code simple-browser layout is broken in Firefox

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4654]
### Bug description

When you open the VS Code mini-browser in Firefox, its layout appears broken in staging, while it looks fine in production. Also, it looks fine in Chrome in both staging and production, so this is Firefox-specific.

### Staging (broken)

<img width="1440" alt="Screenshot 2021-06-29 at 15 55 06" src="https://user-images.githubusercontent.com/599268/123812316-47040e00-d8f4-11eb-86e0-d39118251362.png">

### Production (works)

<img width="1440" alt="Screenshot 2021-06-29 at 15 54 57" src="https://user-images.githubusercontent.com/599268/123812294-44091d80-d8f4-11eb-83a5-3d1150805db3.png">

### Steps to reproduce

1. Open https://github.com/techwithtim/NEAT-Flappy-Bird in staging

Or,

1. Run `python3 -m http.server 1337` in a staging workspace, then open port `1337` in a preview

**Comment by akosyakov** [comment]
Styles seem to be follow-up, the real issue is that FireFox for some reasons blocks already loaded service worker after the content of webview is loaded. And it break since we use virtual domain `*.vscode-webview.net` to load actual content of webview vai service worker, but bootstrap code of webview including service worker is loaded from workspace origin. There is guard that checks whether service worker is activated before loading content, but FF does not seem to care much. It is not an issue in Codespaces since `vscode-webview.net` belongs to them and they server bootstrap code from there too.

**Comment by akosyakov** [comment]
I think it is a bug in FF, CSP is correct: `*.vscode-webview.net` meaning `vscode-webview.net` and its subdomains. `vscode-remote+rose-mouse-braatohu.ws-eu06.gitpod-staging.com.vscode-resource.vscode-webview.net` should match it, but some reason it is not.

**Comment by akosyakov** [comment]
It works if the parent domain of service worker is matching to the parent domain of webview resources. I will have to hack a bit internals of VS Code Web for it, otherwise they hardcode `vscode-webview.net` which is managed by MS and used to serve webview bootstrap code.

**Comment by akosyakov** [comment]
We decided to rewrite `vscode-webview.net` in the blobserve.

**Comment by csweichel** [comment]
solved in https://github.com/gitpod-io/gitpod/pull/4666
