### ISSUE TITLE
Can not open workspaces with Theia editor

### ISSUE THREAD

**Issue by victormgomezp** [gitpod-io/gitpod#4672]
### Bug description

Is not possible to open the workspaces, this is one project that we always open https://gitpod.io#https://github.com/breatheco-de/exercise-postcard.git

HTTP ERROR 401

### Steps to reproduce

clic here

https://gitpod.io#https://github.com/breatheco-de/exercise-postcard.git

### Expected behavior

Open in gitpod

**Comment by gtsiolis** [comment]
Hey @victormgomezp, I was able to open a new workspace for this repository. Are you still seeing this? 👀

**Comment by victormgomezp** [comment]
Yes we are still needing
All students are claiming


| Victor Manuel Gómez Pérez
| Country Manager Spain
| (+34) 684 33 25 81
| www.4GeeksAcademy.com

**Comment by alesanchezr** [comment]
The problem is when using Theia.
We are having 401 and 502 when I trying to open the workspaces using Theia.

I know the editor will be deprecated by august but we are still running our school on Theia because our exercise engine is built on top of it and we have not finished the migration @svenefftinge @gtsiolis . We are focusing on building this vsplugin and we expect to have it ready by august but we are no there yet.

**Comment by gtsiolis** [comment]
Oh, thanks for clarifying, @alesanchezr! Let me escalate this internally. 🏓

**Comment by akosyakov** [comment]
It should work now, sorry for inconvenience. Please open new issue if not.
