### ISSUE TITLE
Number of team members don't match on the billing

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#4693]
### Bug description

When I go to the [team settings](https://gitpod.io/teams) it says that we have 322 members but we deleted (disabled) some of them and the number should be 192 instead.

I'm afraid the billing will also match the 322 instead of 192.

![Teams-—-Gitpod](https://user-images.githubusercontent.com/426452/124292199-4ef5c500-db23-11eb-8eda-4c7bc337fd5e.png)

### Steps to reproduce

1. go to [team settings](https://gitpod.io/teams)
2. Open the team details
3. count the number of items on the list

### Expected behavior

The number of team members should match the number of items in the list.

**Comment by jankeromnes** [comment]
Hi @alesanchezr! Thank you for reporting this problem. I can confirm that something is not right with your Team Plan. We'll investigate why there is such a discrepancy; fix any underlying bug; and of course refund any undue charges.

**Comment by lechien73** [comment]
Hi @jankeromnes - sorry to pile on, but this made me check our Team Unleashed plan too.

We are showing 1649 members, but I scraped the content of the **Manage Team** modal and ran it through a script, which shows a count of 1336. I've spot checked at different places to ensure that the data is the same as the **Manage Team** modal, and all seems to be correct.

Could you add this to your check too, please? The account email is: gitpodteam@codeinstitute.net.

Thanks

**Comment by jankeromnes** [comment]
Hi @lechien73, thank you for double-checking your team account, which seems to be affected as well.

We're hoping to fix this problem for every (potentially affected) team account today or tomorrow, with the fix going to production shortly thereafter. Will post updates to this issue.

**Comment by lechien73** [comment]
@alesanchezr - I don't know if this is helpful to you, but I've made a Chrome extension that helps manage our teams as they get bigger. It's awaiting review in the extension store at the moment, but you can sideload it from here: https://github.com/lechien73/GitpodTeamHelper

It adds some UI elements so you can see how many active and inactive users you have, and highlights the inactive users so they're easier to find when you are scrolling.

**Comment by jankeromnes** [comment]
Wow, cool, thanks for sharing this @lechien73! (This also clearly shows the limitations of our current Teams UI... 🙈)

By the way, you may be interested in knowing that we're entirely re-vamping Teams in Gitpod. This is not ready yet, but parts of it are already implemented behind a feature flag (we could potentially enable it for you, if you'd like to have a look). See the design specs for Teams and Member management in https://github.com/gitpod-io/gitpod/issues/4421

---

Additionally, I've implemented a fix for the current Teams billing issue: https://github.com/gitpod-io/gitpod/pull/4713

Unfortunately, I can't test it right now (I couldn't get a testing environments with payments enabled), and I'll be off for the rest of the week. @geropl and/or @AlexTugarev, could you please take a look at my Pull Request, and see if you can test it? And if it looks correct to you and works as expected, please merge it so that it can be deployed next week.

**Comment by lechien73** [comment]
@jankeromnes - yes please, I'd like that. When I was perusing the code for Teams, I thought I found stuff there that isn't used yet. With such a large (and growing) team, anything that makes it easier for our Student Care folks to manage is a real gift.

PS: I packaged the extension and it's now in the Chrome Web Store [at this link](https://chrome.google.com/webstore/detail/gitpod-team-admin/pcecmmchknbagjicnbkfifajblnbbhlj).

**Comment by geropl** [comment]
Was auto-closed with the PR. Re-opening as there is still some stuff to sort-out, mainly re-funding for wrong invoices!

**Comment by jankeromnes** [comment]
The fix is now deployed to production:

- The number of seats displayed in the overview of https://gitpod.io/teams should always match the number of seats visible in the Manage Members modal (e.g. "5 Members" / 5 seats -- note: the count includes deactivated seats)

- Performing at least one seat operation (adding a seat, deactivating a seat, reactivating a seat) should fix / correctly set the quantity visible in Billing (e.g. "Team Professional (EUR) x 4" -- note: this excludes deactivated seats, because they won't be part of your next bill)

- We are now backprocessing data in order to identify all affected team plans and issue refunds

Thanks again for reporting this embarrassing bug and for bearing with us through the fix! 🙏

---

And on a side note, if you'd like to play with our new (experimental, not-ready-yet) Teams & Projects UI, please ping me and I'll enable the flag for your account. (Same process for leaving the experiment again and waiting for it to be ready.) As a reminder, the new Teams UI is totally decoupled from the current Team Plans -- i.e. you'll need to manage both independently, and you can't cause side effects from one to the other. @lechien73 I'll enable this on your account since you asked. 🙂

**Comment by alesanchezr** [comment]
@lechien73 your extension is amazing, thanks for that!! I'm building a `Gtipod/VSCode Extension` for practicing code if you want to try it. We are in the process of migrating from Theia to VSCode but you can try it already if you open it with Theia, here is a sample: https://github.com/breatheco-de/python-flask-api-tutorial

@jankeromnes Thank you! We don't mind bugs like this when such a great team and product is always there for us. 😄

**Comment by jankeromnes** [comment]
The fix was deployed on July 13th and we've successfully issued refunds where applicable, so this issue can now be closed.
