### ISSUE TITLE
misconfigured svelte project

### ISSUE THREAD

**Issue by proven-design** [gitpod-io/gitpod#4694]
### Bug description

3000 port application previews refresh / lose connection approximately every 10 to 20 seconds.

In console I see this: Firefox can’t establish a connection to the server at wss://3000-emerald-orangutan-byyl8mi5.ws-us10.gitpod.io:24678/. 

Same happens in chrome.

In Chrome:
client.ts:19 WebSocket connection to 'wss://3000-emerald-orangutan-byyl8mi5.ws-us10.gitpod.io:24678/' failed: 
(anonymous) @ client:184

### Steps to reproduce

1. Open this repo https://github.com/proven-design/Respawn
2. Run npm install in terminal
3. npm run dev in terminal
4. open browser 3000 preview
5. Watch 10-20s and watch it refresh / lose websocket connection every 10-20 seconds

### Expected behavior

Page should only refresh on command or on save.

### Example repository

https://github.com/proven-design/Respawn

**Comment by akosyakov** [comment]
I cannot reproduce it. @proven-design Does it happen for you on any repo or only for this?

Are you sure that there is no anything in between which can cause reconnections? Do you use any browser extensions, antivirus software, maybe your provider? Could you try to disable such things and see whether it fixes the situatuion.

**Comment by akosyakov** [comment]
Also which version of Chrome? We test only against stable. If you are using something beta and it does not work then you should report to Chrome devs.

**Comment by akosyakov** [comment]
Yeap, it is Chrome Canary issue, please use stable Chrome. If you use unstable versions, please report to Chrome devs, it is a point of Canary.

<img width="1754" alt="Screenshot 2021-07-05 at 09 02 16" src="https://user-images.githubusercontent.com/3082655/124416120-ba33d700-dd6f-11eb-8318-e1461feb234d.png">

**Comment by akosyakov** [comment]
nope, it seems to be a preview bug, i was able to reproduce on stable as well. It happens only in preview mode. If one opens a new tab (with open browser) then it works without any issues.

**Comment by akosyakov** [comment]
@proven-design The issue is that Gitpod accept HTTP connection only on port 443, and svelte tries to connect on some other port. Usually frameworks allow to configure ports and there is a command `gp url ${portNumber}` which can create an URI to access some HTTP port in Gitpod settings. You can check out how our website is configured: https://github.com/gitpod-io/website/blob/e6bb5a91b8021027baff336008e372720077be57/.gitpod.yml#L12-L18 cc @mikenikles 

But there is even easier solution with Gitpod Local Companion: https://www.gitpod.io/blog/local-app It allows to access services from Gitpod workspace on your localhost as you will do it usually in local development. Give it a try.

**Comment by mikenikles** [comment]
That happens because Vite needs a bit of hand-holding 😉. I opened https://github.com/proven-design/Respawn/pull/1 to provide a solution and make SvelteKit work on Gitpod.

The gitpod-io/website project looks different because we are not on the latest SvelteKit version yet.
