### ISSUE TITLE
How to give access to only a few repositories ?

### ISSUE THREAD

**Issue by iksaif** [gitpod-io/gitpod#472]
I'm trying to give gitpod access to only one or two repositories. I tried to install the application from the marketplace for that, but I eventually end up on  https://gitpod.io/install-github-app/?installation_id=<id>&setup_action=install and the next step asks me again to give access to all my repositories and organizations. Am I missing something ?

cc: @jankeromnes

**Comment by iksaif** [comment]
![Screenshot (85)](https://user-images.githubusercontent.com/1032963/56042562-a25d7c00-5d3b-11e9-970b-91bf39a69300.png)

These three repositories are configured, but I still can't push

**Comment by AlexTugarev** [comment]
@iksaif, a lot of things about GitHub Apps vs. GitHub OAuth Apps are confusing. We're trying to make the process as smooth as possible and are thankful for your feedback.

The permissions of the GitHub App can be configured per repository in order to enable [prebuilt workspaces](https://www.gitpod.io/features#prebuilt-workspaces).

OTOH Gitpod uses GitHub OAuth to authorize read/write access for repositories. Here GitHub differentiates only between user's repositories and organizational repositories.

Also, to install the GitHub App you need to authorize using OAuth.

**Comment by ahmad-punch** [comment]
Hey guys, I only want to allow gitpod access to a selected few github repositories but I can't seem to find any option to do so, it's asking for access of all the private repositories. How can I move forward?

**Comment by ahmad-punch** [comment]
Yes, that is what the question above is about :D

**Comment by JanCizmar** [comment]
So maybe, you would like to reopen this?

**Comment by axonasif** [comment]
Can everyone subscribed to this issue react with a " 👍 " on the [main post](https://github.com/gitpod-io/gitpod/issues/472#issue-431842083-permalink) to upvote?

**Comment by JanCizmar** [comment]
Hey! This is really a deal breaker for us. As a workaround we might create a special GitHub user accounts with restricted permissions, but thats not optimal.
