### ISSUE TITLE
When trying to open a repository from a new Git provider, propose to add an Integration

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4730]
Adding self-hosted GitLabs/GitHubs is not discoverable. See also [Slack thread](https://gitpod.slack.com/archives/C01KPEPNBD0/p1625651848107700) (internal).

When you try to open a repository from a new Git provider (e.g. a self-managed GitLab) by prefixing the repo URL with `my-gitlab.acme.com/#`:

**Expected result**

A message that goes like this:

> Are you trying to open a git repository from a self hosted provider instance? [Add Integration](https://gitpod.io/integrations)

**Current result**

> Unrecognized context / read more about supported context URLs

**Comment by corneliusludmann** [comment]
Steps to reproduce that issue:

1. Open https://gitlab.com/gitlab-org/gitlab/ in Gitpod and wait until the GitLab instance is up and running on port 3000 (could take some time).
2. Login into your GitLab instance (https://3000-xxxxx-xxxxxx-xxxx.ws-xxXX.gitpod.io/) with `root` / `5iveL!fe`.
3. After login into your GitLab instance, open a sample repo and copy the URL.
4. Append this repo URL to your Gitpod instance, e.g. a preview env: 
   ```
   https://xxxx-xxxxx.staging.gitpod-dev.com/#https://3000-xxxxx-xxxxxx-xxxx.ws-xxXX.gitpod.io/flightjs/Flight
   ```

**Comment by corneliusludmann** [comment]
Thinking about it, it would probably be enough to use any random non-existing context URL, like https://gitpod.io/#https://my-gitlab.com/sample/repo since the proposed solution is to just change the error text with a link where you could add an integration for every context URL that cannot be parsed. You don't need to use an actual existing GitLab instance as a context URL as long as we don't want to do some magic to recognize whether this could be a custom GitLab instance or not.
