### ISSUE TITLE
[proxy] Supplement sec-websocket-key with random value

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4742]
Some browsers started to not send the `sec-websocket-key` header when upgrading websocket connections. This lead to a recent outage where we started to send this header along if it wasn't present. When doing so, we should send a random rather than a static value, and produce a metric that tells us how often we had to do this.

A Caddy plugin is in order here :)

**Comment by AlexTugarev** [comment]
What is the difference to sending a static value? 

As long as it's not generated by the browser agent, it's just a workaround for the WS servers which require this header to be present. 

WRT to the browser agent, this won't fix anything, just because there appears to be no check in such cases, which lets me wonder why this is not breaking on client side. In the end, the purpose of the header is for the browser to check against the echoed value and see if the server understood the handshake.

**Comment by akosyakov** [comment]
Last comments [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1226856#c19) indicate that issue does not happen anymore. It would be good to add logging to verify it and remove a work around.

**Comment by akosyakov** [comment]
It was apparently issue on GCP side: https://bugs.chromium.org/p/chromium/issues/detail?id=1226856#c28 which was resolved.
