### ISSUE TITLE
VNC Port not initialized

### ISSUE THREAD

**Issue by AkemiShimizu** [gitpod-io/gitpod#4770]
### Bug description

VNC is not initialized on gitpod.

### Steps to reproduce

1. Click on "Open in Gitpod" at https://github.com/AkemiShimizu/Watson
2. Experience the bug.

### Expected behavior

To run the port 6080 and be able of visiting it.

### Example repository

https://github.com/AkemiShimizu/Watson

### Anything else?

It worked just fine a few days ago, then all of ths sudden any VNC related apps stopped working.

**Comment by AkemiShimizu** [comment]
> ### Bug description
> VNC is not initialized on gitpod.
> 
> ### Steps to reproduce
> 1. Click on "Open in Gitpod" at https://github.com/AkemiShimizu/Watson
> 2. Experience the bug.
> 
> ### Expected behavior
> To run the port 6080 and be able of visiting it.
> 
> ### Example repository
> https://github.com/AkemiShimizu/Watson
> 
> ### Anything else?
> It worked just fine a few days ago, then all of ths sudden any VNC related apps stopped working.

Not related to browser incompatibility as this has been tested in Safari and Chrome, both in incognito.

**Comment by jankeromnes** [comment]
Hi @AkemiShimizu! Sorry about this. It seems that we recently broke the `gitpod/workspace-full-vnc` image (by upgrading noVNC without also renaming the launch script).

We're fixing this in https://github.com/gitpod-io/workspace-images/pull/442 (the fix should be correct, but I haven't taken the time to test it & merge it yet -- will try to do that soon!)

**Comment by Kqpa** [comment]
i'm still having the issue

**Comment by AkemiShimizu** [comment]
Still facing problems with the image.

**Comment by akosyakov** [comment]
@jankeromnes does anyone need to clean up some docker caches or something?

**Comment by jankeromnes** [comment]
Hmm, the new VNC image was successfully deployed 2 hours ago. Will briefly test this again.

**Comment by jankeromnes** [comment]
One note about https://github.com/AkemiShimizu/Watson/blob/master/.gitpod.Dockerfile -- Gitpod currently caches workspace images based on a hash of the Dockerfile.

This means that, if the `FROM` image changes, all workspaces will still get whatever image version was the latest when the Dockerfile was last modified (even brand new workspaces will still get the cached image, which I think is a shame).

The workaround for this is to make at least one small change to your Dockerfile in order to force a rebuild (for example, you can add something like `ENV TRIGGER_REBUILD=1` to your Dockerfile, and then bump the value whenever you want a rebuild).

**Opinion**: The reason we cache unmodified Dockerfiles "forever" is because we don't want to surprise users with unexpected Docker rebuilds (e.g. if your `FROM` image changes one day, and Gitpod decides to rebuild your Dockerfile, and the rebuild fails e.g. due to some new changes in the base image -- that would be a bad UX for you, because you didn't explicitly request a Docker rebuild.) Now, personally, I believe that "serving users with stable images that never rebuild and constantly grow older forever" is actually worse than "occasionally rebuilding images, and sometimes that fails e.g. when you need to update something in your Dockerfile", but I'm currently the only person in the team to think this. 😅

**Comment by jankeromnes** [comment]
I can confirm that the bug was fixed: Tested with https://gitpod.io/#https://github.com/techwithtim/Hangman

<img width="1440" alt="Screenshot 2021-07-13 at 15 12 36" src="https://user-images.githubusercontent.com/599268/125457820-798c156f-bd9c-4b46-85dc-f2845e2568a7.png">

If you have a custom Dockerfile based on `gitpod/workspace-full-vnc` and are affected by this bug, please simply commit a small change to your Dockerfile and try again.

**Comment by Kqpa** [comment]
The fix works, thank you!
<img width="2502" alt="Screenshot 2021-07-13 at 16 23 14" src="https://user-images.githubusercontent.com/76552592/125459454-51afe868-1005-45f4-a537-f764961385d7.png">
<img width="975" alt="Screenshot 2021-07-13 at 16 23 43" src="https://user-images.githubusercontent.com/76552592/125459465-21b6c2ab-d3ec-44ad-a28c-8e9e7b5f60a5.png">
