### ISSUE TITLE
[code] share node_modules between envs

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4777]
Right now to build 3 mins spent to download node_modules, we do it very often in 3 different envs: prod, werft and preview. It would be good if they is a way to share node_modules from one envs with other. Maybe content service could be used somehow?

**Comment by geropl** [comment]
Some notes regarding sharing in `werft` builds:
 - all builds run on the same node (to benefit from caching, especially docker layers)
 - we could - and had in the past - share the yarn cache between builds, but it broke every other week due to bad concurrency behavior
 - we still have a properly configured https cached deployed in `core-dev`, but it's not used for builds atm:
   - the node it runs on are to small to be much faster compared to "just pull it from the internet"
   - it proved to be hard with leeway to configured a `HTTPS_PROXY` for the process we want to used it for (`yarn`), and no other (`docker`: blobs are typically to big to cache; e.g. there's little benefit)

**Comment by akosyakov** [comment]
I was thinking about something similar what CI servers are doing, i.e. create a unique key based on content hash from yarn.lock for instance and cache all node_modules for it. Use such key to restore node_modules later. Could we use the content service for it or there is a better alternative?

**Comment by akosyakov** [comment]
How VS Code team build on CI with caching: https://github.com/microsoft/vscode/blob/9520f0a515e7e24802c92f885a0efb242fca3831/.github/workflows/ci.yml#L32-L67

**Comment by akosyakov** [comment]
Discussed with @geropl :
- we are not going to touch Werft job now, it is rarely a problem, since there is already caching.
- for tasks, we integrate leeway into gitpod-io/vscode and reuse GCP buckets

@csweichel hope it sounds fine with you

**Comment by aledbf** [comment]
Improving caching is easy if we can do something [like this](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/Dockerfile#L31-L35)

**Comment by csweichel** [comment]
During the CI builds we could indeed use a shared yarn cache. You can set the Yarn mutex mechanism using `LEEWAY_YARN_MUTEX` (right now we use `network`):
https://github.com/gitpod-io/leeway/blob/d8f664e241836b97cbf190291cb21cbfeb4f5d89/pkg/leeway/build.go#L63-L66

**Comment by akosyakov** [comment]
Do we need to mount shared yarn cache into https://github.com/gitpod-io/gitpod/blob/c060c81306afa549e719dce0502592000407a498/components/ide/code/leeway.Dockerfile#L53 somehow and tell yarn to use such mount?

**Comment by akosyakov** [comment]
I integrated leeway into VS Code repo. One should configure GCP auth in prev env to make use of the cache.
