### ISSUE TITLE
[ws-daemon] fails mounting proc

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4784]
There are regular CRITICAL errors [logged](https://cloudlogging.app.goo.gl/isfYQsfHAUmTjCm8A) from the `nsinsider` process. Followed by a "cannot mount /proc" error logging.

I am not sure how this is experienced by users, but I guess it means a workspace start failure.

**Comment by csweichel** [comment]
Unfortunately the error message isn't very helpful. It's well possible that the mount-point where the user is trying to mount `proc` no longer exists. It's also just as possible that this is an actual problem.

First step is to get better logging in place.

**Comment by csweichel** [comment]
I've raised a PR to improve the logs in this corner of the system. We'll deploy today 13:00 CEST and bring this into prod.
We'll revisit this issue once the logging is in place.

Until it's clear if this actually impacts users, I'll remove the label for now.

**Comment by csweichel** [comment]
looking at the non-headless cases it seems that the proc mount failures are due to Docker container starts going wrong.
I'd propose we tone down this particular message (i.e. the mount point disappears before we can mount/does not exist).
If this affected workspaces, we'd see workspaces fail.

That said, it would be interesting to reproduce the issue and find out how it comes to be.

For now, I'll reduce the priority because this does not seem to directly impact users.

**Comment by csweichel** [comment]
Closing for now - will reopen if the issue persists
