### ISSUE TITLE
[ws-daemon] missconfigured logging

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4802]
Ws-daemon is very loud with ERROR logs entries that have large json messages and seems to be 'debug' severity.
[Example entry](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-07-13T14:26:54Z;lfeCustomFields=jsonPayload%252Fport;query=severity%3DERROR%0Atimestamp%3D%222021-07-13T14:26:54Z%22%0AinsertId%3D%22yyrb68gbh3b47m%22;summaryFields=jsonPayload%252Fport,labels%252F%2522k8s-pod%252FworkspaceID%2522:false:32:beginning?project=gitpod-191109)

**Comment by csweichel** [comment]
That's because stackdriver interprets anything that does not conform to it's own structure in this way.
Some of the log output produced by ws-daemon comes from processes we do not control (like in this instance `runc`). We execute those processes in ws-daemon, so we could produce a filter that tones down the logs and makes them "GKE compliant".
