### ISSUE TITLE
Prebuild process gets stuck (when updating `.gitpod.Dockerfile`)

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4856]
### Bug description

When updating `.gitpod.Dockerfile` and pushing it back to repo on a branch, the prebuild seems stuck.
It takes over half an hour (but I am not sure how long, perhaps 1 hour?) where all I see is this screen with jumping G.
(while console doesn't display any error) 
![image](https://user-images.githubusercontent.com/22901/126050495-38c3f390-c289-44a6-a970-8d1a6c4f0b7f.png)

Coming back to the computer after a while, I see this screen -
![image](https://user-images.githubusercontent.com/22901/126050511-ee421691-f789-4b2c-be3e-83bbd4f03be6.png)
And here's the output I found in `console` -
https://gist.github.com/shaal/b34b1e2ffba2d50deb4e42a3b4ed961c

I checked `gitpod.io/workspaces`, and I see 5(?) workspaces running, even that I only opened 2 windows of the following URL, expecting to see the prebuild output - https://gitpod.io/#https://github.com/shaal/DrupalPod/tree/debug-with-tmate

![image](https://user-images.githubusercontent.com/22901/126050578-4c2c2c6d-ba24-4b12-807f-ca80fa5f06b9.png)

### Steps to reproduce

In my experience, it is difficult to replicate or anticipate how prebuild behave (especially with custom docker image build)
This happened to me also the other day, when I worked on https://github.com/phase2/outline/tree/gitpod, when I opened an issue in https://community.gitpod.io/t/prebuild-is-stuck/4171

I think I usually use the manual prebuild using the `#prebuild/` in the URL, but in repos that has the Gitpod bot, I would get a message that a prebuild is already running.

These workspaces supposed to run prebuild, but they are stuck, and once 4 workspaces are "running", I cannot open another one, but at the same time I cannot stop a prebuild that is stuck like that.
So, I usually wait a few hours, then the workspaces are shutdown, and I can run prebuild using the `#prebuild/` in the URL, and then it finally works.

**Comment by shaal** [comment]
Update 1:

**Comment by shaal** [comment]
### Update 2:
Gitpod seems to keep restarting these prebuilds, you can see below that these are 4 new workpsaces.
In the meantime, I cannot do anything. I cannot stop these workspaces from rebuilding, and I cannot work on other things in the meantime (because it's maxed out on 4 active workspaces)
![image](https://user-images.githubusercontent.com/22901/126052664-004fee84-34e5-4cb5-aefb-9842eeee70cd.png)

**Comment by shaal** [comment]
### Update 3:
After a few hours, it was no longer stuck.
I opened a workspace with the updated repo, and I saw the "build image" page, now displaying terminal messages as I expected. (I was able to SSH into the process of image build, since I use tmate in there)

**Comment by shaal** [comment]
### Update 4:
I added `ENV TRIGGER_REBUILD 1` to `.gitpod.Dockerfile`, and now I see this screen, which seems to be stuck again. No console errors, and nothing displayed in the "terminal" output. 
![image](https://user-images.githubusercontent.com/22901/126065779-10573bb2-911f-4f2d-92c9-45c3452fda3a.png)

**Comment by ghuntley** [comment]
https://gitpod.io/#https://github.com/ghuntley/learn-graphql/tree/gh/gitpodify

Confirming that I've also witnessed the following as of moments ago

> now I see this screen, which seems to be stuck again. No console errors, and nothing displayed in the "terminal" output.

<img width="798" alt="2021-07-19_13-36-48" src="https://user-images.githubusercontent.com/127353/126099322-632bdb03-78c1-4274-973d-26d803b29cf3.png">

**Comment by geropl** [comment]
Outch... this feels like a restart-cycle because we miss some signal. Might have been introduced with the recent headless-log changes. :confused:  Will dig into this shortly.

**Comment by geropl** [comment]
Thx so much  @shaal for this treasure trove of data.

It's a bit entangled, bit it _seems_ like here are multiple strange things (bugs?) happening here:
 - the root cause for the `cannot resolve base image ref`: not sure where this comes from, yet
 - we seem to not terminate prebuilds properly which do not reach the kubernetes control plane (to be verified!)
 - we start new workspaces in a loop on a (failed) prebuild

Will try to verify and fix one-by-one.

**Comment by shaal** [comment]
Thank you for the quick response, let me know if I can help testing.

**Comment by geropl** [comment]
Ok, pinned it down:
 - the frontend does not properly end it's re-try loop to load headless logs but assumes we will navigate away once we have the first clear signal on "prebuild done". If there is an error during workspace start _before_ we generate an `ideUrl` (e.g., during imagebuilds) we can never navigate away from the prebuild logs view.
 - we do not handle the image builder error properly: instead of failing and stopping the workspace it runs into a timeout (1h)
 
 Besides those errors which we're going to fix in #4875 there is a UI/UX gap for exactly this situation (no `ideUrl` but workspace start fails) which this PR will not attempt to fix because it needs a bit more discussion. I will open a new issue for that.

**Comment by shaal** [comment]
@geropl Do you know why image build takes so long? At least in my case, `.gitpod.Dockerfile` takes less than a minute to install

> it seems the image build takes very long (longer than the default timeout of 1h)

**Comment by geropl** [comment]
> @geropl Do you know why image build takes so long? At least in my case, .gitpod.Dockerfile takes less than a minute to install

Hm, not sure. Maybe my hypothesis (long build) is wrong, but it was the only way I could reproduce the error case.

It _could_ be that there is another error within `image-builder`. Thinking about it I always tested EU, could be that this error manifested in US only. :thinking: Will try that instance with the contexts you shared. But if that's the case, it's likely to go away with the new `iamge-builder` as well, as the core process simplifies a lot.

**Comment by shaal** [comment]
I updated the `.gitpod.Dockerfile`, and then checked this URL
https://gitpod.io/#https://github.com/shaal/DrupalPod/blob/debug-with-tmate/.gitpod/.gitpod.Dockerfile

It still looks like the prebuild is stuck. I am assuming that's expected, because the fix will be done through the follow-up issues?

**Comment by geropl** [comment]
@shaal  I tried the context you linked above (https://github.com/shaal/DrupalPod/blob/debug-with-tmate/.gitpod/.gitpod.Dockerfile) and it hung for me as well, but during image build, not prebuild. And it did so in this `RUN`: https://github.com/shaal/DrupalPod/blob/debug-with-tmate/.gitpod/.gitpod.Dockerfile#L33-L36

top says:
![image](https://user-images.githubusercontent.com/32448529/127134396-0e33a1c7-4bb2-4f5f-8cf3-0bdbbb56b814.png)

It feels this is unrelated to the original problem in this issue (which started multiple workspaces on broken image builds) which got fixed in the meantime, so I opt for closing this. Especially as I see you opened https://github.com/gitpod-io/gitpod/issues/4936 which looks like a follow up. D'accord?

**Comment by shaal** [comment]
@geropl Yeah, I think the original problem of this issue was resolved, and #4936 explains better the problem I'm seeing now.
Closing this issue, Thank you all!
