### ISSUE TITLE
Allow Renaming of Workspaces & More powerful new workspace

### ISSUE THREAD

**Issue by faisal-m16** [gitpod-io/gitpod#4857]
## 1. Allow Renaming of Workspaces
Currently name for Workspaces are randomly generated, but when we have many workspaces of same context for different use it is getting confusing.

## 2. More powerful new workspace
Currently Recent in New Workspace shows you only default branch of recent repos. Making it to at-least select a branch will be great. Also, you can just give a text box which takes URL of repo and start workspace. I know Chrome has extension for this but it will good to have feature in dashboard itself.

**Comment by shaal** [comment]
++ 
Yes please!!

**Comment by geropl** [comment]
> text box which takes URL of repo and start workspace

:+1:

**Comment by gtsiolis** [comment]
Thanks, everyone!
1. Closing this in favor of an older issue in https://github.com/gitpod-io/gitpod/issues/3946 regarding the point for renaming workspaces.
2. The upcoming **Teams & Projects** feature will allow users to quickly open a new workspace for any recent and active branch. @faisal-m16 I've added https://github.com/gitpod-io/gitpod/issues/5372 to track the feature request to open a new workspace for any branch although this could be less relevant after seeing the new workflows coming with the Teams & Projects.

See also an early design draft in https://community.gitpod.io/t/please-let-me-change-workspace-names/3650/4 and relevant issue that could help in this direction in https://github.com/gitpod-io/gitpod/issues/3594. 🖍️

Cc @ghuntley because https://github.com/gitpod-io/gitpod/issues/5365#issuecomment-905186762
Cc @atduarte because https://github.com/gitpod-io/gitpod/issues/4129#issuecomment-905260217 and [relevant discussion](https://gitpod.slack.com/archives/C01KGM9AW4W/p1629879225422600) (internal)
Cc @svenefftinge because https://github.com/gitpod-io/gitpod/issues/5365#issuecomment-905235539
