### ISSUE TITLE
Gitpod is not letting me push my changes to github

### ISSUE THREAD

**Issue by tommygonzaleza** [gitpod-io/gitpod#4914]
### Bug description

When I try to push my changes to github it fails.
![image](https://user-images.githubusercontent.com/56565994/126677180-4dcf96b4-5ee2-4a1f-98c8-66b6157875f3.png)
![image](https://user-images.githubusercontent.com/56565994/126677201-825b07ae-7d3f-4241-bb9a-a2113241b32b.png)

### Steps to reproduce

git add .
git commit -m "Any message"
git push

**Comment by jrdzha** [comment]
Just to chime in here -- we are experiencing the same issue.

Running `git fsck` prints 100's of "missing blob".

However, when we remove the `.gitpod.yml`, so we use the default Gitpod image, then this issue goes away. This is only an issue when using a custom image.

**Comment by jrdzha** [comment]
For what it's worth, using a custom image, and then removing the workspace and cloning it manually solves this issue:

```
rm -rf /workspace/repo
cd /workspace
git clone repo
git fsck  # No errors
```

**Comment by jrdzha** [comment]
Changing our docker image to use `FROM gitpod/workspace-base:latest` fixed this issue for us. This may not be a good solution for many, but worked for us.

**Comment by ArthurSens** [comment]
Hey!

I'm trying to reproduce it somehow and I still couldn't do it. Do you have a repository that we could use as an example to reproduce this problem?

**Comment by tommygonzaleza** [comment]
https://github.com/LeonErasmusCh/jest-unit-test

**Comment by ArthurSens** [comment]
Hmmm, I noticed that this repository is completely empty. So it doesn't have a `.gitpod.yml` file nor a base image to create the workspace.


I tried creating an empty repository: https://github.com/ArthurSens/empty-repository and then opened a workspace from it and pushed some changes.

It worked just fine:
![image](https://user-images.githubusercontent.com/24193764/126714543-01e6ccaa-0bf1-4380-9789-3fac18d0d766.png)

As you can see, the repository is not empty anymore.

@csweichel, any ideas on what could be causing this?

**Comment by akosyakov** [comment]
@jrdzha Which version of git do you use? What `git --version` prints?

**Comment by jrdzha** [comment]
@akosyakov I'm using the `python:3.6` image, and `git --version` is printing out `git version 2.20.1`.

**Comment by akosyakov** [comment]
@jrdzha Could you try to upgrade to latest git and see whether issue persists? We switched to partial clone to speed up workspace startup, maybe it broken older git versions.

**Comment by tommygonzaleza** [comment]
I found out that the error is happening when you change the remote repository, can you try to replicate it?

**Comment by alesanchezr** [comment]
Yeah I can confirm that it happens in all my workspaces when I change the remote.

**Comment by akosyakov** [comment]
I tried and could not reproduce with https://github.com/gitpod-io/vscode. I did:
```
git remote set-url origin https://github.com/akosyakov/vscode.git
git push -f
```

Could someone provide an example repo and commands to reproduce?

**Comment by tommygonzaleza** [comment]
I'm sending you an example

**Comment by tommygonzaleza** [comment]
From this workspace: [https://gitpod.io#snapshot/f9b9f16c-f868-4ea0-b386-4c180ef151fc](https://gitpod.io#snapshot/f9b9f16c-f868-4ea0-b386-4c180ef151fc)

I'm using these commands:
`git remote set-url origin https://github.com/tommygonzaleza/testing-issue.git
git push -f`

**Comment by tommygonzaleza** [comment]
Maybe if you try to do it from this repository: [https://github.com/4GeeksAcademy/html-hello](https://github.com/4GeeksAcademy/html-hello)

Create a repository and push it to your new repository

**Comment by akosyakov** [comment]
still works 🤔

**Comment by akosyakov** [comment]
@tommygonzaleza Does it make a difference if you do `git push -f origin HEAD` i.e. explicitly specifying target origin?

**Comment by manuelabarca** [comment]
> @tommygonzaleza Does it make a difference if you do `git push -f origin HEAD` i.e. explicitly specifying target origin?

git push set-url origin url
git branch -M main
git push -u origin main

`Enumerating objects: 454, done.
fatal: remote error: upload-pack: not our ref 0038472301af887376b326d7873bb840a6bf2dcc
fatal: remote error: upload-pack: not our ref 0038472301af887376b326d7873bb840a6bf2dcc`

**Comment by tommygonzaleza** [comment]
Yes it is the same, and there are a lot of teammates that are facing the same issue

**Comment by alesanchezr** [comment]
Here is a loom video with the error:
https://www.loom.com/share/f877b5a8aaaf4607b58f44a435bfdc14

This is the repository but the error happens with all of them:
https://www.loom.com/share/f877b5a8aaaf4607b58f44a435bfdc14

**Comment by akosyakov** [comment]
I don’t know how to reproduce it but marking as high priority since it seems to affect a lot of users. cc @csweichel 

it may be related to partial cloning

**Comment by tommygonzaleza** [comment]
How can I help you solve it? Are you working on it?

**Comment by csweichel** [comment]
The videos of @alesanchezr very super handy to understand the problem.
We're still trying to reproduce and understand the issue.

There should be news latest end of Monday (CEST).

**Comment by csweichel** [comment]
### The good news
There's a ~fix~ workaround: pushing the repo to a new remote, rather than re-using `origin` works as expected.
![image](https://user-images.githubusercontent.com/3210701/128032708-51daae2e-2f4c-42ea-b8d4-090502a6011e.png)

### Why is this?
We recently started cloning repositories with `--filter=blob:none` (see [docs](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---filterltfilter-specgt)) by default. This massively improves CPU load and improves workspace startup time. When cloning a repo this way, git installs what it calls "promisor" which are essentially a lazy-fetch mechanism. Those promisors are bound to the remote - you can check that by looking at the promisor config of `origin` using `git config remote.origin.partialclonefilter`.

If you now change the remote URL to another repo, the promisor fails because that repo does not actually have the objects the promisor references, hence the unpack errors you're seeing.
If however, we push to a new remote, the promisor on remote works just fine and we can download/push the data to the new origin.

### What now?
To me this looks like a situation where `git` should produce a warning rather than some strange error message. But it doesn't 🤦 
Considering the performance benefits we're seeing from the `clone --filter` trading it off with the very very few cases it's breaking, it's unlikely we'd want to switch back. 

However, we'd do well to put this in the docs.
@ghuntley Could you take it from here and draft a docs page that sums up the above?

**Comment by mikenikles** [comment]
Looking at the video, it feels to me that the suggested workflow should be to fork the repo before opening a Gitpod workspace. This avoids the issue of changing the remote URL entirely and is less work for people (compared to creating a workspace, creating a new GitHub repo, copying the remote URL, changing the remote URL in the workspace).

@ghuntley let's add a "Troubleshooting" section to the nav above "References".

**Comment by akosyakov** [comment]
It means what any workflow from VS Code UI which involves clicking on fork notification is broken? i.e. after that a user cannot pull change anymore?

**Comment by csweichel** [comment]
> It means what any workflow from VS Code UI which involves clicking on fork notification is broken? i.e. after that a user cannot pull change anymore?

Not sure - does the VS Code fork action change the URL of the `origin` remote?

**Comment by akosyakov** [comment]
> Not sure - does the VS Code fork action change the URL of the origin remote?

Yes, whenever you start from the repo and you cannot push, you will be notified to fork and it will update remotes. It is quite typical flow btw while contributing to external projects. As well as there are user cases when projects using forks to contribute but start from the main repo to reuse prebuilds: https://github.com/gitpod-io/gitpod/issues/4588 I hope we are not underestimating impact on usability here.

**Comment by akosyakov** [comment]
> Looking at the video, it feels to me that the suggested workflow should be to fork the repo before opening a Gitpod workspace.

It won't allow users to make use of prebuilds.

**Comment by csweichel** [comment]
> > Looking at the video, it feels to me that the suggested workflow should be to fork the repo before opening a Gitpod workspace.
> 
> It won't allow users to make use of prebuilds.

In case they need to fork the repo afterwards, that is. Not prebuilds in general I'd think.

**Comment by alesanchezr** [comment]
Our biggest challenge is always that we work with beginners or junior devs, they are not familiar with any flow and we try to reduce friction to the lowest.

Our strategy was to create repository templates allowing on-click setup by sharing a link like `gitpod.io#<template_repo_url>`. After the new workspace was initialized, students were asked to push to their own repo (by updating or adding the new remote).

Here is an example of the typical project instructions: 
![Screen Shot 2021-08-04 at 8 53 07 PM](https://user-images.githubusercontent.com/426452/128274239-a275f846-e63d-46d3-bec0-0c920f1d2441.png)

Note: it was very easy to generate a link for the students that opens directly on Gitpod.

## No more student usage statistics 

With the current approach, we could also generate personalized links for each student with environmental variables that help us collect usage statistics on the student, for example:

```
gitpod.io#session_token=val2/<repository_template_url>
```

We are passing an internal `session_token` that we use to report statistics linked to the student, we developed a [webpack plugin](https://www.npmjs.com/package/bc-webpack-error-reporting-plugin) that was reporting compilation errors (for example) and we were also about to integrate that "tracking" functionality with [learnpack](http://learnpack.co/) and the [learnpack vscode plugin](https://open-vsx.org/extension/learnpack/learnpack-vscode) that we recently released to integrate better with Gitpod,

## Forking is not a solution

Forking is not the solution because in this case, students are not contributing to any project, they are using repositories as templates, you cannot have more than one fork to the same repo.

## Github Templates

Asking the students to use the repo as a template to create a new repo seems like a better flow, you can generate new repos based on templates by using the following URL structure:
```
https://github.com/<github_user>/<repository_project>/generate
```

This is "ok" but we are still very sad to lose the ability to generate personalized Gitpod URLs.

**Comment by csweichel** [comment]
a quick thought: you can already add environment variables when starting a workspace: https://www.gitpod.io/docs/environment-variables#provide-env-vars-via-url

@svenefftinge wdyt about the ability to propose env vars from a URL for permanent addition? Maybe teams and projects could offer a better solution here?

**Comment by alesanchezr** [comment]
> a quick thought: you can already add environment variables when starting a workspace: https://www.gitpod.io/docs/environment-variables#provide-env-vars-via-url

Yeah I know we are using that.

**Comment by svenefftinge** [comment]
> wdyt about the ability to propose env vars from a URL for permanent addition? Maybe teams and projects could offer a better solution here?

We definitely are going to add project-level environment variables, soon.

**Comment by akosyakov** [comment]
partial clone was revered in https://github.com/gitpod-io/gitpod/pull/5152
