### ISSUE TITLE
Don't abort prebuild if task failed

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4964]
Task failure means something potentially wrong with user code base. Aborting a prebuild in such case means that a user has to wait all over to see the same error.

Also from Sven:
We’d need to also stop executing follow up task.

**Comment by csweichel** [comment]
Just to clarify: the issue is that when a prebuild task fails, the prebuild is not failed and available, but rather unavailable because it's in the state "aborted"?

The latter state is intended for system failure, while there is an explicit "done_failed" state for prebuilds that ran successfully, but whose tasks failed. If the behaviour is as described above, that's a but we should fix :)

**Comment by akosyakov** [comment]
> the issue is that when a prebuild task fails, the prebuild is not failed and available, but rather unavailable because it's in the state "aborted"?

yes, it seems so

**Comment by csweichel** [comment]
This is most likely a bug in ws-manger where we've changed the way failing headless tasks are communicated to the system. If a headless task fails supervisor writes that to `/dev/termination-log`. However, ws-manager does not distinguish task from system failure well enough and also marks the pod with the `failed` condition. This causes ws-manager-bridge to mark the prebuild as aborted.
