### ISSUE TITLE
Use GitLab private docker registry

### ISSUE THREAD

**Issue by ttauchen** [gitpod-io/gitpod#5000]
Hi all,

we sometimes need custom docker images for our pods. As some of our customes do not want exposure to the public we have to keep our groups and projects private inside gitlab.

We therefore also have to build our docker images for the gitpod dev environment inside a private repository and publish to the gitlab private registry.

It would be nice if gitpod could access these images as well.

**Comment by asthomasdk** [comment]
I believe there is also another issue regarding external registry support in the Gitpod setup. 

You can work around this by setting variables for your registry credentials in your user profile. You can then use these to login to the registries so that automated pulls and pushes can be made to these registries. This is not idea, but works in most cases. One case where it does not work, however, is if you want Gitpod to use a private image as the workspace image. This needs to be publically available.

**Comment by gtsiolis** [comment]
@ttauchen feel free to follow up with any comments or upvote https://github.com/gitpod-io/gitpod/issues/1699. 🏓 Cc @asthomasdk
