### ISSUE TITLE
A way to rebuild the project without creating a new container

### ISSUE THREAD

**Issue by joshleblanc** [gitpod-io/gitpod#502]
If you're trying to configure a project for gitpod, you need to make changes to your repo, push, then open the repo in gitpod to test. You'll be doing this for any changes to the gitpod config file, and any changes to the Dockerfile.

It think it would be tremendously helpful to be able to just click a button and have the current container reload with the new configuration. This would make fine tuning your dockerfile, or fine tuning init steps in the config much easier.

**Comment by jankeromnes** [comment]
I personally use this workflow:

1. commit changes to `.gitpod.yml` and/or `.gitpod.dockerfile`
2. push
3. right-click on browser's `Back` button
4. usually the oldest URL in the list is `gitpod.io/#myrepo`, which creates a new workspace to test my config changes

That's not super convenient (e.g. I frequently get asked "really create new workspace?") but it works for now.

I agree that a shorter cycle / custom "hot-reload" feature would make iterating on configs much nicer, but we'd have to ensure that this mechanism behaves exactly like when you create a new workspace, otherwise you risk missing bugs that could prevent anyone else from creating a new workspace.

**Comment by HorizonShadow** [comment]
@jankeromnes it works, but still makes a new container. Gitpod has a max, and it's not very high. Something like 8 or 10. You hit that pretty fast.

**Comment by jankeromnes** [comment]
> Gitpod has a max, and it's not very high. Something like 8 or 10. You hit that pretty fast.

Ah, that's true, you can't have more than 8 workspaces running at the same time.

A workaround for this is to open https://gitpod.io/workspaces/ and click on `Stop` next to all the running workspaces you no longer need (they also get stopped after a timeout, but you don't have to wait for that).

... sorry for the many workarounds! 😕
