### ISSUE TITLE
Github Copilot says the user is not on the whitelist

### ISSUE THREAD

**Issue by Dattito** [gitpod-io/gitpod#5060]
### Bug description

I installed github copilot with the .vsix file. On my home machine, I can easily use Copilot, but installed on Gitpod, the extensions said I would not be whitelisted (I am whitelisted). I think the communication with Github fails.

### Steps to reproduce

- Installing Github Copilot via .vsix file (at https://marketplace.visualstudio.com/items?itemName=GitHub.copilot)
- Click Login in the bottom right corner
- "Not whitelisted"

**Comment by jankeromnes** [comment]
Hi @Dattito!

Thank you for reporting this problem. Is it possible that you're using a different GitHub account on your home machine vs when logging into Gitpod? Otherwise, you're probably right, maybe it's the communication between the extension and GitHub that breaks somehow.

On a side note, did you know that you can also use Gitpod via your local VS Code on your home machine? You can do this with Gitpod's local companion app, and then use Copilot that way too. See also:

- https://community.gitpod.io/t/gitpod-github-copilot/4421
- https://www.gitpod.io/blog/local-app

**Comment by Dattito** [comment]
(Nice to now that I can use Gitpod from my personal VS-Code!)

I only have one GitHub-Account and I am surely logged in with this account.

**Comment by akosyakov** [comment]
VS Code desktop support is very experimental at the moment, you can follow this steps to try: https://github.com/gitpod-io/gitpod/issues/1781

**Comment by kr-anurag** [comment]
Hey @Dattito 
Can you tell me that how did you install the extension? Like when I try to install it through the `.vsix` file, it throws an error saying that `no servers found`
