### ISSUE TITLE
Redirect new users to /new

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5071]
### Problem to solve

In the upcoming **Teams & Projects** feature, we'd like to also introduce an onboarding flow that helps users get a well-configured, prebuilt, ready-to-code dev environment for their project. See also https://github.com/gitpod-io/roadmap/issues/8. 🗺️ 

Back in https://github.com/gitpod-io/gitpod/pull/4443, we've added the first bits of this new onboarding flow (`/new`) but this is still not enabled for new users signing up. 

### Proposal

Let's redirect all new users to `/new`.

**Note** The simplest strategy to do this would be (A) to change the 'Try Now' CTA link from the website. An alternative strategy (B) would be to auto-detect new users inside the dashboard by distinguishing logins from signups, and then redirecting signups to /new.

### Depends on
(JL) Moving forward with this depends minimally on:

- [x] #6303
- [x] #6010 also has a link to open a workspace with an example repo (screenshots in [PR](https://github.com/gitpod-io/gitpod/pull/6430))
- [x] #6168

Once ☝️ are deployed, ship change to website 👇 
- [x] gitpod-io/website#1139

**Comment by mteam88** [comment]
I think this is a good idea.

**Comment by jldec** [comment]
Notes from design discussion with @gtsiolis 🙏 

- This applies to users who sign up via a the website (`Sign Up` or `Try Now` CTA)

- Instead of an intermediate webiste page, visitors will go straight to https://gitpod.io/new in the dashboard.

- This starts a `New Project` flow which would currently begin with the git provider `Log in to Gitpod` page (1st screenshot below), but could be adjusted to announce itself as `New Project` (similar to the 2nd screenshot below).

- After authenticating the steps depend on whether it's GitHub (to install the Gitpod App) or GitLab (which uses api scope)

- Finally a repo is selected and optionally a new team is created to hold the new Project.

---

![Screenshot 2021-10-20 at 21 58 34](https://user-images.githubusercontent.com/849592/138173323-af19e5d8-6b05-4821-b9b5-900d79e83b8a.png)

![Screenshot 2021-10-20 at 22 08 56](https://user-images.githubusercontent.com/849592/138173187-25e3c15a-1e6f-446c-87a7-e749cc137426.png)

**Comment by jldec** [comment]
Addendum to OP - https://github.com/gitpod-io/website/issues/1194
Re-enable example workspace choice from Try Now and Sign Up buttons
