### ISSUE TITLE
[dashboard] Long project names are cut of which makes them hard to tell apart

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5122]
When opening a long repo name, e.g. `github.com/some-long-org/business-unit-and-department` the context on the dashboard is cut of and it's very hard to tell workspaces apart.

**Comment by gtsiolis** [comment]
Thanks for opening this @csweichel! The pain point described in this issue could be resolved once we ship **Teams & Projects** and properly surface workspaces under each team (see https://github.com/gitpod-io/gitpod/issues/4921).

The end goal is to have workspaces under personal account with links to personal projects if they exist and group all workspaces under each team for all associated projects under a team.

| Workspaces (Personal Account) | Workspaces (Team) |
|-|-|
| <img width="1440" alt="Personal" src="https://user-images.githubusercontent.com/120486/128759190-f9413a10-4d21-4fa6-9ea4-d540fb7a9f84.png"> | <img width="1440" alt="Personal-1" src="https://user-images.githubusercontent.com/120486/128759199-2447a559-cf73-4ee9-ba70-468116b3f9f2.png"> |

🍊 🍊 🍊 🍊 

@corneliusludmann did experiment with adding tooltips on all elements before but voted against it in https://github.com/gitpod-io/gitpod/pull/4416#discussion_r648748187. However, we could consider adding a single tooltip on the repository element if it makes sense.

🍋 🍋 🍋 🍋 

Also, FWIW, there's https://github.com/gitpod-io/gitpod/issues/3594 which could improve the information parsing on the workspace list.

**Comment by gtsiolis** [comment]
Alternatively, using better truncation, by truncating the middle part would also work and would be more preferable maybe as it would introduce a change we can leave there without the need to remove later. 💡 

For example, showing: `github.com/som…department` instead of `github.com/some-long-org/…`.

**Comment by adam-tylr** [comment]
My company has some project names well over 100 characters. I like the truncation idea. Maybe showing the full path on a tooltip or something if you mouse over. We have a few repos that might have the same name but live in a different business unit's folder for example. That would let us verify the whole path if we needed to.

**Comment by svenefftinge** [comment]
We should cut off the `github/gitlab` bit (people know where their repos sit) so it renders s `org/repo`. With projects (coming soon) we will also show it as `org/project` which is the same pattern GitHub and GitLab uses.
I think truncating in the middle would be a little strange/special, but providing tooltips makes a ton of sense.

**Comment by corneliusludmann** [comment]
> We should cut off the `github/gitlab` bit (people know where their repos sit) so it renders as `org/repo`.

What about replacing github.com / gitlab.com / bitbucket.org with their logos? Since I use both, GitHub and GitLab repo, it would help me to spot the right repo. And a small icon would not take that much space.

**Comment by laushinka** [comment]
Discussed this with @gtsiolis and decided to add a tooltip as a temporary solution to this issue until we launch Teams and Projects.

**Comment by gtsiolis** [comment]
Thanks @laushinka, adding below some more discussion points for transparency:
1. Replacing the provider domain name with an icon as described in https://github.com/gitpod-io/gitpod/issues/5122#issuecomment-898287715 could help but I'd suggest to be frugal with adding more icons when possible. Besides this, using the provider icon would work only as a provider type indicator as the domain could be different for self hosted providers which could be fine!
2. Removing the provider domain name as described in https://github.com/gitpod-io/gitpod/issues/5122#issuecomment-897807021, could resolve the issue for most cases but could still keep the project hidden. FYI, [GitLab supports up to 20 levels of subgroups](https://docs.gitlab.com/ee/user/group/subgroups/).
3. Adding a tooltip seems like a good boring (simple) solution forward, in the context of this issue, which is also a **two-way door decision** as we could easily revert this with little to zero impact in the future.
4. [Middle truncation](https://github.com/gitpod-io/gitpod/issues/5122#issuecomment-895863295) may seem a little bit strange but possibly is the best solution in the long run as this would be also needed for the tooltip content when the path is really long due to size contraints we may enforce for tooltip component.
