### ISSUE TITLE
Embeddable widgets for documentation

### ISSUE THREAD

**Issue by beriberikix** [gitpod-io/gitpod#5201]
https://twitter.com/beriberikix/status/1426348601806970882?s=19

The long form context is in the Twitter thread but we'd love to leverage Gitpod as part of our documentation by embedding an environment with samples so that users can run them right from the browser. This would ideally be a slimmed down UX, so not the full IDE, with some level of customization and the ability to pass in runtime information (like user or project metadata.) [oEmbed](https://oembed.com/) is the relevant standard to adopt and embedly is an extremely popular service to consider that simplifies embedding widgets. 

In the Twitter thread I reference https://termible.io/ as an example, which Gitpod already offers 99% of the functionality, and then some.

I'm sure there's both technical and product/business questions to address before considering this FR but I personally think this is a gap in the overall market and as a developer platform would consider this something worth paying to use! 

/cc @mikenikles

**Comment by jankeromnes** [comment]
Hi @beriberikix, many thanks for this cool feature request! I love this idea, and have also always wanted to have such a Gitpod embed / runnable code sample for any language / framework.

I think these could be good potential next steps here:

- [ ] Discussing this idea with our product team, in order to maybe add it to our roadmap

- [ ] Building a quick prototype with a `iframe` that opens a Gitpod context URL (can point to any repository, pre-open any specific file, auto-run some custom scripts, and pass in various env variables for configurability) and see what using it feels like

> This would ideally be a slimmed down UX, so not the full IDE, with some level of customization and the ability to pass in runtime information (like user or project metadata.)

The slimmed-down UX and/or customizable IDE/terminal layout would probably be the biggest work item if implemented in full. Would you have any rough idea of what this should ideally look like? (E.g. some syntax-colored code sample + a run button + a terminal?)

However, you can already pass in today, via the Gitpod context URL:
- the project URL, file path, custom env variables
- the repository can specify init scripts that Gitpod should run on start
- the user is currently determined by the GitHub/GitLab/Bitbucket login

> oEmbed is the relevant standard to adopt and embedly is an extremely popular service to consider that simplifies embedding widgets. 

This seems like a very useful pointer for embeds in general. Thanks again!

**Comment by beriberikix** [comment]
> Would you have any rough idea of what this should ideally look like? (E.g. some syntax-colored code sample + a run button + a terminal?)
That's spot on. I'd also love an Edit button that opens a full Gitpod experience, either in the iFrame or a new page.

A lot of documentation platforms already have the syntax highlighting (ex. we use [Docusaurus](https://docusaurus.io/docs/markdown-features/code-blocks)) so I was originally thinking of that being not in the slimmed UX embed but that actually makes sense. Often times samples come in multiple languages so you see [code tabs](https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks) so the user can toggle between the same sample but in a different language. From there it would be easy to pass in different URLs to the embed depending on which sample was selected.

**Comment by akosyakov** [comment]
VS Code relies on to be run in the top browser context, some features won't work in iframe.

**Comment by beriberikix** [comment]
Got it. So that makes more of the case for the slimmed down UX for an inline iframe and a link to open a new window for the full gitpod experience.
