### ISSUE TITLE
Image Builder Runs out of disk space - Unable to start Gitpod

### ISSUE THREAD

**Issue by jrdzha** [gitpod-io/gitpod#5243]
### Bug description

Cannot launch Gitpod with error:

`Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: `

### Steps to reproduce

Launch any gitpod workspace in the US.

### Anything else?

We are relying on Gitpod for our main work and are on the Professional plan for the whole team. We've experience a handful of Gitpod failures in just the last week that makes Gitpod extremely difficult to use.

**Comment by aledbf** [comment]
@jrdzha please try again

**Comment by jrdzha** [comment]
This has been resolved on our end. I'm wondering what Gitpod is doing about general stability? We are scaling our team, and cloud dev environments are a big part of our workflow, so it would be good to know if Gitpod is actively dealing with the stability problems, and what we can expect in terms of stability going forward? Thanks.

**Comment by atduarte** [comment]
Hi @jrdzha. I understand the frustration, and we are actively working to deal with the problem. Related issue here: https://github.com/gitpod-io/gitpod/issues/5253

**Comment by svenefftinge** [comment]
We have had this yesterday again. It affects every workspace start that is based on a custom image or dockerfile. Even for restarts of existing workspaces. [Logs from yesterday.](https://cloudlogging.app.goo.gl/3dQAwDX33LnUYjwf9)

**Comment by csweichel** [comment]
> This has been resolved on our end. I'm wondering what Gitpod is doing about general stability? We are scaling our team, and cloud dev environments are a big part of our workflow, so it would be good to know if Gitpod is actively dealing with the stability problems, and what we can expect in terms of stability going forward? Thanks.

We have a number of measures in place that address stability:
- w.r.t. to this concrete issue we're about to [roll out a new version of the image builder](https://github.com/gitpod-io/gitpod/issues/5475) which does not suffer from the out-of-disk space issue by design
- we are heavily investing in more thorough testing prior to new deployments to avoid breaking things on updates - at the same time are we refining our operating procedures w.r.t. to gradual rollouts further minimising change-related stability issues
- we are refining our observability posture adding more sensitive alerts that will hit much before issues become user impacting

We clearly have not hit our own uptime goals lately, and do run further internal measures to improve this situation.
