### ISSUE TITLE
[ws-manager-bridge] Regular clean up doesn'T seem to work

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5254]
The regular clean up in ws-manager-bridge should automatically mark workspace instances to 'stopped' if they have been hanging in 'stopping', 'preparing' or 'unknown'.

Telling from the [log entries](https://cloudlogging.app.goo.gl/C9LdZdcTspvm9SuY8) it seems like the query doesn't find workspaces that hang in 'stopping'.

**Comment by csweichel** [comment]
I reckon we tread lightly here. Looking at this on a "per-phase level":
- **preparing**: this should already be fixed in #5055. If we can find instances where this did not happen in time, we likely have a bug here we should fix.
- **stopping**: if we just introduced a timeout after which we consider an instance that was stuck in stopping stopped, we likely hide/shadow an actual problem. Also, what happens if the status of that instance actually changes after we've (falsely) marked it as stopped?
There are valid cases in which we could mark a _stopping_ instance as _stopped_ even though we haven't seen a status update telling us so: when a workspace instance's cluster is **no longer registered** - that's not the same as the cluster being unknown. Right now we don't keep a record of previously registered cluster, but remove their entry from the database when we de-register them.
- **unknown**: has a similar argument to _stopping_. Unknown states are a bug in ws-manager, hence should be repaired rather than hidden. Much like with stopping, at this point we don't actually know if the container is still running, if there's a backup, if it will change its state in the future.

For stopping and unknown we could introduce such a "force to phase" mechanism also, but should do so with generous timeouts, and be very loud about this when it happens.

**Comment by JanKoehnlein** [comment]
Not sure what the action on this could be. @svenefftinge mentioned a predicate in `ws-manager-bridge` to be checked ([this one?](https://github.com/gitpod-io/gitpod/blob/c00a164e49a3cc48eb38aefc9bac315fe9e5c9ce/components/ws-manager-bridge/src/meta-instance-controller.ts#L41)). Other than that I'd close this issue in favor of new, more actionable ones

**Comment by svenefftinge** [comment]
I cannot remember unfortunately, let's close this for now.
