### ISSUE TITLE
Nothing to see here... 🦗 Port 3000 didn't respond

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#531]
- I have started my application.
 - I was asked whether I want to expose port 3000
 - I hit yes, I selected open external
 - I got the Nothing to see here... page

Here is my ws: [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/9db93cf9-b3c7-4192-b648-2131ecc2b521)

**Comment by kittaakos** [comment]
Reopening from the status bar solved the issue.

**Comment by kittaakos** [comment]
This seems to happen with other repositories too.

**Comment by alesanchezr** [comment]
Why don't you expose the port from the beginning using a gitpod.yml?
```yml
ports:
    - port: 3000
```

**Comment by jankeromnes** [comment]
The problem is that `Open Browser` or `Open Preview` currently don't wait for the port to be actually exposed. So if you open a preview too quickly, the port may not be properly exposed yet, leading to this error page.

Pre-exposing the port can indeed work around this problem (because it adds more time between expose and preview).

I'd like to properly fix this issue, but making `Open Browser` wait for the port to be exposed adds a delay between the user click and the actual pop-up, which causes browsers to block it (because it looks like spam).

Another avenue to fix this could be to make the preview URL wait a little bit more, or retry a few times, so that it becomes more robust against timing issues between "expose" and "preview".

**Comment by boghyon** [comment]
Is there any progress in resolving this issue?

**Comment by jankeromnes** [comment]
Hi @boghyon! This is an old issue that has been resolved since (and should be closed), but you're probably referring to the current ongoing incident:

https://github.com/gitpod-io/gitpod/issues/3118

We're planning to deploy a fix for that tomorrow.

**Comment by persyjr** [comment]
I had the same issue, the reason is because the port isn´t configurate correctly, maybe you port changed.
You can write in the terminal: $learnpack start 
after few minutes when you are conect a port.
