### ISSUE TITLE
[admin] "Stop Workspace" button may not work

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5377]
Today we had cases where we could not stop workspaces via the "Stop Workspace" button in the admin panel. 

See for example this [log entry](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-08-25T12:25:09.653Z;query=%22bronze-goose-aauhqxnv%22%20OR%20%2255492138-58b0-4b19-9833-891f5adf0590%22%0AjsonPayload.component%3D%22server%22%0Atimestamp%3D%222021-08-25T10:41:13.077Z%22%0AinsertId%3D%22s8oh00ww77bw4ebo%22;summaryFields=jsonPayload%252Fpayload%252Fmethod:false:32:beginning;timeRange=PT5H?project=gitpod-191109):
> Request adminForceStopWorkspace unsuccessful: 403/"operation not permitted: missing update permission on workspaceInstance"

The impact of the bug was rather unpleasant because the workspaces was running ToS-violating processes.

Maybe related: 
* We had blocked the user before clicking the "Stop Workspace" button.
* I expected that blocking the user would stop the workspace, but for unknown reasons this did not happen.

**Comment by corneliusludmann** [comment]
The actual problem is pretty clear:

- [`adminForceStopWorkspace` ](https://github.com/gitpod-io/gitpod/blob/757a1594c6e5f14a268833b75411e449637c9d40/components/server/ee/src/workspace/gitpod-server-impl.ts#L639) calls `internalStopWorkspace`
- [`internalStopWorkspace`](https://github.com/gitpod-io/gitpod/blob/757a1594c6e5f14a268833b75411e449637c9d40/components/server/src/workspace/gitpod-server-impl.ts#L527) calls `this.guardAccess({ kind: "workspaceInstance", subject: instance, workspace }, "update");`
- [`guardAccess`](https://github.com/gitpod-io/gitpod/blob/757a1594c6e5f14a268833b75411e449637c9d40/components/server/src/workspace/gitpod-server-impl.ts#L164) calls `this.resourceAccessGuard.canAccess(resource, op)`
- [`OwnerResourceGuard`](https://github.com/gitpod-io/gitpod/blob/82f164a024c765c12569595c96cf0d1f14b4820d/components/server/src/auth/resource-access.ts#L169) checks [`resource.workspace.ownerId === this.userId`](https://github.com/gitpod-io/gitpod/blob/82f164a024c765c12569595c96cf0d1f14b4820d/components/server/src/auth/resource-access.ts#L189-L190)
- For the admin case, `ownerId` is not the `userId` of the admin user. The question is, why did this work once or what has changed that this is now broken?
- One possible fix would be to add a `admin: boolean` parameter to the `internalStopWorkspace(...)` that skips the `guardAccess(...)` call when `true` since `adminForceStopWorkspace(...)` uses `guardAdminAccess(...)` already.
