### ISSUE TITLE
[ws-daemon] Internal state after restarts is incomplete

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#5381]
### Bug description

If `ws-daemon` restarts we see the warning `"message":"did not find a Git working copy - not updating Git status"` when the workspace is terminated. This means the internal state is not fully reconstructed on restarts.

### Steps to reproduce

start a workspace
kill `ws-daemon` pod
wait until the new pod is ready
stop workspace

check `ws-daemon` logs

### Expected behavior

No warnings.

**Comment by csweichel** [comment]
we should also be able to reproduce this using a unit test against https://github.dev/gitpod-io/gitpod/blob/2c70b97ac1ed5b5ec8856e49f5c0551637a37092/components/ws-daemon/pkg/internal/session/workspace.go

**Comment by rl-gitpod** [comment]
@aledbf I cannot reproduce this. I tried using kubectl delete on the ws-daemon pod and kill -9 on the ws-daemon after exec-ing into it. Any other suggestions?

The logs are [showing this error in another ws ](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-09-28T06:53:02Z;query=%22ws-daemon%22%0A%22did%20not%20find%20a%20Git%20working%20copy%22%0Atimestamp%3D%222021-09-28T06:53:02Z%22%0AinsertId%3D%22zgc47uxhs23db1g1%22;timeRange=PT15M?project=gitpod-core-dev) where it looks like the CheckoutLocation is empty so [this branch](https://github.com/gitpod-io/gitpod/pull/5879) shows a different error now in that case to help differentiate.

**Comment by rl-gitpod** [comment]
I randomly selected 20 workspaces where this error was reported in prod and all of them were ghost workspaces which do not have a checkout location and so are expected to output this error. In looking for ways to guard against this unnecessary logging (userID==all 0's==system user) I accidentally managed to repro the actual problem!

This workspace was started using a template and does not have a checkout location on disk:

```
$ cat /mnt/disks/raid0/workspaces-staging-rl-ws-daemon-5381/bf124297-0f00-48c8-a04b-64223ccf89e8.workspace.json
{"location":"/mnt/workingarea/bf124297-0f00-48c8-a04b-64223ccf89e8","checkoutLocation":"","createdAt":"2021-10-01T0
3:09:11.692091302Z","doBackup":false,"owner":"86719d85-4e1b-4861-8c5c-d676944c6f15","metaID":"lime-alpaca-1lx6z1cr"
,"workspaceID":"bf124297-0f00-48c8-a04b-64223ccf89e8","lastGitStatus":null,"fullWorkspaceBackup":false,"contentMani
fest":null,"serviceLocNode":"/mnt/disks/raid0/workspaces-staging-rl-ws-daemon-5381/bf124297-0f00-48c8-a04b-64223ccf
89e8-daemon","serviceLocDaemon":"/mnt/workingarea/bf124297-0f00-48c8-a04b-64223ccf89e8-daemon","state":"ready"
```

Once it is in this state, it stays that way and it on workspace stop it no longer reports the number of changes since it cannot determine the git status of an empty location.

No luck repro-ing since.

**Comment by csweichel** [comment]
We've been unable to reproduce this.
