### ISSUE TITLE
sometimes same url can't open 

### ISSUE THREAD

**Issue by iam-frankqiu** [gitpod-io/gitpod#540]
**Describe the bug**

this url, https://f5a0888a-e0f4-4ffa-8946-709e5963e69a.ws-ap0.gitpod.io/, could open before, but i can't open today.
**To Reproduce**

**Expected behavior**

anytime i can open same url.

**Comment by meysholdt** [comment]
hi Quanhu,

that URL belongs to a Gitpod-Workspace and only valid while the workspace is running. When you try to access the URL a day after you used the workspace, it won't be valid anymore, because either you have stopped the workspace or because the workspace timed out after not being used. 

Please open your dashboard: https://gitpod.io/workspaces/. There you will see a list of all workspaces that you have used so far. When you click on "start" for a workspace, it will become available immediately, but it will have a new URL.

Let me know if this helps :)
