### ISSUE TITLE
Gitpod Self-Hosted on Rancher Kubernetes Engine (RKE)

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5410]
Rancher Kubernetes Engine (RKE) does not currently work with Gitpod Self-Hosted but we would like to support the platform in the future. In this GitHub issue members of the community can organise and potentially work together to implement the necessary changes.

edit: the community has [identified a workaround](https://github.com/gitpod-io/gitpod/issues/5410#issuecomment-933905111). Please come join https://www.gitpod.io/chat in the #self-hosted-rke room.

**Comment by jgallucci32** [comment]
We have been using RKE since 0.5.0 and have been running stable with 0.6.0 for the entire year. We just upgraded from RHEL7 to RHEL8 on our RKE nodes and it appears to be working just the same. What exactly isn't working for you?

**Comment by kevinraymond** [comment]
@jgallucci32 - I saw in a different issue (don't have it handy but from January I think) that y'all were struggling with Gitpod+Harbor ... did y'all ever get Harbor working? I've got Gitpod 0.10.0 working well on RKE2 2.59 except for this registry issue. 😞

**Comment by jgallucci32** [comment]
@kevinraymond I can confirm partially Harbor is working, as we have our images pulled from there (we repackage workspace-full with our private SSL certs and store in Harbor). The part which I think you are referring to is the image-builder part of creating the workspace images with the Gitpod layer. I recall trying to do this in Harbor but switched to using GitLab Registry and I cannot recall the exact issue as well.

What I do know is this, you must create the repositories `workspace-images` and `base-images` in the target registry as the image-builder service does not automatically create them (for some reason Docker Trusted Registry did not have this problem, but other v2 registries do). To be clear, those repositories need to be created in the registry defined in this variable
```
components:
  imageBuilder:
    registry:
      name: localregistry.domain.local/myproject/
```
For GitLab Registry I simply created a dummy project which aligned with the registry URL. For Harbor, I believe I did get it working by pushing dummy images using a similar approach by keeping the same directory path. For example
```
docker tag dummyimage localregistry.domain.local/myproject/workspace-images:test
docker push localregistry.domain.local/myproject/workspace-images:test
```

**Comment by kevinraymond** [comment]
@jgallucci32 - yep, the image-builder part is where I was stuck, specifically with that registry creation. I saw another comment about pushing up `workspace-full` tagged as `workspace-images`, which worked, though I had to tag it with `23f6ab84f910d55110992124adb21f7fe3e6494aa225e76497c5669327fee9d2` or workspace creation failed looking for that specific tag. 🤷🏻‍♂️ 

I might have to look at switching to GitLab as well for this part - good to hear that is working.

Thanks for the response!

**Comment by jgallucci32** [comment]
@ghuntley @kevinraymond I have made significant progress getting Gitpod to run RKE and got past the Docker CE issue. See https://github.com/gitpod-io/gitpod/issues/3909#issuecomment-916585668 for details.

I'm stuck as we've only ever deployed RKE with RHEL. There is a hard requirement for Linux Kernel >= 5.4 due to recent syscalls being added, so I'm exploring getting RKE on Ubuntu to see if I can get this fully operational.

**Comment by kevinraymond** [comment]
@jgallucci32 @ghuntley Good timing - I was searching for more about the tag I mentioned above (23f6ab84f910d55110992124adb21f7fe3e6494aa225e76497c5669327fee9d2), which is the only real annoying blocker at this point while deploying.

I've got Gitpod 0.10.0 running on RKE2 (v1.21.4+rke2r2) with Ubuntu 20.04 (latest AMI). I'm going to try making time over the weekend so I can share everything I've got so far. Aside from the issue with `workspace-images` above, and now a new issue with `gp` missing, it's going pretty well.

Re: the `workspace-images`, here's the entire error I get when trying to start a workspace (already created the repository like we discussed above):

```
Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: Error response from daemon: unknown: artifact gitpod/workspace-images:23f6ab84f910d55110992124adb21f7fe3e6494aa225e76497c5669327fee9d2 not found

Unknown Error: { "code": -32603 }
```

**Comment by kevinraymond** [comment]
I created [this gist](https://gist.github.com/kevinraymond/bd8c6513555e41d84d108aaae0acaee3) with a bunch of stuff that, hopefully, will help some people along the way. Happy to provide more details as necessary.

**Comment by jgallucci32** [comment]
Update: I was able to get Gitpod v.0.10.0 working on RKE. The biggest roadblock was the underlying OS. Had to upgrade from RHEL 8 to Ubuntu 20.04. Here is my current configuration validated

Gitpod v0.10.0
RKE 1.20.11
containerd 1.4.9 (installed using Docker CE, but CRI enabled for containerd)
Ubuntu 20.04 LTS

@ghuntley What details do you need for this setup and where should I post them?

**Comment by ghuntley** [comment]
Thanks for the update! 

> @ghuntley What details do you need for this setup and where should I post them?

Right here in this thread (via a gist if required) so that the information is discoverable by all. 

Assuming no knowledge of RKE. Whats involved getting Gitpod Self-Hosted running from scratch on RKE?

**Comment by jgallucci32** [comment]
The following instructions enable you to deploy Gitpod 0.10.0 onto RKE (tested with RKE 1.20.11)
1. Review instructions for deploying RKE here https://rancher.com/docs/rke/latest/en/installation/
2. On every host with Docker installed, enable CRI plugin by modifying `/etc/containerd/config.toml` as follows
```
disabled_plugins = []
```
3. Run `systemctl restart containerd`
4. Verify `cri` plugin is enabled by running `ctr plugins ls | grep cri`
5. Create cluster configuration file following these instructions https://rancher.com/docs/rke/latest/en/installation/#creating-the-cluster-configuration-file
6. Modify `kubelet` to use containerd instead of dockershim (this example is for RKE cluster.yaml)
```yaml
    kubelet:
      extra_args:
        container-runtime: remote
        container-runtime-endpoint: 'unix:///run/containerd/containerd.sock'
      extra_binds:
        - '/var/gitpod:/var/gitpod'
        - '/var/lib/containerd:/var/lib/containerd'
```
NOTE: The `/var/gitpod` binding is required for RKE deployments because kubelet is containerized
7. Follow instructions for deploying Gitpod self-hosted into a K8s cluster using the Helm chart

I used these two sources as reference coming up with the configuration for bypassing Docker Engine and using Containerd
https://gianarb.it/blog/kubernetes-1-20-dockershim-in-practice
https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/
