### ISSUE TITLE
[Dashboard] Make www.gitpod.io redirect work for logged out users

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5452]
### Bug description

If a user is NOT logged in then:

- `https://gitpod.io/chat` does not redirect to `https://www.gitpod.io/chat`

Same for any 404.

When the user is logged in 404's redirect to the website.

### Steps to reproduce

As above

### Expected behavior

`https://gitpod.io` always redirects to `https://www.gitpod.io/` if 404

### Anything else?

💭 As this involves our authentication page - discuss threat model in `#security` before merging.

**Comment by gtsiolis** [comment]
Thanks for opening this @ghuntley! This is because `chat` could be a top-level URL now with **Teams & Projects** as a team.

However, we have already added some forbidden slugs that could conflict with the dashboard pages.

https://github.com/gitpod-io/gitpod/blob/4d9754ecc7bc2105a7ad19b60ea1b8f96fca72d2/components/gitpod-db/src/typeorm/team-db-impl.ts#L19-L50

Maybe it could make sense to also add redirects for the rest of the similar redirects that are already in place for the website?
> 👀  https://github.com/gitpod-io/website/blob/d991562e1e7fb157ed683c3b23129380e0ef75c1/netlify.toml

For example, we could add a redirect but also prohibit new teams with the following URLs: `/features`, `/screencasts`, `/blog`, `/docs`, `/changelog`, `/pricing` but also `/roadmap` and `/terms`.

Cc @jankeromnes because https://github.com/gitpod-io/gitpod/pull/5131

**Comment by ghuntley** [comment]
💭 this smells of future problems related to namespace/naming conflicts as we grow.

Instead of having teams on / what if they were /team/$name?

**Comment by gtsiolis** [comment]
This was also briefly discussed in a [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1625064176314500?thread_ts=1625063886.313200&cid=C021Q4BL8E8) (internal) but didn't move forward.

Cc @AlexTugarev @svenefftinge because **Teams & Projects** crew. 🧑‍🚀 

Cc @jankeromnes because https://github.com/gitpod-io/gitpod/issues/4469#issuecomment-894016435

Cc @corneliusludmann because https://github.com/gitpod-io/gitpod/issues/4469#issuecomment-858657883

**Comment by jankeromnes** [comment]
Hmm, actually the not-redirected-when-guest problem is because this code:

https://github.com/gitpod-io/gitpod/blob/b4f362a123a280329412763977b417d03c4d3ee5/components/dashboard/src/App.tsx#L125-L127

is above this code:

https://github.com/gitpod-io/gitpod/blob/b4f362a123a280329412763977b417d03c4d3ee5/components/dashboard/src/App.tsx#L234-L245

A cheap fix could be to catch `/chat` before both of these, and redirect eagerly.

(Also, it's impossible to create a team with the slug `chat` because we [forbid that](https://github.com/marteinn/The-Big-Username-Blocklist/blob/c5d456f6af0285931c85e08d53ed7e1ac35d31fc/list.txt#L116).)

**Comment by jankeromnes** [comment]
Also, it's worth noting that team slugs are only active for logged-in users who are a member off that team.

So if I still somehow manage to create a team with a problematic slug, it would only affect me & anyone that accepted to join my team. (Also, the order of precedence is 1. dashboard pages, 2. teams, 3. 404, so I'd only affect pages that would normally be 404 for the app.)

**Comment by svenefftinge** [comment]
> Instead of having teams on / what if they were /team/$name?

👍  Given the potential name clash issues I agree compromising on the URL shortness makes sense.

**Comment by svenefftinge** [comment]
@jankeromnes this is not specific to /chat but a general issue for all redirects.

**Comment by jankeromnes** [comment]
> @jankeromnes this is not specific to /chat but a general issue for all redirects.

- Currently, no redirects work when a user isn't logged in (except specifically `gitpod.io` + no hash)
- When they're logged in, it's all 404 pages that redirect to `www.`

What is the proposed solution to make redirects work for not-logged-in users?

a. Make a list of specific redirects that sits above the `if (!user) { return <Login />; }` code (just like in https://github.com/gitpod-io/gitpod/pull/5463 but with more redirects than just `/chat`?) -- easy and already in review

b. Refactor the App router to only show the Login page for every dashboard URL that isn't 404 (e.g. show login on `/workspaces` and `/settings`, but redirect `/anythingelse` to `www.`) -- this is potentially a lot of work, because everything below `if (!user) { return <Login />; }` in `App.tsx` currently assumes there is a logged-in `user`

**Comment by svenefftinge** [comment]
a. create a list of level-one slugs (features, pricing, blog, docs, etc.) that cause a redirect.
