### ISSUE TITLE
Download workspace

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#552]
If I can't start my workspace anymore (e.g. because something is broken) I cannot access the data inside the workspace anymore. There should be a download link on the dashboard that allows me to download the latest backup of a workspace.

**Comment by GuzioMG** [comment]
Can't you download it form GitHub?

**Comment by jankeromnes** [comment]
> Can't you download it form GitHub?

From GitHub, you can only download everything that was committed and pushed.

However, a Gitpod workspace might still contain changes that you didn't commit yet (e.g. work-in-progress), or that you don't want to commit (e.g. secret credentials).

It's generally not a good idea to leave uncommitted changes in a workspace, but when it happens, you want to always be able to retrieve them. And when a workspace refuses to start (e.g. because of a bug), you have no way to retrieve any unsaved changes left inside, unless you're able to download the workspace backup (this is easy and should always work, even when the workspace cannot be restarted).

**Comment by svenefftinge** [comment]
in production
