### ISSUE TITLE
[ws-daemon] Workspace start fails with "cannot connect to daemon"

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5574]
[This error](https://console.cloud.google.com/errors/CI6hwq2sg6bx4AE?time=PT1H&project=gitpod-191109) happens quite often (> 6000 entries in the last 7 days) and seems to be user-facing (i.e. error message on start workspace). 
At least that what I just saw myself.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5574#issuecomment-915015531):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by csweichel** [comment]
At first glance this looks like an issue with ws-daemon serving the IWS socket in time. We might have a problem with the dispatch mechanism here.

**Comment by csweichel** [comment]
@aledbf and I were looking into this issue and found that this issue is mostly a workspace shutdown issue and "should not" happen during startup. 

We've found that the due to a change in ws-manager's status machinery we called `DisposeWorkspace` too early which in turn races the IWS call in workspacekit ring0, producing this error message.
