### ISSUE TITLE
automatically forward newsletter sign ups to customer.io

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#5598]
With the newsletter signup widget, website visitors have the option to sign up for emails without logging into Gitpod. 
Right now we are collecting these email addresses in a [spreadsheet](https://docs.google.com/spreadsheets/d/1DrgFXvDsLmu6kUoBHMfgYqBtqyT9kr4OHqcKX31FbXw/edit#gid=722237941). There are currently >150 email addresses. So far these email addresses are not used and forwarded to customer.io.

**What needs to be done:**
- collect emails separately depending if someone signs up for the devx email or [changelog](https://www.gitpod.io/changelog) 
- update the notification setting of existing users
- create a new user in customer.io if the email address doesn't belong to an existing user

**Next steps (according to @atduarte ):**
In order to implement this, I believe that the Gitpod app (not the website) should be responsible for the flow from form submission (or API call) to Segment updates.

1. The website would call the Gitpod app with the email
2. The app would then check whether the email is registered to decide whether to update the associated setting
3. The app publishes a Segment event (to be listened to by customer.io) with the email, user id or anonymous id, and subscription status (i.e. unsubscribed=false)
4. Customer data is upserted in Customer.io, using the email as the identifier.

**context:** 
[#696](https://github.com/gitpod-io/website/issues/696#issuecomment-894394666)
[#762](https://github.com/gitpod-io/website/pull/762)

Feel free to complement the issue in case I missed something.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5598#issuecomment-917956679):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by JanKoehnlein** [comment]
A few questions on this, as I am not familiar how we use Segment.
1) In case of an unregistered user, should we use `userId: <email>` or the `anonymousId: <anonymousId>` in the `identify` event? For the `unsubscribe` route, we use the former, while the latter keeps the association of the signup with the current session. 
2) Should we use the `traits: { email_untrusted: <email> }` as used on the website ATM, or use the email directly?
3) Is there an email verification mechanism (double opt-in) in Customer.io? 
4) Does Segment/Customer.io keep timestamps on the subscribe/unsubscribe events?

**Comment by jakobhero** [comment]
> should we use userId: <email> or the anonymousId: <anonymousId> in the identify event?

We should use both. Customer.io dictates that our users must be identified via either user ID or email. Thus, we should pass the email as userId whenever the user is not signed up yet / logged in (see [here](https://customer.io/docs/segment-destination/#converting-leads-to-customers)). We should also pass the anonymousId for the reasons you mentioned (it's not an either / or decision, userId and anonymousId are two distinct props).

> Should we use the traits: { email_untrusted: <email> } as used on the website ATM, or use the email directly?

Also do both. Using the email as userId is important for the identification of users in third party tools, as described above, but the userId will be overwritten as soon as the user logs in or signs up. Traits are personal attributes and persist until they are overwritten, so there is value in holding on to this information for us. In general, all personal attributes should be passed in traits within the identify call in the future in order to increase the compatibility of the data segment is passing to third party apps.

> Is there an email verification mechanism (double opt-in) in Customer.io?

At the moment, there is none implemented. double opt in can be introduced via a [campaign in customer.io](https://customer.io/docs/double-opt-in/), but i don't know if this is something that we are planning on doing. @ChristinFrohne, is this accurate / did i miss something?

> Does Segment/Customer.io keep timestamps on the subscribe/unsubscribe events?

Segment keeps timestamps of all events in the event metadata, but coutside of some automatic data parsing, customer.io only gives users control over the props passed in the event. Thus, if it's important to store a timestamp as a user attribute in customer.io (e.g. signup timestamp), we must pass it explicitly in the props.

**Comment by JanKoehnlein** [comment]
I am closing this without merging the proposed change because in the meta team we have serious concerns that this would inflict a bunch of security problems in the application
1) We'd allow operations to unauthorized users that cause DB changes.
2) We'd identify users by their (unverified) email address.
3) We're missing GDPR consent, in particular because email addresses are not verfied.
We should not do it this way.

Instead, we should find a better separation of the tasks for handling newsletters. 

My favorite would be to handle newsletter subscriptions entirely in customer.io. The only part in which the application currently needs to have access to the newsletter subscription information is on the subscription settings page (for authorized users). We could just show/update the subscription information stored in customer.io there and remove it entirely from the application's DB. Into the bargain, I am strongly in favor of enabling double opt-in for newsletter subscriptions (at least for unauthorized/unverified users).
