### ISSUE TITLE
Allocating resources …

### ISSUE THREAD

**Issue by ujjal-zaman** [gitpod-io/gitpod#5645]
i have delete browser local storage, cache , update browser, although this problem is solved. i have buy premium package also. please solve this issue .
gitpod is not opening. it's showing this loading message allocating resources...

**Comment by wulfthimm** [comment]
We are currently investigating that incident. Please follow our updates on https://www.gitpodstatus.com/.

**Comment by wulfthimm** [comment]
We have identified the problem and have taken actions to mitigate the problem.

**Comment by corneliusludmann** [comment]
@ujjal-zaman I'll gonna close this issue for now. Feel free to ping me if there is still an issue.

**Comment by ujjal-zaman** [comment]
Hello.
The issue isn't solved yet.
Its still showing as before.
Right now it's also appear and disappear too .
Please properly resolve this issue.after confirmation you can mark as resolve.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by corneliusludmann** [comment]
@ujjal-zaman Have you tried to re-open a workspace again?

**Comment by ujjal-zaman** [comment]
Yes .i tried reopen workspace.its still as before.
I have tried login and logout also.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ujjal-zaman** [comment]
Hrllo there
Will you please solve the issue?
I are very argent.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by corneliusludmann** [comment]
Hi @ujjal-zaman! I'm very sorry that you have trouble with the workspaces. The problem with your workspaces is not the same as we saw with the incident. However, it could be that the workspaces are in a bad shape for some reason due to the incident. I'm here to help you to get your workspaces up again but I need your assistance.

1. Do you have unsaved changes in your workspace? If not, the easiest fix is to just create a new workspace. Got to the GitHub repo and prefix the URL with `https://gitpod.io/#` and you should get a new workspace. In fact, that is something we recommend anyways and follows our concept of [ephemeral workspaces](https://www.gitpod.io/screencasts/fresh-dev-environments-for-each-new-task).
2. Nevertheless it would be good if you try to create a new workspace (instead of opening an existing one) just to make sure this works.
3. If you have unsaved data, please let me know which workspace is affected and I can try to restore the workspace. A good procedure would be that you create a new workspace for the same repo and I'll take care that you get the unsaved data in this workspace.

**Comment by ujjal-zaman** [comment]
Hello ludmann.
Thanks for your response.
I have followed your all instructions.
Delete all of workspace.and create new one.
That was showing this message for the long time
Opening IDE......

Waiting for your first response.
Thanks.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by corneliusludmann** [comment]
What I can see is that you created new workspaces and that the workspaces are running. E.g. currently there is a workspace `brown-baever-......` that is running. However, when I understand you correctly, it shows `Opening IDE` for you and you can't get into the workspace. I'll have a look …

**Comment by ujjal-zaman** [comment]
Exactly.new workspace created.but it's not opening code editor.
Showing opening ide...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ujjal-zaman** [comment]
Hello is that resolve ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by corneliusludmann** [comment]
Unfortunately, I have no updates yet. Logs look good so far, your workspace starts fine. Could you do me a favor and try again starting a workspace while you have the JavaScript console open (e.g. in Chrome with the Developer Tools that you get with `F12`) and tell me if you see error messages there?

![Screenshot_2021-09-10_18-25-34](https://user-images.githubusercontent.com/24960040/132886199-0d4f51fe-8a8f-4202-b189-993cf1a7d3ab.png)

**Comment by ujjal-zaman** [comment]
Wait a minute.lamme try it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ujjal-zaman** [comment]
Console is clear.
Didn't show anything like that .
It's taking time as starting - opening IDE

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ujjal-zaman** [comment]
Hello there
Finally opened code editor and working while it's taking lots of time
However, it's ruin our almost a day.
In future if we stuck any kinds of this error we will contact you .

Thank you so much your cooperation.
Nice to meet you man.
Have a good day.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by corneliusludmann** [comment]
Good to hear that it finally works for you again. And sorry again for the inconvenience.

**Comment by ujjal-zaman** [comment]
Hello there.
The problem appears again.
Allocating resources....
This message showing for while please fixed this issues

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by corneliusludmann** [comment]
https://github.com/gitpod-io/gitpod/issues/5752#issuecomment-922187092
