### ISSUE TITLE
Investigate clustered call patterns of the ControlPort call

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5669]
@aledbf found concerning patterns in jaeger, where it seems like at times requests would take a long time (20secs). 
since this happens when there are DB calls involved, It looks a little DB calls sometimes take that long.

We should investigate why that is. At the same time it might make sense to investigate if we can skip a few unnecessary calls.

**Comment by JanKoehnlein** [comment]
Example Jaeger trace https://www.notion.so/gitpod/Engineering-Sync-df0b15c73505414abee40e399ca01cb6#588f6328cc87496e991664ee5be9c3eb

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5669#issuecomment-917961881):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by princerachit** [comment]
## Jaeger Trace

![image](https://user-images.githubusercontent.com/32481722/135228626-04946793-25b5-4c83-ae54-75646005be3d.png)


## GKE

[Google Cloud Platform](https://console.cloud.google.com/kubernetes/pod/us-west1/prod-meta-us01/default/server-869b8d4fbb-ftkwz/details?project=gitpod-191109)

The server pod had CPU utilization spike during the duration


![image](https://user-images.githubusercontent.com/32481722/135228712-ad52e53e-84e6-453a-9098-0509af884727.png)


Other server pods did not have this spike:

![image](https://user-images.githubusercontent.com/32481722/135228740-0b776d60-3b50-4e04-bf1f-21b285a4a880.png)


## Database

### CPU

Database CPU utilization remained well under 5% during this duration

![image](https://user-images.githubusercontent.com/32481722/135228780-593b6863-36df-498e-892a-73b439508b69.png)


### Queries

MySQL Queries were under 60/s

![image](https://user-images.githubusercontent.com/32481722/135228825-65ca8256-5b32-4bdd-b0bb-fa12e8450a35.png)


### Latency

Google does not give us this metric atm. We cannot be sure if SQL had an issue or there was an issue from our side. Since SQL is more stable compared to our code and is being used in production by thousands of orgs I suspect our service had some issue. The hike in CPU util in that particular server confirms that.

## Pattern

I saw exactly same issue with [this trace](https://jaeger.gitpod.io/trace/f9d195abb7973936). The CPU utilization spiked up during this duration which led to the issue.

![image](https://user-images.githubusercontent.com/32481722/135228875-4b830e35-8243-4fdd-8a73-667fe5736fee.png)

Further it can be confirmed by [other traces](https://jaeger.gitpod.io/search?end=1632880740000000&limit=20&lookback=custom&maxDuration&minDuration=10s&service=server&start=1632880620000000) that DB calls started to spike up for this pod during the same duration:

![image](https://user-images.githubusercontent.com/32481722/135228950-f69f8ae8-b12a-4400-aef4-a74743439f6d.png)


## Next Steps
Find the route cause of CPU spike and fix it.

**Comment by princerachit** [comment]
Further investigation revealed that their was a network utilization spike:

![image](https://user-images.githubusercontent.com/32481722/135244209-90c32485-02ab-4385-be70-687a14354989.png)


and some API calls were failing too:

![image](https://user-images.githubusercontent.com/32481722/135244163-2965f13d-09ac-454d-ba27-5073f64df852.png)
