### ISSUE TITLE
Workspaces falsely reports "last backup failed: workspace does not exist. Please contact support if you need the workspace data."

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#5689]
### Bug description

On workspace timeout, the users sees `last backup failed: workspace does not exist. Please contact support if you need the workspace data.`.
But on checking, the backup is there, and also re-produced on startup.

Exmaples:
 - fuchsia-spider-384e445r (13.09., around 13:20 CEST)
 - black-sheep-xvsk5brx (14.09., around 09:05 CEST)

Internal slack discussion: https://gitpod.slack.com/archives/C01KGM9AW4W/p1631539665230200

### Steps to reproduce

Have a workspace time out (often enough?)

**Comment by csweichel** [comment]
Is this really bound to workspace timeout? I'd expect to this issue appear on any kind of regular workspace stop, although it may be racy, hence not happen always.

That said, as [@geropl pointed out](https://github.com/gitpod-io/gitpod/pull/5688/files#r708026135) the issue may have been introduced in a recent attempt to fix the unmount issue in ws-daemon.

The underlying issue that the unmount of the mark mount in ws-daemon happens during content finalization. Without this unmount the workspace container never stops because containerd cannot unmount the rootfs, hence we won't trigger the finalization in the first place.

There are two ways we can break this circle:

1. the solution that's currently implemented where ws-manager forces workspace content finalisation if we've exceeded the grace period
2. a ws-daemon dispatch based method that functions much like the former containerd workaround, except that does the unmount rather than force a workspace stop on the API plane.

We opted for the former because it was easier/less complex to implement. It would seem that it hard other adverse side effects though. We should probably move to solution 2 then.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5689#issuecomment-919791443):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
> The underlying issue that the unmount of the mark mount in ws-daemon happens during content finalization.

Ah, makes sense then. :+1:

**Comment by geropl** [comment]
@aledbf https://github.com/gitpod-io/gitpod/issues/5573 could be related, if https://github.com/gitpod-io/gitpod/pull/5688/files#r708026135 really is the issue.
