### ISSUE TITLE
gitpod requests access to all my github repos

### ISSUE THREAD

**Issue by jcayzac** [gitpod-io/gitpod#5779]
### Bug description

GitPod requests access to all my GitHub repos, not just the repo(s) I want to use with GitPod.

### Steps to reproduce

- Add your repo after `gitpod.io/#` and launch.
- GitHub asks to grant access to all repos.

### Expected behavior

GitHub asks to grant access to that repo only, or to filter which repos can be accessed. I know this is supported, because I just went through this exact flow for enabling the LogSeq app.

**Comment by jankeromnes** [comment]
Hi @jcayzac!

Thank you for the feedback.

Unfortunately, this is a limitation of GitHub's OAuth apps, which are different from "GitHub Apps". For somewhat complicated reasons, Gitpod uses both an OAuth app and a GitHub app:

- OAuth app: Works with scopes
  - Used to log in to Gitpod (only requires a valid email address)
  - Works even if you provide no access at all (i.e. Gitpod can clone your public repositories, but not write to them)
  - You can grant write access to all repositories (unfortunately, this is not configurable per-repository, but it's also not required if you don't want to push commits from Gitpod)
- The [GitHub App](https://github.com/apps/gitpod-io): Works only when installed in an org / for a repository
  - Used to trigger webhook events when there is a push to your repository (in order to continuously run [prebuilds](https://www.gitpod.io/docs/prebuilds/) to accelerate your workspaces)
  - Must be installed specifically for an org & a repository (or all repositories of an org) -- here, you can configure which repository Gitpod can access, but you can only give it access to repositories you actually own (i.e. no open-source public repository you don't directly own)

As you can see, both have limitations that make it necessary to keep using both (if we had only the OAuth app, Gitpod could not trigger any Prebuilds -- and if we had only the GitHub App, you wouldn't be able to open public open-source repositories in Gitpod unless you're actually an owner/administrator of them).

But, we've tried to make the access as configurable as possible. You can always audit what permissions Gitpod has in https://gitpod.io/integrations and adjust/revoke any permissions you no longer wish to grant (there is even a link to manage these permissions directly on GitHub).

Hope this helps! Please let us know if you have any additional questions.

**Comment by jcayzac** [comment]
Thanks for the long explainer.
