### ISSUE TITLE
[blobserve] Should serve pre-compressed static assets

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#5804]
Similar to what [caddy provides](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/fileserver/staticfiles.go#L284-L310) in order to avoid compressing every request.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5804#issuecomment-928915669):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by princerachit** [comment]
Have we analyzed performance improvement that we would get if we do this?

**Comment by aledbf** [comment]
@princerachit gzip is one of the more expensive operations. We already have this approach implemented in [dashboard](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/leeway.Dockerfile#L13-L17)

**Comment by princerachit** [comment]
This is being discussed internally in this [slack thread](https://gitpod.slack.com/archives/C01KGM9AW4W/p1632995338430400). There are no prebuilt static assets in blobserve. The relevant assets are downloaded on demand and then used based on the requests. Another catch is the fact that the blobs that are downloaded by blobserve in order to serve client requests can be GCed too.

It is unclear if having a background worker to compress the files in the downloaded blob would be a good idea or compressing it during request processing and storing it for further access would be better.

**Comment by akosyakov** [comment]
We are not taking new feature requests at the moment.
