### ISSUE TITLE
is prolog supported

### ISSUE THREAD

**Issue by bheemaiaha** [gitpod-io/gitpod#589]
I am trying to execute prolog code and am getting the error swipl is missing, which is the prolog compiler? can you add prolog ?

**Comment by meysholdt** [comment]
This should work, but you'll need to install the swipl compiler for your project. 

You can [do this by creating](https://www.gitpod.io/docs/42_Config_Docker/) a `.gitpod.yml` and a `Dockerfile` for your project. In the Dockerfile you can run the [recommended instructions to install Swipl on Debian](http://www.swi-prolog.org/build/PPA.txt). 

Another approach would be to try the [official `swipl` docker image](https://hub.docker.com/_/swipl/) instead of installing swipl on top of Gitpod's `workspace-full` docker image. However, then you would looses support for all other languages except prolog.

In case there are VS Code Extensions or Language Servers for Prolog: They can also soon be installed per project. You might want to subscribe to issue https://github.com/gitpod-io/gitpod/issues/433.

**Comment by jankeromnes** [comment]
Hi @bheemaiaha! FYI [Gitpod now supports VS Code extensions](https://www.gitpod.io/blog/vscode-extension-in-online-ide/).

I don't know if there is a good extension for Prolog, but if there is, you can now download the `.vsix` file, and drag-and-drop it into Gitpod's extension panel, and it should just work. ✨
