### ISSUE TITLE
High Database Load

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5906]
[We just saw a spike in Load on the US Database](https://console.cloud.google.com/logs/query;query=logName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcloudsql.googleapis.com%252Fmysql-slow.log%22%0Aresource.labels.region%3D%22us-west1%22;timeRange=PT24H;cursorTimestamp=2021-09-28T12:25:27.028734Z?project=gitpod-191109). This did not do any harm today; However, if such a spike peaks a bit higher, we'll suffer degraded service performance. 

![image](https://user-images.githubusercontent.com/239422/135088668-f5e26e49-2a05-4af9-8d2c-7241eed693b0.png)

On the US-DB we have the "mysql_slow_log" enabled and thereby can see slow queries in the logs. [Search for](https://console.cloud.google.com/logs/query;query=logName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcloudsql.googleapis.com%252Fmysql-slow.log%22%0Aresource.labels.region%3D%22us-west1%22;timeRange=PT24H;cursorTimestamp=2021-09-28T12:25:27.028734Z?project=gitpod-191109) 
```
logName="projects/gitpod-191109/logs/cloudsql.googleapis.com%2Fmysql-slow.log"
resource.labels.region="us-west1"
```
to find them. I see a bunch that take longer than one second. 

The general_log (logging of all queries) is only enabled in EU, but not US.

**Comment by geropl** [comment]
Looking at the linked slow logs this seems to be caused by queries of the form:
```
SELECT `pws`.`id` AS `pws_id`, `pws`.`cloneURL` AS `pws_cloneURL`, `pws`.`commit` AS `pws_commit`, `pws`.`projectId` AS `pws_projectId`, `pws`.`branch` AS `pws_branch`, `pws`.`state` AS `pws_state`, `pws`.`creationTime` AS `pws_creationTime`, `pws`.`buildWorkspaceId` AS `pws_buildWorkspaceId`, `pws`.`snapshot` AS `pws_snapshot`, `pws`.`error` AS `pws_error` FROM `d_b_prebuilt_workspace` `pws` WHERE `pws`.`buildWorkspaceId` = '...';
```
which we execute much more since recently.

Also, we seem to be lagging an index on `buildWorkspaceId`. While it's in the [code](https://github.com/gitpod-io/gitpod/blob/9ffcfd487fcf327838e1c4910eaa60bba1eadbe0/components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace.ts#L51-L53) the DB does not know about it:
![image](https://user-images.githubusercontent.com/32448529/135225614-059090c6-82fc-48f2-9fcd-ca3446b89b78.png)

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5906#issuecomment-929926966):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by AlexTugarev** [comment]
@geropl that's definitely something we need to optimize. In the mentioned timeframe such queries take +1 s in most cases. I'm just not sure if this is cased by high load, or casing the high load 🤷🏻‍♂️ 

Another instance, which may impact the perf a lot more is `workspaceDB.findSessionsInPeriod`, which has a footprint of 
> Query_time: 12.442992  Lock_time: 0.000185 Rows_sent: 22141  Rows_examined: 88553

**Comment by geropl** [comment]
> high load, or casing the high load

We cannot distinguish here, but past experiences shows it's always a host of small queries generating the load. :-) 

> Another instance, which may impact the perf a lot more is workspaceDB.findSessionsInPeriod, which has a footprint of

Yes, that's a long-standing and known issues with our payment/billing infra. We could easily compact these (to not require 22k rows to be sent :grimacing: , but never did so, yet). One of the many things I hope we get rid of when we tackle payment.

However, in the light of this only happening in US, and to tackle the low-hanging things first, let's add the index.

**Comment by AlexTugarev** [comment]
<img width="1156" alt="Screen Shot 2021-10-01 at 11 33 49" src="https://user-images.githubusercontent.com/914497/135599121-4dd17458-e6ed-443f-8b5c-e4716a98a2f0.png">
<img width="1478" alt="Screen Shot 2021-10-01 at 11 35 57" src="https://user-images.githubusercontent.com/914497/135599124-7f52e9ad-9202-456f-919d-a412aa9a6360.png">


Reopening, because the d_b_code_sync_resource queries are even hotter than the prebuild queries.

**Comment by AlexTugarev** [comment]
Closing with follow up https://github.com/gitpod-io/gitpod/issues/6004
