### ISSUE TITLE
run vscode commands via gp command

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#5934]
It would be great to run any kind of vscode command via the command line for example with your gp tool.

This could be for example a run command in vscode, so that I run a command and automatically attach to a process,...

**Comment by akosyakov** [comment]
We used to have it via the upstream VS Code, but then it was removed because of security considerations. I am not sure whether we would like to introduce something like that in our `code` cli. We need to understand security implications as well, i.e. any script which you run then can call any VS Code commands potentially doing some in GitHub for instance on your behalf.

And we for sure won't add it go `gp`, since it should be agnostic to the editor.

**Comment by konne** [comment]
@akosyakov
Okay, I fully understand your concern about being agnostic to the editor.

I don't see the security issue, because I could develop my own extension for vscode that can do that and just add this as a preinstall task. I just like to avoid this overhead to do such simple things.
