### ISSUE TITLE
Feature Request: Snapshot Tracker

### ISSUE THREAD

**Issue by hpssjellis** [gitpod-io/gitpod#603]
Snapshot Tracker

**1. Monitor and delete old Snapshots.**
 
I have saved and shared links to a few snapshots. I really like this ability, but I am curious if we can delete old snapshots after we have made better snapshots?

2. See who has used the snapshot. Similar to on Github if you click a repositories # of forks, you get a list of everyone who has forked your repository, **in a snapshot monitoring window to click on the snapshot and see all the children snapshots of that workspace**, (who has done it and ways to communicate would be nice but not needed). The important part would be, to be able to track an improvement to your snapshot. 

Presently this will be easy to do over social media. "Send a reply with the snapshot link if you improve my snapshot"

**Comment by meysholdt** [comment]
hi Jeremy, 

I fully agree that Gitpod should have a way to list and delete Snapshots. 

I'm a bit undecided about the monitoring feature because currently users of a snapshot are not being monitored and we surely don't want to surprise them in a bad way. Is this something you would want to use in an education/classroom setting?

In case you work with snapshots that require many manual steps (when creating them) which you plan to update frequently, there is an alternative setup, which I believe can work better:

Git-branches + `gitpod.yml` + prebuilt workspaces can deliver almost exactly the same user experience as snapshots: Instead of manually creating the desired workspace state, you script it in `gitpod.yml`'s [tasks.init](https://www.gitpod.io/docs/44_Config_Start_Tasks#code-classlanguage-textinitcode-command) and the [Gitpod App](https://github.com/apps/gitpod-io/) executes your script to create a prebuild. When a user opens the git-branch, the prebuild will be loaded. That's as fast as loading a snapshot. While this is a bit more effort to set up, it has a few advantages over snapshots:
* much easier when you often update your snapshot
* the URL doesn't change when the snapshot changes
* users can feed back changes via regular GitHub-PRs.
* you have the complete version history in Git.

**Comment by hpssjellis** [comment]
@meysholdt 

> I'm a bit undecided about the monitoring feature because currently users of a snapshot are not being monitored and we surely don't want to surprise them in a bad way.


Good point. The ability to delete snapshots would be the most important, social media can handle the updating of snapshots.

Also good point about tasks.init, I will look into that.

**Comment by hpssjellis** [comment]
Really surprised there isn't a way on the Gitpod.io site to share snapshots. I would really like to see the snapshots other people are working on. I will also ask on the community.
