### ISSUE TITLE
[teams and projects] Use Git host repository IDs instead of their repo names/slugs

### ISSUE THREAD

**Issue by ajhalili2006** [gitpod-io/gitpod#6060]
## About this Issue

The current form of URLs for projects may break if there are two repos with same name (but on different namespaces/orgs), similar to this one below:

```markdown
<!-- a lot of URL encoded stuff for GitLab repos on teams -->
https://gitpod.io/t/recaptime-dev/Custom%20Docker%20Images%20for%20CI%20and%20CD
```

Instead, project URLs in Gitpod should be in form of `https://gitpod-host.here.tld/projects/git{hub,lab}/repo-id`, where:

* `git{hub,lab}` - is the Git provider configured by the instance admin (currently instance admins cannot add more than one GitLab instances to use yet)
* `repo-id` - is the repository ID (or in the case of GitLab, project ID) from the API requests during project addition

**Comment by jankeromnes** [comment]
Many thanks for the helpful feedback!

- [x] Relatedly, we're currently discussing using GitLab's project URL slugs instead of full-text name in URLs: https://github.com/gitpod-io/gitpod/issues/5847

- [ ] I agree that there should also be a de-duplication check (e.g. to append a `-1` to the slug if the new slug already exists in your Team -- we even had that because we added two projects called "Gitpod" from different orgs 🙄 made it impossible to use one of them until we removed the other)

**Comment by ajhalili2006** [comment]
It's still in the backlog, I'm just bumping to ensure stale[bot] doesn't distrub again.
