### ISSUE TITLE
Gitpod Dashboard. Faster and safer way to delete Gitpods

### ISSUE THREAD

**Issue by hpssjellis** [gitpod-io/gitpod#611]
I have been making and testing several Gitpod's, when deleting old workspaces it is slow and tedious. 

Also I have sometimes deleted a workspace that I wanted to keep intact. 

Could there be an easier way to lock an important workspace and delete several other workspaces all at once, perhaps with a delete checkbox beside it. A locked symbol would indicate something that needs at least 2 steps before it can be deleted.

**Comment by jankeromnes** [comment]
@hpssjellis interesting suggestion! Thanks. Note that you don't have to delete old workspaces (you can keep them around almost forever).

Until we figure out a better UX for your use case, maybe a workaround can be renaming valuable workspaces (e.g. to "My demo 1"), so that you can easily delete other workspaces in your list that don't have custom names.

**Comment by hpssjellis** [comment]
> Until we figure out a better UX for your use case, maybe a workaround can be renaming valuable workspaces (e.g. to "My demo 1"), so that you can easily delete other workspaces in your list that don't have custom names.

Yeh @jankeromnes that is what I started doing and yes it solves that problem.
