### ISSUE TITLE
Not Cloning

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#612]
**Describe the bug**
Hi- I've tried opening several different git files directly from github using the chrome extension, and keep getting the "red" logo. On my dashboard I have:

"Last run a few seconds ago: An error occurred during `git clone`, the repository or branch could not be accessed."

These respositories have been running properly with gitpod and not been modified since last working, so I'm thinking the issue is potentially with an update to the platform or a server issue?

**To Reproduce**
Use gitpod chrome extension and open repository (tried with several accounts and computers, same response).

**Expected behavior**
Normal opening of file.

**Comment by meysholdt** [comment]
Hi Colby,

thank you for bringing this up. I tried https://gitpod.io/#https://github.com/theia-ide/theia/blob/master/package.json via the Chrome Browser extensions and it works just fine. 

If the repositories you are trying this with are public, could you let me know the names of the repositories so that I can try to reproduce the issue?

Perfect would be if you do a right mouse-click on the chrome-extension-provided Gitpod-button and do "copy link" and post the link here.

**Comment by ColbyWTaylor** [comment]
Thank you for a quick reply!

Here's one that was working fine yesterday:

https://gitpod.io/#https://github.com/4GeeksAcademy/flask-rest-hello

I also tried the link you sent, and it fails for me as well- is it possibly a profile issue?

**Comment by ColbyWTaylor** [comment]
And... now it is working for all the users that were having the issue- didn't do anything different, just retried.

**Comment by ColbyWTaylor** [comment]
Actually, the issue has started again. Attached is a screenshot from a user:

![Image from iOS](https://user-images.githubusercontent.com/16373392/59149630-b34a0700-89e5-11e9-8ecb-6a5aa301acca.jpg)

**Comment by meysholdt** [comment]
There was indeed an issue with a hard drive. I've fixed that. Can you try again? I'm sorry for the inconveniences :(

**Comment by meysholdt** [comment]
I believe this is fixed. Please reopen if I missed something.

**Comment by ColbyWTaylor** [comment]
Works great again, thank you!
