### ISSUE TITLE
Gitpod Erasing File Content

### ISSUE THREAD

**Issue by jferragut** [gitpod-io/gitpod#615]
**Describe the bug**
While working on any workspace, occassionally Gitpod will delete the contents of a file during the build process. This causes the file to be blank without a way to revert.

**To Reproduce**
1. open a gitpod at a repository location (`gitpod.io/#your_repo_url`)
2. work on files

Appears to occur when you use `npm run start`

**Expected behavior**
Should be able to start server and build project without having file content erasure.

**Comment by svenefftinge** [comment]
We are all working with Gitpod every day. I have never seen nor heard about such a problem.
Could you provide an example project, with which you have experienced the problem?

**Comment by alesanchezr** [comment]
The only time I've seen this error in Gitpod is when there was a hard-drive issue in some of the workspaces, basically everything was read only on the workspace and when you opened a file and try to save it, it will erase the content of the file instead of update it.

Just as a side note I remember Cloud 9 having a similar issue (erasing file contents) because the browser was caching the content of the files for faster re-loading, if the content of the file had changed in the hard drive since the last time (because you open them in another computer/browser, etc) you could partially or totally loose the file content.

**Comment by svenefftinge** [comment]
Ah, yes, indeed it could happen 'when a disk is full' which happened on a node over the weekend.

**Comment by ColbyWTaylor** [comment]
Hi! Experienced the same issue over the last ten minutes here:

https://d74f7b56-f27e-4108-9902-a14e24373bd0.ws-us0.gitpod.io/#/workspace/IMS-Front-End

We tried running the server, and it would delete the content of several files that we had open. Luckily hadn't gone too far, but still very confusing until we realized what had occurred.

**Comment by geropl** [comment]
This is definitely not a 'disk full' case, just checked.

**Comment by ColbyWTaylor** [comment]
Just thinking further- it did eventually stop giving the issue in the same session. When talking to my colleague, they said that previously it went away after stopping and starting again. Whether that is a definite factor or enough time elapsed and it seemed to work by coincidence I'm not sure, but wanted to mention in case it was of any help.
