### ISSUE TITLE
[Prebuilds] Increase timeout and/or make it configurable

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#6283]
The current prebuild timeout is set to 1h. I'm working with some large projects that require more time to compile everything, up to 3 hours given current estimates.

Related to this, it would be a good user experience to allow a configurable timeout per project.

**Comment by tobiasdiez** [comment]
Is there a ETA for when the build times is increased? For https://github.com/sagemath/sage we are currently also above the 1h mark.

**Comment by georg480** [comment]
My prebuild is aborted after one hour, is there a parameter with which I can change the time? The option (Incremental Prebuilds
Enable Incremental Prebuilds Beta) for is also active.

**Comment by Trott** [comment]
> is there a parameter with which I can change the time?

As far as I know, the answer is still "no" but I want to share a workaround I've done that has helped me out a lot.

Here's the GitPod YAML config for one of my projects:

```yaml
tasks:
  - init: ./configure && timeout 45m make -j16 || true
```

The `timeout 45m make -j16 || true` cause `make -j16` to run for 45 minutes. After that, it is terminated but the `|| true` causes a success status code to be provided rather than a failure status code. Since my builds take more than an hour, but usually less than an hour and 15 minutes, that gives me a very big head start on my builds when I open the workspace. This depends on having a build step that can pick up where it left off rather than needing to start over.

**Comment by tobiasdiez** [comment]
Prebuild still timeout after 1h.

**Comment by rober-m** [comment]
Please, add configurable timeout for projects that take longer than 1h! 🙏

**Comment by svenefftinge** [comment]
Adding the possibility for configurable timeouts makes a lot of sense for usage-based plans (to be released soon).
