### ISSUE TITLE
Increase timeouts for shared running workspaces

### ISSUE THREAD

**Issue by mfulton26** [gitpod-io/gitpod#6300]
When [sharing a running workspace](https://www.gitpod.io/docs/sharing-and-collaboration#sharing-running-workspaces) if I don't do anything in the workspace for ~30 minutes then it times out and stops. At such point the person(s) who were using the workspace I shared with them are no longer able to access it. Sharing a running workspace is great because I don't have to share access to code projects that I don't want public.

My primary use case at the moment for extending timeouts while other users are using my shared running workspace is for conducting software engineering programming tests. The timeout means I as the interviewer have to remember to go do something periodically in the workspace (like run `ls` in the terminal 😂) to keep it running. If I forget then the candidate will get an error message about permissions and has to ping me to fix it.

I like some feature to extend the timeout whenever shared users are using the shared running workspace. Thanks!

**Comment by loujaybee** [comment]
Some additional use-cases for extended timeouts, or greater configuration/control around timeouts. 

* Companies who are passing the dev environment about between users, e.g. QA (it could be argued here, that the better option for the user might be to try and ensure environments have all the necessary configuration within them, rather than requiring longer static environments). 

Also related [internal conversation](https://gitpod.slack.com/archives/C01KGM9DVRC/p1637074086120800).

**Comment by akosyakov** [comment]
Have you tried snapshots instead: https://www.gitpod.io/docs/sharing-and-collaboration#sharing-snapshots. It will take the snapshot of your current workspace which can be later instantiated by any user async. In such way you don't need to share running workspace.

**Comment by mfulton26** [comment]
In my use case during a technical interview I don't want the candidate to have a link they can share with others for the coding problem after the interview and I want access to the code the candidate wrote after the interview so unless there is a way to invalidate a snapshot URL I think for some use cases sharing a running environment is best.

**Comment by jimmybrancaccio** [comment]
STAHP stalebot! 😠
