### ISSUE TITLE
Problem "Invalid Host header" when using webpack (vue cli)

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/gitpod#634]
https://github.com/gitpod-io/gitpod/issues/26
You can set vue.config.js in
I know that I can correct it.

But this is felt to be against frictionless coding.
So it feels good to be able to use it without this setting.

**Comment by jankeromnes** [comment]
Thanks @mouse484! You make a great point.

And I agree, any bug that happens frequently on Gitpod should ideally be fixed in Gitpod without requiring any user action.

Actually, @32leaves didn't we already implement the host-rewriting proxy for that purpose? Shouldn't it make servers like Webpack see `localhost` as the host, and thus avoid the "Invalid Host Header" problem?

**Comment by sobiero** [comment]
Where is the file vue.config.js located? or do I need to create it? I'm using vue/cli 3.9

**Comment by mouse484** [comment]
Add vue.config.js to the main directory.

The contents will be good with this:
```js
module.exports = {
    devServer: {
        disableHostCheck: true
    }
}
```

**Comment by HalftimeHarry** [comment]
I added the vue.config.js to the root in my project, but has the same error?
