### ISSUE TITLE
[code] port links validation in .gitpod.yml from server to gitpod-web extension

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6436]
### Bug description

We disable it temporarily https://github.com/gitpod-io/openvscode-server/blob/f14b5f5730b57a05656c1fef9de2f2c22ee8a0c1/extensions/gitpod-web/src/extension.ts#L845

but we should recover it before next stable release.

### Steps to reproduce

See above.

**Comment by akosyakov** [comment]
Generally it seems to work, but there are following regressions, i.e. it works if you use stable version:
- [ ] the following reported like extension is not found in Open VSX when it is there:
```
vscode:
  extensions:
    - stkb.rewrap@1.13.0
```
- [ ] if you add following and try to use install quick fix it fails:
```
vscode:
  extensions:
    - zxh404.vscode-proto3@0.4.2
```

**Comment by akosyakov** [comment]
I think it is a good candidate for integration testing. Since [there are many cases](https://github.com/gitpod-io/gitpod/pull/4646) and easy to cause regressions.

**Comment by jeanp413** [comment]
@akosyakov 
open-vsx says 1.14.0 is the only published version for `stkb.rewrap`
```
"allVersions": {
    "latest": "https://open-vsx.org/api/stkb/rewrap/latest",
    "1.14.0": "https://open-vsx.org/api/stkb/rewrap/1.14.0"
},
```

**Comment by akosyakov** [comment]
@jeanp413 strange why it works in stable, maybe MS code disregards version check, then i think new behaviour is better

**Comment by jeanp413** [comment]
@akosyakov for the second case i.e. `zxh404.vscode-proto3@0.4.2` the issue was that `workbench.extensions.installExtension` didn't accept an extension id with a version, I thought about how to workaround it (by downloading the vsix manually, etc). But in the end I decided to just make `workbench.extensions.installExtension` accept an id with version too as it was just a one line fix.
Created a PR upstream https://github.com/microsoft/vscode/pull/136314 and cherry picked to gp-code/main and gp-code/release/1.62

**Comment by akosyakov** [comment]
thanks, it works now ❤️
