### ISSUE TITLE
Small UI changes for Desktop IDE configuration dashboard (JetBrains)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6438]
A collection of smaller UI suggestions for the JetBrains dashboard.

Changes: 

1. Update the `IdeReady` helper text when IDE is loading from `Your Workspace is Ready` to be: `Running` ([Source](https://github.com/gitpod-io/gitpod/pull/6270#discussion_r734677553))

2. Update `Use Desktop IDE` text on the configuration page to be: `Open in Desktop IDE` ([source](https://github.com/gitpod-io/gitpod/pull/6270#discussion_r734679322))

3. Reorder the primary action button to the right when opening the IDE ([Source](https://github.com/gitpod-io/gitpod/pull/6270#discussion_r734689957))

**Comment by corneliusludmann** [comment]
> * Update the `IdeReady` helper text when IDE is loading from `Your Workspace is Ready` to be: `Running` ([Source](https://github.com/gitpod-io/gitpod/pull/6270#discussion_r734677553))

I had intentionally chosen to take a longer text instead of just "Running". I'm afraid that the short "running" can be quickly overlooked (in particular compared to the other short status texts) and users wait for something to finally happen. The idea was to make the text stand out a bit more.

| Long, explicit text | Short text |
| --------------------|------------|
| ![image](https://user-images.githubusercontent.com/24960040/139829209-71d30698-3d70-47f0-bccb-d9b3ebf8b56e.png) | ![image](https://user-images.githubusercontent.com/24960040/139829319-27597699-a0b9-4caa-8bc9-4e1d39bf2de3.png) |

What do you think?

**Comment by gtsiolis** [comment]
> I had intentionally chosen to take a longer text instead ...

Good point @corneliusludmann! No strong feeling against the longer text.

**question**: Wondering why we require the extra step anyway to get the dynamic URL and the command. Could we get the command beforehand? See early design draft below. Cc @atduarte @loujaybee 

<img width="1041" alt="Screenshot 2021-11-05 at 12 24 40 AM" src="https://user-images.githubusercontent.com/120486/140428815-6444ed4e-a190-4039-aaaf-ea9c5c0dbbfb.png">

**Comment by atduarte** [comment]
@gtsiolis That would be much better. Unfortunately, currently, we only get the link you see, that redirects to a second page, from the Jetbrains IDEs. We could maybe reverse engineer it, but this is to be changed entirely very soon. We will replace this _Code with Me_ connection that adds a hop and asks for a password, for a custom link that automatically opens the local IDE and no additional action is required. 🎉 We haven't done this yet because we are still missing some implementation details from Jetbrains.

**Comment by loujaybee** [comment]
Fully agree with @atduarte on this one. Let's see how the _Code With Me_ removal progresses. But, it's a nice suggestion @gtsiolis and I like the mock-up. It might be useful as a workaround depending on how quick JetBrains are... we might also want to re-use the design in the future 🙏

**Comment by corneliusludmann** [comment]
Great! I marked the [corresponding PR](https://github.com/gitpod-io/gitpod/pull/6507) with the changes as ready for review. @gtsiolis Is it something you can review?

**Comment by gtsiolis** [comment]
Thanks @atduarte for clarifying, @loujaybee for chiming in, and @corneliusludmann for opening https://github.com/gitpod-io/gitpod/pull/6507! 🏀 

Looking forward for improving and making this flow more obvious to users.
