### ISSUE TITLE
Error: You cannot run more than 8 workspaces at the same time.

### ISSUE THREAD

**Issue by nico-abram** [gitpod-io/gitpod#644]
I have 0 running worspaces, and 0 archived ones (well, 3 archived red/stopped ones, and when I hit delete it gives me an error: couldnt delete), and haven't for at least 4 minutes. Yet I still get: https://i.imgur.com/m4cqwua.png .

**Comment by 32leaves** [comment]
Hey. Sorry for that - we have found the issue: during workspace startup `rustup` or `apt-get` fail which prevents the workspace from starting. Unfortunately we also have a but that breaks things in this particular situation.

I'll reset the existing workspaces to stopped so you can work again.
In the meantime we're working on a fix for that, so that you'll see the proper error message should the workspace not start properly.

**Comment by jankeromnes** [comment]
The fix has been deployed. 🎉

This problem should be resolved now. Please comment here if it's not.
