### ISSUE TITLE
Investigate / fix port-forwarding

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6487]
Relates to: https://github.com/gitpod-io/gitpod/issues/5644

**Comment by atduarte** [comment]
If I understand the one you opened correctly—having the workspace ports from the user exposed locally when using jetbrains—these two are different. Jetbrains IDEs are expected to handle this issue. The other issue is something we will need to do in order to replace the Code with Me connection with the custom HTTP links.

**Comment by loujaybee** [comment]
Temporarily removing from GroundWork as this is related to the open BETA not the private BETA, so let's finish off all work for private BETA first.

**Comment by loujaybee** [comment]
Currently no work to do on our end for this, we're waiting on JetBrains for updates.

**Comment by akosyakov** [comment]
It is supported by now by JB products.
