### ISSUE TITLE
killall node stops the workspace

### ISSUE THREAD

**Issue by 32leaves** [gitpod-io/gitpod#654]
**Describe the bug**
When the Theia process dies (e.g. because it's OOM killed) the workspace gets stopped.

**To Reproduce**
`killall node`

**Expected behavior**
The workspace should remain running and Theia should be restarted.

**Comment by jankeromnes** [comment]
It's intended behavior that if you kill your container's `init` process, it stops.

However, I don't know the relationship between Theia and the container's `init` process. Maybe we could make it so that `init` spawns Theia, but doesn't crash if Theia dies.

**Comment by 32leaves** [comment]
> However, I don't know the relationship between Theia and the container's `init` process. Maybe we could make it so that `init` spawns Theia, but doesn't crash if Theia dies.

It should be like that already :)

**Comment by jankeromnes** [comment]
So, the workspace container's `CMD` is a bash script, which runs this:

```bash
# Restart Theia
while true ; do
    echo "[theia] Starting"
    bash startup.sh;
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ] ; then
        echo "[theia] Down with $EXIT_CODE."
        sleep 1
    else
        echo "[theia] Stopped"  >> /dev/termination-log;
        break
    fi
done
```

I'm a bit suspicious of this auto-restarting script (even though I couldn't see any errors), and I think that maybe we should use something well established like [supervisord](http://supervisord.org/) instead of re-inventing our own keep-alive script.
