### ISSUE TITLE
[Installer]: establish a way of running the db migration job on each run of `kubectl apply`

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6548]
This may be solved by #6573

**Comment by MrSimonEmms** [comment]
Runs on from #6515

**Comment by csweichel** [comment]
I reckon it would be enough to run the migration for each new version of Gitpod, rather than for each run of `kubectl apply`. Only when the Gitpod version changes can changes to the database schema be introduced.

In that sense, if we e.g. added the migration version to the job name we might be sorted already. Let's wrap this up in #6573
