### ISSUE TITLE
Sort workspaces by most recently used

### ISSUE THREAD

**Issue by joshleblanc** [gitpod-io/gitpod#664]
I might be an odd one out here, but I have a bunch of workspaces (12), and my most recently used one is actually the first one I created.

So I'll open gitpod, switch the number of visible workspaces to 50, scroll to the bottom of the page, and then open the workspace.

It seems to me that sorting by most recently used would make the most sense from a usability standpoint.

**Comment by meysholdt** [comment]
Hi Josh! this sounds like a useful proposal but I would also like to understand a bit better if you actively work with so many workspaces. 

In my personal usage pattern, I have maybe *one or two* workspaces I'd like to remember because they contain uncommitted files or unpushed commits. Besides that, I have *hundreds* of workspaces I could actually delete because all relevant changes went back to GitHub. After pushing all changes to GitHub and stopping a workspace, I *never* reuse it, but *always* start a fresh workspace on that git branch. 

How do you use workspaces?

**Comment by HorizonShadow** [comment]
I'm basically using them as a primary workspace. So when I want to work on project X, I just go to gitpod, and open project X.

I don't go to github, and create a new workspace for the project. I'd just do a pull on the existing one. I'm treating it as an online IDE.

**Comment by jankeromnes** [comment]
Thanks for the feedback! I agree that the current workspace order is quite strange (see also #494).

**Comment by jankeromnes** [comment]
Update: We recently deployed a workspace sorting change that separates currently running workspaces (always at the top) from stopped workspaces.

This will show an old workspace at the top if it's running, however when it's stopped I believe it will return toward the bottom of the list. So the recent change doesn't fix this issue.

**Comment by akosyakov** [comment]
Please sort by last activity not by creation date. Creation date does not reflect how workspace are used. See the picture below, most recent workspace is the last and one which i just wanted to stop and start again:
<img width="1552" alt="Screen Shot 2020-01-08 at 12 57 42" src="https://user-images.githubusercontent.com/3082655/71960418-cc829280-3216-11ea-8749-0baa6a084344.png">

It's irrelevant whether a user embraces ephemeral workspaces or just using Gitpod as the classic online IDE. The last used workspace at the top would be useful in both cases.

**Comment by geropl** [comment]
Fixed since 27.02.2020
