### ISSUE TITLE
Container exited with exit code -137

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#674]
**Describe the bug**
As of late we’re seeing more and more containers getting oom killed (at least exiting/restarting with exit code `-137`). This seems to happen predominantly around deployments. We’ve seen this on staging and prod.

**To Reproduce**
Not quite sure, but seems related to OOM kills and/or deployment.

**Expected behavior**
The workspace should continue to run, be it after some brief period of unavailability while the container restarts.

**Comment by jankeromnes** [comment]
This is strange, because I'm seeing much _fewer_ OOM kills in our monitoring since we merged the IDE and workspace containers.

Firstly, are we certain that these exits are indeed OOM-kills? (I seem to remember that `137` is a generic kill code -- not necessarily OOM-related.)

Also, what is the exact process that is being killed? Previously, many OOM-kills were affecting compiler processes like `gcc`, `rustc`, `clang`, etc, but without taking down the container itself (`init` process).

As I don't see `init` consuming large amounts of RAM itself, I suspect that somehow, another process gets killed, and that `init` wrongly takes the fall with it.

My prime suspect is the IDE / Theia process: it's been known to occasionally spike at > 20GB RAM for no apparent reason, and I think we've seen a killed Theia process take down a container before (which is a bug -- instead, the Theia process should be auto-restarted, and the container's `init` process should stay alive & healthy in the process).

**Comment by tianhaoz95** [comment]
I just experienced the same error (exiting with code -137). In my case, I am running a `react.js` project. In the command line I am running `npm test` in watch mode and `npm start` with a development `react.js` web application served locally.

**Comment by jankeromnes** [comment]
Thanks for reporting this @tianhaoz95, and sorry, that's a pretty bad experience.

Are you able to reproduce this bug by always running the same steps in the same project? If so, could you please share the project URL, so I can try to trigger this problem too?

Over the past 24 hours, our monitoring only shows a few OOM-kills across all 3 regions:
- `eu`: ~50 OOM-killed processes over 30min, 13 hours ago
- `us`: ~10 OOM-killed processes over 2h, between 13 and 15 hours ago
- `ap`: 1 OOM-killed process, 22 hours ago

I'm guessing you're in the `us` cluster, and these OOM-kills happened between 4 and 6 hours prior to your comment. Is that when you noticed the bug? (If not, I think container `init` kills may be reported differently by Kubernetes/Prometheus.)

**Comment by tianhaoz95** [comment]
@jankeromnes No I am not able to reproduce the crash, so it's likely caused by an infra problem instead of anything to do with my code. I remember it happened some time (less than 4 hours) before I opened this issue.

**Comment by tianhaoz95** [comment]
@jankeromnes the repo I was developing was https://github.com/Acumany/AcumanyVault. Inside `ui/vault_desktop_website`, I was running `npm run storybook`, `npm start` and `npm test` at the same time when this happened.
