### ISSUE TITLE
All my environment variables are gone

### ISSUE THREAD

**Issue by krainboltgreene** [gitpod-io/gitpod#683]
For some reason logging in today all my environment variables are gone.

**Comment by krainboltgreene** [comment]
<img width="996" alt="Screen Shot 2019-07-18 at 1 48 20 AM" src="https://user-images.githubusercontent.com/334809/61443359-2bb5b900-a8fe-11e9-9318-6ede0662d68b.png">

**Comment by jankeromnes** [comment]
Hi @krainboltgreene, wow, this sounds like a pretty bad problem, and I'm so sorry that it took us so long to respond. 😓 We should really get better at triaging issues so that bugs like these don't slip by unnoticed.

I briefly checked our database, and it indeed seems that you no longer have a single entry in your environment variables... I'm not quite sure how something like this could happen, but we'll investigate this problem and let you know what we find.

Thanks a lot for reporting this, and sorry again for not responding earlier.

**Comment by jankeromnes** [comment]
Our first suspicion is that this looks like a broken Update, where a partial key causes updated entries to be deleted. We'll take a closer look at our Update calls to try and confirm this.

**Comment by krainboltgreene** [comment]
It's strange that I have no entries and yet so many empty values? Are you using local storage?

**Comment by jankeromnes** [comment]
This issue is quite tricky to investigate... sorry that it is taking so long. (We've also had a number of other high-priority items to address, related to the recent release, which delayed this investigation a bit.)

Our current theory is that this may not be a DB/backend issue, but rather a front-end bug. I'm not too familiar with that code yet (e.g. I don't know why you're seeing so many empty entries, or if that's cached in local storage), but I'll investigate and let you know what I find.

**Comment by krainboltgreene** [comment]
No worries thanks for looking into it.

**Comment by AlexTugarev** [comment]
@krainboltgreene, it happened to me last week that I forgot to accept changes with the ✔️ on each row. Just asking, could it be that it happened here as well?

I think we really should improve the UX here. Changes has to be highlighted and either applied immediately or after hitting a noticeable button.

**Comment by svenefftinge** [comment]
@AlexTugarev I think the screenshot shows that this was not the case. I.e. all values seem to be properly stored, no?

**Comment by AlexTugarev** [comment]
It's hard to tell, actually. I was thinking of this case:

![2019-08-05 12 41 22](https://user-images.githubusercontent.com/914497/62461555-7734e780-b785-11e9-86a5-8ed9b4459228.gif)

**Comment by krainboltgreene** [comment]
My partner and I definitely checked that the ENVs were present inside of a container afterwards so I very much doubt it.

Can the outer ENVs be mutated from inside a container?

**Comment by svenefftinge** [comment]
Yes, you can use the CLI but I think you'd have noticed. 
https://www.gitpod.io/docs/47_environment_variables/#using-the-command-line-code-classlanguage-textgp-envcode
