### ISSUE TITLE
[git] I cannot push to a remote Theia

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#685]
**Describe the bug**

I cannot push to Theia. I have write-access to the repository.

**To Reproduce**

 - Open Gitpod on a Theia issue, I picked this one: https://github.com/theia-ide/theia/issues/5743
 - Do your work and commit it with sign-off by. I do not know if sign-off by matters.
 - Publish changes from the status bar.

<img width="884" alt="Screen Shot 2019-07-18 at 18 27 18" src="https://user-images.githubusercontent.com/1405703/61474999-15edd580-a98a-11e9-998c-26648c22042a.png">

```
gitpod /workspace/theia $ git remote -v
origin  https://github.com/theia-ide/theia.git (fetch)
origin  https://github.com/theia-ide/theia.git (push)
gitpod /workspace/theia $ 
```

```
root INFO GitHubGitErrorHandler > error message: Request push failed with message: Authentication failed. You may not have permission to access the repository or the repository may have been archived.
```

**Expected behavior**
I can push.

**Comment by kittaakos** [comment]
By the way, I use 2FA for GH.

**Comment by AlexTugarev** [comment]
Thanks for reporting this @kittaakos! I know for sure that you have write access to that repo 🙏 

We've two issues to solve here:
1. get rid of the second error message from above which is just confusing
2. reword first message to tell you that Gitpod needs to be authorized to be allowed to perform git actions on your behalf

We definitely need to improve those flows to make it clear, that it's a different set of permissions your granting to the Gitpod services in order to work with. For example: you need to explicitly allow access for organizations on GitHub even if you're an owner.

**Comment by AlexTugarev** [comment]
Almost forgot to mention: a click on `Grant Permissions` and repeating of `Publish changes from the status bar.` should be "enough". Well, as I said this is not obvious.

**Comment by kittaakos** [comment]
I can confirm, `Granting Permissions` and the pushing the branch to the remote again worked.
 - I clicked on Grant Permissions.
 - Open the GH auth page.
 - Entered username and pwd.
 - I entered the 2FA code.
 - Seen this:

<img width="547" alt="Screen Shot 2019-07-19 at 09 51 37" src="https://user-images.githubusercontent.com/1405703/61519020-2f833180-aa0b-11e9-892f-56674795c597.png">

 - Then I switched back to my Gitpod window.
 - I pushed the branch.
 - It worked. ✨

**Comment by felixfbecker** [comment]
Where can I find this "Grant permissions" button?

**Comment by JesterOrNot** [comment]
@felixfbecker 
https://www.loom.com/share/78fa5f0e110b47fda56399ddf7a232ea

**Comment by jankeromnes** [comment]
Thanks for making a screen cast @JesterOrNot!

Also, direct link is https://gitpod.io/access-control/
