### ISSUE TITLE
Investigate licensing with latest JetBrains images

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6864]
The latest JetBrains images appear to require a license [[1](https://github.com/gitpod-io/gitpod/pull/6802#issuecomment-975701930)]. We need to investigate what needs to be done on our side, and possibly update the: https://www.gitpod.io/docs/editors/jetbrains-private-beta JetBrains beta documentation.

**Comment by corneliusludmann** [comment]
Since we agreed on using the latest releases as images (not the early-access program images anymore), users need a license now. Thus, I think we don't need this issue anymore. Agreed?

I'll close this for now. Fell free to re-open if needed.

_PS: We still need to update the website regarding the needed license, right?._

**Comment by akosyakov** [comment]
> PS: We still need to update the website regarding the needed license, right?.

Here is the PR: https://github.com/gitpod-io/website/pull/1298 but we need to bump all JetBrains products to release first.
