### ISSUE TITLE
Auto generate gitpod.yml from CI configurations

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6888]
There are a few different sources of metadata that exist in a repo that we can extract to help, such as GitLab CI files, or GitHub action YAML files. 

Why? 
1. Quick initial project set-up (i.e you don't need to understand the YAML syntax etc)
2. Don't have duplicate configurations, or refactor into a Makefile, or common bash script, etc. 

I believe @gitpod-io/engineering-meta were already thinking of / doing something with this type of thing? 

Related tweet [[1](https://gitpod.slack.com/archives/C01KGM9DVRC/p1637830873168900)]

**Comment by jankeromnes** [comment]
Interesting idea, thanks @loujaybee!

FYI, we already have some basic `.gitpod.yml`-generating code here:

https://github.com/gitpod-io/gitpod/blob/main/components/server/src/projects/config-inferrer.ts

- It's used to auto-generate a `.gitpod.yml` when you're adding a new Project that doesn't have a `.gitpod.yml` file yet
- It checks for several files in the repo in order to guess what your `init` and `command` tasks should be (e.g. it look for `package.json`, `yarn.lock`, `build.gradle`, `pom.xml`, `cargo.toml`, and various others.)

> 1. Quick initial project set-up (i.e you don't need to understand the YAML syntax etc)

That was actually the goal with this auto-generator. I guess the bar wasn't really met?

Would you have any ideas or suggestions for how:
- The guessing heuristics could be improved specifically? (E.g. checking for new files, like GitLab CI or GitHub Action YAML, in order to derive new `init` tasks?)
- The usage of the generator could be expanded? (E.g. maybe this can be used in other places than just the New Project wizard? For instance, maybe an IDE quick action like "generage `.gitpod.yml`" could help? Or something else?)

> 2. Don't have duplicate configurations, or refactor into a Makefile, or common bash script, etc.

Ah, I guess you're actually talking about making Gitpod use the GitLab CI or GitHub Action YAML files directly in order to run initialization tasks, instead of using them to derive a `.gitpod.yml` file, right?

In that case, this issue about supporting `devcontainer.json` rings a bell: https://github.com/gitpod-io/roadmap/issues/16

That issue has the potential to eventually unify Gitpod and Codespaces around a single standard. Going beyond that, and unifying also with various CI configurations, is an interesting follow-up idea, although I wonder whether maybe the use cases are too different (e.g. sometimes you don't want exactly the same build steps & environments in CI and in dev, because dev needs nicer tools, maybe a debug build, fewer invasive test harnesses and instrumentation, etc, while CI is by nature very non-interactive oriented)
