### ISSUE TITLE
Implement analytics on the "Get Started with Gitpod" walkthrough

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6897]
When opening VS Code for the first time, you are presented with a "welcome to Gitpod" VS Code page, which walks you through different aspects of Gitpod. We need to add analytics to track: 

* Are users dismissing the walkthrough? 
* Which tabs are users navigating to? 
* Are users clicking on the command links. 
* Anything else noteworthy that can help us to assess how useful/valuable this walkthrough is for users. 

![image](https://user-images.githubusercontent.com/5528307/143438194-c99d22c0-3376-4b88-9ddf-0b4a022344dc.png)

**Comment by roboquat** [comment]
@loujaybee: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6897#issuecomment-993357791):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by loujaybee** [comment]
Related internal discussion [[1](https://gitpod.slack.com/archives/C01KGM9BH54/p1639074018482400)]

**Comment by jeanp413** [comment]
From vscode telemetry:
- event name `gettingStarted.ActionExecuted` logs command (`selectTask` a.k.a select step, `toggleStepCompletion`, `allDone`) and argument (extension id + step id)

**Comment by filiptronicek** [comment]
In addition to the `gettingsStarted.ActionExecuted` events that @jeanp413 mentioned, there are a couple more, maybe not relevant at all, but wanted to leave this here for reference.

https://github.com/gitpod-io/openvscode-server/blob/91b97cec911a954bcd83d2613bb6d7b6bd4023ad/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L328 - the switch statement has most of the commands, here are some documented:
- `selectCategory` - when the user selects a built-in walkthrough. In the argument portion of the event, you can find the name of this walkthrough.
- `selectTask` - when a user chooses a step to go to in the walkthrough, for example: 
```
[2021-12-14 23:21:32.330] [telemetry.log] [trace] telemetry/gettingStarted.ActionExecuted {"properties":{"command":"selectTask","argument":"settingsSyncWeb","common.lastSessionDate":"","common.isNewSession":"1","common.remoteAuthority":"other","common.machineId":"75f0fc0a-66ac-4e72-8058-ee24a2b9912f","sessionID":"c0e974d6-9940-4a81-8981-82c6f450a2fd1639514847500","version":"1.64.0-dev-insider","common.platform":"Mac","common.product":"web","common.userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36","common.isTouchDevice":"false","timestamp":"2021-12-14T22:21:32.166Z"},"measurements":{"common.timesincesessionstart":5644666,"common.sequence":438}}
```
Where the `argument` is the target step of the interaction, so for example, if you went to our Gitpod walkthrough and clicked on the prebuilds tab, you would get the following `argument`: `gitpod.gitpod-web#gitpod-getstarted#prebuilds`.
- `allDone` - when the user has completed the walkthrough (by using the <kbd>Mark Done</kbd> button at the bottom of the page). This event is **not** triggered when the user marks all the steps as completed. A noteworthy fact is, that with this event there is no `argument` specified (i.e. we don't know what walkthrough was marked done). This can possibly be solved by the `editorClosed` event, that @jeanp413 mentioned. For example:
```
[2021-12-14 23:25:35.411] [telemetry.log] [trace] telemetry/gettingStarted.ActionExecuted {"properties":{"command":"allDone","common.lastSessionDate":"","common.isNewSession":"1","common.remoteAuthority":"other","common.machineId":"75f0fc0a-66ac-4e72-8058-ee24a2b9912f","sessionID":"c0e974d6-9940-4a81-8981-82c6f450a2fd1639514847500","version":"1.64.0-dev-insider","common.platform":"Mac","common.product":"web","common.userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36","common.isTouchDevice":"false","timestamp":"2021-12-14T22:25:35.387Z"},"measurements":{"common.timesincesessionstart":5887887,"common.sequence":464}}
```
- `nextSection` - when the user clicks on the "Next Section" button on the bottom of the walkthrough.
- `seeAllWalkthroughs` - when the user is on the VS Code onboarding screen and instead of selecting a specific walkthrough, clicks on <kbd>More...</kbd>

in addition to these, there are:

- https://github.com/gitpod-io/openvscode-server/blob/91b97cec911a954bcd83d2613bb6d7b6bd4023ad/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L560
- https://github.com/gitpod-io/openvscode-server/blob/91b97cec911a954bcd83d2613bb6d7b6bd4023ad/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L595
- https://github.com/gitpod-io/openvscode-server/blob/91b97cec911a954bcd83d2613bb6d7b6bd4023ad/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L931
- https://github.com/gitpod-io/openvscode-server/blob/91b97cec911a954bcd83d2613bb6d7b6bd4023ad/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L934
- https://github.com/gitpod-io/openvscode-server/blob/91b97cec911a954bcd83d2613bb6d7b6bd4023ad/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L1052
- https://github.com/gitpod-io/openvscode-server/blob/91b97cec911a954bcd83d2613bb6d7b6bd4023ad/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L1288

/cc @loujaybee

**Comment by akosyakov** [comment]
closing and moving into awaiting deployment since it is not in stable yer
