### ISSUE TITLE
Epic(experiment): Create new projects and enable prebuilds from within the IDE

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#6906]
It would be great if the IDE allowed users to enable Prebuilds for their repository via a simple quick action.

I guess the IDE would need to be aware of:
- Whether Prebuilds are already enabled or not for the current repository (and whether there is already a Gitpod Project associated to it)
- Whether the current user is authorized to enable prebuilds (which implies the creation of a Gitpod Project, and the installation of the [GitHub App](https://github.com/apps/gitpod-io) or GitLab/Bitbucket Webhook)
- Whether there is a `.gitpod.yml` with an `init` task, or if one needs to be created first

**Comment by svenefftinge** [comment]
Enabling prebuild would imply creating a Gitpod project as well.

**Comment by jldec** [comment]
> Enabling prebuild would imply creating a Gitpod project as well.
aah 💡

**Comment by jldec** [comment]
This feels like a joint effort, interfacing from inside the IDE to the Gitpod server/api to create a project with a repo which includes .gitpod.yml configuration.

**Comment by loujaybee** [comment]
Thanks for the issue @jankeromnes ! 🙏 

I think this makes sense. Since prebuilds are in my mind, an optimization of an existing configuration (e.g. `init`), without an existing configuration, a prebuild appears (from a user perspective at least) to bring no value. So I think it makes sense to defer until the user has understood what gitpod is, and what the YAML file / configuration is before we ask them to set up a prebuild. I don't think that necessarily the prebuild _has_ to be configured from within the IDE. 

I think we should also answer this question: "Where is the best / most convenient place/way for a user to set up their YAML file? The dashboard or the IDE? Or do we want to support both of those flows?".

Regarding:

> Whether there is a .gitpod.yml with an init task, or if one needs to be created first

I would add to this: if a user has a `command` property which takes a particularly long to run  ("long" is subjective, and would need to be defined), we should consider prompting a user as to whether there are aspects of that command they could extract into a prebuild. This prompt could be directly within the IDE experience, or via other bumpers, such as suggestions within the dashboard. 

e.g. "Hey, we noticed that X project takes a long time to build, have you considered [setting up a prebuild]?"
