### ISSUE TITLE
Error: Cannot read property 'sha' of undefined on attempt to open  project

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#692]
**Describe the bug**
refuse to open with error Error: Cannot read property 'sha' of undefined
**To Reproduce**
when trying to start a new workspace with the label https://gitpod.io/#github.com/JesterOrNot/Python-Calc.git 
**Expected behavior**
Open new workspace
edits: sorry this is my first time doing this

**Comment by jankeromnes** [comment]
Whoops, thanks a lot @JesterOrNot for reporting this bug, I was able to reproduce it.

I'm not yet sure what the root cause is or how to work around it, so I'll investigate more.

**Comment by jankeromnes** [comment]
So I see two problems here:
1. The error message `Cannot read property 'sha' of undefined` is very unclear and not helpful
2. The Dockerfile doesn't have the same name in `.gitpod.yml` and in your repository

Maybe 2. is the root cause of the problem you're seeing. I've opened https://github.com/JesterOrNot/Python-Calc/pull/1 to fix that. But we should also fix 1. because there is no way users can guess that `Cannot read property 'sha' of undefined` means that your Dockerfile name has a typo.

Maybe an error message like `Could not find Dockerfile '.gitpod.dockerfile' in this repository` would be clearer?

Again, thanks a lot for reporting this bug! 👍 Please let me know if there is anything else I can do to help.

**Comment by JesterOrNot** [comment]
First yes that would be a lot clearer.
Second thank you so much for all your help! Your solution worked like a charm!
