### ISSUE TITLE
Do not allow prebuilds when GitHub app is not configured or GitLab webhook is removed

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7009]
### Problem to solve

When a user removes or reconfigures the Github app, removes the GitLab webhook, or is removed from a project, you can still trigger a prebuild from the dashboard.

For GitHub, the prebuild go through the `RUNNING` and `SUCCESS` states with no error.

For GitLab, the prebuild go through the `RUNNING` and `SUCCESS` states with the following error:

```
last backup failed: workspace does not exist. Please contact support if you need the workspace data.
```

### Proposal

Do not allow prebuilds when GitHub app is not configured or GitLab webhook is removed

**Comment by jldec** [comment]
thanks! 🙏 @gtsiolis

- It would indeed be nice to handle the missing webhook/app config with an indicator as suggested as in #7010 
- But, I don't think we should prevent manually triggered prebuilds in this case - Allowing users to work without the automation seems reasonable to me.
- I could not reproduce the GitLab error which you mentioned probably because I'm not following the same steps that you did  - would you mind opening a separate issue with more details for reproducing so that we can investigate the cause of this bug?
