### ISSUE TITLE
Gitpod in the air!

### ISSUE THREAD

**Issue by asomervell** [gitpod-io/gitpod#707]
So i’m on a flight, on my iPad and Gitpod almost works... it works on laptop amazingly well, but not on iPad.

UX starts up, preview opens, but workspace and code don’t. I can’t inspect what’s failing right now but i’d suspect web sockets? So I fired up an Outline (Socks5) proxy to push the connection over that, still didn’t work. 

Be ideal to support a degraded mode so this works, or figure out why requests aren’t going over the proxy?

**Comment by svenefftinge** [comment]
I understood you are talking about proper iPad support with internet connectivity (https://github.com/gitpod-io/gitpod/issues/28) , not offline mode?

**Comment by jankeromnes** [comment]
Thanks for the feedback @asomervell!

> UX starts up, preview opens, but workspace and code don’t.

Could you please provide more details about what exactly didn't work with your workspace and code? E.g. what did you expect to happen, and what happened instead?

Also, do you know a way to reproduce this problem by following a series of specific steps?

**Comment by asomervell** [comment]
@svenefftinge yes with internet connectivity, not offline mode. Using the full blown Safari browser in iOS13. It also didn't work in chrome for iOS.

@jankeromnes the workspace itself loaded, I got the menu, right and left panels up, but no files, no code and I don't think a terminal. There were a bunch of console errors about websockets. 

Honestly it was just a regular login to a basic gitpod workspace. Safari on iOS13. I'll try it again from where I am now, but i'd point the finger at the proxies they use for in flight wifi killing sockets, i'd say that's the same for most environments behind proxies. Is there a backup mode for that environment ?

**Comment by geropl** [comment]
@asomervell The last time we checked we had serious problems running Gitpod on Safari because basics things (like web socket connections) are handled differently compared to Chrome/Firefox. It seemed Safari does not even try to implement all of the web standards... that's why we focus on Chromium and Firefox. Any chance you could test one of those?

**Comment by asomervell** [comment]
> @asomervell The last time we checked we had serious problems running Gitpod on Safari because basics things (like web socket connections) are handled differently compared to Chrome/Firefox. It seemed Safari does not even try to implement all of the web standards... that's why we focus on Chromium and Firefox. Any chance you could test one of those?

Interesting, I haven't encountered that but not much you can do there. The problem with Chrome on iPad is it still behaves like a mobile browser, scale is still out, fonts massive etc. etc., hopefully at some arbitrary time in the future they follow suit.

**Comment by jankeromnes** [comment]
> The problem with Chrome on iPad is it still behaves like a mobile browser, scale is still out, fonts massive etc. etc.

I believe that iOS apps are not allowed to ship their own web views on iPad, so Chrome and Firefox for iPad are really just "skins" for Safari (at least on iOS 12).

I'm not exactly sure what changed with iOS 13 yet, but I've heard several things like keyboard navigation being fixed (e.g. arrow keys) and Safari no longer forcing a mobile view. But I'm not sure that Chrome or Firefox got permission to ship their own web views, so maybe they're still based on Safari's engine?

In any case, we definitely want Gitpod to work great on tablets/chromebooks/smartphones, and at least on my iOS 12 iPad I'm able to open a workspace and get a few things done at home, i.e. the code and terminals do load for me (there are other UX problems that we'll iterate on, but the websocket link seems to work).

That means that the issues you saw in-flight are indeed probably caused by the network and not Safari itself.

In general, it would be great to improve Gitpod on flaky/unstable networks too, but other than that I'm not sure how to improve the in-flight experience other than waiting for airlines to provide better connectivity. Next time I fly, I'll try to bring my iPad and test Gitpod there. 🙂
