### ISSUE TITLE
Is it possible to run apt-get install on Gitpod?

### ISSUE THREAD

**Issue by dongfangxunlei** [gitpod-io/gitpod#708]
Sometimes I need some extra commands and have to relaunch a fresh gitpod workspace with an update Dockerfile . It is a bit boring.

**Comment by svenefftinge** [comment]
At the moment, we are not allowing root access in running containers due to security reasons.
Therefore apt-get doesn't work (need root).

I have added a section on how to work with the current limitations:

https://www.gitpod.io/docs/42_Config_Docker/#trying-out-changes-to-your-dockerfile

That said we definitely want to allow root at some point as well as running docker builds locally without starting fresh workspaces.
