### ISSUE TITLE
archived gitpod community forum posts are not searchable and therefore permanently lost

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#7164]
## Is your feature request related to a problem? Please describe
As of Dec 7th 2021 the gitpod community forums have been replaced with a discord server. That is great in that gitpod is making a better place for community support. What is really not great is the fact that every link to the community forum now takes you to the discord lobby and no further. In essence alsmost all the essential information found in the gitpod community threads is currently lost. Yes I do see that the community forum forum was archvived but it is pretty much _useless_ without a **search** feature or an ID to plain eligh url mapping of some kind.

The archived forum uses ID numbers in the urls while the original forum  uses plain english delimited with hyphens in the urls . Currently this make it impossible to look up an archived thread.

## Describe the behaviour you'd like

The archived community forum should be searchable in relation to the original url that google has indexed or something. We need some type of system to look up old threads in the archived forum

## Describe alternatives you've considered

Without a search feature or an ID to plain english mapping of the community forum urls I have been unable to find a workaround.

Why not just host the actual gitpod community forum for archival purposes but disallow any further posting or commenting? Then just put a link to the gitpod discord server in the header of the archived gitpod community forum? Then maybe give that website a one or two year lifespan and then do away with it?

## Additional context

Perhaps more users than you know rely on the knowledge base found in the retired community forums.

**Comment by ghuntley** [comment]
> Currently this make it impossible to look up an archived thread.

Howdy @apolopena.

Great feedback, let's make some adjustments...

The [Archiveteam](https://wiki.archiveteam.org) was engaged to archive the forums and upload them to the internet archive. In order to give people like yourself more time the forums are back online in read-only mode whilst our own archive is taken and then afterwards the static archive will be served for a quarter or so. After this point the internet archive resumes being the primary custodian.

<img width="1440" alt="Screen Shot 2021-12-10 at 2 47 57 pm" src="https://user-images.githubusercontent.com/127353/145518899-cb185918-f569-47de-8222-dc25064e66a8.png">


> Why not just host the actual Gitpod community forum for archival purposes but disallow any further posting or commenting

Compliance, reduction of security attack surfaces and https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-erasure/. 

> Perhaps more users than you know rely on the knowledge base found in the retired community forums.

Acknowledging this, at the same time lots of information within the forums is old, incorrect and turns up before official documentation results. If people are relying on the forums for information that hints that there's something wrong with documentation, samples and tutorials. If you find yourself heading to the forums to get information please use the documentation feedback tool to provide insights to _why_ so that Gitpodders and the community can focus on making them better.

<img width="959" alt="Screen Shot 2021-12-10 at 2 58 50 pm" src="https://user-images.githubusercontent.com/127353/145519753-bf8d3b05-3ea3-414d-bf1f-b55b156d5e4d.png">

From https://www.gitpod.io/docs/

**Comment by apolopena** [comment]
@ghuntley Thank you bringing the forum back online in read-only form for a limited time, this is very helpful!

> If people are relying on the forums for information that hints that there's something wrong with documentation, samples and tutorials. If you find yourself heading to the forums to get information please use the documentation feedback tool to provide insights to why so that Gitpodders and the community can focus on making them better.

Historically and honestly there have always been some holes in the gitpod documentation and the forum has filled those gaps nicely. In our busy lives I have opted to spend my time logging gitpod bugs rather than pointing out the shortfalls of the documentation but I will reconsider this moving forward. The gitpod team has always been really great at responding to questions in the forums, filling the knowledge gaps with an archivable record. It has always seemed to me that the forums were a good place to ask questions outside of the issues/features requests where these questions and answers were recorded and could be used as a knowledge base.

With discord being the go to place to for questions  and answers now (which is great by the way) I find myself wondering how I can look up these answers and questions before I ask one of my own. A knowledgebase if you will. 

I suggest that a small knowledge base/FAQ be added to the website. I know this could be difficult the maintain since technology moves so fast. Currently there seems to be no real way to find answers to commonly asked questions such as (for example) "What is the best practice for downgrading something like PHP if I am using `gitpod/workspace-full`?"

Thank you to the gitpod team for all you do! I appreciate you listening and responding to my feedback. Everything I do here is in the interest of improving the gitpod platform.
