### ISSUE TITLE
What environment do I need to install when I run gitpod in my webstorm（windows10）

### ISSUE THREAD

**Issue by Mrzhuxuhao** [gitpod-io/gitpod#7168]
### Bug description

what should I do! Are there any tutorials

### Steps to reproduce

First run gitpod in my local webstrom!

**Comment by sagor999** [comment]
We have documentation available here: https://www.gitpod.io/docs/
If you are trying to install gitpod as self hosted, then Windows 10 is not supported. 
Otherwise if you are just opening a workspace, you can do it from any environment.
Let us know more details about the issue that you are having, as it is a bit unclear as of right now.
I will close this issue, but please re-open if you are still having issues.
