### ISSUE TITLE
Epic: First-class JetBrains browser support

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7194]
This is a placeholder for a future epic/bet, more details coming soon.

**Comment by buggtb** [comment]
Personally I'd rather have Jetbrains in a browser than Jetbrains client download or connection to Idea, but what we have is good enough. Assuming they end up making Fleet a first class citizen and part of their future roadmap, I would certainly like to see Fleet added to the stack so that we can start that up just like we do with VSCode

**Comment by akosyakov** [comment]
@buggtb sure, let's first get out more stable JB products out of beta and when Fleet is out of beta add it too

**Comment by loujaybee** [comment]
With Fleet announcements since this issue, we're now going to remove official support for Projector templates from Gitpod. I'lll close this issue for now, unless the ecosystem changes, it looks like building a great desktop and/or gateway integration JetBrains will be our focus for now.
