### ISSUE TITLE
Multiple URLs for one Gitpod

### ISSUE THREAD

**Issue by matthewhall-ca** [gitpod-io/gitpod#7236]
## Is your feature request related to a problem? Please describe
We utilize a monorepo architecture and have multiple applications that run via our docker-compose file. The simplest explanation of this is that we have an Auth and a GraphQL service that run at

auth.app.docker
graphql.app.docker

## Describe the behaviour you'd like
The ability to utilize multiple URLs within one Gitpod environment

## Describe alternatives you've considered
We are evaluating utilizing multiple ports to make this work today but its a much messier setup

**Comment by svenefftinge** [comment]
Sorry for the late feedback. I probably just didn't understand your request, but you should automatically get a URL per port, so when you start two services (no matter you start them through docker or directly) there will be two URLs that can be accessed. See also [the docs](https://www.gitpod.io/docs/config-ports).

**Comment by matthewhall-ca** [comment]
Correct but it would be nice if we could give it a "pretty" name instead. Its a bit confusing to keep track of all the different ports and how they map

**Comment by sagor999** [comment]
```
gitpod /workspace/gitpod (main) $ gp url
https://gitpodio-gitpod-2wijgs4mg4t.ws-us34xl.gitpod.io
gitpod /workspace/gitpod (main) $ gp url 3000
https://3000-gitpodio-gitpod-2wijgs4mg4t.ws-us34xl.gitpod.io
```
The only way I see this working as of now is that instead of adding port name as prefix, we could provide a way to do something like this:
`gp url 3000 alias`
Which would produce this URL:
`https://alias-gitpodio-gitpod-2wijgs4mg4t.ws-us34xl.gitpod.io`
I am not sure if that would solve what you are trying to accomplish?

Alternatively, we are now allowing you to edit /etc/hosts in your workspace, so you could "fake" any url within your workspace easily.
