### ISSUE TITLE
Add HTTP endpoint to send telemetry

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7257]
## Is your feature request related to a problem? Please describe

Right now, in order to send telemetry from gp-code web we need to create a websocket connection to the server. It could be problematic to have too many connections to the server as we already have one in the gitpod-web extension.

## Describe alternatives you've considered

Create an HTTP endpoint so we can easily send telemetry to the server without creating a websocket connection

**Comment by akosyakov** [comment]
For the context, it seems that we will need one web socket connection for each built-in extension reporting telemetry, so we would prefer HTTP endpoint.

**Comment by jeanp413** [comment]
Alternatively, we can investigate how to send events directly to segment but need to avoid exposing segment sources to end users

**Comment by akosyakov** [comment]
@jeanp413 I chatted with it about @csweichel. The difference between trusted and untrusted that we verify events on the server, i.e. we sure for instance about user identity. But rather than that it does not provide any safety, since a user of workspace can have spam Gitpod Server with events too. I think we should enable untrusted production source as well and use it for analytics just be continuous about data there.

If it is alright with everybody we can close the issue? cc @jakobhero @geropl

**Comment by JanKoehnlein** [comment]
Closing as described above
