### ISSUE TITLE
Snapshots should respect the config in the file system

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#727]
When I 
 1) start a workspace, 
 2) change the Docker config then 
 3) create a snapshot and 
 4) start it, 

the changes are not respected.

**Comment by meysholdt** [comment]
Do you picture "rebuild Dockerfile" as (a) an optional flag for snapshot creation or (b) as the new default behavior? 

While I would find (a) useful I think that (b) will too often break the contract "what ran in my workspace will also run in snapshots", because Dockerfiles are often not deterministic due to sloppy version-locking.

**Comment by svenefftinge** [comment]
Yeah, I have the same concerns. So possibly a special mode. I wanted to put a button on top of the `.gitpod.yml` (and possibly `.gitpod.Dockerfile) editors that would snapshot and start in a new named tab.
