### ISSUE TITLE
Allow Users To Select Their Default Dashboard Tab

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#7290]
## Is your feature request related to a problem? Please describe

Since the implementation of Projects whenever I visit https://my-self-hosted-gitpod.com and am logged in I am now shown the Projects tab by default. I currently have no use for this feature and would prefer to see the Workspaces tab by default. While clicking on the Workspaces tab is minimal effort it would be less effort to just have Workspaces be displayed by default.

## Describe the behaviour you'd like

I would like to have the option to set what URL is the default redirect or which tab is shown by default when visiting my self-hosted Gitpod instance (but this could also apply to gitpod.io). So instead of it going to `/projects` I could set this option to go to `/workspaces`.

## Describe alternatives you've considered

Writing a Grease Monkey script or something? Not sure yet. Would be better for it to just be in the product itself.

## Additional context

N/A

**Comment by pawlean** [comment]
Thanks for this feature request @jimmybrancaccio! I use Gitpod (not self-hosted) and actually agree with you on the default tab. I prefer the workspace tab as well. Maybe this also includes a potential conversation to include in Sass Gitpod as well as self-hosted. cc/ @jldec

**Comment by gtsiolis** [comment]
Hey @jimmybrancaccio! We recently changed this behavior in https://github.com/gitpod-io/gitpod/pull/7606 by :a: merging the workspaces list from projects and :b: defaulting to the workspaces page when loading `/`. You can read more about the reasoning behind this change in https://github.com/gitpod-io/gitpod/issues/7604 and you'll be able to also see this change live in Gitpod.io after tomorrow morning when we'll deploy the latest changes.

Adding this as configuration could be interesting but I think having sensible defaults[[1](https://en.wikipedia.org/wiki/Convention_over_configuration)] can be a better way forward and free users from another choice they have to make.

Closing this for now since the latest changes will resolve the problem state here, but feel free to reopen if you think this feature request could be still interesting to explore. 📕
