### ISSUE TITLE
Oh, no! Something went wrong!

### ISSUE THREAD

**Issue by nedenneden32** [gitpod-io/gitpod#7348]
### Bug description

edit in gitpod
 Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: hostname required

Unknown Error: { "code": -32603 }

### Steps to reproduce

bu hatayı alıyorum yardım edermisiniz lütfen

**Comment by laushinka** [comment]
We're currently experiencing an outage due to issues pulling images from our cloud provider container registry. This is causing some workspaces not to start.
The cloud provider has confirmed the issue on their side, and are working towards the fix.
For status updates: at https://www.gitpodstatus.com/

**Comment by laushinka** [comment]
The incident has been resolved.
