### ISSUE TITLE
Add vm86 seccomp container runtime option to be able to run 32-bit binaries

### ISSUE THREAD

**Issue by 0xd61** [gitpod-io/gitpod#7358]
## Is your feature request related to a problem? Please describe
I need to execute a 32-bit binary in gitpod which is currently not possible because of seccomp restrictions.  The necessary syscall needed in the container runtime options is `vm86` (https://docs.docker.com/engine/security/seccomp/).

## Describe the behaviour you'd like
I'd like to run the 32-bit binary. Current output of strace:
```
gitpod /tmp $ strace ./ti_cgt_pru_2.3.3_linux_installer_x86.bin 
execve("./ti_cgt_pru_2.3.3_linux_installer_x86.bin", ["./ti_cgt_pru_2.3.3_linux_install"...], 0x7fff96baae10 /* 103 vars */) = 0
strace: [ Process PID=163324 runs in 32 bit mode. ]
brk(NULL)                               = ?
+++ killed by SIGSYS (core dumped) +++
Bad system call (core dumped)
```

## Describe alternatives you've considered
I currently have no alternative because Texas Instruments only provide their tools as 32-bit binary.

## Additional context
The tool I'd like to run can be downloaded from here: https://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/2.3.2/ti_cgt_pru_2.3.2_linux_installer_x86.bin

**Comment by axonasif** [comment]
This should also solve #5532

**Comment by kylos101** [comment]
@utam0k this item is currently in our inbox (not scheduled or prioritized). May I ask you to read it and help with the below questions?

Are there any risks we should consider with supporting `vm86`?

How would supporting `vm86` impact runtime performance and compatibility? 

This is new territory for me, which is why I am asking conservative questions. :smile: 

cc: @csweichel

**Comment by utam0k** [comment]
@kylos101 I'll have to do some research, so give me some time. I'll do some research!

**Comment by kylos101** [comment]
Hi @utam0k :wave:, yes, that makes perfect sense, I would too. :smile: 

Also, you may set this to _scheduled_ for now. That way you can focus on other assigned work that is _in-progess_, and start on this research later. :+1:

**Comment by utam0k** [comment]
@kylos101 
This system call provides an in kernel virtual machine for x86 real mode on x86.[^1] It is generally used in DOS emulators. Anyway, it is a system call closely related to the Intel CPU. I think that there is a lot to consider about this system call. I would recommend using qemu instead of allowing this system call.
> Are there any risks we should consider with supporting vm86?

We only need to allow it in our seccomp profile, so there will be no performance issue.
> How would supporting vm86 impact runtime performance and compatibility?

[^1]: https://wiki.osdev.org/Virtual_8086_Mode

**Comment by utam0k** [comment]
Hi @0xd61,

We won't be able to support vm86.

However, a workaround you can do in Gitpod is:

1. Install qemu
2. Download an image
3. Use qemu to run that image, and then run your related 32-bit binary

Maybe this repository is helpful for you.
https://github.com/fntlnz/gitpod-k3s

**Comment by axonasif** [comment]
@utam0k can we have binfmt_misc support at least? With that it would be easier to utilise qemu-user translation layer.
Although I'm not an expert about it's security implications. I had tried to mount it and it was denied.

**Comment by utam0k** [comment]
@axonasif I'll do some research and try it out. Please wait a moment. Just be sure, can you tell me what commands you used.

**Comment by utam0k** [comment]
@axonasif Although I looked into the possibility of using seccomp notify to make it executable, software running with binfmt_misc will be able to influence the host. This means that support is strictly from a security perspective.

cc: @csweichel

**Comment by axonasif** [comment]
> software running with binfmt_misc will be able to influence the host. 

Understood, thanks for looking into it @utam0k. 👍 

> However, I think we can use these commands in gitpod. Isn't this good enough?

Yeah, it's fine and probably the only way to run dynamic x86 programs. However you know, nothing like being able to run x86 programs alongside the gitpod environment but since there are security concerns so nothing to do either I guess.

We can manually invoke a x86 program with qemu-i386 emulator:
```bash
sudo install-packages qemu-user; # It also tries to mount `/proc/sys/fs/binfmt_misc/` and alter stuff there.
qemu-i386 ./something_32bit; # I ran a hello world 32bit C program
```
You see, this requires some manual steps and will likely fail for dynamic and complex programs. But anyways, this is approach is useless.

**Comment by utam0k** [comment]
@axonasif Thanks for your support! I'm sorry but it seems to be difficult at the moment. I'll let you know if I come up with something better.

**Comment by RedstoneWizard08** [comment]
Note that to enable binfmt_misc support one way to do it (which I use the most) is running this command:

```sh
docker run -it --rm --privileged tonistiigi/binfmt
```

Note that I think this modifies files in /proc or /sys so it doesn't work on GitPod.

**Comment by utam0k** [comment]
@RedstoneWizard08 Thanks for your great information.

It should be correct in most cases.
> Note that I think this modifies files in /proc or /sys so it doesn't work on GitPod.
