### ISSUE TITLE
Open in VScode issue (self hosted)

### ISSUE THREAD

**Issue by hm2075** [gitpod-io/gitpod#7360]
### Bug description

using main.2090 branch

open in vscode option returns

Failed to connect to Gitpod workspace black-xerinae-jgitsfxe: FetchError: request to https://xxx.com/static/bin/gitpod-local-companion-windows.exe failed, reason: certificate has expired

same issue on previous builds

### Steps to reproduce

install main.2090  ,   open gitpod and select open in vscode

**Comment by akosyakov** [comment]
I think it is something wrong with your local certificates, probably they have to be updated.

**Comment by hm2075** [comment]
not entirely sure,      certs are good
some other person mentioned the same issue in discord

**Comment by sedattanir** [comment]
I have same errors. My local certificates are signed by letsencrypt. I can't use this option. It does not give certificate error on localhost. The certificate appears to be signed.

**Comment by Pothulapati** [comment]
Hey 👋🏼 

Today, I ran into this, while running a self-hosted instance of gitpod with let's encrypt for SSL!

Based of comments from https://github.com/gitpod-io/gitpod/pull/5944#issuecomment-933665265, This happens when your server's root cert is [cross signed by the already expired `DST ROOT CA X3` issuer cert](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/), while your client isn't updated with the latest `open-ssl` that takes into account of the other signer of the cert i.e `ISRG ROOT X1`. This cross-signing is done to maintain backward compatibility with android devices by let's encrypt by default!

`gitpod` extension which uses `node-fetch` npm dependency, and code's underlying `electron`, to perform a `fetch` call on the URI to download the `remote-local-companion` app seem to use an older version of an ssl library (possible openssl) that hasn't got the latest changes, and hence the expired root certificate error. (i'm not entirely sure yet, on who exactly is the problem here i.e `node-fetch` or underlying `electron` in code)

There are multiple ways to get around this:

- Update the server to not have a root certificate that is cross signed by `DST`. For Self-Hosted, This means [setting the `preferredChain` to `ISRG Root X1` in the `Issuer` object of Cert Manager](https://cert-manager.io/v1.0-docs/configuration/acme/#use-an-alternative-certificate-chain). I've tested this, and code **seems to work after this change**. But this means that we would lose Android device compatibility prior to 7.1.0, which seems fine for gitpod self-hosted, as our clients are not native android clients, and this should work fine from browsers.

- Obviously, Like you'd expect it's more of a client issue than the server, as let's encrypt s trying to do the right thing i.e maintain device compatibility, while its the client who is struck on a older version. As we can't skip SSL verification in the extension for security reasons, We could first try to see if using a latest version of `node-fetch` fixes it. If that doesn't fix it, then it could be a underlying old ver dependency issue in code 🤔

**Comment by Pothulapati** [comment]
So, I was able to fix it by building a version of the `gitpod` extension that had a latest version of `node-fetch`. Obviously, Ass we can't expect servers to not have root certs signed by the expired `DST ROOT CA X3` issuer. Updating the client, to use the latest version of SSL library that knows about ISRG Root X1 is the right way to fix this issue!

Will raise a PR, and update progress here in the issue! :)

**Comment by Pothulapati** [comment]
https://github.com/gitpod-io/openvscode-server/pull/305#issue-840141234 PR bumps the node-fetch, which fixed what I was facing locally but this could also be caused when they are using an older version of code (and thus getting an older version of `electron`). So, Updating Vs Code could very well fix the issue!

Thanks!

**Comment by akosyakov** [comment]
It was published, please try.
