### ISSUE TITLE
Epic: unify ports view between web and desktop

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7408]
Build a prototype of Ports view using webview in VS Code Browser which resembles Ports view from Remote SSH but provides our features.
As a result list difference between features.

**Comment by akosyakov** [comment]
We should be careful here. There are features where we should align, and there are important integration points like ports. VS Code ports view is very limited to want we have now and switching to it will block us innovate in this point. I think it makes sense for VS Code desktop since we rely there on Remote SSH for port forwarding. But in case of web it does not make sense. We should rather study our users and improve ports view for them, i.e. how to connect several workspaces in one network with services on localhost, how to represent it in ports view, how to resolve conflicts there and so on. Switching to another view and removing features will rather break experience.

**Comment by jeanp413** [comment]
Could you point out what features would be missing if we use the tunnel view?

**Comment by loujaybee** [comment]
Will remove this one from the inbox, but, it's something we should consider as part of: 

- https://github.com/gitpod-io/gitpod/issues/7184

**Comment by filiptronicek** [comment]
For some more context: 
this is the ports view Gitpod contributes on the Browser version of VS Code:
![image](https://user-images.githubusercontent.com/29888641/171014886-b529dc93-c230-4075-b162-c36171fa0bb4.png)

this is the ports view that is bundled into VS Code:
![image](https://user-images.githubusercontent.com/29888641/171015348-e3a64c9c-146b-4f95-ace4-d4746395dee9.png)

**Comment by loujaybee** [comment]
As discussed with @jeanp413 and @mustard-mh is that we'll start by: 

1. Unifying the existing browser view to be the same as the desktop view (focusing mainly on the ports view). 

2. We'll tackle issues around SSH connections, and achieving parity with **Remote - SSH** before turning on the functionality also in VS Code Desktop, and remove the dependency on Remote SSH, to gain more freedom over the experience. 

Let's scope this issue to part 1, and leave part 2 for another issue 🙏

**Comment by mustard-mh** [comment]
@loujaybee to look into what can we do further with this Epic

**Comment by loujaybee** [comment]
Complete + shipped 🚢  - If you have any issues or ideas, please let us know! 

**Announcements:** 

* https://www.gitpod.io/changelog#vs-code-ports-view-is-now-responsive
* https://www.gitpod.io/changelog#new-ports-view-in-vs-code
