### ISSUE TITLE
IDEA/Question: Access local server from Gitpod instance.

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#741]
This is just an idea that I don't even know how to solve but here is the problem:

1. We are doing some developments on Raspberry PI running on a local network.
2. We have a Python code running on Gitpod that its unable to reach the raspberry because it is in a different private network (NAT limitation).
3. We don't have access to the router to forward IP or ports.

Would there be any way we could create like a virtual thing in which both: The Raspberry PI and the Gitpod Instance have access to each other? Maybe a VPN, Proxy, VLAN, etc.

We had to move the python code running on Gitpod to a local computer, but I'm 😞 about it.

**Comment by jankeromnes** [comment]
Aha, that’s an interesting use case. We’d love to figure out how Gitpod can interact with remote devices (e.g. smartphones, Raspberry Pis, etc).

Quick question, does the Raspberry Pi have internet access? If it does, I’m thinking that maybe it connect to a Gitpod workspace, e.g. by setting up an SSH tunnel, so that the workspace can communicate back to the Pi.

Your Python code just needs network access to the Pi? (I.e. no USB flashing or Bluetooth link or anything else like that?)

**Comment by svenefftinge** [comment]
Maybe you can run something like localtunnel on your PI?
This article seems to be helpful https://www.pluralsight.com/guides/exposing-your-local-node-js-app-to-the-world

**Comment by alesanchezr** [comment]
@jankeromnes Yeah just access to the PI, we are exposing a server on the PI.

@svenefftinge this sounds like a possible solution 😄 I will read more about it and post it here if I'm able to solve it.

**Comment by brandonkal** [comment]
Some options:
https://github.com/inlets/inlets -- in my experience, it is much more pleasant than ngrok/localtunnel but keep in mind it is a newer project.
https://www.zerotier.com/
The latter option is rather slick because it adds another network interface, so as far as the app is concerned, the two devices are a local network. I haven't tried either with GitPod though.

**Comment by svenefftinge** [comment]
Here's an article about using inlets for it:
https://www.gitpod.io/blog/local-services-in-gitpod/
