### ISSUE TITLE
Terminal text has wrong layout on startup

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7443]
### Bug description

![image](https://user-images.githubusercontent.com/25115070/148090455-74985e84-c189-4872-b88c-e2cdf3b2cb10.png)

### Steps to reproduce

1. Open a workspace 
2. Open terminal panel
3. :bug: Observe terminal text has an odd layout

**Comment by svenefftinge** [comment]
I see this regularly on most of my workspaces. Seems to happen reliable when the output is sent before the terminal was rendered or so.

**Comment by jldec** [comment]
+1 - I thought it was a vscode insiders thing. After changing that setting the issue appeared to be fixed for one or two workspaces, but now I see the 2-char wide terminal most of the time on workspace start like before.

**Comment by jeanp413** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/139457

**Comment by svenefftinge** [comment]
This is really annoying as it happens very often. Seems like the VS Code team has issues reproducing this. 
I left [a comment](https://github.com/microsoft/vscode/issues/139457#issuecomment-1020879323) but maybe we can help fix this?

**Comment by mustard-mh** [comment]
To reproduce this issue, we can
1. Open a `empty` new workspace [like this](https://gitpod.io/#github.com/mustard-mh/empty) which terminal will not shown automatically (if it does, we should drag hidden it and start a new one)
2. Wait a moment (wait the terminal console load res)
3. Open terminal

|Incorrect|Correct|
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/20944364/153261261-2aec3c69-426a-490e-a5db-f8a752bc9728.png) | ![image](https://user-images.githubusercontent.com/20944364/153261333-1c844f98-8748-4f22-a745-8e894f6dd6e8.png) |

PS. Incorrect one got a new line of input

So it might caused by terminal backend render didn't know window size well

So, may be we can improve this by auto display terminal like codespace, and with it, it can also mention users that Gitpod can edit and run code (XD

|Codespace|
|:-:|
|![image](https://user-images.githubusercontent.com/20944364/153264352-ffb7ee58-7a59-4d28-a59a-522416e7a7db.png)|

cc @jeanp413

**Comment by jeanp413** [comment]
@mustard-mh tried your steps but cannot reproduce :thinking: how do you open the terminal? I use the <kbd>ctrl+`</kbd> shortcut.

I took a look at this a long time ago and from what I remember is a race condition when creating the process and xterm.
I know it happens in gitpod production and it was easier to reproduce from sources mid of last year but now It's really hard, I tried multiple times both in gitpod and locally but had no luck yet :disappointed:

**Comment by mustard-mh** [comment]
@jeanp413 are you use vscode stable? I can reproduce this consistently with stable version, but insider can't

**Comment by jeanp413** [comment]
I'm using insiders will try stable, but does this mean is "fixed" in insiders or that it's even harder to repro =S

**Comment by jeanp413** [comment]
Using stable I can repro the with your steps @mustard-mh
Don't see any changes related that could fix this, so I guess it's just harder to repro :disappointed:

**Comment by jeanp413** [comment]
I think this got fixed in https://github.com/microsoft/vscode/commit/e3dcaa1fdac18c1aeb965527ff3a9d553c5890cb, @mustard-mh we can check in our meeting on Monday

**Comment by mustard-mh** [comment]
Yes, also find it out, the default value of xterm.js is `cols=2` `rows=1`

**Comment by mustard-mh** [comment]
( If you pass cols=0 and rows=0

**Comment by mustard-mh** [comment]
Also file an issue in xterm.js https://github.com/xtermjs/xterm.js/issues/3647

**Comment by mustard-mh** [comment]
Should we cherry-pick the changes that upstream make https://github.com/microsoft/vscode/commit/e3dcaa1fdac18c1aeb965527ff3a9d553c5890cb to ensure our stable vscode works well? Or just wait for another release of vscode?

**Comment by jeanp413** [comment]
Just wait for next stable release =)

**Comment by jeanp413** [comment]
Stable release 1.65 got deployed with the fix, closing this
