### ISSUE TITLE
[installer] Use regionless GCR endpoints for better distribution of container images

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#7446]
## Is your feature request related to a problem? Please describe
Previously the self-hosted container images were on `gcr.io/self-hosted` which is the regionless endpoint for GCR. They were moved to using the registry `eu.gcr.io/gitpod-core-dev` project, but that GCR project does not have the regionless endpoint enabled.

## Describe the behaviour you'd like
Enable the use of `gcr.io/gitpod-core-dev` to allow for better distribution of the images. This will allow US and non-US entities to use the same endpoint (and potentially allow for better content caching on Google's end)

## Describe alternatives you've considered
Update scripts to use the `eu.gcr.io` rather than `gcr.io` registry.

**Comment by MrSimonEmms** [comment]
If accepted, the Installer will need to be reconfigured to accept any future official Gitpod pull registries, eg as in [constants.go](https://github.com/gitpod-io/gitpod/blob/263119581e4f508bf87b1cea4adcc415df268a87/installer/pkg/common/constants.go#L20). The registry `eu.gcr.io/gitpod-core-dev/build` is considered the official Gitpod pull registry

**Comment by jgallucci32** [comment]
If I remember correctly, self-hosted 0.4.0 started out on eu.gcr.io then switched in 0.5.0 to use the global endpoint. I guess my suggestion is you might consider doing this again and making `grc.io` the official Gitpod pull registry.

**Comment by meysholdt** [comment]
I'm all in favor of a "global" registry to have high download speeds and low egress costs. 

However, the [docs](https://cloud.google.com/container-registry/docs/overview#registries) say about gcr.io:
> gcr.io currently hosts the images in the United States, but the location may change in the future

**Comment by meysholdt** [comment]
@mads-hartmann and I discussed this and here is our position :) 

It would be great if official releases would not be downloaded from `eu.gcr.io/gitpod-core-dev` but from another registry. This is because the gitpod-core-dev is for development only and we need the liberty to "clean up" and purge all images from there if we choose to. 

Instead, it would be great if the @gitpod-io/engineering-self-hosted team would have a "release" job that copies the images from gitpod-core-dev to a "releases" registry. 

The "releases" registry would be owned by the @gitpod-io/engineering-self-hosted team - allowing to control address, UI, access, global distribution, download counters, cleanliness of the inventory, etc.

The "releases" registry could be GCR - but GCR is [on the way out and superseded by Googles Artifact Registry](https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry). However, just like GCR the artifact repository [supports multi-region repositories](https://cloud.google.com/artifact-registry/docs/repo-locations#location-mr) but not truly global repositories. If that really is a problem you could also make the images available in all three multi-regions (eu, us, asia). 
Alternatively, you could consider publishing the images on the [Github container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

In fact, `gcr.io/self-hosted` used to be this "releases" registry.

I'm happy to help with setting up a releases registry or the needed GCP project. 

Since I haven't been involved with the release process of self-hosted in the recent month I hope that my comments are helpful and fit with what you have already built/discussed. :)

**Comment by MrSimonEmms** [comment]
I think that it's broadly a good idea to have a registry that we own for public consumption. As we don't just support releases any more but any build in Werft, our registry would have to be a mirror of everything so we would need to be wary of the cost implications of this.

Personally, I think that having a solution that we don't have to manage from an infrastructure point of view would be ideal - GitHub or Docker Hub would be my preference if they are truly global (I've never done any testing with this, but my assumption is that it would be).

And yes @meysholdt, your comments were very helpful. Thank you

**Comment by meysholdt** [comment]
> As we don't just support releases any more but any build in Werft

If we can agree on an end-of-live for images, it's fine to support "any build in Werft" from `eu.gcr.io/gitpod-core-dev` :) 
I assume supporting "any build" is valuable because users can try fixes immediately or help us test feature branches.  However, I'm not sure if it's good when users stay on these non-release builds forever. 

This would allow us to remove images from `eu.gcr.io/gitpod-core-dev` when their end-of-life has been reached, e.g. after  3 or 6 months.
