### ISSUE TITLE
nvm changes do not persists

### ISSUE THREAD

**Issue by borisyordanov** [gitpod-io/gitpod#7459]
### Bug description

Changing the node version with nvm only works in the current terminal. If another terminal is opened it uses a different node version

### Steps to reproduce

0. Change the `NODE_VERSION` env variable to your desired version
![image](https://user-images.githubusercontent.com/12392666/148244774-72e48fdb-0781-4abf-a4d7-9b4b1746eec4.png)

1. Add this task to `gitpod.yml`
```
tasks:
  - name: Setup node
    init: nvm install && nvm use && nvm alias default 14
```
2. Add an `.nvmrc` file that sets the version != 16
3. Open a new workspace and make sure the task is executed
4. Open a new terminal and compare the node version between the two terminals
![image](https://user-images.githubusercontent.com/12392666/148244465-3790a484-54eb-4123-a943-f19edb5eb719.png)

### Workspace affected

All of them

### Expected behavior

The node version is changed permanently for the entire workspace

### Example repository

https://github.com/borisyordanov/Gitpod-Node-Example

### Anything else?
Changing `NODE_VERSION` seems to make no difference

**Comment by svenefftinge** [comment]
Gitpod currently only persists the file contents under`/workspace` between workspace sessions (a prebuild is also workspace). `nvm` however persists changes in the user home directory. In order to have them persisted you need to make those changes in the docker file.
You can [find instructions here](https://www.gitpod.io/docs/languages/javascript#node-versions).

**Comment by axonasif** [comment]
@borisyordanov you can also use `before:` task spec instead of `init:` but the dockerfile approach is recommended as @svenefftinge told.
