### ISSUE TITLE
[Dashboard] refactor the CodeText utility component

### ISSUE THREAD

**Issue by trumbitta** [gitpod-io/gitpod#7555]
As detailed in the https://github.com/gitpod-io/gitpod/pull/7302#pullrequestreview-847622451 thread, the `CodeText`utility component seems to need a refactor replacing the `<span>` tag with a `<code>` tag which is the right semantic choice for such a component.

Beware:

- Are there any cases in the codebase where a `<span>` tag is actually the best choice?
- Will this change work seamlessly? Better check each occurrence.

**Comment by jankeromnes** [comment]
Thanks for opening this issue! [100% agree with you](https://github.com/gitpod-io/gitpod/pull/7302#discussion_r790555966).

Additionally, instead of having a single-line React component with a bunch of CSS classes (that everyone might forget to use or not know about), I think we should just use `<code>` everywhere (more semantic and "natural"), and apply our custom CSS classes to the `code` element in [index.css](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/index.css) (so that they apply everywhere consistently).
