### ISSUE TITLE
Gitpod broken on iPad w/ iOS 10.3.3

### ISSUE THREAD

**Issue by TheParadoxTheory** [gitpod-io/gitpod#756]
**Describe the bug**
When I try to open a gitpod workspace on my iPad, (after it exceeds the 3/3 running state) it gets stuck on a blank screen with the gitpod logo 

**To Reproduce**

Opening gitpod through an iPad 4th generation (Non-jailbroken) running IOS 10.3.3, Safari (and other browsers for that matter)

**Expected behavior**

I expected the workspace to open (don’t understand how that’ll help) lol

**Comment by jankeromnes** [comment]
Hi again @TheParadoxTheory, thanks for trying Gitpod on your iPad!

We're currently working on improving the iPad support, as that's an important and super-cool use case we want Gitpod to address flawlessly. This general effort is tracked in #28.

Also, note that on iPad, all web browsers are actually "skins" around a Safari webview (Apple doesn't allow anyone else to ship a web engine to iOS, so everyone is pretty much stuck with Safari, with a customized theme/experience/bookmarks/etc).

Gitpod is currently able to load properly on iOS 12, but there are a few annoying issues like [keyboard arrows not working](https://github.com/gitpod-io/gitpod/issues/311).

The good news is that on iOS 13 (currently in beta I think), some of these issues have been fixed by Apple, and thus web IDEs like Gitpod should work much better there.

Unfortunately, iOS 10 is probably a bit too old for us to target realistically, although I'd love to eventually get Gitpod to work on almost all mobile devices.

**Comment by TheParadoxTheory** [comment]
Thanks for the information, appreciate it, I’m gonna use it on on my Iphone, works flawlessly
