### ISSUE TITLE
Provide access to the keyboard during the BaseImage phase

### ISSUE THREAD

**Issue by eryjus** [gitpod-io/gitpod#759]
I am trying to install MySQL 8.0 as part of a Dockerfile.  During this installation, the installation wants to secure the root user -- asking for a password.

It would be good to be able to key that password when prompted rather than have it sitting in a Dockerfile for everyone to see.

See this commit for an example: https://github.com/eryjus/cba-lib/tree/95c4e87ee37ae613a83665821776cb6c5197f170

Additionally, when this starts and hangs waiting for input, the container cannot be shut down and needs to wait for timeout to be closed.

**Comment by jankeromnes** [comment]
Hi @eryjus, thanks for the great feedback!

Generally, we try to avoid interactive behavior (like prompting for input) in Dockerfiles, because it doesn't play well with automated builds. So personally I'd try to prevent it from prompting, e.g. by:

- disabling the root user protection if possible (that's already done by Gitpod afterwards)
- using tricks like `echo "value" | cmd` (like you already did)
- setting `DEBIAN_FRONTEND=noninteractive`

Also, it's not a good practice to have a password for the root user (even if it's kept "secret"), because the password can still be discovered/guessed/brute-forced by hackers, and then all the users of your image are suddenly exposed. (This happened recently with several core images on Docker Hub...)

On the other hand, did you know that Gitpod has an [official MySQL image](https://hub.docker.com/r/gitpod/workspace-mysql)? Maybe that doesn't give you exactly the version you need, but for inspiration, the Dockerfile is [here](https://github.com/gitpod-io/workspace-images/blob/master/mysql/Dockerfile).

> Additionally, when this starts and hangs waiting for input, the container cannot be shut down and needs to wait for timeout to be closed.

I agree that that's not a good experience. We should probably try to address this in Gitpod somehow. I wonder what other Docker-building services handle that (e.g. CircleCI, Docker Hub Automated Builds, etc.)

**Comment by eryjus** [comment]
OK, I have what I think is a working solution and I would like to start a pull request.  Before I do that, however, I am not really sure how to go about testing what I am asking to pull.  Any help with how to will be appreciated.

**Comment by svenefftinge** [comment]
Is it possible to provide the password when the database starts (i.e. not during docker build)?
In that case you could use an ENV variable. Which is the preferred way for injecting user-specific secrets.
See https://www.gitpod.io/docs/47_environment_variables/

**Comment by eryjus** [comment]
@svenefftinge, I was able to make that suggestion work.  This overcomes the immediate need that generated this request.

With the resulting conversation, this then leaves (in my mind) 3 bits to consider, which might just be better served as separate requests from this one:

1. Add `debconf-utils` into the gitpod/workspace-full image to be able to take advantage of delayed configuration.
2. Set up `DEBIAN_FRONTEND=noninteractive` by default during the docker build to push for delayed configuration -- perhaps by setting that by default and the having the Gitpod Layer un-set it...?
3. Add the ability to shut down a running Gitpod during the build phase when it is waiting for input -- in case something happens to sneak through.

**Comment by 32leaves** [comment]
We could consider introducing something like a `no_output_timeout` (like in [CircleCI](https://circleci.com/docs/2.0/configuration-reference/)) whereby the image build is terminated if it doesn't produce output for some time.
