### ISSUE TITLE
Prebuild hasn't run in 7 days

### ISSUE THREAD

**Issue by jaredp** [gitpod-io/gitpod#7648]
### Bug description

According to https://gitpod.io/t/dandy-eng/orthlyweb/prebuilds, the last prebuild was made 7 days ago

The last push to master on https://github.com/orthly/orthlyweb was 3 hours ago. There were lots of pushes in the last week.

### Steps to reproduce

To go https://gitpod.io/t/dandy-eng/orthlyweb/prebuilds, see there are no recent prebuilds

### Expected behavior

There should be many prebuilds from the last week

**Comment by svenefftinge** [comment]
I can confirm, that the last prebuilds ran on January 10th. It seems like the GitHub app has been deactivated somehow. 
Could you check the configuration on the org? https://github.com/apps/gitpod-io

**Comment by jldec** [comment]
User has reinstalled the app but still reports prebuilds not happening.
([support thread](https://app.frontapp.com/open/cnv_inmzwne) - internal)

**Comment by jldec** [comment]
Scheduled for investigation - related to #7812

**Comment by jldec** [comment]
Asked for additional information in support thread (internal)

**Comment by jldec** [comment]
From (internal) [thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1643368559365809)

Our tracing reports that push events are being received, but prebuilds are not being triggered because of an authorization error in `fetchConfig`.

```
Error: Unauthorized
    at GitHubGraphQlEndpoint.<anonymous> (/app/node_modules/@gitpod/server/dist/src/github/api.js:106:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@gitpod/server/dist/src/github/api.js:19:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

from @AlexTugarev 

We would need to check few things:

- which account/token is used for the fetchConfig? is it the same as the installer, or at least one user that also have permissions for the GitHub App Installation? we're picking some team owner, maybe that user has no access to the installation, see https://github.com/gitpod-io/gitpod/blob/28597c5342fd6f9ca7bcc4bd6859928760df9e45/components/server/ee/src/prebuilds/github-app.ts#L358
- when did the installer updated token, i.e. did a login? it could be outdated.

**Comment by jldec** [comment]
User reports that prebuilds have resumed after removing the additional owner (who did not have repo access).
@jaredp you should be able restore the owner role for that member now that #8128 is fixed.
