### ISSUE TITLE
Run performance testing on the new SSH gateway

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7712]

**Comment by loujaybee** [comment]
Assigning to @akosyakov, it seems a pragmatic solution is to simply run some concurrent users tests on a smaller node / test environment.

**Comment by akosyakov** [comment]
@iQQBot Will do automatic testing in prev envs and test several cases:
- many connections to learn the cost of single connection in terms of memory and CPU
- and several connection with huge amount of data back and forward
- several connections and see how long they can stay alive with heartbeat

**Comment by mustard-mh** [comment]
Comment updated
cc @loujaybee @akosyakov @iQQBot

**Comment by akosyakov** [comment]
@mustard-mh It would be nice if you document here steps to did you test it that someone can reproduce and verify. 🙏

**Comment by mustard-mh** [comment]
Prepare workspace pair AB like this:
1. We need to keep workspace alive, so edit gitpod-cli to build a new tmp exec file with command to keep heartbeat: send heartbeat every 30 seconds
2. Open a workspace `A` as target workspace, copy file that step1 produce to it, and exec file to keep it alive
3. Open a workspace `B`, repeat step 2

Testing in prev envs and test several cases:
- many connections to learn the cost of single connection in terms of memory and CPU 
  For B, write ssh connect script with connect num 10000
- and several connection with huge amount of data back and forth
  Simply exec scp with large file (`dd if=/dev/zero of=test bs=1M count=1000`) from A to B and B to A several times
- several connections and see how long they can stay alive with heartbeat
  For B, open several terminals connect to A and exec command like `htop`

**All cases need to observe cpu and memory of the `ws-proxy`**
**Remember to delete workspaces after test, since they are always active**

**Comment by akosyakov** [comment]
> For B, write ssh connect script with connect num 10000

Do you have scripts to share it? Did you try dropping and reopening connections to see whether ws-proxy leaks memory on such connections?

**Comment by mustard-mh** [comment]
Add test case: try dropping and reopening connections to see whether ws-proxy leaks memory on such connections
Bug👾 found and then fixed
https://github.com/mustard-mh/test/tree/gp/ssh-load

**Comment by akosyakov** [comment]
@mustard-mh Do you think we can contribute something to codebase for future usage? i.e. add them to ws-proxy with docs how to run?

**Comment by akosyakov** [comment]
Let's consider it as done.
