### ISSUE TITLE
Feature: Give the user an option to open an existing workspace connected to the same git URL or to create a new workspace

### ISSUE THREAD

**Issue by ghost** [gitpod-io/gitpod#7723]
## Is your feature request related to a problem? Please describe
Yes and no, more of a user error then anything with the service. This would prevent the accidental creation of projects when you are really just trying to open an existing workspace, which we then have to delete and then navigate to the gitpod dashboard to launch the existing workspace/s that is connected to that project.

## Describe the behaviour you'd like
We document all our future projects with an environments table in the readme file so that developer can easily get an overview and launch the project from gitlab docs. But an issue/feedback that i have gotten is that developers (including myself) who are actively working on a project, every now and then click the "open in gitpod" button thinking that it would open the existing workspace that they are working on.

![img](https://imgur.com/glQJRUr.png)

The future that i am requesting is to match the git URL that is trying to be opened, eks: https://gitpod.io/#https://github.com/gitpod-io/gitpod and check if there are any existing workspaces that use that git URL.

If there are none found then just create a new workspace, but if there are already workspace/s existing show a list of them and giving the user an option to either click one of the existing workspaces to open or a button create a new one. Also maybe add a parameter that just creates a new workspace that skips this check for others that might need this or the other way around.

**Comment by svenefftinge** [comment]
> The future that i am requesting is to match the git URL that is trying to be opened, eks: 
> https://gitpod.io/#https://github.com/gitpod-io/gitpod and check if there are any existing workspaces that use that git URL.

Gitpod currently does this when the same commit is opened in a running workspace already. From what I understood you should see this dialog, or are you opening different commits?

**Comment by mickmister** [comment]
I can see the benefit of showing this whether the developer has purposely or accidentally opened Gitpod from a different commit. It can be a reminder of other workspaces that you might choose from instead of opening a new workspace, and checking out the branch you want to use in the terminal instead of in the initial context.

I think this is particularly useful to newcomers of Gitpod. The idea of a saved workspace, and differentiating between resuming and creating a workspace, can be difficult to grasp if you're not familiar with the concept. Especially the detail about how a specific commit is tied to a specific workspace, for the lifetime of that workspace (I think that's how it works?).

Developers probably think about their development environments as they would structure them on their OS. One example would be having one copy of each repo on your computer, with the workflow of switching between branches in each of those folders when different tasks are being worked on. Gitpod  embraces the idea of _ephemeral_ development environments, which is one of my favorite things about the service. When a developer clicks "Open in Gitpod" on a repo's README, they probably think "create a directory for this repo if not exists", rather than "create a new directory for the latest commit of master". If the URL being sent to the `gitpod.io/#` route is coming from the repository root page, rather than a URL pointing to a commit, then we could treat it differently and expect the user to possibly want to reuse an existing workspace.

I think it's important to tailor the experience to someone who has never used Gitpod, or is new to software development, e.g. a beginning open-source contributor. This may include:

- While creating their first workspace, explain how the ephemeral nature of the workspaces works, and how a workspace is tied to a specific commit. This may already be explained in a sign-up flow. It's important to have them see the value in the ephemeral design, and understand it clearly.
- Provide an alternative workflow that matches what they would expect on their own OS. This would be a workspace-per-repo approach. I think this option should be available, yet the ephemeral workflow should be the recommended option in each workspace setup landing page. It wouldn't be a permanent either/or option for the different workflows. Somehow conveniently provide a choice that fits the familiar workflow. Migrating a user's thinking over to ephemeral environments may need to develop over time.

**Comment by AjXUthaya** [comment]
We are talking about different commits in this scenario @svenefftinge, beacuse the "open in gitpod" will always refer to the master branch/URL. Updating this to correspond to every commit/branch in the readme and then for the user to lookup the branch they want to open again in not a realistic scenario, not from the gitlab project docs at least and as mentioned above here if they create a new workspace they are more likely to just checkout to the commit/branch they need then to select the branch to launch from (it's just what is most natural from how we used to working from before)

**Comment by mickmister** [comment]
Can we treat issue and PR links differently, so a developer can visit an issue they started working on, and pick up where they left off by clicking the `Gitpod` button on the issue.

So if the Gitpod URL is https://gitpod.io/#https://github.com/gitpod-io/gitpod/issues/7723, clicking the green `Gitpod` button on the issue on multiple occasions should ask me subsequent times if I want to go to the workspace that was created for this issue before, even if there is a newer commit on the main branch between when the first workspace was created and now.
