### ISSUE TITLE
[installer] Add support for Ingress traffic in cloud providers

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#7734]
### Bug description

The installer uses services `type=ClusterIP`. In particular for workspace clusters we need to use `type=LoadBalancer`, using standard ports 80 and 443. If we could also add support for additional annotations it would be ideal.

The goal here is to reduce the need for post-processing.

### Steps to reproduce

-

**Comment by corneliusludmann** [comment]
Thanks, @aledbf, for opening this issue.

Could you help me better understand what we actually need?

1. Does a workspace cluster always need the ingress type `LoadBalancer` instead of `ClusterIP` (even for self-hosted installations) or does it depend? The question is about whether we can simply change the ingress [for the case `InstallatinKind = "Workspace"`](https://github.com/gitpod-io/gitpod/blob/9a7411f0e92e239142943a8aa07f4198736419eb/installer/pkg/config/v1/config.go#L146-L152) or if we need a configuration option for that.
  _We have so far [refrained from making this freely configurable](https://github.com/gitpod-io/gitpod/pull/7280) because otherwise, we would also have to fully support it. So it would be good to understand first, what we really need._
2. What support for additional annotations do you have in mind? @metcalfc once said that customers often need a specific set of annotations (e.g. for security policies) and that we maybe should support to configure a list of annotations in the config file. Again, it would be good to better understand the use cases here.

Thanks. :pray:

**Comment by aledbf** [comment]
> What support for additional annotations do you have in mind?

In `proxy`, `ws-proxy` or `ws-manager`, depending the `kind` of installation, if you are in GCP for instance, you need to set 
[`cloud.google.com/neg` ](https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg) in the service.

**Comment by aledbf** [comment]
> Does a workspace cluster always need the ingress type LoadBalancer instead of ClusterIP (even for self-hosted installations) or does it depend? 

I think this is more related where are you running Gitpod than anything else. If you are running in the cloud (not important which one) you will use a service type `LoadBalancer`.

There is one exception, EKS/AWS, where you need to use [Ingress (ALB) in order to avoid websocket disconnections
](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/lib/charts/assets/ingress.yaml)

**Comment by aledbf** [comment]
> We have so far refrained from making this freely configurable because otherwise, we would also have to fully support it. So it would be good to understand first, what we really need.

I share that idea until I need to do this post-processing, which is weird and not easy to maintain

```
yq e --inplace 'select(.kind == "Service" and .metadata.name == "ws-proxy").spec.type="LoadBalancer"' manifests.yaml
yq e --inplace 'select(.kind == "Service" and .metadata.name == "ws-proxy").spec.ports=[{"name": "http-proxy","port": 80,"protocol": "TCP","targetPort": 8080},{"name": "https-proxy","port": 443,"protocol": "TCP","targetPort": 9090},{"name": "ssh","port": 22,"protocol": "TCP","targetPort": 2200}]'
```

**Comment by yevon** [comment]
I would also need supporting this, I have a self-hosted k3s cluster but I use ingress for all other services in just a unique public IP on ports 80 and 443, so I cannot have multiple public IP just for gitpod. (And i want to be able to run it without being exposed to internet).

I have a local dns server that redirects all requests of the self-hosted gitpod domains to the load balancer IP (in my case the load balancer IP is a local IP as I'm using metal LB, not public). I just tried redirecting all traffic on ports 80 and 443 to the local load balancer address, and then gitpods started succcessfully downloading and configuring all container images. Then I just reverted the change, without exposing gitpod to the internet just locally, and the workspace continued working nicely. It seems like it needs internet just during first start up. I don't really understand what happens as the logs just spawns 404 not found or similar network errors without any detail.

**Comment by aledbf** [comment]
>  it should support ingress and annotations. 

My request is to support service type=LoadBalancer, not Kubernetes Ingress.

One of the reasons we don't support Ingress OOTB is that some implementations, like NGINX, require a reload every time you change and Ingress or a Secret, which disconnects all WebSocket sessions.

**Comment by yevon** [comment]
But it is not so common to make changes to the ingress once you have set it up, and when you do so you can assume that some things might stop working temporarily. Or by doing so something can stop working permanently? Anyway this could happen anyway when you update gitpod isn't it?
