### ISSUE TITLE
workspace crash-loops when backup is not present

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#7754]
### Bug description

When trying to restart a workspace which doesn't have a backup present in core-dev, it crash-loops because the container exits too quickly. This happens because the supervisor does not start correctly, usually because it cannot file a file it expects from within its own container, e.g.

```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"unexpected error creating SSH key:\n    github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.newSSHServer\n        github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/ssh.go:33\n  - cannot locate sshd binary in path /.supervisor/ssh/sshd:\n    github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.prepareSSHKey\n        github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/ssh.go:157","level":"error","message":"err starting SSH server","serviceContext":{"service":"supervisor","version":"commit-60939d974914173c98aef7f5c623c9d2185edab1"},"severity":"ERROR","time":"2022-01-21T10:42:18Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb12c9a]

goroutine 38 [running]:
github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.(*sshServer).listenAndServe(0x0)
        github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/ssh.go:57 +0x3a
github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.startSSHServer.func1()
        github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/supervisor.go:1195 +0x194
created by github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.startSSHServer
        github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/supervisor.go:1189 +0x165
```

We have also seen this with `/.supervisor/supervisor-config.json` not being present.

Strange thing is that the absence of a backup should not affect registry-facade at all.

### Steps to reproduce

In a preview environment
1. start and stop a workspace
2. delete the backup from minio
3. try to restart the workspace

### Expected behavior

the workspace should fail to start and show an appropriate error message. No crash-looping should happen

**Comment by kylos101** [comment]
@Furisto unassigned you as this is still scheduled. If you're actively working, please assign and move to in-progress, otherwise feel free to leave "as is". :+1:

**Comment by sagor999** [comment]
So if backup is missing, then over here we will return an error, since we cannot download anything:
https://github.com/gitpod-io/gitpod/blob/7216e78f9437ceed4d3e9e57a0318fd66a1fe125/components/content-service/pkg/initializer/initializer.go#L425
This causes workspace to fail to init:
https://github.com/gitpod-io/gitpod/blob/a2c08bc8dcd6560470e519e6fe4dc92808a4671b/components/content-service/pkg/executor/executor.go#L81
And this is coming from this request that expects backup to exist:
https://github.com/gitpod-io/gitpod/blob/f8151d217f98719075d3447274135135143ebf3a/components/server/src/workspace/workspace-starter.ts#L941
And the root of the problem is here:
https://github.com/gitpod-io/gitpod/blob/f8151d217f98719075d3447274135135143ebf3a/components/server/src/workspace/workspace-starter.ts#L103

Ideally I guess we would want to check if backup actually exists in `workspace-starter:103` but not sure if it is possible.
Alternatively, if we fail to restore from backup, can we fall back and restore from git repo instead? (not sure if that would require walking back and creating workspace from a new initializer (git source). Ideally we would want to tell user that something is not right (missing backup) and ask if they want to try again (maybe back up is just late) or abandon backup and restore from git repo instead. 

tagging @gitpod-io/engineering-webapp team for input.

**Comment by kylos101** [comment]
@sagor999 I just added this to the WebApp Team project/inbox, this way it will be visible along with other issues, and can be prioritized accordingly. :+1: Also, I like the idea you shared, about asking the user how they would like to proceed - that is a better experience than just landing on the error itself.

**Comment by csweichel** [comment]
Core issue: as @sagor999 pointed out, we're not actually checking if there's a backup available but just assume that because there's a prior workspace instance there must be a backup.

I see two ways to replace this assumption:
1. as part of the workspace startup we could ask content service if the workspace has a backup. We'd add a corresponding function to the [`ContentService`](https://github.com/gitpod-io/gitpod/blob/e56ed09ccb99dccd27507c3559ca64a49e857786/components/content-service-api/content.proto#L11) which checks with the remote storage. Pro: very straight forward to implement, maintains a single source of truth: the backup itself in the remote storage. Downside: we pay the RTT to the remote storage (content service lives in the same cluster, RTT is negligible).
2. we start storing the [`final_backup_complete`](https://github.com/gitpod-io/gitpod/blob/92994450900d3b002acc829ef72f208247bf37c1/components/ws-manager-api/core.proto#L357) condition on the workspace instance and only expect a backup if that field is set. Pro: uses existing structures, does not incur remote storage RTT during workspace startup. Con: might mean we miss backups if we mess up our state management (which we have done numerous times in the past), does not integrate well with delayed backup mechanisms such as the PVC durability work discussed in the workspace team, where a backup may be created independently of the workspace instance.

**Comment by jldec** [comment]
Removed from WebApp Inbox for now - feel free to add back if necessary.

**Comment by atduarte** [comment]
Since the root cause is identified 👏 and it seems to be an issue in `server` I will remove it from the Workspace Inbox.

**Comment by Milo123459** [comment]
Hey,
Any updates on this? This error is proving to be extremely annoying.
