### ISSUE TITLE
[ws-manager-bridge] New registered clusters are not used until ws-manager-bridge is restarted

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#7778]
### Bug description

The registration of `workspace-clusters` using `gptcl` works without any issue but until the `ws-manager-bridge` deployment is restarted, no workspaces are scheduled in the new cluster.

### Steps to reproduce

Register a new cluster against a meta cluster and try to open new workspaces

**Comment by sagor999** [comment]
I believe this might be fixed with this commit: https://github.com/gitpod-io/gitpod/commit/3179adc80256e0023569b3baeba7627e1fef3c0c
https://github.com/gitpod-io/gitpod/blob/3179adc80256e0023569b3baeba7627e1fef3c0c/components/ws-manager-bridge/src/bridge-controller.ts#L61-L92

Currently this function `this.metrics.updateClusterMetrics` throws exception and that causes line below to never execute, so we are not able to call `createAndStartBridge` for new clusters, and that is why they are not working until restart of `ws-manager-bridge`. 

@geropl do you know when your fix from above will be deployed?

**Comment by kylos101** [comment]
@sagor999 I am guessing the next webapp deployment will be early this week. @geropl @JanKoehnlein , do you have an eta for when that may be?

**Comment by JanKoehnlein** [comment]
The plan is to deploy Tuesday 9am CET

**Comment by geropl** [comment]
Just found this issue, and it's hard to believe that cluster update should not work at runtime. We noticed the metrics error to appear around Christmas (do not recall precisely).
@sagor999  Do you trigger a restart of `ws-manager-bridge` every time you deploy a new workspace cluster to mitigate, as part of your deployment script? :thinking:

**Comment by aledbf** [comment]
> Do you trigger a restart of ws-manager-bridge every time you deploy a new workspace cluster to mitigate, as part of your deployment script? 

Yes

**Comment by geropl** [comment]
Got deployed this morning.

**Comment by kylos101** [comment]
Awesome, thank you, @geropl !

CC: @sagor999
