### ISSUE TITLE
Cannot connect to solana devnet/testnet

### ISSUE THREAD

**Issue by blockchainlover2019** [gitpod-io/gitpod#7830]
### Bug description

Hi. I am a solana blockchain engineer who is keen on gitpod. I have some mates and they also develop on gitpod.
But from a few days ago(I can't expect, but 2 or 3 days ago), I can't deploy smart contract to Solana Devnet from gitpod ubuntu.(In my computer it works well. And It worked very well on gitpod before.)
![image](https://user-images.githubusercontent.com/92380384/151094297-5e15ceba-f0a1-4493-bf1c-26f01f2996ef.png)
So solana engineers(my mates) couldn't use gitpod and they left from gitpod to local vs code.
But anyhow I love gitpod.

### Steps to reproduce

--- solana install ---
sh -c "$(curl -sSfL https://release.solana.com/v1.8.6/install)"
export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH"
solana-keygen new -f
solana config set --url devnet
solana airdrop 2
solana airdrop 2
solana airdrop 2
solana deploy first.so

### Anything else?

[first.zip](https://github.com/gitpod-io/gitpod/files/7938590/first.zip)

**Comment by cryptoman0702** [comment]
same issue for me

**Comment by axonasif** [comment]
There are some ongoing incidents, please hold on a bit.

**Comment by blockchainlover2019** [comment]
It still doesn't work.
![image](https://user-images.githubusercontent.com/92380384/151185769-7775c17a-f9af-4a60-bd28-fe17924f1ab6.png)

**Comment by BlockchainCrazy95** [comment]
Same issue for me now. have trouble with deploying to solana devnet, testnet, mainnet.

**Comment by SuperBlockchainMan** [comment]
Thanks for your posting, @blockchainlover2019.
I also have same issue. Any solution?

**Comment by csweichel** [comment]
Is the data you aim to send sent using TCP or UDP?

**Comment by blockchainlover2019** [comment]
Not sure about that.
But It worked very well before. But recently it doesn't work.

**Comment by blockchainlover2019** [comment]
Thank you gitpodders. You don't need to worry about this issue. We moved to other tool.
We were fascinated by gitpod but we couldn't use it anymore. Anyhow thank you for your effort.

**Comment by pyr0gan** [comment]
Users of the [Figment Learn Solana pathway](https://learn.figment.io/protocols/solana) have been impacted by this bug. We have been using Gitpod with great success - A resolution or workaround to this issue would be greatly appreciated! 😄

**Comment by pawlean** [comment]
@pyr0gan Thanks for the tag! Looping in my colleague @kylos101 who may know more about this issue. Thanks!

**Comment by kylos101** [comment]
Hi @pyr0gan :wave: ,

I was reading through [the linked PR](https://github.com/figment-networks/learn-web3-dapp/pull/240#issue-1122558497), and I rather like this thought `...users to deploy to a test validator running inside of Gitpod instead of the devnet cluster`. 

Have you considered using [tasks](https://www.gitpod.io/docs/config-start-tasks#start-tasks), to automate the configuration and starting of test validators within your Gitpod workspace? I'd be happy to share a PR, there are a couple benefits to using tasks. Things services start predictably, and automatically when the Gitpod workspace opens. Plus, you'll be able to remove the deploy contract documentation about local setup (because it'll be scripted in the .gitpod.yml file), which'll save users time so they can get coding faster.  Let me know if you'd be willing to accept a PR using tasks?

Let me share why I like tasks. [I was recently working a project](https://github.com/gitpod-io/workspace-images/blob/master/.gitpod.yml#L9-L26), where I deployed a local `buildkitd` and `docker registry` in a Gitpod Workspace. This helped me to develop and test new images for Gitpod faster, without leaving my Gitpod workspace or having to rely on a remote image registry. Anyone looking to contribute to the repo I shared will have the same experience I did (for building and testing the related project).

Regarding your devnet cluster, if tasks aren't enough, and you need to connect, a workaround may be for you to try connecting to it using [Tailscale](https://www.gitpod.io/blog/tailscale). Is that something you'd be willing to try?

**Comment by pyr0gan** [comment]
Hey @kylos101 👋 ,

> Have you considered using [tasks](https://www.gitpod.io/docs/config-start-tasks#start-tasks), to automate the configuration and starting of test validators within your Gitpod workspace?

It's not a bad idea, though the way it was working before where users were interacting directly with Solana's devnet was good. We were trying to reduce complexity for the sake of new learners. More experienced developers would likely be able to figure out the issue and work around it without our help.

My only real issue with making test validators a part of the tutorial is that it increases complexity and requires users to have yet another running process in a terminal - as I said, we have been trying to reduce complexity where possible.

Tailscale looks interesting. I'll need to discuss it with the team to see if we want to implement this. Personally, I think asking users to manually rn a test validator is one of the least complex options and fits the learning curve for using Solana anyway - whereas additional tech outside the Web 3 stack is .. a bit of a sticky wicket 😁 

Thanks for your response! I'm still intensely curious as to the technical reason for the breakage, too. 🤔

**Comment by kylos101** [comment]
Hey @pyr0gan I believe I found the network requirements for devnet, [here](https://docs.solana.com/running-validator/validator-reqs#networking) and [here](https://docs.solana.com/cluster/bench-tps#developer-testnet), and am scheduling an issue to fix this for you. Just wanted to give you a heads up! Have a good one.

**Comment by pyr0gan** [comment]
> Hey @pyr0gan I believe I found the network requirements for devnet, [here](https://docs.solana.com/running-validator/validator-reqs#networking) and [here](https://docs.solana.com/cluster/bench-tps#developer-testnet), and am scheduling an issue to fix this for you. Just wanted to give you a heads up! Have a good one.

Magnificent! Thank you!

**Comment by sagor999** [comment]
@blockchainlover2019 @pyr0gan can you try again and let me know if connectivity is now restored for you?

**Comment by kylos101** [comment]
> @blockchainlover2019 @pyr0gan can you try again and let me know if connectivity is now restored for you?

:wave:  @BlockchainCrazy95 @pyr0gan hi there, just checking in, is it better now?

**Comment by pyr0gan** [comment]
@kylos101 @sagor999 It does appear to be, yes 😄  I was able to deploy a program to Solana devnet as before! Thanks so much 🚀
