### ISSUE TITLE
gitpod.yaml is not working

### ISSUE THREAD

**Issue by kdileepreddy** [gitpod-io/gitpod#7844]
### Bug description

I have to install angular cli every time. so i thought of keeping command in gitpod.yaml, but commands in gitpod.yaml are not working. please check my gitpod.yaml

tasks:
  -init: npm i -g @angular/cli 
  command: > ng serve --host 0.0.0.0 --disable-host-check && gp await-port 4200 && gp preview $(gp url 4200)
ports:
  - port: 4200
    onOpen: open-browser      

My repo: kdileepreddy-interviewpr-9luobcvihr8.ws-us29.gitpod.io

### Steps to reproduce

gitpod.yaml is not working
tasks:
  -init: npm i -g @angular/cli 
  command: > ng serve --host 0.0.0.0 --disable-host-check && gp await-port 4200 && gp preview $(gp url 4200)
ports:
  - port: 4200
    onOpen: open-browser

**Comment by axonasif** [comment]
@kdileepreddy You have to use `before:` instead of `init:` for that `npm -i -g` command.
To learn why, please see: https://www.gitpod.io/docs/prebuilds#workspace-directory-only

Other than that, it is a good practice to use custom dockerfiles for installing tools like these, that way your workspace starts even faster. See https://www.gitpod.io/docs/config-docker
