### ISSUE TITLE
Feedback Issue: Project-level environment variables

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#7860]
## Objective

This issue is to track feedback related to project-level environment variables.

**Comment by zpthree** [comment]
Are project environment variables not accessible in the same way that regular environment variables are? I set up a bunch of project environment variables and made them visible in workspaces but they are not showing up with my other variables.

**Comment by TamaMcGlinn** [comment]
The [documentation](https://www.gitpod.io/docs/environment-variables#project-specific-environment-variables) for this is pretty short. I imagine it's probably possible to add something like:

```
env:
    - PATH: /workspace/something
```

to the .gitpod.yml file to set environment variables across the whole gitpod workspace (so that even the language server running inside VSCode will see it), but without an example in the documentation I can't be sure.
