### ISSUE TITLE
Epic: Licencing UI for self-hosted

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7862]
## Summary

The licencing for self-hosted users does not meet the expectations currently advertised on the [self-hosted landing page](https://www.gitpod.io/self-hosted)

This epic is to make the licencing match what is advertised

## Context

We offer three licencing models for users:
- community, always free. Does **NOT** have prebuilds, snapshots or shared workspaces
- free. Free for first 10 users, Has prebuilds, snapshots and shared workspaces
- professional. As per "free", but paid from the 11th user

How the application actually works:
- Free for first 10 users. Prebuilds, snapshots and shared workspaces work (this is my assumption as `<domain>/#prebuild/<repo>` runs the rebuild functionality)
- Can add a licence via the Installer config. This licence is generated manually after an email request
- As far as can be seen, no difference between free and paid versions
- If number of seats is exceeded, the UI is very poor and only indication is in the error URL (see [loom](https://www.loom.com/share/a94d6d069b3047b5a93640837c2331a7))

## Questions for Product Manager

- How do we differentiate between community and free if you have <= 10 users?
- Does there need to be a difference?
- If no difference, how do we communicate that when the 11th user signs up, they will lose prebuilds etc? From a support side, we need to be careful we're not inundated with "my prebuilds have stopped working" requests due to the 11th user signing up.
- Do we need to advise people to use block lists to avoid exceeding their free allocation? See #6372

## Acceptance Criteria

- What is advertised must match what is delivered.
- There should be a nicer way of telling users 

## In Scope

- [ ] Offer additional users for those who send telemetry data
- [ ] Automated license purchasing

## CC

This requires co-ordination across teams. Will likely require input from @jldec @gtsiolis @geropl as well as @gitpod-io/engineering-self-hosted

**Comment by webermax** [comment]
I agree; `Community` -> `Registered` -> `Paid` could be another variant.

Furthermore, the functionality is not as announced on the landing page using a fresh installed gitpod instance:

1) Minutes countdown per user (probably inconsequential)

2) Workspace sharing fails with license hint

3) No admin Dashboard (e.g. no global workspace management; at least misleading)

At the moment it's not clear how to "upgrade" from "Community" to "Free".

Last but not least the button under the "Free" plan should just write "Register" whereas "Professional" would not need any button at all.

**Comment by metcalfc** [comment]
Some of this was also discussed in https://github.com/gitpod-io/gitpod/issues/5690. We should allow folks to opt out of the free tier and start with and stay on community. We'd love for everyone to land, see how awesome Gitpod is and stay forever (including paying one day). But if they know from the go that they'll just use community check this box in the admin dashboard and we can disable it. 

After that Free (10) or Free with a registration  (20) does turn off on the Nth user. We can warn them at X%. Some folks will get annoyed by continuous warnings. So it should be dismissible. After its triggered we can show a header that they're over and that's why things have changed. They can disable the free tier in the admin dashboard. When they disable free tier that warning can go away.

For the Free (10) tier we can point out that they can register with their company name and get a license for 20 to extend their tier.

@atduarte naming is beyond the scope for a GitHub issue. Lots of stakeholders there that don't watch here.

**Comment by gtsiolis** [comment]
Added this to [product design inbox](https://github.com/orgs/gitpod-io/projects/29) for keeping an eye on ongoing discussions.

**Comment by nandajavarma** [comment]
The first iteration of the Licence UI in the admin dashboard is currently WIP. The work done towards this so-far are:
- PR to [Match the licence as advertised for self-hosting](https://github.com/gitpod-io/gitpod/pull/8593) by @MrSimonEmms  - This change is already included in the current release
- PR to [Add the Licence admin UI](https://github.com/gitpod-io/gitpod/issues/8413) is currently WIP. What is left is to implement the design specs made by @gtsiolis

The above two changes meet the acceptance criteria for this Epic. The other things in scope, including option to purchase licence and offering more users for those who send telemetry data, will be done during the next iteration.

**Comment by lucasvaltl** [comment]
This has been merged and released :)
