### ISSUE TITLE
showing You have not yet opened a workspace. 

### ISSUE THREAD

**Issue by sagarkodte** [gitpod-io/gitpod#788]
After starting the workspace from dashboard in code editor showing you have not yet opened a workspace. Could you please tell me what is the issue? I have done lots of work. All is gone?

**Comment by JesterOrNot** [comment]
Can you show me the repository in question

**Comment by jankeromnes** [comment]
See also https://spectrum.chat/gitpod/general/gitpod-fails-to-load~a6589294-26e3-4978-b3ef-ed3bb7ec434d

This seems to be an intermittent problem, because sometimes restarting it works fine. Also, I was able to reproduce the bug this morning, with:

- https://gitpod.io/#https://github.com/jankeromnes/discourse
- workspace `bda0a1b8-254b-46f1-88cc-f691c50f3b2b`

<img width="1552" alt="Screenshot 2019-09-16 at 11 24 41" src="https://user-images.githubusercontent.com/599268/64947583-a3a84d00-d875-11e9-83e3-811e3aaba11f.png">

**Comment by sagarkodte** [comment]
@JesterOrNot Sorry I have  created another one because of this issue

**Comment by svenefftinge** [comment]
Seems to happen when a websocket reconnection is happening while the shell is still preparing.

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/66914686-f3954380-efdc-11e9-9fe1-4c1a1e02905e.png)
It opens

**Comment by jankeromnes** [comment]
@JesterOrNot Many thanks for trying to reproduce this bug! But as Sven mentioned, it only happens when your network is unstable:

> This seems to be an intermittent problem, because sometimes restarting it works fine.

> Seems to happen when a websocket reconnection is happening while the shell is still preparing.
