### ISSUE TITLE
Can't find credentials

### ISSUE THREAD

**Issue by Jmcclain0129** [gitpod-io/gitpod#791]
Having difficulty setting up my first got pod environment. I cloned project from GitHub repo where it works fine. I finally got project running on gitpod but unable to add products to store. I am getting errors relating to credentials and secret keys via bot bot3

My project uses s3 buckets and dj-Db via heroku

Any suggestions

**Comment by JesterOrNot** [comment]
question: do you have push access to the repository?

**Comment by jankeromnes** [comment]
@Jmcclain0129 please type `env` into the Terminal, and compare the results with what the command gives you on your local computer where the project works (but don't paste the results here).

Specifically, does your Gitpod workspace have the required s3 credentials? If not, you may want to use https://gitpod.io/environment-variables/ to define your s3 credentials for all workspaces.

**Comment by svenefftinge** [comment]
> question: do you have push access to the repository?

To your repository? No.
Please comment/reopen if there is still something we should do here.

**Comment by Jmcclain0129** [comment]
Got past that issue only problem now is with single page not showing product images in view

**Comment by jankeromnes** [comment]
@Jmcclain0129 Glad you got past that issue.

> only problem now is with single page not showing product images in view

Maybe your page is using incompatible URLs for the images? You could try to right-click on the page, and choose "Inspect Element", and then inspect the `<img>` sources, or go to the Console to see if there were any errors while loading your images.

In theory, your page should add images with relative URLs like `<img src="./dir/image.png">`, or absolute URLs like `<img src="/some/dir/image.png">`.

In any case, they should _not_ contain domain names or ports like `<img src="http://localhost:3000/some/dir/image.png">`, because that won't work through Gitpod's preview proxy.
