### ISSUE TITLE
Readme link to Integrated Code Reviews is broken

### ISSUE THREAD

**Issue by vfonic** [gitpod-io/gitpod#7911]
### Bug description

Readme link to Integrated Code Reviews is broken

### Steps to reproduce

1. Go to: https://github.com/gitpod-io/gitpod
2. Go to Features: https://github.com/gitpod-io/gitpod#features
3. Click "Integrated code reviews ": https://www.gitpod.io/docs/code-reviews/#code-reviews

**Comment by axonasif** [comment]
I guess it should be: https://www.gitpod.io/docs/context-urls#pullmerge-request-context ?
cc @pawlean

**Comment by dkp1903** [comment]
Hi, @axonasif @vfonic 

I ran into this issue when exploring the Readme for this very requirement. Have created [a PR](https://github.com/gitpod-io/gitpod/pull/7913) using the updated URL @axonasif recommended.

Do let me know if this looks good, so that any future users do not get blocked when trying to access this one

**Comment by axonasif** [comment]
Thank you very much @dkp1903 🙏

**Comment by pawlean** [comment]
Great spot @dkp1903! Thanks :)

**Comment by gtsiolis** [comment]
Resolved in https://github.com/gitpod-io/gitpod/pull/7913. Closing! 📕
