### ISSUE TITLE
Investigate if the `JaegerOperator` config is necessary

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7942]
When the Installer was originally build, the JaegerOperator is installed to provide the operator was believed to be necessary for everything to function correctly. Investigate whether this is actually required for successful installation of Gitpod.

This operator does not provide a Jaeger dashboard (nor should it) - this is configurable via the Observability config option as an external deployment only. There is no intention to bring any tracing dashboard into the Gitpod Installer.

See [Slack](https://gitpod.slack.com/archives/C01KLC56NP7/p1643705843170309) for more detail

**Comment by mads-hartmann** [comment]
The [JaegerOperator](https://github.com/jaegertracing/jaeger-operator) simplifies the deployment of Jaeger by following the Operator pattern. It adds CRDs so that if you want to deploy Jaeger you "simply" use their custom resource and the operator will use that to create the relevant k8s resources.

So if we don't have any Jaeger Operator CRDs in our installs it should be safe to remove ☺️
