### ISSUE TITLE
installed plugin not working 

### ISSUE THREAD

**Issue by akiaksdon** [gitpod-io/gitpod#798]
**Describe the bug**

I have installed jave test runner extension but it is not working , it worked only once but when i had restarted my workspace it did not work.

**To Reproduce**

Install test runner extension  , try using the extension 

**Expected behavior**

The installed extension should work properly

**Comment by jankeromnes** [comment]
Hi @akiaksdon, I'm sorry that this happened to you. In order to help us troubleshoot this, could you please share your repository URL (if it's public)?

@svenefftinge @akosyakov I suppose https://github.com/Microsoft/vscode-java-test is meant here. Do we officially support this extension? Should this issue be filed against https://github.com/eclipse-theia/theia?

**Comment by svenefftinge** [comment]
Yes, would make sense to have this ticket in Theia as well. I have used that extension and noticed a couple of other rough edged, i.e. bad rendering of test results and test result icons in the tree were missing. Didn't noticed the reloading issues, though. Someone needs to look into it.

**Comment by jankeromnes** [comment]
Hi @akiaksdon, is this problem still happening or is it fixed now?

If it's still broken, could you please provide more details about the failures if you have time?

There were a few fixed in Gitpod's extension support, see https://github.com/eclipse-theia/theia/issues/6294#issuecomment-560243551

**Comment by jankeromnes** [comment]
I assume this is fixed and the extension works great. 🙂

If not, please re-open an issue and provide as many details as you can, e.g. screenshots, precise descriptions of what exactly doesn't work, etc.

Thanks!
