### ISSUE TITLE
display warning for latest IDE versions on the loading screen

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#8028]
For latest versions like VS Code Insiders and EAP of JB products we should display a warning at all phases of the loading screen and provide an action to switch to restart a workspace with a corresponding stable version of a selected product.

### Designs

| Preparing | Running |
|-|-|
| <img width="1440" alt="Preparing" src="https://user-images.githubusercontent.com/120486/158705245-ee345d3d-1c03-4c20-9997-bc6ae61fb62b.png"> | <img width="1440" alt="Running" src="https://user-images.githubusercontent.com/120486/158705257-04b3bb54-8bac-4c18-a853-b81f69a20875.png"> |

See [design specs](https://www.figma.com/file/3K7TIuko6ADxO0FY941huB/Display-warning-for-latest-IDE-versions-on-the-loading-screen-%238028?node-id=1107%3A764).

**Comment by akosyakov** [comment]
@gtsiolis we will need a design for it.

cc @loujaybee

**Comment by loujaybee** [comment]
In addition to this, I think we need to review our documentation and copy-text to ensure that the expectations are set with users properly. If we have this flag on the workspace loading, I think copy text such as "what does this mean" which links to docs about the insiders and explains how it works / user expectations would also be useful.

**Comment by loujaybee** [comment]
> @gtsiolis we will need a design for it.

@akosyakov - Would be nice if designed, but I wouldn't necessarily wait a design on this one as we could do something simple, draft an approach / PR and tweak based on feedback from @gtsiolis et al.

**Comment by loujaybee** [comment]
Also, this relates to: https://github.com/gitpod-io/gitpod/issues/7026. In future I think we should consider having less stable features more clearly documented, e.g. Chrome Canary is a separate product / download so it's very clear. Or with the JetBrains [EAP](https://www.jetbrains.com/resources/eap/) version marked clearly as EAP.

**Comment by loujaybee** [comment]
Created a companion issue in website docs: https://github.com/gitpod-io/website/issues/1700

**Comment by akosyakov** [comment]
>  It would be nice if designed, but I wouldn't necessarily wait a design on this one as we could do something simple, draft an approach / PR and tweak based on feedback from @gtsiolis et al. 

put in scheduled for IDE team as well

**Comment by gtsiolis** [comment]
**fyi**: I've added the specs in the issue description.

**Comment by filiptronicek** [comment]
@gtsiolis do you think it would make sense to make this user-dismissible or rather to stuff it in every user's face all the time to make sure? 

What about maybe a way for the user to minimize it to just a ⚠️ icon somewhere that would stay there forever, making (upon focus / click) a pop up / tooltip with this exact message possible?

**Comment by gtsiolis** [comment]
> do you think it would make sense to make this user-dismissible or rather to stuff it in every user's face all the time to make sure?

I swayed between making this dismissible. Here're some thoughts on this:
1. It makes sense to not make it dismissible as the goal of this is to make users aware of a user preference that could be breaking the user experience.
2. Making this dismissible _once_ could create an unessasary habbit of users wasting time on dismissing a modal that only exists for a few seconds until the workspace is up and running.
3. Making it dismissible _forerever_ will cancel the goal of this to make users aware of the preference, resulting into users 

> What about maybe a way for the user to minimize it to just ...

This could be interesting and useful long term. also, currently thinking of making this more compact as @mustard-mh is working on this in #8783 since it can grab quite a lot of vertical space. But we can certainly imporve this in the next iteration.

| BEFORE | AFTER (WIP) |
|-|-|
| <img width="1440" alt="Screenshot 2022-03-17 at 11 31 49 PM (2)" src="https://user-images.githubusercontent.com/120486/158898506-2facbd11-0327-4edc-83ff-174fa2c7c604.png"> | <img width="1440" alt="Screenshot 2022-03-17 at 11 33 40 PM (2)" src="https://user-images.githubusercontent.com/120486/158898688-fd647cb9-f746-4fd3-81bd-163b950b86cd.png"> |

Thanks for the feedback, @filiptronicek! 🙏
