### ISSUE TITLE
Swift language support

### ISSUE THREAD

**Issue by ghost** [gitpod-io/gitpod#805]
It would be nice to have things like autocomplete and having swift preinstalled on gitpod

**Comment by svenefftinge** [comment]
There's a bit more that needs to be done, e.g. install swift.
Would be great if someone could write a guide for the documentation.

This seems to be a good starting point: https://github.com/PerfectlySoft/PerfectDocs/blob/master/guide/gettingStarted.md

**Comment by jankeromnes** [comment]
To clarify, what's required here is:

- [ ] Write a Dockerfile based on `FROM gitpod/workspace-full` that installs `swift`, to produce a base image for Gitpod workspaces

- [ ] Find good VS Code extension(s) for Swift, and install them in Gitpod

**Comment by Blurryface05** [comment]
Yea

**Comment by JesterOrNot** [comment]
Hey, can I help make the Dockerfile?

**Comment by jankeromnes** [comment]
@JesterOrNot Yes please! That would be awesome. 💯

I think the first step would be to set up a demo Swift project, with a `.gitpod.yml` that points to a Dockerfile installing Swift, and that also installs the appropriate VS Code extension(s).

I'm happy to help if you have any questions. 😄

**Comment by JesterOrNot** [comment]
Here is the repo so that you can check on it and stuff
https://github.com/JesterOrNot/Gitpod-Swift

**Comment by jankeromnes** [comment]
Thanks for setting up a repo, @JesterOrNot! 😄

I went ahead and ran `gp init` and also installed Swift in the Dockerfile: https://github.com/JesterOrNot/Gitpod-Swift/pull/1

**Comment by JesterOrNot** [comment]
Nice! Now I'll get the stuff for the lang server together if you look in sources.txt I have some extensions that I found

**Comment by JesterOrNot** [comment]
alright, I just got an error Activating extension Maintained Swift Development Environment failed: Cannot read property 'replace' of undefined.

**Comment by jankeromnes** [comment]
@JesterOrNot So cool! Many thanks for the great work on this. 🙏 Is there any good Swift sample project I can use to test the language support?

**Comment by JesterOrNot** [comment]
https://github.com/groue/GRDB.swift seems pretty cool!

**Comment by JesterOrNot** [comment]
Were you able to test the lang server?

**Comment by svenefftinge** [comment]
I tried https://github.com/svenefftinge/Kitura-Sample but there is an issues with the vscode extension. https://github.com/eclipse-theia/theia/issues/6329

**Comment by JesterOrNot** [comment]
I sent a PR try it again

**Comment by JesterOrNot** [comment]
What now do we PR?

**Comment by jankeromnes** [comment]
@JesterOrNot Your repo seems to work well! I tried cloning https://github.com/groue/GRDB.swift and https://github.com/svenefftinge/Kitura-Sample into it, and played with various Swift files.

I didn't know how to compile the Swift projects though (I've never worked with Swift before). Basic syntax highlighting seemed to work, as well as `Go to Definition` (at least within the same file), but I wasn't able to `Rename Symbol`. Also, a few external symbols didn't seem to be recognized by the language server (maybe some extra configuration is needed, or dependencies should be installed).

In any case, I think the next steps would be to make a PR adding this Gitpod set-up to a "real" Swift project, e.g. GRDB.swift or Kitura-Sample. That way it becomes easier to test Swift support in Gitpod, because you can directly open real Swift files and (hopefully) build & run the project. That would make a really cool demo, which we could feature in our language docs. 😄

Thanks again for adding so many new languages to Gitpod! 💯 I find it hard to keep up. 😅

**Comment by jankeromnes** [comment]
> In any case, I think the next steps would be to make a PR adding this Gitpod set-up to a "real" Swift project, e.g. GRDB.swift or Kitura-Sample.

Oh, sorry, I totally missed that you already did that: https://github.com/svenefftinge/Kitura-Sample/pull/1 Thanks a lot!

@svenefftinge please take a look at the pull request when you have time. 🙂

**Comment by JesterOrNot** [comment]
https://github.com/JesterOrNot/Gitpod-Swift/pull/4
Take a look at the dockerfile

**Comment by gengjiawen** [comment]
brew now has swift support. `brew install swift` but it now fails on gitpod, not sure why.
