### ISSUE TITLE
[Admin] Search for team by name or slug and show team details

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8060]
From discussion[[1](https://www.notion.so/gitpod/WebApp-Notes-Admin-for-Teams-Laurie-J-rgen-Feb-10-2022-f75d2e6f886a44ceb23bc57c419ab28c)](internal):

Search for teams
- by name
- by slug (helpful for team names with funny characters)

- Results - order by created desc
    - [x] Name + team URL (/t/slug) underneath
    - [x] Created date (order by desc) show arrow in heading
    - [x] Indicate deleted (nice to have in admin lists) 
- [x] Click on any result (entire row is clickable) to go to team detail

Team detail
- [x] Team name + team URL at the top
- Other fields:
    - [x] created date (either friendly with actual date/time on hover, or actual date/time)
    - [x] marked deleted
    - [x] member count
    
- Member list 
  - [x] (Not required for deleted teams)
  - [x] List columns: Member, Joined, Role
  - [x] Paginated would be nice OR ok to limit list + Search for now
  - [x] Click to link to user detail
  - [x] Nice to have actions: change role (useful for support to assign new owner)

Future
- More actions
  - Rename (should be possible for non-admin users as well - complexity with slug rename)
  - Delete 
  - Invite URL (@laushinka moved this from nice-to-have to a future task)
- Project list
  - toggled with member list using tab-like component

**Comment by jldec** [comment]
@gtsiolis
Please see MVC spec for new team admin pages above.
Happy to take addditional suggestions from you if you have.

**Comment by gtsiolis** [comment]
While working this, I'm taking a stab at re-ordering some of the navigation structure in favor of some upcoming dashboard navigation changes in https://github.com/gitpod-io/gitpod/issues/8385 in case these could be part of this issue. However, going with the existing layout pattern should suffice. Will post some designs specs later today. Cc @laushinka @jldec

**Comment by gtsiolis** [comment]
Posting below some specs that reuse existing patterns from the admin dashboard. Future iterations will probably re-order some of the navigation elements, see #8385.

| Teams List | Team Details | Team Details (Deleted) |
|-|-|-|
| <img width="1440" alt="Teams (List)" src="https://user-images.githubusercontent.com/120486/155149862-3f100a91-9659-4ceb-a1c8-c64c4af1e42a.png"> | <img width="1440" alt="Team (Details)" src="https://user-images.githubusercontent.com/120486/155149874-809485c6-2bff-4c3a-b699-9618d2012f46.png"> | <img width="1440" alt="Team (Details)-1" src="https://user-images.githubusercontent.com/120486/155149886-812344fb-7230-4b4c-acc1-b642b2d207f1.png"> |

See [design specs](https://www.figma.com/file/qxvM2S0gu2L3uVM2UfsjhM/Search-for-team-by-name-or-slug-and-show-team-details-%238060?node-id=0%3A1).

**Comment by laushinka** [comment]
> Posting below

@gtsiolis Thank you! I was a bit uninspired when thinking of what the team details should look like, and this looks good. Are the possible actions for each team member the same as the current actions? i.e. `Leave Team` or `Remove`

**Comment by gtsiolis** [comment]
@laushinka Yes, I swinged between re-using the existing tabular pattern of the project detail page but also tabs to separate overview, members, and projects. However, I think going with a (simple) _boring solution_ here like the proposal in https://github.com/gitpod-io/gitpod/issues/8060#issuecomment-1047839340 sounds good for the first iteration.

Things to consider dropping:
1. The more actions on members (Leave team, etc)
2. The invite team members button
3. The search button from the search form. Long-term we will most probably build an overview dashboard page that links to all sub-entities including listing recently added entries by default instead of having empty pages like we have now for users, projects, teams, etc.

To answer your question, I'd drop the members actions. Cc @jldec 

Things to consider adding:
1. Option to delete a team, see relevant screenshot from the users in admin below.

<img width="777" alt="Screenshot 2022-02-22 at 4 43 28 PM" src="https://user-images.githubusercontent.com/120486/155155520-d8d90dfa-903c-42fc-a1c1-d1ef1ab4427b.png">

**Comment by laushinka** [comment]
@gtsiolis @jldec Feel free to play around in the draft PR to get early thoughts 🙏🏽

**Comment by laushinka** [comment]
@jldec @gtsiolis 
1. I will be removing the `Owner/Member` dropdown, since we won't be allowing role changes right now. 
2. I see there is a design view for the deleted team detail. However when a team is deleted, we also don't see any members because they will have been deleted as well.

**Comment by jldec** [comment]
Looks good thanks @laushinka - adjusted description with additional tasks.
