### ISSUE TITLE
Add deployment metadata/labels to PRs

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#8127]
## Is your feature request related to a problem? Please describe
When we release new gen of workspace clusters and shift traffic to that. Do our customers actually know about it?
Do they know what is fixed?
We mark issues as resolved/merged in github, but I think from customer standpoint it might not be clear when those fixes are actually pushed out.
Do we want to introduce special label on PR/Issues that would indicate in which generation it was fixed? And educate customers which gen their workspace is running in?

Several more cases that maybe we should handle:
We deploy a new cluster and begin to shift traffic to it
We deploy a new cluster, and shift traffic to it right away (global outage)
We patch an existing cluster

## Describe the behaviour you'd like

I think it would be good to have milestones, or labels, that when we mark an issue as fixed or PR merged, that we can apply label\milestone to it identifying to users when to expect that to be available in SaaS.

Alternatively, we can also create a separate issue for issue generation of workspace clusters, and then link any issue\PR to it. And then we that generation is deployed -> we update it and close it. That way it will be easy for users to know when their issue is actually fixed in production.
(Personally I like issue per generation and linking fixed issues to it)

## Describe alternatives you've considered

We could also use this as part of post deployment step:
https://github.com/gitpod-io/gitbot/tree/main/plugins/deployed-labeler
But it would apply labels retroactively which might not be that obvious and visible to users.

**Comment by ArthurSens** [comment]
https://github.com/gitpod-io/gitbot/tree/main/plugins/deployed-labeler belongs to us, so I believe we could also extend it apply to a single commit instead of a batch 🙂

**Comment by atduarte** [comment]
Two actions were discussed during the goals & results brainstorming that relate to this:
1. Adding labels/metadata to all PRs
2. Creating a public changelog for each workspace cluster generation.

This issue description seems focused on the first action. Should we rename and create a second one for the 2nd action, @sagor999?

**Comment by sagor999** [comment]
@atduarte yeah, that sounds like a good idea.

**Comment by kylos101** [comment]
@sagor999 this is a great issue, thank you for creating it!

We package the [changelog](https://github.com/gitpod-io/gitpod/blob/main/CHANGELOG.md) now as a [docker container](https://github.com/gitpod-io/gitpod/blob/1c0c677313692945976566d0d042e4f033889de2/dev/changelog/leeway.Dockerfile).

We could serve it from a workspace, and link to it from via a new IDE option. i.e. **Gitpod: Changelog**. Another option is via a sub item in the Help menu. WDYT @atduarte ?

Considerations:
- Some of our changes (even though they could be public) are in the Ops repo, which is private. 
- As a potential solve, we could manage the public cluster changelog as a MD file in the Gitpod mono repo - instead of a Notion page.
- Notion would only be used for private content. 

Why? This way the public changelog is "up-to-date" with every Gitpod change and accessible from within a workspace - easy. It would reference issues, and they would reference PRs used to manage a MD file which represents the "workspace" cluster changelog.

WDYT? @sagor999 @atduarte

**Comment by sagor999** [comment]
I like that idea. 
Bonus point if inside IDE\dashboard "what's new\changelog" can be highlighted when there are new changes in it.

**Comment by kylos101** [comment]
@aledbf what do you think of using a MD file, rather than Notion, to manage a public changelog for workspace clusters? I should have copied you on this earlier. D'oh!

**Comment by kylos101** [comment]
@aledbf ignore this. We'll create a new issue for changelog.

@sagor999 we are going to fix the deployment label here, https://github.com/gitpod-io/ops/issues/1667, so that when we deploy workspace clusters, we must opt into adding the deployment label. Right now, we add it when we deploy ephemeral clusters, which is misleading, I think. Separate from the above label issue, I think we should create a new one to improve/consider how we add content to the changelog for workspace clusters.

@atduarte I am going to close this, can you start a new issue? I ask because you met with Mike recently to socialize the changelog and workspace contributions.
