### ISSUE TITLE
Settings page on mobile layout

### ISSUE THREAD

**Issue by krystxf** [gitpod-io/gitpod#8133]
It would be nice to have a responsive settings page. Probably with some sort of drop down menu instead of the side menu on mobile. I'm willing to help with the styling, but I need some suggestions to get it the way you'd like.

**Comment by pawlean** [comment]
Thanks for your feedback, @krystofex! I'm looping in @gtsiolis for information. 😊

**Comment by jldec** [comment]
Moved to investigating/visual-design

**Comment by gtsiolis** [comment]
Thanks for opening this, @krystofex! This is related to the responsive layout of the dashboard in general, see also https://github.com/gitpod-io/gitpod/issues/4050.

Thanks for the ping @pawlean! 🏓

**Comment by gtsiolis** [comment]
Regarding settings layout specifically, let me cross-post below an early design from a [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BUNS/p1625656466130800?thread_ts=1625644808.128800&cid=C01KGM9BUNS) (internal).

Cross-posting also a [relevant doc](https://www.notion.so/gitpod/Mobile-friendly-Gitpod-a383083509754d77a355d769dd699975#3ce5bf63a4ae418981af58b23daa9717) (internal) from @jankeromnes.

<img width="1137" alt="Screenshot 2021-07-07 at 2 12 47 PM" src="https://user-images.githubusercontent.com/120486/153859779-a81f52ec-bfaa-4b42-af2c-b2e19aad1627.png">

**Comment by jankeromnes** [comment]
Awesome, many thanks for getting the ball rolling and offering to help here @krystofex! ♥️🚀📱

And thanks @gtsiolis for re-surfacing the initial designs!

I like many of their aspects.
- For the top-right menu, I guess `Admin`, `Docs` and `Help` could indeed get folded into the Avatar drop-down menu
- For the Settings menu (and other similar sub-menus), I'm not a big fan of the big drop-down selector. We used to have this on https://www.gitpod.io/docs/ and it felt a bit awkward/unfinished (now they have a nice "Go back to all topics" link / all topics page)
- For the top-left menu, I'm not sure whether grouping into a drop-down makes sense, especially with our new "personal/team account selector with tabs beneath" UI

In any case, I do think maybe the top-left and top-right menus are out of scope here, since the issue specifically mentions the Settings menu. Focusing on these sub-menus first makes sense.

I wonder how other apps with outstanding mobile UI have solved this problem.
