### ISSUE TITLE
old version of yarn

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/gitpod#816]
Yarn version is out of date for images.

Is it possible to start with the latest version installed?
![image](https://user-images.githubusercontent.com/38714187/65840963-b2086580-e359-11e9-9fa7-79ceea841e1c.png)

**Comment by jankeromnes** [comment]
Hi @mouse484, good catch! Thank you for filing this issue.

I think there are several ways to get a more recent Yarn version:
- Add the suggested command (`curl --compressed -o- -L https://yarnpkg.com/install.sh | bash`) to your project's `.gitpod.yml`'s init tasks, or to your `.gitpod.Dockerfile`
- Or, use this alternative command: `npm upgrade --global yarn`
- Or, fix Gitpod's [default Dockerfile](https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile) so that it installs a more recent Yarn by default

Regarding the last point, I'm not sure why it doesn't do it currently. I'll try to upgrade various versions in the default Dockerfile and see if that updates Yarn as well.

**Comment by jankeromnes** [comment]
Maybe this pull request may fix it: https://github.com/gitpod-io/workspace-images/pull/117 (we install Yarn with `npm install -g yarn` just after installing Node.js)
