### ISSUE TITLE
Error: cannot start a workspace because no workspace clusters are available

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#8173]
### Bug description

This issue seems to be quite frequent, the error message `Error: cannot start a workspace because no workspace clusters are available` is probably seen after being stuck in `Allocating Resources` for a while.

Users who reported to be facing this issue:

- @shaal [on Discord](https://discord.com/channels/816244985187008514/816246578594840586/939715845934968864), workspace-id: `shaal-drupalpod-x8u7hhb95tu`
- @megatank58 [on Discord](https://discord.com/channels/816244985187008514/816246578594840586/939722222795366430), workspace-id: `megatank58-website2-o050xdvntnt`
- @CarterQC [on Discord](https://discord.com/channels/816244985187008514/816246578594840586/941823668009459752), workspace-id: `awaiting-reply`
- @Dogkiller87 [on Discord](https://discord.com/channels/816244985187008514/941982753044443176/941983116464119869), workspace-id: `4geeksacademy-htmlhello-pzttg3zw2pi`
- More will be added here when found....

Usually, the error goes away by itself upon trying to launch a new workspace.

Internal discussion on Slack[^1]
cc @kylos101 

[^1]: https://gitpod.slack.com/archives/C02F19UUW6S/p1644118483199979

**Comment by kylos101** [comment]
Hey @axonasif thank you! Each of these instances lines up very close to occurrences of high event loop lag with our Server component. I wonder if there is a correlation. For example, when the Server event loop lag is high, it is possible there is trouble routing the user to a workspace clsuter. 

I am going to include our WebApp team, so that they can help investigate. @JanKoehnlein and @jldec for awareness.

Related pager duty events:
* [Feb 6th @ 3:20am UTC](https://gitpod.pagerduty.com/incidents/Q2KIM5TKEAESWO?utm_source=slack&utm_campaign=channel) - relates to **shaal** and **megatank58** in the US region
* [Feb 11th @ 10:48pm UTC](https://gitpod.pagerduty.com/incidents/Q26849NNEQ4GS9?utm_source=slack&utm_campaign=channel) - relates to **CarterQC** in the US region

**Comment by mikenikles** [comment]
This has been happening again for the last 60 minutes.

**Comment by kylos101** [comment]
> This has been happening again for the last 60 minutes.

Thanks, @mikenikles, [that lines up with another occurrence of server event loop lag](https://gitpod.slack.com/archives/C01TNS8EVQT/p1644722849010879?thread_ts=1644722525.383919&cid=C01TNS8EVQT). 

I've added this to the WebApp inbox, and am certain @JanKoehnlein and @jldec will consider for scheduling & triage. If you notice this behavior again, and there's no alert, I recommend `/pd trigger` within Slack, [it'll trigger the on-call person](https://www.notion.so/gitpod/Incident-cheatsheet-eea595a065d946a3aec5f9fefeea5154).

**Comment by csweichel** [comment]
We will want to add counter vec metric which counts how many workspaces we route to a cluster, and how often we fail to find a cluster. Alerting on the latter would be sensible.

**Comment by princerachit** [comment]
I am closing this issue in favour of https://github.com/gitpod-io/gitpod/issues/8173 as in both the cases user saw the same issue of Allocating resources and the status in the db for the ws was `Error: cannot start a workspace because no workspace clusters are available`
