### ISSUE TITLE
New controller: node-backup-watcher

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#8205]
## Is your feature request related to a problem? Please describe
This is required by this: #8202 
When node goes away, we need to make sure that all backups were completed on that disk.

## Describe the behaviour you'd like

This controller would use gcloud to list all disks in the project and would filter them by the label of the cluster.
Once it finds a disk that is no longer attached to the VM, it would:
1. Add label to the disk (`backup-recovery=true`)
2. Attach that disk to the VM on which controller runs.
3. Scan the disk for workspaces and backup if there are any left.
4. Detach and delete the disk when done.

Controller would run on its own dedicated VM in a separate node pool and would perform backup (similar to ws-daemon).

**Comment by csweichel** [comment]
Since we're incurring a GCP dependency anyways, maybe we could simplify the process of accessing the disk. There are a lot of things that can fail in steps 2 - 4. For example, we could have the node-backup-watcher run on dedicated nodes and attach the disks directly to those nodes (i.e. outside of Kubernetes).

**Comment by csweichel** [comment]
Also, we'll want to tie that process into the workspace status somehow. I.e. ideally we can maintain the same interface towards the application cluster in the regular backup and recovery case.

**Comment by aledbf** [comment]
Why not just use of https://github.com/kubernetes-csi/external-snapshotter?
- decouples backup/restore from Gitpod
- improve ws-daemon memory?
- remove object storage from Gitpod (performance?)
- Native cloud snapshot

ws-daemon creates the snapshot object instead of handling the tar/untar and gcs operations, removing one of the sources of state and huge memory utilization.

**Comment by sagor999** [comment]
@aledbf using PVC is expensive and adds about 20 second delay to pod start up due to the time it takes to attach that PVC to the node on which pod is scheduled to run. Plus there would be some additional delay added for how long it takes for gcp to restore snapshot and create a disk out of it (I assume it is fast, but it will probably still add 5+ seconds)

**Comment by sagor999** [comment]
>Since we're incurring a GCP dependency anyways, maybe we could simplify the process of accessing the disk. There are a lot of things that can fail in steps 2 - 4. For example, we could have the node-backup-watcher run on dedicated nodes and attach the disks directly to those nodes (i.e. outside of Kubernetes).

@csweichel Yes, I was thinking of using labels on disk to maintain the state of backup, so that if one of the steps fail, we can easily retry on next run. 
Idea of running this on a dedicated node pool is great!

**Comment by sagor999** [comment]
https://github.com/gitpod-io/gitpod/issues/8202#issuecomment-1051066250
