### ISSUE TITLE
Enabling . keybind to open repositories when using the browser extension does not work for logged in users on GitLab

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#8242]
### Bug description

In https://github.com/gitpod-io/browser-extension/pull/54, we've added the ability to enable the `.` keybind  to open repositories in Gitpod. However, this seems to not work as expected for logged in users on GitLab.

See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1644837995228049) (internal). Cc @filiptronicek @felladrin @akosyakov @loujaybee 

### Steps to reproduce

1. Install the latest browser extension version, see [relevant docs](https://www.gitpod.io/docs/browser-extension).
2. Enable `.` keybind to open repositories in Gitpod from the extension options (Chrome) or prefefences (Firefox).
3. Go to a GitLab instance, including [GitLab.com](https://gitlab.com/).
4. Log in and try pressing `.` on any valid context URL (repository, branch, etc)

**Comment by filiptronicek** [comment]
Thanks @gtsiolis for taking the time to take feedback and raise this issue ✨! I tried reproducing this, and couldn't. I double checked I'm on 1.13 and not running from sources.

I recorded a loom with me being logged in and the key bind working just fine, with the same being when not logged in: https://www.loom.com/share/084aa3735072447d9748f332c75b3904

I am rather puzzled as to how it could be the case that this bug is dependent on the auth status, because we simply unbind the `Period` key bind and rebind it to our thing, but I guess there could be two causes:
1. The state of the webpage is somehow treated differently when authed (i.e. our rebinding code does not execute for some odd reason)
2. A different library / code is used for key binds for authenticated users, which I find pretty unlikely, but who knows. I developed the GitLab functionality when authenticated as far as I remember, no issues.
