### ISSUE TITLE
Workspace with phase "Timed out" refresh didn't restart

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#8246]
### Bug description

Workspace with phase "Timed out" refresh didn't restart. But with devTools Network, you can see that server has updated instance status with "running". And after refresh URL looks weird
https://gitpod.io/start/?not_found=true#gitpodio-ops-2v9ggs50f5l
https://gitpod.io/start/?not_found=true#gitpodio-ops-mpri4nsjyng

Click `Open Workspace` works

<img width="606" alt="image" src="https://user-images.githubusercontent.com/20944364/154279321-225470be-ec0c-44a8-a773-68ee1e238cca.png">

|instance update|get workspace|
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/20944364/154278543-504e8ed3-dfcb-4502-9d61-bb99235819b2.png)| ![image](https://user-images.githubusercontent.com/20944364/154279053-52f793b5-d195-4c1c-ab19-ef5e5a856864.png) |

| Before refresh | After Refresh |
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/20944364/154279766-f3999e2b-4153-4e92-9052-bc93b1ac1dc2.png)| ![image](https://user-images.githubusercontent.com/20944364/154279733-5003f972-046c-4429-8b0b-5fcff5267e8b.png)|

### Steps to reproduce

1. Make workspace timeout
2. Refresh

### Anything else?

May be related to this PR? https://github.com/gitpod-io/gitpod/pull/8125

**Comment by jankeromnes** [comment]
> May be related to this PR? https://github.com/gitpod-io/gitpod/pull/8125

Yes 🎯 the new behavior was made like this on purpose:
- Before, we could have an infinite-redirect loop (e.g. on workspace fast crash) between `/start/` and the IDE URL, causing a sort of Denial-Of-Service attack against ourselves
- The new behavior no longer has this infinite-redirect problem (even on workspace fast crash), because it requires an explicit click on `Open Workspace` to actually restart the workspace

Our assumption was that, from a user experience perspective, it's okay to require an explicit click on `Open Workspace` before actually restarting the workspace on such a "stopped" (or "timed out") page. For example, in some cases maybe you didn't even want to restart the workspace (e.g. if you have several older stopped workspaces in your browser tabs, and you quickly cycle through your browser tabs, this might actually refresh and restart them all by accident).

Also, thanks a lot for your feedback. 🙏 Now we know for sure that some users actually relied on the old refresh-restart behavior.

**Comment by kylos101** [comment]
@jmls this is what we were just talking about

**Comment by geropl** [comment]
There there are multiple issues mixed in here:
 1. Refresh does not restart/re-open IDE: As @jankeromnes mentioned: the fact that we treat an instable state as instable is a feature, not a bug :upside_down_face: 
 2. A re-started workspace page does still show "Timed Out" instead of "Running": that sounds like a bug, but I cannot reproduce it anymore :thinking: 
 3. The fact that supervisor/index.ts does not auto-reveal the IDE for a re-started workspaces when the state changes back to Running: This is what I wanted to get at with #8226. :100: 

IMO we should think about closing this issue, and re-creating more specific ones.

**Comment by iurjoh** [comment]
I am having this issue right now. How I can solve this?

**Comment by axonasif** [comment]
Hi @iurjoh, is this still happening?

**Comment by rainerCH** [comment]
i have this issue aswell since 2 days. how can i provide some informations to solve?

**Comment by axonasif** [comment]
@rainerCH you can send us a message through https://www.gitpod.io/contact/support

**Comment by iurjoh** [comment]
> Hi @iurjoh, is this still happening?

I created a new workspace and leave the problem behind. I could not found any solution for this problem at that time.
