### ISSUE TITLE
Make the licensing match what's advertised

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8328]
On [Gitpod](https://www.gitpod.io/self-hosted), we advertise three self-hosted plans - community, free and professional.

In the [application](https://github.com/gitpod-io/gitpod/blob/main/components/licensor/ee/pkg/licensor/licensor.go#L81), we only provide two plan types - team and enterprise

This ticket is to make the application match what we advertise.

---

There are a few potential things that need to be thought about here

- Any changes need to maintain backwards compatibility with existing customers (including SaaS)
- We should support automatic downgrading to the community license if a user has a free license and the number of users increases from 10 to 11
- I would suggest that the admin dashboard is enabled for all license levels. This will allow us to put useful things in here in future

Linked to #8329

**Comment by jldec** [comment]
cc: @lucasvaltl on the topic of making the Admin dashboard unrestricted for any license or user count.

**Comment by fritterhoff** [comment]
According to the current description on the homepage, the free and professional plans are announced with an unlimited timeout. @MrSimonEmms told me that the actual plans are that both plans will have a timeout of 1h. From my point of view I would not expect this limitation, since the servers/aws-instances are already paid.

![grafik](https://user-images.githubusercontent.com/32478819/156975244-39bf2963-69b6-4339-a580-b36de724cc5c.png)

**Comment by fritterhoff** [comment]
@MrSimonEmms maybe this issue is also relevant: https://github.com/gitpod-io/gitpod/issues/8528
