### ISSUE TITLE
Change "Search workspaces" to "Enter workspace ID" and disable contextURL search.

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#8453]
Workspace ID search returns quite fast, and searches usually do use the workspace IDs. 
Therefore we will only allow workspace ID searches and disable the free text search.

**Comment by laushinka** [comment]
Cc-ing @geropl in case you disagree or have other thoughts 🙏🏽

**Comment by geropl** [comment]
@laushinka Thx for the ping.

> Therefore we will only allow workspace ID searches and disable the free text search.

Thoughts:
 - :100: agree with "disable free text search"
 - we should allow to search for `workspacenId` _and_ `instanceId`
 - either we keep the code that try to guess from the given IDs **or** add a dropdown for the searchtyp (with [workspaceId, instanceId]), which makes it explictily
 - if we choose the dropdown, this is straight forward to extend, e.g. for contextURL (once we indexed that). And can be replicated for the user search (email, accountname, etc.)

**Comment by laushinka** [comment]
> * we should allow to search for `workspacenId` _and_ `instanceId`
Do we know in which cases or how often we search with instanceIds? If we go for now with guessing from the given input, it's very fast for workspaceId but still slow with instanceIds. 

cc @jldec

**Comment by laushinka** [comment]
@gtsiolis I'll probably need your design input for a search dropdown 🙏🏽

**Comment by gtsiolis** [comment]
@laushinka adding this to product design board to take a look later.

**Comment by laushinka** [comment]
@gtsiolis Thanks! And it doesn't have to be a dropdown, something like a search with radio buttons would also work?
<img width="183" alt="Screenshot 2022-02-28 at 17 58 42" src="https://user-images.githubusercontent.com/8015191/156025346-77b969bd-d74a-401a-939b-690a2486981d.png">

**Comment by gtsiolis** [comment]
Breaking down the issue, here're some thoughts:
1. Removing free text search that tries to search across all fields like context, projects, etc sounds good! 💯
2. Keeping search visible and simple[[1](https://www.nngroup.com/articles/search-visible-and-simple/)] is a good UX practice. To this extend, I'd vote for keeping a simple search input instead of adding complexity ahead of search using a dropdown and definitely include a default option if we need the option to do so
3. Introducing more filters later on that can narrow down search as described in https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1050875763 sounds better and definitely worth exploring. For example, in the projects list it could be intersting or useful to search within a team scope, in the workspaces list it could be intersting to search for specific teams using query parameters like `team: gitpod`. This is also common in search engines with key-value search[[2](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/kv-processor.html)][[3](https://solr.apache.org/guide/8_11/the-standard-query-parser.html)] or using regexp[[4](https://www.elastic.co/guide/en/elasticsearch/reference/8.0/regexp-syntax.html)], etc.
4. However, we still haven't figured out the best way to surface context information like this in the workspaces list, see https://github.com/gitpod-io/gitpod/issues/3594. This will be also useful in the new workspace modal improvements in https://github.com/gitpod-io/gitpod/issues/8088 for surfacing context, etc.
5. While the admin dashboard matures as we add more functionality it will become clearer where users can search for what kind of information, like projects, teams, or workspaces.
6. The change in https://github.com/gitpod-io/gitpod/pull/7391 introduced new workspaces names (IDs) that are based of the username and project itself, making it easier to search for project within the workspaces list.
7. Currently the workspaces list includes unnecessary or duplicate information that can be skipped or consolidated in future iterations as we focus on improving the workspaces list now that we also default to `/workspaces` when loading the dashboard.
8. Taking into account https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1050875763, does it make sense to search for an email on the workspaces list and not the users list?
9. Given that teams and projects are growing as the best way to use Gitpod, does it also help to search project names or context URLs when the workspace name (ID) already contains most of this information?

Taking the above into account, changing the backend to search only across workspaces names (IDs) as described in the issue sounds good. However, I agree that the placeholder _Search Workspaces_ sounds a bit abstract and could be misleading but also currently follows the pattern we're using across the product for all search inputs.

What we could also do is either keep the input placeholder as is or improve this by rephrasing the placeholder to be more explicit. For example, using _Search by workspace name_ or simply _Search by name_ sounds like an improvement. What do you think? Cc @laushinka @geropl 


| CURRENT | Option A | Option B |
|-|-|-|
|  <img width="400" alt="search-1" src="https://user-images.githubusercontent.com/120486/156066964-f619f1e8-b6e0-4f7c-a70d-78dbf5179e5f.png"> | <img width="400" alt="search-2" src="https://user-images.githubusercontent.com/120486/156066966-afc5c80c-1579-424d-b59e-84e18333cc3d.png"> | <img width="400" alt="search-3" src="https://user-images.githubusercontent.com/120486/156066967-3849c25a-ca8f-42c3-abb7-ff3f5b430970.png"> |

Sorry for the lengthy comment! 😇

**Comment by laushinka** [comment]
@gtsiolis Thanks for the comprehensive comment! Definitely a lot coming down the road and that's good to know.
Keeping it simple for now works, as long as admins can find the workspace they need quickly. 
I can create a ticket already as a follow-up to improving the workspace (or any) search, so we make sure to schedule it and put ideas there 🙏🏽 cc @jldec 

So the minimum changes here we can make are:
- disabling the free text search
- only allowing workspace and instance ID searches (I was leaning towards only workspace ID searches but from @geropl's comment it seems that instance ID searches are important)
- rephrasing the placeholder. @gtsiolis I'd propose to stay with "ID" instead of "Name", i.e. "Search by Workspace ID or Instance ID"

**Comment by laushinka** [comment]
> 8. Taking into account [Change "Search workspaces" to "Enter workspace ID" and disable contextURL search. #8453 (comment)](https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1050875763), does it make sense to search for an email on the workspaces list and not the users list?

If I understand your question correctly, should we allow searching for emails on the workspaces list? I haven't run into that usecase, but if there is please let me know.

> 9. Given that teams and projects are growing as the best way to use Gitpod, does it also help to search project names or context URLs when the workspace name (ID) already contains most of this information?

This was also a question I had - what admins actually need to search on regarding workspaces. It seems that usually when there are customer issues, we ask for their workspace IDs and contextURL to investigate (Gero and Jürgen can correct me if I'm wrong). Down the road we can allow contextURLs again, but for now workspace IDs should suffice.

**Comment by gtsiolis** [comment]
Regarding https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1055225207:

> If I understand your question correctly, should we allow searching for emails on the workspaces list?

@laushinka I was playing devil's advocate here. I also think this is not a useful or valid use case. 😈 

> This was also a question I had - what admins actually need to search on regarding workspaces.

I think just the workspace name (ID) suffices when it comes to customer support but I could be wrong. Cc @geropl @jldec 

---

Regarding https://github.com/gitpod-io/gitpod/issues/8453#issuecomment-1055211887:

1. To clarify, with workspace ID we're both referring to the workspace name here, right?
2. I'd be in favor of using a less scary term than ID here but I'll leave this up to you to decide. Both options can suffice.
3. Is there a use case where admins search for a **workspace ID** or a **workspace instance ID** in the admin?

**Comment by geropl** [comment]
> I think just the workspace name (ID) suffices when it comes to customer support but I could be wrong

IMO workspaceId is by far the most important one, so fine to take that approach as MVC.
`instanceId`, however, is also used during debugging. But as this is mostly done with DB connection open, the additional lookup in those cases is ok for now.

**Comment by gtsiolis** [comment]
> IMO workspaceId is by far the most important one, so fine to take that approach as MVC.

Thanks, @geropl! Makes sense and probably would solve 90% of the use cases, right?

Later on we could introduce better ways to debug or discover **workspace instance IDs** from the admin dashboard while **browsing workspace IDs**, too.
