### ISSUE TITLE
Multiple version control of docker-related packages

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#8496]
### Bug description

Maybe this issue should be raised [github-io/workspace-image.](https://github.com/gitpod-io/workspace-images), but now we control the versions of runc, docker-compose, and docker versions in workspace-image and gitpod-io/gitpod. For this reason, we don't use the versions which [docker-up/dependencies.sh](https://github.com/gitpod-io/gitpod/blob/main/components/docker-up/dependencies.sh) specify.

https://github.com/gitpod-io/gitpod/blob/4e4386e1213de06b207a2081940814418ed69c2f/components/docker-up/dependencies.sh#L8-L10

### Steps to reproduce

```console
gitpod /workspace/gitpod (to/update-docker-cli) $ runc --version
runc version 1.0.2
commit: v1.0.2-0-g52b36a2
spec: 1.0.2-dev
go: go1.16.10
libseccomp: 2.5.2
gitpod /workspace/gitpod (to/update-docker-cli) $ docker-compose version
Docker Compose version v2.2.2
gitpod /workspace/gitpod (to/update-docker-cli) $ docker version
Client: Docker Engine - Community
 Version:           20.10.12
...

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
...
```

### Expected behavior

Clarify whether workspace-image or docker-up should be specified, and simplify double management.

**Comment by Furisto** [comment]
Timely issue @utam0k, was thinking the same thing. We should remove docker and docker-compose at least. Runc and uidmap should stay as customers could create custom images where they install docker themselves and we cannot expect them to know that they also need to install these two dependencies in order to make docker ns-remap work. 

@kylos101 What do you think?

**Comment by kylos101** [comment]
It's possible a user could avoid installing Docker and Docker Compose in their base image. Here is an example where the base image lacks both because the [base image is not from gitpod/workspace-*](https://hub.docker.com/u/gitpod). Thank you @mikenikles for the recent conversation in Slack, or I would have known about a minimal image to try!

- [Internal thread discussing a slim base image.](https://gitpod.slack.com/archives/C01RC164G48/p1643832231357119?thread_ts=1643822510.512109&cid=C01RC164G48)
- [Sample PR using slim base image w/o Gitpod base images](https://github.com/mikenikles/gitpod-minimal-custom-dockerfile/pull/2/files)

I see we added dependencies.sh [in this PR](https://github.com/gitpod-io/gitpod/pull/3633) because of [this issue](https://github.com/gitpod-io/gitpod/issues/3632). It looks like the intent was to make Docker and Docker Compose available to users - even if their base image did not support it. For example, [this branch has a docker-compose.yml file](https://github.com/Xcov19/covidX/blob/bug/fix-timeout-deps/docker-compose.yml).

@Furisto I just tried `docker` and `docker-compose` in https://mikenikles-gitpodminimal-yjd0d7snrd6.ws-us34xl.gitpod.io/, and they do not work:

```bash
gitpod@mikenikles-gitpodminimal-yjd0d7snrd6:/workspace/gitpod-minimal-custom-dockerfile$ docker
bash: docker: command not found
gitpod@mikenikles-gitpodminimal-yjd0d7snrd6:/workspace/gitpod-minimal-custom-dockerfile$ docker-compose
bash: docker-compose: command not found
```

I think this means we've got a broken regression, and as such, I am going to schedule this work. The intent, I think must be to make `docker` and `docker-compose` available to the workspace if the underlying image does not provide it.

To answer your original question, I think we must keep docker and docker-compose versions in both places, and if they do not exist in the image, `docker-up` will provide them. In this way, we can ship a new version in an image (or not), falling back to what is in `docker-up`.

**Comment by utam0k** [comment]
@kylos101 I feel makes sense.

**Comment by kylos101** [comment]
Thanks! I will close for now. We can reopen if there is demand/need.
