### ISSUE TITLE
transitions

### ISSUE THREAD

**Issue by sammysimmons** [gitpod-io/gitpod#851]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by JesterOrNot** [comment]
can you elaborate?

**Comment by jankeromnes** [comment]
Hi @sammysimmons, welcome to Gitpod!

Many thanks for opening an issue. If you encountered a bug with Gitpod, or you have a question about it, please reply here with a bug description or your question.

Otherwise, happy coding!

**Comment by sammysimmons** [comment]
Hey Jan,

Totally new to github and gitpod, I'm learning code athe moment however
when I'm trying to run the code through preview I'm constantly having to
keep refreshing the page for 10mins or more before anything works am I
doing something wrong?

Also it keeps duplicating the repository I now have.....

Thanks
Sam

**Comment by JesterOrNot** [comment]
what language are you learning?

**Comment by sammysimmons** [comment]
Css, java, python..

**Comment by jankeromnes** [comment]
Hey Sam,

So by default, Gitpod will create a new workspace every time you open a GitHub repository. That's by design, because we think it's nicer to create a new separate workspace for each new "development task" that you begin (for example, "fix bug X", "implement new feature Y", "test pull request Z", etc).

If you don't want to create a new workspace every time, please always go to https://gitpod.io/workspaces/ and click on "Start" next to an existing workspace -- that way, it won't duplicate the project.

However, having to refresh the preview for 10 minutes doesn't sound right, so maybe there is a bug in Gitpod that we need to fix.

Would you have time for a quick call, so that we can troubleshoot this together? I'd love to help get this to work, and also maybe I can answer a few questions about GitHub and Gitpod if you'd like.

- If you have time now, please feel free to jump into: https://meet.google.com/gdk-fopj-vjw
- If you'd like to have a call later, you can book it here: https://calendly.com/gitpod/onboarding

**Comment by JesterOrNot** [comment]
java compile: javac <filename> ie. javac app.java
java run java <filename but no extension> ie java app
