### ISSUE TITLE
Configuration of email notifications for selfhosting

### ISSUE THREAD

**Issue by fritterhoff** [gitpod-io/gitpod#8531]
At the moment the installer provides no out-of-the-box option to configure email notifications. The support/documentation should be extended at this place.

**Comment by jimmybrancaccio** [comment]
@fritterhoff I'd like to better understand this as I don't want to open a duplicate issue. Do you mean configure the email notifications (checkboxes) that show up on the Settings > Notifications - Email Notification Preferences page, or something else?

Or configuring the email notifications that are already setup - like the content of those email notifications?

**Comment by jemand771** [comment]
going by the original question on discord (that lead me to this issue), I think this is about configuring gitpod to use a mail server in the first place. I can't find any mention of it in the selfhosted docs or config.go and don't understand how gitpod is supposed to send emails without it.
As in- users have the option to set email preferences and receive emails from a selfhosted gitpod instance, but I don't know the way of setting that up from the admin's perspective

![image](https://user-images.githubusercontent.com/19669567/177107682-52396113-704f-48a6-99ae-f4b6eb8624ed.png)
https://discord.com/channels/816244985187008514/879915120510267412/948514669054808064

**Comment by fritterhoff** [comment]
> @fritterhoff I'd like to better understand this as I don't want to open a duplicate issue. Do you mean configure the email notifications (checkboxes) that show up on the Settings > Notifications - Email Notification Preferences page, or something else?
> 
> Or configuring the email notifications that are already setup - like the content of those email notifications?

Ah sorry I forgot to reply to your question. @jemand771 already explained what was my problem ;-)

**Comment by lucasvaltl** [comment]
Hey @fritterhoff and @jemand771 - thanks for raising this. I'd like to better understand your use case here. 

As of right now, we send two types of email notification - however currently not from self-hosted instances:
- Billing-related: these are not related to Self-Hosted, as billing works differently there - developers using a self-hosted instance are usually not concerned with billing.
- Tips/promotional/campaigns: these might be relevant for self-hosted users as well, at least with respect to tips.

(In order to avoid any further confusion here, I've raised https://github.com/gitpod-io/gitpod/issues/11193 to remove this page for now.)

To better understand if there are any emails we should be sending: What types of emails are you hoping to send and why?

**Comment by jemand771** [comment]
hmm right, I haven't given too much thought about what I'd actually want to get 😅 
I agree that promotional/billing-related emails are probably not relevant for selfhosted instances.
The only option that sounded relevant is "Account Notifications [required] - Receive essential emails about changes to your account"
I didn't really have anything specific in mind for this, I just expected there to be _something (since the settings are there)

Somewhere in the back of my head I had "password reset links, account confirmation, and the like" but given the way users sign into gitpod that's not relevant at all here.

**Comment by lucasvaltl** [comment]
That was a quick response :) If you think of anything feel free to add it into this ticket. 

From my side, I thought it might make sense to send emails related to tips around getting the best out of Gitpod. Not something we will likely work on soon, but I think it would be valuable to spread Gitpod usage within an organisation/team.
