### ISSUE TITLE
Malware Detected 

### ISSUE THREAD

**Issue by srinivastamada** [gitpod-io/gitpod#857]
**Symantec is block the following file **
https://ec8ca72e-d6d9-4887-b958-d0eaf2028886.ws-us1.gitpod.io/bundle.js

**Malware Detected**
Your request could not be completed. Malware has been detected in the selected file. To keep traffic on the network secure, your company has decided to prevent users from downloading files when malicious software is detected. Malware information: "Html.Exploit.CVE_2016_3271-2".

Tech support information: virus_detected more

All-To request access to this website, please open a Security Exception Request, on Equifax Central, open Global Security then open Security Exception Request and provide the website address (https://ec8ca72e-d6d9-4887-b958-d0eaf2028886.ws-us1.gitpod.io/bundle.js).

If this site is categorized as "none", "Uncategorized" or is categorized incorrectly, please follow the Web Site Categorization Instructions below.
1. Visit the BlueCoat Site Review Page: https://sitereview.bluecoat.com/sitereview.jsp
2. Enter the desired domain requiring re-categorization and click “Check Rating”.
3. Click the drop down box located below the “Filtering Service” label, select “Blue Coat Cloud Service”.
4. Select the most appropriate category for this domain (definitions provided).
5. (Optional) Select “Send results of the review via email”.
6. (Optional) Enter comments & site description details.
7. Click “Submit for Review”.
(Note: Site categorization may take up to one business day.)

**Comment by JesterOrNot** [comment]
@srinivastamada Can you send a link to the repo the workspace link you gave is either dead or we don't have access

**Comment by meysholdt** [comment]
hi @srinivastamada!

Thank you for reporting this. I assume this is a false positive. 

I could not find technical information about how the exploit `Html.Exploit.CVE_2016_3271-2` is supposed to look like. However, [many](https://github.com/google/draco/issues/202) [people](https://github.com/catx23/xamiro/issues/9) [got](https://twitter.com/kapeli/status/780535427019177984) [this](https://askubuntu.com/questions/743917/clamav-scan-found-the-virus-html-exploit-cve-2016-0108) message and it was a false positive. 

`CVE_2016_3271` describes a [vulnerability in the Microsoft Edge browser](https://www.symantec.com/security-center/vulnerabilities/writeup/91586`). This knowledge is not helpful either to tell whether the claim of your antivirus is correct. 

The `bundle.js` file your antivirus flagged is basically Theia IDE web-packed into a single file of JavaScript. It's several megabytes in size. 

Ans yes, like @JesterOrNot said, security@gitpod.io is the preferred way for reporting security related information. 

@srinivastamada, do you have technical information about `Html.Exploit.CVE_2016_3271-2`?

If not, I'll close this due to a lack of actionable information and ask you to report this finding to your antivirus supplier as a false positive.

**Comment by srinivastamada** [comment]
@meysholdt  Symantec antivirus is blocking gitpod bundle.js file. We able to access other online IDEs like GroomIDE

**Comment by JesterOrNot** [comment]
Should we close this issue and then in the future reopen it if necessary?

**Comment by jankeromnes** [comment]
I think this issue should remain open until @srinivastamada is able to use Gitpod. It's a bit annoying that an antivirus decides to block random websites like that.
