### ISSUE TITLE
Feedback Issue: Multi-repo workspace configuration

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8623]
### Objective

The aim of this issue is to gather feedback on the Beta feature: **Multi-repo workspace configuration**. 
Please add your feedback in comments below -- any feedback is welcome!

### More information
- [Docs](https://deploy-preview-1717--gitpod-kumquat.netlify.app/docs/multi-repo-workspaces)
- [RFC](https://www.notion.so/gitpod/RFC-Multi-Repo-Support-247be8565ed14d8e88cf4147a740c9fc)
- [Roadmap Issue](https://github.com/gitpod-io/gitpod/issues/7608) 
- [Pull Request](https://github.com/gitpod-io/gitpod/pull/7785)

**Comment by mikenikles** [comment]
I wanted to use this feature to open all `template-*` repositories in a single workspace so we can apply changes across all repos with minimal effort. See PR https://github.com/gitpod-io/template-all/pull/2.

I encountered various issues:
* https://github.com/gitpod-io/gitpod/issues/8952
* The GitHub Pull Requests & Issues extension repeatedly asks me to grant permissions
* The browser crashes after a few minutes

What was the maximum number of repositories multi-repo workspaces were tested with? I'd like to add a disclaimer to the docs to warn people not to exceed that number.

**Comment by ibrah3m** [comment]
I recommend providing an option to make us able to pass/get the main configuration from 
 environment-variables  like the example below 
 `YAML
mainConfiguration: $MY_VAR // should already exist or be passed by the URL 
`

**Comment by axonasif** [comment]
> 

You can pass env vars via URL: https://www.gitpod.io/docs/environment-variables#provide-env-vars-via-url
However, I guess this parameter does not support env vars now.

**Comment by ThePaulMcBride** [comment]
When working on local VSCode the `workspaceLocation` option doesn't seem to do anything. I have to navigate to the file described and then it prompts me to reload the workspace.

**Comment by axonasif** [comment]
> 

Hey @ThePaulMcBride, can you please describe more of what you're trying to do?

**Comment by ThePaulMcBride** [comment]
In this [article](https://www.gitpod.io/docs/multi-repo-workspaces) it says you can add a `workspaceLocation` line to the `gitpod.yaml` file so that both repos are opened in the IDE. This works when working in the browser IDE but when working with my local VSCode this doesn't work and only the main repo shows up. I can still right click in the file explorer sidebar and add it manually, so not the end of the world.

**Comment by Clemog** [comment]
Hi ! I am tring to deal with multi repos in the same workspace but adding the following lines in my gitpod config file doesn't clone the second repo ...
(for development, there are no task to do in the imported repo, it juste have to be a the same root)

Do i have something else to do to make the second repo appear in my workspace ?

```
additionalRepositories:
  - url: https://github.com/xxxxxxxxx

tasks:
  - init: yarn install && yarn run compile
    command: yarn run start
```

**Comment by tysonrm** [comment]
Can this be nested?

**Comment by scasei** [comment]
Addtional repositories are cloned as shallow copies [1] with `git clone --depth=1` [2]
If you need it deeper you can call ´git-fetch --depth 10000´ in the repo on init task or something.
I propose to update docs [3] about that fact or to load entire history as default.

[1] https://www.git-scm.com/docs/shallow
[2] https://github.com/gitpod-io/gitpod/blob/3939796825c604fe1e3fa6c9a59993a8abbb1ce6/components/content-service/pkg/git/git.go#L321
[3] https://www.gitpod.io/docs/multi-repo-workspaces

**Comment by sebastianjung** [comment]
making vscode workspace files work with this would be great. Otherweise having both folder in the workspace by opening the parent folder would be an option too. For me at least.

**Comment by spearki** [comment]
@jldec Something we found surprising (which someone has also [raised in discord](https://discord.com/channels/816244985187008514/1011358585093103616)), is that if you add an `additionalRespository` to a repo but don't have a `mainRepository` backlink from the additional repo, then prebuilds stop being used if there is a newer commit in that repo than the prebuild.

We would potentially have a lot of `additionalRepository` repos, and we don't really want all of them to be triggering prebuilds, so we didn't plan on adding a `mainRepository` link to them. But at the same time, we don't want that to break the use of prebuilds entirely.

**Comment by gierschv** [comment]
This features work great, we have 5 additional repositories in one of our workspaces.

Similar to @ThePaulMcBride feedback, I was wondering if that would be possible to opt-in for some of them to automatically add them to the VSCode workspace next to the main repository?

Kind of equivalent to this UI feature:

![Screenshot 2022-08-31 at 12 38 26](https://user-images.githubusercontent.com/396537/187660313-2fc14370-e42d-4f00-a2b6-e37346ac95a2.png)

Thanks!

**Comment by axonasif** [comment]
Hey @gierschv, we're doing it on this `gitpod` repo itself.

To make this work, you have to create a `.code-workspace` file and define the folders you would like to be loaded.
https://github.com/gitpod-io/gitpod/blob/ccb148f2a65f1be9a97f76342685b369792165db/gitpod-ws.code-workspace#L2

Next, you have to tell gitpod to use that `.code-workspace` file like so:
https://github.com/gitpod-io/gitpod/blob/ccb148f2a65f1be9a97f76342685b369792165db/.gitpod.yml#L2

-----
## More info on docs:
- https://www.gitpod.io/docs/multi-repo-workspaces
- https://www.gitpod.io/docs/references/gitpod-yml#workspacelocation

**Comment by gierschv** [comment]
> Hey @gierschv, we're doing it on this `gitpod` repo itself.
> 
> To make this work, you have to create a `.code-workspace` file and define the folders you would like to be loaded.
> 
> https://github.com/gitpod-io/gitpod/blob/ccb148f2a65f1be9a97f76342685b369792165db/gitpod-ws.code-workspace#L2
> 
> Next, you have to tell gitpod to use that `.code-workspace` file like so:
> 
> https://github.com/gitpod-io/gitpod/blob/ccb148f2a65f1be9a97f76342685b369792165db/.gitpod.yml#L2
> 
> ## More info on docs:
> * https://www.gitpod.io/docs/multi-repo-workspaces
> * https://www.gitpod.io/docs/references/gitpod-yml#workspacelocation

Awesome! I didn't know you could put a `.code-workspace` config here. From the docs it sounds like you can only pass the path of the folder you want to use as workspace root. It works perfectly :)

**Comment by david-bakin** [comment]
I'd like to point you to this comment - https://github.com/gitpod-io/gitpod/issues/9209#issuecomment-1098347728 - where I suggest considering the use case where you want to use Gitpod to work on repos where you have no access to that repo to add a `.gitpod.yml` and it will never happen.

What I'd particularly like is _environment variable expansion_ within `.gitpod.yml` _expecially_ in the `additionalRepository:` attribute.  Then I could have a "main repository" that used a per-user or per-project env var or frequentely an env-var-embedded-in-url to launch my desired repo as an "additional repository" but with all the configuration I want.  Even prebuilds.  And there would be two ways to use this:

1) Have a _project specific_ repo all prepared with a custom dockerfile and a `.gitpod.yml` for working with that desired repo and make it public and _anyone_ could _immediately use it_ with _their own fork (!!!)_ merely by using the env var to point to their fork of that repo.  (This is what I'm trying to do with https://gitlab.com/bakins-bits/gitpod-setup-for-bitcoin-core-dev/ but without this capability that repo still needs to be cloned by everyone intending to work with Bitcoin Core.)

2) Have a sort of "generic" setup repo that would work with any repo you'd like to work with that went beyond basic dotfile support - you could have a custom container that you always used (perhaps with additional tools), also a custom `.gitpod.yml` of course - this would apply if you frequently did _similar_ work but in different repos.  _Even if you could_ put a `.gitpod.yml` in those repos you worked in you might, maybe, want to have a single configuration setup rather than copy it into each such repo _and maintain it_.

**Comment by shyim** [comment]
I would like to use this feature to clone my repository inside another repository.

For the context: My repository is an extension for another.  So I have to install first the other repository and clone my repository inside a specific folder.

For this I would like to install inside an `additionalRepository` my repository. I did that currently all using init section and moving files, but this breaks with image caching of prebuilds

**Comment by axonasif** [comment]
Cross posting potential feedback:
- https://github.com/gitpod-io/demo-multi-repo-frontend/issues/1

**Comment by sgurlt** [comment]
This is currently a nice feature but is lacking integration into prebuilds.
Within my prebuild `init` steps I want to be able to interact with my additional repositories.
Sadly I have learned the hard way, that the additional repositories are not existent during the prebuild phase.

Additionally, to that, I want to be able to select additional repositories that trigger a prebuild of my main repository, when a commit is found added to a given branch.

**Comment by svenefftinge** [comment]
This should work. Can you share the repositories (configurations) you are using it with?
