### ISSUE TITLE
Problems when selecting characters with IME

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/gitpod#875]
**Describe the bug**

![1572176989086](https://user-images.githubusercontent.com/38714187/67634132-6bc40900-f8fb-11e9-8e47-acfedfc45cae.gif)

**To Reproduce**

Enter with IME and press Tab

**Expected behavior**

![1572177225395](https://user-images.githubusercontent.com/38714187/67634185-e68d2400-f8fb-11e9-8311-5cbde4bce48f.gif)

**Additional Information**

**Comment by monaka** [comment]
@mouse484 I'm a committer of Eclipse/Che. And I'm inspecting the similar issue in Che-Theia editor.
I suspect your issue is caused by Theia, that Gitpod uses.
Theia should care about the key code `KEY_IN_COMPOSITION` but it doesn't.
It might be better to open the new issue to https://github.com/eclipse-theia/theia
