### ISSUE TITLE
Switch IDE version with one toggle

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#8786]
## Is your feature request related to a problem? Please describe
`Latest Release` only works for JetBrains IDE, and the `insiders` version of VSCode is one stand-alone option.

## Describe the behaviour you'd like

We can change the IDE configuration with one toggle only to switch the LATEST (EAP) version of IDE, vscode included.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/20944364/158135221-2ac9d32a-cd50-4aa7-8f9e-166112b2dcd0.png">

**Comment by akosyakov** [comment]
@gtsiolis @loujaybee I remember there was a proposed design somewhere without browser and desktop headers, but with just list of IDEs and then 2 new toggles:
- to control whether desktop or browser IDE should be opened by default
- and whether latest release should be used

In this design for VS Code there will be only one tile. 

Could you point to it?

**Comment by akosyakov** [comment]
Got feedback from @svenefftinge that VS Code Desktop should be own product. So then only one toggle to use latest.

**Comment by gtsiolis** [comment]
> ... that VS Code Desktop should be own product. 

Makes sense. 💯 

🍊 🍊 🍊 🍊 

The proposed designs mentioned in https://github.com/gitpod-io/gitpod/issues/8786#issuecomment-1066527780 can be found in https://github.com/gitpod-io/gitpod/issues/7932. There were some ongoing discussions and the designs are also work-in-progress, see screenshots below. Feedback is welcome.

[ETA](https://en.wikipedia.org/wiki/Estimated_time_of_arrival): Will update the final specs later today or tomorrow. ⏱️ 

🍋 🍋 🍋 🍋 

💭 **thought**: We could safely proceed with the updated card-based design, drop the desktop switch checkbox, and simply indicate that one of the two VS Code editor options is browser-based or also the default (fallback) option.

💡 **suggestion**: It's worth paying attention to the latest switch checkbox description so that it's inclusive and safely addresses both latest versions for all editors, incl. VS Code Insiders and JetBrains EAP.

❓ **question**: One question here is whether is makes sense to include version numbers for any the desktop editors. For VS Code only if you have Insiders installed would work regardless which exact version, right? Similarly, for JetBrains editors only indicating EAP version could suffice. However, for this iteration we could simply drop any version numbers and rely on the checkbox below to indicate whether we're using latest or not.

| Card-based (DRAFT) | Dropdown-based (DRAFT) |
|-|-|
| <img width="1440" alt="Editors" src="https://user-images.githubusercontent.com/120486/158217419-dfec68e4-496b-41df-ac8c-d12c7e9e8b75.png"> | <img width="1440" alt="Editors-1" src="https://user-images.githubusercontent.com/120486/158217422-a3dcf699-fadd-4d59-aabc-6d9d21b6bf7e.png"> |

**Comment by akosyakov** [comment]
>  One question here is whether is makes sense to include version numbers for any the desktop editors. For VS Code only if you have Insiders installed would work regardless which exact version, right? Similarly, for JetBrains editors only indicating EAP version could suffice. However, for this iteration we could simply drop any version numbers and rely on the checkbox below to indicate whether we're using latest or not.

Let's file another issue for versions. They are just nice to see what we actually support now. But it requires some work to get them. @mustard-mh Could you file another issue? And add it to scheduled?

**Comment by gtsiolis** [comment]
Closing this as it has been resolved in https://github.com/gitpod-io/gitpod/pull/8783. Thanks, @mustard-mh @akosyakov!

**Comment by akosyakov** [comment]
Could someon file an issue to show versions then we toggle `Latest Release`? I think it is really good feedback to indicate whether it is enabled or not.
