### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#8952]
### Bug description

Workspaces no longer start due to `API rate limit exceeded for user ID 788827.`

That user ID is my personal one.

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/788827/160007090-1c92a1ca-41e9-48c3-a811-4a53caf3daaa.png"/>
</details>

### Steps to reproduce

Attempt to open any Gitpod workspace.

### Workspace affected

All

### Expected behavior

Workspaces start

### Example repository

Any

### Anything else?

About 30 minutes ago, I worked with https://github.com/gitpod-io/template-all/pull/2 where I have a multi-repo configuration that loads 67 additional repositories.

This on its own caused numerous bugs (I will open separate tickets once I can start workspaces again). I wonder if I hit my rate limit because of the work I did earlier.

**Comment by mikenikles** [comment]
Resolved after going for a walk. This is very likely related to the new multi-repo workspace feature.

**Comment by mikenikles** [comment]
On second thought, this is a valid bug with multi-repo workspaces - re-opening.

**Comment by geropl** [comment]
Scheduled it because users can end up in this situation quite easily, just by following our docs.

We should investigate whether there are some low-hanging fruits, e.g. where we're pulling unnecessary things for all repos involved. `.gitpod.yml`, `Dockerfile`, or similar.

/cc @jldec

**Comment by meatflavourdev** [comment]
How do I fix this? Gitpod basically is non-functional for me for the last 2 days, all I get is this error.

**Comment by yenicelik** [comment]
same issue. was repeatedly building repos, but this is not mentioned anywhere in the pricing or plan structures

**Comment by geropl** [comment]
To clarify:
 - this is a rate limit imposed by GitHub
 - AFAIU this might happen if you use multi-repo, where - depending on the size and structure/config - we are currently pulling a lot of (possibly redudant) info on each workspace start

**Comment by AlexTugarev** [comment]
That happens to me today. I was working on a single Gitpod workspace for +1h and the only thing that could have drained the API rate is the GitHub Pull Requests extension. 

<img width="465" alt="Screen Shot 2022-09-13 at 10 45 23" src="https://user-images.githubusercontent.com/914497/189951715-2ddd9c1a-2831-424e-9986-8aa1125f393c.png">

That said, there is no easy fix for this. If the Pull Request extension goes wild, and chances are best if multi-repo workspace is opened, the API rate is burnt for 1h or so. 

We can add a better GH Error code to improve the startup experience, i.e. explain what's happening, but because this limit applies to ones GH account, not the integration with Gitpod, that a solid wall.

**Comment by AlexTugarev** [comment]
Possible related issue https://github.com/microsoft/vscode-pull-request-github/issues/3847

**Comment by raphaeltm** [comment]
I'm running into this issue as well. I'm not using multi-repo, but I do have ~20 submodules. I'm not sure if I have anything more meaningful to add, but I figured I'd add my voice here. It's frustrating because it prevents work on any other GitHub-based repos.

**Comment by mobi3006** [comment]
shouldn't

- https://github.com/microsoft/vscode-pull-request-github/pull/4043

fix the issue? 

On my v.0.54.0 of "GitHub Pull Requests and Issues" it is not yet fixed. Giving the pre-release version (v0.55.2022111609) a chance ...

**Comment by elemwr** [comment]
I run into this issue since I started to use gitpod, My scenario:
1. I do something in workspace, then goes AFK. When I come back my workspace is stopped - thats ok. I want to start it again, but it goes into loop displaying "preparing" and refreshing the browser tab until I go back to dashboard manually. It never goes into error.
2. I think that maybe re-login will help, so I try to do it but then I get and error API rate limit exceeded and its not possible to login. GH says that for authenticated user the limit is 5000 calls per hour. Does every try of workspace start makes an call? Or what is the cause of filling this limit so dramatically fast?
