### ISSUE TITLE
Incremental prebuilds not triggering custom dockerfile rebuild on change

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#8980]
### Bug description

Gitpod is not picking up changes in custom dockerfile specified from `.gitpod.yml:image:file` when incremental prebuilds is enabled.

### Steps to reproduce

- Enable incremental prebuilds from project settings.
- Make changes to your dockefile (e.g `.gitpod.Dockerfile`)
- Push the change
- Open a new workspace
- Observe if the new dockerfile changes are reflected in the workspace

### Expected behavior

Custom dockerfile changes are picked up and imagebuild is triggered.

### Anything else?

See three reports on Discord:
1. https://discord.com/channels/816244985187008514/816246578594840586/958073574302818314
2. https://discord.com/channels/816244985187008514/816246578594840586/956491168500314132
3. https://discord.com/channels/816244985187008514/959493715955683378/959493722251333632

**Comment by djsnipa1** [comment]
Is there a workaround for this? I’ve been trying to get my workspace to prebuild properly but it always uses an old custom dockerfile. Please help

**Comment by axonasif** [comment]
> Is there a workaround for this? I’ve been trying to get my workspace to prebuild properly but it always uses an old custom dockerfile. Please help 

Try `https://gitpod.io/#prebuild/https://github.com/you/repo.git`

**Comment by jldec** [comment]
As a workaround, how about temporarily turning off the incremental prebuild flag and then triggering the prebuild?

**Comment by jldec** [comment]
scheduled for investigation.

**Comment by axonasif** [comment]
> As a workaround, how about temporarily turning off the incremental prebuild flag and then triggering the prebuild?

That works 👍, also if you trigger a prebuild by `https://gitpod.io/#prebuild`

**Comment by jankeromnes** [comment]
We were able to reproduce this bug with @laushinka, and believe we have found the bug. 🐛

Long story short: Since a recent refactor of the Incremental Prebuilds logic (from 3 weeks ago), we now seem to consider _every_ old Prebuild as a compatible base for new Incremental Prebuilds. 😱 (Even if the Prebuild had an older image, or even if it was a failed Prebuild...)

### Details

The reason is that we now have this method to determine whether an old Prebuild is a good compatible base for a new Incremental Prebuild or not:

https://github.com/gitpod-io/gitpod/blob/2f0b9462b0451f0974434fa36bd757420ef04e34/components/server/ee/src/workspace/workspace-factory.ts#L170

However, when we call this `async` method, we do not `await` -- thus we consider ever old Prebuild as a good base 😱

https://github.com/gitpod-io/gitpod/blob/2f0b9462b0451f0974434fa36bd757420ef04e34/components/server/ee/src/workspace/workspace-factory.ts#L112-L113

The impact isn't actually too noticeable, since the Incremental Prebuild will re-run all `init` / `prebuild` tasks fresh on top of it. However, the Docker image will not be rebuilt, which is how we've noticed this problem.

Working on a fix with @laushinka.

**Comment by jankeromnes** [comment]
Note: We've merged a fix and expect it to be deployed tomorrow around 2022-04-05T08:30
