### ISSUE TITLE
Prebuilds not working

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#907]
**Describe the bug**
Prebuilds not starting
**To Reproduce**
open this repo
https://github.com/JesterOrNot/pymath
**Expected behavior**
prebuilds work as usual!
**Additional Information**
I use prebuild: for tasks

**Comment by svenefftinge** [comment]
Did you install and enable the GitHub App on your project?
https://github.com/apps/gitpod-io

**Comment by jankeromnes** [comment]
Note: Once you've made sure prebuilds are enabled for your project in the GitHub App, you'll also need to push a new commit to master to trigger a prebuild.

Another note: Prebuilds worked successfully for other repositories belonging to you: e.g. https://github.com/JesterOrNot/voc. But the last successful prebuild for _any_ of your projects was on `2019-07-30`, so either:
- you haven't pushed commits to a prebuild repo since July 30, or
- you uninstalled or disabled the Gitpod App, or its installation broke, after July 30

Maybe try re-installing the app?

**Comment by JesterOrNot** [comment]
wouldn't that void my subscription?

**Comment by jankeromnes** [comment]
It really shouldn't. (If that happens, it would be a severe bug.)

**Comment by JesterOrNot** [comment]
Alright I'll try

**Comment by JesterOrNot** [comment]
Issue resolved for anyone who stumbles on this issue the fix is reinstall GitPod
