### ISSUE TITLE
[server] add a metric for received webhook events

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#9170]
*Problem to solve*

Let's see the frequency of webhook events. Tough it's clear, that we want/need to decouple inrush from actually handling of those events, it would be interesting to see the impact on the current system.

**Comment by AlexTugarev** [comment]
@jldec, you are right about the overlap. Do you think merging both is necessary?

I'd like to see a metric for received webhook events per provider in order to identify spikes (or issues) and correlate with load induced.

**Comment by jldec** [comment]
Feel free to combine the 2 issues. The requirement from a support perspective is that we need to be able to trace working prebuilds from repo commit -> webhook trigger -> prebuild start -> prebuild end. 

This would give us a baseline to find issues when say webhooks stop arriving from the git provider, or prebuilds are not starting because of auth for a specific user, or because of a broken git integration.
