### ISSUE TITLE
Research how to throttle I/O latency or bandwidth

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9241]
## Is your feature request related to a problem? Please describe

There can be times where disk IO is high (`atop -D`, see giant percentages), and the pods on a node are suffering due to high I/O usage. For example, this could be coming from `ws-daemon` doing backup/restore with TAR, or a workspace running intensive `docker compose`.

## Describe the behaviour you'd like

Research if we can throttle latency (IO latency controller ), or [bandwidth](https://andrestc.com/post/cgroups-io/), to provide a more consistent experience for users. 

Another possibility to look into is [this](https://github.com/intel/goresctrl/blob/main/doc/blockio.md). Nice find, @aledbf .

## Describe alternatives you've considered

We are currently considering enabling a custom kernel with [this feature enabled](https://cateee.net/lkddb/web-lkddb/BLK_CGROUP_IOLATENCY.html). But it doesn't fully solve the issue.

## Additional context

[Internal Slack](https://gitpod.slack.com/archives/C02F19UUW6S/p1649689118890019)

**Comment by Furisto** [comment]
Raw, unedited thoughts, will update later:

- Our goal should be to be work conserving, meaning that the machine should not be idle while there is still work to do. We should also strive to to not throttle workloads if we have resources to spare (an anti example of this would be cpu control with cpu.max where the workload would not get more than the quota even though more compute capacity is available)
- We do not want the application do change in any way (e.g. like only having to use direct IO). The control mechanism should be transparent to the workload.
- The IO controller seems actually to be multiple controllers that are activated when the kernel is build with the correct flags. CONFIG_BLK_IO_COST activates the blk_iocost controller (this controller exposes the io.cost.qos and io.cost.model cgroup interface files). There is also CONFIG_BLK_CGROUP_IOLATENCY) which exposes the io.latency file and adds extra stats to the io.stat file). Another is CONFIG_BLK_CGROUP_IOPRIO which exposes the io.prio.class file). We currently have all of these activated with the exception of CONFIG_BLK_CGROUP_IOLATENCY (but have a custom kernel build where this flag is enabled).
- The recommendation seems to be to concentrate on one IO control mechanism as the controllers interact with each other in ways that are not easily to predict.
- There is a correlation between memory and IO that we need to be aware of. If memory usage of workloads goes up the OS will start swapping and this contributes to increased IO pressure. We could see increased IO pressure, but the culprit is actually  memory pressure.
- Pressure stall information (PSI) could give us insight into which workloads are currently experiencing resource pressure. PSI is tracked per cgroup, so this would give us a finer grained insight than just "node is overloaded". This information is tracked in memory.pressure and io.pressure cgroup files (there is also cpu.pressure, but that is not important for this issue). I am not sure if we are capturing this information anywhere. If anything I would expect this information [here](https://grafana.gitpod.io/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&refresh=10s), but I did not see it.

**Comment by utam0k** [comment]
We are using `xfs` so we will be able to properly limit io outside of direct IO.
Today, I found the Issues: 
- Is it necessary to limit each workspace? If so, what to do since the limit can only be applied to each device.
    - We will need to know and verify exactly how inheritance works with cgroup v2 io. It may be possible to limit per workspace by using inheritance.
- How do we set the threshold?

**Comment by utam0k** [comment]
The mem of workspace is currently limited by cgroup. The `memory.limit` is set to 80% of `memory.max`. This may affect swapping.
> There is a correlation between memory and IO that we need to be aware of. If memory usage of workloads goes up the OS will start swapping and this contributes to increased IO pressure. We could see increased IO pressure, but the culprit is actually memory pressure.

**Comment by utam0k** [comment]
Relates PR https://github.com/gitpod-io/gitpod/pull/9271

**Comment by utam0k** [comment]
@kylos101 Can we close this issue by https://github.com/gitpod-io/gitpod/pull/9271?

**Comment by kylos101** [comment]
Yes, although, we need a new issue (to avoid throttling I/O for content-init, and potentially backup). :wink:
