### ISSUE TITLE
Error response from daemon: OCI runtime create failed /proc/self/fd

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#9247]
### Bug description

#8070 follow up

It just happend again

![image](https://user-images.githubusercontent.com/1100969/162907847-18c42359-ecb0-4343-9551-6f3609962910.png)

### Steps to reproduce

see descriptions

### Workspace affected

vizlib-gucci-0daa9pimywm.ws-eu39axl.gitpod.io

**Comment by kylos101** [comment]
@utam0k this appears to have manifested again. Could we ask you to take a peek?

**Comment by utam0k** [comment]
@konne I investigated the logs of this error. However, I didn't find this error message in the last 30 days. It's possible that my research for errors is incorrect.  Are you still encountering this error?
We have been running the integration test for the previous issue #8070 measures every day since about last week.

**Comment by konne** [comment]
@utam0k still happens:
at least one developer had this issue yesterday at 3:58 PM GMT+2 on vizlib-gucci-yom27jlp1k9 workspace

**Comment by utam0k** [comment]
@konne cc: @kylos101 
Thanks for your information. I found the same error message. This problem is certainly happening.
> at least one developer had this issue yesterday at 3:58 PM GMT+2 on vizlib-gucci-yom27jlp1k9 workspace

I tried to reproduce this problem with https://github.com/kylos101/OCI-runtime-create-failed, but I couldn't. How often did you encounter it?


And, today I found a curious thing the proc mount sys-call has sometimes failed since 4/30. I guess it may relate to this problem. However, there was insufficient information in the logs to trace from those failed logs to workspace information. I'll try creating PR to add some information to these logs tomorrow.
https://cloudlogging.app.goo.gl/oqgziQvYjPS2A2Xw5 (sorry, it is internal link)

**Comment by utam0k** [comment]
And this seems to be a different bug than the last one, I couldn't reproduce the problem after 1000 iterations of mount proc.

on workspace
```console
for i in {1..%d}; do echo $i; sudo unshare -m --propagation unchanged mount -t proc proc $(mktemp -d) || exit 1; done
```

**Comment by konne** [comment]
@utam0k  this bug happens during a complex docker-compose up we start:
kes, nginx, postgres, nats and about 5 go and nodejs services.
This happens about once a day per developer and I would say the developer does that docker-compose up maybe 3 times a day.
If this happens we can just start it again and usually, it is working then, so this is the reason the devs only report it to me if I actively ask for.

**Comment by utam0k** [comment]
@konne I possibly found the root cause of this problem. This is a parallel problem docker-compose and seccomp notify. I'll try to mitigate this.

**Comment by utam0k** [comment]
I tried to mitigate this. It was difficult to eliminate completely. This was mitigated somewhat by speeding up the handling of system calls in gitpod, but it will probably never be completely eliminated. It is safe for docker-compose and runc to handle the error and retry.
https://github.com/gitpod-io/gitpod/pull/11082

**Comment by utam0k** [comment]
`COMPOSE_PARALLEL_LIMIT` may help reduce this error. But it affect the start-up performance 😭 
https://docs.docker.com/compose/reference/envvars/#compose_parallel_limit

**Comment by spearki** [comment]
> This was mitigated somewhat by speeding up the handling of system calls in gitpod, but it will probably never be completely eliminated. It is safe for docker-compose and runc to handle the error and retry.

Hi @utam0k, thanks for your work here. I still regularly see this (along with other temporal runc-related failures) in our docker-compose stacks. I wonder if this retry could be handled in `runc-facade`?

**Comment by utam0k** [comment]
> > This was mitigated somewhat by speeding up the handling of system calls in gitpod, but it will probably never be completely eliminated. It is safe for docker-compose and runc to handle the error and retry.
> 
> Hi @utam0k, thanks for your work here. I still regularly see this (along with other temporal runc-related failures) in our docker-compose stacks. I wonder if this retry could be handled in `runc-facade`?

Good question! Great idea. It might be worth a try.

**Comment by utam0k** [comment]
@kylos101 , can you give me time to re-open this issue and give it a try?

**Comment by kylos101** [comment]
:wave: @spearki, is it possible for you to recreate this error from a public repo? I ask because that would help expedite debugging that @utam0k would do. Let us know? :pray:

**Comment by spearki** [comment]
> 👋 @spearki, is it possible for you to recreate this error from a public repo?

Hi @kylos101 👋🏻. Not sure, but I can try! Will get back to you.

**Comment by utam0k** [comment]
@spearki Thanks for your effort. I looked into how to identify the type of runc's error. I found this issue and asking to OCI spec team.
https://github.com/opencontainers/runtime-spec/issues/1061

short term: I am thinking that perhaps putting in about 3 retries would be a significant improvement.
long term: contributing to runc(?)

**Comment by utam0k** [comment]
The runc exit code usually mirrors the exit code of the running container application. So we can identify it as not found. But you are right, the container application could give a not found error, and we can't currently distinguish between that and the not found error 😭

**Comment by spearki** [comment]
> @spearki Thanks for your effort. I looked into how to identify the type of runc's error. I found this issue and asking to OCI spec team.
> [opencontainers/runtime-spec#1061](https://github.com/opencontainers/runtime-spec/issues/1061)

Thanks for the pointer @utam0k, it's interesting that these errors aren't part of the spec!

> short term: I am thinking that perhaps putting in about 3 retries would be a significant improvement.

I found that 1 retry was enough to eliminate it for us, since the error is quite rare already from the perspective of a single container. Maybe twice to be safe? :)

> The runc exit code usually mirrors the exit code of the running container application. 

What I noticed was that for any errors that happen during `runc init` (up to the point it is ready to exec the container entrypoint) the error code returned is always 1:
https://github.com/opencontainers/runc/blob/4a51b047036cf16d4f124548c2a7ff24b5640bad/init.go#L35-L39

**Comment by utam0k** [comment]
Good information. Maybe twice would be better since the container activation is a fairly small time.
> I found that 1 retry was enough to eliminate it for us, since the error is quite rare already from the perspective of a single container. Maybe twice to be safe? :)

As you may possibly know, the init command is an internal subcommand of runc and is not usually used directly.　In this case it is the create command, but the create command calls the init command internally; how the create command handles errors from the init command may be important. That needs a little more investigation. My experience is that runc is probably using fifofd.
> What I noticed was that for any errors that happen during runc init (up to the point it is ready to exec the container entrypoint) the error code returned is always 1:
https://github.com/opencontainers/runc/blob/4a51b047036cf16d4f124548c2a7ff24b5640bad/init.go#L35-L39

**Comment by utam0k** [comment]
@spearki I've created a new issue because it's getting a little out of line with the purpose of this issue. Please keep watching this issue 🙏 Your help is greatly appreciated.
https://github.com/gitpod-io/gitpod/issues/12365

**Comment by spearki** [comment]
> @spearki I've created a new issue because it's getting a little out of line with the purpose of this issue. Please keep watching this issue 🙏 Your help is greatly appreciated.

Will do, thanks!

> how the create command handles errors from the init command may be important. That needs a little more investigation. My experience is that runc is probably using fifofd to get a exit code.

Agreed. I haven't been able to trace where that is happening exactly yet.

**Comment by utam0k** [comment]
@spearki @konne Thanks for waiting. We deployed the workaround @spearki suggested(Thanks). I think they've improved. It is not a complete solution, but it should be better.
