### ISSUE TITLE
Be able to set PATH environment variable for all shell (terminal) windows in VSCode from `.gitpod.yml`

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#9275]
I'd like a way to alter the PATH from `tasks/command:` or `tasks/env:` so that it takes effect in the terminal window.  

Currently if you do alter the path in the usual way - `PATH=/new/dir:$PATH` - it only is in effect during the `init:` or `command:` task - it doesn't stay set in the terminal window in VSCode.  In fact I don't know of a way to do it.

Reason is: In the `init:` I add binaries to directories in `/workspace` so they persist - I want to have those binaries in the path so I can use them both in `command:` and also in any shell/terminal window in VSCode.  I can get it in `command:` by adding it to the path _again_, which is tedious but ok, but I _really_ want them in a terminal window for every such window I launch. 

I know (i.e., believe, haven't tried it yet) that I can use the Dockerfile feature ["environment replacement"](https://docs.docker.com/engine/reference/builder/#environment-replacement) to do it there; but for various reasons it is better (for my use case) to do it in `.gitpod.yml`.

An "easy" fix (for some definition of easy) would be for `tasks/env:` to do variable substitution - even if limited to environment variables, and then make sure they're defined in the "outer" shell it launches.

Maybe better would be an option to always put some extra directories in the path - `/workspace/.bin` would be a good one!

(Or you can propose alternative workarounds here.)

**Comment by axonasif** [comment]
Hey @david-bakin, you can do it with `before:` task since `init:` can effect `/workspace` dir only in terms of persistency[^1], so you write to `$HOME/.bashrc` and that's enough.
Check https://github.com/axonasif/test/blob/c45459ff8eeebadbb9cd7b166edd49ae66eb65db/.gitpod.yml#L4 for example. Or you can copy paste this snippet into your `.gitpod.yml` and change the `/usr/games` string as per your needs:
```yaml
tasks:
  - before: printf 'export PATH="%s:$PATH"\n' "/usr/games" >> $HOME/.bashrc && exit
```

[^1]: https://www.gitpod.io/docs/prebuilds#workspace-directory-only
