### ISSUE TITLE
KOTS Admin Dashboard Shows Incorrect Version Deployed

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#9310]
### Bug description

This is slightly connected to #9308, wherein if an upgrade fails, the version that is really deployed isn't reflected in the KOTS admin dashboard. It shows the version that it attempted to upgrade too, but doesn't revert if the upgrade failed. My instance was/is running `main.2860` and failed to update to `main.2898`.

<img width="614" alt="Screen Shot 2022-04-13 at 15 03 06PM" src="https://user-images.githubusercontent.com/405585/163276418-8982cbdc-33c1-4426-a187-ef2d8a126034.png">

The failed version should not be displayed here as the currently deployed version.

### Steps to reproduce

This may be a little difficult to replicate (at least I am not 100% sure on how too).

1. Spin up a Gitpod instance.
2. From the KOTS admin dashboard attempt to deploy a version of Gitpod which would be known to fail to upgrade too.
3. Observe the UI is updated to show that the currently deployed version is the one which failed to upgrade and not the version which is actually deployed.

**Comment by lucasvaltl** [comment]
To be realistic, we don't think we can execute on this soon - we would need to engage with Replicated, and they are unlikely to prioritise this for us. As such, I will close this for now.

**Comment by jimmybrancaccio** [comment]
@lucasvaltl Rather than close the issue, shouldn't we start the process of engaging with Replicated? Even if it's not a high priority for them this issue still stays open and we can note we've at least started the process with them?

Regardless we probably shouldn't close the issue but leave it open as I'm hoping it's something we'd work on (eventually). I would only close it if it's not something we'd be interested in ever making happen.

**Comment by lucasvaltl** [comment]
👋 Thanks for raising this - currently, we are working under the principle of closing things we are unlikely to do any time soon - but we are happy to reopen them as they become a priority again. This is mostly done to keep the backlog clean and focused in order to facilitate internal team collaboration. Happy to talk about this! 

I've started the process with replicated, you can follow along [here](https://github.com/replicated-collab/replicated-gitpod/issues/33) (private repo). Also updated the description of this issue.
