### ISSUE TITLE
vscode about dialog don't show insiders label

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#9380]
After https://github.com/gitpod-io/gitpod/pull/8783/ now `ideAlias` is always `code` for insiders and stable.
We need to look for other ways to differentiate vscode insiders and stable

**Comment by andreafalzetti** [comment]
I'd be keen to pick this up, I just have a couple of questions:

- what component is actually affected by this bug?
- what's the "vscode about dialog"?

cc @jeanp413 @akosyakov

**Comment by andreafalzetti** [comment]
@akosyakov and I had a call and clarified the impact and work required.

Summary:
- The `ideAlias` property is part of workbench (part ofGitpod VS Code browser extension) and the misconfiguration could cause both visual and functional bugs (because we do not differentiate between `code` and `code-latest` anymore). The blast radius of the bug is not well defined.
- The agreed solution includes extending supervisor with an additional property `bool ide_latest` and source the `ideAlias` from the workspace instance configuration instead of the user's preferences (so that it's actually accurate)

I am going to start working on this issue today.

cc @jeanp413 @akosyakov

**Comment by andreafalzetti** [comment]
I had a chat with @jeanp413, we agree to proceed with the approach he suggested cc @akosyakov
