### ISSUE TITLE
.vsix are availabe for download from marketplace as apposed to what docs say

### ISSUE THREAD

**Issue by janat08** [gitpod-io/gitpod#942]
The doc page in question gives the impression that it's difficult to get the .vsix file for extensions and its not.
https://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline
https://www.gitpod.io/docs/vscode-extensions/

**Comment by jankeromnes** [comment]
Hi @janat08, thanks for your input.

I think what the Gitpod docs are trying to say is that Gitpod can not directly use the Visual Studio Marketplace:

> Microsoft prohibits the direct use of the Visual Studio Marketplace for any other software but their own. Although most extensions are open-source and not even developed or maintained by MS, the access to the Marketplace is restricted.

I think that's why Gitpod isn't allowed to tell users to download `.vsix` files from the Marketplace directly.

**Comment by janat08** [comment]
Under law describing how to commit a crime is not a crime.

**Comment by jankeromnes** [comment]
Thanks a lot for the positive sentiment! 🙂 But as I'm not a specialist in international business laws, I try to stay well clear of any lines I wouldn't know how to walk.

**Comment by ntziolis** [comment]
As far as I understand the licensing for the marketplace, its not just that:  
- gitpod (or other companies / editors ) are not allowed to pull from the marketplace directly for you
- but its generally disallowed to install the vsix into a non microsoft product even when you do so manually

The reason the download link is even there is for example so corporate customers can download a specific version of an extension. In order to:  
- install it into vscode or visual studio on machines that do not have access to the marketplace (corporate firewall)
- and to be able to control the versions of extensions that is being installed
