### ISSUE TITLE
when i run my code output showing is no output yet i am not getting it please can i get stepby step gitpod configuration for C Language?

### ISSUE THREAD

**Issue by Parshchakurkar** [gitpod-io/gitpod#951]
heelo i am not able to configure gitpod ide for C language please help.

**Comment by JesterOrNot** [comment]
Can you be more specific about what isn't supported?

**Comment by svenefftinge** [comment]
Sharing your project is usually the best way to allow us to help you.

**Comment by Parshchakurkar** [comment]
https://github.com/Parshchakurkar/first-c-project here is my github repo link

**Comment by jankeromnes** [comment]
@Parshchakurkar Thanks for sharing your repository!

So, Gitpod will work with C projects right out of the box (no configuration needed). I simply tried this:
1. opened your repository in Gitpod, by visiting https://gitpod.io/#https://github.com/Parshchakurkar/first-c-project
2. compiled your code by running `gcc prashant.c` in the Terminal
3. ran your code by running `./a.out` in the Terminal
4. since it waits for a number, I then typed `3`, and your program printed `three` and exited:

```
gitpod /workspace/first-c-project $ gcc prashant.c
gitpod /workspace/first-c-project $ ./a.out 
3
three
```

As you can see in this screenshot, as soon as you open a `C` file, Gitpod's language server will already be running in the background, analyzing the code:

<img width="925" alt="Screenshot 2019-12-09 at 19 21 12" src="https://user-images.githubusercontent.com/599268/70461716-9b992b80-1ab9-11ea-9824-3576225977f8.png">

Nevertheless, I've sent you a pull request with an example Gitpod configuration that will automatically compile and run your program: https://github.com/Parshchakurkar/first-c-project/pull/3

**Comment by Parshchakurkar** [comment]
Thank you .It is a great help.

**Comment by Varshi567** [comment]
how to get output without code after opening github
