### ISSUE TITLE
Google Analytics in workspaces

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#956]
Hello!
I just noticed that Google analytics is active in workspaces, which I am certainly not comfortable with.  

I can understand having GA on the landing page, but on the dashboard and in workspaces, that is something I am NOT ALRIGHT with.

In my opinion this is a serious violation of privacy within workspaces, as GA can collect data for its personal profiles.  

Please remove it from workspaces/dashboard as soon as possible.

**Comment by JesterOrNot** [comment]
What's wrong with GA?

**Comment by RDIL** [comment]
https://privacy.rdil.rocks/#analytics

**Comment by JesterOrNot** [comment]
So what even GitHub uses it see?
![image](https://user-images.githubusercontent.com/50386709/69734823-45111200-10f5-11ea-87d6-4bf579ae428e.png)

**Comment by RDIL** [comment]
They actually use octolytics, and I'm pretty sure that is just because this page has the words "Google Analytics" together

**Comment by JesterOrNot** [comment]
here is another on another page where the results are duplicated
![image](https://user-images.githubusercontent.com/50386709/69735497-632b4200-10f6-11ea-82a2-3eb57e86fcf3.png)
https://github.com/JesterOrNot/gosh/pull/54

**Comment by RDIL** [comment]
Interesting.  This is sad to know.  I just think it would be generally better, the less data we feed them.

**Comment by JesterOrNot** [comment]
I get it I recommend this browser extension so you can stay on top of GA
https://chrome.google.com/webstore/detail/wappalyzer/gppongmhjkpfnbhagpmjfkannfbllamg

**Comment by RDIL** [comment]
I already have privacy badger by the EFF which I'm comfortable.

**Comment by JesterOrNot** [comment]
ok cool

**Comment by jankeromnes** [comment]
Hi @RDIL and @JesterOrNot,

> I just noticed that Google analytics is active in workspaces, which I am certainly not comfortable with.
> 
> I can understand having GA on the landing page, but on the dashboard and in workspaces, that is something I am NOT ALRIGHT with.

Thanks for reporting this! I totally agree with you, and Google Analytics doesn't actually ship with workspaces, i.e. we already don't track workspaces at all.

I think the only way you can possibly get GA "inside" a workspace is if your workspace opens a website that uses GA, but that would be inside the preview iframe, and I don't think the GA script inside the iframe can know much about what you're doing in the parent frame -- but please correct me if I'm wrong!

**Comment by RDIL** [comment]
Not sure how this is, but its here on plain gitpod:
![Screenshot 2019-11-27 at 9 07 56 PM](https://user-images.githubusercontent.com/34555510/69771221-02cdec00-115a-11ea-8118-a341be8828f0.png)
![Screenshot 2019-11-27 at 9 07 01 PM](https://user-images.githubusercontent.com/34555510/69771227-06617300-115a-11ea-9321-ccaa47480145.png)

**Comment by jankeromnes** [comment]
Thanks. This is a bit worrying, I'll take a look.

**Comment by jankeromnes** [comment]
Ah, I think I know what's happening here. While workspaces should indeed _not_ be tracked by GA, I think the brief loading screen is.

This is probably why the browser thinks GA is loaded inside the workspace:

<img width="1552" alt="Screenshot 2019-11-28 at 09 07 11" src="https://user-images.githubusercontent.com/599268/69788487-efa13780-11be-11ea-95e8-e0482f04016a.png">

However, the `ga` object doesn't actually exist in the workspace page once loaded, so I don't think it can track anything:

<img width="1552" alt="Screenshot 2019-11-28 at 09 07 25" src="https://user-images.githubusercontent.com/599268/69788556-12cbe700-11bf-11ea-890f-a0cdf527932b.png">

On the other hand, in a tracked page like the Gitpod website, the `ga` object exists and is active:

<img width="1552" alt="Screenshot 2019-11-28 at 09 06 53" src="https://user-images.githubusercontent.com/599268/69788601-27a87a80-11bf-11ea-8a84-1e7051e7f9b7.png">

Still, since we don't want GA anywhere near workspaces, I think we should remove it from the loading screen to be extra safe. I'll try to find out if tracking the loading screen is 100% necessary for something, or if we can just remove it.

**Comment by RDIL** [comment]
Thank you @jankeromnes.  Please let me know once this is resolved :)

**Comment by RDIL** [comment]
Hey @jankeromnes, I just noticed a new deploy, (😃) does this fix it?

**Comment by jankeromnes** [comment]
Hi @RDIL, indeed, great catch! 😄 (Also, there are a few cool surprises in this deploy! We'll announce them soon.)

Unfortunately, I haven't had time to make sure GA is removed from the loading screen yet, so the problem may still be there. Sorry about that, I'll try to get to it as soon as possible.

**Comment by RDIL** [comment]
No worries.  Keep up the good work!

**Comment by JesterOrNot** [comment]
Hey, @jankeromnes, where do I find out about the latest changes now they used to be here https://www.gitpod.io/docs/80_release_notes/, is there a new place I should be looking?

**Comment by jankeromnes** [comment]
Closed too soon, sorry. This fix should get deployed by the end of the week.

**Comment by RDIL** [comment]
Got it, thanks.

**Comment by Kreyren** [comment]
>  I just noticed that Google analytics is active in workspaces, which I am certainly not comfortable with.

me neither, kudos to gitpod for valuating end-user privacy! <3

**Comment by svenefftinge** [comment]
deployed
