### ISSUE TITLE
Improve opening flow + docs for VS Code Desktop (many popups)

### ISSUE THREAD

**Issue by tobiasdiez** [gitpod-io/gitpod#9568]
When you start a workspace in desktop VS code, you have to 

1. Allow the redirect to desktop client
    1. https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#autolaunchprotocolsfromorigins
    1. https://chromeenterprise.google/policies/#AutoLaunchProtocolsFromOrigins
    1. https://admx.help/?Category=Chrome&Policy=Google.Policies.Chrome::AutoLaunchProtocolsFromOrigins
    1. MS Edge configuration: `[{"allowed_origins": [ "https://gitpod.io" ], "protocol": "vscode"}, {"allowed_origins": ["https://gitpod.io"], "protocol": "jetbrains-gateway"}]`
    1. https://support.google.com/chrome/a/answer/7517624?hl=en&ref_topic=9023246
1. Select the remote server platform (linux)
1. Accept the ssh fingerprint
1. Decide if you trust the contents of the remote repo

**Relates to:** 
- https://github.com/gitpod-io/gitpod/issues/8513
- https://github.com/gitpod-io/website/issues/2262
- https://github.com/gitpod-io/website/issues/1262
- https://github.com/gitpod-io/website/issues/2455

<details>
<summary>Original description</summary>

## Is your feature request related to a problem? Please describe

When you start a workspace in desktop VS code, you have to 
- Select the remote server platform (linux)
- Accept the ssh fingerprint
- Decide if you trust the contents of the remote repo

One has to do this for every new workspace, even for the same repo.

## Describe the behaviour you'd like

Make it possible to save the choices (per repo), so that one doesn't need to answer any questions when working on repos that one usually contributes too.

## Describe alternatives you've considered

Writing a script that automatically clicks the correct buttons.

## Additional context

Might be part of https://github.com/gitpod-io/gitpod/issues/8513

</details>

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/openvscode-server/pull/346

**Comment by loujaybee** [comment]
Going to now close this issue, here are a couple related docs: 

* [VS Code Desktop and SSH explained](https://www.gitpod.io/blog/vscode-desktop-ssh-updates)
* [How to optimise the VS Code Desktop opening flow](https://www.gitpod.io/docs/ides-and-editors/vscode#optimizing-vs-code-desktop)

1. SSH fingerprint is now optimised with SSH Gateway settings, we recommend setting up an SSH key, and setting `gitpod.remote.useLocalApp` to `false` in your VS Code Preferences so that you get the latest connection method. 
* [How to upload an SSH key to Gitpod](https://www.gitpod.io/docs/configure/ssh#upload-an-ssh-key-to-gitpod)
* [Connecting to VS Code via SSH Gateway method](https://www.gitpod.io/docs/ides-and-editors/vscode#connecting-to-vs-code-desktop-ssh)

2. The browser redirect will only need to be dismissed once going forward (not per workspace)
* https://github.com/gitpod-io/gitpod/pull/12082

3. How to optimise Workspace Trust is now documented
* [How to optimise Workspace Trust popup for VS Code](https://www.gitpod.io/docs/ides-and-editors/vscode#workspace-trust)

Have a go setting everything up @tobiasdiez and let us know if you have any feedback 😁
