### ISSUE TITLE
Feedback Issue: Bitbucket Server

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#9592]
### Objective

The aim of this issue is to gather feedback on our **Bitbucket Server** integration. 
Please add your feedback in comments below -- any feedback is welcome!

### More information
- [Docs](https://www.gitpod.io/docs/bitbucket-server-integration)

**Comment by peters-ben-0007** [comment]
Trying to configure bitbucket server integration. 
Was able to initiate activation, it asks me to login to BitBucket, then BitBucket asks for consent, all good. But when it finally redirects back to GitPod, it says "404 user not found". To diagnose, had to install self-hosted GitPod and inspect server logs to find the real error: 

`stdout F {"component":"server","severity":"DEBUG","time":"2022-08-22T04:50:19.546Z","message":"BitbucketServer GET https://bitbucket.example.com/rest/api/1.0/users/username@example.com - error 404 / User username@example.com does not exist.","loggedViaConsole":true}`

This is because my user SLUG in BitBucket is "username_example.com", not "username@example.com". There does not seem to be anywhere I can override BitBucket username in GitPod settings, so unable to get past this error :(
Not sure if the response from BitBucket server specifically includes the user's slug as something that can be inspected + used, otherwise some way to override this default assumption (that email id == bitbucket user id) is needed
