### ISSUE TITLE
Improve packaging + distribution of the local companion

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#9615]
Currently, the local companion is downloaded and installed as an executable, which can lead to security warnings. We need to ensure the app can be downloaded from trusted registries, and signed where necessary to ensure user trust and prevent security warnings or flagging by anti-virus software etc. 

https://developer.apple.com/documentation/notaryapi/submitting_software_for_notarization_over_the_web

**Comment by ajhalili2006** [comment]
For Windows and macOS: Go for the regular code-signing step with a trusted CA.

For Linux: Things might go a bit tricky, since each distro has its own packaging formats and way to sign packages. If Gitpod prefers to manage the package repo for Local Companion themselves and not use distro-specifics, maybe GPG + checksums on both monthly releases and nightly builds is enough on my opinion.
