### ISSUE TITLE
[ws-manager] If a prebuild's snapshot fails with "out of disk" it does not report "failed" (just empty "snapshot")

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#9710]
Corollary to: https://github.com/gitpod-io/gitpod/issues/9676

version: `2022.04.1` (self-hosted installation)

Instead of resulting in an status update of `"phase": 6, "conditions": { "failed": "some error" }`, ws-manager-bridge receives:
```
"phase": 6,
"conditions": {
    "failed": "",
    "timeout": "",
    "pullingImages": 0,
    "snapshot": "",
    "finalBackupComplete": 1,
    "deployed": 0,
    "networkNotReady": 0,
    "headlessTaskFailed": "",
    "stoppedByRequest": 0
}
```

**Comment by sagor999** [comment]
@geropl while trying to repro this case, I noticed an odd behaviour that I think is due to a fix for #9676 :
when prebuild has finished, and snapshot is being taken, prebuild will show up in dashboard in ERROR state. After snapshot was taken, it will get updated into READY state. But when I go into list of prebuilds, it still shows up there as in ERROR state.
