### ISSUE TITLE
Make terminal prompt user configurable

### ISSUE THREAD

**Issue by shawalli** [gitpod-io/gitpod#9739]
## Is your feature request related to a problem? Please describe
My immediate request is to have the timestamp included as part of the terminal prompt. Having a timestamp record of commands run helps to track numerous things, such as how long a command took to run, when it was run, etc.

However, I think it'd be great to build in some prompt configuration into .gitpod.yml somehow. Even if it began as basic on/off features, it'd be really nice to have.

## Describe the behaviour you'd like

Same as above.

## Describe alternatives you've considered

I tried hacking this by echoing a `PS1` value into the bashrc file as part of `tasks`, but couldn't seem to get it to work. I also really don't want to have a whole Dockerfile to maintain on my own just for a single environment variable.

**Comment by loujaybee** [comment]
You can edit or customize your shell using dotfiles support: https://www.gitpod.io/docs/config-dotfiles#dotfiles. 

I think this type of functionality is probably best distributed through existing package managers like: 

https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
https://github.com/oh-my-fish/oh-my-fish 

As it'll be hard to agree a standard convention for Gitpod, however a default (kumquat orange) Gitpod terminal theme could be a fun idea, to compliment the [existing default VS Code Theme](https://github.com/gitpod-io/openvscode-server/tree/gp-code/main/extensions/theme-defaults/themes) 😁 

Rather than directly baked into Gitpod itself. 

Also see: 
* https://dev.to/giannellitech/setting-the-default-terminal-in-vs-code-95c
* https://github.com/gitpod-io/website/issues/1955
