### ISSUE TITLE
[eks-guide] Reduce variance by using the CLB load balancer instead of the ALB load balancer in the EKS Guide

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#9751]
In our [EKS guide](https://github.com/gitpod-io/gitpod-eks-guide/), we currently use the ALB load balancer instead of the CLB load balancer. This was for historical reasons where we needed to do the TLS termination in the load balancer. However, our supported setup does the TLS termination in the proxy component. Also ALB breaks the SSH support (and thus the support for desktop IDEs).

To reduce variance and to remove friction for customers who want to use SSH support, we should change the guide to use the CLB load balancer instead the ALB load balancer. The EKS setup should work like the other setups and should not do TLS termination in the load balancer.

### See also
- https://gitpod.slack.com/archives/C01KLC56NP7/p1650893878521329 (internal)
- https://gitpod.slack.com/archives/C03A96H89V2/p1650619784264099?thread_ts=1649343349.358989&cid=C03A96H89V2 (internal)
- https://gitpod.slack.com/archives/C01LDA28WV6/p1651622583353039 (internal)
- https://gitpod.slack.com/archives/C020VCB0U5A/p1651508241759449 (internal)

**Comment by Pothulapati** [comment]
Yep, As you rightly said, We use a a ALB right now preventing us from doing SSH there.

I'll updathe repository to instead create a CLB so that this is fixed!

**Comment by mrzarquon** [comment]
It looks if we can move the SSH service to stand alone and configure it as loadbalancer, if one has an aws load balancer controller (not an ALB) properly configured, it should create the corresponding NLB: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/service/nlb/

This has the benefit of continuing to use an ALB for SSL traffic to proxy, because in some customer environments a publicly signed certificate (especially one with wildcards) may have strict lifecycle enforcement requirements, in AWS that would be provided by ACM and only AWS resources (ie, an ALB or NLB) can retrieve them.

**Comment by corneliusludmann** [comment]
Closing this because we handle this in the reference architecture and deprecate the guide repos soon.
