### ISSUE TITLE
Hide license type in admin dashboard when not applicable

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#9767]
### Problem to solve

In **[/admin/license](https://gitpod.io/admin/license)** there are some edge cases where license type is not applicable.

Cc @nandajavarma @MrSimonEmms because https://github.com/gitpod-io/gitpod/issues/9763

| Screenshot from the license page in an instance |
|-|
| <img width="1021" alt="Frame 1059" src="https://user-images.githubusercontent.com/120486/166717927-8d5ed49e-bf7e-47ee-ba3e-af21d466f811.png"> |

### Proposal

When the license information is not applicable, let's hide the key-value element altogether. 

Since we're here, we could also:
- :a: keep the bottom card link fixed a the bottom of the card
- ~~:b: include some left margin (`ml-4`) on the license status icon for better visual balance.~~ (being addressed in https://github.com/gitpod-io/gitpod/pull/9823)

**Comment by MrSimonEmms** [comment]
It's my understanding that there will always be a license, it's just that it may not be a license that the user has uploaded. It may be the "default license" (<= 10 users) or the "fallback license" (> 10 users)

If you're on the default license, it'll look similar to as it does in the screenshot. If it's the fallback, it'll only show the admin dashboard as an available feature and also show unlimited users.

**Comment by nandajavarma** [comment]
Just to add to the discussion, in the case of `gitpod.io` and `gitpod-staging.io`, I am deliberately avoiding to set the value of the licenseType https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/admin/License.tsx#L27
I am currently of the opinion that this can be removed. Especially since is a rather light operation on the server. At the time of adding the change, I was trying to mimic what was done in the [PR that added the settings page.](https://github.com/gitpod-io/gitpod/pull/7732)
