### ISSUE TITLE
[self-hosted] Adding Custom CA fails for GKE `update-containerd-certificates` crashes

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#9801]
Using self-signed certs for Gitpod installations on GKE is not supported yet. However, it should be possible to add a custom CA when e.g. GitLab is uses a self-signed cert and Gitpod needs to trust this cert.

Unfortunately, currently `update-containerd-certificates` crashes on GKE.

[see also (internal)](https://gitpod.slack.com/archives/C01KLC56NP7/p1651760805567009?thread_ts=1651485800.580789&cid=C01KLC56NP7)

**Comment by Pothulapati** [comment]
:wave:  Hmm, So, The issue is that GKE’s `update-containred-certificates` fails causing initialisation errors! Even after initialisation, The image pulls may not work (as `registry-facade` is self-signed and the containerd doesn’t trust the cert) but that can be fixed by manually loading certs onto nodes (by ssh’ing).

Simon did test this out on GKE, and same with me. So, I’m guessing it might be some configuration in their cluster? As the `update-containerd-certificates` does some host level stuff and they could have some way of stopping apps from doing that.

On our side, We could either
- Update `update-containerd-ceritificates` to not fail, but just put out a warning if it did not succeed.
- Have a config flag to disable the `initContainer` itself? 🤔
