### ISSUE TITLE
Custom GUI?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#981]
Is there some way to get custom GUI on gitpod? alike changing the overall look and where the buttons and which features are used?

### Making the gui more efficient for the git process:
To elaborate this i like the way Atom handles the git: 
<img width="222" alt="image" src="https://user-images.githubusercontent.com/11302521/70396244-6df3aa00-1a07-11ea-8b9a-48a2d72e6615.png">

Where
- 1 = Commits
- 2 = Stages
- 3 = Commits message
- 4 = Commit history

This is currently done on gitpod using multiple submenus which is not as effective and i would like to have a way to customize the windows since this can be optimized further depending on the workflow.

### Graphical customization
I would also like to customize the GUI for the project colors, etc.. alike custom theme, icons, etc..

**Comment by JesterOrNot** [comment]
A this is probably an issue for theia Gitpod's IDE but here is a screencast demonstrating it
https://www.loom.com/share/1d4ec9abf91843d387ad6cf0df502ff9

**Comment by Kreyren** [comment]
> this is probably an issue for theia Gitpod's IDE

Theia doesn't accept github issues afaik? And i wasn't able to get the answer on spectrum chat.

Or should i ask somewhere else? I was asking on IRC and they recommended me to make an issue here.

> but here is a screencast demonstrating it
https://www.loom.com/share/1d4ec9abf91843d387ad6cf0df502ff9

My fault didn't know that moving GUI is possible -> Remove the two examples mensioning this in OP and thanks for explanation.

How do i save the configuration repository-wide?

---
 
I'm still unable to customize the git windows as presented in OP

Graphical customization still seems as not possible per repository?

**Comment by jankeromnes** [comment]
Hi @Kreyren, many thanks for filing this issue!

> This is currently done on gitpod using multiple submenus which is not as effective and i would like to have a way to customize the windows since this can be optimized further depending on the workflow.

Thanks for the feedback! In general, we try to follow VS Code on UX matters, because we consider that their UX generally works well for most developers and is also highly popular.

However, we also want to allow developers to customize their own experience in Theia and Gitpod as they see fit (e.g. aligning the commit UI with Atom like in your example).

Maybe one way to do that is to implement a VS Code extension (you can install these in Gitpod, and I believe that they can change the UI in many ways that could be useful to you).

> I would also like to customize the GUI for the project colors, etc.. alike custom theme, icons, etc.

A big part of customizing colors, icons, etc will be the support of the theming API for VS Code extensions, tracked in https://github.com/eclipse-theia/theia/issues/4831. This will allow you to install extensions like `vscode-icons`, or write your own.

I also found https://github.com/eclipse-theia/theia/issues/6040 which wants to customize this via preferences.

> Theia doesn't accept github issues afaik?

Theia is open source, and does accept and appreciate issues :) https://github.com/eclipse-theia/theia/issues

> How do i save the configuration repository-wide?

For now, even though you can resize and move IDE panels pretty much all over the place (thanks to PhosphorJS), I don't think you can persist these changes into your repository yet (however, maybe we persist it per workspace, e.g. if you stop and restart a workspace, but I'm not sure).

I'd encourage you to either try writing your customizations as a VS Code extension (can be committed into your repository), or open a dedicated feature request issue for persisting the PhosphorJS layout into your repository.

P.S. I do realize the irony of suggesting you make Gitpod look less like VS Code with help of... VS Code extensions. Sorry about that!

**Comment by JesterOrNot** [comment]
https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
This one could help with the git stuff

**Comment by Kreyren** [comment]
> Theia is open source, and does accept and appreciate issues :) https://github.com/eclipse-theia/theia/issues

My fault i though that theia on gitpod is standalone project (theia repository in gitpod doesn't have issues enabled), thanks for info

>A big part of customizing colors, icons, etc will be the support of the theming API for VS Code extensions, tracked in eclipse-theia/theia#4831. This will allow you to install extensions like vscode-icons, or write your own.
> I also found eclipse-theia/theia#6040 which wants to customize this via preferences.

Using preferences or some kind of config file would be prefered (it feels to be more efficient to manage compare to VS-code) in comparison to VS-code extension.

> ...

Thanks for all info tracking the preferences and will investigate further. I guess this can be closed as `notourbug` now?

**Comment by JesterOrNot** [comment]
@Kreyren this should also help
https://www.gitpod.io/docs/44_config_start_tasks/
