### ISSUE TITLE
Change wording in KOTS Admin Install Console Welcome Page

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#9820]
## Is your feature request related to a problem? Please describe
Currently, the first thing you see when opening up the kots admin console during installation is "welcome to gitpod":
<img width="642" alt="Screenshot 2022-05-06 at 12 20 08" src="https://user-images.githubusercontent.com/22516873/167113896-cf2cd3f4-16c5-4426-a734-c8f7389c6f0b.png">

This is confusing, because this is not Gitpod per se, but rather the installation UI used to install Gitpod. We should make this more clear. 

## Describe the behaviour you'd like
Instead of Welcome to Gitpod, we should say:
### "Welcome to the Gitpod Admin Console"  
"Here you can install and configure your Gitpod Installation. Please type in your password to proceed."

## Additional context
Internal discussion [here](https://gitpod.slack.com/archives/C01KGM9AW4W/p1651775983255399?thread_ts=1651764197.241229&cid=C01KGM9AW4W).

**Comment by MrSimonEmms** [comment]
Yeah, what @corneliusludmann says I'm afraid - this is controlled entirely by Replicated. There's even things like, because we only have one logo we can use, it looks a bit rubbish in the favicon if we make it look good for the logo.

I've suggested a feature request with Replicated that allows us to style these pages. As far as I know, there's not been one raised but maybe ask them to do that in our join Slack channel

**Comment by MrSimonEmms** [comment]
@lucasvaltl I've raised a ticket with Replicated to address this

**Comment by lucasvaltl** [comment]
Closing for now - outside of our control.
