### ISSUE TITLE
Wording on new Git integration page incorrect

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#9873]
### Bug description

The "new Git integration" page says "configure a GitLab or GitHub instance", but Bitbucket is now available.

![image](https://user-images.githubusercontent.com/275848/167439687-b105a171-1c88-4b80-9624-a763d6cee96a.png)

### Steps to reproduce

Go to a fresh installation with no integrations configured

### Expected behavior

Should say "configure a GitLab, GitHub or Bitbucket instance"

**Comment by gtsiolis** [comment]
This seems to be different from what is visible in production in `/integrations`. In case the same options are available also in self hosted we could probably use the same copy here.

Cc @AlexTugarev @jldec because https://github.com/gitpod-io/gitpod/pull/9135.

| Integrations > New Git Integration |
|-|
| <img width="494" alt="Screenshot 2022-05-09 at 7 37 00 PM" src="https://user-images.githubusercontent.com/120486/167456642-a24e704a-ce17-45cb-82a1-3b5668808785.png"> |

**Comment by jldec** [comment]
@MrSimonEmms is this just a case of the self-hosted release being behind the commits on gitpod main?
If so, we don't need this issue right?

**Comment by gtsiolis** [comment]
@jldec I had the same thought but it seems we still use the old copy here in the setup step. Cc @AlexTugarev 

https://github.com/gitpod-io/gitpod/blob/b5175874e7e685f2a9bf9720743b3450f403ffe8/components/dashboard/src/Setup.tsx#L36

**Comment by MrSimonEmms** [comment]
@jldec seemingly not. This is from the September release candidate of Self-Hosted 
![image](https://user-images.githubusercontent.com/275848/193224670-6872e2c9-f917-4d3f-a61e-aa6455e8ce19.png)

**Comment by jldec** [comment]
Scheduled
