### ISSUE TITLE
Why starting workspace is so long ?

### ISSUE THREAD

**Issue by isontheline** [gitpod-io/gitpod#993]
**Describe the bug**
Everytime I launch a workspace I need to wait 4 to 6 minutes in order to have my workspace alive :(

**To Reproduce**
Create a workspace, wait at least one week and then try to launch it.

**Expected behavior**
I expect my workspace launched in less than 60 seconds. If greater than 60 seconds I prefer to start my old Eclipse IDE instead.
This delay is always, even if the workspace has been paused one hour ago.

**Additional Information**
![solong](https://user-images.githubusercontent.com/44212923/70655845-3ed47700-1c59-11ea-8e78-7cde50051c21.png)

Does this load is normal every time I start my workspace ?
![solong2](https://user-images.githubusercontent.com/44212923/70655858-4431c180-1c59-11ea-8e7d-9fcbbe43432a.png)

**Comment by Kreyren** [comment]
**Disclaimer:** i'm not a gitpod staff, but i think that i know what is causing this.

On my end it seems to take a long time if `Dockerfile.gitpod` is used with an instructions that configures additional packages or other configuration that is expected to be present as addition to the used docker image since it seems that gitpod configures these on runtime.

I believe that this can be optimized by providing a custom Dockerfile in `Dockerfile.gitpod` as:
```docker
FROM gitpod/workspace-full:latest
```

GitPod has documentation on submiting these images here: https://www.gitpod.io/docs/42_config_docker/#creating-docker-images-for-gitpod

**Comment by isontheline** [comment]
@Kreyren Thanks for your tip :) 
But I don't use a Dockerfile.gitpod file. The workspace is as simple as possible.

**Comment by geropl** [comment]
@isontheline If you tried yesterday evening: We had some "users" abusing Gitpod to mine their cryptocurrency with a new tool. It took us some time to detect, implement detection routines and deploy those.

**Comment by isontheline** [comment]
@geropl Ok I will try again tonight and will let you know
Thank you !

**Comment by isontheline** [comment]
@geropl It's better than yesterday :
![Capture d’écran 2019-12-12 à 20 27 08](https://user-images.githubusercontent.com/44212923/70742573-25e1c980-1d1e-11ea-8352-b2bb05bdc04a.png)

I'm closing this issue. 
Thanks for your work Gitpod!
