### ISSUE TITLE
Menu item in VSCode to stop workspace and start a new one aka rebuild workspace

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#9956]
## Describe the behaviour you'd like

<img width="514" alt="Screen Shot 2022-05-12 at 4 08 42 pm" src="https://user-images.githubusercontent.com/127353/168003290-e2ca40cd-5332-4ff1-b330-2b98ec2414c2.png">

From: https://twitter.com/hrittikhere/status/1524630369575702528?s=20&t=jmOoNX6wzNVo0bJV93clDQ

## Additional

- [Internal discussion](https://gitpod.slack.com/archives/C01KGM9DVRC/p1652335285017579).
- https://github.com/gitpod-io/gitpod/issues/7671

**Comment by hrittikhere** [comment]
So, to understand this issue, we need to understand where I am coming from first. I am using codespace since Day 2 and got introduced to GitPod much later. I like gitpod for the `.gitpod` yaml and the containers are a bit more robust if compared to codespaces. 

One of the good features of codespaces is allowing for rebuilding containers with a click:


![image](https://user-images.githubusercontent.com/67012359/168011851-47241aec-bb48-4b9b-a11b-25f24034bbc6.png)

Now, we can do that in GitPod, but then I think keeping two containers will be a waste of resources at the scale you operate and I also like to keep my portal clean. I am lazy enough to go delete the containers. I will be waiting for 90 days for auto delete for unpinned containers to kick in.  

Some folks might need two containers but for most, rebuilding one when things go haywire is the best shot. 

Haywire? A few instances for me when I needed to rebuild a container were:
> 1. Messing with network configuration and mess things up. Now I can correct things or build a new one easily.
> 2. Dependency issues where I install a lot of packages to test my code and new stuff but I can send all of them to requirements. Now I can remove all of them manually or can build a new one and move forward with the one I need.
> 3. Sometimes things break. I am not sure how but there's some issue with installation or configuration. Creating one without leaving the tab is fast and effortless. 

![image](https://user-images.githubusercontent.com/67012359/168013842-6967a0b0-aeb9-4212-a3ba-b187d56c60ea.png)

I can't think of anything more now. Options like recreating a container without leaving the tab will be helpful.

What do you think?
