### ISSUE TITLE
Doesn't work as blog explains

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/gitpod#999]
>As a last resort, Gitpod analyzes the repository and derives a suitable configuration from there. For instance, if the repository contains a yarn.lock file it will automatically run yarn install in the beginning.

[Gitpod blog](https://www.gitpod.io/blog/github-flow/)

This doesn't work.
Something is wrong.Doesn't work as blog explains

**Comment by JesterOrNot** [comment]
What is wrong? Can you explain

**Comment by mouse484** [comment]
>a yarn.lock file it will automatically run yarn install

It may be different from the problem.
Not really working, auto install.

**Comment by svenefftinge** [comment]
We have that for go projects, but not for Yarn. Generally, I'm a bit concerned that doing the wrong thing would be worse than doing nothing at all. 
Instead of doing this automatically, I'd prefer to assist users with creating a config. In that case we can derive a good suggestions and propose that in a .gitpod.yml. So it is proposed but the user can still adjust it.

**Comment by mouse484** [comment]
I think it's right

Automation is convenient, but there are problems.
For yarn/npm, node.js version, etc.
